### ISSUE TITLE
One-to-Many relationships require hasMany to be explicitly set?

### ISSUE THREAD

**Issue by Aaronfischer** [samselikoff/ember-cli-mirage#1001]
I'm currently using 0.3.0beta.4

This explains what I'm finding:
https://ember-twiddle.com/3d9f8cb96e7d2f81c30443a4dfee4be4?openFiles=mirage.fixtures.authors.js%2C
Basically, comment out the `bookIds: [...],` line and the hasMany relationships will not be returned.

In the past, I could setup only the belongsTo side of the relationship and Mirage would implicitly know and properly setup the hasMany on the reverse side. This does not seem to be the case anymore with 0.3.0. Just checking if this is a bug, this implicit behavior is tucked away somewhere in an option or if this is intended?

**Comment by samselikoff** [comment]
That is correct, you read more about why here: http://www.ember-cli-mirage.com/blog/2017/01/09/0-3-0-beta-series/.

I use mostly factories and not fixtures, but I can see why it's annoying if you're relying heavily on fixtures to seed your test data. Do you use factories? If not why not? Factories make this easier because they take care of a lot of the key management for you.

**Comment by Aaronfischer** [comment]
@samselikoff I use both pretty heavily. Factories for the bulk of data and fixtures for very specific (if I want to know the ID and exactly what relationships it may have). I've also found fixtures work well for the authenticated user/account/etc.

Thanks for confirming!

**Comment by Aaronfischer** [comment]
@samselikoff Can you think of any better way for Mirage to automatically setup the fixtures' hasMany side of the relationship as factories setup the belongsTo?

ex. I have 4 categories created through Fixtures for the root level categories. Then I have Factories create the remaining 30 categories as children of those root level categories.
So in my factories I'm setting `rootId: faker.list.cycle(1, 2, 3, 4),`.

However, the inverse hasMany on the root level categories are not setup since they're fixture data. What did work is setup the factories `afterCreate()`, find the root level category, and concat its childIds, then save the root record. This is, unfortunately painfully slow because I have 30+ records. 
(App previously rendered in 2 secs to now 8 secs.)

Do you have any ideas? Is there a better way to setup this flow for Mirage to handle more of the heavy lifting automatically? or is `afterCreate()` really the best way for my situation?

**Comment by samselikoff** [comment]
What about something like this in your scenario:

```js
server.loadFixtures(); // creates 4 categories

let categories = server.schema.categories.all();

categories.models.forEach(root => {
  server.create('category', { root });
});
```

**Comment by samselikoff** [comment]
You could also set up a trait on your category factory so you can do

```js
server.create('category', 'withChildren');
```

which would look something like

```js
withChildren: trait({
  afterCreate(root, server) {
    server.createList(10, { root });
  }
})
```

**Comment by Aaronfischer** [comment]
@samselikoff Thanks for the suggestions! I'll try out the first example, hoping that maybe avoiding `afterCreate` may speed up render times.

**Comment by samselikoff** [comment]
Also there's potentially some changes we can make to `db` to speed up perf

**Comment by Aaronfischer** [comment]
@samselikoff What kind of changes can we make to speed up the db?
I'm seeing my testing suite go from 7mins to 30mins. 😅 

30minutes when I use the `afterCreate()`

**Comment by samselikoff** [comment]
Oof, seems weird... There's definitely some ideas but this seems strange.

One issue is `db.users` uses JSON.stringify to copy the users db table each time its accessed. This was to give a nice API and to prevent inadvertent mutation. We can revisit this.

How much data are you loading?

**Comment by Aaronfischer** [comment]
Well data that changed the tests, 30 records generated via factory and 10 fixtures.

**Comment by samselikoff** [comment]
Any chance you could provide a reduced test case via a repo or the [test boilerplate twiddle](https://ember-twiddle.com/e75d1a5d602a250c295987c23f40d7a4)?

**Comment by Aaronfischer** [comment]
Hey @samselikoff Sorry for the delay, had to get some other things pushed out before this.

https://github.com/Aaronfischer/Mirage---Slow---Reduced-Test-Case

So this is a VERY reduced case where adding `afterCreate()` to a factory increases the testing time anywhere from 3x-5x. (And I'm seeing this kind of margin stand true with 200+ tests across 10+ different models)

I made a simple test and noted if you comment out the afterCreate and re-run the test you'll see the speed jump: https://github.com/Aaronfischer/Mirage---Slow---Reduced-Test-Case/blob/master/tests/acceptance/index-test.js

**Comment by hbrysiewicz** [comment]
There was some perf work done in https://github.com/samselikoff/ember-cli-mirage/pull/1254. Please open a new issue if you’re still having perf problems
