### ISSUE TITLE
Reflexive hasMany inverse bug

### ISSUE THREAD

**Issue by samselikoff** [samselikoff/ember-cli-mirage#1009]
HasMany reflexive inverse relationships are buggy, it most likely has to do with the `inverse()` method on association. I think [this line](https://github.com/samselikoff/ember-cli-mirage/blob/one-way-associations/addon/orm/associations/association.js#L49) is wrong - originally I assumed a reflexive relationship that had an inverse was self-referencing, but it can refer to a separate named relationship. (Even still, the self-referencing is buggy, too).

Here's a twiddle demonstrating some issues:

https://ember-twiddle.com/c81e60b8c1ff02c4b69e8503fa96858e?openFiles=mirage.models.objective.js%2C

**Comment by samselikoff** [comment]
fb941d03d468040f91a544af29b6cd21816130df closes

**Comment by Brandon-Wolff** [comment]
[This line](https://github.com/samselikoff/ember-cli-mirage/blob/one-way-associations/addon/orm/associations/association.js#L49) is still causing me issues in the 0.3.0 release. It seems to prevent a reflexive relationship from having an inverse that is a different key. [This twiddle](https://ember-twiddle.com/28d17974f31791799c489bc13d590192?openFiles=tests.test-helper.js%2C) shows the issue. The three children should all have a parentId of 1, but instead the parent's ID is put in the childIds array, despite having the inverses explicitly defined in the mirage model.
