### ISSUE TITLE
Mirage automatically sorts data: Bug or feature

### ISSUE THREAD

**Issue by rldleblanc** [samselikoff/ember-cli-mirage#1011]
I created a component that displays a list and if you specify 'sortBy="somefield"' it sorts the list. When sortBy is not specified I found that the list was still sorted. Looking at the response from mirage, the data is sorted from what is specified in the fixture file. I created a [twiddle](https://ember-twiddle.com/d40f3e7f793b7dfdbebfe182b6ce6cf3?openFiles=mirage.fixtures.category.js%2C) that shows the issue.

Is this a bug or feature? I would like to be able preform a unit test against my component to know if it is sorting properly or the original order of the list in the fixture.

**Comment by samselikoff** [comment]
We do sort by `id` by default before inserting records, since Mirage's database tries to replicate a true database as much as possible.

In your twiddle example you're using strings as ids. Typically these strings would be fields on the record, and the `id` would be an autoincrement integer. The strings look more like something like a `slug`, and if you were to change it you'd get the expected unsorted behavior. Does that solve your problem?

**Comment by samselikoff** [comment]
I know this is a super late reply and this question is old, sorry about that. I'll go ahead and close this for now, but please drop a message here if you're still stuck and we can work through it!

**Comment by rldleblanc** [comment]
Thanks for the reply. I haven't worked on this pet project in a while. Since I wanted something more descriptive in the URL, and an auto incrementing int and a unique slug would be redundant, I just decided to omit the int and use the slug as the id.

It was more of a question of behavior and if it was expected, which it sounds like it is. I can do something in the unittest to test sort behavior now that I know.

Is there any downside to using the slug as the id instead of an int in Ember.js?

**Comment by samselikoff** [comment]
Understood + you're welcome :)

There's no downside from Ember's perspective, but a traditional server like Rails would recommend using auto-incremening integers as your ID fields, and using a separate field for slugs. Few reasons:

- slugs can change, but database ids never should change
- what if you delete `my-slug` but then want to re-insert it? many database systems prevent ever inserting records with ids that have already been used

In general a slug is different from an id (even if it happens to be a unique field), and over time the consensus has been to let databases use completely meaningless auto-incrementing integers for the id field.

**Comment by rldleblanc** [comment]
Makes sense. Thanks for taking the time to answer my questions.
