### ISSUE TITLE
Mirage (in pass-through) causes missing id error in Ember

### ISSUE THREAD

**Issue by Redsandro** [samselikoff/ember-cli-mirage#1012]
One of my pages loads a model like so:

```
this.store.findAll('software/category', {include: 'featured', reload: false, backgroundReload: false});
```

The app works fine. However, in development mode, when I have mirage in the chain, in pass-through mode, it causes this error:

```
Preparing to transition from 'software/software' to 'software.index'
server.js:70 Passthrough request: GET http://www.windowsremix.dev/api/v2/software/category?include=featured
ember.debug.js:30610 Error while processing route: software.index Assertion Failed: You must include an 'id' for software/category in an object passed to 'push' Error: Assertion Failed: You must include an 'id' for software/category in an object passed to 'push'
    at EmberError (http://www.windowsremix.dev/assets/vendor.js:29811:21)
    at assert (http://www.windowsremix.dev/assets/vendor.js:16841:13)
    at Object.assert (http://www.windowsremix.dev/assets/vendor.js:29623:34)
    at assert (http://www.windowsremix.dev/assets/vendor.js:159524:37)
    at Class._pushInternalModel (http://www.windowsremix.dev/assets/vendor.js:168702:41)
    at Class.push (http://www.windowsremix.dev/assets/vendor.js:168678:36)
    at http://www.windowsremix.dev/assets/vendor.js:169405:15
    at Backburner.run (http://www.windowsremix.dev/assets/vendor.js:10420:25)
    at Class._adapterRun (http://www.windowsremix.dev/assets/vendor.js:168927:31)
    at http://www.windowsremix.dev/assets/vendor.js:169402:13
```

Any idea what's going on here? Tried `0.2.4` and `0.2.5`. Not the latest version because I require Ember-cli 2.7 at the moment.

`mirage/config.js`

```
this.urlPrefix = 'http://www.windowsremix.dev';
this.namespace = 'api/v2';
this.get('unrelated/path', someFunc);
this.passthrough();
```

**Comment by yurygnutov** [comment]
Have same issue. And no response from team so far 😞 
@Redsandro did you find any workaround though?

**Comment by Redsandro** [comment]
@yurygnutov I'm sorry, nope. 

I can imagine the team doesn't want to spend time on someone elses problem until they have a complete functioning testcase on something like [ember-twiddle](https://ember-twiddle.com) before they wish to even look into this. However, some words would be nice.

For me the issue has expired and I have since moved on. It's been half a year and I don't recognize myself in the mirror anymore. Since this issue is recent for you, perhaps you can create a twiddle that demonstrates the problem and see if @ignatius-j can take a look at it.

**Comment by samselikoff** [comment]
I apologize for not responding to this!

I'll go ahead and close this issue for now since it's quite old, but if you’re still having trouble, please ping me here or on slack @samselikoff and I will reopen + discuss.
