### ISSUE TITLE
InvalidStateError on IE 11 when changing response type

### ISSUE THREAD

**Issue by pawepaw** [samselikoff/ember-cli-mirage#1017]
Hello,

I have defined route as passthrough. On ie 11 when i fire action and this route is called i got error invalidStateError when it tries to set responseType. I've also created issue on pretender js repo because it breakes there (https://github.com/pretenderjs/pretender/issues/196)

Check microsoft bug report: https://connect.microsoft.com/IE/feedback/details/795580/ie11-xmlhttprequest-incorrectly-throws-invalidstateerror-when-setting-responsetype

Maybe you could do some workaround and fix it?

**Comment by samselikoff** [comment]
If https://github.com/pretenderjs/pretender/pull/197 gets merged would that fix this?

**Comment by pawepaw** [comment]
yap i created pr and wrote in comment that it fixes it.

**Comment by samselikoff** [comment]
Believe this was fixed upstream in Pretender.

**Comment by pawepaw** [comment]
yes, they've already merged my pr.
