### ISSUE TITLE
Fresh install does not work with ember-cli beta 2.12

### ISSUE THREAD

**Issue by topaxi** [samselikoff/ember-cli-mirage#1019]
Steps to reproduce:
```bash
$ ember new mirage-test
$ ember install ember-cli-mirage
$ ember s
```

Dies with:
```
Error: Could not find module `lodash/camelCase` imported from `ember-cli-mirage/utils/read-modules`
```

Using:
```bash
$ ember --version
ember-cli: 2.12.0-beta.1
node: 7.5.0
```

Works with ember-cli-mirage version 0.2.5

**Comment by samselikoff** [comment]
Thanks for reporting this.

Looks like we currently have `ember-lodash` in our deps and `lodash` in our devDeps. I'm wondering if this is necessary...

Anyways, I imagine this has to do with `ember-lodash`. Could you investigate this a bit? Maybe try installing `ember-lodash` in a new 2.12 app and seeing if you can import `camelCase` in a module somewhere.

**Comment by jakeleboeuf** [comment]
Same story for me- @topaxi did you find any resolution here?

**Comment by mfazekas** [comment]
This should have fixed in https://github.com/mike-north/ember-lodash/pull/93 
It should be working with `2.12.0-beta.2` and ember-lodash `v4.17.1`

**Comment by jakeleboeuf** [comment]
@mfazekas but it's not ¯\_(ツ)_/¯

**Comment by mfazekas** [comment]
@jakeleboeuf can you double check the version of your `ember-lodash, version of your `ember-cli`

```sh
cat ./node_modules/ember-lodash/package.json | grep version
cat ./node_modules/ember-cli/package.json  | grep version
```

Hm it looks like `ember-cli@2.12.0-beta.2` is not yet released.

As a workaround you can try adding `"ember-lodash": "github:mfazekas/ember-lodash#ember-212-beta1-fix",` to your `package.json`/`devDependencies`

see
https://github.com/mfazekas/fastboot-mirage-test/blob/master/package.json#L29

**Comment by jakeleboeuf** [comment]
Ahhh, that did the trick. I was confirming `ember@2.12.0-beta.2`.

`ember-cli` makes more sense ;)

**Comment by jakeleboeuf** [comment]
Thanks @mfazekas!

**Comment by samselikoff** [comment]
Fixed with beta.2.
