### ISSUE TITLE
Returning an error 401 from oauth2 request

### ISSUE THREAD

**Issue by kgish** [samselikoff/ember-cli-mirage#102]
How can return errors from a `this.post('/token', function(db, request){...})` ?

For example, I want to check the username and password and return a 401 if they are invalid.

**Comment by samselikoff** [comment]
You could overwrite it in a test

```js
test("An error message shows when the server responds with a 401", function() {
  server.post('/token', { error: 'invalid credentials' }, 404);

  visit('/');
  // submit form

  andThen(function() {
    ok( find('.error').text().match('Invalid credentials. Try again?') );
  });
});
```

or write it directly in the route:

```js
// mirage/config.js
import Mirage from 'ember-cli-mirage';

export default function() {

  this.post('/token', function(db, request) {
    var data = JSON.parse(request.requestBody);
    
    if (data.username == 'bob' && data.password === 123) {
      return {message: 'success'};
    } else {
      return new Mirage.Response(401, {some: 'header'}, {message: 'invalid credentials'});
    }
  });

}
```

**Comment by kgish** [comment]
Thanks, however for some reason I am getting the following an exception:
```
Mirage: Your custom function handler for the url /api/token threw an error: undefined \
    is not a function TypeError: undefined is not a function
```
When I call:
```
return new Mirage.Response(401, {some: 'header'}, {message: 'invalid credentials'});
```
And yes, I included the following at the top of the file:
```
import Mirage from 'ember-cli-mirage';
```
Could it be that I should be calling a different method than `Response` ?

**Comment by kgish** [comment]
Actually, while looking through the code I couldn't find an easy way to pass back errors, but perhaps I am missing something obvious.

**Comment by samselikoff** [comment]
Are you on 0.26?

**Comment by kgish** [comment]
I just followed the installation instructions and ran `ember install ember-cli-mirage`

In my `package.json` file it tells me `0.0.24`

Should I change that to `0.0.26` and rerun `npm install` ?

**Comment by samselikoff** [comment]
What version of Ember CLI? You can just change the number in package.json

**Comment by kgish** [comment]
I have version `0.2.3` of `ember-cli` which I believe is the latest version.

Will try bumping up `ember-cli-mirage` to version `0.0.26` and see what happens.

**Comment by kgish** [comment]
Yeps, that did the trick, thanks!
```
npm install --save-dev ember-cli-mirage@0.0.24
```
Wonder why `ember install ember-cli-mirage` doesn't work.
