### ISSUE TITLE
GET route with include query parameter requires extra work

### ISSUE THREAD

**Issue by jonblack** [samselikoff/ember-cli-mirage#1022]
I have two models: `User` and `FriendRequest`:

```
// user
import { Model, hasMany } from 'ember-cli-mirage';
export default Model.extend({
  recvFriendRequests: hasMany('friend-request', { inverse: 'receiver' }),
  sentFriendRequests: hasMany('friend-request', { inverse: 'initiator' }),
});

// friend-request
import { Model, belongsTo } from 'ember-cli-mirage';
export default Model.extend({
  initiator: belongsTo('user'),
  receiver: belongsTo('user')
});
```

In my Ember application I want to side-load the `initiator` and `receiver` in the `FriendRequest` model, which I do with the following:

```
  model() {
    let currentUserId = this.get('sessionUser.user.id');

    return RSVP.hash({
      sent: this.store.query('friend-request', {
        initiatorId: currentUserId,
        status: 'new',
        include: 'initiator,receiver'
      }),
      received: this.store.query('friend-request', {
        receiverId: currentUserId,
        status: 'new',
        include: 'initiator,receiver'
      })
    });
  },
```

This results in the following request to the backend/mirage:

    Mirage: [200] GET /friend-requests?include=initiator%2Creceiver&initiatorId=1&status=new

Because I need to filter based on the query parameters, I have to implement my own mirage route, and it's not obvious at first what you need to do.

In the shorthand route, the `include` query parameter is handled automatically. When you write a custom route and pass the query parameters to the `where` method, `include` "gets in the way", so the query params need to be copied so that `include` can be removed:

```
  this.get('/friend-requests', function(schema, request) {
    let qp = JSON.parse(JSON.stringify(request.queryParams));
    delete qp['include'];
    return schema.friendRequests.where(qp);
  });
```

I admit that it makes sense that you have to remove `include` from the query params when passing them directly to `where`, but I also have the feeling this should just sort of work in some way.

Perhaps what I expect is a shorthand to handle the query parameters automatically:

**shorthand**

```
this.get('/friend-requests', { filter: true });
```

**equivalent to**

```
  this.get('/friend-requests', function(schema, request) {
    let qp = JSON.parse(JSON.stringify(request.queryParams));
    delete qp['include'];
    return schema.friendRequests.where(qp);
  });
```

Or perhaps the `include` parameter should set some state on the serializer and be removed before the route handler is called, if that's at all possible (I'm not familiar with the ember-cli-mirage code).

Just thinking out loud :)

**I'm running 0.3.0-beta.5**

**Comment by samselikoff** [comment]
Glad you figured out how to get it working. Yah there are a lot of different use cases so its hard to get the shorthands to cover everything. I think adding filtering functionality is definitely reasonable, we have a note about it somewhere in the Roadmap project.

Maybe once I finish this round of changes and release 0-3 I'll reach out to you in case you want to help with that feature.

**Comment by jonblack** [comment]
Yeah I saw the roadmap issue. Happy to help out with this so please get in touch when you're ready.

I was thinking that this depends on the serializer being used. I'm actually using the JSON API serializer, and since the spec recommends a `filter` query param, a better work around is (not tested):

```
this.get('/friend-requests', function(schema, request) {
  return schema.friendRequests.where(request.queryParams.filter);
});
```

This is a lot nicer since we don't need to delete anything. Of course, it's specific to JSON API. I suppose the `coalesce` option is also meant for JSON API, so maybe it doesn't matter.

**Comment by samselikoff** [comment]
Closing this as the filtering feature request is in the Canny board.
