### ISSUE TITLE
[SUGGESTION] split config.js into several enpoints

### ISSUE THREAD

**Issue by yratanov** [samselikoff/ember-cli-mirage#1027]
Hello,

On one of my projects we have thousands and thousands lines in `config.js` file. Basically everything there are endpoints. I know, we can split it as we want to, but I think in Ember we love conventions? :)

I suggest to add
-  `mirage/endpoints` and include all files inside of it automatically, by calling as function with server as param (same way as we run `config.js`). Possible name convention: `mirage/endpoints/users.js` for defining routes like `GET /users, POST /users`, etc.
- `mirage/helpers` as a place for common functions that are often used in endpoint definitions (like pagination, filtering, etc).

What do you think?

**Comment by samselikoff** [comment]
Thanks for opening the issue!

For now you can use imports:

```js
// endpoints/user.js
export default function(server) {
  server.get('/users');
}

// mirage/config.js
import userRoutes from './endpoints/user'

export default function() {
  userRoutes(this);
  // etc.
}
```

I know you'd like more conventions but for now there's a lot going on so this is lower priority. If enough people 👍  I'm happy to reopen and discuss!
