### ISSUE TITLE
v0.2.5 -> v0.2.6 breaks phantomjs builds

### ISSUE THREAD

**Issue by jesseditson** [samselikoff/ember-cli-mirage#1032]
Started seeing build errors on my CI server, and tracked it back to this line:

https://github.com/samselikoff/ember-cli-mirage/compare/v0.2.5...v0.2.6#diff-3da129bcd0b0367d1b65b28e9ecc34c9R345

Phantom doesn't have the `Number` type yet, so this will break any consuming applications who state `"ember-cli-mirage": "^0.2.5"` or similar in package.json.

Unfortunately this won't even be obvious to most consuming applications, as this error will be thrown from `test-support.js` without a trace (at least on my build server, this is the case). Since we accept patch updates automatically, this broke all our builds while still passing locally.

I'd personally recommend hotfix a patch version changing those `Number.isInteger()` tests with something more es5 compatible, as this is a bit tough to track down, and is a breaking patch change for us.

Thanks!

**Comment by samselikoff** [comment]
Just released https://github.com/samselikoff/ember-cli-mirage/releases/tag/v0.2.7 which should close this. Sorry about the delay & thanks for reporting!

**Comment by jesseditson** [comment]
🙌thank you!
