### ISSUE TITLE
How to let Mirage passthrough node modules access?

### ISSUE THREAD

**Issue by li-xinyang** [samselikoff/ember-cli-mirage#1035]
I am using SimpleMDE which seems send a request to `/node_modules/typo-js/dictionaries/en_US/en_US.dic` internally.

[![enter image description here][1]][1]

[![enter image description here][2]][2]

How to pass this GET request using Mirage?

I am using the following setting with no effect.

      this.passthrough('node_modules/**');
      this.passthrough('node_modules/typo-js/dictionaries/en_US/en_US.dic');

      this.passthrough('/node_modules/**');
      this.passthrough('/node_modules/typo-js/dictionaries/en_US/en_US.dic');

  [1]: https://i.stack.imgur.com/LD5EX.png
  [2]: https://i.stack.imgur.com/vNM9U.png

**Comment by samselikoff** [comment]
Try

```js
this.passthrough();
```

at the bottom of your config to allow all same-origin requests through.

**Comment by li-xinyang** [comment]
I did try `this.passthrough()` and the issue was persist.

**Comment by samselikoff** [comment]
Do you have a `namespace` defined?

**Comment by li-xinyang** [comment]
yes i do have

**Comment by samselikoff** [comment]
Could you try the latest version of mirage and see if you're having this problem?

**Comment by samselikoff** [comment]
Also, the URL prefix might be the problem, if your Ember app is hitting localhost:4200

**Comment by ashrafhasson** [comment]
I have this same issue where `namespace` is set and regardless whether `urlPrefix` is set or not, I get 404 Page not found back from Express.
I'm just trying to passthrough my API calls for endpoints that are now available on the backend which is hosted at  `localhost:4000`, is there a trick to getting this to work correctly or is this a current limitation?

**Comment by samselikoff** [comment]
@ashrafhasson `this.passthrough()` should work for your case. A 404 means Mirage is letting the request pass through, and your backend doesn't have the route defined.

Closing this issue for now - if you have another question feel free to open a new issue or ping me on Slack!
