### ISSUE TITLE
ember test --serve with mirage does not work

### ISSUE THREAD

**Issue by pawepaw** [samselikoff/ember-cli-mirage#1036]
Hello,

I just discovered that when i run tests from embercli using "ember test --serve" it spawns with some strange randomly generated url  like this 'http://localhost:7357/3714/tests/index.html?hidepassed' because of this my standard mirage rules are not working:

```
this.get('/users');
```

If they are defined in this way it'll capture only requests like 'http://localhost:7357/users' but ember is trying to reach 'http://localhost:7357/3714/tests/api/faq'

I found that when i define rule with wildcard like this it works:

```
this.get('**/users');
```

But standard and tutorial way is to just define relative path with no wildcards. Are you aware of this? Or is it my fault that it works like this? It works great when i run tests in other way (server application and navigate to /tests endpoint.

**Comment by acorncom** [comment]
This sounds like you are using either `ember-exam` or `ember-mocha` (test randomizing).  Does that happen to be the case?

**Comment by pawepaw** [comment]
Well at least not on purpose. I just use pure ember cli and trigger test run i didn't change anything maybe they did some changes? I'm using 2.10 version.

When i searched in node_modules directory i see that there are some mocha files but they are dependencies for ember-cli-legacy and ember-data. 

I also checked on pure ember tutorial (super-rentals) and it runs in the same way (with some strange id) so it seems that it's not only my problem.

**Comment by samselikoff** [comment]
I always run `ember t -s` so this is definitely working, let's figure out what's different with our apps.

Mirage doesn't actually allow your Ember app to make server requests so the domain (localhost:7357 in this case) doesn't affect it. Mirage uses Pretender and intercepts ajax requests in the browser.

When you have

```
this.get('/users');
```

and try to run a test, is there an error? If so what does it say?

**Comment by pawepaw** [comment]
ok so i found out what was the problem. I have relative path with rootURL defined in my adapter and tests run with ```ember t -s``` changed rootURL to some random url like ```/3714/tests/```. Because of it adapter is defined for ```/3714/tests/users``` and mirage is defined for ```/users``` 

so it's just my own problem. Sorry for bothering.

**Comment by ivinayakg** [comment]
> relative path with rootURL defined in my adapter
Can you explain a bit more about the solution, I'm facing the same issue and not able to solve it.

**Comment by ivinayakg** [comment]
> ok so i found out what was the problem. I have relative path with rootURL defined in my adapter and tests run with `ember t -s` changed rootURL to some random url like `/3714/tests/`. Because of it adapter is defined for `/3714/tests/users` and mirage is defined for `/users`
> 
> so it's just my own problem. Sorry for bothering.

Can you explain a bit more about the solution, I'm facing the same issue and not able to solve it.
