### ISSUE TITLE
Factories and Fixtures working together

### ISSUE THREAD

**Issue by sescobb27** [samselikoff/ember-cli-mirage#1038]
hi everyone, i have the following use case: mix in fixtures and factories for test cases, but i'm not able to make it work

```js
// models/order.js
import { Model } from 'ember-cli-mirage';

export default Model.extend({
  plan: belongsTo('plan')
});
```

```js
// factories/order.js
import { Factory } from 'ember-cli-mirage';

export default Factory.extend({
  season: config.ec.currentSeason
});
```

```js
// models/customer.js
import { Model, hasMany, belongsTo } from 'ember-cli-mirage';

export default Model.extend({
  orders: hasMany('order'),
  plan: belongsTo('plan')
});
```

```js
// factories/customer.js
import { Factory } from 'ember-cli-mirage';

export default Factory.extend({});
```

```js
// fixtures/plans.js
const _1shirt = {
  id: '1-shirt',
  title: '1 Shirt Plan',
  itemLimit: 1,
  discount: 0.5
};

const _2shirt = {
  id: '2-shirt',
  title: '2 Shirt Plan',
  itemLimit: 2,
  discount: 0.5833
};

const _3shirt = {
  id: '3-shirt',
  title: '3 Shirt Plan',
  itemLimit: 3,
  discount: 0.6667
};

export default [
  _1shirt,
  _2shirt,
  _3shirt
];
```

```js
module('Acceptance', {
  beforeEach: function () {
    this.App = startApp();
    server.loadFixtures()
  },

  afterEach: function () {
    destroyApp(this.App);
  }
});

test('make it work', function (assert) {
  const plan = server.db.plans.find('1-shirt');
  const orders = server.createList('order', 1, { plan }); // TypeError: newModel.isNew is not a function
  const customer = server.create('customer', { orders });
});
```

but i'm getting `TypeError: newModel.isNew is not a function` when setting up order's relationships. what i'm doing wrong? is this use case supported?, if not do you know how can i make it work?. thanks

**Comment by sescobb27** [comment]
ok, i already solved it, but don't know if is the right approach, i created a plans factory and then i did this
```js
const plan = server.create('plan', server.db.plans.find('1-shirt'));
const orders = server.createList('order', 1, { plan });
const customer = server.create('customer', { orders });
```

**Comment by thornomad** [comment]
I am also curious about the correct approach for this scenario.

Most of my models are generated by factories, however, I have a few fixtures.  Is this:

```javascript
const plan = server.create('plan', server.db.plans.find('1-shirt'));
```

The correct approach to get a fixture record before creating the relationship to the factory?  It seems to work for me in some cases but am struggling in others and I can't pinpoint the problem. Thanks.

**Comment by samselikoff** [comment]
I apologize for not responding to this!

If fixtures are defined but not loading, try calling `server.loadFixtures()` and then using your factxories.

I'll go ahead and close this issue for now since it's quite old, but if you’re still having trouble, please ping me here or on slack @samselikoff and I will reopen + discuss.
