### ISSUE TITLE
PUT status code defaulting to 204 bite me

### ISSUE THREAD

**Issue by cibernox** [samselikoff/ember-cli-mirage#104]
I spent a couple hours pulling hair of my head because I couldn't understand why Ember Data was just ignoring the response from my PUT actions.

I added a custom handler and returned different json's and nothing worked, but the messages that mirage logs in the console showed that mirages was responding with the expected payload, so the problem had to be in my code...

Until I went down the rabbit hole and discovered the jQuery's ajax ignores the response body of requests with a 204 header, and mirage uses that header by default for PUT requests. So even if I was returning the good json and mirage was logging it, `$.ajax` (and therefore Ember Data) was just ignoring it.

I can implement any of this solutions:

A) Show a warning in the console when you return content form a custom hander and the code is 204.
B) When a custom handler returns data and the default status code is 204, put a 200 instead.
Z) Regardless of A or B, add some entry in the wiki about what are the default status code for each verb.

I can take care of this, but I'd like to discuss which options feels more natural. My personal choice is B. I think that if I am returning a body from my custom handler, I expect my request to not use a 204.

Thoughts?

**Comment by samselikoff** [comment]
Ugh, what a nightmare :/ sorry about this man. I actually encountered this when writing the shorthands, and my research led me to the conclusion that 204 with no response was what the default should be for PUT.

[This ember data](https://github.com/ebryn/ember-model/pull/340) issue discusses the same thing, and it looks like they automatically updated the adapter to take server data, if it was returned. That makes me think we should go with your option (B).

Sorry again - and thanks soo much for investigating!! I owe you a :beer: whenever we meet :)

**Comment by cibernox** [comment]
Closed by #106
