### ISSUE TITLE
 Ember.$.ajax().then() never called

### ISSUE THREAD

**Issue by woprandi** [samselikoff/ember-cli-mirage#1044]
Hi,

In my ember code I wrote ajax jquery with jQuery $.ajax but the then() is never called.

```
Ember.$.ajax(....).then(() => {
console.log("never called");
}).always(() => {
console.log("called")
});
```

The then is called when I don't use mirage.
I correctly declared the route in my mirage/config.js file : 

```
this.post("/objects/:id", (db, request) => {
  ....
  return new Response(200, {}, "Confirmed");
}
```

**Comment by woprandi** [comment]
Same problem with done()

**Comment by samselikoff** [comment]
Could you pass an argument to `.catch(reason)` and inspect it?

**Comment by woprandi** [comment]
I got : `SyntaxError: Unexpected token C in JSON at position 0`

Mirage's `Response` constructor seems to not like string response ("Confirmed"). If I replace : 
`  return new Response(200, {}, "Confirmed");`
by
`  return new Response(200, {}, {"response": "Confirmed"});`
it works.

**Comment by samselikoff** [comment]
Hmm this test shows a string as a response

https://github.com/samselikoff/ember-cli-mirage/blob/master/tests/integration/route-handlers/function-handler-test.js#L55

Could you investigate - maybe clone the repo, make a copy of that test and put your code as the response, and see if it errors?

**Comment by woprandi** [comment]
I understood, it's because I return "Confirmed", so plain text without specify "Content-Type : text/plain". I guess the default Content-Type is "application/json".  I close this issue
