### ISSUE TITLE
faker.list.random array argument support

### ISSUE THREAD

**Issue by ksin** [samselikoff/ember-cli-mirage#1048]
Wondering what you think about allowing an array as the argument for `faker.list.random` and `faker.list.cycle`

ie:
```
faker.list.random([100, 200, 300, 400])
// same as calling
faker.list.random(100, 200, 300, 400)
```

Basically semantic sugar for using `.apply`.

Let me know if you think that's cool and I can make a PR.

**Comment by fran-worley** [comment]
You could just use the native faker:
faker.random.arrayElement(array)
?

**Comment by hbrysiewicz** [comment]
Feature requests are being moved to Canny.
[View this feature request on Canny](https://ember-cli-mirage.canny.io/feature-requests/p/fakerlistrandom-array-argument-support)
