### ISSUE TITLE
update Mirage Boilerplate Twiddle - in new issue template

### ISSUE THREAD

**Issue by cs3b** [samselikoff/ember-cli-mirage#1049]
it's on a very ancient version 

how can I help? 

here as a more modern example

https://ember-twiddle.com/95cb2c68af1349576c4ee8328c5f80e3?openFiles=templates.application.hbs%2C

**Comment by samselikoff** [comment]
That would be great! Send a PR to update https://github.com/samselikoff/ember-cli-mirage/blob/master/ISSUE_TEMPLATE.md

**Comment by cs3b** [comment]
pull request with link to new ember-twiddle submitted
