### ISSUE TITLE
[0.3.0] [BUG] assigning the same object to belongs_to relation keep only the last one  

### ISSUE THREAD

**Issue by cs3b** [samselikoff/ember-cli-mirage#1050]
(It was working before 0.3.0)

I've User model, that have parent belongs_to relation 

````js
import { Model, belongsTo, hasMany } from 'ember-cli-mirage';

export default Model.extend({
  parent: belongsTo('user', { inverse: 'children' }),
  children: hasMany('user', { inverse: 'parent' }),
});
````
When I try to give it few children

````js
import { Factory, faker, trait } from 'ember-cli-mirage';

export default Factory.extend({
  name() {
    return faker.name.findName();
  },
  withChildrens: trait({
    afterCreate(parent, server) {
      server.create('user', { parent, name: 'first child' });
      server.create('user', { parent, name: 'second child' });
      server.create('user', { parent, name: 'third child' });
    }
  })
});
````
only the last one have the parent

![screen shot 2017-03-22 at 21 45 39](https://cloud.githubusercontent.com/assets/120829/24219959/f1f80818-0f48-11e7-9fa1-d88cb0daf84e.jpg)

Here is [Ember Twiddle](https://ember-twiddle.com/95cb2c68af1349576c4ee8328c5f80e3?openFiles=mirage.factories.user.js%2C)

**Comment by samselikoff** [comment]
Def a bug, looking at it

**Comment by samselikoff** [comment]
Also looks like the parent's `childIds` is null too?

**Comment by cs3b** [comment]
@samselikoff yes, the `childIds` is empty

**Comment by samselikoff** [comment]
https://github.com/samselikoff/ember-cli-mirage/pull/1054 closes

**Comment by samselikoff** [comment]
confirmed your twiddle works with 0.3.1 :)
