### ISSUE TITLE
Reflexive relationships don't use explicit inverse

### ISSUE THREAD

**Issue by Brandon-Wolff** [samselikoff/ember-cli-mirage#1052]
I think [this line](https://github.com/samselikoff/ember-cli-mirage/blob/one-way-associations/addon/orm/associations/association.js#L49) referenced in [this issue](https://github.com/samselikoff/ember-cli-mirage/issues/1009) might be the problem. It seems like it still assumes that a reflexive relationship has a self referencing inverse. [This twiddle](https://ember-twiddle.com/28d17974f31791799c489bc13d590192?openFiles=tests.test-helper.js%2C) shows the issue, the parent's id is being put in the childIds array of the children instead of the parentId property.

**Comment by samselikoff** [comment]
I think you're right, looking into this now. Also think it's the same problem with https://github.com/samselikoff/ember-cli-mirage/issues/1050

**Comment by samselikoff** [comment]
https://github.com/samselikoff/ember-cli-mirage/pull/1054 closes
