### ISSUE TITLE
Issue with polymorphic record

### ISSUE THREAD

**Issue by jackmatt2** [samselikoff/ember-cli-mirage#1057]
ember-cli-mirage@0.3.1

Getting this error
> Mirage: Couldn't find all steps with ids: (1) (found 0 results, but was looking for 1)

Mirage Models defined as follows

```
// mirage/models/step.js
// This is essentially abstract and has a number of implementations such as start-step.js below
import { Model, hasMany } from 'ember-cli-mirage';
export default Model.extend({
  fromConnections: hasMany('connection', { inverse: 'fromStep' }),
  toConnections: hasMany('connection', { inverse: 'toStep' }),
});
```

```
// Example step implementation
// mirage/models/start-step.js
import Step from './step';
export default Step.extend({
});
```

```
// mirage/models/connection.js
import { Model, belongsTo } from 'ember-cli-mirage';
export default Model.extend({
  fromStep: belongsTo('step'),
  toStep: belongsTo('step')
});
```

The issue occurs when creating the connection model in scenarios/default.js

```
  const startStep1 = server.create('start-step', {
    name: 'Start' example
  });

  const finishStep1 = server.create('finish-step', {
    name: 'Finish example',
  });

  // Complains with message at start of this issue.
  const connection1 = server.create('connection', {
    fromStep: startStep1,
    toStep: finishStep1
  });
```

I should also point out that changing "connection.js" to use the implementation instead of the abstraction makes it work.

```
// mirage/models/connection.js
export default Model.extend({
  fromStep: belongsTo('start-step'), // Using an implementation here instead of the "step" interface
  toStep: belongsTo('finish-step')
});
```

**Comment by dguettler** [comment]
@jackmatt2 possibly related to #1154 which works on 0.2.9 may be an option for you as well

**Comment by samselikoff** [comment]
I apologize for not responding to this!

There's been a lot of work on Mirage since this issue, specifically making polymorphic relationships more robust, so I would give the latest version a shot.

I'll go ahead and close this issue for now since it's quite old, but if you’re still having trouble, please ping me here or on slack @samselikoff and I will reopen + discuss.
