### ISSUE TITLE
Add `updateAttributes` for models?

### ISSUE THREAD

**Issue by balinterdi** [samselikoff/ember-cli-mirage#1060]
Typically in a `patch` Mirage handler, we receive the payload in the request, then set those attributes on the identified model record and then save and return it.

I had to do that today and here is what I came up with:

```js
this.patch('/questions/:slug/answers/:id', (schema, request) => {
  let { slug, id } = request.params;
  let attributes = JSON.parse(request.requestBody).data.attributes;
  let question = findBySlug(schema.questions, slug, 'question');
  let answer = question.answers.models.find((answer) => { return answer.id === id; });
  Object.keys(attributes).forEach((key) => {
    answer.update(key, attributes[key]);
  });
  return answer.save();
});
```
Ideally, I'd like to be able to do `answer.updateAttributes(attributes)` (like in Rails) to get rid of the `Object.keys(...)` loop, basically just doing the same thing in Mirage itself.

Does that make sense to add, or would that unnecessarily bloat the API?

I can volunteer to add that, if that seems like a good idea.

**Comment by samselikoff** [comment]
It's not clear from the docs but this actually already exists, look at the example from #update http://www.ember-cli-mirage.com/docs/v0.3.x/models/#instance-methods

and the code https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/orm/model.js#L75-L76

**Comment by balinterdi** [comment]
Ah, so instead of

```js
Object.keys(attributes).forEach((key) => {
  answer.update(key, attributes[key]);
});
```

We could just write

```js
answer.attrs = attributes
```

?

**Comment by samselikoff** [comment]
Actually `answer.attrs` should be considered private, it would be

```js
answer.update(attrs)
```

You can see this being used in the [put shorthand](https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/route-handlers/shorthands/put.js#L24) for example

**Comment by samselikoff** [comment]
Also your line here

```js
let attributes = JSON.parse(request.requestBody).data.attributes;
```

won't always work because JSON:API attributes tend to be dasherized. So you can use the `normalizedRequestAttrs()` method to get those extracted for you:

```js
let attrs = this.normalizedRequestAttrs();
```

If you want to use this you'll have to change the fat arrow function to a normal function, as it depends on the `this` binding. You can read more here: http://www.ember-cli-mirage.com/docs/v0.3.x/route-handlers/#normalizedRequestAttrs

**Comment by balinterdi** [comment]
Makes sense, thank you!
