### ISSUE TITLE
server variable is not available in acceptance tests

### ISSUE THREAD

**Issue by matthias-k** [samselikoff/ember-cli-mirage#1063]
I forked the mirage boilerplate twiddle and added an acceptance test for `/` which tries to use the server to generate some users as shown in the mirage quickstart by

```
let users = server.createList('user', 3);
```

However the test fails with `ReferenceError: server is not defined` `this.server` doesn't work either. You can look into the twiddle [here](https://ember-twiddle.com/fc804553d54b920861a02cfb1044eb52?openFiles=tests.acceptance.application-test.js%2C).

**Comment by matthias-k** [comment]
This also explains my issues described in #1058

**Comment by hbrysiewicz** [comment]
I am getting this error using `ember-cli: 2.13.0-beta3` `ember-source: 2.13.0-beta.1` and `ember-data: 2.13.0-beta.1`.

Within the `beforeEach` hook on a `moduleForAcceptance` `this.sever` is `undefined`.

**Comment by hbrysiewicz** [comment]
Update: changing to `window.server` instead works - seems bad though.. Not sure what the best solution to moving server off window is, but found this nice `TODO` while I was investigating https://github.com/samselikoff/ember-cli-mirage/blob/fb2428aa957d919b0a87457656294a16fa63b405/addon/server.js#L182

**Comment by abrinckm** [comment]
odd... neither `server` nor `window.server` works for me.

http://localhost:7357/assets/test-support.js:7414:22: Can't find variable: server

http://localhost:7357/assets/test-support.js:7414:22: undefined is not an object (evaluating 'window.server.create')

**Comment by abrinckm** [comment]
This worked

http://stackoverflow.com/questions/33192260/using-the-server-variable-in-ember-cli-mirage-tests

**Comment by matthias-k** [comment]
The answer suggests to either upgrade PhantomJS to 2.x or install ember-cli-es5-shim. Since I'm running the tests in chrome, PhantomJS cannot be the culprit (but I'm using version 2.1.1 anyway). Installing `ember-cli-es5-shim` doesn't solve the problem either, as can be seen in the updated [twiddle](https://ember-twiddle.com/fc804553d54b920861a02cfb1044eb52?openFiles=tests.acceptance.application-test.js%2C) which now installs ember-cli-es5-shim. Neither `server`, nor `this.server` or `window.server` works. Apparently, this is some other issue.

**Comment by ankushdharkar** [comment]
@matthias-k: I have been experiencing a similar problem recently. It may be unrelated, but I have an issue open at #1279
