### ISSUE TITLE
Shorthand `this.patch('users/:id');` does not persist changes in relationships

### ISSUE THREAD

**Issue by Herriau** [samselikoff/ember-cli-mirage#1072]
It seems like the shorthand for `this.patch()` properly persists attributes, but mutations of relationships, whether they are `belongsTo` or `hasMany` do not appear to be persisted.

Example:
[https://ember-twiddle.com/c496ddbf58986fd2082a2e4771a5987d](https://ember-twiddle.com/c496ddbf58986fd2082a2e4771a5987d)

Click the "Update Users" button, which removes the posts associated with the first user in the collection and then `save()` that user. The post counter next to the first user will temporarily change to "0 posts" while the request is still being handled by mirage, but will revert to 1 as mirage responds with the old list of related posts.

**Comment by samselikoff** [comment]
I believe https://github.com/samselikoff/ember-cli-mirage/pull/1086 closes this
