### ISSUE TITLE
Foreign Keys are stripped unnecessarily for ActiveModelSerializer

### ISSUE THREAD

**Issue by kylemellander** [samselikoff/ember-cli-mirage#1074]
https://ember-twiddle.com/072de99410f21ff42db8264bd9665ca3?openFiles=mirage.serializers.application.js%2C

In a simple situation with ActiveModelSerializer and a belongsTo relationship, the fk's are stripped from the payload, so the relationship is non-existent.

I am going to put together a PR to address this.

**Comment by cyberxander90** [comment]
I have some troubles with this issue, and is good to know there are a pending PR to resolve this.
Meanwhile i have a solution on [this post](https://stackoverflow.com/questions/44705795/mirage-serializer-drop-ids-when-include-and-embed-some-model).

**Comment by jherdman** [comment]
I can confirm that @cyberxander90's solution works, and that this is what I'm doing at present in my apps.

**Comment by kylemellander** [comment]
Sorry for my delay on this...I'll work on getting the test up soon.

**Comment by samselikoff** [comment]
I think if you use `serializeIds: 'always'` on the Serializer you should be all set here. 

I know it should be the default behavior but I didn't want to add a breaking change. It should likely be changed to the default in the 1.0 release.
