### ISSUE TITLE
`include` array requires property name not model name

### ISSUE THREAD

**Issue by brandynbennett** [samselikoff/ember-cli-mirage#1090]
If you extend a serializer and use the `include` array, but the property name on your relationship doesn't match the model name e.g.

```javascript
// mirage/models/post.js
export default Model.extend({
  person: belongsTo('user'),
});

// mirage/serializers/post.js
export default BaseSerializer.extend({
  include: ['user'],
});
```

Then you won't get an `included` array in your JSONAPI response.

https://ember-twiddle.com/043c15ac8c1355afabe9885dc35d367b?openFiles=templates.application.hbs%2C

**Comment by samselikoff** [comment]
This is intended, because you could have two named associations on your post model that are both users:

```js
parent: belongsTo('user'),
child: belongsTo('user')
```

and you want to differentiate between the two. Does that make sense?

**Comment by brandynbennett** [comment]
I see what you mean. That makes sense. Thanks for the explanation.
