### ISSUE TITLE
Self-referential associations cause "RangeError: Maximum call stack size exceeded"?

### ISSUE THREAD

**Issue by Kerrick** [samselikoff/ember-cli-mirage#1091]
I have a self-referential model, one that `belongsTo` itself and `hasMany` of itself. I tried creating a factory with traits that would use `afterCreate` to generate a tree of these objects, and I ended up getting a `RangeError: Maximum call stack size exceeded` error. Am I doing something wrong, or is this not supported?

Here's the error:

```
Died on test #1     at Module.callback (http://localhost:7357/assets/tests.js:7:19)
    at Module.exports (http://localhost:7357/assets/vendor.js:119:32)
    at requireModule (http://localhost:7357/assets/vendor.js:34:18)
    at TestLoader.require (http://localhost:7357/assets/test-support.js:7675:7)
    at TestLoader.loadModules (http://localhost:7357/assets/test-support.js:7667:14)
    at Function.TestLoader.load (http://localhost:7357/assets/test-support.js:7697:22)
    at http://localhost:7357/assets/test-support.js:7580:18: Maximum call stack size exceeded
```

```
Expected: 	
null
Message: 	Diff suppressed as the expected and actual results have an equivalent serialization
Source: 	
RangeError: Maximum call stack size exceeded
    at http://localhost:7357/assets/vendor.js:156438:44
    at apply (http://localhost:7357/assets/vendor.js:151684:21)
    at http://localhost:7357/assets/vendor.js:159926:33
    at http://localhost:7357/assets/vendor.js:132935:47
    at Array.reduce (native)
    at Server._mergeExtensions (http://localhost:7357/assets/vendor.js:132934:30)
    at Server.build (http://localhost:7357/assets/vendor.js:132569:39)
    at Server.create (http://localhost:7357/assets/vendor.js:132620:32)
    at http://localhost:7357/assets/vendor.js:132954:50
    at Array.forEach (native)
```

[Here's the code that caused the error](https://github.com/Kerrick/mirage-problems/commit/bbfa4d8e1606237488c881820345c8b6bd47ac00), and [here's a repo you can check out](https://github.com/Kerrick/mirage-problems) and see the error as you run `ember test --server`.

**Comment by Kerrick** [comment]
Assuming I tested this correctly, the issue does _not_ seem to be fixed by #1078.

**Comment by samselikoff** [comment]
Should be supported but there's lots of these tricky cases and it's possible I didn't cover this one with tests. I'm tied up with other things at the moment - if you have some time to investigate I would try duplicating one of the [one-to-many](https://github.com/samselikoff/ember-cli-mirage/tree/master/tests/integration/orm/mixed) test cases and setting up a self-referential example in the helper file, and trying to see if you can isolate a test failure

**Comment by samselikoff** [comment]
Turns out the problem is with `association()`. Every page being created is trying to create a parent for itself, and on, and on, and on...

I'm going to update `association()` to `throw` if its used for a self-referential belongsTo. The solution in your case is to remove the `parentPage: association()` line, and only use `afterCreates`. (You could add a `withParent` `trait` that uses `association`:

```js
withParent: trait({
  parentPage: association()
})
```

so that way other pages being created don't always hit this code path.)

**Comment by samselikoff** [comment]
https://github.com/samselikoff/ember-cli-mirage/pull/1354 closes
