### ISSUE TITLE
Relationships not working in production

### ISSUE THREAD

**Issue by luxferresum** [samselikoff/ember-cli-mirage#1092]
its seems like in a production build relationships are not working as expected.

I have enabled mirage with:

    ENV['ember-cli-mirage'] = {
      enabled: true
    };

[Here](https://github.com/luxferresum/mirage-not-working-on-production) is a git repo to demonstrate the error. Compare the result of `ember s` with `ember s --prod`.

In production the relationship `bars` on the `foo` model is not loaded.

**Comment by samselikoff** [comment]
Believe these lines https://github.com/luxferresum/mirage-not-working-on-production/blob/master/config/environment.js#L49-L51 need to be within your `if environment === production` block.

**Comment by luxferresum** [comment]
That does not make any sense. This code will run as well, its not in any `if`. However I tried that as well.

**Comment by samselikoff** [comment]
I found it! `inverse.constructor.name = 'HasMany'` was breaking in production due to minification.

60918b19c45b926ce3a9e9c26126e8ea8a0e3cfa closes.
