### ISSUE TITLE
Bug - attempting to use ID 1 but its already used

### ISSUE THREAD

**Issue by samselikoff** [samselikoff/ember-cli-mirage#1099]
```
  afterCreate(clip, server) {
    clip.encodes = [
      server.create('encode', 'mp4'),
      server.create('encode', 'webm')
    ];
    clip.save();
  },

...
clip.encodes.destroy();

...

      clip.update({
        encodes: [
          server.create('encode', 'longMp4'),
          server.create('encode', 'longWebm')
        ]
      });
```

**Comment by geekygrappler** [comment]
Hey @samselikoff I couldn't reproduce this: https://github.com/geekygrappler/ember-cli-mirage/commit/44162b8a8d634827cc2a656bf53551870727fa0d

Created new children with correct IDs in my test, didn't try and reuse id `1`. Any further steps to reproduce?

**Comment by erichonkanen** [comment]
Just ran into this, not sure if it's ember-data or mirage but I create a new record with a specific id, then I delete it, then I recreate the record with that specific id and I get ```Attempting to use the ID current-user|test-user-0, but it's already been used```

**Comment by samselikoff** [comment]
@erichonkanen That's on Mirage's side - it's how the default [identity manager](http://www.ember-cli-mirage.com/docs/advanced/identity-managers) works (check out [the set method](https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/identity-manager.js#L33)).

What's your use case?
