### ISSUE TITLE
hasMany (one way) POST/PATCH does not persist the hasMany relationship in the response (or db)

### ISSUE THREAD

**Issue by Aaronfischer** [samselikoff/ember-cli-mirage#1100]
Hello! I created this twiddle: https://ember-twiddle.com/9fb4e28d80767fdb5ccf8ec5aeae6b3b?openFiles=routes.application.js%2C

(EDIT: I forgot to state HOW to trigger the bad behavior, DOH, Press "Add Book" and inspect the request (in the local store) vs the response (in the db dump/console))

I've read over the blog post about one-way hasMany and obviously based this example off of the twiddle provided. Anyway, what I'm seeing is that if I was to add the `book` to the `author.books` array then save `author` the request looks accurate, (`author.books` contains the `book` in its array) however, mirage's response returns an empty array.

Is this a bug? Is there something I'm missing for one-way hasMany that I need to account for in my route handler? How do I get this hasMany relationship to persist in the DB for `author`?

(to kind of state the obvious, but to ensure were on the same page: I'm not looking for `book` to have any reference of `author`s, I just want `author`s to persist its reference to books)

Thanks!! 👍

**Comment by Baukereg** [comment]
I suspect this problem actually extends beyond just POST/PATCH calls and one-way relations. Imagine this model hook:

```
return this.store.findRecord('client', clientId).then(client => {
  this.store.query('clientNameDetails', { client:clientId });
  this.store.query('clientPhoneNumber', { client:clientId });
});
```
In this case clientNameDetails has a one-to-one relation to client, where clientPhoneNumber has a many-to-one relation with client. With Mirage 0.3.2 (and 0.3.3 as well), the clientNameDetails resolves as expected, but the GET response of clientPhoneNumber doesn't even include clientId. So when I check a clientPhoneNumber record in the Ember Inspector, client resolved to null.

**Comment by samselikoff** [comment]
@Aaronfischer This is a missing feature - the shorthands aren't quite that intelligent yet. In cases like this I drop down to a function handler to code the logic myself, something like this:

```js
this.patch('authors/:id', function(schema, request) {
  let attrs = this.normalizedRequestAttrs();
  let id = request.params.id;
  let author = schema.authors.find(id);
  let bookIds = JSON.parse(request.requestBody)
    .data
    .relationships
    .books
    .data
    .map(book => book.id);

  attrs.bookIds = bookIds;
  
  author.update(attrs);

  return author;
});
```

I would love for you to help code this missing feature. We could start with a failing test - would you be willing to submit a PR with essentially the twiddle you've set up in a test? You could add a new file in [this folder](https://github.com/samselikoff/ember-cli-mirage/tree/master/tests/integration/route-handlers), call it `put-shorthand-relationships-test`, and code up a failing test.

**Comment by Aaronfischer** [comment]
@samselikoff Sure, I'll try to get a failing test up to start us off.

**Comment by Aaronfischer** [comment]
Just to keep this issue updated, its looking like somewhere between 0.3.0 and 0.3.3 this issue seems to be resolved. (at least for my use case)

Unfortunately ember-twiddle can't build mirage 0.3.3 or even 0.3.2 for me to show one working and one failing but in my application (and after attempting to create a `put-shorthand-relationships-test` it passes)

Feel free to reopen if anyone is still having this issue on 0.3.2/0.3.3
