### ISSUE TITLE
Expose Mirage Database in the serializer

### ISSUE THREAD

**Issue by taras** [samselikoff/ember-cli-mirage#1103]
This is an issue to keep track of a change to address a common request to make it possible to access the Mirage database a Mirage Serializer. 

Had a quick chat with Sam about this and he commented the following:

<img width="564" alt="screen shot 2017-06-08 at 10 58 18 am" src="https://user-images.githubusercontent.com/74687/26935233-6b2887da-4c39-11e7-99a6-afb80faf9d02.png">

**Comment by corrspt** [comment]
I see the referenced merged PR, should this issue be closed?

**Comment by taras** [comment]
My guess is yes.

**Comment by acorncom** [comment]
Thanks, closing
