### ISSUE TITLE
Ember Data model auto discover does not work with PODS model structure

### ISSUE THREAD

**Issue by yratanov** [samselikoff/ember-cli-mirage#1104]
At the moment Mirage tries to import Ember Data models from 
```js
let modelMatchRegex = new RegExp(`^${modulePrefix}/models`, 'i');
```

But if you are using POD project structure it won't work, because models are in: `${modulePrefix}/<modelName>/model.js`

**Comment by samselikoff** [comment]
@yratanov could you try again with this commit? https://github.com/samselikoff/ember-cli-mirage/commit/1b7bf74f0670d2f741f28b11c57a92e1b975297f

**Comment by acorncom** [comment]
Looks like this has been addressed, closing to clean up the issue fracker. Happy to re-open if needed

**Comment by yratanov** [comment]
@samselikoff hi, sorry for delayed response, but I have an issue with your solution.

In my project `podModulePrefix` is empty and I don't think I need it. 
So this line 
```js
let modelMatchRegex = new RegExp(`^(${modulePrefix}/models|${podModulePrefix}/.*/model$)`, 'i');
```
evaluates to `^my-project-name/models|/.*/model$`, but what I need is
`^my-project-name/.*/model$`. I can set `podModulePrefix` to `my-project-name` and it fixes mirage, but all ember generators create files under `/my-project-name/app/my-project-name/...`. 

Can we change the regexp to?
```js
^(${modulePrefix}/models|${isEmpty(podModulePrefix) ? modulePrefix : podModulePrefix}/.*/model$
```

I can send a PR if you agree with my approach.
