### ISSUE TITLE
Does Get /:id shorthand automatically use the correct ID?

### ISSUE THREAD

**Issue by flyswatter** [samselikoff/ember-cli-mirage#111]
I found [the relevant page of the wiki](https://github.com/samselikoff/ember-cli-mirage/wiki/GET-shorthands) unclear how this works.

if I say `app.get('users/:id');`, is it going to find a `user` with the `id` matching `:id`?  If so, that's crazy cool, and bravo.

**Comment by flyswatter** [comment]
I'd also be curious how the database identifies a model's type.  Is it the file name that contained, it, or an identifying key it looks for?

**Comment by samselikoff** [comment]
yes sir, you can see from [the dummy app's config](https://github.com/samselikoff/ember-cli-mirage/blob/master/tests/dummy/app/mirage/config.js), thats a fully functional mirage server, and when the Ember app makes a GET request to `/contacts/1`, mirage will fetch the `contact` with an `id` of 1 and return it. 

The database has collections, so for example by creating the file `/mirage/fixtures/contacts.js`, the `contacts` collection will be created, and any data you export from that file will become data in the database.

**Comment by flyswatter** [comment]
Awesome, thanks!
