### ISSUE TITLE
Broken tests when using startMirage with loader.js > 4.0.9

### ISSUE THREAD

**Issue by thomblake** [samselikoff/ember-cli-mirage#1111]
I'm not sure if this is a documentation issue or just a case of me doing it wrong in general, but this issue https://github.com/ember-cli/loader.js/issues/87 seems to be related to the order in which the mirage initializer is called, since it's added to the application initializers and app is also imported in tests.

Basically there's a major test breakage that can happen based on where you put the stuff recommended here http://www.ember-cli-mirage.com/docs/v0.2.x/manually-starting-mirage/ and it's pretty hard to debug.

Here's as close as I could come to a minimal reproduction: https://github.com/PagerDuty/loader-js-test

**Comment by jasonmit** [comment]
Also noticed this.  I found lazily requiring the initializer seemed to work around the issue.  Not a fix - but hopefully helps unblock others.

**Comment by theseyi** [comment]
Any updates on this issue? seems fairly easy to repro given the sample provided above

**Comment by theseyi** [comment]
@thomblake are you doing this in an acceptance test?

**Comment by samselikoff** [comment]
Sorry about the delay!

I pulled down the repo and updated ember/ember-cli to recent versions, and this seems to have been fixed.
