### ISSUE TITLE
Unable to delete records with polymorphic belongsTo associations

### ISSUE THREAD

**Issue by omghax** [samselikoff/ember-cli-mirage#1112]
Okay, this is a little involved, so bear with me.

I was getting some really strange errors in my app when trying to delete a record with a polymorphic `belongsTo`. In my case, the record itself would be deleted, but it wouldn't be removed from the inverse relationship correctly.

After digging around through Mirage's source, I think I found the root cause. In the `BelongsTo#disassociateAllDependentsFromTarget` method, a [query is generated](https://github.com/samselikoff/ember-cli-mirage/blob/fe8ec9c838feec42270e950beb55ef0619ecd6c6/addon/orm/associations/belongs-to.js#L228-L235) which, in the case of a polymorphic association, ends up looking like:

```js
aCollection.where({ aForeignKey: { id: 1, type: 'some-model-type' } })
```

Ultimately this falls into `DbCollection#_findRecordsWhere` which, in the case that it's given an object, will attempt to [coerce all values to strings](https://github.com/samselikoff/ember-cli-mirage/blob/fe8ec9c838feec42270e950beb55ef0619ecd6c6/addon/db-collection.js#L295-L297). But, if we have a polymorphic association, these values will all be `{ id, type }` pairs, so coercing them into strings will result in `"[object Object]"`, and _every_ record will be matched.

I think the simplest way to fix this would be to pass a function to `where` instead (in fact, `HasMany#disassociateAllDependentsFromTarget` [already does this](https://github.com/samselikoff/ember-cli-mirage/blob/fe8ec9c838feec42270e950beb55ef0619ecd6c6/addon/orm/associations/has-many.js#L256-L268)).

**Comment by samselikoff** [comment]
Oof - great sleuthing!

That sounds like a good fix to me. Would you be able to open a PR with the failing test, and then make the change? Even a PR with the failing test would be very helpful.

Thank you for taking all the time to open this issue!

**Comment by omghax** [comment]
Thanks for the quick reply :)

Yeah, I already have the change ready, I just need to come up with a minimal failing test case. I'll try to get a PR out shortly.

**Comment by samselikoff** [comment]
https://github.com/samselikoff/ember-cli-mirage/pull/1173 closes
