### ISSUE TITLE
"meta traits" or combining traits into one

### ISSUE THREAD

**Issue by andrewhavens** [samselikoff/ember-cli-mirage#1116]
I need to create a trait which is a combination of other traits. I tried doing something like this:

```js
export default Factory.extend({
  'traitOne': trait({
    // ...
  }),
  'traitTwo': trait({
    // ...
  }),
  'allTraits': trait('traitOne, 'traitTwo')
});
```
...however, that did not work. Is there a way to define a trait which is a combination of multiple traits ("meta trait")?

**Comment by samselikoff** [comment]
Currently there is not, for now I would suggest writing a reusable function. I've added a card to the Roadmap if anyone can take this on. The API should look like

```js
export default Factory.extend({
  traitOne: trait({
    // ...
  }),
  
  traitTwo: trait({
    // ...
  }),
  
  allTraits: trait('traitOne, 'traitTwo', {
    some: 'override'
  })
});
```

**Comment by samselikoff** [comment]
Closing for now because I'm trying to keep the issue list actionable, but please work on this if you have time!
