### ISSUE TITLE
Inherit prefixes from application adapter

### ISSUE THREAD

**Issue by kellyselden** [samselikoff/ember-cli-mirage#1117]
Similar to how mirage now reads model relationships, I wonder if it makes sense for the defaults to come from the adapter:

`host` => `urlPrefix`
`namespace` => `namespace`

This would also let mirage respect that some adapters have one namespace and some another, instead of the current global `this.namespace`.

**Comment by samselikoff** [comment]
Yes, 100%

**Comment by eliasmelgaco** [comment]
@samselikoff close pls

**Comment by samselikoff** [comment]
We're moving feature requests to Canny so I'll go ahead and close this

https://ember-cli-mirage.canny.io/feature-requests/p/inherit-prefixes-from-application-adapter
