### ISSUE TITLE
Intercept routes with query parameters

### ISSUE THREAD

**Issue by VasylMarchuk** [samselikoff/ember-cli-mirage#1123]
So I have this in my route:
```
model() {
  return this.store.query('foo', {
    bar: 'baz'
  });
}
```

I need mirage to intercept the API request **only** if there's a `bar` query param that equals `baz`, and passthrough all the other cases. I expect something like the following in the mirage config:

```
this.get('https://api.example.com/foo?bar=baz', (db, request) => {
  debugger;
});
this.passthrough('https://api.example.com/foo');
```

Unfortunately it doesn't work that way.

**Comment by acorncom** [comment]
Hmm, that doesn't seem to fit the way pretender works under the hood. Might be worth opening an issue there to see what they think of changing things? I would imagine they might not want to do so though as it could be a breaking change ...

I'll close this issue for now, feel free to comment if you think this still needs addressing ...
