### ISSUE TITLE
Trouble mocking non-resource route

### ISSUE THREAD

**Issue by flyswatter** [samselikoff/ember-cli-mirage#113]
Hi there,

I've ported all my old normal-Pretender mocks over to a `mirage/config.js` file, and it looks like it's nearly working just perfectly!

Right now it looks like just one of the mocked endpoints isn't actually being impersonated.  This happens to be an endpoint that isn't associated with a particular ember model/resource, so its name isn't the same as any model.  It's like if it were `/api/sessionInfo.json`.

Two real questions here:

1.  I believe this route is not being mocked because the browser IS making a real HTTP request to this route, and it's receiving a 404 from some express server.  Pretender prevents real XHR requests from happening, right?  So it's fair to believe this endpoint isn't being mocked?

2.  Are there any caveats/gotchas to adding arbitrary endpoints to mirage?

Thanks a ton for your help, this addon is looking great, I've been wanting something like it for a while now!

**Comment by samselikoff** [comment]
you're welcome!

you can use [a function](https://github.com/samselikoff/ember-cli-mirage/wiki/HTTP%20Verb%20function%20handler) as a custom route handler for any path you choose:

```js
this.get('/sessionInfo', function(db, request) {
  // return whatever you want
});
```

I also was under the impression Pretender will prevent other requests from making it through, so I'm not sure how/why this one is getting through. Did you set up a passthrough? Maybe you could post your mirage config

**Comment by flyswatter** [comment]
Yeah, I am using a function, it's strange to me this isn't working.

It's basically set up like this:

```javascript
import posts from './fixtures/posts';
import sessionInfo from './fixtures/session';

export default function() {

  this.namespace = 'api';    // make this `api`, for example, if your API is namespaced
  this.timing = 40;      // delay for each request, automatically set to 0 during testing

  /* This seems to be working */
  this.get('posts.json', ()=> posts);

  /* Application State */
  this.get('/sessionInfo.json', ()=> sessionInfo );

}
```

It looks basically identical to me, so I'm really scratching my head.  Anyways, it's probably on my end, but I'll leave this open for now so I can share the solution I find.

**Comment by samselikoff** [comment]
`posts` and `sessions` should export arrays of POJOs (make session plurals sessions). Then they'll be added to the database automatically. Then you can just do this:

```
this.get('posts'); // thats it, will return all posts in your database, which will be added automatically from fixtures/posts

this.get('/sessionInfo', (db) => {
  return db.sessions[0];
});
```

I'd suggest reading through the readme to understand how & why the data gets added to the db. You don't want to statically import the data like that directly to your server definition, it's the main point of the project :)

**Comment by flyswatter** [comment]
Yeah, you're right.  I should just do that already.  I was trying to get by with my old mock files, which are duplicates of the server responses.

Do you think that could be related to why it's not stubbing out?

**Comment by samselikoff** [comment]
it could, I'd have to examine more in detail to know. There is another library that records + replays server responses, if that's more what you're looking for, called ember-cli-proxy-fixtures. mirage is more about mocking out server responses on the client. it's a different approach.

**Comment by flyswatter** [comment]
I might try that out too...

So many interesting projects going on in Ember lately!

What's your current approach to stubbing in relationships?  Do you just end up making a function, and enumerating models to update their belongsTo ids?  What are your longer term ideas about how to mock relationships, that you allude to in the README?

**Comment by samselikoff** [comment]
so if you look at the [get shorthands](https://github.com/samselikoff/ember-cli-mirage/wiki/GET-shorthands) you'll see you can do something like

```js
this.get('/contacts/:id', ['contact', 'addresses']);
```

it will return contacts from the db, and any address from the db where `contact_id` equals the `:id` in the path.

In testing with factories, you'd have to do something like

```js
var contact = server.create('contact');
var address = server.create('address', {contact_id: contact.id});
```

which is a pain right now but is workable in the short-term. Right now I'm working on an orm layer that will let you essentially do

```js
var contact = server.create('contact');
var address = contact.createAddress();
```

as well as use relationships in your factories, so you essentially don't have to worry about ids anymore.

**Comment by flyswatter** [comment]
Having a mini-ORM for client mocking is pretty awesome, it looks like a very worthwhile abstraction.

I'm writing a script now to dump a mock db into the format mirage prefers.

**Comment by samselikoff** [comment]
@flyswatter do you need any more help here?

**Comment by flyswatter** [comment]
No, you were a great help, thanks!
