### ISSUE TITLE
feature request - import swagger.json

### ISSUE THREAD

**Issue by HaithamMaya** [samselikoff/ember-cli-mirage#1132]
Would be nice to be able to import/reference a swagger.json file to auto-configure endpoints

**Comment by QuantumInformation** [comment]
Seems like a good candidate for a company to sponsor.

**Comment by jlegrone** [comment]
I've been working on an experimental mirage plugin to support this.  Documentation is lacking and at the moment you'll need to use ember-browserify to import the library, but it's a work in progress.  Please open issues if you come across any bugs!

See https://github.com/jlegrone/mirage-openapi

**Comment by hbrysiewicz** [comment]
Feature requests are being moved to Canny.
[View this feature request on Canny](https://ember-cli-mirage.canny.io/feature-requests/p/support-for-importing-swaggerjson)
