### ISSUE TITLE
`_` is undefined

### ISSUE THREAD

**Issue by cibernox** [samselikoff/ember-cli-mirage#114]
Now maste can't be used out of the box because lodash is a runtime dependency but the blueprints don't add it to the `bower.json`.

The change should be this:

```diff
'use strict';

module.exports = {
  normalizeEntityName: function() {
    // this prevents an error when the entityName is
    // not specified (since that doesn't actually matter
    // to us
  },

  afterInstall: function() {
    return this.addBowerPackagesToProject([
      {name: 'pretender', target: '~0.6.0'},
-      {name: 'ember-inflector', target: '~1.3.1'}
+      {name: 'ember-inflector', target: '~1.3.1'},
+      {name: 'lodash', target: '~3.7.0'}
    ]);
  }
};
```

Fancy a PR?

**Comment by samselikoff** [comment]
woops. let me take care of it.

is there a way to test this?

**Comment by cibernox** [comment]
I haven't tested, but this steps should work:

1. Create brand new app
2. run `ember install ember-cli-mirage`
3. Update to master => "git://github.com/samselikoff/ember-cli-mirage.git#cc9be12",
4. The console should show `Uncaught ReferenceError: _ is not definedFactory.extend`

**Comment by samselikoff** [comment]
right i did that + fixed, but I meant is there a way we could add a test to the test suite to ensure this doesn't break in the future

**Comment by seawatts** [comment]
Oops, that was my bad. Sorry.

**Comment by cibernox** [comment]
This is tricky, because in the dummy app in testing it will be included, because it's in the `bower.json` of the addon. I think that this is untestable.

**Comment by samselikoff** [comment]
haha @seawatts no worries - not as bad as me adding `tmp` to the repo ! :)

**Comment by samselikoff** [comment]
@cibernox right i figured. that's annoying, would be nice to eventually have a sanity check test like this run somewhere automatically as part of the suite.

**Comment by seawatts** [comment]
@samselikoff :stuck_out_tongue:
