### ISSUE TITLE
Add transient attributes

### ISSUE THREAD

**Issue by RoM4iK** [samselikoff/ember-cli-mirage#1141]
It will be great to add transient attributes like FactoryGirl (and maybe others) do. Here is code example
```js
export default Factory.extend({
  date(i) {
    return  this.startDate.add(i -1, 'days').format('YYYY-MM-DD');
  },
  startDate: transient((date) => (
     date ? moment(date) : moment();
   ),
});
```

The only difference between transient and normal attributes, transient attributes shouldn't be passed on model creation but should be available for use in the factory.
Usage of this factory:

```js
server.createList('spots', 3, { startDate: "2017-07-20") })
// Spot { date: "2017-07-20" }
// Spot { date: "2017-07-21" }
// Spot { date: "2017-07-22" }
```

If you are going to merge this feature, I can implement it by myself.

**Comment by samselikoff** [comment]
I apologize for not responding to this!

I would love to add this feature. I've moved it over to our [Canny board](https://ember-cli-mirage.canny.io/feature-requests), however if you still want to implement it I would appreciate the help very much! 

I'll close this for now but we can discuss here if you're up for it.
