### ISSUE TITLE
IE8 reserved word "delete"

### ISSUE THREAD

**Issue by zyllorion** [samselikoff/ember-cli-mirage#115]
With the following code:

```
define('ember-cli-mirage/controller', ['exports', 'ember', 'ember-cli-mirage/shorthands/index', 'ember-cli-mirage/response'], function (exports, Ember, shorthandHandlers, Response) {

  'use strict';

  var defaultCodes = {
    put: 204,
    post: 201,
    delete: 204
  };
```
delete causes issues with ie8 because it is reserved.  Please can you rename?

Thanks

**Comment by samselikoff** [comment]
I certainly can, though you should know Ember will dropping IE8 support this summer. You can of course stay on the 1.x series of Ember, but there are some upcoming changes to Mirage that use `Object.defineProperty` with getter/setters which I believe are not supported in ie8.

It may be possible to maintain a slimmed down version that works in ie8.

**Comment by zyllorion** [comment]
Hi,
I don't suppose you know when you might be able to refactor the delete part of the code?  Not concerned about Ember 2, it's a fair way off yet and can just use the Mirace for Ember 1 LTS
Thanks!!

**Comment by samselikoff** [comment]
No prob, replacing with DELETE should work correct? I don't have IE8 so I can't test

**Comment by samselikoff** [comment]
Let me know if master works

**Comment by zyllorion** [comment]
Perfect! Thanks
