### ISSUE TITLE
Polymorphic relationships

### ISSUE THREAD

**Issue by dguettler** [samselikoff/ember-cli-mirage#1154]
## Description
For polymorphic relationships the foreign keys on the `hasMany` side end up containing
```
{ type, id }, id
```
which results in an error when trying to lookup the models.

### Twiddle
https://ember-twiddle.com/570ae58cf87abee21b8b59a0c868feb0

### Affected versions
- 0.3.0 - 0.3.2 fail with #1057 
- 0.3.3 - 0.3.4 fail with
> Mirage: Your GET handler for the url /timelines threw an error: Cannot read property ‘replace’ of undefined

as `type` is undefined here
```
          if (association.isPolymorphic) {
            found = foreignKeys.map(function (_ref2) {
              var type = _ref2.type;
              var id = _ref2.id;

              return _this5._schema.db[(0, _emberCliMirageUtilsNormalizeName.toCollectionName)(type)].find(id);
            });
            found = (0, _lodashCompact['default'])(found);
          }
```

### Not affected versions
- 0.2.9

**Comment by lukemelia** [comment]
I've run into this same bug.

I think the root cause may be that (this line)[https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/route-handlers/base.js#L64] is not polymorphic-aware.

**Comment by scottkidder** [comment]
Just hit this one as well. Is there any progress on this?

**Comment by scottkidder** [comment]
I was hitting a similiar issue on PATCH and tracked it down to here:
https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/orm/associations/belongs-to.js#L135

It appears that foreignKeyId is expected to be  `{ type: 'some-type', id: 123 }` but in my case it is just `123` which causes `toCollectionName` to blow up.

Am I doing something wrong when setting up my polymorphic relations?

Or is the ember-data auto discovery doing something incorrectly or just not enough?

I will try to get a minimal reproduction soon.

**Comment by algodave** [comment]
I've run into this issue as well. I have an `address` model with an `addressable` polymorphic `belongsTo` relationship, and I want to set `addressable` when creating a new `address`.

So, I expanded my `POST` route handler like this:

```javascript
this.post('/addresses', function({ addresses }, request) {
  let attrs = this.normalizedRequestAttrs();
  return addresses.create(attrs);
});
```

and inspected the `attrs`. I figured out that `addressableId` was missing the `type` - I learnt [here](http://www.ember-cli-mirage.com/docs/v0.3.x/models/) that polymorphic foreign keys are expected to be objects holding both `id` and `type` (see the `commentableId` example)

So, I came up with the following workaround:

```javascript
  this.post('/addresses', function({ addresses }, request) {
    let attrs = this.normalizedRequestAttrs();
    let params = JSON.parse(request.requestBody);
    const addressableData = params.data.relationships.addressable.data
    if (addressableData)
      attrs.addressableId = addressableData;
    return addresses.create(attrs);
  });
```

and it works pretty well 🙂

**Comment by moogus** [comment]
I get this is an old post but for anyone that comes across this issue, add the `belongsTo` and happy days 🎉

```js
import { Model, belongsTo } from 'ember-cli-mirage';

export default Model.extend({
  author: belongsTo('user')
});
```
