### ISSUE TITLE
JSONAPI Compliant attributes' member names

### ISSUE THREAD

**Issue by ashrafhasson** [samselikoff/ember-cli-mirage#1159]
It appears that when creating a mirage model with attributes' member names starting and/or ending with `U+005F LOW LINE, “_”`, Mirage returns it dasherized, e.g., if I use `__id__` as a member key name, say for an internal property due to a dependency, Mirage is dasherizing it and returns `--id--`. I think this is not an issue unless I'm trying to play nicely with JSONAPI. Obviously, this is not JSONAPI compliant since the [specs mention hyphens and underscores should not constitute part of the name if they appear at the beginning or end of the member key name](http://jsonapi.org/format/#document-member-names). I believe this is mainly because when creating the model, the serializer is obviously not inspected (nor it should be, probably?) while the JSONAPISerializer simply dasherizes the model keys without inspecting whether the result is compliant.

What's the best approach here, should the current behaviour be allowed given Mirage's transparent treatment of the model properties or should JSON:API be enforced? Should the violating keys be allowed as is without [dasherizing](https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/serializers/json-api-serializer.js#L9-L11) but maybe a warning be generated pointing out there's a JSONAPI compliance violation if the `JSONAPISerializer` is in use? Should the model be created in the first place?

Thanks,

**Comment by samselikoff** [comment]
The approach here should be to customize the serializer's `keyForAttribute` hook
