### ISSUE TITLE
mirage-serializer blueprint should extend application serializer

### ISSUE THREAD

**Issue by scottkidder** [samselikoff/ember-cli-mirage#1165]
When running `ember generate mirage-serializer foo` I would expect the serializer to extend the Application serializer like mentioned in the docs. It may cause confusion that the blueprint doesn't follow this advice.

**Comment by acorncom** [comment]
That sounds like a good idea, would you mind sending in a PR to fix it?

**Comment by ChrisBarthol** [comment]
I'd like to take this up.
