### ISSUE TITLE
Associations not properly updated when Mirage is minified and uglified

### ISSUE THREAD

**Issue by DLiblik** [samselikoff/ember-cli-mirage#1168]
In the `model` class within Mirage, `save` makes a call to `_disassociateFromOldInverses()`.  This code is written to depend on a string constructor name for the association, as can be seen here in [model.js](https://github.com/samselikoff/ember-cli-mirage/blob/85a6ac052f38ffd80f41b6d8e87332a680d33740/addon/orm/model.js#L513).

The issue here is that in a prod build, minification comes up with wonderfully efficient names for parameters (like `t` in the `_savesBelongsToAssociations()` signature, which in turn becomes the constructor name) instead of 'HasMany` and as a result, associations are not being updated at all in this call.

Here is a screenshot in which a breakpoint shows the parameter `e` holding an object of `t` (this is the re-prettified minified and uglified (and hence borkified!) code):

![image](https://user-images.githubusercontent.com/4047997/29841941-4d98e188-8cd5-11e7-9660-a58cd6f7fd5a.png)

Mirage is not a production facility (typically) but thought it was worth raising.

**Comment by DLiblik** [comment]
For completeness, I have confirmed that compiling for production with minification disabled for vendor files does suppress the issue.

**Comment by acorncom** [comment]
This may have just been resolved. See https://github.com/samselikoff/ember-cli-mirage/issues/1092#event-1232447876

**Comment by DLiblik** [comment]
That definitely looks like it should do it, but I won't have time to test until early next week (not sure if there are other areas of Mirage that depend on constructor names - didn't do a search).

I will post back once I have a chance to re-run the test here.

Thanks for the #1092 ref.

**Comment by acorncom** [comment]
@Dliblik any updates here? I'll close for now but feel free to comment if we need to re-open ...

**Comment by DLiblik** [comment]
@acorncom a quick test appears to be fine based on changes in 60918b1 so I agree with the closure - thanks
