### ISSUE TITLE
hasMany polymorphic relationship error

### ISSUE THREAD

**Issue by jon-hall** [samselikoff/ember-cli-mirage#1175]
I had originally believed the issue I was getting was the same as #1154, but that's the same error message coming from a different location.

When using polymorphic relationships and having a serializer which has both `embed: true` and an `include` for the polymorphic `hasMany` field, mirage gets an error coming from the `camelize` call here:

```
// addon/serializer-registry.js
serializerFor(type, { explicit = false } = {}) {
  let SerializerForResponse = this._serializerMap && (this._serializerMap[camelize(type)]);
  // ...
}
```

The `type` is coming through `undefined` and `camelize` attempts to call `replace` on it, which causes an error.

This ultimately tracked back to the code trying to read the value of `type` from `modelName` on a `PolymorphicCollection`, which doesn't have that property.

Apologies for not including a reproduction twiddle but the boilerplate seems broken (get an error about it being a private gist), and attempting to use mirage 0.3.4 in ember-twiddle currently seems to get a build error for the addon.  There is already a PR in to fix this though (#1174), with a reproduction case added as a test.

**Comment by scottkidder** [comment]
I will test this tomorrow and hopefully we can GTM.
