### ISSUE TITLE
how to get file name via request

### ISSUE THREAD

**Issue by GrreyWang** [samselikoff/ember-cli-mirage#1177]
I upload a file via FormData object. How to get the file meta data (such as file name) in mirage ?

**Comment by acorncom** [comment]
https://emberobserver.com/addons/ember-file-upload has a built-in Mirage handler for helping work with form data and file uploads. You might try that or reference what is done there ... It's not built-in to Mirage though ...

I'll close this issue for now, please comment if we should re-open here
