### ISSUE TITLE
Acceptance tests timing out randomly

### ISSUE THREAD

**Issue by ashrafhasson** [samselikoff/ember-cli-mirage#1190]
I'm struggling to make my acceptance test more consistent and acceptable (time-wise). The test is rather simple, in fact I stripped the test down to a single case that does `assert.ok(true)` after the `visit()` helper and yet the test randomly times out or at best would pass after 16, 30 or 45 seconds. 

The test case does employ [ESA's `authenticatedSession()`](https://github.com/simplabs/ember-simple-auth#testing) test helper to authenticate the session then visit a protected route via ESA but also protected via a mixin that applies some route-permissions logic to establish whether the user can view the route and be redirected to index otherwise. This works perfectly fine when tested manually. In the test, however, it appears that the test is stuck after visiting the protected URL although I can see that the page was actually redirected as expected and the `currentURL` shows I'm at the intended target URL.

```
test('visiting /cash-register/show when logged in but have no permissions redirects to the / route', function(assert) {
  let securityGroup = server.create('securityGroup', {
    name: 'default', description: 'testers group',
    permissions: ['view-transactions']
  });
  let account = server.create('account', {subType: 'cash-register', securityGroup});
  let user = server.create('user', { securityGroups: [securityGroup] });

  let authData = {
    "user_id": user.id,
    "account_id": account.id,
    "authenticator": "authenticator:jwt",
    "exp": Date.now()/1000 + 500
  };

  let signedToken = generateJWTToken(authData);
  authData.token = signedToken;
  authenticateSession(this.application, authData);

  visit(`/cash-registers/${account.id}`);
  assert.ok(true);
});
```

Mirage's `server.logging=true` is set and all data requests are answered as per console log. I do have couple pending promises but at least one of which is related to the TestPromise being run.

The generateJWTToken has no promises, just flat functions.

![screenshot_2017-10-13_10-15-04](https://user-images.githubusercontent.com/1919410/31550500-8a1d1d2a-afff-11e7-81c8-ad02e6e1a74c.png)

I'm also calling `server.shutdown()` in the `beforeEach` hook and tried the `afterEach` hook of the test as well but that doesn't help.

I was using ember-cli 2.12.2 originally when the issue appeared (when I started testing!) and upgrading to 2.14.2 did improve the timing but not to the point where it's not longer visible.
Current stack of libs is:
Mirage 0.3.4
ESA 1.4.0
ember-cli 2.14.2
ember source 2.14.1
ember-data 2.13.1
jQuery 3.2.1
ember-simple-auth-token 2.1.0
node 8.6.0

I have seen similar issues discussed in #129 but couldn't get any of the suggestion to work for me. I have labelled all my promises so not sure what's pending or how to go forward from here.

Any help is appreciated.

Thanks,

**Comment by seansellek** [comment]
I am also seeing acceptance tests hanging whenever Mirage is involved. 

I have a simple test that looks like this:

```js
test('should display a message if no things are available', function(assert) {
  visit('');

  andThen(() => {
    assert.equal(find('[data-test-thing-monitor-no-things-found-message]').text(), 'No things are available to monitor.');
  });
});
```

and it works fine, but by adding:

```js
test('should display a message if no things are available', function(assert) {
  server.createList('thing', 4);
  visit('');

  andThen(() => {
    assert.equal(find('[data-test-thing-monitor-no-things-found-message]').text(), 'No things are available to monitor.');
  });
});
```

...the test hangs and never completes. Mirage's logging also shows that all requests resolve as expected.

**Comment by ro0gr** [comment]
Have you tried to enable "no try/catch" checkbox in the qunit interface in order to ensure you don't have exceptions swallowed by qunit?

**Comment by seansellek** [comment]
I've resolved the issue, turns out it was unrelated to mirage. When items populated the page, we'd kick off polling on their status, and that would cause the acceptance tests to wait indefinitely. We were able to work around this using `Ember.run.cancelTimers();`

**Comment by samselikoff** [comment]
I apologize for not responding to this!

I’m trying to get back on top of issues, so for now I’ll go ahead and close this issue since it's quite old.

If you’re still having trouble, please ping me here or on slack @samselikoff and I’ll be happy to reopen + discuss.
