### ISSUE TITLE
Reduce total number of CI builds.

### ISSUE THREAD

**Issue by rwjblue** [samselikoff/ember-cli-mirage#1192]
I do not believe there is any reason that we need to test _every_ supported Ember version on _every_ supported Node version. 

I think we could probably just default the node version testing to the most restrictive (Node 4) for the ember-try scenario tests (which is what the default ember-cli addon blueprint suggests), and then run the `fastboot` and `node` tests once for each Node version supported. This would take our total number of builds from 30 down to a much more manageable number...

**Comment by mixonic** [comment]
Indeed @rwjblue I expect we might get better milage out of testing various versions of Ember-Data instead of so many Node versions.

**Comment by samselikoff** [comment]
I definitely defer to yall here.
