### ISSUE TITLE
Default values as a part of a Ember data model

### ISSUE THREAD

**Issue by ondrejsevcik** [samselikoff/ember-cli-mirage#1195]
It would be nice to be able specify default test values inside my model instead of mirage factories. That way I wouldn't have to copy & paste my property names from model to factory and I would have all in one place. 

something like this...
```js
export default DS.Model.extend({
  name: DS.attr('string', {
    mirageConfig: {
        defaultValue() {
          return faker.name.findName();
        }
    }
  }),
})
```

**Comment by acorncom** [comment]
This doesn't sound like a good idea, as it mixes your test logic into your Ember Data models. While it might be convenient, mixing the two sounds like would lead to problems ...

**Comment by ondrejsevcik** [comment]
@acorncom you're right. Closing.
