### ISSUE TITLE
using fixture with reflexive relation throws model.hasInverseFor is not a function

### ISSUE THREAD

**Issue by edouard-lopez** [samselikoff/ember-cli-mirage#1196]
I have an _article_ model that is reflexive to itself through a `related_articles` fields. In order to have a finer control of the context in my tests, I want to use fixture.

**model**
```
// app/models/article.js
export default Model.extend({
  featured: attr('boolean'),
  related_articles: hasMany('article', { inverse: null })
});
```

**fixture**
```
// mirage/fixtures/articles.js
  export default [{
    id: 2,
    featured: true,
    related_articles: [1, 2]
  }];
```

**scenario**
```
// mirage/scenarios/default.js
export default function(server) {
  server.createList('category', 10);
  server.loadFixtures('articles');
}
```

### Test

```
test('has related-articles block', function(assert) {
  authenticate(this.application);
  server.loadFixtures('articles');

  visit('/app/articles/2');
  andThen(function() {
    let relatedArticlesBlock = document.querySelectorAll('.related-articles');
    assert.ok(relatedArticlesBlock.length);
  });
});
```

### Error
> Mirage: Your GET handler for the url /api/v2/employee/articles/2 threw an error: model.hasInverseFor is not a function

### Question

There is no related articles in the `related_articles` key returned by mirage. What's the matter?

**Comment by mickit** [comment]
Hello Edouardo, i am having this exact same issue.  Have you found an answer?  Thanks in advance for your help.

**Comment by edouard-lopez** [comment]
Nope, went back to use factories and the following syntax to create object in a more controlled way:

    // mirage/scenarios/default.js
    server.createList('article', 10, { pinned: true });

**Comment by mickit** [comment]
interesting...  that was my plan b also.  thank you for your response.

**Comment by eliasmelgaco** [comment]
try use `include` property in serializer:

```
// serializers/article.js
import { RestSerializer } from 'ember-cli-mirage';

export default RestSerializer.extend({
  include: ['related_articles']
});
```

```
// scenarios/default.js
let relatedArticles = server.createList('relatedArticle', 10);
let articles = server.create('articles', [ relatedArticles ]);
```
Tell me if you solve the problem.

see more options:
http://www.ember-cli-mirage.com/docs/v0.4.x/serializers/#serializeids

**Comment by samselikoff** [comment]
We fixed this in a recent release, could you try 0.4.4 and see if it fixes your bug?

**Comment by samselikoff** [comment]
Closing this as the original issue is quite old, but feel free to ping here and I can reopen if it's still an issue!

**Comment by ziali088** [comment]
I had this error because I was defining relationships in my mirage factories, when I didn't have to since I'm using JSONAPI and the models were created automatically by mirage.

So if you're using JSONAPI with Ember, no need to setup relationships in your mirage factories
