### ISSUE TITLE
`blogPost.comments` gives Collection instead of array

### ISSUE THREAD

**Issue by stephanebruckert** [samselikoff/ember-cli-mirage#1197]
In the doc for [Model](http://www.ember-cli-mirage.com/docs/v0.3.x/models/#associations) v0.3.x, in the `Association > hasMany` section it says:

```
blogPost.commentIds;                      // [1, 2, 3]
blogPost.commentIds = [2, 3];             // updates the relationship
blogPost.comments;                        // array of related comments   <------
blogPost.comments = [comment1, comment2]; // updates the relationship
blogPost.newComment(attrs);               // new unsaved comment
blogPost.createComment(attrs);            // new saved comment (comment.blogPostId is set)
```

`blogPost.commentIds` works well and returns an array.

However `blogPost.comments` doesn't give an array but a [Collection](http://www.ember-cli-mirage.com/docs/v0.3.x/collections/), which explains why we can't do `blogPost.comments.push(comment)`.

Should we update the doc or the code?

**Comment by samselikoff** [comment]
Good catch - it needs to be a Collection so empty arrays can be properly serialized.

Docs update would be great!

**Comment by stephanebruckert** [comment]
OK thanks, adding that to my todos

**Comment by erichonkanen** [comment]
by making it a collection it also means that computed properties that rely on the relationship do not work:

example:
```
foos: computed('foo.bars.[]', function() {
  return get(this, 'foo.bars').findBy('id', 'baz');
});
```
Will fail if a mirage model is used in an integration test.. this seems like an issue worth addressing, thoughts?

**Comment by jeffreybiles** [comment]
This is also causing an issue for me.  I found a "workaround" by relying on `models`, so @erichonkanen 's code would look like this:

```js
foos: computed('foo.bars.[]', function() {
  return get(this, 'foo.bars.models').findBy('id', 'baz');
});
```

However, that has the unfortunate side effect of breaking everything besides my tests.

Are there plans to change this behavior, or are there known (better) workarounds?

**Comment by samselikoff** [comment]
Hm... it looks like you're using Mirage models in Ember computed properties. Mirage models are just designed to help seed Mirage's database. The only way Mirage data should end up in an Ember app is via an API request. 

What are you doing here - passing a Mirage model into a component? If so there's a better way to do this.

**Comment by jeffreybiles** [comment]
I am indeed passing Mirage models into a component in my integration tests.

I know it's possible to pass POJOs into the component, but I was hoping to take advantage of Mirage's ability to generate relationships.  Is that possible?  If so, could you point me to where the better way is documented?

**Comment by lukemelia** [comment]
@jeffreybiles you might find this function useful, as we do:

```
import { run } from '@ember/runloop';

export function loadIntoStore(params, server, store) {
  let emberDataModels = {};
  for (var instanceName in params) {
    let mirageModel = params[instanceName];
    let emberDataModelName = mirageModel.modelName.dasherize();
    let emberDataPayload =server.serializerOrRegistry.serialize(mirageModel);
    run(() => {
     store.pushPayload(emberDataModelName, emberDataPayload);
    });
    emberDataModels[instanceName] = store.peekRecord(emberDataModelName, mirageModel.id);
  }
  return emberDataModels;
}
```

**Comment by samselikoff** [comment]
Great!

Keep an eye out for some new APIs to mirage coming soon that will make this easier, because really passing Mirage models/data directly to components shouldn't really be done. But I understand that it can make your life easier.

**Comment by jeffreybiles** [comment]
Awesome, looking forward to the new APIs!
