### ISSUE TITLE
Track requests with Pretender in test mode

### ISSUE THREAD

**Issue by DingoEatingFuzz** [samselikoff/ember-cli-mirage#1200]
By default Pretender tracks requests made during the lifespan of the Pretender server. This is a really handy way to spy on requests and assert behaviors in tests.

A simple example:

https://github.com/hashicorp/nomad/blob/master/ui/tests/acceptance/namespaces-test.js#L21-L28

A more complex example:

https://github.com/hashicorp/nomad/blob/master/ui/tests/acceptance/token-test.js#L45-L56

However, in #1137 `trackRequests` was hardcoded to be false.

I think the best way forward is to track requests in tests by default, don't track requests in dev by default, and expose a property like `server.logging` to control whether or not requests should be tracked.

**Comment by geekygrappler** [comment]
Fixed in #1217
