### ISSUE TITLE
`coalesce` shorthand option does not comply with JSON:API / ember-data

### ISSUE THREAD

**Issue by simonihmig** [samselikoff/ember-cli-mirage#1202]
The `coalesce` option of shorthand GET requests, introduced in #123 by @cibernox, expects query params in the form `?ids=1,3`. This however does not comply with the JSON:API [recommendation](http://jsonapi.org/format/#fetching-filtering) and the default serialization of the ember-data JSONAPI adapter's [`coalesceFindRequests`](https://www.emberjs.com/api/ember-data/2.16/classes/DS.JSONAPIAdapter/properties/coalesceFindRequests?anchor=coalesceFindRequests), which looks like `?filter[id]=1,3`.

It would be nice to have this match out of the box!

Changing that would probably not be very hard, but introduce a breaking change. Not sure how to solve this?
* do the change and accept a breaking change
* introduce another option like `coalesceWithFilter` (or whatever)
* use the filter-based serialization only when the `JSONAPIAdapter` is used for the given model. Would still be kind of a breaking change, although I am unsure if anybody was able to use the existing way with an JSON:API compliant API?

**Comment by simonihmig** [comment]
@samselikoff could I have your opinion on this? I might be able to contribute a PR, once the direction is clear. But this currently makes our tests fail, or test something that does not match the real world, so a bit pointless...

**Comment by cibernox** [comment]
When I implemented it, I was using the REST adapter, which [expects the current format](https://www.emberjs.com/api/ember-data/2.16/classes/DS.RESTAdapter/properties/coalesceFindRequests?anchor=coalesceFindRequests). I wasn't aware that JSONAPI expected a different one.

I think it the option could be the same (it could be renamed on both, that's fine) but should behave differently depending on the kind of mirage-adapter in use.

**Comment by simonihmig** [comment]
That would be the third option I mentioned. Sounds reasonable to me!
