### ISSUE TITLE
0.4.0 does not include relationships

### ISSUE THREAD

**Issue by kielni** [samselikoff/ember-cli-mirage#1204]
Upgrading from 0.3.3 to 0.4.0 broke my acceptance tests that use objects with `belongsTo` relationships. My tests fail when trying to navigate through the `belongsTo` because the relationships were not included.  For example, with a `bill` model that has `meter: belongsTo('meter')`, `bill.meter.id` is undefined, because the `meter` relationship was not included in the response.

I tried Mirage Boilerplate Twiddle but got an alert that "The gist is missing or secret"

My `bill` model looks like this:
```
  meter: DS.belongsTo('meter'),
  initial: DS.attr('date),
```

My real API and Mirage 0.3.3 ([_getResourceObjectForModel](https://github.com/samselikoff/ember-cli-mirage/blob/ee0efc89615c0ae0553a5407286fcde4f17d7382/addon/serializers/json-api-serializer.js#L167)) return data like this:

```
{
    "type": "bill-summary",
    "attributes": {
        "initial": "2014-07-02"
    },
    "id": "4170595602188",
    "relationships": {
        "meter": {
            "data": {
                "type": "meter",
                "id": "1971049867684"
            }
        }
    }
}
```

With 0.4.0, there are no relationships included because [_maybeAddRelationshipsToResourceObjectForModel](https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/serializers/json-api-serializer.js#L181) includes them only if `hasLinksForRelationship`, `alwaysIncludeLinkageData`, or `this._relationshipIsIncluded`  Data returned by Mirage 0.4.0:

```
{
    "type":"bill-summary",
    "id":"1",
    "attributes": {
        "initial": "2014-07-02"
    }
}
```

My real API does not add links or include relationships for this model, and `alwaysIncludeLinkageData`is [defaults to false](https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/serializers/json-api-serializer.js#L221)

I think this changed here: https://github.com/samselikoff/ember-cli-mirage/commit/ab87ac40747d1f46e8b5d6fa22bcfa133271a07f  I expect can work around this by setting `alwaysIncludeLinkageData` on every model with `belongsTo` relationships, but I'd rather that my Mirage API responses match my real API responses as much as possible.

**Comment by riklaunim** [comment]
I have it too. When I create a "foo" that has FK to "bar" then with 0.4.0 foo.bar will be undefined and tests will fail.
```
let bar = erver.create('bar', { name: 'A bar' });
server.create('foo', { slug: 'abc', bar });
```

**Comment by seansellek** [comment]
I am seeing this as well. `hasMany` relationships seem to be included no problem, but only `belongsTo` relationships are failing to be included in responses.

**Comment by scottkidder** [comment]
I can confirm that @seansellek above fix works for me and I was able to get to 0.4.0.

**Comment by iballack** [comment]
I spent so many hours trying to fix the relationship issues and finally this thread saves my day!!
@seansellek solution is working from my side too!

**Comment by TayHobbs** [comment]
I also spent a lot of time trying to solve this exact issue. The fix provided worked for me and I have made a PR (#1252) to add it to the changelog.

**Comment by samselikoff** [comment]
Sorry all, this was a bad change. Data linkage was breaking other folks' apps in different ways but I need to communicate all my findings better.

I'll address this shortly

**Comment by erichonkanen** [comment]
im not sure if related but im seeing this on 4.1.0 when I return a user model in my mirage route for acceptance test (user has belongsTo and hasMany)

![image](https://user-images.githubusercontent.com/230757/35548512-be4f8422-0534-11e8-8723-03dab6ca6221.png)

**Comment by samselikoff** [comment]
I've addressed this in a blog post: http://www.ember-cli-mirage.com/blog/2018/02/01/changing-mirages-default-linkage-data-behavior/

and it was also added to the CHANGELOG.

Sorry again for the confusion + thanks for raising this issue everyone!

**Comment by erichonkanen** [comment]
@samselikoff after further looking last night I was able to figure out my issue was related to a hasMany on a model with irregular pluralization https://github.com/samselikoff/ember-cli-mirage/issues/1258, maybe there's already a way to handle that?

**Comment by georgevanvliet** [comment]
@samselikoff Is the ```alwaysIncludeLinkageData``` property omitted from the serializer documentation by intent?
It is only mentioned in your blogpost. Took me a while to run into the blogpost in a serendipitous way, others might not be so lucky.

**Comment by samselikoff** [comment]
Nope it’s not, we need to document it. I’ve just fallen behind
