### ISSUE TITLE
autoCreateRelatedRecord

### ISSUE THREAD

**Issue by caseywatts** [samselikoff/ember-cli-mirage#1205]
It took me a while of googling and asking around today to figure out how to have mirage auto-create relationships for me. I don't have to use `afterCreate`, and I don't have to do it manually everywhere.

The `association()` helper can do it! 🎉 
In my head I think of this helper as `autoCreateRelationshipIfNeeded()` or `autoCreateRelatedRecord` - I think that's its one purpose.

Would it make sense to alias or rename `association` to something more specific, or does it do more than this one thing?

**Comment by caseywatts** [comment]
I think "if needed" because the auto-creation doesn't happen if we pass in an instance during the `create()` call - we can overwrite this default value.

**Comment by samselikoff** [comment]
I agree the term is a bit vague. It was borrowed from factory_girl (the thoughtbot library).

I wonder if more info in the `Factories` section of the docs would have helped?

**Comment by ro0gr** [comment]
I also didn't know about this "association" feature despite the fact I've carefully read the docs recently. Agree that docs update would be helpful.

I like a declarative nature of the "association" name.

**Comment by ro0gr** [comment]
Actually `association` is well explained in the Factories API section - http://www.ember-cli-mirage.com/docs/v0.4.x/factories/#factories-and-relationships

I think [Seeding your database](http://www.ember-cli-mirage.com/docs/v0.4.x/seeding-your-database/) has to be updated to mention `assotiation` helper.

**Comment by samselikoff** [comment]
Going to stick with the name and close this for now, but if anyone has any specific docs updates they'd like to suggest/PR I'm happy to merge!
