### ISSUE TITLE
Consider a Noop Initializer when mirage is not enabled in a build

### ISSUE THREAD

**Issue by kennethdavidbuck** [samselikoff/ember-cli-mirage#1210]
Hey, first off, thank you for all the great work! 

I just came across an issue where one of my apps initializers had to run before the ember-cli-mirage initializer (to seed momentjs with a predefined "now"). Doing so created a scenario where everything would be fine in both the test and development builds (all tests green), but the apps production build would fail due to a missing initializer. I did some investigating and I believe it happens for the following reason:

In development/test builds ember will catch missing initializers that are referenced in an initializers "before" and "after" keys, however because mirage is excluded when its enabled flag is set to false, it is able to pass the assertions and then it disappear in a production build.

To get around the issue I am currently conditionally setting the before key in my apps initializer based on the ember-cli-mirage enabled configuration value. While this works, it seems like it would be better if consumers didn't have to think about this detail. One way to handle this could involve a noop initializer for the cases where mirage is excluded from the builds.

Please let me know what you think

Thanks!

**Comment by rwjblue** [comment]
Agreed. We should always have an initializer, it should just do nothing when not included...

**Comment by kennethdavidbuck** [comment]
@rwjblue thank you for the quick reply. If there is no immediate rush, then I would be up for attempting a PR for this. It looks like the initializer is already set up to handle the case where mirage is disabled, so I imagine there just needs to be a higher degree of specificity when excluding files from the build tree?

**Comment by rwjblue** [comment]
Seems reasonable, though I haven't recently reviewed the build configuration here so am not 100% certain.

**Comment by kennethdavidbuck** [comment]
Ok, I will take a look at it and see how far I can get. Thanks again.

**Comment by kennethdavidbuck** [comment]
@rwjblue I made a first attempt at addressing this in #1236 and was wondering if you wouldn't mind taking a look at it / giving me some feedback?
