### ISSUE TITLE
Files are not created when using Yarn

### ISSUE THREAD

**Issue by ryanlitalien** [samselikoff/ember-cli-mirage#1218]
When using yarn to install, `yarn add ember-cli-mirage`, yarn doesn't create the necessary files. I had to install it again via `ember` to create the files. Should there be documentation or a note about this?

```
$ ember install ember-cli-mirage
Yarn: Installed ember-cli-mirage
installing ember-cli-mirage
  create /mirage/config.js
  create /mirage/scenarios/default.js
  create /mirage/serializers/application.js
Installed addon package.
```

**Comment by mupkoo** [comment]
Using `ember install` will trigger the default blueprint of the addon. So doing:

```
ember install ember-cli-mirage
```

does

```
yarn add ember-cli-mirage
ember generate ember-cli-mirage
```

This is true for all addons.

**Comment by ryanlitalien** [comment]
Ah, thank you for clarifying @mupkoo.
