### ISSUE TITLE
Wrong way of passing a Mirage model to test a component?

### ISSUE THREAD

**Issue by stephanebruckert** [samselikoff/ember-cli-mirage#1219]
I am passing a fake model to my component, this way:

```
test('it renders', function(assert) {
  let user = window.server.create('user');
  let inventory = window.server.create('inventory', { title: 'My Inventory', users: [user] });
  this.set('inventory', inventory);
  this.render(hbs`{{inventories/edit-inventory model=inventory}}`);

  // asserts.equal...
});
```

In a computed property, I can see that my model is a Mirage Collection:

```
Collection {modelName: "user", models: Array(1)}
modelName
models
length
__proto__
```

... while out of the tests it's expected to be a Class:

```
Class {__ember1510770708339: null, _super: ƒ}
content
_super
isDestroyed
isDestroying
__OWNER__ [id=__ember15107707083391008093622924]
__ember1510770708339
_debugContainerKey
get content
set content
__proto__
```

It means that I need 2 different pieces of code for prod/tests.

What am I doing wrong?

**Comment by mupkoo** [comment]
In your test case `inventory` is a Mirage Model, not an ember object or ember data object. While you are using Mirage in dev mode, those models gets translated into a JSON format, which later turns into a Ember Data Models, when you call `this.store.findRecord('inventory', 1)`.

What you can do here, is just pass plain JavaScript objects in your tests.

```javascript
let user = { name: 'Stephane' };
this.set('inventory', { title: 'My Inventory', users: [user] });
this.render(hbs`{{inventories/edit-inventory model=inventory}}`);
```

**Comment by stephanebruckert** [comment]
@mupkoo good, simple idea, that works! thanks
