### ISSUE TITLE
Mirage: You're instantiating a foo that has a barId of bar, but that record doesn't exist in the database.

### ISSUE THREAD

**Issue by yatinranadive** [samselikoff/ember-cli-mirage#1231]
I am getting an error from Mirage when I have a field which ends with ***Id** and there is a matching **belongsTo** relationship field on the model.

E.g. 
```javascript
// Parent model: foo.js
import DS from 'ember-data';
export default {
  barId: DS.attr('string'),
  bar: DS.belongsTo('bar')
};
```
```javascript
//Child model: bar.js
import DS from 'ember-data';
export default {
  baz: DS.attr('string'),
};
```

And my factory for foo.js
```javascript
import { Factory } from 'ember-cli-mirage';

export default Factory.extend({
  // Setting value of barId throws error.
  //barId: 'something'
});
```

I have found the culprit of this error in repository: https://github.com/samselikoff/ember-cli-mirage/blob/5a40018951c7d5db2245c27ae364972cdc88ce60/addon/orm/associations/belongs-to.js#L33

As it is trying to pull up relationship which does not exist in store and throws an exception `Mirage: You're instantiating a foo that has a barId of bar, but that record doesn't exist in the database.`

**Comment by imalexsq** [comment]
I'm experiencing the same issue. Is there a workaround other than renaming my model's properties?

**Comment by yatinranadive** [comment]
Unfortunately I decided to rename property name to bypass this issue. Not
idea & long term fix but got me unblocked in this scenario.

**Comment by samselikoff** [comment]
Sorry about the delayed response!

Assuming that `barId` is in fact `bar.id`, I would avoid storing a separate `barId` field in Mirage's database, and instead use the serializer layer to add the field at serialization time, derived from the actual `bar` relationship. That way the two will never be out of sync.

You'll also need to do some work on the receiving end if you're going to take data from a request payload and CRUD your Mirage models. I would use `normalizedRequestAttrs()` for this, and then strip the `barId` from the request.

Can I ask how you're using `barId`? Typically you'd access the id of a relationship in Ember via `this.get('bar.id')`, and I think you'll save yourself a lot of headache if you structure things like that.

**Comment by samselikoff** [comment]
Closing this issue for now but let me know if you have any more questions!
