### ISSUE TITLE
[Feature request] framework independent version?

### ISSUE THREAD

**Issue by QuantumInformation** [samselikoff/ember-cli-mirage#1233]
I would love to have this functionality to run a React app against. Any plans to make this framework independent?

**Comment by acorncom** [comment]
@QuantumInformation believe https://github.com/cowboyd/mirage-server is what you're after?

**Comment by QuantumInformation** [comment]
Wow will check it out thx!

**Comment by QuantumInformation** [comment]
Is anyone actually using it
https://github.com/cowboyd/mirage-server/issues
