### ISSUE TITLE
Polymorphic collection is not passed to application serializer

### ISSUE THREAD

**Issue by janmisek** [samselikoff/ember-cli-mirage#1242]
PolymorphicCollection (`ember-cli-mirage/orm/polymorphic-collection`) returned from handler is not passed to serializer. 

Cause is `SerializerRegistry.serialize` and `SerializerRegistry._isCollection`. 

I would suggest to pass polymorphic collection to default `application` serializer. I can prepare pr if agreed.

**Comment by samselikoff** [comment]
Seems problematic, a PR with a test would be very helpful! Thanks!

**Comment by samselikoff** [comment]
@janmisek what serializer are you using? JSONAPISerializer?
