### ISSUE TITLE
Any plans to make mirage agnostic from ember?

### ISSUE THREAD

**Issue by nicsefer** [samselikoff/ember-cli-mirage#1243]
@samselikoff It'll be great if it could be used independent of ember. 
It's the best jsonapi mock tool i found, but unfortunately ember isn't in our stack :(

Thanks in advance!

**Comment by acorncom** [comment]
@nicsefer more details available at https://github.com/samselikoff/ember-cli-mirage/issues/1233 Some folks are working on it 😀  (but it may be in rough shape) will close here for now

**Comment by cowboyd** [comment]
Hi @nicsefer 

I've extracted Mirage into its own vanilla JS library and have been using it for about 6 months now. https://github.com/cowboyd/mirage-server

**Comment by QuantumInformation** [comment]
How is it all going? We want to use Mirage on a react project.

**Comment by samselikoff** [comment]
@QuantumInformation Hi there - not at this point in time! I'd say @cowboyd's fork is your best bet.

**Comment by cowboyd** [comment]
@QuantumInformation We're maintaining a cross-framework fork of mirage over at [Bigtest](https://bigtestjs.io)  https://github.com/bigtestjs/mirage

**Comment by QuantumInformation** [comment]
hows it all going?

**Comment by samselikoff** [comment]
@QuantumInformation Cowboy's fork still works, but we have started working on this. We have a version [here](https://github.com/miragejs/server) that you can keep your eyes on. The current release there works in React and Vue apps but there's some more cleanup work to get it properly extracted and rework Ember CLI Mirage to consume it.

The current priority is to release Ember CLI Mirage 1.0, including taking care of any outstanding bugs. Then we'll be able to shift focus to the proper extraction.

**Comment by QuantumInformation** [comment]
awesome thanks!!!!

Kind regards

Nikos Katsikanis
