### ISSUE TITLE
links does not work

### ISSUE THREAD

**Issue by erichonkanen** [samselikoff/ember-cli-mirage#1246]
Just tried to return `links` with my jsonapi collection but it ends up as an empty object. My ember-data call is to `store.query` in my route.

serializer for model:
```
import ApplicationSerializer from './application';

export default ApplicationSerializer.extend({
  links() {
    return { next: 'foo' };
}})
```

using latest mirage // ember // data
  
EDIT: I discovered that maybe I was confusing the concept of `links` with that of relationship links, I am trying to return `links` metadata key as sibling to `data` and `include`, seems like [this](http://www.ember-cli-mirage.com/docs/v0.3.x/serializers/#serializeresponse-request) is where to add it?

**Comment by samselikoff** [comment]
Correct, there's no first-class API for adding metadata at the moment, so the `serialize` hook is your best bet.
