### ISSUE TITLE
How to handle pagination or dynamically load nth set of different data?

### ISSUE THREAD

**Issue by erichonkanen** [samselikoff/ember-cli-mirage#1247]
How can I make e.g. the first call to `GET /foo` return 10 Foo items, and the 2nd or nth call to `GET /foo` return a new set of Foo items? That's the most simple use case, in reality it'd also be nice to have it based on a query param (cursor pagination in my case)

**Comment by samselikoff** [comment]
I'd do something like this:

```
this.get('/posts', (schema, request) => {
  let page = request.queryParams.page;
  let offset = page - 1;
  let begin = 0 + (10 * offset);

  return schema.posts.slice(begin, begin + 10);
});
```

**Comment by samselikoff** [comment]
Let me know if you need more help!

**Comment by erichonkanen** [comment]
thanks!

**Comment by allthesignals** [comment]
Be sure to use `query` instead of `findAll`. I think the only QP `findAll` serializes is `include=`.
