### ISSUE TITLE
Mirage boilerpate twiddle - gist is missing or secret

### ISSUE THREAD

**Issue by myartsev** [samselikoff/ember-cli-mirage#1249]
The boilerplate twiddle used to file Mirage bugs is not working: https://ember-twiddle.com/072de99410f21ff42db8264bd9665ca3

_The gist is missing or secret_

**Comment by samselikoff** [comment]
Thanks - shoulld be fixed!

https://ember-twiddle.com/eedfd390d8394d54d5bfd0ed988a5d0f?openFiles=templates.application.hbs%2C
