### ISSUE TITLE
Ember 2.18: unable to manually start Mirage for integration tests

### ISSUE THREAD

**Issue by myartsev** [samselikoff/ember-cli-mirage#1250]
It's been a while since I've used Ember, so while running through [the tutorial](https://guides.emberjs.com/v2.18.0/tutorial/ember-data/), I noticed that all the acceptance tests were failing once Mirage is used.

Looking into it, the solution appears to be to manually start mirage per [these instructions](http://www.ember-cli-mirage.com/docs/v0.3.x/manually-starting-mirage/).
However, the import path _super-rentals/initializers/ember-cli-mirage_ is not valid. I assume there is supposed to be an _initializers_ folder and an _ember-cli-mirage_ file? That is not the case with a newly created Ember 2.18 app.

I don't remember running into this issue last time I went through the tutorials...

**Comment by samselikoff** [comment]
Hm, you definitely shouldn't have to manually start Mirage for this. Could you upload your repo?

**Comment by myartsev** [comment]
I don't have it in this state anymore, but it's not hard to reproduce, I literally just followed the official Ember tutorial up to this point: https://guides.emberjs.com/v2.18.0/tutorial/ember-data/

Should take 5 minutes or so to get there, let me know if you'd rather prefer I upload a repo.

**Comment by samselikoff** [comment]
I just followed the tutorial and Mirage is running during the tests

![image](https://user-images.githubusercontent.com/2922250/34949082-0eb1edaa-f9dd-11e7-8831-f50d1c26cf31.png)

![image](https://user-images.githubusercontent.com/2922250/34949093-19acdd46-f9dd-11e7-933b-af646176e825.png)

If you can upload your exact repo it'd be easier to see what's going on

**Comment by myartsev** [comment]
Sure thing; here you go: https://github.com/myartsev/ember-cli-mirage-1250

[This](https://github.com/myartsev/ember-cli-mirage-1250/commit/840df8f30f8c6152dd3139d4a7cfd132a62daa04) is the tutorial code up to the point before switching over to mirage
[This](https://github.com/myartsev/ember-cli-mirage-1250/commit/6282ea973af270699819d91aeba26ba518bf760a) is when the route is updated to fetch data from Mirage. Acceptance test start to fail due to a 404 error when fetching data.

![screenshot_2018-01-16_17-19-04](https://user-images.githubusercontent.com/4885345/35015340-f6f4b5d4-fae1-11e7-8b2b-8dc51209c278.png)

Note that outside of the tests, Mirage is working as expected
![screenshot_2018-01-16_17-24-03](https://user-images.githubusercontent.com/4885345/35015373-1f2fc7f0-fae2-11e7-8dac-c3dec3419dea.png)

**Comment by myartsev** [comment]
Wait, I understand now.
Add-ons need the Ember server to be restarted to include a recently added add-on to the build.

The documentation mentions this and tells you to restart the main ember server `ember s`  but doesn't mention restarting `ember test --serve`. Duh. Sometimes it's the simple things!

My apologies for the churn here...

**Comment by acorncom** [comment]
@myartsev No problem, glad you got it figured out! 😀 I'll go ahead and close this for now.
