### ISSUE TITLE
`include` as function in serializer not supported anymore?

### ISSUE THREAD

**Issue by deepflame** [samselikoff/ember-cli-mirage#1251]
version: 0.4.1

Hi there!

After upgrading I am running into an issue with serializers. It seems that "`include` as functions" is not supported anymore.

I get the following error:
<img width="519" alt="screen shot 2018-01-18 at 13 52 23" src="https://user-images.githubusercontent.com/91208/35099068-ebe0124e-fc56-11e7-9d39-9a61f4938622.png">

which is in code (json-api-serializer):
```javascript
  _relationshipIsIncluded(relationshipKey) {
   [...]
    } else {
      return this.include.includes(relationshipKey);
    }
  },
```
https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/serializers/json-api-serializer.js#L203

Is this a bug or was this feature removed? It is still in the 0.3 docs though.

Thanks!
Andreas

**Comment by samselikoff** [comment]
Looks like a bug
