### ISSUE TITLE
'this' undefined from component integration test?

### ISSUE THREAD

**Issue by stephanebruckert** [samselikoff/ember-cli-mirage#1256]
I figured this issue between ember and ember-cli-mirage could have its place here, as well as on https://github.com/emberjs/ember.js/issues/16052 and on https://stackoverflow.com/questions/48359509/this-undefined-only-from-component-integration-test.

This is a component that will need `this` at some point:

    export default Component.extend({
      filteredSubs: computed.filter('model.subs', function() {
        // this will always return true in development http://localhost:4200/dummy
        // but will always return false in test because 'this' becomes undefined
        return this;
      })
    });

`Dummy` has a one-to-many relationship to `Sub`:

    export default Model.extend({
      subs: hasMany('sub')
    });

    export default Model.extend({
      dummy: belongsTo('dummy')
    });

This test fails but shouldn't:

    test('it renders', function(assert) {
      let dummy = server.create('dummy');
      server.create('sub', { dummy });
    
      this.set('dummy', dummy);
      this.render(hbs`{{show-dummy model=dummy}}`);
    
      assert.equal(this.$().text().trim(), 'Hi! There are 1 sub-dummies');
    });

> not ok 13 Chrome 63.0 - Integration | Component | show dummy: it renders
>
> actual: Hi! There are 0 sub-dummies
>
> expected: Hi! There are 1 sub-dummies

---------

The issue has been isolated in a new repo: https://github.com/stephanebruckert/ember-bug-16052

- The 4th commit (https://github.com/stephanebruckert/ember-bug-16052/commit/8bbacf9136a755a5fb87827e5b87da1b8ec61e80) shows that `this` is available as expected.
- The 5th commit (https://github.com/stephanebruckert/ember-bug-16052/commit/c00ec8f4a35f0344486615984a583c7ac643950d) shows that `this` is not available anymore, as soon as a relationship `sub-dummy` is added to my main model `dummy`.

Any help is very much appreciated! Thank you

**Comment by luxferresum** [comment]
As explained on SO the `this`-context is lost on [`.filter()`](https://github.com/samselikoff/ember-cli-mirage/blob/6a9c8489368c86af4ca4b2c15052aff4ebbe4303/addon/orm/collection.js#L131) for the `Collection` type. This could be improved, but I'm not sure that it qualifies as a bug, because I'm not sure that this qualifies as public API.

**Comment by stephanebruckert** [comment]
@samselikoff what do you think about this? I could definitely go over my issue and use 

```
filteredSubs: computed('dummy.subs', function() {
    return this.get('dummy.subs').filter(s => s);
})
```

instead of 

```
filteredSubs: computed.filter('model.subs', function() {
    // this will always return true in development
    // but will return false in the tests because this === undefined
    return this;
})
```

but do you think that [`.filter()`](https://github.com/samselikoff/ember-cli-mirage/blob/6a9c8489368c86af4ca4b2c15052aff4ebbe4303/addon/orm/collection.js#L131) should not loose the context for `this`?

Thanks

**Comment by samselikoff** [comment]
@stephanebruckert sorry about the delayed response!

To answer the question, Mirage should not be used in this manner:
```
let dummy = server.create('dummy');
this.set('dummy', dummy);

this.render(hbs`{{show-dummy model=dummy}}`);
```
Mirage models just exist to help seed Mirage's database with data. The only way data from Mirage should get into your application is via an ajax request. 

This makes integration and unit tests more difficult to use Mirage in. We are planning on adding APIs soon for making this easier. In the meantime, check out [this helper](https://gist.github.com/samselikoff/b00b5a190321c8236ee0e0fab200bf65) which would let you get Ember Data models from Mirage-created data.
