### ISSUE TITLE
Does not play nicely with rfc232/rfc268 tests

### ISSUE THREAD

**Issue by bendemboski** [samselikoff/ember-cli-mirage#1257]
The new test framework ([rfc232](https://github.com/emberjs/rfcs/blob/master/text/0232-simplify-qunit-testing-api.md)/[rfc268](https://github.com/emberjs/rfcs/blob/master/text/0268-acceptance-testing-refactor.md)) runs initializers differently than the older `moduleFor*` tests, and is problematic for how `ember-cli-mirage` sets itself up. Specifically, it can cause the multiple pretender instances warning, and can leak state between tests.

## Old tests
In the old tests, each individual test would have its own mirage server instance.

### integration & unit
In old-style integration/unit tests, the test framework would not run any initializers, so the test itself would have to invoke the initializer and shut down the server [manually](http://www.ember-cli-mirage.com/docs/v0.3.x/manually-starting-mirage/).

### acceptance
In old-style acceptance tests, initializers would run before each test, so `ember-cli-mirage`'s initializer would run before each test, and its blueprint would cause the server to be shut down [after each test](https://github.com/samselikoff/ember-cli-mirage/blob/master/blueprints/ember-cli-mirage/index.js#L53). 

## New tests
There are no longer any relevant-to-this-issue distinctions between the various types of tests -- they all behave the same with respect to initializers. That behavior is that, while instance initializers run before each test, initializers just run before the first test in the entire test run. `destroy-app.js` is no longer used, so `ember-cli-mirage`'s current blueprint has no effect on these tests. This causes a couple of problems:

1. If you have a mix of old and new-style tests, you'll probably get a whole bunch of multiple pretender instance warnings since the first new-style test that runs will create a mirage server instance and never shut it down, so every old-style test that sets its own up (either via the initializer called from a `moduleForAcceptance` test or manually in a unit/integration test) will create a "second" pretender instance.
2. If all of your tests are new-style tests, changes to the mirage database and routes dynamically created in one test will persist into other tests because it's one long-lived instance that is never shut down.

## Possible solutions
1. Change the server from being a standalone object to a singleton (`service:mirage`?) registered in, and created out of, the container. This will ensure that it is shut down when the application is shut down. Then change the initializer that creates it to be an instance initializer. That way it will be created before each test, and shut down after each test like it used to be. This would have the side benefit of allowing users like myself that aren't fond of globals to access the server by just looking it up in the container (but it could still set itself as a global to preserve compatibility).
2. Implement some mechanism for resetting the mirage server to its initial state and implement an instance initializer that does that.
3. Explore other ways of running code after each test to shut down/reset the mirage server. This could be blueprint code that detects QUnit vs Mocha and adds global after-test behavior to them, or some other mechanism that I'm not aware of, or that would have to be implemented in `@ember/test-helpers`. This also might involve changing the existing initializer to an instance initializer.

My strong preference is (1), but I don't know the history of how the mirage setup code came to be how it is today, so maybe there are reasons to not make it a container object?

**Comment by erichonkanen** [comment]
does this imply that in newer style tests mirage may not work or should in theory have issues? just spent time setting up mirage for acceptance testing using latest/new style tests etc

**Comment by bendemboski** [comment]
I haven't actually seen any issues arising from the multiple pretender instances problem, but if you have tests that rely on the clean state of the mirage server, then you will have issues. For example, suppose you have a blog route that fetches all blogPost models and displays them in a list, and you have a test that uses mirage to create three blogPost records, activates the route and verifies that there are three list items. If you have another test running earlier that uses mirage to create a blogPost model, it will "leak" into the blog route test and the test will fail because it will see four models (the model the other test created plus the three it created).

Similarly if a test manually overrides a configured route handler, e.g. to test error responses.

**Comment by bendemboski** [comment]
FWIW I worked around this issue by implementing an instance initializer that looks like this:

```javascript
import Ember from 'ember';
import Service from '@ember/service';

//
// This is a workaround for https://github.com/samselikoff/ember-cli-mirage/issues/1257
//
export function initialize(application) {
  if (Ember.testing) {
    if (!window.server) {
      application.resolveRegistration('initializer:ember-cli-mirage').initialize();
    }

    application.register('service:mirage-workaround', Service.extend({
      willDestroy() {
        window.server.shutdown();
        window.server = null;
        this._super(...arguments);
      }
    }));
    application.lookup('service:mirage-workaround');
  }
}

export default {
  name: 'mirage-workaround',
  initialize
};
```

**Comment by erichonkanen** [comment]
ok I see thanks for the info! yeah I can see how the test bleeding is a problem...

**Comment by CvX** [comment]
@bendemboski which ember version does this workaround run on? On 2.18 `application` does not have the `lookup` method.

**Comment by CvX** [comment]
Whoops, my bad. Generated an initializer instead of instance-initializer…
The workaround works great!

**Comment by erichonkanen** [comment]
@bendemboski implemented your solution and it seemed to work but then I added a 3rd acceptance test file and now I'm seeing errors that seem to only happen when running `ember t`.. the individual acceptance test files pass...

I get e.g. `TypeError: Cannot read property 'querySelectorAll' of null` which is odd and makes it seem like one of the tests doesn't have it's element set? not even sure what's going on

**Comment by bendemboski** [comment]
@erichonkanen I can't think of how that would be caused by this workaround or anything else mirage-related...maybe a stack trace would help?

**Comment by Turbo87** [comment]
FWIW this is what we're doing in some projects that use pretender directly instead of mirage. I'm assuming mirage could provide a similar `setupMirage()` function that sets up and tears down the server correctly.

```js
export function setupPretender(hooks) {
  hooks.beforeEach(function() {
    this.server = new Pretender();
  });

  hooks.afterEach(function() {
    this.server.shutdown();
  });
}
```

**Comment by Turbo87** [comment]
forgot to mention how to actually use it...

```js
module('Acceptance | whatever', function(hooks) {
  setupApplicationTest(hooks);
  setupPretender(hooks);

  test('it works', function(assert) {
    assert.ok(this.server);
  });
});
```

the above pattern should also mostly be compatible with `ember-mocha` though in that case `hooks` would default to `self` as `before/afterEach` are globals in Mocha

**Comment by balinterdi** [comment]
At the same time, I came with a solution that manually truncates the database after each test, and it works great:

```js
module('Acceptance | Buy DogeCoin', function(hooks) {
  hooks.afterEach(function() {
    server.db.emptyData();
  });
 (...)
}
```

The real solution, I think, is along the lines of the initializer of what @bendemboski describes above, this is just a (rather simple, I think) workaround.

**Comment by paulcwatts** [comment]
I've used the same workaround as @Turbo87 suggested. First, I disable Mirage globally in environment.js, then I have a setup method:

```js
import { startMirage } from '../../initializers/ember-cli-mirage';

export default function(hooks) {
  hooks.beforeEach(function() {
    this.server = startMirage();
  });

  hooks.afterEach(function() {
    this.server.shutdown();
  });
}
```

Then I use it as:

```js
module('Acceptance | whatever', function(hooks) {
  setupApplicationTest(hooks);
  setupMirage(hooks);

  test('it works', async function (assert) {
     this.server.create(....);
  });
});
```

**Comment by bendemboski** [comment]
If anybody interested in this issue has the expertise and willingness to help me figure out why the fastboot tests are failing in #1263 (https://travis-ci.org/samselikoff/ember-cli-mirage/jobs/342215170) or point me in a debugging direction (I know almost nothing about fastboot) I'd be grateful.

**Comment by simonihmig** [comment]
@bendemboski I would *guess* that some browser-only API gets hit in one of the new/changed initializers. Wrapping in a `if (typeof FastBoot === 'undefined') {}` check (or an early return) would fix that.

Also it might be useful to add more debugging output to the fastboot tests, see https://github.com/kaliber5/ember-bootstrap/blob/master/config/ember-try.js#L213

If that doesn't help, feel free to ping me, I can take a deeper look then!

**Comment by ajcolter** [comment]
What was the resolution here? Is there a `setupMirage()` that I can import from `ember-cli-mirage` in my tests? It would be nice to not have to roll my own.

**Comment by bendemboski** [comment]
@ajcolter `import setupMirage from 'ember-cli-mirage/test-support/setup-mirage';`

**Comment by musaffa** [comment]
@ajcolter It looks like your suggested approach doesn't work with Mocha.

@Turbo87 What does `self` for Mocha mean? Can you please suggest the Mirage setup for Mocha?

Currently I'm using this approach for Mocha:
```javascript
// setup-mirage.js
import { startMirage } from 'web-app/initializers/ember-cli-mirage';

export default function setupMirage(hooks) {
  hooks.beforeEach(function() {
    hooks.server = startMirage();
  });

  hooks.afterEach(function() {
    hooks.server.shutdown();
    delete hooks.server;
  });
}

// in an acceptance test file
describe('Acceptance: X', function() {
  setupApplicationTest();
  setupMirage(this);
  ...
});
```

**Comment by Turbo87** [comment]
@musaffa `self` is usually `window` in the browser

I'm not sure if `this.beforeEach()` is a thing in Mocha, you should probably use the global `beforeEach()` function provided by Mocha

**Comment by musaffa** [comment]
Both `this.beforeEach()` and `self.beforeEach()` work in Mocha.
