### ISSUE TITLE
[Feature request] Persist DB in localStorage

### ISSUE THREAD

**Issue by cibernox** [samselikoff/ember-cli-mirage#126]
Just a random idea I might be pursuing in the next days. 

I've been working in a feature that requires me to pass though a few forms back and forward, and when I change a single line of CSS live-reload kicks in and I'm back on the square one (I'm aware I can disable live-reload)

Thinking about adding an opt-in configuration option to persist the entire state of the DB to localStorage after each insert/update operation when I want a bit of persistence.

Thoughts?

**Comment by samselikoff** [comment]
Um, would be amazing. I had a feeling this would be an eventual part of
mirage. I'm getting closer to having models done and there will be a slight
change to the db API, but not enough to block you if you wanted to work on
this sooner.

**Comment by samselikoff** [comment]
So eventually, I'd also like to see possibly some simple UI for mirage,
thinking on one side of the screen, perhaps only shows with a keyboard
shortcut. The UI would be to switch scenarios (different sets of data as
data). It could also be good for enabling/disabling this option of
persisting db, or even clearing it out.

**Comment by samselikoff** [comment]
*sets of development data

**Comment by seawatts** [comment]
What would be even cooler is a chrome extension. Like embers. I would say
we should add it to the ember one but I know you want to keep that sperate

**Comment by cibernox** [comment]
I had the same idea and I'm investigating a slightly different solution that could be even more disruptive to the ember ecosystem if it happens to be techically possible: Allow ember addons to extend the functionalities of the ember-inspector.

By example, mirage adding a "Mirage" tab on the ember-inspector that allows to inspect the state of your database, change it, copy it to localStorage/indexedDB or export it so you can share with your coworkers the exact set of data necessary to reproduce a bug.

Or liquidfire adding a tab to edit without reloading your animations.

It's a very powerful idea, but requires a lot of thought.

**Comment by samselikoff** [comment]
That sounds really awesome. <has nightmares of supporting multiple versions
of ember extension in multiple browsers>

But seriously that's a great idea, have you brought it up with zeenny?

**Comment by cibernox** [comment]
I did. 

In my head makes a lot of sense. By example could be ember-data the one responsable of implementing the `data` tab of the inspector (or maybe a separate addon you opt-in like `ember-data-inspector`).

I'm not sure how possible this is, because maybe there is some kind of security constraint in chrome extensions that preventing this kind of information interchange.

**Comment by seawatts** [comment]
Just found this. It looks like you can pass messages between extensions.
This would be so awesome!
https://developer.chrome.com/extensions/messaging#external

On Mon, May 18, 2015 at 4:30 AM, Miguel Camba <notifications@github.com>
wrote:

> I did.
>
> In my head makes a lot of sense. By example could be ember-data the one
> responsable of implementing the data tab of the inspector (or maybe a
> separate addon you opt-in like ember-data-inspector).
>
> I'm not sure how possible this is, because maybe there is some kind of
> security constraint in chrome extensions that preventing this kind of
> information interchange.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/samselikoff/ember-cli-mirage/issues/126#issuecomment-103024953>
> .
>



-- 
*Chris Watts* | Software Engineer | cwatts@simplymeasured.com

**Comment by JoshSmith** [comment]
@samselikoff curious if this is anywhere near your radar at all.

**Comment by samselikoff** [comment]
Filed under "Persist DB state in localStorage" note in the Roadmap project.

**Comment by courajs** [comment]
@samselikoff What is the Roadmap project?

**Comment by JoshSmith** [comment]
@courajs https://github.com/samselikoff/ember-cli-mirage/projects/3
