### ISSUE TITLE
[Feature Request] Ensure db#collectionName#update returns the updated resource

### ISSUE THREAD

**Issue by mariogintili** [samselikoff/ember-cli-mirage#127]
Hello!

I've noticed that the current behaviour would follow something along the lines of:

```javascript
db.spelling_test_submission_tasks.find(req.params.id);
=> Object {id: "991-1", spelling_test_tray_task_id: 1}
```

However

```javascript
db.spelling_test_submission_tasks.update(req.params.id, studentTask);
=> undefined
```

I think it would follow the same behaviour as `#insert`. I'm more than happy to implement :confetti_ball:

**Comment by samselikoff** [comment]
thx! change is in master

**Comment by mariogintili** [comment]
perfect, thanks! @samselikoff
