### ISSUE TITLE
POST with one-to-many Relationships using RestSerializer and shorthand routes errors on save()

### ISSUE THREAD

**Issue by ASH-Anthony** [samselikoff/ember-cli-mirage#1270]
I've confirmed that this works with JSONAPI, but when using REST, to `save()` a record with a one-to-many relationship, I get the following error:

```
addon.js:54824 Mirage: Your POST handler for the url /books threw an error: model.hasInverseFor is not a function

addon.js:54825 MirageError {description: "Mirage: undefined", fileName: undefined, lineNumber: undefined, message: "Mirage: Your POST handler for the url /books threw an error: model.hasInverseFor is not a function", name: "Error", …}description: "Mirage: undefined"fileName: undefinedlineNumber: undefinedmessage: "Mirage: Your POST handler for the url /books threw an error: model.hasInverseFor is not a function"name: "Error"number: undefinedstack: "Mirage: Error: Your POST handler for the url /books threw an error: model.hasInverseFor is not a function

Mirage: [500] POST /books
```

I've posted a link to a twiddle below. My main questions is: is this an actual issue or is something missing from my setup. One key point is that this only happens when using the shorthand routes. Writing routes using the expanded pattern works fine.

https://ember-twiddle.com/bf0f87e8de270532af4b74e86a70ed59?openFiles=serializers.application.js%2C

**Comment by samselikoff** [comment]
Sorry for the huge delay in response.

Turns out all you need to add is `normalizeIds: true` to your serializer.

```js
import { RestSerializer } from 'ember-cli-mirage';

export default RestSerializer.extend({
  normalizeIds: true
});
```

(This won't work in your Twiddle since it's on an older version of Mirage, but more recent versions will work.)

We added this as a flag since it had some slight changes in behavior. It will become the default in 1.0.

Sorry again!

**Comment by ASH-Anthony** [comment]
No worries thanks @samselikoff! I added a new Twiddle to demo this fix (also updated the previous Twiddle to use the latest Mirage and Ember 3.2). One note, for anyone else facing this issue is that it normalizeIds needs to go on the application serializer (not `serializers/author.js`)

https://ember-twiddle.com/0b6ca4e0d47c57378e7649c05aa31b91?openFiles=mirage.serializers.application.js%2C

**Comment by samselikoff** [comment]
Awesome, thanks!
