### ISSUE TITLE
ReferenceError: server is not defined | 0.4.2

### ISSUE THREAD

**Issue by ankushdharkar** [samselikoff/ember-cli-mirage#1279]
Mirage fails to introduce `server` in my acceptance tests

```Acceptance | authors loads: visiting route named author
    ✘ Promise rejected during "visiting route named author": server is not defined
        ReferenceError: server is not defined
```

I have mirage enabled in my env, also installed the `ember-cli-es5-shim`, added server to `.eslintrc.js` globals

This is my test:
```/* global server */

import { module, test } from 'qunit';
import { visit, currentURL } from '@ember/test-helpers';
import { setupApplicationTest } from 'ember-qunit';

module('Acceptance | authors loads', function(hooks) {
    setupApplicationTest(hooks);

    test('visiting route named author', async function(assert) {    
        // server.logging = true;
        server.createList('author', 3);
        await visit('/');
        assert.equal(currentURL(), '/');
    });
});
```

The `createList` works fine when I am in development mode and my site works fine. But during testing, the tests fail, because `server` is not defined

Sample repo containing the problem here: https://github.com/ankushdharkar/Mirage-Problem

**Comment by ankushdharkar** [comment]
@sivakumar-kailasam pointed a change to me: [changelog-0.4.2](https://github.com/samselikoff/ember-cli-mirage/blob/master/CHANGELOG.md#042)

On ember 3.x, it seems `server` does not get bound automatically in acceptance tests.

There are two ways, setting `autostart` to true, but this will start the server for ALL tests, including the non-acceptance ones

In your `config/enviroment.js`:
```
    ENV['ember-cli-mirage'] = {
      enabled: true,
      autostart: true
    };
```

The other, more fine method would be to set up `server` manually, in tests where you need them:
```
import { module, test } from 'qunit';
import { findAll, visit, currentURL } from '@ember/test-helpers';
import { setupApplicationTest } from 'ember-qunit';
import setupMirage from 'ember-cli-mirage/test-support/setup-mirage';


module('Acceptance | author', function(hooks) {
  setupApplicationTest(hooks);
  setupMirage(hooks);

  test('visiting /author', async function(assert) {
    server.createList('author', 5);
    await visit('/author');
    assert.equal(currentURL(), '/author');
    assert.equal(findAll('li').length, 5);
  });
});
```

This doesn't seem to be in the docs yet. Will send out a PR soon

**Comment by samselikoff** [comment]
Believe we've addressed this here https://github.com/samselikoff/ember-cli-mirage/commit/4b6176cec1f44b6902c445f34fa051ef2e6f5493

Sifting through issues and then hoping to improve the testing setup section of the guides. Lemme know if anyone's still having trouble and I'm happy to reopen!
