### ISSUE TITLE
Could I use Mirage to read/write the file system?

### ISSUE THREAD

**Issue by karellm** [samselikoff/ember-cli-mirage#1288]
I'm running a bunch of experiments to create a CMS with Ember. Among those experiments, I'm considering storing some data in flat files (rather than having a backend). It means that I need to read and write files.

I saw this [comment](https://discuss.emberjs.com/t/how-to-get-into-json-file-in-emberjs/9884/3?u=karel) which is not related to Mirage but still led me here. I understand it is not the intended use of Mirage but I was curious if it was something you could give me a pointer on in terms of feasibility. 

Thanks for any help you might be able to provide!

**Comment by samselikoff** [comment]
@karellm if I had to do this today I can think of a few approaches:
 - use Mirage route handlers/schema/db in Express in node-land, and have them write the `db` to a file
 - use an Electron app so Node has access to Mirage's `db`, and write that somewhere

You should be able to easily persist Mirage's `db` to `localStorage` in case that would solve your issue.

**Comment by samselikoff** [comment]
Closing for now to keep issues actionable but feel free to respond if you'd like some more info :)
