### ISSUE TITLE
Store peekRecord does not return item from fixture in testing.

### ISSUE THREAD

**Issue by omairvaiyani** [samselikoff/ember-cli-mirage#1292]
Ember (and Ember Data) 3.0.0
Mirage v0.4.3

I have one fixture in my fixtures folder ```"/fixtures/parse-users.js"```, with one record. I can see in my test that ```schema.db.parseUsers``` has the record. However, during the test, my application tries to load the object using ```store.peekRecord('parse-user', userId);``` which is returning empty. I know that the record is present in mirage's database collection, but it seems that my application's store is unable to find it.

Any ideas?

**Comment by bantic** [comment]
@omairvaiyani Mirage's DB is separate from what is in your application's Ember Data store. Does your app make a request (using, e.g. `store.findRecord('parse-user', userId)`) somewhere that will populate the Ember Data store? Your Ember Data store will only be populated with records that it has loaded via ajax calls. Mirage fixtures aren't automatically populated into your Ember Data store.

**Comment by omairvaiyani** [comment]
Right got you now - I was unsure if loading fixtures also loaded the data into the store. Thanks for clarifying!
