### ISSUE TITLE
Associated record created unnecessarily when an explicit association is passed

### ISSUE THREAD

**Issue by bantic** [samselikoff/ember-cli-mirage#1293]
I have a test in my app that makes some assertions around the count of models in the mirage server db, and noticed that even when passing an explicit associated model to the `server.create` call, mirage is creating a second (unused) model for that relation.

For example:
```
// models/comment.js
...
  post: DS.belongsTo()

//===========

// mirage/factories/comment.js
...
  post: association()

//===========

// some-test.js
...
let post = server.create('post');
// server.db.posts.length === 1

let comment = server.create('comment', {post});
// server.db.posts.length === 2
// (expected it to equal 1, since we are reusing the already-existing post)
```

I had some trouble getting the mirage boilerplate twiddle to run my tests correctly so I created a repo to demonstrate instead: https://github.com/bantic/try-mirage-relation-creation

The index-tests.js file in particular has an example 2 failing tests:
https://github.com/bantic/try-mirage-relation-creation/blob/32535e8f8d94403a39ba319bbf253eec7288f704/tests/acceptance/index-test.js#L21-L47

**Comment by samselikoff** [comment]
I think what's happening here is, the `association()` helper is getting used whenever you call `server.create('comment')`, so in the second and third scenarios, you create a post explicitly, but then the comment creation creates the second post.

Basically `association()` isn't smart enough to check if there's already a post associated with the comment.

The way I'd solve your situation is to move the `association()` helper into a `trait`:

```js
import { Factory, trait, association } from 'ember-cli-mirage';

export default Factory.extend({
  withPost: trait({
    post: association()
  })
});
```

That way, if you want a comment with a post and you don't care about configuring that post, you can call `server.create('comment', 'withPost')`. But if you want more control, you can do 

```js
let post = this.server.create('post');
let comment = this.server.create('comment', { post });
```

and have full control.

Another pattern is to use the orm to customize the post after you've created the default one:

```js
let comment = this.server.create('comment', 'withPost');
comment.post.update({
  title: 'My first post'
});
```

**Comment by bantic** [comment]
@samselikoff Thanks for the explanation, this makes sense. Would you be open to a PR that modified the way `association` works so that it only creates the associated record when one isn't explicitly included? This was the way I was expecting it to work, and it's the way the factory_bot gem works (iirc).

The way I would like to use the factories is as a way to define a "valid" instance of the model. So in my tests I can do `server.create('comment')` and be confident that I have a comment that has all the expected attributes and associations. I've noticed in some of our tests that there's a pattern developing of cargo-culting related associations in setup. For example some tests have setup code like `let a = server.create('a'); let b = server.create('b', {a}); let c = server.create('c', {a,b});` and if the test really only cares that a "c" record exists, it's unclear whether the separately-created records really need to be created for the test to pass or not. Ideally the developer could trust that the factory for "c" describes everything needed (including associations, if applicable) and `server.create('c')` is sufficient if that is the only model referenced in the test body.

Your suggestion of using traits would also work well, although it would require someone to flip back to the factory and review the code there to determine that a `withPost` (e.g) trait needs to be specified when creating the record.

It doesn't sound like this is a bug specifically, so I will close this issue. Thanks!

**Comment by samselikoff** [comment]
>  Ideally the developer could trust that the factory for "c" describes everything needed (including associations, if applicable) and server.create('c') is sufficient if that is the only model referenced in the test body.

This is exactly how I intended factories to work & be used, just like in the factory_bot gem. The factory should describe the "minimum valid state" of the model.

If factory_bot's `association()` helper works like this I'm definitely open to a PR! I think it'd be more tricky with a `hasMany`, but we have no helper for that - that's all done in `afterCreate`.

**Comment by happycollision** [comment]
@bantic See merge commit e3023d1

We had the same thought, and since this issue was closed, I missed it in my search. Anyway, the behavior is changed for (I suppose) whatever release happens after v0.4.6. If you'd like, until the next release, I have a workaround I describe (`ensureBelongsTo`) in #1298 that keeps records from being created unnecessarily which I thought was understandable enough for now.
