### ISSUE TITLE
204 response should not have a payload body

### ISSUE THREAD

**Issue by simonihmig** [samselikoff/ember-cli-mirage#1295]
It seems a 204 response e.g. from a `DELETE` shorthand request will nevertheless have an empty JSON body (`{}`), while technically it should not have any message body at all. See https://httpstatuses.com/204:

> A 204 response is terminated by the first empty line after the header fields because it cannot contain a message body.

This is currently causing some trouble with `ember-fetch`, see https://github.com/ember-cli/ember-fetch/issues/107.

**Comment by nicosefer** [comment]
Having the same issue!
Any workaround in sight?

This is my mirage temp fix...
```
router.delete('/users/:id', (db, request) => {
        const id = request.params.id;

        db.users.find(id).destroy();
        return new Mirage.Response(204, {}, '');
    });
```

**Comment by samselikoff** [comment]
This would be a great easy contribution for someone to make! If anyone starts it I’d be happy to help answer any questions.
