### ISSUE TITLE
Take new QUnit API into account when checking for `destroy-app` helper

### ISSUE THREAD

**Issue by twokul** [samselikoff/ember-cli-mirage#1300]
New QUnit API makes `destroy-app` helper obsolete. If you create a new ember app w/ `ember-cli@3+` and run `ember install ember-cli-mirage`, you would get a warning such as

```
******************************************************
destroy-app.js helper is not present. Please read this
https://gist.github.com/blimmer/35d3efbb64563029505a
to see how to fix the problem.
******************************************************
```

asking you to create the helper that's no longer relevant.

**Comment by ballPointPenguin** [comment]
Shouldn't we still need to call server.shutdown() somewhere?

**Comment by jelhan** [comment]
> Shouldn't we still to call server.shutdown() somewhere?

It's done in the `afterEach` hook registered by `startMirage`: https://github.com/samselikoff/ember-cli-mirage/blob/master/addon-test-support/setup-mirage.js#L22-L25
