### ISSUE TITLE
hasMany relationship is not "included" automatically, but belongsTo is OK

### ISSUE THREAD

**Issue by timmyomahony** [samselikoff/ember-cli-mirage#1308]
I've got an issue where a `hasMany` relationship is not being included in reponses, but the reverese `belongsTo` reltionship **is**. I'm not sure why the former isn't working while the latter is OK. 

My set up is (I'm using 0.4.1):

**Models:**

```js
// mirage/models/image.js
import { Model, belongsTo } from 'ember-cli-mirage';

export default Model.extend({
  imageGallery: belongsTo('image-gallery')
});
```

```js
// mirage/models/image-gallery.js
import { Model, hasMany } from 'ember-cli-mirage';

export default Model.extend({
  images: hasMany('image')
});
```

**Fixtures:**

```js
// mirage/fixtures/image-galleries.js
export default [
    {
      id: 0,
      title: 'Gallery'
    }
]
```

```js
// mirage/fixtures/images.js
export default [
    {
      id: 0,
      imageGalleryId: 0,
      caption: 'Test caption 1'
    },
    {
      id: 1,
      imageGalleryId: 0,
      caption: 'Test caption 2',
    },

    {
      id: 2,
      imageGalleryId: 0,
      caption: 'Test caption 3',
    }
]
```

**Scenarios:**

```js
export default function(server) {
  server.loadFixtures('image-galleries');
  server.loadFixtures('images');
}

```

**Serializers**:

```js
// mirage/serializers/application.js
import { JSONAPISerializer } from 'ember-cli-mirage';

export default JSONAPISerializer.extend({
    alwaysIncludeLinkageData: true
});
```

```js
// mirage/serializers/image-gallery.js
import ApplicationSerializer from './application';

export default ApplicationSerializer.extend({
  include: ['images']
});
```

```js
// mirage/serializers/image.js
import ApplicationSerializer from './application';

export default ApplicationSerializer.extend({
  include: ['imageGallery']
});
```

**Config:**:

```js
export default function() {
  this.get('/image-galleries/:id');
  this.get('/image-galleries');
  this.get('/images/:id');
  this.get('/images');
}
```

It's strange the the `belongsTo` relationships are being included automatically, but the reverse are not. I've tried a number of combinations to try get it working

- I've included `alwaysIncludeLinkageData` in the base application serializer
- I'm not using ` ?include=...` query param as I have specified `include: [...]` in the serializer explicitly:
  > Note that, in accordance with the spec, Mirage gives precedence to an ?include query param over a default include: [] array that you might have specified directly on the serializer. Default includes will still be in effect, however, if a request does not have an ?include query param.
- The only think I can think of is that I havne't explicitly included the reverse `hasMany` relationship in the fixtures, as I assume that would be automatically reveresed

EDIT: Even specifying the `hasMany` relationship in the fixtures still doesn't work:

```js
// mirage/fixtures/image-galleries.js
export default [
    {
      id: 0,
      imagesIds: [0, 1, 2],
      title: 'Gallery'
    }
]
```

**Comment by timmyomahony** [comment]
OK, I think I have it working. I didn't realise I was using an older version so I upgraded to `0.4.5` and then explicitly added the `hasMany` relationships to the fixtures:

```js
// mirage/fixtures/image-galleries.js
export default [
    {
      id: 0,
      imageIds: [0, 1, 2],
      title: 'Gallery'
    }
]
```

I mentioned this not working in the edit of my original post, but I didn't notice that it should be `imageIds` and not `imagesIds` (not the "image**s**)

**Comment by samselikoff** [comment]
👍  great, glad you fixed it!
