### ISSUE TITLE
Passthrough by default

### ISSUE THREAD

**Issue by knownasilya** [samselikoff/ember-cli-mirage#131]
So I would like to pass through requests to the server by default, if there is no mirage route. Or at least have it as an option in the config.

```js
this.passThroughByDefault = true
```

**Comment by samselikoff** [comment]
this is absolutely planned. Not hard to implement either, just haven't had time yet

**Comment by knownasilya** [comment]
Does the current manual passthrough work? Doesn't seem too..

**Comment by samselikoff** [comment]
Should be able to do something like

```js
this.get(':fallback', this.pretender.passthrough);
this.post(':fallback', this.pretender.passthrough);
this.put(':fallback', this.pretender.passthrough);
this.delete(':fallback', this.pretender.passthrough);
```

**Comment by samselikoff** [comment]
duplicate #80
