### ISSUE TITLE
Ember Simple Auth & Mirage for API stub

### ISSUE THREAD

**Issue by lougreenwood** [samselikoff/ember-cli-mirage#1317]
Hi, I'm using mirage as an API stub whilst our proper API is being built.

However, we do have a working local OAuth server.

It seems that mirage is intercepting Ajax calls to `/oauth/token`, but I need these to be sent over the network to my actual auth server.

Is there anyway to tell mirage to ignore a specific route/url or to have mirage just pass the request through?

I've had a look through the past issues, but it seems most auth questions have been about name spacing...

**Comment by samselikoff** [comment]
I believe you're looking for the [passthrough](http://www.ember-cli-mirage.com/docs/v0.4.x/configuration/#passthrough) API. It should do what you want!

Let me know if you have any more questions :)
