### ISSUE TITLE
Shorthand this.get('/foo', ['collection1', 'collection2']) broken in 0.0.29

### ISSUE THREAD

**Issue by seawatts** [samselikoff/ember-cli-mirage#132]
I believe #123 broke this functionality.

Before 0.0.29 this worked
`this.get('/foo', ['friends', 'groups', 'foo'])`
Which should return all three of those sideloaded together in the response.

This is equivalent to 
```js
this.get('/foo', function(db) {
  return {
    friends: db.friends,
    groups: db.groups,
    foo: db.foo
  };
});
```

After 0.0.29 it just returns the first group, `friends`.

**Comment by samselikoff** [comment]
oy. need a test on this

**Comment by samselikoff** [comment]
thx for bringing up!

**Comment by cibernox** [comment]
I can check this if you want

**Comment by seawatts** [comment]
:+1: I'm a bit busy to look into it right now.

**Comment by samselikoff** [comment]
I actually have time now

**Comment by samselikoff** [comment]
I think we should go to 0.1.0 so we can push bugfixes as patches. agree?

**Comment by cibernox** [comment]
yep

**Comment by seawatts** [comment]
Absolutely

On Wed, May 20, 2015 at 3:55 PM, Sam Selikoff <notifications@github.com>
wrote:

> I think we should go to 0.1.0 so we can push bugfixes as patches. agree?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/samselikoff/ember-cli-mirage/issues/132#issuecomment-104066386>
> .
>



-- 
*Chris Watts* | Software Engineer | cwatts@simplymeasured.com

**Comment by cibernox** [comment]
BTW, I have spotted the problem: https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/server.js#L18

In this line, `typeof ['friends', 'groups', 'foo']` **is object** (fuuu javascript) and therefore it's interpreting it as the options has. Easy to fix.

**Comment by samselikoff** [comment]
haha :) good job! im setting up an integration test now with a failing test. don't want to use dummy/mirage/config.js anymore so we can test this stuff more easily. im almost there

**Comment by samselikoff** [comment]
also, `server.js` is a monster and needs refactoring

**Comment by seawatts** [comment]
:+1: Thanks @samselikoff and @cibernox for getting to this so quickly! :smile:

**Comment by samselikoff** [comment]
yw!

**Comment by cibernox** [comment]
:grin:
