### ISSUE TITLE
JSON API Serializer assumes `include`d relationships are always dasherized

### ISSUE THREAD

**Issue by bantic** [samselikoff/ember-cli-mirage#1322]
We have an API that uses underscores to separate multi-word model names (e.g. `blog_post` instead of `blog-post`) in its responses.

Accordingly, it also wants the `?include=` query param to use the same format for relationship names (e.g. `GET /comments/1?include=blog_post`).

I therefore am wanting to configure Mirage to respond to a request like so:
```js
// GET /comments/1?include=blog_post

{
  data: {
    attributes: {},
    id: "1",
    type: "comments"
    relationships: {
      blog_post: { data: { id: "1", type: "blog-posts" } }
    }
  },
  included: [{
    id: "1",
    attributes: {},
    type: "blog-posts"
  }]
}
```

~~(I would probably also ideally want to alter the `type` values in the payload to be singularized+underscored, but that's unrelated to this specific issue.)~~ Edit: This can be changed using `typeKeyForModel`.

If I define a `keyForRelationship` method on the serializer that returns "blog_post" for the relationship key "blogPost", then I can get partway there: The `included` section of the mirage response is correct, but the `relationships` attribute is not present in the `data` section.

This appears to be due to how Mirage creates its internal graph (in `_addPrimaryModelToRequestedIncludesGraph`) and how it later reads that graph (in `_relationshipIsIncludedForModel`).
When creating the graph from the `queryParamIncludes`, it uses the `relationshipKey` unmodified from the query param:

https://github.com/samselikoff/ember-cli-mirage/blob/3b4509c5fc93942e227f5d0f52d7cf549f133a8d/addon/serializers/json-api-serializer.js#L280

In my example case the value of `relationshipKey` is "blog_post".

When using the graph to populate the response `relationships` field in `_relationshipIsIncludedForModel`, it looks for the dasherized model name in the graph's `included` part:

https://github.com/samselikoff/ember-cli-mirage/blob/3b4509c5fc93942e227f5d0f52d7cf549f133a8d/addon/serializers/json-api-serializer.js#L217

In the case of my example, this check fails (it is looking for `graph.relationships['blog-post']` but the data is actually in `graph.relationships['blog_post']`), so the related blog post isn't part of `data.relationships`.

However, the `getIncludesForResourceAndPath` does end up adding the related blog post to `included` because it searches for the camelized relationship path here:

https://github.com/samselikoff/ember-cli-mirage/blob/3b4509c5fc93942e227f5d0f52d7cf549f133a8d/addon/serializers/json-api-serializer.js#L91-L97

On the last line, the values from my example would be: `let relationship = comment['blogPost]'`.

I think this would be fixed if Mirage's graph always dasherizes relationship path names before putting them into the graph. I have a PR I will submit that I think will address this.

**Comment by bantic** [comment]
(accidentally submitted this while editing...updating now)

**Comment by samselikoff** [comment]
Looks like you learned a lot more about Mirage than you bargained for ;) 

Thanks so much for the help dude!!
