### ISSUE TITLE
normalizedRequestAttrs returns incorrect ID format for poloymorphic relationship

### ISSUE THREAD

**Issue by chrismatheson** [samselikoff/ember-cli-mirage#1324]
It seems that the internal normalizedRequestAttrs is not serialising the relationship correctly

I will try and express this as a test / twiddle as soon as i can, but want to capture here before forgetting.

The setup is to define a polymorphic relationship, then try and update that relationship with a PUT request, it should throw errors from mirage.

```js
//Work around

self.patch(api_v2 + `${route}/:id`, function(schema, request) {
        let id = request.params.id;
        let attrs = this.normalizedRequestAttrs();

        if(modelNameFromRoute === 'complaints') {
            attrs.assigneeId = JSON.parse(request.requestBody).data.relationships.assignee.data;
        }

        return schema[modelNameFromRoute].find(id).update(attrs);
    });
```

**Comment by samselikoff** [comment]
Believe https://github.com/samselikoff/ember-cli-mirage/pull/1337 fixed this

**Comment by chrismatheson** [comment]
looks like it may well have. Is there any rough plan for the next release of ember-cli-mirage that will include https://github.com/samselikoff/ember-cli-mirage/pull/1337 ?

**Comment by samselikoff** [comment]
@chrismatheson 0.4.9 has it - give it a try and if you have any issues please report back!
