### ISSUE TITLE
scheduleProgressEvent updates progress on upload after handling response

### ISSUE THREAD

**Issue by DLiblik** [samselikoff/ember-cli-mirage#1329]
Mirage version: `0.4.2`

In `pretender.js`, the `handleResponse` method includes a call to `scheduleProgressEvent` that gets made if there is a non-zero timing delay on a route handler.  `scheduleProgressEvent` in turn updates progress on `request.upload` which has the unfortunate side effect of indicating to the client that data continues upload to the (faked) server even after the route handler has executed.  This causes particular problems when the faked route is a file-upload handler and progress monitoring is being performed on the upload in the client code.

```js
function scheduleProgressEvent(request, startTime, totalTime) {
  setTimeout(function() {
    if (!request.aborted && !request.status) {
      var ellapsedTime = new Date().getTime() - startTime.getTime();

// === Calls a progress update on the upload side ===
      request.upload._progress(true, ellapsedTime, totalTime);

      request._progress(true, ellapsedTime, totalTime);
      scheduleProgressEvent(request, startTime, totalTime);
    }
  }, 50);
}
```

**Comment by DLiblik** [comment]
More info on the "particular problems": because `scheduleProgressEvent` uses the elapsed amount of time of the delay to report progress, client code suddenly sees the size of every file change from the file size to the number of milliseconds of delay on the progress event `total` property.  

So in the situation where the route delay is 400ms, an uploaded file goes from, say, 65365 bytes out of 65365 (i.e. 100%) to 80 bytes out of 400, then 150, etc., until finally landing at 400/400, which results in the client progress (if numbers are displayed) on each file showing 400/400 bytes uploaded.

Across all files, overall progress cannot be calculated on the client side as the sum of all uploaded progress divided by the sum of all file sizes results in a skewed number (usually 0% since most files are >> 400 bytes).

**Comment by samselikoff** [comment]
Sorry for never responding to this!

I'm not really sure if this is a question or a bug report. Let me know if you're still having an issue.

**Comment by DLiblik** [comment]
Hi @samselikoff , it was a bug report - do you require more information?  I don't know if this has now been resolved.  Basically progress was being reported to the client _after_ the handler had already processed the upload.

**Comment by DLiblik** [comment]
And the numbers being reported were numbers of milliseconds, not bytes - in the example above, a file of x bytes being uploaded to a handler with a timing delay of 400ms would receive progress values leading up to 400, not to x.  I think the proper execution would return numbers escalating to x over the course of 400ms, not numbers escalating to 400 over the course of 400ms.

**Comment by DLiblik** [comment]
So technically, it's a bug-report two-fer (do you have a label for that :) ).

**Comment by samselikoff** [comment]
I've read the original two comments several times and I don't understand them – is this a Pretender bug? scheduleProgressReport is not our function

**Comment by samselikoff** [comment]
Reproduction with desired / actual behavior always helps

**Comment by DLiblik** [comment]
Fair enough - I posted it during a rushed time so never had time to do up a proper sample.  Might be best to close it - I'm sure this will come up again and/or may have been solved on pretender itself.

**Comment by samselikoff** [comment]
No worries - happy to help but I'm just not familiar with this internal part of pretender! If it's affecting your Mirage usage I'm happy to move it forward but let's do it over in pretender. Just ping me there if it comes up again 🤙

**Comment by DLiblik** [comment]
👌
