### ISSUE TITLE
Conflict with async functions and Ember's run loop

### ISSUE THREAD

**Issue by FrenchHipster** [samselikoff/ember-cli-mirage#1330]
Hi guys 👋 

First time I open a ticket here, and also this issue is very confusing to me, so please bear with me while I try to make sense of it 🙏 
I'm also not sure if this is purely because of ember-cli-mirage, or if this is an issue with qunit/ember-data. If that's the case, please point it out!

I managed to create a basic Ember repo to reproduce the error I got:
https://github.com/manudwarf/ember-cli-mirage-async

Here are the relevant snippets:

I started from this code:
```javascript
  successPromise() {
    this.get('model').save()
      .then(() => this.get('model').set('name', 'New Name!'));
  },
```
Which works, and then I rewrote it using new Javascript `async` goodness:
```javascript
  async failAsync() {
    await this.get('model').save();
    this.get('model').set('name', 'New Name!');
  },
```
But this fails in acceptance tests. However, if I use this code:
```javascript
  async successAsync() {
    this.set('saving', true);
    await this.get('model').save();
    this.set('saving', false);
    this.get('model').set('name', 'New Name!');
  },
```
It all works fine.

Here is the acceptance test:
```javascript
  test('fail with async', async function(assert) {
    await visit('/sample');
    await click('#fail-async');
    assert.ok(true);
  });
```

Here is the error that is thrown:
```
Error: Assertion Failed: You have turned on testing mode, which disabled the run-loop's autorun. You will need to wrap any code with asynchronous side-effects in a run
```

This comes from the `model.set(...)` statement, more specifically `this._internalModel.send('didSetProperty', ...)`, in the `recordDidChange` function.

Moreover, you'll notice the difference with `set('saving', ...)`. This test case fails if I remove the `<span>` from the template:
https://github.com/manudwarf/ember-cli-mirage-async/blob/master/app/templates/components/sample-form.hbs

**Comment by samselikoff** [comment]
Not sure, will have to dig into it. Thanks for the repro!

**Comment by jelhan** [comment]
Isn't this simply the autorun assertion by ember, which is not yet removed? https://github.com/emberjs/ember.js/pull/16797 https://discuss.emberjs.com/t/readers-questions-why-does-ember-still-use-rsvp/14736

**Comment by samselikoff** [comment]
I upgrade Ember Data to 3.3.1 and that fixed the text. Looks like it was an ED bug!

**Comment by samselikoff** [comment]
Feel free to post if you have any more questions :)
