### ISSUE TITLE
prod build with mirage enabled fails

### ISSUE THREAD

**Issue by CezaryH** [samselikoff/ember-cli-mirage#1339]
I'm using ember version 3.1.4 with ember-cli-mirage 0.4.1,
unfortunately enabling mirage in prod build end with an error
```
Build failed.
Build Error (BabiliPlugin)

assets/vendor.js: Cannot convert undefined or null to object
```

**Comment by jamesarosen** [comment]
Possibly the same as #1211

**Comment by samselikoff** [comment]
Confirm, cannot reproduce on a new ember/mirage app.

Closing for now, @CezaryH please reopen if you're still having trouble!
