### ISSUE TITLE
Installing into an addon

### ISSUE THREAD

**Issue by ksnyde** [samselikoff/ember-cli-mirage#135]
I can't wait to start using this but I fell down at the start line ... when I install using Ember-CLI 0.2.5 using:

> ember install ember-cli-mirage

It does install the repo to `node_modules` but then during the installation processing it comes back with the unexplainable error of:

> Installed packages for tooling via npm.
Install failed. Could not find addon with name: ember-cli-mirage

Is there anything different one needs to do with installing mirage for use with an addon? I know there had been some CLI restrictions about loading addons within addons in 0.2.3 but I thought (hoped anyway) that this was resolved in 0.2.5. Anyway, since I'm sure I'm not the only one to want to use this tooling in an addon it would be great if we could at least document any needed workaround.

**Comment by samselikoff** [comment]
I think this is a great use case for mirage, I just haven't had time to
investigate. I'll try to get to it soon.

Thanks for opening the issue!

**Comment by ksnyde** [comment]
Great. I was out with @cibernox last night and he got me completely convinced this is something I need in my tool chest. Looks awesome and let me know when you're ready for me to give this another test.

**Comment by samselikoff** [comment]
should have a fix for this soon, it's the `app.bowerDirectory` line

**Comment by samselikoff** [comment]
blocked right now: https://github.com/ember-cli/ember-cli/issues/3718

**Comment by samselikoff** [comment]
#108 duplicate
