### ISSUE TITLE
Mirage not initialized on pre-RFC-232 test

### ISSUE THREAD

**Issue by jamesarosen** [samselikoff/ember-cli-mirage#1351]
The app has `@ember/test-helpers` installed, but uses RFC-232-style only for a small fraction of its tests.

There are lots of tests that look like
```js
import { moduleFor, test } from 'ember-qunit'
import { getOwner } from '@ember/application'
import initializeMirage from 'my-app/initializers/ember-cli-mirage'

moduleFor('foo:bar', 'Integration: foo:bar test', {
  integration: true,
  beforeEach() {
    initializeMirage(getOwner(this))
    server.doSomething()
  }
})
```

On mirage 0.3.4, these tests work fine.

On mirage 0.4.7, in each such tests, `server` is undefined. As best I can trace the logic,

 1. `ember-test-helpers` legacy `test-module` [calls `super`](https://github.com/emberjs/ember-test-helpers/blob/v0.7.21/addon-test-support/ember-test-helpers/legacy-0-6-x/test-module.js#L121-L129)
 1. legacy `abstract-test-module` [calls `setContext`](https://github.com/emberjs/ember-test-helpers/blob/v0.7.21/addon-test-support/ember-test-helpers/legacy-0-6-x/abstract-test-module.js#L136)
 1. other stuff happens…
 1. `beforeEach` calls the initializer
 1. `initializeMirage` [calls `_shouldUseMirage`](https://github.com/samselikoff/ember-cli-mirage/blob/v0.4.7/app/initializers/ember-cli-mirage.js#L26)
 1. `_shouldUseMirage` [calls `getRfc232TestContext`](https://github.com/samselikoff/ember-cli-mirage/blob/v0.4.7/app/initializers/ember-cli-mirage.js#L40) to see whether it can get an RFC-232-style test context
 1. `get-rfc-232-test-context` [calls `require.has`](https://github.com/samselikoff/ember-cli-mirage/blob/v0.4.7/addon/get-rfc232-test-context.js#L11) to determine whether `@ember/test-helpers` exist in the app. In this case, they do.
 1. `get-rfc-232-test-context` [calls `getContext`](https://github.com/samselikoff/ember-cli-mirage/blob/v0.4.7/addon/get-rfc232-test-context.js#L13), returning the context from the initial setup

That is, I believe `getRfc232TestContext()` is not a valid proxy for _is this test RFC-232-style?_

**Comment by samselikoff** [comment]
Gotcha, so we need to make the initializer more intelligent about whether it's being run in an RFC 232 test or not, correct?

**Comment by samselikoff** [comment]
I looked into this and things seem to be working as expected. If you are able to change how you're manually starting Mirage in your integration tests to follow [the cookbook entry in the guide](http://www.ember-cli-mirage.com/docs/v0.4.x/manually-starting-mirage/)

```
// tests/integration/components/your-test.js
import { startMirage } from 'yourapp/initializers/ember-cli-mirage';

moduleForComponent('your-component', 'Integration | Component | your component', {
  integration: true,
  beforeEach() {
    this.server = startMirage();
  },
  afterEach() {
    this.server.shutdown();
  }
});
```

then everything should work.

Could you try that and let me know how it goes? Also, do you remember where you got the `initializeMirage(getOwner(this))` snippet example from? (I am planning on clarifying how to start Mirage in different test setups in the new version of the docs.)

**Comment by jamesarosen** [comment]
Our current (pre-RFC-232, mirage 0.3.4) code is
```js
// tests/helpers/setup-mirage-for-integration.js

import mirageInitializer from '../../initializers/ember-cli-mirage'

export default function setupMirage(container) {
  mirageInitializer.initialize(container)
}
```
We have 25 tests that use that like so:
```js
beforeEach() {
  startMirage()
}
```
When I run these on mirage 0.4.7, I get
```
TypeError: Cannot read property 'register' of undefined
    at Object.initialize (http://localhost:4201/assets/my-app.js:5967:21)
    at setupMirage (http://localhost:4201/assets/my-app.js:33375:29)
```

We also have 21 tests that do this:
```js
beforeEach() {
  startMirage(Ember.getOwner(this))
}
```
On 0.4.7, those yield
```
ReferenceError: server is not defined     at Object.beforeEach (http://localhost:4201/assets/tests.js:33614:23)
```

**Comment by jamesarosen** [comment]
`import { startMirage } from 'my-app/initializers/ember-cli-mirage` works on 0.3.4 and 0.4.7. Thanks for the tip!

**Comment by samselikoff** [comment]
Wonderful!
