### ISSUE TITLE
v1.0

### ISSUE THREAD

**Issue by samselikoff** [samselikoff/ember-cli-mirage#1363]
- [x] change `normalizeIds` default on AMS/RestSerializer to `true` (0d93eac11afe6fd15a6f0ea292f4ee4168799599 closes)
- [x] Faker.js work in https://github.com/samselikoff/ember-cli-mirage/issues/1037
- [x] Pretender work in https://github.com/samselikoff/ember-cli-mirage/issues/1469
- [x] Revisit lodash stuff. Possibly remove?
- [x] remove deprecated behavior of plural model name to create/createList
- [ ] ~the camelCase vs. dasherized stuff is rough and confusing. Is there some sort of check/assertion/typing we can introduce so this is less of a pain going forward?~
- [x] Look for "This behavior will be removed in 1.0." comments
- [x] skipped tests
- [ ] ~consider simplifying factory/fixture logic in config()? more explicit?~ Maybe v2
- [ ] ~deprecate object handler (fat arrow functions returning objects are commonplace now)~ Maybe v2

**Comment by bartocc** [comment]
I believe the plan for the Faker codemod is to use the faker.js npm package with ember-auto-import, right ?

**Comment by samselikoff** [comment]
@nightire believe if pretender becomes a peer dep than host apps can choose their own versions

**Comment by jherdman** [comment]
FYI I've done a little work on the Pretender as a peer dependency thing. Check out #1389

**Comment by jherdman** [comment]
As of #1392 we support Pretender v2+. 💃

**Comment by samselikoff** [comment]
c8384bb31e59aac9d058aa3d007708f09bd1a290 closes
