### ISSUE TITLE
Faker generated images from lorempixel are taking upwards of 20 seconds to load

### ISSUE THREAD

**Issue by rondale-sc** [samselikoff/ember-cli-mirage#1365]
<img width="1121" alt="screen shot 2018-08-07 at 12 14 52 pm" src="https://user-images.githubusercontent.com/75710/43788589-ccb11caa-9a3b-11e8-9342-bd992c4aaeef.png">

In the latest release of faker.js there is a datauri function that can be used to generate inline images to prevent this.  I think we should consider bumping the faker version

**Comment by samselikoff** [comment]
Hehe - yep sounds like a good idea.

Dup of https://github.com/samselikoff/ember-cli-mirage/issues/1037, trying to decide the best path forward over there for the Faker dep.
