### ISSUE TITLE
Switch to use lodash-es directly instead of ember-lodash

### ISSUE THREAD

**Issue by leondmello** [samselikoff/ember-cli-mirage#1378]
Since Ed has now come up with something as seamless as `ember-auto-import`, mirage could update it package JSON to not depend on `ember-lodash` anymore

**Comment by jherdman** [comment]
Something to consider is that the app currently loads NPM packages with ember-cli-node-assets. As a step one we ought to migrate to e-auto-import first.

**Comment by samselikoff** [comment]
Believe https://github.com/samselikoff/ember-cli-mirage/pull/1561/files closes
