### ISSUE TITLE
Factories collides with 'schema' property name

### ISSUE THREAD

**Issue by igbopie** [samselikoff/ember-cli-mirage#1379]
I have a factory that has a property named 'schema'. That property collides with an internal property named 'schema' too, which breaks things.

https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/orm/model.js#L131

I guess this has to do with this commit:

https://github.com/samselikoff/ember-cli-mirage/commit/521e8414ffa26e1cbe56df3c0285a16f7e968a77

Is it not possible to have a property named 'schema'?

**Comment by theseyi** [comment]
@samselikoff this is an issue that caused us to pin mirage at `0.4.7`. The schema key overrides/clobbers a property on our model. Was there a reason for this change? [521e841](https://github.com/samselikoff/ember-cli-mirage/commit/521e8414ffa26e1cbe56df3c0285a16f7e968a77)

**Comment by samselikoff** [comment]
@theseyi At this point I can't remember, but I think it was just due to refactoring and perhaps `model.schema` being called from outside the Model class. I agree this is an issue and I can revert this.

The lesson learned for any future ORM authors is to always namespace userland attributes :)

**Comment by samselikoff** [comment]
@igbopie @theseyi should be all set! Let me know if you run into any more issues.
