### ISSUE TITLE
Using `this.normalizedRequestAttrs()` with form-data is case-dependent

### ISSUE THREAD

**Issue by kimroen** [samselikoff/ember-cli-mirage#1398]
In a route handler, one can call `this.normalizedRequestAttrs()` to get an object representing the request data.

For requests with the content type of `x-www-form-urlencoded`, this should convert a query string to an object. This happens here (and was implemented in #796):

https://github.com/samselikoff/ember-cli-mirage/blob/0213a9573dcf4ef4e7888b1678013d561b6a90fe/addon/route-handlers/function.js#L42-L44

It checks the headers for one named `'Content-Type'`:

```js
requestHeaders['Content-Type']
```

In our case the header name is `'content-type'`, so it instead tries to parse the request body as JSON and fails.

Title-casing header names is the norm, so I tried finding out why this was happening.

The request was coming from `ember-simple-auth`, which in turn uses `ember-fetch`, which again uses the `fetch`-polyfill from github. It turns out that this library downcases all header names to normalize and avoid duplication:

https://github.com/github/fetch/blob/899b155746630c32d83ee29a38642da16b314ecb/fetch.js#L43-L51

Although surprising, there's nothing wrong with this because [as they say in an issue asking about this](https://github.com/github/fetch/issues/249), HTTP headers are case-insensitive.

Because of this, I suggest we make the check for header name case-insensitive.

**Comment by samselikoff** [comment]
Agree!

**Comment by samselikoff** [comment]
https://github.com/samselikoff/ember-cli-mirage/pull/1409 closes
