### ISSUE TITLE
Usage with ember-cli-cordova

### ISSUE THREAD

**Issue by igorrKurr** [samselikoff/ember-cli-mirage#140]
Hi!

I was using `mirage` to develop my web app first, then i wanted to make it mobile and used cordova for this.

In my app there are some static json files that i just passthrough:

```
  this.pretender.get('/translations/:locale', this.pretender.passthrough);
```

But while run in `cordova` i get:

```
Mirage: Your Ember app tried to GET 'file:///Users/igor/Library/Developer/CoreSimulator/Devices/F540AE3F-1AF0-48E8-8FD6-DF432F7935EF/data/Containers/Bundle/Application/95B4F0D1-3636-43FE-B612-C77AB1717A2D/M3.app/www/translations/en.json', but there was no route defined to handle this request. Define a route that matches this path in your mirage/config.js file.
```
So, is there any chance to  fix this? And can be mirage used with cordova at all?

**Comment by samselikoff** [comment]
hmm...try `this.get(':base/translations/:locale')`? I'm not sure how pretender works with the file protocol.

You could also write catchall routes

```js
this.pretender.get('/:passthrough', this.pretender.passthrough);
this.pretender.post('/:passthrough', this.pretender.passthrough);
this.pretender.put('/:passthrough', this.pretender.passthrough);
this.pretender.del('/:passthrough', this.pretender.passthrough);
```

at the bottom of your config file, so the error doesn't show and mirage just ignores those request. (fyi #134 is adding a flag for global passthrough).

**Comment by igorrKurr** [comment]
Thank for quick response!

I solved this issue, and the problem wasn't in `mirage`.
That was because I built and ran cordova wrong way.
So that issue just should be closed now.
Mirage is great)

**Comment by samselikoff** [comment]
awesome, glad to hear!

**Comment by jrhe** [comment]
@igorrKurr Can you elaborate on how you solved this? Also having the same issue.

@willviles

**Comment by igorrKurr** [comment]
@jrhe as i remember that happened to me because i forgot to rebuild cordova app after included mirage.
