### ISSUE TITLE
Explicitly including `@ember/jquery` breaks mirage

### ISSUE THREAD

**Issue by psbanka** [samselikoff/ember-cli-mirage#1400]
I am seeing the following when upgrading Ember to the latest (`3.5`)
```
DEPRECATION: Ember will stop including jQuery by default in an upcoming version. If you wish keep using jQuery in your application explicitly add `@ember/jquery` to your package.json
```

However, when I add that package (`@ember/jquery`), Mirage seems to break entirely. Is there a workaround?

**Comment by samselikoff** [comment]
Not seeing this... could you help with a reproduction? 

Perhaps it was fixed with 3.5.1/3.4.4

**Comment by meganre** [comment]
> I am seeing the following when upgrading Ember to the latest (`3.5`)
> 
> ```
> DEPRECATION: Ember will stop including jQuery by default in an upcoming version. If you wish keep using jQuery in your application explicitly add `@ember/jquery` to your package.json
> ```
> 
> However, when I add that package (`@ember/jquery`), Mirage seems to break entirely. Is there a workaround?

Do you have the optional features jquery flag set to true? Mirage only failed when it was set to false

**Comment by meganre** [comment]
Speak of this - is there a plan to remove the jquery dependency of `ember-cli-mirage`?

**Comment by samselikoff** [comment]
would be great, think it's just used for tests

**Comment by samselikoff** [comment]
Closing this for now. jquery is just a devDependency of mirage, used for our test-projects.

Let me know if this is still an issue, and if so I could use help with a reproduction!
