### ISSUE TITLE
Twiddle in issue template out of date

### ISSUE THREAD

**Issue by ELepolt** [samselikoff/ember-cli-mirage#1402]
Would love to see this bumped to the latest Ember LTS

I also noticed that tests were not running

https://ember-twiddle.com/eedfd390d8394d54d5bfd0ed988a5d0f?openFiles=templates.application.hbs%2C

**Comment by ELepolt** [comment]
I've got a working Ember 3.4 with mirage@0.4.9 here: https://gist.github.com/ELepolt/332efdcd216d886ad4978f0f3c6c052c

Not entirely sure what needs to be done to get the tests running though

**Comment by samselikoff** [comment]
Updated: https://github.com/samselikoff/ember-cli-mirage/blob/master/ISSUE_TEMPLATE.md

**Comment by samselikoff** [comment]
@ELepolt do you mean, get tests running in Twiddle?

**Comment by ELepolt** [comment]
Yes

**Comment by samselikoff** [comment]
What about this? https://codesandbox.io/s/003o6pq34n

**Comment by ELepolt** [comment]
Looks good to me!
