### ISSUE TITLE
Subdirectory / nested module support

### ISSUE THREAD

**Issue by samselikoff** [samselikoff/ember-cli-mirage#1414]
6 upvotes from Canny

**Comment by artsyca** [comment]
I'm a newcomer to this project but nested module support is an interesting and high-value capability that would suit ember-cli-mirage quite well in my view and fits in to my own use case very closely. A lot of moving parts it seems; @ro0gr do you suppose you'd be up for a pairing session or something of that nature to help one get up to speed on the task?
