### ISSUE TITLE
Pretender is not shut down after tests

### ISSUE THREAD

**Issue by andrei1089** [samselikoff/ember-cli-mirage#142]
As a workaround I'm calling `server.pretender.shutdown()` in the `afterEach` hook.

I've noticed this side effect while trying to integrate ember-cli-blanket. The addon is making a POST request to send the coverage when all the tests have finished. Everything worked fine on Chrome/Firefox but failed on PhantomJs with some exception in pretender.

**Comment by elskwid** [comment]
@andrei1089 you can use the passthrough functionality to allow this but then you'll see a new problem which @samselikoff has [pushed upstream in pretender#74](https://github.com/trek/pretender/pull/74).

**Comment by andrei1089** [comment]
@elskwid I've already tried with the passthrough functionality. It worked fine on Chrome/Firefox but faced the issue you've mentioned on PhantomJs.

**Comment by samselikoff** [comment]
This should be taken care of

**Comment by ashrafhasson** [comment]
this seems to have resurfaced. I'm experiencing this issue with mirage 0.3.4

**Comment by rwjblue** [comment]
Probably best to open a new issue with a current reproduction (as opposed to commenting on a long closed issue where folks may not notice...)

**Comment by ashrafhasson** [comment]
@rwjblue granted I should have opened a new issue but I wasn't able to reproduce as the set of conditions in my app are likely playing a significant role too. I'll open a new issue if I was able to reproduce at least once with a new app. Thanks for noticing though, really appreciated.
