### ISSUE TITLE
add an `empty` method

### ISSUE THREAD

**Issue by samselikoff** [samselikoff/ember-cli-mirage#1433]
![image](https://user-images.githubusercontent.com/2922250/48871682-c2ec6000-edb3-11e8-8717-a301665c7dfa.png)

**Comment by samselikoff** [comment]
this should be `.none()`

**Comment by Oreoz** [comment]
I was going to do this, but it looks like it already exists! #1290

**Comment by samselikoff** [comment]
Yes - thank you! 

Docs here: http://www.ember-cli-mirage.com/docs/api/modules/ember-cli-mirage/orm/schema~Schema#none
