### ISSUE TITLE
Relationship linkage is lost when JSON:API serializer has default include dot path

### ISSUE THREAD

**Issue by ryanto** [samselikoff/ember-cli-mirage#1437]
Code sandbox: https://codesandbox.io/s/6z457x7jxk

Here's the following relationships

A user belongs to a school
A school has many buildings

The user serializer has a default include of `['school.buildings']`, so I'll get the whole graph when doing `store.findRecord('user', 1)`.

In our mirage scenario we create a school and a user with that school. We don't create any buildings.

If you open the JS console in your browser for that code sandbox, you'll see the request to `/users/1`, and the school is included, but the linkage between user and school is missing. If we change the user serializer's default include to only be `['school']`, it works correctly.

This is because the dot notation does not work include of the serializer layer, it's only for the include query param.

**Comment by ryanto** [comment]
A way to fix this is to let route handlers pass an include string to a serializer. This way there's no ambiguity between different serializers specifying their own include paths.

```js
this.post('/users', function(...) {
  // normalize request attrs, create user model
  return this.serialize(user, { include: 'x.y.z' });
});
```

In order for this to happen we would need an API for passing options to `this.serialize` as the 2nd param.

**Comment by samselikoff** [comment]
I think this is really "clarify the behavior around dot path includes in the Serializer `include` attribute, right?
