### ISSUE TITLE
Build failed. Path or pattern "bower_components/lodash/lodash.js" did not match any files

### ISSUE THREAD

**Issue by notmessenger** [samselikoff/ember-cli-mirage#144]
This problem occurs for versions 0.0.28 and 0.0.29 of ember-cli-mirage

Run `ember build` and get error of "Build failed. Path or pattern "bower_components/lodash/lodash.js" did not match any files".

Run `bower install lodash` and `ember build` then works as expected.

Saw https://github.com/samselikoff/ember-cli-mirage/issues/114 but it still doesn't seem to be working as expected.

**Comment by samselikoff** [comment]
it's not mirage, it's your version of ember cli, it's not running `ember g ember-cli-mirage` after install

what version of CLI?

**Comment by notmessenger** [comment]
Oh yeah...that would do it.  What I'm actually doing is I bumped up the version of the library in `package.json` but am never re-running the install command and/or running the generator.

When I ran `ember g ember-cli-mirage` all now works correctly.  Sorry about that and thanks!

The app is currently running 0.1.15 of Ember CLI

**Comment by samselikoff** [comment]
glad to hear :)
