### ISSUE TITLE
nfig

### ISSUE THREAD

**Issue by tszymon** [samselikoff/ember-cli-mirage#1441]
# Feature request

If this is a feature request, add a 👍 reaction to it. We use these to help us prioritize new feature development!

# Bug or question

If possible, please use the Mirage Boilerplate CodeSandbox to demonstrate your issue or bug:

1. Open the Mirage Boilerplate CodeSandbox:

    https://codesandbox.io/s/003o6pq34n

2. Click Fork

3. Reproduce your issue and save

4. Include the URL to your Sandbox in your issue

**Comment by locks** [comment]
Hi @tszymon, there seems to have been a problem with your posting because it contains the boilerplate. Can you update it?

**Comment by tszymon** [comment]
Sorry, I must have created it accidentally.
