### ISSUE TITLE
Renaming `.schema` to `._schema` broke our ability to guard against creating duplicates

### ISSUE THREAD

**Issue by psbanka** [samselikoff/ember-cli-mirage#1446]
# Bug / question

we were doing something like this in one of our mirage models to simulate an authentication token:

```js
export default Model.extend({
  save() {
    const result = Model.prototype.save.apply(this, arguments)
    const { schema } = this

    if (schema.tokens.length >= 1) {
      throw new Error('Cannot create token when token exists')
    }

    localStorage.setItem(
      'sessionToken',
      JSON.stringify({
        access_token: 'abcde', // eslint-disable-line camelcase
        id: this.id,
      })
    )
    return result
  },

})
```

Due to this change: https://github.com/samselikoff/ember-cli-mirage/commit/557180de580c2d2a9a811e34c9de7bf992398477 , this code is now broken because `this.schema` is now `this._schema`. So...three questions:

1. Is `this._schema` truly private, and should we avoid using it from now on?
2. Shouldn't a change like this require at least a minor version-bump and not a bug-fix bump if you're following semver?
3. Do you have any other recommendations for accomplishing this other than using `this._schema` ?

Thanks! I absolutely love mirage and the work y'all do!

**Comment by samselikoff** [comment]
Sorry I never responded to this... did we chat about it online somewhere?

So I agree this is kinda confusing. I need to figure out a better way to document what is "public" to end-users and what is "public" to other classes within Mirage. I don't think we (the ember community) should operate under the assumption that all public/non-prefixed methods on every class under `/addon` should be seen as a public API authors are committed to support. I hope the AddonDocs site helps with this by documenting things I don't mark with `@hide`, and having that more or less be my public API.

That being said I can see why you went down this road, totally reasonable.

Now to answer the question, personally I don't ever override `save()` and don't see these methods as public API either. We really need to add things like `beforeSave` and `afterSave` to the model layer. But for now, I think I'd do all this in the route handler layer. Have the route handler check for the auth token, and respond accordingly.

If it becomes a common thing you need to do across multiple routes, extract a higher-order function for reuse. I explain in this video:

https://embermap.com/topics/mirage-tips-and-tricks/using-higher-order-functions-to-generate-route-handlers

**Comment by psbanka** [comment]
Thanks, @samselikoff . That totally works and makes sense.
