### ISSUE TITLE
Timing forced to 0 in test environment?

### ISSUE THREAD

**Issue by acj3840** [samselikoff/ember-cli-mirage#1458]
Is this.timing supposed to be ignored in a test environment?

I feel like the [docs](http://www.ember-cli-mirage.com/docs/v0.4.x/configuration/#timing) imply that you can add a global timing delay to all requests, but https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/server.js#L273 very clearly overrides any global timing if running in a test environment.

Is this a case where the docs could be more explicit? Or should the code do something different?

**Comment by samselikoff** [comment]
Yeah the docs do say the default is 0 in testing, it's so your tests run faster. You can override this by putting `this.timing = 100` at the top of a test.

The idea being if you had `this.timing = 100` in your `config.js` file for development, you don't want that to slow down your test suite.

If it's not clear from the docs we could definitely update them 👍

**Comment by acj3840** [comment]
Awesome! That makes a lot more sense now. I've included a PR https://github.com/samselikoff/ember-cli-mirage/pull/1459 to help possibly clarify the docs a bit better.

**Comment by samselikoff** [comment]
Thanks for the PR!
