### ISSUE TITLE
Heroku missing ember-cli-mirage module

### ISSUE THREAD

**Issue by glrangel** [samselikoff/ember-cli-mirage#1462]
I am trying to deploy an ember app on heroku. I am using this buildpack https://codon-buildpacks.s3.amazonaws.com/buildpacks/heroku/emberjs.tgz and my project is successfully builds. When I check the deployed url (https://crud-authors.herokuapp.com/) I get this error:

> Error while processing route: authors.index Could not find module `ember-cli-mirage` imported from `project/controllers/authors/index`

Any help would be appreciated, thanks!

**Comment by samselikoff** [comment]
Hm, do you need enable in production?

Check the [Environment options](http://www.ember-cli-mirage.com/docs/advanced/environment-options#enabled) docs for the `enabled` option

**Comment by samselikoff** [comment]
Closing for now – let me know if you need any more help!
