### ISSUE TITLE
`passthrough()` is intercepting requests that should pass through

### ISSUE THREAD

**Issue by kevinansfield** [samselikoff/ember-cli-mirage#1464]
I have a mirage development config that looks like this:

```
export default function () {
    this.namespace = '/ghost/api/v2/admin';
    this.timing = 400;
    this.logging = true;

    this.createList('member', 200);
    this.get('/members/');

    // keep this line, it allows all other API requests to hit the real server
    this.passthrough();

    // add any external domains to make sure those get passed through too
    this.passthrough('https://count.ghost.org/');
    this.passthrough('http://www.gravatar.com/**');
}
```

In general this works absolutely fine, unspecified API routes pass through to our server and external requests work too.

However, I've just run into an issue where local assets URLs which don't match the configured namespace are being intercepted rather than passed through.

<img width="1221" alt="image 1" src="https://user-images.githubusercontent.com/415/51600932-028e1000-1efb-11e9-9376-45bef6cc2fbf.png">

I haven't been able to find any passthrough config that will allow local requests outside of the configured namespace to work. Is this expected behaviour or a bug?

**Comment by kevinansfield** [comment]
After reviewing the code I found that it's possible to configure passthrough's before the `namespace` property is set. This config is working 👍

```
export default function () {
    this.passthrough('/ghost/assets/**');

    this.namespace = '/ghost/api/v2/admin';
    this.timing = 400;
    this.logging = true;

    this.createList('member', 200);
    this.get('/members/');

    // keep this line, it allows all other API requests to hit the real server
    this.passthrough();

    // add any external domains to make sure those get passed through too
    this.passthrough('https://count.ghost.org/');
    this.passthrough('http://www.gravatar.com/**');
}
```

**Comment by samselikoff** [comment]
Ugh I know this is super confusing. Could also reset `namespace` after your mocks but before passthrough, so you can leave the passthrough calls at the end.

**Comment by egaleme** [comment]
So how do you make a post request with some body params to an exernal url?

**Comment by samselikoff** [comment]
@egaleme You can handle external requests by either setting the [urlPrefix](https://miragejs.com/api/classes/server/#url-prefix) or putting the full domain in your handlers:

```js
this.get('api.twitter.com/tweets', () => {
  return [ {id: 1} ];
})
```
