### ISSUE TITLE
acceptance test broken after upgrading mirage

### ISSUE THREAD

**Issue by Pingu69** [samselikoff/ember-cli-mirage#1465]
Hello, I have upgraded my ember-cli-mirage from 0.2.5 to 0.4.12, and now my acceptance tests stopped working. Instead of going through the handler I defined in mirage config, the test actually tries to access the url... Any idea what the problem might be?
Here is an example test:
```
 test('visiting /content/id of the page with content blocks content does not fail', async function(assert) {
   await visit(CONTENT_WITH_CONTENT_BLOCKS_PAGE_URL);
   assert.equal(currentURL(), CONTENT_WITH_CONTENT_BLOCKS_PAGE_URL, 'Content block URL is correct');
  });
```

This is my handler I defined in mirage config 
```
    this.get('/contents', (_, request) => {
    if (request.queryParams && request.queryParams['filter[tags]']) {
      return getContentByQuery();
    }

    return getContent(parseContentId(request));
  });

```
it worked before I upgraded mirage, I also checked for any breaking changes, but I couldn't find anything obvious

EDIT: I accidentally deleted some helpers for my tests, I restored them and it works again

**Comment by samselikoff** [comment]
Sweet! Closing for now, let me know if you run into anything else :)
