### ISSUE TITLE
Disable namespace for specific route

### ISSUE THREAD

**Issue by Fryie** [samselikoff/ember-cli-mirage#147]
On my server, my typical API endpoints are namespaced with '/v1'. However, I also have an OAuth Authentication Server returning tokens under '/oauth/token'.

Is there a way to disable the namespace just for that specific route? If not, that would be a nice thing to have, since I wouldn't have to type in '/v1' for all the other routes.

**Comment by samselikoff** [comment]
actually the `this.namespace` option only affects routes defined below it, so you could define your oauth route first, then namespace, then the rest of your endpoints. (I need to add this to the docs).

Does this help?

**Comment by Fryie** [comment]
Ah yes. Awesome. That definitely helps :)
