### ISSUE TITLE
A model instance can't belong to itself

### ISSUE THREAD

**Issue by aaxelb** [samselikoff/ember-cli-mirage#1479]
We have a model with a reflexive `belongsTo` relation, and it often points from a model instance back to itself. We're trying to do something like:
```js
afterCreate(user) {
    user.update('representative', user);
}
```
but it looks like it's impossible to do this in mirage. Saving a relation requires that the related object is not currently being saved, so it always skips the self relation:
https://github.com/samselikoff/ember-cli-mirage/blob/33049c5db50b609054b146165ac00683f48630d0/addon/orm/model.js#L880

This feels like a bug to me, but I suppose it could also be considered a feature request.

Repro with passing and failing test: https://codesandbox.io/s/v35v9ry60

**Comment by samselikoff** [comment]
Thanks for the repro! Looking now.

Btw I couldn't get your sandbox working, I think it's because you changed the name, which automatically changes the `package.json` name field which breaks certain things. It's a very annoying aspect of the currenct CodeSandbox setup...

**Comment by samselikoff** [comment]
https://github.com/samselikoff/ember-cli-mirage/pull/1495 should fix, just checked it against your repro and tests pass 👍
