### ISSUE TITLE
February 2019 update

### ISSUE THREAD

**Issue by samselikoff** [samselikoff/ember-cli-mirage#1494]
I've been focused on closing bugs in prep for a 1.0 release. We've just got a few more issues to work out.

I also updated our site recently, and just today, our blog. The blog is now powered entirely by GitHub pages – both the blog content and the comments. It's a new architecture I plan on writing more about, and hope to upstream into AddonDocs so every addon can easily have their own development blog out of the box.

More soon! Here's hoping this blog architecture works out. 👍

**Comment by samselikoff** [comment]
You can now comment via GitHub! 🎉

**Comment by oligriffiths** [comment]
Woah this is dope. Well done 👏

**Comment by dfreeman** [comment]
Very cool! 💯

**Comment by mehulkar** [comment]
That's awesome! how do you get the custom timestamps? Looking forward to seeing if I can make it work on GHE!

**Comment by samselikoff** [comment]
@mehulkar just using GitHub's API and Ember Moment's `moment-from` component

**Comment by ryanto** [comment]
Awesome!!! 🎉 🎉 🎉

**Comment by mehulkar** [comment]
@samselikoff but I see that you posted all the Blog Post issues yesterday, but some of them are showing up as 2015 posts on the site. Is there some frontmatter or something in the posts with the extra metadata?

**Comment by samselikoff** [comment]
@mehulkar yep – I'm using HTML comments to post YAML metadata. It looks like this:

```
<!--
publishedAt: "2015-01-04"
slug: "rewriting-npm"
-->

In this post I'm going to rewrite npm...
```

I'll detail it in an upcoming post.
