### ISSUE TITLE
Initializer has broken import

### ISSUE THREAD

**Issue by ryanbillingsley** [samselikoff/ember-cli-mirage#150]
This [line](https://github.com/samselikoff/ember-cli-mirage/blob/master/app/initializers/ember-cli-mirage.js#L3) is breaking `ember-browserify`.

I am not totally up to speed on ES6 module imports, but changing the line to

`import {baseConfig, testConfig} from '../mirage/config';`

at least got ember to build again.

**Comment by samselikoff** [comment]
but `baseConfig` is the default export, not a named export. Not sure this will work?

**Comment by ryanbillingsley** [comment]
@samselikoff it may not be an issue anymore after ember-browserify's last update.  I haven't had a chance to go and check it though and won't for sometime.

I would go ahead and close this and if/when I can get back to it or someone else has this issue, it could be reopened?

**Comment by samselikoff** [comment]
sounds good :)
