### ISSUE TITLE
Could not find module `lodash/assign`

### ISSUE THREAD

**Issue by SparshithNR** [samselikoff/ember-cli-mirage#1548]
I recently upgraded from version `0.4.6` to `0.4.15`. When I `ember serve` my app I am getting the following error
```js
Uncaught Error: Could not find module `lodash/assign` imported from `ember-cli-mirage/factory`
    at missingModule (vendor.js:255)
    at findModule (vendor.js:266)
    at Module.findDeps (vendor.js:176)
    at findModule (vendor.js:270)
    at Module.findDeps (vendor.js:176)
    at findModule (vendor.js:270)
    at Module.findDeps (vendor.js:176)
    at findModule (vendor.js:270)
    at Module.findDeps (vendor.js:176)
    at findModule (vendor.js:270)
```
I found that https://github.com/samselikoff/ember-cli-mirage/commit/dcab27a7bb775e1d6afda90cf8c2c9e81b9d1fd1 removed ember-lodash and added lodash. I think this error has something to with this change.

When I added `ember-lodash` to my project and tried serving app I could successfully serve it.

**Comment by sunishsheth2009** [comment]
Yes, I could reproduce this as well. I think instead swapping lodash for ember-lodash, we could add [lodash-es](https://github.com/lodash/lodash/tree/es) which ember-lodash previously got.

**Comment by samselikoff** [comment]
Sorry for the delay response!

Could either of you produce a simplified reproduction? Auto import should be taking care of the import...

**Comment by jackson-dean** [comment]
I'm seeing a similar issue upgrading from 0.4.12 to 1.0.0
Adding ember-lodash to my package.json also resolves the error, 
but I would prefer not to have to do that.
My repo isn't public so I can't share it...

**Comment by jackson-dean** [comment]
ok, I found the fix for this. Need to tell ember-auto-import to not use `eval` for source maps by adding the following option to ember-cli-build.js

`  let app = new EmberApp(defaults, {
    // Add options here
    autoImport: {
      forbidEval: true,
    }
  });`

**Comment by samselikoff** [comment]
Hoping https://github.com/samselikoff/ember-cli-mirage/pull/1666 closes.

Please let me know if this is still an issue!
