### ISSUE TITLE
Missing documentation in serializer.js?

### ISSUE THREAD

**Issue by nino** [samselikoff/ember-cli-mirage#1560]
In [`addon/serializer.js`](https://github.com/samselikoff/ember-cli-mirage/blob/be23f538131228d1deeec1aedf9a2a51f0a7957f/addon/serializer.js#L902), the following methods don't have any documentation:

- `keyForForeignKey`
- `keyForPolymorphicForeignKeyId`
- `keyForPolymorphicForeignKeyType`

Since they are not marked `@private`, and don't have a leading `_`, I'm assuming they are meant to be public. Is that correct?

**Comment by samselikoff** [comment]
Correct! Just laziness on my part... would love some help!

From the commit for `keyForForeignKey`:

```
- new serializer hook: `keyForForeignKey`
  - used for belongsTo relationships (keyForRelationshipIds)
  - TODO: this is an awful name, change it
```

**Comment by samselikoff** [comment]
d34784201bfe1e5c2e7c331e7c5c54e26d8aa152 closes

**Comment by dgaus** [comment]
keyForForeignKey is still undocumented

**Comment by samselikoff** [comment]
I believe it's there on master's docs ya? https://www.ember-cli-mirage.com/versions/master/docs/api/modules/ember-cli-mirage/serializer~Serializer#keyForForeignKey

**Comment by dgaus** [comment]
You're right, sorry, I missed that. Thanks!

>
