### ISSUE TITLE
[Documentation] Broken link to Serializers and Faker guides

### ISSUE THREAD

**Issue by belgoros** [samselikoff/ember-cli-mirage#1563]
[Quickstart](https://www.ember-cli-mirage.com/docs/quickstart) section contains a link to the [Serializers guide](https://www.ember-cli-mirage.com/serializers) whick is broken.
<img width="749" alt="Screenshot 2019-03-27 at 11 06 34" src="https://user-images.githubusercontent.com/83579/55067758-96599500-5080-11e9-8bb8-3857001dd57d.png">

The same for [Faker guide](https://www.ember-cli-mirage.com/docs/factories#using-fakerjs):
<img width="327" alt="Screenshot 2019-03-27 at 16 10 01" src="https://user-images.githubusercontent.com/83579/55087862-08df6a80-50ab-11e9-8a0b-82d888975c51.png">

**Comment by samselikoff** [comment]
ea53b9ab5f9ccc25ec1fc72f0cdca14a0018e7a7 and 41f436dd39ff11ea7f4415f999a239c20d36706a close.

Thanks for opening this!
