### ISSUE TITLE
Directory not found: /tests/dummy/mirage

### ISSUE THREAD

**Issue by masterchef** [samselikoff/ember-cli-mirage#1564]
To reproduce:
1. add the following package.json
```
"ember-addon": {
    "configPath": "ember-config"
  }
```
2. `rename "config" folder to "ember-config"`
3. Make sure you don't have the following set in environment.js
```
ENV['ember-cli-mirage'] = {
      directory: 'mirage'
    };
```
4. Try running tests or `ember s`
Sandbox example: https://codesandbox.io/s/xolz43y89w

**Comment by samselikoff** [comment]
@masterchef sorry for the delay here.

When I start a new addon I get a default `configPath` of

```
"configPath": "tests/dummy/config"
```

Did you mean to say change this to

```
"configPath": "tests/dummy/ember-config"
```

? (Not top-level `ember-config`?)

**Comment by masterchef** [comment]
@samselikoff, no worries.

I think the issue is with my particular setup of the project. I'm not actually making an addon, but have to have ember-addon configured to just change the config folder location due to the nature of our system. Closing, thanks for your time!
