### ISSUE TITLE
Clear behavior of Schema.first() on empty collection and Schema.findBy() on empty result

### ISSUE THREAD

**Issue by jelhan** [samselikoff/ember-cli-mirage#1567]
It's currently not defined how `first()` and `findBy()` methods of a `Schema` behave if schema doesn't have any record (`first()`) or doesn't have any matching record (`findBy()`).

This case isn't mentioned in docs for either of them. It's not [covered by tests for `schema.first()`](https://github.com/samselikoff/ember-cli-mirage/blob/master/tests/integration/orm/first-test.js). I wasn't able to find any tests for `Schema.findBy()`.

There is a similar case of `DbCollection.findBy()`. It's docs also doesn't cover how it behaves if no record matches the criteria but it has test coverage for that scenario: https://github.com/samselikoff/ember-cli-mirage/blob/20d9d84841ebbeb7672a313282b8a03a0bfe1338/tests/unit/db-test.js#L276-L280

Based on that test coverage, which exists since implementation of that feature, I would expect that `Schema.findBy()` and `Schema.first()` also return `null` if no record is found. This should be covered by tests and mentioned in docs for all of them.

**Comment by samselikoff** [comment]
agree 👍

**Comment by Oreoz** [comment]
@samselikoff Just opened a PR that attempts to fix this! Thanks for this great addon.
