### ISSUE TITLE
Question: Is there the opposite of passthrough?

### ISSUE THREAD

**Issue by crhayes** [samselikoff/ember-cli-mirage#1580]
Often during feature development I would like all requests to pass through EXCEPT requests to new endpoints that are currently under development.

However configuring passthrough for all existing API endpoints (except a few under development) is cumbersome.

Is there a way to easily achieve this currently?

**Comment by samselikoff** [comment]
Did you try ‘this.passthrough()’ (no args)? It passes all requests through for the current domain.

**Comment by crhayes** [comment]
I would like a list of endpoints that aren't passed through.

So for instance, if I had 100 endpoints and wanted to stub out 3 additional ones that my backend team was currently working on, I could intercept just the 3 endpoints under development and allow the other 100 to pass through.

**Comment by samselikoff** [comment]
something like this should do it:

```js
export default function() {
  this.get('/mocked-1');
  this.get('/mocked-2');
  this.get('/mocked-3');
  
  this.passthrough(); // all others pass through
}
```

**Comment by samselikoff** [comment]
Let me know if you have any more questions about this!
