### ISSUE TITLE
Per-relationship control for alwaysIncludeLinkageData

### ISSUE THREAD

**Issue by lukemelia** [samselikoff/ember-cli-mirage#1588]
In json-api-resources, the Rails implementation we use, we are able to specify `always_include_linkage_data: true` on a per-relationship basis within a resource.

In mirage, the `alwaysIncludeLinkageData` property of jsonapi-serializer is an all-or-nothing proposition. It applies to all relationships on a model.

This makes it impossible to easily make mirage conform to our server behavior.

One possible solution would be to add an overridable method to jsonapi-serializer `shouldIncludeLinkageData(key, model)` that returns a boolean. It would be nice to further allow an option on the model relationship declarations themselves, but the method would provide an outlet for developers to address the situation. We would be happy to work on a PR to add this if there is a consensus that it's a good idea.

**Comment by samselikoff** [comment]
Yep, makes sense.

Given today's architecture I _think_ this would make the most sense on a per-model serializer... we have plans to introduce a new `resource` class that acts as a point of abstraction between the Model and Serializer, in the same way it does in JR. If that existed it would probably be the best home for this option.

Out of curiosity how are you using this in your actual JR server? Why do some relationships enable it?

**Comment by lukemelia** [comment]
All makes sense.

Example of how this is declared in our server app:

```rb
       # post_resource.rb
       #...
       has_one :author, class_name: 'Profile', always_include_linkage_data: true
```

We use this for two reasons that I can remember:

1. we have an app where half the models are still using active-model-serializers and half are using JR. This helps us deal with the relationships that cross these boundaries.
2. this means that linkage data for key relationships appear in the response to POST/PUT operations when they wouldn't normally.

**Comment by lukemelia** [comment]
Boom! https://github.com/samselikoff/ember-cli-mirage/pull/1590

**Comment by samselikoff** [comment]
3df9ae92d0bb133ff7f74f4d3129b0c5539bb8dd closes

**Comment by mattmcmanus** [comment]
@samselikoff Any idea on when this will be released?

**Comment by samselikoff** [comment]
@mattmcmanus working on v1.0-beta.1 as we speak actually!
