### ISSUE TITLE
Console Warning: ignoring input sourcemap for bower...

### ISSUE THREAD

**Issue by benedikt-d** [samselikoff/ember-cli-mirage#159]
Console is throwing a warning after mirage installation:

Warning: ignoring input sourcemap for bower_components/route-recognizer/dist/route-recognizer.js because ENOENT, no such file or directory '/Users/user/repol/Code/myapplication/tmp/tree_merger-tmp_dest_dir-4R7asWVx.tmp/bower_components/route-recognizer/dist/route-recognizer.js.map'

**Comment by benedikt-d** [comment]
changed title to be more explicit

**Comment by sarus** [comment]
Getting this warning as well with the latest ember-cli-mirage

```
ember-cli-mirage: v0.1.2
ember-cli : v0.2.7
ember.debug.js:4888DEBUG: Ember             : 1.12.0
ember.debug.js:4888DEBUG: Ember Data        : 1.0.0-beta.18
ember.debug.js:4888DEBUG: jQuery            : 1.11.3
ember.debug.js:4888DEBUG: Ember Simple Auth : 0.8.0-beta.2
```

**Comment by benedikt-d** [comment]
Also if I do a get request in the browser i get: Uncaught UnrecognizedURLError: http://localhost:4200/api/foo/
I don't know if this is intended. Because the app does the GET requests to the api requests just fine. Would be nice to see what the json objects look like in the Browser though.

**Comment by benedikt-d** [comment]
This is the issue:
https://github.com/tildeio/route-recognizer/issues/44

**Comment by blimmer** [comment]
The original issue was fixed by [this PR](https://github.com/tildeio/route-recognizer/issues/44). This can be closed.

**Comment by samselikoff** [comment]
awesome, so pretender just needs to update that right? or users in their own projects?
