### ISSUE TITLE
how to fetch the has many relationship in ember-cli-mirage?

### ISSUE THREAD

**Issue by Dominicbarretto** [samselikoff/ember-cli-mirage#1606]
so i have created a jsonapi payload in my mirage/config, i am able to get the author data, but i m unable t get the books data, wat settings do i need to do to get the included part?
```
data:{
attributes:{name: "joseph"}
type:"Author"
id:"1"
relationships: {books: {data: [{id: "1", type: "books"}, {id: "2", type: "books"}]}}
}
included:
[
{id: "1", type: "books", attributes: {title: "catch22"}}, 
{id: "2", type: "books", attributes: {title: "catch23"}}
]
```

i am unable to fetch the included part
when i do this.get('author.books').mapBy('id'), i get an empty array[]

NOTE: THAT is the actual response from my local server, ii works fine there, but only in testing it dosent work

**Comment by samselikoff** [comment]
Check out the `alwaysIncludeLinkageData` option on the serializer: https://www.ember-cli-mirage.com/docs/api/modules/ember-cli-mirage/serializers/json-api-serializer~JSONAPISerializer#alwaysIncludeLinkageData

If you do something like this

```
// mirage/serializers/application.js
import { JSONAPISerializer } from 'ember-cli-mirage';

export default JSONAPISerializer.extend({
  alwaysIncludeLinkageData: true
});
```

you should get the IDs in the payload.

**Comment by Dominicbarretto** [comment]
thanks for the reply, actually i tried the above thing,  
so this is what i am trying to achive

`
this.get('/authors', () => {
   

    *** some logic i need to implement here **

    var author = server.db.authors.find(1)
    // debugger
    var included = []
    var book_array = []
    var included_array = []
    if(author.bookIds != null){
      author.bookIds.forEach((book) => {
        var book = server.db.books.find(book)
        book_array.push({id: book.id, type: "books"})
        included_array.push({id: book.id, type: "books", attributes: book})

      })
      included =  included_array
    }

    return {data: {type: 'authors', id: author.id, attributes: author, relationships: {books:book}}, included:  included_array };
});
`
so here i have created a payload so that i get a suitable response, i did it this way beacuse i need to implement some logic here, normally i would have just done: ` this.get('/authors');`
and yes i have also included `alwaysIncludeLinkageData: true` in my serializer

so the above query gives me the author data, but fails to give the books data

**Comment by Dominicbarretto** [comment]
an ya i m using queryRecord to fetch the autor and books info

**Comment by Dominicbarretto** [comment]
sorry there was a small issue in my payload, it works fine now
