### ISSUE TITLE
Cannot GET /url

### ISSUE THREAD

**Issue by sebyx07** [samselikoff/ember-cli-mirage#162]
i tried to add mirage in main app, tried the example but they all return the same: status 404
so i even made a new app just to test why it doesn't work. The problem is both test and dev env.
The same result is even if i curl the url

I use the latest version of ember cli and ember 1.12

**Comment by samselikoff** [comment]
Could you post your mirage/config.js?

**Comment by sebyx07** [comment]
i used it from the example: https://gist.github.com/sebyx07/c691e08e4f5febf4ff88
so when i try to `$ curl http://localhost:4200/api/users` i get : Cannot GET /api/users

**Comment by samselikoff** [comment]
Mirage only intercepts requests generated by the browser, so `curl` won't work. Is your Ember app working?

**Comment by sebyx07** [comment]
the ember app works, but requests don't get intercepted neither in dev or when running tests

**Comment by samselikoff** [comment]
Does Mirage throw an error? What happens when your app requests `/api/users`?

**Comment by sebyx07** [comment]
ah i only get this warning
`
Warning: ignoring input sourcemap for bower_components/route-recognizer/dist/route-recognizer.js because ENOENT, no such file or directory '/home/sebi/RubymineProjects/test_mirage/tmp/tree_merger-tmp_dest_dir-bGa9kNS3.tmp/bower_components/route-recognizer/dist/route-recognizer.js.map'

`

**Comment by samselikoff** [comment]
Check the browser's console

**Comment by sebyx07** [comment]
https://gist.github.com/sebyx07/c97d63627a25aab0714c

**Comment by samselikoff** [comment]
This should work in development, but it won't work in that test because Mirage is booted up in an Ember initializer.

You can just 

```js
import startApp from 'your-app/tests/helpers/start-app';
```

and then run `startApp()` in the `beforeEach` block of your test. That should start the Mirage server.

**Comment by blimmer** [comment]
Since this issue has been quiet for some time, I'm going to close it. Feel free to reopen if there's still an issue.
