### ISSUE TITLE
Relations and fixtures

### ISSUE THREAD

**Issue by marxsk** [samselikoff/ember-cli-mirage#1620]
ember-cli-mirage 0.4.15

I'm trying to create a fixture with belongsTo relation.
ember-models:

vendor => (name)
item> = (price, belongTo(vendor), name)

Creating fixtures for vendor works as expected. I have tried to follow documentation with the following fixture:: [vendor with ID 1 exists and is loaded via findAll to ember]
```
export default [ { id: 1, revenue: 333, vendorId: 1 } ];
```
Your GET handler for the url /invoice-items threw an error: Cannot read property 'isPolymorphic' of undefined.

And I was not able to find this issue anywhere. So I tried to go a different way:

```
const vendor = server.schema.vendors.find(1);
server.create("invoice-item", {
    id: 111,
    vendor,
    revenue: 777
  });
```

Result is 
You're trying to create a invoice-item model and you passed in a model:vendor(1) under the vendor key, but you haven't defined that key as an association on your model.

So the last attempt was to use vendor.id instead and it passes but it looks more like silent error. 

What am I doing wrong?

**Comment by samselikoff** [comment]
Code looks right to me, with the exception of `item` vs. `invoice-item`.

Could you create a simplified reproduction, either using the [CodeSandbox boilerplate](https://codesandbox.io/s/003o6pq34n) or by uploading a repo?

**Comment by marxsk** [comment]
@samselikoff 

I have simplified the names - my original model is 'aggregate-invoice-items' what may cause troubles as well :)

I'm unable to reproduce it via CodeSandbox but I have found out that there is a difference when I do `console.log(server.db.dump());` at the end of the default scenario. In the CodeSandbox, there is `@each` but I don't have it on my machine. I don't know if it is relevant to this issue or not.

I have also add 'include' into serializer and when I'm using CodeSandbox - it works as expected but not on my local machine. 

The simplified code is available at https://github.com/marxsk/problem-mirage ; I'm using google-inspector to check what is loaded in the page.

Thanks for a help

**Comment by samselikoff** [comment]
I think the problem is that you've defined Mirage models, and those models have no relationships defined on them.

Because you're using Ember Data, you can skip creating any Mirage models at all, since they will be autodiscovered from your Ember Data models.

So, try deleting the `mirage/models` folder and see if that fixes it!

**Comment by marxsk** [comment]
Thanks, it works. 

Do you think it is worth mentioning this in the documentation?

**Comment by samselikoff** [comment]
I've recently reworked the docs to call this out in several places so I'm hoping that clears it up.

There might be a way to add a run-time assertion to the library though, if this keeps coming up.

Glad you got it figured out!

**Comment by samselikoff** [comment]
Here's the new overview which has a paragraph: https://www.ember-cli-mirage.com/versions/docs-updates/docs/getting-started/overview. I think I'll eventually give it a more prominent alert-like visual treatment.

Feel free to leave any more feedback about it!
