### ISSUE TITLE
Can't get to work with Ember Simple Auth

### ISSUE THREAD

**Issue by anthonycollini** [samselikoff/ember-cli-mirage#163]
I am currently trying to acecptance test signing in from my app. I use ember simple auth, have a form set up, and everything works in development.

Upon submitting the form, the browser sends a post request to the api and it works fine. However, in tests, mirage throws the following error:

    Mirage: Your Ember app tried to POST '/token', but there was no route defined to handle this request. Define a route that matches this path in your mirage/config.js file.

However, the route is defined in my config, and I've tried to define it multiple ways. 

    this.post('/token', function(db, request) {
      let data = JSON.parse(request.requestBody);
      if (!data.user.email || !data.user.password) {
        return new Mirage.Response(422,
          { 'Content-Type': 'application/json' },
          { errors:
            { email: 'can\'t be blank' }
          }
        );
      } else {
        return new Mirage.Response(200);
      }
    });

Other factories, POST, and GET requests work fine. It's just signing in. Any thoughts?

Here's my simple test:

    test('redirects to dashboard if logging in from homepage', function(assert) {
      assert.expect(1);

      let currentUser = server.create('currentUser');

      visit('/');

      click('a:contains("Sign In")')

      andThen(function() {
        fillIn('#email', currentUser.email);
        fillIn('#password', 'Password');
        click('button:contains("Sign In")')
      });

      andThen(function() {
        assert.equal(currentPath(), 'dashboard.index');
      });
    });

**Comment by anthonycollini** [comment]
Okay, so I haven't had time to test this yet, but I just realized that simple auth is hitting `/oauth/token`. I have a namespace of `v1` on my api, so I set that at the top of the config file. Since mirage was saying can't find `token`, I'm guessing it does some kind of substitution thinking that the `oauth` part of the request is the namespace and removes it.

Is there a way to tell that one post request to not use the namespace?

**Comment by samselikoff** [comment]
Yep you need to put it above the namespace declaration. `this.namespace` will namespace every route defined beneath it

**Comment by samselikoff** [comment]
http://www.ember-cli-mirage.com/docs/latest/server-configuration/#namespace

**Comment by blimmer** [comment]
@anthonycollini I'm going to close this issue since we haven't heard back from you on this issue. If this is still an issue, please don't hesitate to reopen.
