### ISSUE TITLE
`this.serialize` not working if used in arrow function (as shown in the docs)

### ISSUE THREAD

**Issue by roberkules** [samselikoff/ember-cli-mirage#1634]
from the docs: https://www.ember-cli-mirage.com/docs/data-layer/serializers#working-with-serialized-json

this code does **not work**:

```
// mirage/config.js
this.get('/movies', (schema, request) => {
  let movies = schema.movies.all();
  let json = this.serialize(movies);

  json.meta.size = movies.length;

  return json;
});
```

but in that case `this` is the server instance, which doesn't have the `.serialize` helper.

so it only works by not using the arrow function:

```
this.get('/movies', function (schema, request) {
  let movies = schema.movies.all();
  let json = this.serialize(movies);

  json.meta.size = movies.length;

  return json;
});
```

(using ember 3.9.0, mirage 1.0.0)

**Comment by samselikoff** [comment]
https://github.com/samselikoff/ember-cli-mirage/commit/62432513bf84aa9552316c4785bba3e66b732f16 closes, thanks!

**Comment by dnldmp** [comment]
This still working only with normal functions

**Comment by francoislevesque** [comment]
We also have the same issue using the lastest version

**Comment by cah-briangantzler** [comment]
The code in question has all been extracted to [MirageJS](https://miragejs.com).   The docs there https://miragejs.com/docs/main-concepts/serializers/ show using normal functions not arrow functions. If there is an issue to be raised it should be raised there.
