### ISSUE TITLE
Ember data store is undefined when injected into service tested with mirage

### ISSUE THREAD

**Issue by sarus** [samselikoff/ember-cli-mirage#164]
Not sure if this is a mirage issue or a more general problem with how I'm trying to do testing.  First, thank you for this fantastic library.  It has finally gotten me to bite the bullet on unit and acceptance testing haha.

I have a service called `validator` that I inject the ember data store into.  The store is required because some of the validations provided by the validator service check against the server to see if for example a username already exists.

```javascript
// /app/initializer/validator.js
export function initialize (container, app) {
  // Inject the Ember Data Store into our validator
  app.inject('service:validator', 'store', 'store:main');
}

export default {
  name: 'validator',
  initialize: initialize
};
```

The validator then has a snippet that looks like this:

```javascript
// /app/services/validator.js
import Ember from "ember";

export default Ember.Service.extend({
     username: function(username, options){
          var self = this;
          return new Ember.RSVP.Promise(function(resolve, reject){
               self.store.filter('user', function(user){
                     return user.get('username') === username;
               }).then(function(users){
                     if(users.get('length') > 0){
                           resolve('Username already exists');
                     }else{
                       resolve(null);
                     }
              });
          });
     }
});
```

I've setup a factory to create user data and a config for the users REST API point.

The problem I've run into is that the store object in the validator is undefined when calling the validator service in a test.  Here's an example test:

```
test('[username] cannot be less than minimum length', function(assert){
  assert.expect(1);
  var validator = this.subject();
  var input = 'u';
  var expectedOutput = 'Username must be at least 2 characters';

  validator.username(input).then(function(validationMessage){
    assert.equal(validationMessage, expectedOutput);
  });
});
```

and the error:

```
TypeError: 'undefined' is not an object (evaluating 'self.store.filter') at http://localhost:7357/assets/my-project.js, line 2122
```

Could this be Mirage related or am I just setting up the test wrong in a more general sense?

Thank you!

**Comment by samselikoff** [comment]
I believe this is because the `container` isn't initialized in unit tests. I think they're working on integration tests but for now, I would just throw this in an acceptance test (you can call it `/tests/integration` or something), and import `startApp` and run it

```
import startApp from 'your-app/tests/helpers/start-app';

module('your service', {
  beforeEach: function() {
    application = startApp();
  },

  afterEach: function() {
    Ember.run(application, 'destroy');
  }
});
```

and see if that works.

**Comment by sarus** [comment]
Thank you very much for the additional info.  For anyone else trying to do this I booted the app as pointed out by samselikoff and imported the service like this:

```javascript
var application;
var validator;
module('Service | Validator', {
  beforeEach: function() {
    application = startApp();
    validator = application.__container__.lookup('service:validator');
  },
  afterEach: function() {
    Ember.run(application, 'destroy');
  }
});
```

This seems to allow me to test the service and ensure the service has access to the ember data store which gets injected via an initializer.

I think I've run into an issue in that my usage of `this.store.filter` does not include a query (no query params) and as a result does not issue a request to the server, and therefore mirage does not get a chance to send back data from the factory I created.

Just to test I added in a query so that my call looks like:

```
self.store.filter('user', function(user){
    return user.get('username') === username;
})
```

This ensures a database request each time a validation is done.  Unfortunately, I'm now getting the following error:

```
Assertion Failed: The response from a findQuery must be an Array, not undefined
```

I believe this is caused by this error which I can see in the browser:

```
Mirage: Your custom function handler for the url /v1/users?limit=100 threw an error: db.users.all is not a function TypeError: db.users.all is not a function
```

I have a factory called `/app/mirage/user.js` (singular as in the examples) and my route looks like

```
  this.get('/users', function(db, request) {
    return db.users.all(); // <-- this is what is failing
  });
```

I populate the db using:

```
server.createList('user', 10);
```

I do see the `users` array in the `db` object but do not see an `all` method.  If I just return the db things work:

```
  this.get('/users', function(db, request) {
    return db; // <-- this works because the db object contains a users array which is what ember data is expecting
  });
```

**Comment by samselikoff** [comment]
The current API is just db.users to return the collection. .all is going to
be the future api but it hasn't landed yet - where did you see it?

**Comment by sarus** [comment]
@samselikoff Saw it on the quick start guide:

http://www.ember-cli-mirage.com/docs/latest/quickstart/

```
Dynamic data

In the examples above, we wrote the response data directly in the route. Instead of doing this, Mirage provides a simple in-memory database you can use to make your routes more versatile.

The database is injected into each route handler as the first parameter:

this.get('/api/users', function(db) {
  return db.users.all();
});
Route handlers can also create, update and delete database records.
Now, Mirage will respond to this route with all the user records in its database. To seed your database with data, you can use fixtures or factories.

As long as all your Mirage routes read from and write to the database, user interactions will persist during a single session. This lets users interact with your app as if it were wired up to a real server.

View the full database API to see how your routes can interact with your data.
```

Was I using this in the wrong context?

**Comment by samselikoff** [comment]
whoops, that's definitely not the current api. Sorry! that shouldn't be in there.

Right now it's just `db.collection`: http://www.ember-cli-mirage.com/docs/latest/database/#collection

**Comment by samselikoff** [comment]
should be fixed. oy, I can't believe that was wrong like, everywhere. I've been spending too much time in the new models branch (where this api has changed) - thanks so much for pointing this out!

**Comment by sarus** [comment]
No Problem!  Thanks for the great library =)  Got everything working now.
