### ISSUE TITLE
Brand new Ember Octane and Mirage 1.0 not intercepting requests

### ISSUE THREAD

**Issue by JonForest** [samselikoff/ember-cli-mirage#1648]
# Bug 
Sorry, can't use the code sandbox as is related to the Ember Octane. 
Issue is: The app is making XHR requests to a server; the requests are not getting intercepted and I'm getting a 404.
![image](https://user-images.githubusercontent.com/4940106/59154851-e36dd480-8acf-11e9-837c-925c2b99bc0c.png)

In the command line I've completed this:
```
ember new tailwind-demo -b @ember/octane-app-blueprint —yarn.
ember install ember-cli-mirage ember-cli-tailwind
ember g model task description:string detail:string target:date completedAt:date
ember g route dashboard --path='/'
```
In `/app/routes/dashboard.js` I added:
```
model() {
  return this.store.findAll('task')
}
```

In `/mirage/config.js` I added:
```
  this.get('/tasks', (schema) => {
    return {
      data: [
        {id: 1, type: 'tasks', attributes: {description: 'test'}},
      ]
    }
  });
```

Key package.json data is:
```
    "ember-cli": "github:ember-cli/ember-cli#5bb062af85cebdf7dbc77132860dc2547fc7cfa4",
    "ember-cli-mirage": "^1.0.0",
    "ember-cli-tailwind": "^0.7.0",
    "ember-source": "https://s3.amazonaws.com/builds.emberjs.com/canary/shas/0de75b8f751ae13b14b08f0ee6dd7958737fff34.tgz",
```

This can be found in a repo here:
https://github.com/JonForest/temp-ember-mirage-issue-repro

I suspect I've just done something stupid, but I can't see the difference between this and a working Octane app, which had a previous ember-cli, ember-source and Mirage 0.4.15.
(note: tried setting this failing app to 0.4.15 and still no dice, so I don't think it's that.)

**Comment by kevswanberg** [comment]
`ember install ember-fetch`

[ember-fetch](https://github.com/ember-cli/ember-fetch)

Should get it working.

**Comment by brunoocasali** [comment]
I'm with exact same issue, but after did what @kevswanberg suggested worked... But is a mirage or a octane issue?

**Comment by samselikoff** [comment]
I looked at this a bit on the lastest master of Mirage, but the `ember-fetch` package doesn't seem to fix it anymore...

I'm hesitant to dig too much into this while Octane is still being worked on. I'm going to mark this as a feature request until Octane is ready, but I'm going to deprioritize this until then.

If anyone else wants to work on this, feel free to dive in! And I'd be happy to help out any way I can.

**Comment by samselikoff** [comment]
Believe this was fixed (somehow) with some of the recent commits. Give `1.1.0-beta.4` a shot.
