### ISSUE TITLE
Missing documentation on defining models

### ISSUE THREAD

**Issue by lolmaus** [samselikoff/ember-cli-mirage#1665]
There used to be docs on defining models: https://www.ember-cli-mirage.com/versions/v0.4.x/models/

In the latest version of the website, it no longer exists.

Polymorphic relationships are never mentioned, hasMany/belongsTo are not mentioned.

The very fact that defined models are required for relationships to work is not mentioned!

**Comment by samselikoff** [comment]
You're right! I think the hasMany/belongsTo got shoehorned into the API guides for association. Definitely need all this covered though.

**Comment by lolmaus** [comment]
🙇
