### ISSUE TITLE
ids in fixtures can't be '0'

### ISSUE THREAD

**Issue by Eptis** [samselikoff/ember-cli-mirage#167]
Is there a specific reason for this? Ember cli mirage currently replaces my id's with a different number which interferes with my ui and tests.

**Comment by samselikoff** [comment]
Does the integer 0 work?

**Comment by Eptis** [comment]
Currently using integers but it doesn't work, should I use strings?

**Comment by samselikoff** [comment]
It's because of this: https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/db.js#L55

I'll change it to explicitly check for undefined

**Comment by samselikoff** [comment]
Should be all set!
