### ISSUE TITLE
Issue with loading fixture data

### ISSUE THREAD

**Issue by blankenshipz** [samselikoff/ember-cli-mirage#168]
I'm having an issue with loading fixture data, I can see that the request is made to `/api` and that an array is returned in the console containing the correct data but there seems to be a problem with ember interpreting this response. It seems like ember is trying to find models for the keys of the array as well as the functions defined on the array object rather then the values of the array. 

I'm using `ember-cli-mirage` `0.1.4` and `ember-cli` version `0.1.15` (I'm stuck for the time being on an older version of `ember-cli`

Here's a clipped version of the warnings and errors I'm seeing:

```
ember.js:15373 WARNING: Encountered "1" in payload, but no model was found for model name "1"...
ember.js:15373 WARNING: Encountered "2" in payload, but no model was found for model name "2"...
ember.js:15373 WARNING: Encountered "3" in payload, but no model was found for model name "3"...
ember.js:15373 WARNING: Encountered "_super" in payload, but no model was found for model name... 
... (more of the same)
WARNING: Encountered "sortBy" in payload, but no model was found for model name "sortBy"...
... (more of the same)
Error while processing route: forecasts.index Invalid fullName: `model:@each`, must be of the form `type:name`  TypeError: Invalid fullName: `model:@each`, must be of the form `type:name`...
```

I setup the fixture file as described in the docs, any thoughts as to what might be happening?

Thanks!

**Comment by samselikoff** [comment]
What adapter/serializer do you have specified?

**Comment by blankenshipz** [comment]
It turned out that I was not using the correct definition for a route instead of something like "return objects: db.objects" I was doing "return db.objects"

Switching to the shorthand from the docs fixed my issue.
