### ISSUE TITLE
Test a list of objects for belongsTo object's property value

### ISSUE THREAD

**Issue by sbsurf** [samselikoff/ember-cli-mirage#169]
A Patient `belongsTo` an Account. I have a page which displays a list of patients, one of the columns being their account's name.

If I need to go to `/patients` and test that a list of patients with their account's name are listed, how do I do it? Documentation talks about going to `/accounts/:id` and testing for the account's list of patients, but not the other way around.

Basically, I want to test that an element with the value of `patients[0].account.name` exists on the page.

To set this up, I have tried things like:

    const account = server.create('account'),
         patients = server.createList('patient', 2, {account_id: account.id});

And

    const account = server.create('account'),
         patients = server.createList('patient', 2, {account: account});

And

    const patients = server.createList('patient', 2, {account: {id: 1, name: 'test name'}});

All of which make the test fail. For the 1st example, none of the `account` properties, besides id, are set, making the `patient[0].account.name` check fail. For the 2nd approach, visiting `/patients` never routs to appropriate route. And the 3rd approach has the same problem.

The above happens when my `mirage/config.js` looks similar to:

    export default function () {
      this.namespace = '/api/v1';

      this.get('/accounts');
      this.get('/patients');
    }
    

I have also tried different versions of:

    export default function () {
      this.namespace = '/api/v1';

      this.get('/accounts');
      this.get('/accounts/:id');

      this.get('/patients');
      this.get('/patients', ['account', 'patients']);
    }

For the set up above, the error I get while running the test is:

    TypeError: Pretender intercepted GET /api/v1/patients?page=1&q= but encountered an error: 'undefined' is not an object (evaluating 'owner.id')

I also posted this on SO, in case you'd like to answer it there: http://stackoverflow.com/q/30812897/1042380

Thanks!

**Comment by g-cassie** [comment]
What do your models look like? Are the relationships sync or async?  Are you using embedded records?

**Comment by sbsurf** [comment]
patient.js:

```
import DS from 'ember-data';
import Ember from 'ember';

export default DS.Model.extend({
  firstName: DS.attr('string', {defaultValue: ''}),
  lastName: DS.attr('string', {defaultValue: ''}),
  middleName: DS.attr('string', {defaultValue: ''}),
  dob: DS.attr('date'),
  gender: DS.attr('string'),
  account: DS.belongsTo('account', {async: true})
```

account.js:

```
import DS from 'ember-data';

export default DS.Model.extend({
  name: DS.attr('string'),
  labels: DS.hasMany('label'),
  statuses: DS.hasMany('status')
});
```

**Comment by g-cassie** [comment]
Does your api not include the inverse relationship to patient on account? 

The only thing i would change from your first example is this.  Though I notice in your model you do not define the inverse relationship so you might not even need this.
```js
const account = server.create('account');
const patients = server.createList('patient', 2, {account_id: account.id});
account.patient_ids = patients.mapBy('id');
```

I would make your mirage conf like this:
```
export default function () {
  this.namespace = '/api/v1';

  this.get('/accounts');
  this.get('/accounts/:id');
  this.get('/patients');
  this.get('/patients/:id');
}
```

From your comment it sounds like you might trying to use mirage in a way it can't.  Right now the factories just create POJOs.  So you cannot do this:
```js
const account = server.create('account');
const patients = server.createList('patient', 2, {account_id: account.id});
assert.equal(patients[0].account.name, 'something');
```

You have to do this:
```js
assert.equal(patients[0].account_id, account.id)
assert.equal(account.name, 'something');
```

**Comment by sbsurf** [comment]
Sample output:

`/patients`
```
{"patients":[{"id":2,"pid":"clementine schmeler","first_name":"","last_name":"Clementine Schmeler","middle_name":"","dob":null,"gender":"O","account_id":1,"status_id":null}
```

`/accounts`
```
{"accounts":[{"id":1,"name":"OBGYN","links":{},"status_ids":[],"label_ids":[]},{"id":2,"name":"XYZ","links":{},"status_ids":[],"label_ids":[]}]}
```

**Comment by sbsurf** [comment]
Thanks, I'll ponder your response for a while... I did try 
```
var account = server.create('account', {patient_ids: [1, 2]});
```
similar to your:
```
account.patient_ids = patients.mapBy('id');
```
with no luck yet.

**Comment by g-cassie** [comment]
Can you paste in your actual test?

**Comment by samselikoff** [comment]
You could also try `server.logging = true` in your test and throw in a `debugger` to see what you're getting. Also as @g-cassie said you won't be able to `patient[0].account.name`, you'll need to just grab the account from the `create('account')` call directly.

**Comment by sbsurf** [comment]
The problems stems from the fact that the column displaying Account Name gets its value in the controller like this:

```
Column.create({
    isVisible: false,
    name: 'Account',
    id: 'patient.account.name',
    attr: 'accounts.name',
    getContent: function(patient) {
      return '<a href="/account/%@" data-table-action="link">%@</a>'.fmt(
        patient.get('account.id'),
        patient.get('account.name'));
    }
  }),
```

The value doesn't get displayed, because `patient.get('account.name')` doesn't have a value.

Not sure how else I can use your add-on to test that when an Account is set on a Patient, that Patient's Account Name will show up in the Patients list.

**Comment by samselikoff** [comment]
Are you saying you're expecting the API response to be nested/embedded data? Remember, the purpose of Mirage is to mock out your API. Perhaps it'd be helpful if you posted what you want the data to look like that's returned from a particular endpoint, and we can help you structure your Mirage route accordingly.

**Comment by sbsurf** [comment]
Thanks for you help guys. I think the issue may be stemming from the fact that I'm doing some custom data preloading. Let me play around with it a bit more, see if I can get everything to work as expected. I will update and/or close this issue once I have some more info.
