### ISSUE TITLE
[BABEL] Note: The code generator has deoptimised ...

### ISSUE THREAD

**Issue by DenisNazarenko** [samselikoff/ember-cli-mirage#1699]
#### repo: [mirage-test](https://github.com/DenisNazarenko/mirage-test)

`ember s` getting a note from Babel ==> `[BABEL] Note: The code generator has deoptimised the styling of /bla-bla-bla-path-to/mirage-test/node_modules/@miragejs/server/dist/index.js as it exceeds the max of 500KB.`

<img width="1603" alt="Screenshot 2019-07-25 at 08 22 50" src="https://user-images.githubusercontent.com/17509521/61848046-6945b380-aeb5-11e9-8ebf-221e3ec3f8a1.png">

**Comment by jayzhou3** [comment]
How do we fix that or remove that warning

**Comment by mehulkar** [comment]
Also seeing this

**Comment by samselikoff** [comment]
I think we should replace the Lodash modules in @miragejs/server with the individual npm packages. Quickest way to solve this issue.

**Comment by samselikoff** [comment]
https://github.com/samselikoff/ember-cli-mirage/pull/1747 closes

**Comment by samselikoff** [comment]
This should be fixed in `1.1.1`.

Let me know if you have any more issues!
