### ISSUE TITLE
API links from database page in data layer section are broken

### ISSUE THREAD

**Issue by backspace** [samselikoff/ember-cli-mirage#1709]
Hey, I noticed that the API links at the bottom of the database page in the data layer section are broken. Normally I’d submit a PR but [the Markdown line contains some kind of helper](https://github.com/samselikoff/ember-cli-mirage/blame/master/tests/dummy/app/pods/docs/data-layer/database/template.md#L60) and I didn’t want to dig in too deeply.

You can see that the path shown on hover differs in the body vs the sidebar:

<img width="939" alt="image" src="https://user-images.githubusercontent.com/43280/62571716-b0d62300-b857-11e9-8f90-d988e7b4e77a.png">

<img width="939" alt="image" src="https://user-images.githubusercontent.com/43280/62571843-feeb2680-b857-11e9-8671-9e062707450f.png">

(also the links are reversed in the body)

Thanks for the continued work on this ever-useful project!

**Comment by samselikoff** [comment]
Good catch! [That helper comes from AddonDocs](https://ember-learn.github.io/ember-cli-addon-docs/docs/api/components/docs-link), it's just a styled `link-to`.

The link is broken because I forgot to change the `ember-cli-mirage` part of the path to `lib` after we extracted the code into @miragejs/server. Should be an easy fix if anyone gets to it before me!

**Comment by backspace** [comment]
Much simpler than I inexplicably feared 😆

In running locally, I had to use `FASTBOOT_DISABLED=true` because I was getting an error related to `fetch`, I’m not sure what that’s about! But with that, I was able to confirm that the links worked on the aforelinked branch.

**Comment by samselikoff** [comment]
That is weird... didn't think we ran FastBoot but for one of the test-projects. Strange.

Thx for the commit 👍
