### ISSUE TITLE
Faker breaks IE8, no way to disable?

### ISSUE THREAD

**Issue by zyllorion** [samselikoff/ember-cli-mirage#171]
Faker uses..
Object.keys which I have found a working polyfill for.
Object.defineProperty which I have not found a working polyfill for.

Can you make faker configurable so we can disable it and maintain IE8 compatibility?  Also I don't use it so it would be nice to not have the extra code :)

Thanks

**Comment by blimmer** [comment]
IE8 is not supported by Ember 2.0 moving forward. If you're interested in maintaining IE8 support for this project, please feel free to submit PRs!
