### ISSUE TITLE
IE8 fix for initialiser

### ISSUE THREAD

**Issue by zyllorion** [samselikoff/ember-cli-mirage#172]
I get a reserved word exception in IE8 for this code:

```
function _shouldUseMirage(env, addonConfig) {
  var userDeclaredEnabled = typeof addonConfig.enabled !== 'undefined';
  var defaultEnabled = _defaultEnabled(env, addonConfig);
  return userDeclaredEnabled ? addonConfig.enabled : defaultEnabled;
}
```
Could you change defaultEnabled to defEnabled
Thanks

**Comment by samselikoff** [comment]
Thanks for the report!

I can make the change, but you should know IE8 support is typically a low priority for me. If you'd like these sorts of changes to happen faster, you can always submit a PR. I'm happy to talk through any problems you encounter, and the help can really lighten the load!

**Comment by blimmer** [comment]
IE8 is unsupported by Ember 2.0 forward. However, if you'd like to fix this and submit a PR, please do!
