### ISSUE TITLE
How can I access server.create/createList OR use factories during development mode?

### ISSUE THREAD

**Issue by erichonkanen** [samselikoff/ember-cli-mirage#1725]
Our ember app is rendered onto a 3rd party site and in real world has some configuration passed via iframed local storage solution.

For local development we added a special mirage route we use to load one of 3 mirage scenario files based on a query param.

The problem is that I can't find a way to access `server` and thus `server.create/createList` in the mirage config, and on top of that if I use the `schema.create`, it doesn't use the mirage factories.

Is there a way to use the mirage factories or access server in this way?
```
  /**
   * rule mode selection (development environment only).
   * Loads environment-specific fixture data for local development.
  */
  this.get('/select-rule-mode', (schema, { queryParams }) => {
    const create = schema.create.bind(schema);
    const { preview, ruleType } = queryParams;
    const isPreview = !!preview;

    switch (ruleType) {
      case ruleTypes.AB:
        abScenario(create, isPreview);
        break;
      case ruleTypes.DYNAMIC:
        dynamicScenario(create, isPreview);
        break;
      case ruleTypes.TARGET:
      default:
        targetScenario(create, isPreview);
    }
    return;
  });
```

**Comment by samselikoff** [comment]
There is, `this` actually refers to the server instance so you can call `this.create` or `this.createList`. You can also use the `loadFixtures` API.

You might want to add a check to these to make it idempotent - in case the request comes through twice you wouldn't want to duplicate the data.

**Comment by erichonkanen** [comment]
ok great will try that thanks for the quick response!

**Comment by samselikoff** [comment]
Because using `this` in that way is not really conventional you might also want to reference `server` from outside the scope of the route handler, I think it's a bit more clear and probably what I'd do:
```js
// mirage/config.js
export default function() {
  let server = this;
  
  this.get("/select-rule-mode", (schema, { queryParams }) => {
    server.create()
    
  });
}
```

**Comment by erichonkanen** [comment]
ok using `let server = this; server.create('model')` works, but doesn't use factory?

factory:
```
import { Factory } from 'ember-cli-mirage';
import faker from 'faker';

export default Factory.extend({
  description: faker.lorem.paragraph,
  id: faker.lorem.word,
  isSelectedForPreview: false,
  name: faker.lorem.word,
});
```

![image](https://user-images.githubusercontent.com/230757/63480417-a6ff1300-c446-11e9-9072-ddadde5be1b4.png)

**Comment by samselikoff** [comment]
Ah I think I might know why... [factories aren't loaded](https://github.com/miragejs/server/blob/master/lib/server.js#L390) by the time the config is run.

Hm. Does it work if you just do `this.create` in the route handler?

**Comment by erichonkanen** [comment]
negative :)
![image](https://user-images.githubusercontent.com/230757/63480734-d5c9b900-c447-11e9-844f-062ae213f493.png)

**Comment by samselikoff** [comment]
Hm I just tried it out in my app and it does work... when the `server.create` call executes the factories have been loaded so I get my attributes.

Might need a reproduction to investigate further...

**Comment by erichonkanen** [comment]
ok darn, are you running in ember dev server? also what version? I tried latest but not sure if it matters. I'll have to look at loadFixtures

**Comment by samselikoff** [comment]
yep ember dev server, just `ember s`. Even though factories are loaded after `config`, by the time the function executes all that stuff should be loaded up.

Mirage 1.1.0

**Comment by erichonkanen** [comment]
interesting... it could be due to the way our app works, we don't use index.html at all & instead we have a static site that injects the ember app similarly to how customers use it. We load the script via express in /server/index.js. I wonder if that could affect timing

**Comment by erichonkanen** [comment]
found out that if I add a blank default scenario, then factories will work :D `export default function() {}`

**Comment by samselikoff** [comment]
ahhhh - that is most unfortunate. This is a really dumb holdover from our initialization logic, when we first moved from fixtures to factories. Factories only get loaded in development if a scenario is discovered 🤦‍♂️

Sorry you had to go through this! Hoping to fix this up with the miragejs/server extraction soon

**Comment by erichonkanen** [comment]
haha no prob! also stoked on miragejs/server as I recently started work on a react app and discovered there aren't any mock server solutions on par w/ember-mirage. Will be following the progress! cheers.

**Comment by samselikoff** [comment]
@erichonkanen awesome! Email list on miragejs.com is best way to hear when the docs are ready. And please feel free to reach out with any feedback if/when you start using it in React! Eager to hear how folks' experience goes.
