### ISSUE TITLE
bump miragejs/server

### ISSUE THREAD

**Issue by mehulkar** [samselikoff/ember-cli-mirage#1739]
Would like to get this https://github.com/miragejs/server/issues/75 fix in ember-cli-mirage. Looks like ember-cli-mirage hardcodes to 0.1.9, but the change is available in the latest 0.1.21. Not sure how much upgrade is safe, but would be great 👍

**Comment by samselikoff** [comment]
For sure - planning on getting to it real soon, ember-cli-mirage was broken for a while but it's fixed again so going to bump `@miragejs/server` again.

BTW – I _think_ you should be able to add `@miragjs/server` yourself, to override the version `ember-cli-mirage` uses? I'm not positive though.

**Comment by samselikoff** [comment]
I did bump it but it doesn't fix #1699 😞

We need to do a bit more work on our builds to get `ember-cli-mirage` to use our ESM build.

**Comment by samselikoff** [comment]
Fix incoming. We had a typo in our build ^_^

**Comment by samselikoff** [comment]
https://github.com/samselikoff/ember-cli-mirage/pull/1747 closes

**Comment by samselikoff** [comment]
This should be fixed in `1.1.1`.

Let me know if you have any more issues!
