### ISSUE TITLE
API for adding links to a response

### ISSUE THREAD

**Issue by cball** [samselikoff/ember-cli-mirage#176]
How can we handle / is it worth supporting a links hash defined in the route config for relationships? I'm leaning towards it not being necessary but thought I'd bring up for discussion.

**Comment by samselikoff** [comment]
Hm could you post a snippet of how you think this might look?

**Comment by samselikoff** [comment]
If you're thinking along the lines of json api, I think eventually this will be part of mirage (or a separate package).

**Comment by samselikoff** [comment]
Thought for future, we'd need to add a routing DSL similar to JSON:API Resources. Perhaps a short-term solution would be to let you define links urls somewhere in your serializers.

**Comment by samselikoff** [comment]
Filed under ""links" support for json:api responses" note in the Roadmap project.
