### ISSUE TITLE
Getting 500 error from Mirage ""Mirage: The route handler for /api/1.0/employees/ is trying to access the {modelName} model, but that model doesn't exist. Create it using 'ember g mirage-model {modelName}'.""

### ISSUE THREAD

**Issue by Rajkiran0147** [samselikoff/ember-cli-mirage#1788]
Ember CLI Mirage Boilerplate branch - https://github.com/Rajkiran0147/ember-cli-mirage-boilerplate/tree/mirage_server_issue

I was trying to prepare a simple tutorial app to demonstrate the greatness of ember cli mirage to people at work who are just stepping into Ember. Whilst I was doing that, I created a fixture file and did server.loadFixtures of the same in scenarios.js. I tried to return this fixture that I created from the route handler and I got a 500 error from mirage server "trying to access the model, but that model doesn't exist". Tried to go through the issues in the repo but couldn't find anything similar. This new tutorial app uses ember 3.13 and mirage 1.1.3.

I would like to know why I am being asked to create a model when I don't have any models in the application ? I have used`discoverEmberDataModels: false` previously to work around this issue but I don't even have models in this case.

**Comment by samselikoff** [comment]
You have a small typo. Your module exports

```js
export default { fetchAllEmployees, createEmployee }
```

but then in `mirage/config.js` you call

```js
import { fetchAllEmployees, createEmployee } from "./route-handlers/employees";
```

which are named imports, and are thus `undefined`, so Mirage is trying to use its shorthand. Remove the `default` from your export and you should be all set.

**Comment by Rajkiran0147** [comment]
@samselikoff Thank you. It worked.
