### ISSUE TITLE
ember-1.13.2 & ember-data-1.13.3 - Can't get fixture objects/files to load on the actual route 

### ISSUE THREAD

**Issue by e-karma** [samselikoff/ember-cli-mirage#179]
I've been taking my first swing at ecli-mirage and i'm down but not out.  I love whats possible with this, I just can't catch a break or find anything online... 

I am repeatedly running into walls when it comes to loading data/fixtures/ serializers/adapters/versions...  

I'm coding for the most part on a fresh app installs with no added variables; 
 
1. In every case EXCEPT loading objects into the config.js file, no data loads after I followed the steps from the code-mentor video a month ago.  

2. Almost every case, fixture objects located in mirage/fixtures/contact.js (or many like contact.js)  isn't showing up in ember-inspector or on-page

3. Short-hand 'succeeds' the get within the console, but the array=0 when theres multiple fixture object files filled out as in your video 

4. Received multiple deprecation warnings related to REST adapter deprecated in favor of JSON API => yet theres no documentation I can find to even share what text to swap? or if to do so?

5. The most success i've had thus far has just been copying full objects into the config.js file 

6. Tried a few posts and couldn't get it working even on the basic level, but that may be due to other reasons...

Is adding our own application adapter a requirement? If so, which should/can be added?

//application template
{{#each users as |user|}}
{{contact.name}}
{{/each}}

//application route
  model(){
    return this.store.findAll('user');
  }

\/\/ wouldn't show  \/\/
mirage/fixtures/contacts.js 
export default [
  {
    id:1,
    name: 'Zelda'
  },
  {
    id:2,
    name: 'Link'
  },
];

\/\/  mirage/config.js  \/\/  

appeared in the console array count {3}, but gave the response that would indicate a serialization / adapter issue 

this.get('/api/users', function() {
  return {
    users: [
      {id: 1, name: 'Zelda'},
      {id: 2, name: 'Link'},
      {id: 3, name: 'Epona'},
    ]
  }
});

Thanks for your contributions and help.  I can implement any suggested solutions on the spot as shipping code by tomorrow was of great interest.  

Cheers

**Comment by samselikoff** [comment]
Sounds super frustrating, so sorry you've had a rough time getting started. I'd love to help out.

Can you try `npm install samselikoff/ember-cli-mirage` and restart? I think there was a bug with fixtures that should be fixed, that might be all there is.

**Comment by e-karma** [comment]
ok, I ran that command (no deleting or cache clearing..) and both objects are making their way to the console {3} but not onto the page.  The only time the objects reach the console is when it's explicitly laid out in the config file.  

deprecation warnings is down to just the one "should Update All"
Also have a REST adapter w/ namespace:api

seems like adapter / serializer that's keeping the objects from loading into the each loop?

**Comment by samselikoff** [comment]
Your fixtures are named `contacts` but it looked like your Ember app may be request `users`. What's the name of the model?

You could either change the fixture file to `users.js`, or use a shorthand to specify the mirage data collection you want to return:

```js
this.get('/api/users', 'contacts');
```

**Comment by samselikoff** [comment]
Also, I just cut a release so you can update your package.json to `0.1.5` to get the latest code.

**Comment by e-karma** [comment]
I have a users.js and contacts.js file that has the same data basically...

Both have their own very basic model of name.  

I ran your suggestion and it gave an error about adding a 'contact' route.  After adding it, => {0} and nothign on the page.  I'll try a reset w/ the new version and let ya know.  Thanks for helpin out so fast

**Comment by samselikoff** [comment]
No prob. Also is

```
{{#each users as |user|}}
```

supposed to be

```
{{#each model as |user|}}
```

?

**Comment by samselikoff** [comment]
If the data is showing up in console, it could be your serializer. What is it set to? Does it expect a root key?

**Comment by e-karma** [comment]
you've found the true source of the frustration... documentation.   I have seen an equal amount of people / posts as well as emberjs.com saying {{#each users as |user|}} was correct, even though at some point I thought I read about it being model. Is the convention moving forward {{#each model as |user|}} ?

serializer = application/adapter.js
import DS from 'ember-data';

export default DS.RESTAdapter.extend({
  namespace: 'api'
});


Mirage is reading the route correctly.. i'm confident from doing it all the wrong ways before and after lol

**Comment by samselikoff** [comment]
Haha - such is the life of a programmer!

The syntax

```hbs
{{#each user in model}}
```

and

```hbs
{{#each model as |user|}}
```

are semantically equivalent. `model` in both versions refers to an array, and `user` the locally assigned iteration. Sometimes people will do something like this on their controllers

```js
Ember.controller.extend({
  users: Ember.computed.alias('model')
})
```

which will allow them to write either of the following:

```hbs
{{#each user in users}}
{{#each users as |user|}}
```

Going forward, the `{{each array as |item|}}` syntax (known as block params) will be preferred syntax going forward.

And remember, frustration is a sign that important learning is taking place. Best of luck! :)

**Comment by e-karma** [comment]
ok, just confirmed that's not the issue.  I was pretty sure the each block was one of the first things I varied.  Same result... 

It must be the serializer (or lack thereof?).  

Is one required for ember-cli-mirage?  Could that be what's preventing fixture files from loading as well as not showing the objects?

**Comment by samselikoff** [comment]
Do you have a serializer configured at all, or are you using the default? It should work with the default.

**Comment by samselikoff** [comment]
If not, could you post a gist that has your `mirage/config.js`, `mirage/fixtures/users.js`, and the route and template you're looking at?

**Comment by e-karma** [comment]
no just the REST adapter I shared...  One of the recent embers was giving fits about changing it tho.. REST -> JSON API

**Comment by e-karma** [comment]
yea, putting it together right now, wanted to try just removing the adapter to see if that helps.. and it did provide me w/ a copy of the deprecation warning about REST ..  

You are currently using the default DS.RESTAdapter adapter. For Ember 2.0 the default adapter will be DS.JSONAPIAdapter.

**Comment by samselikoff** [comment]
What version of ember data?

**Comment by e-karma** [comment]
1.13.3

**Comment by e-karma** [comment]
Here's the Gists..

https://gist.github.com/e-karma/4f164f36e4a66640812
https://gist.github.com/e-karma/30d3d91c487cbfea3893

I don't say this often, but I don't think the issue is on my end this time..  I removed the REST adapter and now a library from 'vendor' is bringing it back into the code-base (or does mirage use REST?) even after a full rm -rf cache wipe

Do you have an app/repo you could share where mirage is working or a combination of versions I should try?  I can get by w/ developing on an older version until a solution is figured out later in the week.

**Comment by samselikoff** [comment]
It should be working on Ember CLI 0.2.7, it's absolutely possible it's a bug. I just haven't gotten around to testing the newest versions yet.

Your first gist link is 404'ing, btw you can add multiple files to a single gist.

**Comment by samselikoff** [comment]
As for a sample app, you can check out the [dummy app](https://github.com/samselikoff/ember-cli-mirage/tree/master/tests/dummy/app) in the Mirage repo, in particular the contacts fixtures, the contacts route and contacts model.

I could also pair with you on this in a bit.

**Comment by e-karma** [comment]
this is all that's in the config file... I boiled everything down to the bare-minimum to eliminate variables interfering 
export default function() {

  // These comments are here to help you get started. Feel free to delete them.
  this.get('contacts', function() {
      return {
        users: [
          {id: 1, name: 'Zelda'},
        ]
      }
    });
}

reads {1} in the console

**Comment by e-karma** [comment]
ok, awesome to both.  i'll mess with it a bit on my end in the meantime and if you felt like pairing, i'd most certainly be down :)  Thanks again for helpin out!

**Comment by samselikoff** [comment]
Happy to pair if you're still having trouble: sam[at]ted.com

**Comment by e-karma** [comment]
Hey Sam,

Incase I sent the other email wrong, i'm absolutely down to pair.  I'll be
online the next few hours.

Thanks!

Best,

Ryan
