### ISSUE TITLE
Rename scenarios/default.js?

### ISSUE THREAD

**Issue by samselikoff** [samselikoff/ember-cli-mirage#180]
I think this might be confusing, maybe it should just be `/mirage/db/seeds.js` or something?

**Comment by seawatts** [comment]
I'm indifferent. The only reason I'd think it would be useful to keep it in the scenarios folder is if there was a possibility to have multiple different scenarios.

**Comment by blimmer** [comment]
I think that it's OK how it is and there hasn't been a lot of feedback on this issue. I'm going to close this, but please feel free to reopen/comment if you think that this should change.
