### ISSUE TITLE
Mirage conflicting with Image Paths

### ISSUE THREAD

**Issue by hhff** [samselikoff/ember-cli-mirage#181]
Hi Sam!

I'm loving this addon - it's made building out prototypes so so easy.  Such a breeze!

I'm running into a problem with Image Paths.  I'm using Mirage with `ember-material-design`, and when using the ``{{md-icon}}`` component and passing a local path to an image in my application's `/public` folder, I get an error like this:

```
Mirage: Your Ember app tried to GET 'images/icons/cross.svg', but there was no route defined to handle this request. Define a route that matches this path in your mirage/config.js file
```

Is there a way to bypass Mirage for certain requests?

Thankyou a milli!

**Comment by samselikoff** [comment]
Yes try adding

```js
this.get('/*passthrough', this.pretender.passthrough);
this.get('/*passthrough', this.pretender.passthrough);
this.get('/*passthrough', this.pretender.passthrough);

**Comment by hhff** [comment]
Ok - I've tried 

```
this.get('/*images', this.pretender.passthrough);
this.get('/images/*', this.pretender.passthrough);
this.get('/*images/*', this.pretender.passthrough);
```

None of the above seem to work.  Am I missing something?

**Comment by hhff** [comment]
Neither does explicitly stating the item:
```
this.get('images/icons/menu.svg', this.pretender.passthrough);
```

**Comment by samselikoff** [comment]
Woops try

```
this.pretender.get('/*images', this.pretender.passthrough');
```

**Comment by hhff** [comment]
*boom*

**Comment by JowelTisso** [comment]
> Neither does explicitly stating the item:
> 
> ```
> this.get('images/icons/menu.svg', this.pretender.passthrough);
> ```

Thanks man this worked.
