### ISSUE TITLE
Fat arrows shouldn't be used in class bodies

### ISSUE THREAD

**Issue by ebryn** [samselikoff/ember-cli-mirage#182]
Your docs use fat arrows inside of `extend`, this is not a good practice.

**Comment by samselikoff** [comment]
you mean like this

```js
// app/mirage/factories/user.js
import Mirage, {faker} from 'ember-cli-mirage';

export default Mirage.Factory.extend({
  name: i => `Person ${i}`
});
```

? If so why? Btw that extend is not `Ember.Object.extend`

**Comment by samselikoff** [comment]
is it because the `this` context will be `window`?

**Comment by ebryn** [comment]
Yes, it's because you'll likely want to have a usable `this`. You should use concise object literal syntax:

```
export default Mirage.Factory.extend({
  name(i) { return `Person ${i}` }
});
```

I know it's not an Ember.Object, but most users will not.

**Comment by samselikoff** [comment]
2ae8443c1bf568247d84c648c7d5b1e3619311f0 closes
