### ISSUE TITLE
Extract initializer

### ISSUE THREAD

**Issue by samselikoff** [samselikoff/ember-cli-mirage#183]
Right now Mirage's server boots up in an application initializer. We should extract this logic so users can start their server e.g. in a unit or integration test.

**Comment by tomoguisuru** [comment]
This would help out a lot :+1:

**Comment by chrisgame** [comment]
This would be great for components that access the store!

**Comment by chrisgame** [comment]
Just been speaking to @rwjblue and he suggested the following work around if you need this now...

Create the helper below
```
// tests/helpers/setup-mirage-for-integration.js

import mirageInitializer from '../../initializers/ember-cli-mirage';

export default function setupMirage(container) {
  mirageInitializer.initialize(container);
};
```

Then add the following to your test
```
// tests/integration/components/your-test.js

import mirage from '../../../helpers/setup-mirage-for-integration';

moduleForComponent('your-component', 'Integration | Component | your component', {
  integration: true,
  setup: function() {
    mirage(this.containter);
  }
});
```

**Comment by samselikoff** [comment]
Documented here: http://www.ember-cli-mirage.com/docs/v0.1.x/manually-starting-mirage/

I think this is fine for now
