### ISSUE TITLE
PATCH request errors with DS.JSONAPIAdapter and DS.JSONAPISerializer

### ISSUE THREAD

**Issue by biscuitvile** [samselikoff/ember-cli-mirage#187]
I'm switching to the new `DS.JSONAPIAdapter`and `DS.JSONAPISerializer` available in Ember Data 1.13.4 and running into an issue with Ember CLI Mirage.

I get the somewhat usual: `Mirage: Your Ember app tried to PATCH '/orders/FTWG-49137', but there was no route defined to handle this request. Define a route that matches this path in your mirage/config.js file.` error that one sees from time to time in development but in this particular case it is complaining about a PATCH request and I already have this route defined in my `config.js` file.

I previously handled this with code like this:

```
this.put('/orders/:id', function(db, request) {
  // ...
});
```

After switching to the new adapter and serializer Mirage does not recognize this route due to the PATCH request and obviously `this.patch('/orders/:id');` is not a valid thing.

I don't have a lot of context on the internals at the moment, is this some deficiency in Pretender or Ember CLI Mirage or am I just making a mistake somewhere?

This library has been amazing for our Ember app but at the moment this is a hard blocking issue on our number one priority of adopting JSON API endpoints. Is there something I can do to help with this or am I just missing something obvious?

Thanks!!

**Comment by biscuitvile** [comment]
@samselikoff I can hack this to work by doing this: https://gist.github.com/biscuitvile/9c9ebf1c93caf2bd17c2#file-server-js-L74

However, I'm unsure if a) that's remotely appropriate, or b) what kind of test changes you'd expect to see accompany a change like this.

I'd love to help if you can give me some pointers and feedback on what changes you'd like to see and how they should be tested to make this work.

Thanks again :)

**Comment by samselikoff** [comment]
Hey - thanks for the issue. Supporting JSON API is a priority but, is going to involve some work. The solution is going to be to use serializers, which depend on the orm I've almost completed. 

For now, I don't think I have a good answer for you. I know some people have written essentially their own serializers which they use in their mirage route handlers to return JSON API-formatted data, @lukemelia for one. You may have to do something similar since you all are now on latest ED.

**Comment by samselikoff** [comment]
As an aside JSON API is still new and you may run into a similar issue with other libs that you use. In your current app is it essential to switch to JSONAPI this early? You may have an easier time if you wait a month or two.

**Comment by biscuitvile** [comment]
@samselikoff Thanks for the info! This makes a lot of sense and also now I can visualize how serializers would make a lot of the extensive manipulation I'm doing in the `config.js` redundant and just baked in.

As for my project's needs, it is not publicly released yet but the longer we wait to adopt JSON API the longer we'll have different sets of devs kind of working against each other. A bit hard to explain but we're basically making double work for ourselves every day we're not using JSON API.

Thanks for your very prompt reply I really appreciate it.

**Comment by lukeclewlow** [comment]
Hi Guys, I don't want to open an issue as it's really more a request for advice, but I'm quite new to this and would really like to use mirage to mock out my API. I am using a JSON-API adapter and serializer too. At what layer do I implement the serialization? It works perfectly well if I just return a JSON object in the config routing, but if I try to pass the same object through via db and fixtures it doesn't recognise it.

Apologies if this is the wrong place for this, happy to move it elsewhere if so!

Thanks!!

**Comment by samselikoff** [comment]
@lukeclewlow there is no built in way to handle JSON API yet and there's no mirage serializer yet. Unfortunately if you want to support you'll have to do the data munging yourself using [mirage function handlers](http://www.ember-cli-mirage.com/docs/v0.1.x/routes/#function-handler).

**Comment by biscuitvile** [comment]
Hmm so I'm a little confused here because it certainly seems you can write successful JSON API responses ussing the mirage function handlers suggested above but the lack of PATCH as a possible HTTP method seems to not work with the DS.JSONAPIAdapter.

Am I missing something still?

**Comment by samselikoff** [comment]
You are correct, I need to add `this.patch`. I can do that tonight.

**Comment by samselikoff** [comment]
@biscuitvile you can use master to get this now. Sorry about the delay here, I didn't understand your original point - you should be able to fully (if manually) mock out your JSON API server now.

**Comment by biscuitvile** [comment]
Thanks!! I really appreciate your responsiveness. I'm excited for the serializers to come with full JSON API support but for some of us who just need to plow forward now, adding `this.patch` is a tremendous help.

I'll leave you to close this issue whenever you see fit, in case it ties into some kind of release schedule.

**Comment by sarus** [comment]
I'm currently using jsonapi-serializer (https://github.com/SeyZ/jsonapi-serializer) on the server side to convert my json payload into a json-api compatible payload.  Working to see if I can get it working on the client-side.  Would be a super easy way to convert the json data currently returned from mirage db into a json-api compatible payload.

**Comment by samselikoff** [comment]
that's great news! I actually opened and issue over there because I had the
same thought, and once I have the serializer layer done we can have first
class support for this in mirage.

Keep me up to date on your efforts!

**Comment by webPapaya** [comment]
Is this fix already publisched on npm? I ran into the same issue and wanted to update the package.

**Comment by MarcoPrins** [comment]
When is this fix going up? Been waiting days now and it's slowing down development

**Comment by samselikoff** [comment]
woops sorry guys, 0.1.6 is out :)
