### ISSUE TITLE
Unable to create passthrough without additional option

### ISSUE THREAD

**Issue by jrjohnson** [samselikoff/ember-cli-mirage#189]
I'm having some trouble with creating a passthrough route.  The initial issue seems to be that
```this.post('pass', this.pretender.passthrough);```

Doesn't end up sending the passthrough to pretender due to:
https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/server.js#L18

Since the hander here is the last object and this.pretender.passthrough is just an empty object:
https://github.com/trek/pretender/blob/master/pretender.js#L157

The quick solution seems to be setting this route as ```this.post('pass', this.pretender.passthrough, {});```

I think the fix here is probably to count parameters before stripping anything out, but I don't know all the ways that https://github.com/samselikoff/ember-cli-mirage/pull/123 might apply so might need to be a documentation fix.

**Comment by samselikoff** [comment]
Ugh sorry about this. #188 is going to help this a lot, we were stalled for a while by another project but we should have that soon.

In the meantime can you try

```js
this.pretender.post.call(this.pretender, '/*passthrough', this.pretender.passthrough);
```

and tell me if that works?

**Comment by jrjohnson** [comment]
Nice.  That works great.  I did it as 
```
this.pretender.post.call(this.pretender, '/my-route', this.pretender.passthrough);
```
So it wasn't a catchall.

I took a look at #188 before I submitted this and it doesn't seem to handle this issue with the server.extractStubArguments() method for single passthrough requests.

There appears to be another issue that mirage replaces the handler declared in the route with its own on https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/server.js#L61.  Which appears to foil pretender checking to see if something is a passthrough route.  I think you may need to check if a passthrough is set before declaring the handler.

Once 188 is in I will take a look unless someone else gets there before me.

**Comment by samselikoff** [comment]
Yah we'll definitely land a nicer api for declaring one-off passthroughs. Thx for opening this

**Comment by samselikoff** [comment]
I think route-recognizer needs `*something` for catchall. Check out the [docs on the new passthrough feature](http://www.ember-cli-mirage.com/docs/v0.1.x/server-configuration/#passthrough) and let me know if you still need help here.

Thanks!
