### ISSUE TITLE
Cross origin requests

### ISSUE THREAD

**Issue by samselikoff** [samselikoff/ember-cli-mirage#19]
Pretender doesn't support cross origin requests (see [#39](https://github.com/trek/pretender/issues/39)). We either need to come up with a solution and submit upstream to Pretender, or use something like jquery-mockjax.

**Comment by Eptis** [comment]
Is this still being considered? For me this is the only reason not to use Mirage because I consume multiple API's on different domains.

**Comment by samselikoff** [comment]
looks like it's getting added to pretender! https://github.com/trek/pretender/pull/66

**Comment by theazureshadow** [comment]
And it has landed in [Pretender 0.8.0](https://github.com/trek/pretender/releases/tag/0.8.0)

**Comment by acorncom** [comment]
@samselikoff Any pointers on where you'd like to get started on this?  I've got a client who needs it, so may be able to help push this in the right direction tomorrow ...

**Comment by theazureshadow** [comment]
@acorncom: You might be able to get it to work without any changes in ember-cli-mirage. In `app/mirage/config.js`, try setting `this.namespace` to your API endpoint hostname and path. For us that looks something like:

```
this.namespace = config.api.host + '/' + config.api.namespace;
```

**Comment by acorncom** [comment]
@theazureshadow Sadly, that doesn't work.  What I'm trying to do is build a prototype backed by Ember-CLI-Mirage that uses Algolia for searching.  I either need a way to mock responses from Algolia for non-acceptance tests (I can do it for acceptance tests) or a way to poke a hole clean through Mirage so I can actually talk to Algolia.  Things work smoothly if I turn off Mirage altogether, but then the rest of my prototype doesn't work (no data ;-)

I'm getting this error:

```
Pretender will not respond to requests for URLs. It is not possible to accurately simluate the browser's CSP. Remove the http://<app-id>-dsn.algolia.net from http://<app-id>-dsn.algolia.net/1/indexes/*/queries
```

**Comment by samselikoff** [comment]
are you sure you updated Pretender? That error message doesn't exist in 0.9.

To poke a hole in Mirage add

```
this.pretender.get('/*passthrough', this.pretender.passthrough);
```

to the bottom of your `mirage/config.js`.

**Comment by acorncom** [comment]
@samselikoff Yes, sadly, I've tried that exact line of code for poking a hole in Mirage.  Actually, more accurately, I've tried the following:

```
this.pretender.get('/1/index*', this.pretender.passthrough);
```

within the `app/mirage/config` function that is exported.  And I've tried it with pretender 0.6.0, 0.7.0 and 0.9.0.  With 0.9.0 the error I'm getting is:

```
Mirage: Your Ember app tried to POST 'http://<app-id>-dsn.algolia.net/1/indexes/*/queries', but there was no route defined to handle this request. Define a route that matches this path in your mirage/config.js file.
```

but it's still approximately the same.  I've dug in deep a few times and seem to be getting snagged on the host registry combined with an absolute URL (which Algolia's search client requires).

I've been quietly beating my head against a wall, hoping that the upgrade to pretender would magically fix everything ;-)  When it didn't, I thought I'd better ask a few more questions ...

**Comment by vvo** [comment]
@acorncom as for mocking xhrs at Algolia we built https://github.com/algolia/faux-jax maybe have a look

**Comment by samselikoff** [comment]
Sorry, sounds v frustrating @acorncom. I should have time to take a look at this soon.

**Comment by samselikoff** [comment]
Ah looks like you're POST'ing, try this

```
this.pretender.get('/1/index*', this.pretender.passthrough);
this.pretender.post('/1/index*', this.pretender.passthrough);
this.pretender.put('/1/index*', this.pretender.passthrough);
this.pretender.delete('/1/index*', this.pretender.passthrough);
```

or like I said use `/*passthrough` for the route and put that at the bottom of your `config.js` to have all non-handled requests pass through.

**Comment by samselikoff** [comment]
Looks like you need to be on jQuery 2.x as well

**Comment by acorncom** [comment]
@samselikoff Appreciate your help on it.  We've been using jQuery 1.x, so that may be the issue.  I'll be in touch once I've had a chance to test.

Re: frustrating.  Time-consuming at the least ;-)  I definitely know far more about the internals of Mirage and Pretender than I did before, let's put it that way ;-)

**Comment by acorncom** [comment]
@samselikoff Looks like upgrading to jQuery 2.x isn't helping on my end.  Am I wasting too much of your time here?  Should I open a new issue?  I'd be happy to post a reproduction repo if you are inclined to help, but don't want to presume ...  Thanks!

**Comment by blimmer** [comment]
@acorncom are you sure that you're depending on pretender 0.9? It looks like we [forgot to update](https://github.com/samselikoff/ember-cli-mirage/pull/240) this package's blueprint to install pretender 0.9.

**Comment by blimmer** [comment]
I'm pretty sure this is possible. I created a [sample repo](https://github.com/blimmer/ember-cli-example-app-for-github/compare/cross-origin-mirage) with this working. @acorncom if you can post an app where this is reproducible, that would be great.

**Comment by acorncom** [comment]
@blimmer Appreicate your sample repo.  I'll open a separate issue, as this may be a misconfiguration on my part (don't think so though ...)

**Comment by samselikoff** [comment]
Passthrough api has landed, if anyone here still needs help please comment.

http://www.ember-cli-mirage.com/docs/v0.1.x/manually-starting-mirage/

Thanks!
