### ISSUE TITLE
Re-start mirage?

### ISSUE THREAD

**Issue by lessless** [samselikoff/ember-cli-mirage#192]
Hello,
as a temporary workaround for https://github.com/trek/pretender/issues/82 I decided to shutdown and than re-start pretender, so that request can reach an S3 instance. 
I know how sick is that, but it's an only possible way that I can think of.  
Though there is no problem with shutdown, but what is the easiest (most convenient way) to start mirage after shutdown?

**Comment by samselikoff** [comment]
Unfortunately there's no API for this right now, all the startup logic is [here](https://github.com/samselikoff/ember-cli-mirage/blob/master/app/initializers/ember-cli-mirage.js).

I think the proper fix is to allow passthrough of this, or proper host support (which is coming to pretender soon).

For now, you could fork pretender and comment out [this line](https://github.com/trek/pretender/blob/master/pretender.js#L186).

**Comment by lessless** [comment]
done.
though that required a hack with path altering, due to https://github.com/trek/pretender/issues/83#issuecomment-119835009
hope that issue will get a proper care anytime soon.

**Comment by blimmer** [comment]
@lessless it looks like this should be fixed by the new version of pretender. please upgrade pretender to 0.9+ in your `bower.json`.
