### ISSUE TITLE
Wrong value returned by Delete.undefined shorthand

### ISSUE THREAD

**Issue by andrei1089** [samselikoff/ember-cli-mirage#196]
Using ```undefined``` as the name of the function and returning ```undefined``` (https://github.com/samselikoff/ember-cli-mirage/blob/cc765963794863716f6e5c413d23e796e31de933/addon/shorthands/delete.js#L80) may result in unexpected behavior. I was not able to reproduce this issue using the unit tests from ember-cli-mirage but in one of the projects where I'm using mirage the value returned by this function is not the expected JS constant ```undefined``` but the function itself. 
I fixed it by returning window.undefined, but using language reserved keywords as variable/function names is a bad practice so I think this should be refactored.

**Comment by samselikoff** [comment]
I agree, will update this

**Comment by samselikoff** [comment]
This issue was resolved, sometime during the route handler refactoring.
