### ISSUE TITLE
Improve missing route error message

### ISSUE THREAD

**Issue by samselikoff** [samselikoff/ember-cli-mirage#197]
Common case, someone forgets to put a namespace (e.g. in a links hash). If mirage doesn't match the request, offer this as a hint ("Did you forget to add your namespace?")

**Comment by blimmer** [comment]
Code is [here](https://github.com/samselikoff/ember-cli-mirage/blob/eb3682eb8e9e93c0e8b71788589640d0fc32eccf/addon/server.js#L36).
