### ISSUE TITLE
Shorthand doesn't work

### ISSUE THREAD

**Issue by halogenandtoast** [samselikoff/ember-cli-mirage#198]
In my `config.js` if I have:

```javascript
this.post("/users")
```

I get `SyntaxError: Pretender intercepted POST /api/users but encountered an error: Unexpected token u`

If I instead write out what it expands to:

```javascript
this.post("/users", function(db, request) {     
  const attrs = JSON.parse(request.requestBody);
  const record = db.users.insert(attrs);
  return {
    user: record
  };
});
```

It works fine. Any ideas?

Info:

ember-cli-mirage: 0.1.5
JSONAPIAdapter

**Comment by samselikoff** [comment]
it's not tested with json api right now :/ I think I recall seeing this having to do with JSON.parse, if you're feeling up to it you could put a debugger around [here] and step through, seeing what happens? I'd be happy to talk you through anything.

**Comment by halogenandtoast** [comment]
Yeah it looks like this line is the culprit:

https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/shorthands/post.js#L19

Since the json will look like

`{ data: { type: "user", attributes: { ... } } }`

You could conditionally respond depending on the adapter but since that can be per model I'm not sure which way is best to get this information.

**Comment by samselikoff** [comment]
really needs the serializer layer (wip...)

**Comment by halogenandtoast** [comment]
If that is something that could use assistance, let me know, it would give me a good reason to contribute.

**Comment by erichonkanen** [comment]
+1 shorthand didnt work for me using latest version and ember 1.13.8 / data 1.13.9

**Comment by samselikoff** [comment]
Yah, haven't had time lately to work on this, fix is coming soonish tho

http://www.ember-cli-mirage.com/docs/v0.1.x/working-with-json-api/

**Comment by samselikoff** [comment]
The [serializer layer](http://www.ember-cli-mirage.com/docs/v0.2.x/serializers/) that will be in 0.2.0 addresses this. You can try it out now by installing the beta.

If you have more questions, please lmk!
