### ISSUE TITLE
New name?

### ISSUE THREAD

**Issue by samselikoff** [samselikoff/ember-cli-mirage#20]
This is no longer really about Pretender, it's
 - an XHR interceptor (currently Pretender, possibly mockjax in the future if we can't solve #19)
 - a clientside datastore
 - soon, a clientside factory system

It's really a fake clientside server. Any good name ideas?

I want to extract the main part into a separate non-Ember lib, and keep this lib the ember addon that ties it all together. That way it could be used elsewhere, e.g. in a React app.

**Comment by lukemelia** [comment]
api-front, frontman, fronting, affront, frontster, frontrunner, frontage

api-faker, fakester, fake-server

magic-cloak, api-cloak, api-shroud, 

simulation, api-simulation, api-sim

sham-api, api-sham, api-beard, api-disguise

**Comment by samselikoff** [comment]
I like api-sim, I feel like that communicates a lot about the project.

api-sim, api-simulator, api-mock, clientside-api, client-api, browser-api, clientside-server, frontend-server, frontend-api, mock-api

If I was thinking of a tagline for a hypothetical site for this project, 

"Whip up a fake API that runs in the browser for you to prototype and test your new interface against"
"A concise API server that runs in the browser for your next JavaScript application"
"Use ____ to quickly prototype and test your next JS app"
"Get started prototyping and testing your next JS app with API responses from _____"
"Handle API requests directly from the browser with a simple but powerful server definition"

**Comment by devinrhode2** [comment]
xhr-server

**Comment by lukemelia** [comment]
nice double entendre too: `api-sim(ulator|ple)`

Riffing off your taglines: "api-sim lets you quickly and expressively define a fake API that runs completely in the browser to make testing and prototyping a delight. Start with fixtures so your GETs have data right away and automatically add or update an in-memory store via POST/PUT/DELETEs."

**Comment by samselikoff** [comment]
I'd like to make this name change soon. I'm leaning towards Mirage.js.

```js
var server = new Mirage();
```

It's a cool name and it also somewhat communicates that you've just set up a fake server that's going to act as your data layer.

Other ideas:

Illusion.js
Charade.js
Veil.js
Veneer.js
Pretense.js
Imposter.js
Guise.js
Figment.js

Thoughts?

**Comment by lukemelia** [comment]
I think those are all great names. Have you vetted against existing usage?
If you can find one that is clear on npm and github, I'd choose that one
(though it may be a long shot)

**Comment by samselikoff** [comment]
looks like there's a mirage package on npm but it has to do with some realtime framework thing: https://www.npmjs.com/package/mirage

Here's a 3-year old github repo: https://github.com/krawaller/mirage

Seem ok? I wouldn't imagine there'd be much confusion

**Comment by lukemelia** [comment]
:+1:

**Comment by samselikoff** [comment]
ohh i see, there's already an npm package so i couldn't ever have `npm install mirage`. I'd have to do something like `npm install miragejs`

**Comment by devinrhode2** [comment]
Maybe "BS" for 'Bull Server' - serves up some bs json

or "FedServe" which is a shortening of "FEDeral reSERVE", which is a FAKE
institution!


-Devin <http://zerply.com/DevinRhode2>
<http://zerply.com/devinrhode2>
