### ISSUE TITLE
Upgrade to Faker 3.0

### ISSUE THREAD

**Issue by blimmer** [samselikoff/ember-cli-mirage#201]
I ran into this [error](https://github.com/Marak/faker.js/issues/241) when using `faker.internet.email`, and their solution was to upgrade to faker 3. I upgraded locally in my `bower.json` and don't see any direct problems from the upgrade. Is it safe to upgrade this dependency?

**Comment by samselikoff** [comment]
should be, I haven't looked at it - are you saying is it safe to PR it? If you PR the tests should run so we could find out :)

**Comment by blimmer** [comment]
Just one small change in the API, but looking good. PR is open and ready to merge.
