### ISSUE TITLE
not all faker methods are exposed

### ISSUE THREAD

**Issue by blimmer** [samselikoff/ember-cli-mirage#203]
e.g. `faker.commerce` from the [API Docs](https://github.com/Marak/faker.js#api-methods)

Seems like we should be able to just add our custom `.list` to the main faker object and export everything else.

**Comment by samselikoff** [comment]
that sounds right, not sure if there was a particular reason certain methods were chosen

/cc @mupkoo

**Comment by blimmer** [comment]
#204 should resolve it and be more forward-compatible should they add more faker options.
