### ISSUE TITLE
Shorthand does not work for camel cased endpoints

### ISSUE THREAD

**Issue by jackmatt2** [samselikoff/ember-cli-mirage#205]
Using the latest ember-cli-mirage as of yesterday.

The following works fine in config.js:

```javascript
this.get('/accounts');
```` 

Any camel cased request do not work.

```javascript
this.get('/bookingStatuses');
```` 

I had to explicitly use the override and a dasherized key.
```javascript
this.get('/bookingStatuses', function(db, request) {
  return {
    bookingStatuses: db['booking-statuses'] //the key is dasherized in the db object but the enpoint is not
  }; 
});
``` 

This has resulted in bloating out my config.js as all the get, post, delete and put endpoints need to be overridden.

**Comment by samselikoff** [comment]
Yah I know this is a pain, sorry. I've been working on serializers, which
will have an answer to this.

For now, try this.get('/bookingStatuses', 'booking-statuses');

**Comment by jackmatt2** [comment]
ah, that is easier.  Thanks.

**Comment by blimmer** [comment]
This should be fixed in a more sustainable way when the serializer work is done. For now, I'm going to close this issue since there's a workaround.
