### ISSUE TITLE
Calling functions inside nested objects

### ISSUE THREAD

**Issue by lessless** [samselikoff/ember-cli-mirage#206]
Hello,

current Factory implementation execute functions  only if the defined on the top-level of the object https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/factory.js#L6

so, something like this won't ever work 

```javascript 


export default Mirage.Factory.extend({
  first_name: faker.name.firstName,
  last_name: faker.name.lastName,
  company: faker.company.companyName,
  birthday: '11-30-1980',
  photo: '/img/avatar.png',
  emails: [
    {
      id: i => `${ parseInt(Math.random() * 100) }`,
      address: faker.internet.email(),
      type: 'personal'
    }
  ],
  addresses: [
    {
      id: i => `${ parseInt(Math.random() * 100) }`,
      street_address: faker.address.streetAddress(),
      buzzer: faker.address.secondaryAddress(),
      city: faker.address.city(),
      state: faker.address.stateAbbr(),
      zip: faker.address.zipCode(),
      country: faker.address.country(),
      type: 'home'
    }
  ],
  phones: []
});

```

**Comment by samselikoff** [comment]
For now you should define a separate factory:

```js
// factories/user.js
export default Mirage.Factory.extend({
  first_name: faker.name.firstName,
  last_name: faker.name.lastName,
  company: faker.company.companyName,
  birthday: '11-30-1980',
  photo: '/img/avatar.png'
});

// factories/email.js
export default Mirage.Factory.extend({
  id: i => `${ parseInt(Math.random() * 100) }`,
  address: faker.internet.email(),
  type: 'personal'
});
```

then in your tests or default scenario, do something like

```js
var user = server.create('user');
server.createList('email', 2, {user_id: user.id});
```

to create the related data.

The Models branch is my top priority, and we need the orm layer in order to add relationships directly to the factory. For now, this is how you have to create related data.

Does that help?

**Comment by pzuraq** [comment]
@samselikoff We also need to be able to call functions on nested data, as our JSON structure includes embedded objects, some of which are not full Ember models but just transitory JS objects.

**Comment by samselikoff** [comment]
That's fine, you need to call functions in browserland right? After the JSON is deserizlied? Your factory attributes can be whatever you want, they don't just have to be strings/numbers/bools.

**Comment by pzuraq** [comment]
@samselikoff Sorry I was unclear, I mean we need to be able to populate nested data structures with faker data, something along the lines of:

```javascript
export default Mirage.Factory.extend({
  name: faker.name.firstName,
  address: {
    city: faker.address.city
  }
});
```

**Comment by samselikoff** [comment]
I think you want

```js
export default Mirage.Factory.extend({
  name: faker.name.firstName,
  address() {
    return {
      city: faker.address.city()
    };
  }
});
```

**Comment by pzuraq** [comment]
ah, brilliant, thanks!
