### ISSUE TITLE
Using ${i} on numeric model fields

### ISSUE THREAD

**Issue by jackmatt2** [samselikoff/ember-cli-mirage#208]
I tried using the following on a DS.attr('number') model field in the factory.

age(i) { return ${i};},
-----^

However, the test server will not start at complains at the character marked.  Is it possible to use ${i} on numeric fields?

**Comment by samselikoff** [comment]
`${i}` is for use within a template string, so I think you want 

```js
age(i) { return `${i}`; }
```

or more simply (since you don't have any other text)

```js
age(i) { return i; }
```

**Comment by jackmatt2** [comment]
ah, ok thanks.
