### ISSUE TITLE
Test cases for a new model (not saved to the DB)

### ISSUE THREAD

**Issue by jackmatt2** [samselikoff/ember-cli-mirage#211]
I have some test cases that depend on the model being new (not yet saved to the database).

Is there a way to do this in `ember-cli-mirage` and pass it to the visit test helper somehow.

```javascript
let booking = server.createNew('booking'); //It would be good if this would return an empty booking object.
visit('my/route', booking); //not exactly sure how to pass a model using the visit helper
```

Maybe it makes no sense using ember-cli-mirage in this context and I should import the model directly into the test.

**Comment by jackmatt2** [comment]
closing, this is not really an issue with ember-cli-mirage.

**Comment by ballPointPenguin** [comment]
I think this provides the feature you are describing:
https://github.com/samselikoff/ember-cli-mirage/pull/459
