### ISSUE TITLE
Cannot use use models with irregular (non-pluralized) names

### ISSUE THREAD

**Issue by tomoguisuru** [samselikoff/ember-cli-mirage#212]
When setting up a factory for a model that has a non-pluralized name I get an error, `Cannot read property 'insert' of undefined` since mirage cannot find the collection in the db[collection] in the final line of the this.create function:
`
this.create = function (type, overrides) {
      var collection = inflector.pluralize(type);
      var currentRecords = this.db[collection];
      var sequence = currentRecords ? currentRecords.length : 0;
      if (!this._factoryMap || !this._factoryMap[type]) {
        throw 'You\'re trying to create a ' + type + ', but no factory for this type was found';
      }
      var OriginalFactory = this._factoryMap[type];
      var Factory = OriginalFactory.extend(overrides);
      var factory = new Factory();

      var attrs = factory.build(sequence);
      return this.db[collection].insert(attrs);
    };
`

The factory name in this case is 'campus' and should also resolve to 'campus' and not 'campuses'. 

Is there anyway to override this at the moment?

**Comment by samselikoff** [comment]
So you have the file `/factories/campus.js` and you're calling `server.create('campus')`?

**Comment by tomoguisuru** [comment]
Right, the factory is under /factory/campus.js but it is an irregular store, so
`Ember.Inflector.inflector.irregular('campus', 'campuses');`

**Comment by samselikoff** [comment]
Ah I see...nope not right now unfortunately, you could dive in or I can look into this in a bit...I'm trying to focus my efforts on the orm stuff right now to get that out the door

**Comment by tomoguisuru** [comment]
The issue seems to be resolved with 0.1.6

**Comment by samselikoff** [comment]
¯\_(ツ)_/¯ not sure what changed..if it comes up again feel free to reopen! thanks for following up on this :)
