### ISSUE TITLE
Blob protocol support 

### ISSUE THREAD

**Issue by igorrKurr** [samselikoff/ember-cli-mirage#213]
Hi!

I'm using localforage in my app, and it is sending such request to check blob support - `GET 'blob:http%3A//localhost%3A4200/8d788512-7a99-4e34-8bef-84fa1a2dd4a8`

And sure I get mirage intercepted it and giving me error that I need to define such route.

So, I tried to passthrough this request, adding to my config file that line:
```javascript
this.pretender.get('/:passthrough', this.pretender.passthrough);
```
but it didn't react on `blob:` protocol I saw.

So is it any support for such requests in `mirage`? Or this is more pretender issue and we are waiting for it?

**Comment by samselikoff** [comment]
Hmm....try

```
this.pretender.get('/*passthrough', this.pretender.passthrough);
```

To fully answer your question, yes we're waiting on [this pr](https://github.com/trek/pretender/pull/66) to fully deal with this issue.

**Comment by igorrKurr** [comment]
@samselikoff yes, this works for me, many thanks! :+1:

**Comment by Lyfeway** [comment]
hi, @igorrKurr, I added `this.pretender.get('/*passthrough', this.pretender.passthrough);` to config.js, but get the error all the same, I use `"ember-cli-mirage": "0.2.1"`, thanks.

**Comment by igorrKurr** [comment]
hi, @Lyfeway,
I worked on that quite long time ago, so I don't remember details, but I'm sure it was working like that for me. Only difference could be is that I used mirage `0.1.6` or near that version. So maybe something changed in newer release.
So I can just advice to play with mirage versions and/or your localforage versions(or whatever you use instead).
