### ISSUE TITLE
Per adapter requests

### ISSUE THREAD

**Issue by ultimatemonty** [samselikoff/ember-cli-mirage#214]
Is is possible to have mirage only respond to requests from specific adapters? We have an API that is partially implemented and our application adapter is configured to use a local vagrant instance for the working bits of the API.

I have a separate adapter for a set of endpoints that is not yet implemented that I need to mock. I'm currently seeing the `Pretender will not respond to requests for URLs.` issue. The endpoints that work are hosted on a local vagrant instance. The application adapter is configured to use that instance for requests. A separate adapter is being used for the yet-to-be implemented portions of the API that we'd like to mock.

Is this currently possible? I'm running into the `Pretender will not respond to requests for URLs.` at the moment.

**Comment by samselikoff** [comment]
What's the URL for the request being made? Pretender does capture requests with a hostname present, this won't be an issue once [this PR](https://github.com/trek/pretender/pull/66) is resolved

**Comment by ultimatemonty** [comment]
Full url is `pi.localhost.com:8081/reports/workflow/id/2`
`pi.localhost.com` is the vagrant instance

Looking forward to seeing that PR merged!

**Comment by blimmer** [comment]
The PR mentioned above has been merged to pretender.

**Comment by samselikoff** [comment]
The [passthrough api](http://www.ember-cli-mirage.com/docs/v0.1.x/server-configuration/#passthrough) landed in 0.1.9, please upgrade and let us know if you need more help.

Thanks!
