### ISSUE TITLE
Any reason why Ember CLI Mirage wouldn't work with Mocha?

### ISSUE THREAD

**Issue by jamesdixon** [samselikoff/ember-cli-mirage#215]
Hi, I'm using `ember-cli-mocha` and writing my tests in Mocha + Chai. I was using Sinon successfully to intercept my XHR calls, but stumbled upon `ember-cli-mirage` and decided to give it a shot. My Sinon setup was working using `sinon.fakeServer`, but am not having any success with `ember-cli-mirage` at the moment.

For reference, here is my previous Sinon setup and an example test:

```javascript
// tests/authentication-test.js
beforeEach(function() {

    // start the ember application
    application = startApp();

    // invalidate session if it exists
    invalidateSession();

    // stub the login endpoint for all authentication calls
    server = sinon.fakeServer.create();
    server.respondImmediately = true;
    
    server.respondWith('POST', config.APP.API_URL + '/auth/login', [
      200, 
      {'Content-Type': 'application/json'},
      '{"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiIxfHVuZGVmaW5lZCIsInN1YiI6ImkgZG9udCBrbm93IHdoYXQgdGhpcyBzaG91bGQgYmUiLCJhdWQiOiJ3YWxrbWF0ZSIsImV4cCI6MTQzODIwMzYyNDA3MCwibmJmIjoxNDM3NTk4ODI0MDcxLCJpYXQiOjE0Mzc1OTg4MjQwNzEsImp0aSI6ImFiZTMzOTcwLTMwYjQtMTFlNS1iNDk5LTgzYmE2Y2Y2NDE3MyJ9.ysWwzAqI8V9yKdMbXjQtNRXRM8LpMdBoZpJX4Mck0nw","token_type":"bearer","expires_in":7200}'
    ]);
  });

it('can login to application', function() {

    visit('/');
    fillIn('input[type="email"]', 'test@test.com');
    fillIn('input[type="password"]', '123124fdsdf3!!23');
    click('button[type="submit"]');

    andThen(function() {
      expect(currentRouteName()).to.equal('app.index');
    });
  });
```

Here's the equivalent for Mirage:

```javascript
// app/mirage/config.js
this.post(config.APP.API_URL + '/auth/login', function() {
    return {
      token: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiIxfHVuZGVmaW5lZCIsInN1YiI6ImkgZG9udCBrbm93IHdoYXQgdGhpcyBzaG91bGQgYmUiLCJhdWQiOiJ3YWxrbWF0ZSIsImV4cCI6MTQzODIwMzYyNDA3MCwibmJmIjoxNDM3NTk4ODI0MDcxLCJpYXQiOjE0Mzc1OTg4MjQwNzEsImp0aSI6ImFiZTMzOTcwLTMwYjQtMTFlNS1iNDk5LTgzYmE2Y2Y2NDE3MyJ9.ysWwzAqI8V9yKdMbXjQtNRXRM8LpMdBoZpJX4Mck0nw',
      token_type: 'bearer',
      expires_in: 7200
    };
  });
```

*Note that I have validated that `config.APP.API_URL` is resolving to the correct URL*

The specific piece of code being tested (note that I'm using `ember-simple-auth` with JWT for authentication):

```javascript
// app/controllers/auth.js
actions: {
            login: function() {
                var flashMessages = Ember.get(this, 'flashMessages');
                var _this = this;

                // clear all previous flash messages
                flashMessages.clearMessages();

                this.validate().then(function() {
                    _this.get('session').authenticate('simple-auth-authenticator:jwt', {
                        'identification': _this.get('email'),
                        'password': _this.get('password')
                    }).then(null, function(msg) {
                        flashMessages.warning(msg.error);
                    });
                }).catch(function() {
                    // display any errors returned by the client-side validator
                    var errors = _this.get('errors');
                    for (var e in errors) {
                        if (errors.hasOwnProperty(e) && errors[e].length > 0) {
                            flashMessages.warning(errors[e]);
                        }
                    }
                });

            }
        }
```

And finally, the error that I'm receiving when removing `sinon` and attempting to use `ember-cli-mirage`:

```
TypeError: Cannot read property 'error' of undefined
    at http://localhost:7357/assets/business-c7b15f144aaa251638f7515ed314b7dd.js:718:50
    at tryCatch (http://localhost:7357/assets/vendor-fef92444fcee2380784bf5f81617ce31.js:65632:14)
    at invokeCallback (http://localhost:7357/assets/vendor-fef92444fcee2380784bf5f81617ce31.js:65647:15)
    at publish (http://localhost:7357/assets/vendor-fef92444fcee2380784bf5f81617ce31.js:65615:9)
    at publishRejection (http://localhost:7357/assets/vendor-fef92444fcee2380784bf5f81617ce31.js:65549:5)
    at http://localhost:7357/assets/vendor-fef92444fcee2380784bf5f81617ce31.js:42476:7
    at Queue.invoke (http://localhost:7357/assets/vendor-fef92444fcee2380784bf5f81617ce31.js:11455:16)
    at Object.Queue.flush (http://localhost:7357/assets/vendor-fef92444fcee2380784bf5f81617ce31.js:11519:11)
    at Object.DeferredActionQueues.flush (http://localhost:7357/assets/vendor-fef92444fcee2380784bf5f81617ce31.js:11319:17)
    at Object.Backburner.end (http://localhost:7357/assets/vendor-fef92444fcee2380784bf5f81617ce31.js:10712:25)
```
Note that `error` is referencing the `flashMessages.warning(msg.error)` in the `auth` controller.

All that said, if there is no issue with Mocha and Mirage, is there something else I need to do enable my tests to communicate with Mirage? Is there a way to test the server?

Thanks in advance!

Cheers,
James

**Comment by samselikoff** [comment]
Thanks for taking the time to open the issue! I'm sure this was all frustrating.

I don't see any fundamental reason why mirage shouldn't work with Mocha - it just uses Pretender, which hijacks `window.XMLHttpRequest`.

To debug, first I would put a `debugger` statement in your mirage config, like this:

```js
// app/mirage/config.js
this.post(config.APP.API_URL + '/auth/login', function() {
    debugger; // here
    return {
      token: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiIxfHVuZGVmaW5lZCIsInN1YiI6ImkgZG9udCBrbm93IHdoYXQgdGhpcyBzaG91bGQgYmUiLCJhdWQiOiJ3YWxrbWF0ZSIsImV4cCI6MTQzODIwMzYyNDA3MCwibmJmIjoxNDM3NTk4ODI0MDcxLCJpYXQiOjE0Mzc1OTg4MjQwNzEsImp0aSI6ImFiZTMzOTcwLTMwYjQtMTFlNS1iNDk5LTgzYmE2Y2Y2NDE3MyJ9.ysWwzAqI8V9yKdMbXjQtNRXRM8LpMdBoZpJX4Mck0nw',
      token_type: 'bearer',
      expires_in: 7200
    };
  });
```

and see if that gets called. If so, you know the mirage server is hooked up, and is intercepting your Ember app's request.

**Comment by jamesdixon** [comment]
Thanks for responding! Appreciate it.

Unfortunately, no luck on reaching the `debugger` statement. I did try it outside of the actual method and it does reach the configuration file, but I can't seem to get it to trigger the route. 

This may be a dumb question, but I see that Pretender doesn't support cross-origin requests. Is this an issue for me since I'm appending a different prefix to my path? My API server lives separately, but didn't think it mattered since the whole point is to hijack the request.

**Comment by jamesdixon** [comment]
@samselikoff I just created a new Ember project and installed `ember-cli-mocha` as well as `ember-cli-mirage` and tried to run a simple test that posts to `/test` with a corresponding entry in `mirage/config.js`; it worked! 

However, if i change the post url and corresponding Mirage entry to `http://test.com/test`, things stop working. It appears the cross-origin request is causing the issue. That said, how can Mirage be used in the case that your API server sits somewhere else? I'm assuming that's the case for a lot of Ember apps. 

Thanks!

**Comment by samselikoff** [comment]
Yes we're blocked by [this issue](https://github.com/trek/pretender/pull/66) on pretender, unfortunately

**Comment by samselikoff** [comment]
You could use that fork in your bower.json file for now and see if it works?

**Comment by jamesdixon** [comment]
@samselikoff I'll give it a try and let you know. Just curious, how do you run your setup given the current limitations - do you have a single server serving both Ember app and API?

Cheers,
James

**Comment by samselikoff** [comment]
Hm not sure I understand the question, you mean given the limitations of not being able to mock out other-origin domains?

**Comment by jamesdixon** [comment]
Sorry if that wasn't clear. What I meant was that I'm assuming most (possibly a poor assumption) people developing with Ember are connecting to some sort of API on a different server. In my case, this is true, and I have one local server running Ember and the other running my API. That said, my question is whether you typically run a similar setup and if so, how do you use Mirage in this scenario or do you typically end up running everything on the same server because of the other-origin domain limitation?

Thanks, Sam!

**Comment by samselikoff** [comment]
Actually for me, my api server is also serving up my ember frontend, so I haven't run into this issue.

What I imagine you could do is, have you adapter layer (say if you're using Ember data) set the hostname per environment. So in test or dev environment, leave the hostname blank. Then if you wanted to connect to your real api server, you could use ember cli's http proxies. Also, when you deployed to production, your adapter layer would set the appropriate domain. 

Does that help?

**Comment by jamesdixon** [comment]
Great idea. I'll give it a shot. Thanks, Sam!
