### ISSUE TITLE
[Feature request] allow searching with a callback

### ISSUE THREAD

**Issue by Truffula** [samselikoff/ember-cli-mirage#217]
I have some many-many relationships which, when stored in a nested form, can't be easily searched. Theoretically I could create a joining table, but it would be nice to be able to use:

```js
db.widgets.where((widget) => widget.foos.contains('bar'));
```
or
```js
db.widgets.where({
    foos: (foos) => foos.contains('bar'),
    bar: (bar) => /someTest/.test(bar),
    // etc
});
```

**Comment by samselikoff** [comment]
a72fd487776a048791db52ed114137842bf074c2 closes
