### ISSUE TITLE
Passthrough Defaults

### ISSUE THREAD

**Issue by dgavey** [samselikoff/ember-cli-mirage#219]
I looked at issue #131 and #80 and I see that some commits have been made to enable passthrough defaults.  I was wondering when/if those will be merged?  

Also was wondering if there is anyway to enable this now without defining every single route I need to pass through?  I tried the suggestion in #131 but wasn't sure if I should be putting something else in for :fallback or if that was a keyword of some sort.

Thanks for the great addon!

**Comment by dgavey** [comment]
Actually, I was able to enable a default passthrough by doing something like this:

this.pretender.get('/*catchall', this.pretender.passthrough);

However there still seems to be another problem, where only the first url resolves and the Ember promises are stuck on 'resolving'

**Comment by samselikoff** [comment]
Yes `this.pretender.get('/*catchall', this.pretender.passthrough)` should work for now.

I haven't heard of the pending thing..are you putting the `catchall` route at the bottom of your `config.js` file (so your other route definitions match first)?

**Comment by dgavey** [comment]
I don't have any others defined right now.  So even if I don't do a 'catchall' if I put my first two calls  each in a passthrough specifically, the first api call that gets hit, gets the data from my local server. But it never reaches the second api call.  It almost looks like for some reason the first ajax promise is not fully being resolved according to my Ember inspector. Even though I see in the network tab it is being returned.

I'm still trying to determine why that might be.  We don't use Ember-data but an old (abandoned, much hacked) Ember model.  I'm still digging, but any suggestions you have would be appreciated.

**Comment by dgavey** [comment]
And I have the answer! Apparently using passthroughs with pretender requires using Jquery 2 and up.  Found in this [issue](https://github.com/trek/pretender/issues/85) on pretender's github issues.

**Comment by samselikoff** [comment]
bizarre! Great investigative work :mag:
