### ISSUE TITLE
Replace ember-inflector(bower) with ember-inflector(npm)

### ISSUE THREAD

**Issue by bianjp** [samselikoff/ember-cli-mirage#221]
Bower package [ember-inflector](https://github.com/fivetanley/ember-inflector-bower) is out of date and seems discontinued.
It causes warnings about deprecation of Ember.Handlebars.helper" (at least for ember 1.13) and will not work after ember 2.0.
In fact, ember-data has bundled npm package [ember-inflector](https://github.com/stefanpenner/ember-inflector), and it's available in browser as `Ember.Inflector.inflector`.
Please use the npm version instead.

**Comment by bianjp** [comment]
Ember 2.0 has been out and this addon breaks.

**Comment by Eptis** [comment]
@bianjp can you check if my PR works for you?

**Comment by bianjp** [comment]
@Eptis 
Yes, it works. :thumbsup:

**Comment by samselikoff** [comment]
looking into this - sorry guys!

**Comment by samselikoff** [comment]
@Eptis there was a similar issue [here](https://github.com/samselikoff/ember-cli-mirage/pull/234) but, bringing in the npm package `ember-inflector` would make code under `/addon` depend on Ember, which it currently doesn't. As my goal is to extract the core of Mirage out into it's own ember-free lib, would it be possible to use https://github.com/stefanpenner/ember-inflector as a bower package instead?

**Comment by Eptis** [comment]
Mmm I don't have enough experience with addons/bower/npm to say if this is possible. Only thing I know is that the ember-inflector package is deprecated and stuck on 1.3. Development has continued on Npm and is now 1.9

**Comment by samselikoff** [comment]
Using the npm package for now, hopefully we can get it as a bower/client package and not depend on Ember's build process eventually.

Thanks yall!

**Comment by sarus** [comment]
Hello, would is be appropriate to keep this issue open?  I spent some unnecessary time trying to figure out why ember-inflector-bower was being installed because I saw this issue was closed and assumed it had been resolved in the latest version of ember-cli-mirage.  I'm also getting the helper deprecations warnings while trying to get my project ready for Ember 2.0. 

Thank you!

**Comment by samselikoff** [comment]
sorry about that @sarus ! This is actually fixed in master, we just need to cut a release, which we're planning on soon

**Comment by sarus** [comment]
No problem at all!  I know things are still in flux as the Ember community continues to transition to 2.0 so it's very understandable that it'll take a little while for things to settle down and stabilize.  Thank you for your hard work on such a useful add on.
