### ISSUE TITLE
Use fixtures and factories during development and testing

### ISSUE THREAD

**Issue by pzuraq** [samselikoff/ember-cli-mirage#222]
We have some models whose data is highly static and almost never changes, and currently it makes much more sense for us to treat that data as fixtures in our data store. On the other hand, some of our models are highly flexible and would be better served as factories.

Would it be possible to allow both to be specified? Perhaps if a factory for a given model doesn't exist, it defaults to looking up fixtures?

**Comment by chrisgame** [comment]
This would be really useful on the project i'm working on at the moment. 
Pretty much the same use case. A lot of the data that is fetched from the api is just reference data that wouldn't change in different scenarios and is much easier to have as a fixture. But there is a lot of data that is specific to the users current journey that i would want to use scenarios and factories for.

**Comment by samselikoff** [comment]
I wonder if you could just `import` some fixture data in your scenario, and just use `server.db.insert`. We could make a nice api for this.

**Comment by chrisgame** [comment]
Yep, that would work. The fixture data I'm most concerned about is all the internationalised strings we load based on the locale. If I could just make one call in a scenario to load the existing collection I have in the fixture that would be great!

**Comment by samselikoff** [comment]
@chrisgame can you do that now? like literally just

```js
import data from '../fixtures/my-data.js';

export default function(server) {
  server.db.things.insert(data);  

  // server.create('blah')
}
```

**Comment by chrisgame** [comment]
@samselikoff it works if i create an empty factory first. Great work around for now, thanks!

**Comment by samselikoff** [comment]
great :) I'm surprised, you shouldn't have to create a factory if you directly insert into db? Unless you also want to use `server.create` for that same model.

**Comment by chrisgame** [comment]
given the example above if i just call `server.db.things.insert(data)` things doesn't exist in the db object at that point, so i just get an error about calling insert on null.

**Comment by samselikoff** [comment]
ah gotcha, right the empty factory ensures the db table exists. You could also `db.createCollection(things)`, but either way is the same.

http://www.ember-cli-mirage.com/docs/v0.1.x/database/#createCollection

**Comment by chrisgame** [comment]
Ahhh, thats much nicer! 
I admit it, i skipped that section of the docs :disappointed:

**Comment by blimmer** [comment]
@chrisgame closing this for now, seems like everything got worked out. Please reopen if not.
