### ISSUE TITLE
JSONAPI factory serialization utility

### ISSUE THREAD

**Issue by maxcal** [samselikoff/ember-cli-mirage#223]
Thanks @samselikoff for your help on stackoverflow. 
While solving my own problem I came up with a lightweight helper which makes creating JSONAPI responses a lot simpler:

```JS
import Ember from 'ember';
export default Ember.Object.extend({
  serialize(object) {
    let attributes = Ember.copy(object, true);
    delete attributes.id;
    delete attributes.type;
    return {
      id: object.id,
      type: object.type,
      attributes: attributes
    };
  },
  serializeCollection(collection){
    return {
      data: collection.map(u => { return this.serialize(u); })
    };
  }
});
```

It basically takes a straight factory object:
```JS
{
  type: "users",
  id: 1,
  name: "Joe"
}
```
And converts the object into a JSONAPI compatible response:

```JS
{
  type: "users",
  id: 1,
  attributes: { 
     name: "Joe"
  }
}
```
Is this something that fits into Mirage?

**Comment by maxcal** [comment]
Basic usage example:

```JS
import jsonapi from './jsonapi-helper';

this.get('/users', function(db){
  return jsonapi.serializeCollection(db.users);
});
```

**Comment by samselikoff** [comment]
Nice, great work on this!

I'm actually working on a serializer layer right now for Mirage, so JSON:API and other backends will be super easy to support. I think what you have is great but I want to make sure it's robust to handle updates, includes etc. in the future if we decide to support that.

Let's keep this open so others can find it, until that layer lands.

**Comment by kagemusha** [comment]
@samselikoff have you looked at things like https://github.com/SeyZ/jsonapi-serializer.  Haven't tried it, but looks like may be useful.

**Comment by samselikoff** [comment]
@kagemusha yep I have, actually I was going to use that but, the serialization is so tied up with the association lookup it may be easier to write our own for now. I haven't run into issues, just haven't had time yet :)

**Comment by oliverbarnes** [comment]
what about [ember-jsonapi-resources](https://github.com/pixelhandler/ember-jsonapi-resources) own [serializer](https://github.com/pixelhandler/ember-jsonapi-resources/blob/master/addon/serializers/application.js)

**Comment by derekdowling** [comment]
Thanks for the work around @maxcal! I'm running into this issue as well after upgrading to Ember-Data 2.0. This is popping up on SO now [too](http://stackoverflow.com/questions/32241632/error-returning-promise-from-ember-data/32381734#32381734).

**Comment by maxcal** [comment]
Here is an updated version which handles arrays and single objects through the same interfaces:

```JS
import Ember from 'ember';

let Helper = Ember.Object.extend({
  serialize(obj_or_ary) {
    let _serialize = function(object){
      let attributes = Ember.copy(object, true);
      delete attributes.id;
      delete attributes.type;
      return {
        id: object.id,
        type: object.type,
        attributes: attributes
      };
    }
    if ($.isArray(obj_or_ary)) {
      return { data: obj_or_ary.map(_serialize); }
    } else {
      return { data: _serialize(obj_or_ary); }
    }
  },
  deserialize(serialized){
    let data = serialized.data;
    let compact = function(obj){
      let o = Ember.copy(obj, true);
      let attributes = o.attributes;
      delete o.attributes;
      return $.extend(o, attributes);
    };
    if ($.isArray(data)) {
      return data.map(compact);
    } else {
      return compact(data);
    }
  }
});

export default Helper.create();
```

**Comment by derekdowling** [comment]
Cool, I'll give this updated version a shot! Thanks @maxcal

**Comment by derekdowling** [comment]
Since it's a bit trickier (not by much), here is an example of doing a PATCH request through Mirage, which in Ember Data 2.0, happens whenever `Ember.Model.save()` is called:

```js
  this.patch('/secrets/:id', function(db, request) {
    var id = request.params.id;
    var secret = JSON.parse(request.requestBody);
    return jsonapi.serialize(
      db.secrets.update(
        id,
        jsonapi.deserialize(secret)
      )
    );
  });
```

**Comment by jsmestad** [comment]
@derekdowling @maxcal how did you guys get this working with associations? I'm struggling to get it working in that situation :(

**Comment by mupkoo** [comment]
I know that you are working on this, but here is what I do to handle JSONAPI requests and fabrications.
https://gist.github.com/mupkoo/5203dd5e06662e43867b

**Comment by christophermlne** [comment]
@jsmestad re: associations, i've been playing around with that for a couple of days. I've reached the conclusion that it would be smarter to user Pretender directly and just return canned responses from the Pretender instance than to try to use Mirage before the new JSON api support is ready. Once Mirage is ready, I will rewrite my tests to take advantage of it.

**Comment by jsmestad** [comment]
I wonder if ember-cli-mirage is still working on native JSONAPI support. It's been months.

**Comment by samselikoff** [comment]
There is JSON:API support in beta, but you should know beta is currently unstable. Many are using it.

Check out the WIP [0.2.x](http://www.ember-cli-mirage.com/docs/v0.2.x/) guides, in particular the [serializers](http://www.ember-cli-mirage.com/docs/v0.2.x/serializers/) guide.

**Comment by samselikoff** [comment]
Closing since this is in 0.2.0, which is currently in beta. Please lmk if you have more questions!
