### ISSUE TITLE
window.server leaks, should be removed on shutdown

### ISSUE THREAD

**Issue by stefanpenner** [samselikoff/ember-cli-mirage#225]
https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/server.js#L56-L59

**Comment by blimmer** [comment]
Is this resolved by [this commit](https://github.com/samselikoff/ember-cli-mirage/commit/c8338534ea5d5905bcf4c9f78903fd3a32665b74)?

**Comment by stefanpenner** [comment]
yup should be.
