### ISSUE TITLE
docs aren't clear server needs to be shutdown

### ISSUE THREAD

**Issue by stefanpenner** [samselikoff/ember-cli-mirage#226]
Either the docs need to be adjusted, or a mechanism of automatic shutdown (after `run(app, 'destroy')`) is needed

cc @cibernox

**Comment by cibernox** [comment]
I'll add some context to this. 

Chasing some memory leaks, we saw that pretender instances were leaking all over the place, once per test. 

There is ([was](https://github.com/trek/pretender/pull/89), actually) a memory leak in pretender itself, but also seems that unless you explicitly shutdown the server, that also keeps some references, but once @trek cuts a new release we'll see if this is really necessary. I'd say that after the fix in pretender the the only leaked variable will be the global `server`, and if that's the case I wouldn't care, it's only one.

**Comment by blimmer** [comment]
@stefanpenner do you have any ideas how to fix this? Is there a way to hook into the app destroy event to clean up the server?

**Comment by blimmer** [comment]
Also, for those running into this, you need to call `window.server.shutdown();` after you `run(app, 'destroy')` for the time being.

**Comment by stefanpenner** [comment]
> app destroy event to clean up the server?

i think you want to hook into the test runner after hooks

**Comment by blimmer** [comment]
I wonder if there's a way to do that in a generic way that would work for people using Qunit, Mocha, etc.

**Comment by blimmer** [comment]
I just wrote a PR to ember-cli that would make this a very simple fix. We'll see how it goes.
