### ISSUE TITLE
Can't access relationships on Ember Data models

### ISSUE THREAD

**Issue by jerel** [samselikoff/ember-cli-mirage#230]
I have a simple scenario like this:

``` js
// user.js
DS.Model.extend({
  project: DS.belongsTo('project', {async: true}),
});
```

``` js
// acceptance test
test('visiting /some/url', async (assert) => {
  const project = server.create('project'),
        user = server.create('user', {project_id: project.id});

  await visit('/some/url');
});
```

``` js
/// and the route
Ember.Route.extend({
  model() {
    return this.store.find('user', 1).then(user => {
      // project is always empty. Created projects exist in the mirage db but the
      // user record doesn't have the relationship. user._data.project_id does exist
      console.log(user.get('project'));
    });
  },
});
```

Is this supposed to work and I'm doing something wrong or are relationships not possible yet? Does the user factory need to know that `project` is a relationship? I'm on Ember 1.12 and using the default ED serializers and etc.

**Comment by samselikoff** [comment]
Depends on how your routes (`/mirage/config.js`) are configured, does it return related resources? If you want async, it may not include it until/unless your template requests (e.g. `user.project`).

If you want `GET /users/1` to return the user and their project, you'd do something like this

```js
this.get('/users/:id', function(request, db) {
  let user = db.users.find(request.params.id);
  return {
    user: user,
    projects: db.projects.where({ id: user.project_id })
  };
});
```

depending on your adapter.

**Comment by jerel** [comment]
Thanks so much Sam. Sorry for opening an issue for what ended up being user error :/ You helped me out though by confirming that it should be working.

For anyone else that may run into this: the main thing I had wrong was using `server.create('user', { project_id: project.id })` when it should have been `server.create('user', { project: project.id })` for a belongsTo. Ember Data wasn't actually getting the project's id so it naturally wasn't hooking up the relationship. It doesn't appear to matter if the factory includes the property to start with or not, whatever you pass will get added to the mock instance.

**Comment by samselikoff** [comment]
Yep that's correct, think of Factory's as more of a "minimal generic set of attrs" rather than a full-blown model definition.

No need to apologize at all, Issues are a great place to get help!
