### ISSUE TITLE
Respect models primaryKey serializer configuration

### ISSUE THREAD

**Issue by medokin** [samselikoff/ember-cli-mirage#232]
Mirage assumes that the models PK ist always 'id'. Finding data fails if your primary key is different.

https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/db-collection.js#L29

**Comment by samselikoff** [comment]
Would something like this work?

```js
this.get('/posts/:slug', function(db, request) {
  return {
    contact: db.posts.findBy('slug', request.params.slug);
  };
});
```

I can't inspect ember data's primary key field because this is a server mock, it knows nothing about your Ember client.

**Comment by medokin** [comment]
Yes it does. Thanks.

**Comment by pinx** [comment]
In the new version of Mirage, that would be
`db.posts.where({'slug': request.params.slug})`

**Comment by medokin** [comment]
:thumbsup:
