### ISSUE TITLE
Uncaught TypeError: Cannot read property 'enabled' of undefined

### ISSUE THREAD

**Issue by mikkergimenez** [samselikoff/ember-cli-mirage#233]
This seems to be happening when loading the environment.js into mirage, specifically this addonConfig.enabled line below:

function _shouldUseMirage(env, addonConfig) {
    var userDeclaredEnabled = typeof addonConfig.enabled !== 'undefined';
    var defaultEnabled = _defaultEnabled(env, addonConfig);

    return userDeclaredEnabled ? addonConfig.enabled : defaultEnabled;
  }

addonConfig is the variable: ENV['default']['ember-cli-mirage']
when called.

I did some tracing around and no matter how I edit the environment.js I can't seem to get this to load which makes me think I missed some change I have to make to environment.js.  Any suggestions?

**Comment by blimmer** [comment]
Can you provide a reproducible example of this problem? Feel free to fork and use [this repo](https://github.com/blimmer/ember-cli-example-app-for-github).

**Comment by jmar910** [comment]
We are running into this exact issue after adding ember-cli-mirage. I cannot get my app to boot because it is hitting this error. No matter what I do to my environment file, it does not pick up the changes. I even tried removing items from the environment file and it doesn't pick up those changes either.

```
      if (_shouldUseMirage(environment, ENV['default']['ember-cli-mirage'])) {
        var modules = readModules['default'](ENV['default'].modulePrefix);
        var options = _.assign(modules, { environment: environment, baseConfig: config['default'], testConfig: config.testConfig });

        new Server['default'](options);
      }
```

I am breaking here and inspecting the contents of `ENV['default']`. For some reason it seems to be holding onto a frozen copy of the environment.js. Any changes to environment.js are not being reflected when I inspect.

**Comment by jmar910** [comment]
Somehow, it started working. Most likely an error on my part? Not sure.

**Comment by jmar910** [comment]
Still an issue. This may be some kind of issue with ember-cli? It finally picked up my changes to the environment.js. I'm not sure what caused it to pick up the changes but again it's stuck and newer changes aren't getting picked up. At a loss here why this is happening :/

**Comment by samselikoff** [comment]
are you on the latest release?

**Comment by jmar910** [comment]
Yes. Realized this was an error on my part, specific to our setup. All fixed and good to go. Sorry about that.

**Comment by samselikoff** [comment]
no problem.

@mikkergimenez please let us know if you still need help here, happy to reopen.

**Comment by cristiangrama** [comment]
@jmar910 Can you let me know what specific setup error was on your part? I have the same issue and cannot get by it no matter what.

**Comment by notmessenger** [comment]
I'm experiencing the same issue as well

**Comment by cristiangrama** [comment]
@notmessenger I was able to get rid of the issue by reloading my vagrant box. I was using symlinks to two clones of the same repo and when switching between the two I started to get all kinds of weird errors (one of them being this one). 

In my case the error was completely unrelated to ember. I still don't understand why this is happening sometimes but every single time I fix it by reloading my vagrant box (that is if you use one).

**Comment by notmessenger** [comment]
So the scenario I have ran into this is that I have `ember-cli-mirage` installed as a `dependency` in an addon that I then consume (referring to the addon) in an app.  When running `ember serve` I get

```
Cannot read property 'env' of undefined
TypeError: Cannot read property 'env' of undefined
    at Class.module.exports._shouldIncludeFiles (/appFolder/node_modules/ember-cli-mirage/index.js:68:33)
    at Class.module.exports.treeFor (/appFolder/node_modules/ember-cli-mirage/index.js:50:15)
    at /appFolder/node_modules/ember-cli/lib/models/addon.js:244:32
    at Array.map (native)
    at Class.eachAddonInvoke (/appFolder/node_modules/ember-cli/lib/models/addon.js:242:22)
    at Class.treeFor (/appFolder/node_modules/ember-cli/lib/models/addon.js:289:20)
    at /appFolder/node_modules/ember-cli/lib/broccoli/ember-app.js:463:20
    at Array.map (native)
    at EmberApp.addonTreesFor (/appFolder/node_modules/ember-cli/lib/broccoli/ember-app.js:461:30)
    at EmberApp._processedTemplatesTree (/appFolder/node_modules/ember-cli/lib/broccoli/ember-app.js:780:25)
```

Moving it to be a `devDependency` solves this issue but doesn't address my use case, so am installing `ember-cli-mirage` in my consuming app as a dependency.

Maybe this will help someone :-)

**Comment by sdhull** [comment]
FWIW I was having trouble getting it working with www.ember-twiddle.com but was able to get it working by following [this gist I found](https://gist.github.com/williamhaley/425262903604fd5192a37d807c59b777)
