### ISSUE TITLE
Timing is ignored

### ISSUE THREAD

**Issue by mydea** [samselikoff/ember-cli-mirage#235]
In my config.js I have:

    export default function () {
        this.namespace = '/api';
        this.timing = 500;
        // ...
    }

However, there seems to be nearly no delay when making requests. I tried to test this with:

    console.time("load listings");
    this.get("store").findAll("listing").then((listings) => {
        console.timeEnd("load listings");
    });

And I always get times between 50 and 150 ms back. 

I'm on:

- ember-cli-mirage@0.1.6
- pretender@0.9.0
- ember@1.13.7
- ember-data@1.13.8

**Comment by samselikoff** [comment]
is the `this.timing` declaration above your route definition? I just tried this on a brand new app and I couldn't reproduce.

**Comment by mydea** [comment]
Yes, my full config.js is:

```
export default function () {
    this.timing = 500;
    this.namespace = '/api';

    this.pretender.get('/assets/:id', this.pretender.passthrough);
    this.pretender.get('/assets/i18n/:id', this.pretender.passthrough);
    this.pretender.get('https://www.telize.com/geoip', this.pretender.passthrough);

    // routes to mock here
}
```

Otherwise, its a pretty standard setup. I use factories and a default scenario to seed data.

**Comment by samselikoff** [comment]
do you have any routes mocked? the timing only applies to routes mocked with Mirage, e.g.

```js
this.get('/contacts', ...
```

**Comment by mydea** [comment]
Yes, sorry, that was a bit unclear from my side, I have a couple of routes specified where I wrote ```// routes to mock here``` and they all work fine so far, only that they process more or less instantly instead of after the set timing.

**Comment by samselikoff** [comment]
hm. Any chance you could reproduce in an empty repo that I could look at?

**Comment by alisdair** [comment]
Not sure if this is the same issue, but yesterday I tried to use mirage's timing settings slow down my tests when I was giving a talk. Looks like `timing` is disabled/ignored during tests, even if set in the config.

@mydea are you trying to set timing in development mode, or when testing?

**Comment by mydea** [comment]
In dev-mode, directly in the config.js. I tried to isolate it, but honestly I have no idea where this is coming from. Trying it with a fresh install of ember + ember-cli-mirage and it works. However, I don't see what of my configuration could affect this behaviour.

My bower.json:

    "ember": "1.13.8",
    "ember-cli-shims": "ember-cli/ember-cli-shims#0.0.3",
    "ember-cli-test-loader": "ember-cli-test-loader#0.1.3",
    "ember-data": "2.0.0-beta.1",
    "ember-load-initializers": "ember-cli/ember-load-initializers#0.1.5",
    "ember-qunit": "0.4.9",
    "ember-qunit-notifications": "0.0.7",
    "ember-resolver": "~0.1.18",
    "jquery": "^2.1.4",
    "loader.js": "ember-cli/loader.js#3.2.1",
    "qunit": "~1.18.0",
    "pretender": "~0.9.0",
    "ember-inflector": "~1.3.1",
    "lodash": "~3.7.0",
    "Faker": "~3.0.0",
    "ember-simple-auth": "0.8.0",
    "moment": ">= 2.10.6",
    "moment-timezone": ">= 0.4.0"

**Comment by samselikoff** [comment]
@alisdair didn't think of this use case, i think we should change this so it's possible

@mydea i wonder if it's pretender 0.9? could you try 0.7 or something?

**Comment by blimmer** [comment]
@alisdair I opened #242 to track your feature request.

@mydea this issue will just be used to track down the issue you're describing. please provide us with a reproducible example of your issue. Feel free to use [this repo](https://github.com/blimmer/ember-cli-example-app-for-github) to provide an example.

**Comment by mydea** [comment]
I really can't seem to track this down. I tried to reproduce it but I can't. It's not that big of a deal, so I guess you can close this. If I somehow manage to track it down, I will reopen it.
