### ISSUE TITLE
Respect timing specifications in test

### ISSUE THREAD

**Issue by blimmer** [samselikoff/ember-cli-mirage#242]
Currently, timing is ignored in the test environment.

cc @alisdair

**Comment by samselikoff** [comment]
Would be nice to have a default of 0 (instead of 50 like in dev) but allow users to specify per-test or per-route-in-test, in case they want to test slow responses.

**Comment by workmanw** [comment]
:+1: My biggest concern here is not necessarily the fact it's 0ms vs 50ms, but that when it is 0, pretender does not delay the response to even the next loop. It responds immediately which would never happen in production. See this stack:

![image](https://cloud.githubusercontent.com/assets/825487/15324878/4c4cb2d6-1c16-11e6-83d0-799aeb1137d4.png)

I would love to submit a PR to change this, I'm just curious what you envision as the right solution @samselikoff .  One option would be to not have: [server.js#loadConfig](https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/server.js#L159-L162]) behave differently with tests. Another option might be if it is testing, then check for a non-default value (i.e. `this.timing !== 50`). Yet another thought I had was to introduce a `testTiming` option to be very explicit about it. `testTiming` would just be 0 by default and then could be easily overridden.

**Comment by samselikoff** [comment]
Oh, excellent point @workmanw. What about if the default test timing was 1, instead of 0? That way tests would by default be fast, but Mirage would respond on the next tick of the run loop as you point out.

**Comment by workmanw** [comment]
@samselikoff Yeap! 1 sec would be :+1: from me. I'll submit a PR.

**Comment by workmanw** [comment]
@samselikoff Actually upon further inspection it appears that I was wrong about that 😩. Using 0 does still result in responses being handled asynchronously. Using `false` would result insynchronouss responses.

Sorry about that. My mistake. We're all good :)

**Comment by blimmer** [comment]
@workmanw 1 second per test is way too long IMO. I think he meant 1ms.

**Comment by samselikoff** [comment]
👍

**Comment by workmanw** [comment]
@blimmer Yeap that was a typo on my part. I was planning to do 1ms, but if you see my last comment it turns out I've wasted everyone's time and it isn't necessary to even do 1ms :)

**Comment by samselikoff** [comment]
Closed due to inactivity.
