### ISSUE TITLE
Using a fully-qualified URL in configuration breaks

### ISSUE THREAD

**Issue by blimmer** [samselikoff/ember-cli-mirage#244]
Now that pretender supports cross-origin requests, it would be nice to be able to define a configured route like this:

```js
this.get('http://example.org/foos/:id')
```

However, the [server](https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/server.js#L72) is always placing a `/` before the path, which breaks fully qualified domains. With the example above, pretender will try to stub `/http://example.org/foos/:id`.

**Comment by samselikoff** [comment]
Regex if host is present so we don't break backwards compat?

**Comment by blimmer** [comment]
Yep, working on it now.
