### ISSUE TITLE
Do not catch assets request

### ISSUE THREAD

**Issue by bianjp** [samselikoff/ember-cli-mirage#249]
I'm trying to use [system.js](https://github.com/systemjs/systemjs) to dynamically load third-party addons, but ember-cli-mirage catches the request and reports `Mirage: Your Ember app tried to GET 'http://localhost:4200/assets/ueditor/ueditor.js', but there was no route defined to handle this request. Define a route that matches this path in your mirage/config.js file.`

Is there any way to prevent ember-cli-mirage from catching URLs of specific pattern (for example, starting with '/assets/')?

**Comment by samselikoff** [comment]
We're working on a better api for this, you can do

```js
this.pretender.get('/*passthrough', this.pretender.passthrough)
```

at the bottom of your config file to let everything pass through (or prefix with `/assets` if you only want those to pass through).

**Comment by bianjp** [comment]
Sorry, just got time to test it.
It works.
Thanks.
