### ISSUE TITLE
Cannot get working...

### ISSUE THREAD

**Issue by erichonkanen** [samselikoff/ember-cli-mirage#252]
Hello, I am getting an error trying to get mirage working for the first time... can anyone explain? Im using ember 1.13.4 and ember data 1.13.7

```
Mirage: The route handler for /v1/content is requesting data from the content collection, but that collection doesn't exist. To create it, create an empty fixture file or factory.


# mirage/config.coffee

import Mirage from 'ember-cli-mirage'

MirageConfig = ->
  @namespace = 'v1'

  # Route definitions.

  # Auth routes.
  @get '/auth-tokens/obtain', (db, request)->
    log 'obtain', request
  @get '/auth-tokens/refresh', (db, request)->
    log 'refresh', request

  # User routes.
  @get '/users'
  @get '/users/:username'

  # Content routes.
  @get '/content'
  @get '/content/:slug'
  

export default MirageConfig


# mirage/factories/content.coffee

import Mirage, { faker } from 'ember-cli-mirage'

title = faker.lorem.sentence()

export default Mirage.Factory.extend
  uid: faker.random.uuid()
  title: title
  slug: faker.helpers.slugify(title)
  sourceUrl: faker.internet.url()
  isPublished: faker.random.boolean()
  createdAt: faker.date.recent()
```

**Comment by blimmer** [comment]
This is going to be difficult to diagnose. Can you make a simple example app showing the issue? Feel free to fork/use [this example app repo](https://github.com/blimmer/ember-cli-example-app-for-github) .

**Comment by erichonkanen** [comment]
hey, so I think I narrowed it down to the shorthand routes not working.. I updated as follows and now the app loads but I have a new issue which is only 1 object is displayed, despite creating 10 and seeing 10 in the returned array in debugger.. any ideas on that?

```
# mirage/config.coffee

  # User routes.
  @get '/users'
  @get '/users/:username', (db, request)->
    id = request.params.username
    db.users.find id

  # Content routes.
  @get '/content', (db, request)->
    db.contents


# mirage/scenarios/default.coffee

DefaultScenario = (server)->
  user = server.create 'user', name: 'zelda'
  server.createList 'content', 10, poster: user.username

export default DefaultScenario
```

**Comment by samselikoff** [comment]
@erichonkanen what adapter/serializer are you using? JSON API? If so consult http://www.ember-cli-mirage.com/docs/v0.1.x/working-with-json-api/

**Comment by erichonkanen** [comment]
hey @samselikoff im using https://github.com/dustinfarris/ember-django-adapter

**Comment by samselikoff** [comment]
what format does django return a response? Do you know if it's just an array, is there a root, etc.? You need to replicate this in your route handler

**Comment by erichonkanen** [comment]
hm ok I think it's just an array.. do I need to wrap it with a root or make it jsonapi obj?

**Comment by samselikoff** [comment]
it needs to be the format your adapter/serializer expect...i'd say look at your django responses to see.

**Comment by erichonkanen** [comment]
hm it seems like it matches it pretty closely.. why would it display 1 object but not the others?

# actual api response
```
created_at: "2015-08-17T09:16:07.182933Z"
is_published: false
poster_id: "tallerholler"
slug: "nintendo-should-create-a-tower-defense-game-where-the-objective-is-to-keep-princess-peach-from-getting-kidnapped-in-the-first-place"
source_url: "http://asdasd.com"
tags: []
title: "Nintendo should create a tower defense game where the objective is to keep Princess Peach from getting kidnapped in the first place."
uid: "8e752da99e464e92b7afebe1fb8471ba"
updated_at: "2015-08-17T09:16:07.182945Z"
```

# mirage response
```
created_at: "2015-08-20T01:38:29.809Z"
is_published: true
poster_id: "Lillie34"
slug: "Dolorum-aspernatur-rerum-dignissimos-et-facilis-tenetur-ratione-explicabo-harum-autem-sunt-est-laboriosam-consectetur-ipsam-sequi-in-et-qui."
source_url: "https://leola.org"
tags: Array[0]
title: "Dolorum aspernatur rerum dignissimos et facilis tenetur ratione explicabo harum autem sunt est laboriosam consectetur ipsam sequi in et qui."
uid: "af296dd6-767c-4d2c-b5f7-df5cc59f9751"
```

**Comment by dustinfarris** [comment]
@erichonkanen I was able to use ember-cli-mirage in my ember-django-adapter project.  the only hangup was with embedded data—had to create that response manually.  otherwise things seem to just work.

**Comment by erichonkanen** [comment]
@dustinfarris hm yeah its really strange it works sort of... list responses are coming back with multiple objects in array but only 1 gets displayed

**Comment by dustinfarris** [comment]
Can you post an example JSON response that mirage is kicking back, but is not being parsed properly?

**Comment by erichonkanen** [comment]
@dustinfarris 
![image](https://cloud.githubusercontent.com/assets/230757/9455837/30b3dcf2-4a84-11e5-9d39-7e87bf9bd46b.png)

**Comment by dustinfarris** [comment]
How are you declaring `uid`?  Can you paste that part of your Ember models/user.js

**Comment by erichonkanen** [comment]
# models/user.coffee

```
import DS from 'ember-data'

export default DS.Model.extend
  uid: DS.attr 'string'
  username: DS.attr 'string'
  email: DS.attr 'string'
  fullname: DS.attr 'string'
  createdAt: DS.attr 'string'
  contentSet: DS.hasMany 'content', {async: true, inverse: 'poster'}
```

# serializers/content.coffee

```
import DS from 'ember-data'

export default DS.Model.extend
  uid: DS.attr 'string'
  title: DS.attr 'string'
  slug: DS.attr 'string'
  poster: DS.belongsTo 'user', {async: true, inverse: 'contentSet'}
  sourceUrl: DS.attr 'string'
  tags: DS.hasMany 'tag', {async: true, inverse: null}
  isPublished: DS.attr 'boolean'
  createdAt: DS.attr 'string'

  # properties
  canDelete: (->
    currentUserId = @currentUser.get 'content.username'
    posterUserId = @get 'poster.username'
    currentUserId == posterUserId
  ).property 'currentUser.content'
```

# serializers/user.coffee

```
import DRFSerializer from './drf'

UserSerializer = DRFSerializer.extend
  normalize: (type, hash, property)->
    hash.id = hash.username
    @_super type, hash, property

export default UserSerializer
```

# serializers/content.coffee

``
import DRFSerializer from './drf'

ContentSerializer = DRFSerializer.extend
  normalize: (type, hash, property)->
    hash.id = hash.slug
    @_super type, hash, property
  attrs:
    poster: key: 'poster_id'

export default ContentSerializer
```

**Comment by samselikoff** [comment]
I'm going to close this for now as it's very general, please lmk if you still have questions!
