### ISSUE TITLE
Create object outside scenarios/default

### ISSUE THREAD

**Issue by erichonkanen** [samselikoff/ember-cli-mirage#253]
Hello, I am new to mirage and trying to figure out how to get it working with my auth route that uses https://github.com/jpadilla/ember-cli-simple-auth-token. My app expects that both a jwt token and the serialized currently logged in user are returned in the payload from my /auth-tokens/obtain endpoint.

My issue is how can I create a user object to return as part of my route? Still learning this and trying to figure it out so any info appreciated! Also let me know if it looks like good approach in general...

```
  # Auth routes.
  @post '/auth-tokens/obtain', (db, request)->
    params = JSON.parse request.requestBody
    if params.username == 'tallerholler' && params.password == 'bagiales'
      data =
        'token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjoiNjczN2E5ZWM0OTY1NDY0Yjg1MTQ0ZjQ3YjkwZThmZDciLCJvcmlnX2lhdCI6MTQzOTk5NTkzMiwiZW1haWwiOiJlcmljQHNxd29rLmlvIiwidXNlcm5hbWUiOiJ0YWxsZXJob2xsZXIiLCJleHAiOjE0Mzk5OTYyMzJ9.DtkL0bmmrdGdSbqq4EIEPagQyw_02DcW7oyJ-PlT_Eo'
        'user': {<USER>}
      return data
    else
      body = errors: 'Email or password is invalid'
      new Mirage.Response 401, {}, body
```

**Comment by erichonkanen** [comment]
made some progress since I posted this but still all I know how to do is grab an object from the `db.users` array.. not sure if there is a better way.. 

here is my current auth route for mirage

```
  # Auth routes.
  @post '/auth-tokens/obtain', (db, request)->
    params = JSON.parse request.requestBody
    token = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjoiNjczN2E5ZWM0'+
            'OTY1NDY0Yjg1MTQ0ZjQ3YjkwZThmZDciLCJvcmlnX2lhdCI6MTQzOTk5NTkzM'+
            'iwiZW1haWwiOiJlcmljQHNxd29rLmlvIiwidXNlcm5hbWUiOiJ0YWxsZXJob2'+
            'xsZXIiLCJleHAiOjE0Mzk5OTYyMzJ9.DtkL0bmmrdGdSbqq4EIEPagQyw_02D'
            'cW7oyJ-PlT_Eo'
    unless params.username? and params.email?
      response = new Mirage.Response 401, {},
        errors:
          email: 'Missing username or email'
    else
      response =
        'token': token
        'user': db.users[0]
    return response
```

**Comment by samselikoff** [comment]
Yep, that looks good to me, `db.users[0]` will always return the first user in the db, you could also `db.users.where({username: params.username})[0]`.

View the full db api here: http://www.ember-cli-mirage.com/docs/v0.1.x/database/

**Comment by samselikoff** [comment]
It seems like you were able to get this working, closing for now. Lmk if you have more questions!
