### ISSUE TITLE
Transitionning to mirage from http mocks

### ISSUE THREAD

**Issue by olivierlesnicki** [samselikoff/ember-cli-mirage#255]
Is there a way both are able to live together while one transition from http-mocks ember-cli-mirage. We have a lot of acceptance tests and mocks, but we don't have the time to make a BIG BANG switch. How can one do the switch in staged fashion?

**Comment by samselikoff** [comment]
@olivierlesnicki absolutely, you can stick a glob `passthrough` route at the bottom of your `config.js` to allow unhandled routes to pass through mirage:

```
this.pretender.get('/*passthrough', this.pretender.passthrough);
this.pretender.post('/*passthrough', this.pretender.passthrough);
this.pretender.put('/*passthrough', this.pretender.passthrough);
this.pretender.del('/*passthrough', this.pretender.passthrough);

**Comment by olivierlesnicki** [comment]
@samselikoff awesome!!!

**Comment by samselikoff** [comment]
let me know if you need anything else!
