### ISSUE TITLE
Issues accessing remote service using passthrough

### ISSUE THREAD

**Issue by acorncom** [samselikoff/ember-cli-mirage#256]
This is a continuation of my comments on #19, but not sure it's a CORS issue ...  Will post a reproduction repo shortly ...

**Comment by acorncom** [comment]
I'm afraid I may have mixed things up by asking my question on a CORS issue.  If so, I apologize :-/

Per discussion on the referenced issue, doing this at the end of `app/mirage/config.js`:

`this.pretender.get('/*passthrough', this.pretender.passthrough);`

or adding these lines to the same file:

```
  this.pretender.get('/1/index*', this.pretender.passthrough);
  this.pretender.put('/1/index*', this.pretender.passthrough);
  this.pretender.delete('/1/index*', this.pretender.passthrough);
  // this.pretender.post('/1/index*', this.pretender.passthrough);
```

should allow access to remote URLs through pretender 0.9.0 when using jQuery 2.x.

I've got a sample repo setup here showing my issue: https://github.com/acorncom/algolia-pretender-issue-reproduction

With Ember-CLI-Mirage off, things work quite well (start typing in David, Sam or Ben and you should get results).  If you re-enable mirage in `config/environment.js` however, things don't work.

Thoughts?

**Comment by samselikoff** [comment]
try `/1/index*passthrough`, I think you might need some text after the `*`?

**Comment by acorncom** [comment]
@samselikoff Was just writing a note as I thought I had to have a full url.  Yes, you're right, some test after the `*` is required, much appreciated!  Was able to figure out my issue based on https://github.com/samselikoff/ember-cli-mirage/issues/228

Closing this now.  And in case I haven't been clear, I'm really appreciating Mirage :+1:

**Comment by samselikoff** [comment]
so glad! sorry this whole passthrough thing has caused a lot of users confusion, we really need a better api for it

**Comment by acorncom** [comment]
It's possible a better api is what's needed, but you've saved a lot of users a lot of time / effort with the tool, so don't apologize ;-)  APIs can be fixed, but this tool is very, very handy

**Comment by samselikoff** [comment]
:heart:
