### ISSUE TITLE
Scenarios can leverage fixtures

### ISSUE THREAD

**Issue by ksnyde** [samselikoff/ember-cli-mirage#257]
It would be nice to have a scenario load fixtures for all "reference data" sources and then create some transactional data with factories. I'm imagining something like:

    server.loadFixture('products');
    server.loadFixture('locations');
    server.createList('users', 10);

**Comment by pichfl** [comment]
I don't know if this is the best idea, but with 0.1 you can do this in your scenario.js

```js

import ENV from '../config/environment';
import readModules from 'ember-cli-mirage/utils/read-modules';

// Retrieving the mapper used internally when loading fixtures
var modulesMap = readModules(ENV.modulePrefix);

// Load all fixtures
server.db.loadData(modulesMap['fixtures']);

```

You should be able to run `server.createList` for your factories after that. It's however not a good idea to have both fixtures and a factory for the same data type.

**Comment by samselikoff** [comment]
Nice hacking florian! It may not be the worst thing, actually. I've even
thought maybe we should have first class support for this in the public
API.

Fixtures and factories are two different ways to solve the same problem:
seeding your db with test data. If the easiest way to get your test db set
up is to use both, I don't see a huge problem with that.

**Comment by ksnyde** [comment]
In fact I think it would be not too uncommon for apps which work off existing data platforms to create a large data dump for reference data and load that as a fixture whereas all *transactional* data is loaded using the more dynamic factory pattern.

**Comment by samselikoff** [comment]
No updates, hacking away on serializers/ factory relationships. This API shouldn't be too difficult to add, if someone gets a chance to PR before I get there.

**Comment by mrpollo** [comment]
@pichfl thanks for the hack, I would vote to make this public, fixtures + factories are powerful, why?, consider the case where you want to have 1 static fixture with a fixed ID always there, say you depend on this to have specific attributes or relationships, you can always ask for this fixture by id, but also have some other generated dynamically by the factories, I might have a fairly convoluted fixture+factories setup but I'm sure i'm not alone, plus #69 will help a lot with relationships, I'm just trying to make them work right now on my end, this means hacking my way through fixtures+factories and having my default scenario use both to create my seed data.

**Comment by samselikoff** [comment]
Yep, this will absolutely be public. Will be easy after merging some recent changes to `Server`, actually

**Comment by mrpollo** [comment]
awesome, thanks @samselikoff, let me know if you need beta testers, more than glad to go cutting edge

**Comment by samselikoff** [comment]
The `loadFixtures` api just landed: http://www.ember-cli-mirage.com/docs/v0.1.x/server-configuration/#passthrough

Upgrade to 0.1.9 and let me know if you need anything else. Thanks for kicking off this discussion!

**Comment by ksnyde** [comment]
Exciting. I'm doing some non-technical nonsense for a few days but I'll check it out by EOW. Thanks for continuing to be awesome. :+1:
