### ISSUE TITLE
Fix `ember-pretenderify` on npm.

### ISSUE THREAD

**Issue by ChALkeR** [samselikoff/ember-cli-mirage#259]
_I know that `ember-pretenderify` is deprecated, but it's still on `npm` and still gets downloaded._
_Disclaimer: I am not a user of the package._

The current problems are:
1. [embed-pretenderify](https://www.npmjs.com/package/ember-pretenderify) bundles **303 MiB** of garbage in `/tmp` dir.
2. Does every user get a proper deprecation message? Not everyone checks the npm page.

The correct way of fixing this (if the project was renamed, in case if it's a library) would be to replace the package with a thin wrapper that depends upon the latest compatible version of `ember-cli-mirage` and prints a deprecation message.

If that is somewhy impossible, you probably should at least fix the ~300 MiB issue. For details, see https://github.com/ember-cli/ember-cli/issues/4199#issuecomment-134204192.

**Comment by samselikoff** [comment]
Closed due to inactivity.
