### ISSUE TITLE
Passthrough non JSON returning end-point

### ISSUE THREAD

**Issue by olivierlesnicki** [samselikoff/ember-cli-mirage#264]
Attempting to passthrough API end-points that do not return JSON text results in errors.
Is there a way to pass-through those end-points?

**Comment by samselikoff** [comment]
try

`this.pretender.get('http://*', this.pretender.passthrough);`

**Comment by samselikoff** [comment]
Please upgrade to 0.1.9 and try the new [passthrough api](http://www.ember-cli-mirage.com/docs/v0.1.x/server-configuration/#passthrough) api, and let me know if it doesn't solve this. 

Thanks!

**Comment by olivierlesnicki** [comment]
@samselikoff Sadly we can't upgrade to jQuery 2.x for support reasons.

**Comment by samselikoff** [comment]
Understood. Maybe you could provide some more information or help out over on trek/pretender to move this along:

https://github.com/pretenderjs/pretender/issues/85

**Comment by olivierlesnicki** [comment]
Yes, it's a simple fix actually. Raised PR https://github.com/pretenderjs/pretender/pull/114
But unit tests are failing and I haven't had the time to identify the culprits.

**Comment by olivierlesnicki** [comment]
according to the specs both onreadystatechange and onload events are supposed to be triggered, but prentender only trigger one at any given time.

**Comment by samselikoff** [comment]
Closing for now, since this is a Pretender issue. Please lmk if you have more questions.

**Comment by samselikoff** [comment]
Actually, it looks like it was fixed - you should try it out!
