### ISSUE TITLE
object.defineproperty calls in schema.registerModels prevent server re-initialization

### ISSUE THREAD

**Issue by 2468ben** [samselikoff/ember-cli-mirage#266]
Happens when running more than one test in qunit, with or without window.server.shutdown in between.
 
In `schema.registerModels`, some Object.defineProperty getters are created on the model prototypes during the first initialization. If the server's re-created for a second test on the same page, those getters override some calls in `schema.registerModels`'s second runs.

https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/orm/schema.js#L36 was getting picked up by one of these three getters:

https://github.com/samselikoff/ember-cli-mirage/blob/6753698ec3818b6b5e99594a74f764230cdc0d01/addon/orm/associations/has-many.js#L41 (looking for undefined attrs)
https://github.com/samselikoff/ember-cli-mirage/blob/6753698ec3818b6b5e99594a74f764230cdc0d01/addon/orm/associations/has-many.js#L38 (calling isNew() which looks for attrs)
https://github.com/samselikoff/ember-cli-mirage/blob/6753698ec3818b6b5e99594a74f764230cdc0d01/addon/orm/associations/has-many.js#L83
(calling isNew() which looks for attrs)

If I add `if(!this.attrs) { return; }` to the top of those getters, everything runs fine again, but that's not a great solution so I skipped the PR.

**Comment by samselikoff** [comment]
Hm, still seeing this?

Should we do some more cleanup in `server.shutdown`? Something to ensure all the objects are GC'd so we start fresh in new tests?

**Comment by 2468ben** [comment]
I was waiting to retry models & serializers due to some work busy-ness, but I'll try to check out in the next few days.

Yeah, the issue was that the defineProperty properties were being accessed on a second run before they could be redefined. I don't know if that's still the case since it's been a few months, but if it is then having a list of keys that mirage can push to whenever it uses defineProperty, then cleaning out that list on shutdown.

**Comment by 2468ben** [comment]
I just finally finished getting my whole suite running in the ORM and not seeing this at all, so closing it. Thank you!

**Comment by samselikoff** [comment]
Awesome!
