### ISSUE TITLE
Model update breaks when a request is sent with a 'type' field

### ISSUE THREAD

**Issue by 2468ben** [samselikoff/ember-cli-mirage#267]
like `{comment: {id: 1, type: 'photo'}}` as the JSON

the model.update function's overwriting this.type with this.attrs.type, so when it calls model.save it looks for a collection based on this.attrs.type.

**Comment by samselikoff** [comment]
ahh, good catch. attrs are stored on a `attrs` hash but I define getter/setters using object.defineProperty, so that's the problem. I suppose I should make that `_type` or even `__type`.

Btw the model layer is not ready yet and the api is still undergoing changes, just so you're aware!

**Comment by samselikoff** [comment]
57c9ca4dea414eb0479a6c376addbb30078b7635 closes

**Comment by samselikoff** [comment]
`type` has been renamed to `modelName`

**Comment by 2468ben** [comment]
Awesome, thank you very much!
