### ISSUE TITLE
Factory sequences, traits, lazy

### ISSUE THREAD

**Issue by samselikoff** [samselikoff/ember-cli-mirage#27]
The API for sequences is changing to be consistent with upcoming traits, dynamic attrs and associations.

```js
// factories/post.js
import Mirage from 'ember-cli-mirage';

export default Factory.extend({
  title: 'ABC',
  date: new Date(),

  likes: Mirage.seq(i => i),

  approved: Mirage.trait({
    approved_at: new Date(),
  }),

  views: Mirage.lazy(() => {
    return Math.random() * 1000;
  }),

  link: Mirage.lazy('title', 'date', (title, date) => {
    return moment(date).format('MM/DD') + '/' + title;
  }),

});


// tests/acceptance/index-test.js
...
server.create('user');
server.create('user', 'approved');
```

**Comment by jamesarosen** [comment]
One pattern we use a lot is a belongs-to relationship that defaults to the first one in the DB:
```js
foo_id: Mirage.lazy((db) => {
  return db.foos.firstOrCreate().id;
})
```

**Comment by mellatone** [comment]
Would this support something like

'''
Factory.extend({
  first: function(){
    return faker.name();
  },
  last: function(){
    return faker.name();
  },
  full: function(){
    Return this.first + " " + this.last;
  }
})
'''

(Take it as pseudo code.. on a mobile!)

**Comment by samselikoff** [comment]
@jamesarosen interesting... I think an `afterCreate` block would be a nice place for this?

@mellatone yes, actually this is possible as soon as [this PR](https://github.com/samselikoff/ember-cli-mirage/pull/269) lands, which is backwards compatible so there's nothing blocking it.

**Comment by samselikoff** [comment]
![image](https://cloud.githubusercontent.com/assets/2922250/14576163/fb09c46c-0334-11e6-8064-13cc8cc72ce3.png)

**Comment by samselikoff** [comment]
https://github.com/samselikoff/ember-cli-mirage/pull/269 closes dynamic

**Comment by samselikoff** [comment]
closing, follow https://github.com/samselikoff/ember-cli-mirage/issues/852 to track
