### ISSUE TITLE
How to write acceptance tests with liquid fire modals

### ISSUE THREAD

**Issue by mswanson** [samselikoff/ember-cli-mirage#275]
Quick question, I am trying to do some acceptance testing with my app and I'm stuck on how to make ember-cli-mirage work with Liquid Fire modals. I am following the Liquid Fire docs pretty much verbatim for implementing the modals.

All the modals are being defined in the router using query params to invoke them. So in `router.js` I have something like
```js
Router.map(function() {
    this.route('index', function() {
        this.modal('my-modal', {
            withParams: ['modalType', 'modalTargetId'],
            otherParams: ['model', 'hasServerError'],
            dismissWithOutsideClick: false,
            dismissWithEscape: false,
            controller: 'modal/my-modal',
            dialogClass: 'Modal',
            actions: {
                submit: 'submit',
                cancel: 'cancel'
            }
        });
    });
});
```

In the app the controller observes the query prams and the modals are invoked by setting them in a `link_to` like so:
```js
{{#link-to (query-params modalType="new" modalTargetId=model.id)}}New{{/link_to}}
```

Executing a `click` on the linkto inside the test does nothing. Based on the mirage documentation it sounds like I need to add a route to the `config.js` file but I am not sure what to add. The route is the same as a route I have already defined just with the query params. Also worth noting is the fact that I have multiple modals hanging off the same route. (e.g. a 'New' modal, an 'Edit' modal and a 'Delete' modal)

Any suggestions or documentation around this would be super helpful. Once I get this figured out I would be happy to write some documentation around it and submit a PR to update the docs or even just post a gist of the solution. I figure I am not the only one trying to write acceptance test with liquid fire modals.

@samselikoff great work, this plugin has already made the testing story in Ember 10x better.

**Comment by samselikoff** [comment]
Thanks for the kind words, and sorry you're running into trouble!

Mirage is only for mocking out your backend, so unless you're Ember app is making AJAX requests I suspect there's something else going on here. Are there any network requests involved in the bug you're seeing?

**Comment by mswanson** [comment]
The requests to the server for these modals don't happen until the user submits the form inside them. I'll dig around some more and see if there is something else I am missing. Thanks.

**Comment by blimmer** [comment]
@mswanson I'm going to close this issue for now, but if your investigation shows that there's a bug in Mirage related to this, please don't hesitate to reopen.
