### ISSUE TITLE
Calls with filter params (JSONAPI)

### ISSUE THREAD

**Issue by oliverbarnes** [samselikoff/ember-cli-mirage#278]
I'm trying to stub a `GET /supports?filter[proposal_id]=1&filter[author_id]=1` call, which uses [JSONAPI filtering](http://jsonapi.org/format/#fetching-filtering), with

```
this.get('/supports?filter[proposal_id]=1&filter[author_id]=1', function(db, request) {
...
});
```

but it doesn't get recognized. `this.get('/supports, function...` does, but that means that all GET calls to `/supports` get intercepted as well.

Am I doing something wrong, or is this a limitation of the way uris are parsed? If so, are there any tricks to get around it?

**Comment by oliverbarnes** [comment]
ok, people on slack pointed out that url params aren't supported, then realized I can check for the filter params with `​request.queryParams`. Here's the final stub, in case somebody has the same problem:

```
this.get('/supports', function(db, request) {
    let supports = []

    if(Ember.isEmpty(request.queryParams)) {
      supports = db.supports;
    } else {
      let proposalId = request.queryParams['filter[proposal_id]'];
      let authorId = request.queryParams['filter[author_id]'];

      supports = db.supports.where({proposalId: proposalId, authorId: authorId});
    }

    return {
      data: supports.map(attrs => (
        {type: 'supports', id: attrs.id, attributes: attrs }
      ))
    };
  });
```

**Comment by topaxi** [comment]
Shouldn't this be supported out of the box? Or at least easily configurable somehow?

**Comment by samselikoff** [comment]
I've made a new issue to track: https://github.com/samselikoff/ember-cli-mirage/issues/565

**Comment by samselikoff** [comment]
And yes it is absolutely a reasonable thing to include with the JSON API layer. It doesn't exist right now because, it's not the highest priority :)

**Comment by topaxi** [comment]
Awesome! :)

**Comment by Silverdark** [comment]
For me, this works pretty fine:

```javascript
this.get('/logs', function (db, request) {
    let logs = [];

    if (Object.keys(request.queryParams).length === 0) {
      logs = db.log.all();
    } else {
      let filteredCategory = request.queryParams['filter[category]'];
      logs = db.log.where({category: filteredCategory});
    }

    return logs;
});
```

When I apply no filter to the solution from @oliverbarnes, `Ember.isEmpty` is false -> it tries to apply a filter, because `request.queryParams` is an empty Object.

Maybe this is coming from a new mirage version, I use beta.7.

**Comment by v3ss0n** [comment]
filters are supported now?

**Comment by samselikoff** [comment]
@v3ss0n not out of the box. You can filter data manually using a function route handler, but #565 is about adding out-of-the-box support for {json:api} spec'd filters.

**Comment by v3ss0n** [comment]
i c. i am building one by manually filtering arrays for now.

**Comment by nselikoff** [comment]
Latest issue tracking this feature request is https://github.com/samselikoff/ember-cli-mirage/issues/1419

**Comment by nselikoff** [comment]
Example that supports filtering by an array of values. You can pass a function to `where` instead of a POJO (see https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/db-collection.js#L399).

```js
  this.get('/trips', function (schema, request) {
    if (isEmpty(request.queryParams)) {
      return schema.trips.all();
    }

    let query = {};
    if (request.queryParams['filter[trip_tag]']) {
      filters.tripTag = request.queryParams['filter[trip_tag]'];
    }

    // custom query function to support array values for filters
    function customQueryFunction(record) {
      let keys = Object.keys(query);

      return keys.every(function(key) {
        if (Array.isArray(query[key])) {
          return query[key].includes(String(record[key]));
        } else {
          return String(record[key]) === String(query[key]);
        }
      });
    }
    return schema.trips.where(customQueryFunction);
  });
```

Another option here would be to do `schema.trips.all().filter(...)`.
