### ISSUE TITLE
Factory relationships

### ISSUE THREAD

**Issue by samselikoff** [samselikoff/ember-cli-mirage#28]

**Comment by jrjohnson** [comment]
I'm assuming from the title that there is no current way to generate relationships between factories?
So the right way to create relationships would be something like:
```javascript
// tests/factories/contact.js
import Mirage from 'ember-cli-mirage';

export default Mirage.Factory.extend({
  name: 'Pete',
  age: 20,

  friends: function(i) {
    return [
      {id: 100+i, name: "Pete's Friend", age: 21},
      {id: 101+i, name: "Pete's Mom", age: 55},
    ]
  }
});
```

Or is there a simpler path?

**Comment by samselikoff** [comment]
correct, no current way. I've been doing it in my tests:

```js
create('contact', {friend_ids: [1, 2, 3]});
createList('friend', {contact_id: 1});
```

which is obviously not idea, since I'm "guessing" the ids.

**Comment by samselikoff** [comment]
Thinking about the api...

```js
// factories/book.js
import Mirage from 'ember-cli-mirage';

export default Mirage.Factory.extend({
  name: 'A Wrinkle in Time',

  author: Mirage.Factory.association(),
  author: function() {
    this.association();
  },
  associations: {
    author: 'author',
    author: ['author', 'person', 'blah', {name: 'Sam'}]
  },
  associations: [
    'author',
    ['author', 'person', 'blah', {name: 'Sam'}]
  ]
});
```

full api needs to include association(optionalFactory, trait..., overrides...)

**Comment by buschtoens** [comment]
Were you able to make some progress on this?

This is currently areal pain point for me, as I'm working on a scheduling app that naturally has a lot of many to many and one to many relationships. I'm currently abusing the `i` parameter really hard.

Here's an example of a automatic many to many relationship:

```js
import Mirage from 'ember-cli-mirage';
import subjects from '../fixtures/subjects';

const LENGTH = subjects.length;

function getRandomInt(min, max) {
  return Math.floor(Math.random() * (max - min)) + min;
}

export default Mirage.Factory.extend({
  isVisible: true,
  room: i => `${getRandomInt(1, 2)}.${getRandomInt(0, 2)}${getRandomInt(0, 9)}`,

  studentsLocalOral:     i => getRandomInt(1, 5),
  studentsLocalWritten:  i => getRandomInt(4, 10),
  studentsRemoteOral:    i => getRandomInt(0, 2),
  studentsRemoteWritten: i => getRandomInt(0, 4),

  subject(i) {
    let s = subjects[i % LENGTH];
    s.courses.push(i + 1);
    return s.id;
  }
});
```

This is all *very* hacky, but kinda works. However, this technique has its limits, as I can only "read" data from the fixtures, but not from previously generated factory records. If I had access to the DB in my factories, I could do some more clever stuff. It'd be still ugly as hell, but hey! :smile: 

Have you yet decided on a proper API for factory relationships? I'd be happy to implement it, if you can't find the time.

**Comment by buschtoens** [comment]
Ah, I see that this is probably tracked in #69 for now.

**Comment by samselikoff** [comment]
Yep see my note there. Also, I think what you said is good, having an "escape hatch" in a factory to let you access db/schema to do whatever you want.
