### ISSUE TITLE
External API requests getting intercepted

### ISSUE THREAD

**Issue by constantm** [samselikoff/ember-cli-mirage#285]
I'm running into an issue where external API requests are captured by mirage. Is there a way around this? Mapbox, for instance:

`Mirage: Your Ember app tried to GET 'http://a.tiles.mapbox.com/v4/testmapstuff.zvnjyewv.json?access_token=ek.gsTgsV...', but there was no route defined to handle this request. Define a route that matches this path in your mirage/config.js file.`

In my config, I've tried to namespace the Mirage API with `urlPrefix` and `namespace` to no avail.

As a side note, I also ran into another issue with external APIs where the object created by fake XMLHttpRequest created by Pretender doesn't include `withCredentials`, and causes corslite.js to break. I've logged an issue for that here, but I managed to get passed it until I get a proper fix by editing `pretender.js` to always include `withCredentials`. (Yes, this is horrible) https://github.com/pretenderjs/pretender/issues/112

**Comment by samselikoff** [comment]
Could you try adding

```
this.pretender.get.call(this.pretender, '/*passthrough', this.pretender.passthrough);
```

at the bottom of your config.js? I just haven't had time to add this API yet.

**Comment by constantm** [comment]
Nope, doesn't work.

**Comment by samselikoff** [comment]
What version of mirage / pretender? I think you also need to be on jquery 2.x

**Comment by constantm** [comment]
Ember 1.13.8, Mirage 0.1.8. Jquery is on 1.11.3, so that might be the issue? I'll try moving to 2.x and see what blows up.

**Comment by constantm** [comment]
Doing the same thing on jQuery 2.1.4 - if it helps, my config file looks like follows:

```
export default function() {
  this.urlPrefix = 'http://api.test.com';
  this.namespace = 'v1';

  this.get('/companies');
  this.get('/companies/:id', ['company', 'events']);

  this.get('/events');
  this.get('/events/:id');

  this.get('/opportunities');
  this.get('/opportunities/:id');

  this.pretender.get.call(this.pretender, '/*passthrough', this.pretender.passthrough);
}
```

**Comment by samselikoff** [comment]
try `'*passthrough'* (without the leading `/`)?

**Comment by samselikoff** [comment]
also, the `urlPrefix` may be getting added, try `http://a.tiles.mapbox.com/*` for the path

**Comment by constantm** [comment]
Doesn't look like `*passthrough` does anything. I've also tried removing the urlPrefix from Mirage and the adapter. With part of `this.pretender.get.call(this.pretender, '/*passthrough', this.pretender.passthrough);` is the path that I need to change?

**Comment by samselikoff** [comment]
the `"/*passthrough"` part, the second argument

**Comment by samselikoff** [comment]
also, what version of pretender?

**Comment by constantm** [comment]
Okaaay it looks like added the mapbox url into the path resolves the error, and it returns a JSON response. However, the map isn't rendered. I'm going to try and use the map addon I'm using on a new, clean Ember app and see if it does the same.

**Comment by constantm** [comment]
Using that PR doesn't seem to work, unless I'm using it wrong. Requests not caught by Mirage aren't passed through/isn't getting returned. With the following in the config file, it does a request, and returns it just fine. However, it seems that the request is never passed back to the corslite library, and after the first request returns nothing happens. I've tried this is a project without Mirage and it seem to work fine. So, the issue at this point seems that the request gets made, and then it appears af if it doesn't end up back with the function that called in. I'm afraid I'm stuck here. :/

```
this.pretender.get.call(this.pretender, 'http://a.tiles.mapbox.com/*passthrough', this.pretender.passthrough);
  this.pretender.get.call(this.pretender, 'http://b.tiles.mapbox.com/*passthrough', this.pretender.passthrough);
```

My XHR calls with Mirage installed:
![screen shot 2015-09-24 at 1 01 22 pm](https://cloud.githubusercontent.com/assets/292439/10071834/381041ce-62bd-11e5-99da-c58f4d872b88.png)

My XHR calls without Mirage:
![screen shot 2015-09-24 at 1 02 54 pm](https://cloud.githubusercontent.com/assets/292439/10071846/48e36d96-62bd-11e5-9533-2ea8eb1e695d.png)

**Comment by samselikoff** [comment]
You sure you're on jquery 2.x? [This comment](https://github.com/samselikoff/ember-cli-mirage/issues/219#issuecomment-126098862) in another issue sounds very familiar

**Comment by olegdovger** [comment]
I do not if it helps someone with mapbox script loading but I found that if we add `withCredentials` and `onload` in prototype

(somewhere in your script)
`FakeXMLHttpRequest.prototype.withCredentials = false;` //fix for corslite.js
`FakeXMLHttpRequest.prototype.onload = function () {};`  //fix for FakeXMLHttpRequest (pretender), corslite.js

(config.js)
`this.pretender.get('http://a.tiles.mapbox.com/*passthrough', this.pretender.passthrough);`
`this.pretender.get('http://b.tiles.mapbox.com/*passthrough', this.pretender.passthrough);`

This is a hack I know. Sorry for such dirty solution. And this solution can be incompatible with other requests

**Comment by constantm** [comment]
Ah this is awesome @olegdovger. I had the `FakeXMLHttpRequest.prototype.withCredentials = false;`, which resolved the initial `XDomainRequest ` error, but then nothing happened after that. Will add `onload` and see what happens. Thanks!

**Comment by samselikoff** [comment]
There's now a [passthrough api](http://www.ember-cli-mirage.com/docs/v0.1.x/server-configuration/#passthrough), could you upgrade to 0.1.9 and try that out and let me know if you're still having problems?

Thanks!

**Comment by constantm** [comment]
Amaaazing thanks!

**Comment by variousred** [comment]
I can get the requests to mapbox to go through but it seems somehow the handling of the response isnt quite right.

When i run in development mode i see the request to mapbox initiated by pretender.js. I see that the response looks proper. But the map does not load. When i run in production mode and the request is initiated by corslite and everything works fine.

I see no errors in console in either case.
Jquery 2
ember-cli-mirage@0.1.13
https://api.mapbox.com/mapbox.js/v2.4.0/mapbox.js

**Comment by samselikoff** [comment]
What version of Pretender in your `bower.json`? This sounds vaguely familiar to issues others have had, I believe related to an older version of Pretender

**Comment by variousred** [comment]
pretender ~0.10.1

**Comment by variousred** [comment]
You called it. I upgraded to pretender 1.0.0 and the issue goes away. Thanks @samselikoff

**Comment by allthesignals** [comment]
I have somewhat the opposite problem: I'd like to try to intercept these tile requests through Pretender. However, it doesn't seem like `fetch` gets intercepted correctly. Here's where it is called in MapboxGL code: https://github.com/mapbox/mapbox-gl-js/blob/4f0ab92b28df6cc6ea00280ddc079a4fc9fbd55b/src/util/ajax.js#L132.

It workers everywhere else.

**Comment by allthesignals** [comment]
<img width="640" alt="Screen Shot 2020-01-17 at 5 00 12 PM" src="https://user-images.githubusercontent.com/5004319/72649170-ee80c100-394a-11ea-937a-112808928ab4.png">
Logging window.XMLHttpRequest, it just seems like it isn't being applied to the service worker context (although I don't understand enough about service workers to get around this).
