### ISSUE TITLE
Fixtures & Factories Co-Existing?

### ISSUE THREAD

**Issue by drewcovi** [samselikoff/ember-cli-mirage#289]
I'm getting the following message while working with Mirage despite having a plural fixtures file under the fixtures directory.  I also have a number of factories working without issue:

`Mirage: The route handler for /d3sapi/Service3S.svc/userRoles is requesting data from the userRoles collection, but that collection doesn't exist. To create it, create an empty fixture file or factory.`

Am I missing a step to ensure that the fixtures are leveraged? I've been pouring over the docs to no avail.

**Comment by drewcovi** [comment]
upon further investigation I feel as thought the following stand at odds.  Quote from docs, and conditional only loading (exclusively) fixtures or factories.

>You can also choose to use fixtures instead of (or in addition to) factories. If you've never used fixtures before, think of a fixture file as a database table. To add data to your users table, for instance, create the file /app/mirage/fixtures/users.js

`if (env === 'test' && hasFactories) {
        server.loadFactories(modulesMap['factories']);
      } else if (env !== 'test' && hasDefaultScenario && hasFactories) {
        server.loadFactories(modulesMap['factories']);
        modulesMap['scenarios']['default'](server);
      } else {
        server.db.loadData(modulesMap['fixtures']);
      }
`

**Comment by samselikoff** [comment]
Sorry about the confusion. Currently if factories are defined, fixtures will be ignored. We're working on an API that will let you load fixture files and also use factories. 

For now, you can try something like in [this issue](https://github.com/samselikoff/ember-cli-mirage/issues/257).

**Comment by samselikoff** [comment]
There's now a [loadFixtures](http://www.ember-cli-mirage.com/docs/v0.1.x/server-configuration/#loadFixtures) api, upgrade to 0.1.9, try it out and let me know if you still need help.

Thanks!
