### ISSUE TITLE
Factory fake data with Faker.js

### ISSUE THREAD

**Issue by samselikoff** [samselikoff/ember-cli-mirage#29]

**Comment by seanpdoyle** [comment]
How do you feel about integrating with `json-schema`? The schema allows for an `example` key, which could be used in place of whatever value `faker.js` would generate.

This schema could serve as the glue between the client and server. 

On the server side, the schema would be used to validate the response. 

On the client side, (with some additional work) `mirage` could somehow validate the factories against the schema.

This way, we could use the schema to serve as the shared contract between the front and back end.

@rondale-sc we talked about this at EmberConf. Do you have any input?

**Comment by samselikoff** [comment]
I'm very interested, actually [@achambers](https://github.com/achambers) has mentioned something similar in reference to [pact](https://github.com/realestate-com-au/pact), essentially an automated way to verify the consumer app and API both respect the same contract.

I think this is a big project but something I'm absolutely interested in tackling. Not entirely sure where we'd start, we still have a lot of work to get Mirage to a point where you can use it to faithfully represent your backend. I think I have a good roadmap for this, though - essentially adding collections + serializers.

I don't know anything about json-schema so that might be a good place for me to start. I'm also wondering how ios/native mobile apps have been tackling this problem. Are we missing something? I don't want to go down a road where there's unnecessary maintenance on a developer to keep his fake frontend server implementation in sync with his real backend. But I'm not sure there's a better alternative out there right now.

**Comment by rondale-sc** [comment]
@seanpdoyle @samselikoff Yeah, I think this sounds like a good thing to look into.  I'm not very familiar with json-schema, I'll take a look.  :)  Definitely interesting.

**Comment by samselikoff** [comment]
#153 closes
