### ISSUE TITLE
Using with proxy?

### ISSUE THREAD

**Issue by wayne-o** [samselikoff/ember-cli-mirage#294]
Hi

Is there anyway I can use this when we are using a proxy for auth methods? 

We need to be able to proxy http://localhost:1337/api/v1/auths (only) to http://localhost:4200/api/v1/auths so that we can get oAuth working - the rest of the app doesn't proxy at all - it talks direct to 1337 - is there anyway we can do this and use this project? 

I have tried setting it up but no luck so far.

**Comment by wayne-o** [comment]
I ended up with this:

```
if (config.enableAuthProxy) {
    mocks.forEach(function(route) { route(app); });
    proxies.forEach(function(route) { route(app); });
  }
```

**Comment by samselikoff** [comment]
You'd need to use an http-proxy. Also, you can mock out other-origin requests, e..g

```js
this.get('http://localhost:1337/api/v1/auths', (db, request) => {
  ...
});
```
