### ISSUE TITLE
Period in the route URL is considered part of the dynamic segment

### ISSUE THREAD

**Issue by dwickern** [samselikoff/ember-cli-mirage#296]
I'm modeling a URL which looks like this: `/posts/123.json`

Following the documentation I created this route:
```
this.get('/posts/:id.json', function(db, request) {
  var id = request.params.id;
  return db.posts.find(id);
});
```
(I can't use shorthands because they wrap the responses)

I expected this to parse as `/posts/:{id}.json` but it instead parses to `/posts/:{id.json}`
```
this.get('/posts/:id.json', function (db, request) {
  /*
  	request.params looks like this:

  	  { "id.json": "123.json"}
  */
});
```

**Comment by samselikoff** [comment]
I think this is how [route-recognizer](https://github.com/tildeio/route-recognizer) works. You could do something like `/posts/:id` and `let id = request.params.id.replace('.json', '')`, or maybe open an issue over there asking if there's a better way.

**Comment by dwickern** [comment]
Yeah, that's it. route-recognizer is hard-coded to split on slashes and doesn't support regex matching. Oh well.
