### ISSUE TITLE
Error with app that has `baseUrl` defined

### ISSUE THREAD

**Issue by andycrum** [samselikoff/ember-cli-mirage#302]
When trying to setup Mirage, I am consistently getting the error even though all configuration appears to be correct:
```
Mirage: Your Ember app tried to GET '/models', but there was no route defined to handle this request. Define a route that matches this path in your mirage/config.js file.
```

The only thing that fixes this error is changing my config/environment.js `baseUrl` value to `/`, instead of what it is now. It seems to me that `baseUrl` should have no effect on Mirage, but in this case it definitely appears to. Branch this is occurring on [here](https://github.com/andycrum/ember-data-model-maker/tree/6d90e2a5bc611c78207990549f05ec42d3c2b222).

**Comment by MiracleBlue** [comment]
I just ran into the same issue, and it seems that the way to fix it for me was to set my namespace to '/api' in the mirage config.  Before this, I had it set to 'api', which was resolving to a relative url.

I'd recommend trying to set this.namespace = '/'; if you don't already have one set up, and see if that helps :)

**Comment by andycrum** [comment]
@MiracleBlue thanks for the tip. Unfortunately, it didn't seem to make a difference in this case :( have tried every combination of configs I can think of...

**Comment by MiracleBlue** [comment]
@andycrum That is very unfortunate!  Could you share your configuration file with us in a gist?

**Comment by andycrum** [comment]
@MiracleBlue https://github.com/andycrum/ember-data-model-maker/blob/6d90e2a5bc611c78207990549f05ec42d3c2b222/app/mirage/config.js

That branch is the one failing. I've changed it a bit since pushing there, but still have the same top-level `this.get('/models')`, etc.

**Comment by MiracleBlue** [comment]
Looks fine to me.  That's strange that setting the namespace didn't help.  My configuration looks very similar to yours except I have the namespace property which points to '/api' for me, which overrides the baseUrl only when the '/' is at the start of the namespace property.

**Comment by MiracleBlue** [comment]
Sorry I can't be of more help :( hope you figure out what's going on!

**Comment by andycrum** [comment]
@MiracleBlue your comment pointed me in the right direction. I set `this.urlPrefix = '/';` and everything is working now. haha.

@samselikoff it looks like it's an issue with the logic in this function: https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/server.js#L197. I haven't looked that far into the root cause yet, but I was able to debug and found that Mirage was registering `models` as the route instead of `/models`. No idea if this is related to the `baseUrl` thing or not. Actually very curious how no one else ran into this, unless everyone happens to have a `urlPrefix` defined

**Comment by MiracleBlue** [comment]
Ah interesting!  I certainly don't have a urlPrefix defined as far as I can tell.  If I run into the same situation where my namespace isn't overriding the baseUrl in the future this will be very useful to know.

**Comment by samselikoff** [comment]
If true this is definitely a bug. A failing test would be great help!

**Comment by acorncom** [comment]
@andycrum @MiracleBlue Anything additional we should fix here now that `baseURL` has been removed in Ember-CLI?  If not, I'd like to close this issue as we're trying to get the issue tracker into a more reasonable state so we can see the issues that are still outstanding 😀

**Comment by rwwagner90** [comment]
@acorncom @andycrum @MiracleBlue what are we supposed to set now that `baseURL` is gone? I tried setting `this.urlPrefix = '/';` and that did not seem to help. Please advise!

**Comment by acorncom** [comment]
@rwwagner90 There's a new issue at #901, I'm unclear on the issue so probably best to watch that issue
