### ISSUE TITLE
Using the faker.address.city method in factories fails at sequences greater than 4

### ISSUE THREAD

**Issue by MiracleBlue** [samselikoff/ember-cli-mirage#306]
I'm using faker.address.city as one of the properties in my model factory (for a location) and tried generating 100 of them.  Each time, the first 4 get populated, but all after that return 'string parameter is required!'.  I did some stepping in the debugger and it appears that when Mirage calls the faker method, it passes a sequence number as the first argument, and it seems that this particular faker method expects an index for its formatting options rather than a sequence number.  There are only 4 possible formatting options for this method, so when it gets passed an index of 4 and above and can't find that index in the formatting array, it errors and returns 'string parameter is required!'

**Comment by samselikoff** [comment]
It does, we should really update the guides to just use an anonymous function:

This should work:

```js
// app/mirage/factories/user.js
import Mirage, {faker} from 'ember-cli-mirage';

export default Mirage.Factory.extend({
  fullName() {
    return faker.address.city();
  }
});
```

**Comment by MiracleBlue** [comment]
Ah excellent, I ended up doing something similar, but this is much nicer.  Appreciate it!
