### ISSUE TITLE
Polymorphic Relationships in acceptance tests

### ISSUE THREAD

**Issue by philipdesmedt** [samselikoff/ember-cli-mirage#308]
Hi there,

First of all, great library! Saved us a ton of time mocking everything.

We're running into an issue with polymorphic relationships and ember-data though. This is the situation:

Step model:
```
DS.Model.extend({
  unit: DS.belongsTo('unit', { polymorphic: true, async: false }),
  unit_type: DS.attr('string'),
});
```

Unit model:
```
DS.Model.extend({
  bucket: DS.belongsTo('bucket', { async: false })
});
```

Lecture model (this is a unit):
``` 
Unit.extend({
  step: DS.belongsTo('step', { async: false })
});
```

Now, in an acceptance test, we're doing the following:

```
let course = server.create('course', { stage_ids: [1] }),
      stage = server.create('stage', { course_id: 1 }),
      lecture = server.create('lecture', { step_id: 1 }),
      step = server.create('step', { stage_id: 1, unit_type: 'Lecture', unit_id: lecture.id }),
      url = `/studio/courses/${course['id']}/steps/${step['id']}`;
```

Whatever I do though, I cannot get the unit (a Lecture in this case) using `model.get('unit');` in an Ember route or controller (the code with a real API works, the tests with mirage don't).

How should I model a polymorphic relationships in Ember? Am I doing something wrong? I'm just creating factories for each model like in the above code and I hoped the unit would resolve automatically to the right type according to the `unit_type` field. This is unfortunately not happening.

**Comment by samselikoff** [comment]
This does not have first-class support yet, unfortunately. I'll have time to look at this more later, but for now you can do something like

```js
server.create('unit', { step_id: 1, unit_type: 'lecture' });
```

as a temporary workaround. Sorry about the inconvenience!

**Comment by philipdesmedt** [comment]
Thanks for the quick reply!

Unfortunately, this doesn't seem to be working either. `model.get('unit')` is still `null` in the route.
I'm doing the following now:

```
let course = server.create('course', { stage_ids: [1] }),
      stage = server.create('stage', { course_id: 1 }),
      // lecture = server.create('lecture', { step_id: 1 }),
      lecture = server.create('unit', { step_id: 1, unit_type: 'lecture' }),
      step = server.create('step', { stage_id: 1, unit_type: 'lecture', unit_id: lecture.id }),
      url = `/studio/courses/${course['id']}/steps/${step['id']}`;
```

Do I need to create new factories? I have defined Unit, Lecture and Step already... so I can't think of anything. In the route, in `renderTemplate`, I print the following: 

`console.log('new model is', model.get('unit_type'), model, model.get('unit'));`

The result is:
`new model is lecture Class {id: "1", store: Class, container: Container, _internalModel: InternalModel, isError: false…} null`

**Comment by philipdesmedt** [comment]
Also, can I just define the shorthand route `this.get('/steps/:id');` or do I need to add something myself?

**Comment by philipdesmedt** [comment]
FYI - I figured it out after a few hours of searching:

I needed the following:
`let step = server.create('step', { stage_id: 1, unit_type: 'lecture', unit: unit.id })`
(note `unit` instead of `unit_id`)

Not sure why `unit` is working and `unit_id` is not. :)

**Comment by philipdesmedt** [comment]
FYI - this is still not working the way it should..

`let unit = server.create('unit', { step_id: 1, unit_type: 'lecture', wistiaId: '1' });`

This does return the right `unit` now, but the `wistiaId` property is always `null`. Any clues?

**Comment by samselikoff** [comment]
Should it be `wistia_id`? Sorry you've been running into issues, I'll have some time to look at this tonight.

**Comment by philipdesmedt** [comment]
It's not `wistia_id`. We have a Rails backend and use ActiveModelSerializers and `wistia_id` on the backend is automatically camelCased to `wistiaId` on the front-end afaik. In any case, I just tried `wistia_id` as well, and it gives me `undefined` :/

Thanks for the help so far. Hopefully we can figure this out :)

**Comment by philipdesmedt** [comment]
FYI - if I write my own `get('step/:id')` endpoint I get the following error:

```
this.get('/steps/:id', function (db, request) {
    let step = db['steps'].find(request.params.id),
        unit = db['units'].find(step['unit_id']);

    step['unit'] = unit;
    console.log(step, unit);

    return {
      step: step
    };
});
```

returning `{ step: step, unit: unit }` doesn't work either. The console log prints the unit with the correct `wistiaId` in this case.

Error:
Assertion Failed: Ember Data expected a number or string to represent the record(s) in the `unit` relationship instead it found an object. If this is a polymorphic relationship please specify a `type` key. If this is an embedded relationship please include the `DS.EmbeddedRecordsMixin` and specify the `unit` property in your serializer's attrs object. Error: Assertion Failed: Ember Data expected a number or string to represent the record(s) in the `unit` relationship instead it found an object. If this is a polymorphic relationship please specify a `type` key. If this is an embedded relationship please include the `DS.EmbeddedRecordsMixin` and specify the `unit` property in your serializer's attrs object.

**Comment by philipdesmedt** [comment]
@samselikoff sorry to bother you, but do you have any clue or an idea what we could do here? :)

**Comment by samselikoff** [comment]
Sorry about the delay, had a busy week!

There's a lot going on here. Can you be specific about the exact API response you're expecting, and the response you're getting now, and we can work from there?

**Comment by philipdesmedt** [comment]
Sorry for the late reply!

I started tracking the exact responses in my Chrome Network tab, and used these to build up the dynamic responses in my mocked Mirage API, and it works now! Thanks a lot for the help and putting me in the right direction of looking at my actual API responses :)

This can be closed.

**Comment by dodeja** [comment]
@philipdesmedt Hey - curious to hear more about your implementation on the Mirage side. 
On ember I have mode's setup like this.
```
// Notifications Model (with polymorphic relationship) 
export default DS.Model({
  subject: DS.belongsTo('subjectable', { polymorphic: true })
});
``` 
```
// Subjectable Mixin
export default Mixin.extend( {
  notifications: DS.hasMany('notification'),
)};
```
```
// Booking model
export default Model.extend(Subjectable, {
  notifications: DS.hasMany('notification'),
)};
```

How would I represent subjectable mixin inside Mirage?
