### ISSUE TITLE
Shorthand PUT request behaves differently from default expanded behaviour

### ISSUE THREAD

**Issue by Arkham** [samselikoff/ember-cli-mirage#312]
Hello there, me again :D 

I have noticed that the PUT shorthand behaviour

`this.put('/contacts/:id');`

behaves differently from the default expanded version

```js
this.put('/contacts/:id', function(db, request) {
  var id = request.params.id;
  var attrs = JSON.parse(request.requestBody)['contact'];
  var record = db.contacts.update(id, attrs);

  return {
    contact: record
  };
});
```

In my use case, I have configured the mirage factory to be something like this:

```js
import Mirage, { faker } from 'ember-cli-mirage';

export default Mirage.Factory.extend({
  advisor_availability: null
});
```

But if I console.log the response from the shorthand PUT handler I get something like this:

```js
{
  interaction: {
     advisorAvailability: null,
     advisor_availability: "Today"
   }
}
```

I dug a bit around the codebase and it looks to me that the culprit is this line: https://github.com/samselikoff/ember-cli-mirage/blob/8500379c28fef7a21881ee51a1e434dd73036600/addon/route-handlers/shorthands/base.js#L71

Should I be using camel case for my models instead?

Thanks!

**Comment by samselikoff** [comment]
Indeed, good finding. `getAttrsForRequesrt` is a standardized version, meant for the ORM. These should default to using `getJsonBodyForRequest`.

Fix in shortly. Thank you so much for reporting these, *super* helpful!

**Comment by samselikoff** [comment]
Also, lesson learned - tests should always have multi-word examples in them ^_^

**Comment by samselikoff** [comment]
0.1.11 cut

**Comment by Arkham** [comment]
Woah, thank you for fixing this so promptly! Everything works perfectly now :)
