### ISSUE TITLE
Irregular inflector not being honored

### ISSUE THREAD

**Issue by tomoguisuru** [samselikoff/ember-cli-mirage#313]
I have an initializer that was working with v0.1.6

```
import Ember from 'ember';

export function initialize(/* registry, application */) {
    Ember.Inflector.inflector.irregular('campus', 'campuses');
}

export default {
  name: 'inflections',
  before: 'ember-data',
  initialize: initialize
};
```

Since updating to v0.1.11, I've been getting the following warning 
`WARNING: Encountered "campuses" in payload, but no model was found for model name "campuse" (resolved model name using app@serializer:campus:.modelNameFromPayloadKey("campuses"))`

I've tried moving the inflector around in the code and changing the before to 'ember-cli-mirage' but haven't had any luck with getting it to work

**Comment by samselikoff** [comment]
Can I see your `config.js`? For now, you could write out the route handler yourself:

```js
this.get('campuses/:id', (db, request) {
  let id = request.params.id;
  return {
    campus: db.campuses.find(id)
  };
});
```

**Comment by tomoguisuru** [comment]
I already have a route handler for campuses
```
  @get('/campuses/:id', (db, request) ->
    params = request.queryParams

    results = simpleSearch(db, 'campus', params, customMetaData.campuses)
    results = pageResults(results, 'campus', params)

    return results
  )
```

the issue is when I return campuses as sideloaded data like so


```
  @get('/rooms/:id', (db, request) ->
    params = request.queryParams

    results = simpleSearch(db, 'rooms', params, customMetaData.campuses)
    results = pageResults(results, 'rooms', params)

    return results
###
{
   "rooms":[
      {
         "name":"Bettye Hoeger",
         "description":""
         "id":1
         "campus_id": 1
      }
   ],
   "campuses":[
      {
         "name":"Stephany Veum",
         "address":"81274 Nienow Locks",
         "id":1
      }
   ]
}
###
```

**Comment by samselikoff** [comment]
Are you saying mirage is causing a bug on the ED side, or that the payload returned by mirage is wrong?

**Comment by tomoguisuru** [comment]
sorry, I just realized the warning I posted in was for the base object, here is the warning for the child
` WARNING: Encountered "campuses" in payload, but no model was found for model name "campuse" (resolved model name using app@serializer:room:.modelNameFromPayloadKey("campuses"))`

**Comment by tomoguisuru** [comment]
the payload is correct, it isn't resolving correctly anymore

**Comment by tomoguisuru** [comment]
basically, Mirage is resolving correctly when using the server calls,
```
server.create('campus')
```
and 
```
db.campuses
```
work just fine but if `campuses` is included the retuned results, I get the error and then the promise will not resolve

**Comment by tomoguisuru** [comment]
I found that including `Ember.Inflector.inflector.irregular('campus', 'campuses');` in the app/app.js file will fix the issue but it doesn't seem like the correct solution since this should already be taken care of in the initializer

**Comment by tomoguisuru** [comment]
@samselikoff any ideas on what might have changed between 0.1.6 and 0.1.11 that would require the extra inflector declaration in the app.js file?

**Comment by samselikoff** [comment]
Yes it looks like it was this commit: https://github.com/samselikoff/ember-cli-mirage/commit/fe47139538905f80a29c6a9623f46b1328858191#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

There was a related issue here: https://github.com/samselikoff/ember-cli-mirage/issues/221

I can take a look at this later, I think we should probably add a separate spot to configure inflector in mirage-land. Right now mirage knows absolutely nothing about your ember app, I think it should probably stay that way.

**Comment by ballPointPenguin** [comment]
Mirage is honoring my custom inflectors after following the suggestion here:
https://github.com/samselikoff/ember-cli-mirage/issues/265#issuecomment-142059544
and loading my inflector initializer before ember-cli-mirage

**Comment by tomoguisuru** [comment]
@samselikoff I think that would be great to add a location to put all that customization.

**Comment by davekaro** [comment]
I think the problem is using an initializer to define the inflector stuff. See the latest guides here - https://guides.emberjs.com/v2.3.0/models/customizing-adapters/#toc_pluralization-customization that recommend using app/app.js anyways.

**Comment by ballPointPenguin** [comment]
I have since removed my initializer and adapted what @davekaro points out the Ember Guides now suggest by using app.js and everything seems to be working.

FYI I'm using this in an Ember 1.13 project (even though the guide above is for 2.3)

**Comment by Glennvd** [comment]
Ran into the same issue, @davekaro's solution worked for me on 1.12 as well, with the small adaptation that you have have to use 

`import Ember from 'ember';

const inflector = Ember.Inflector.inflector;`

Instead of `ember-inflector`

**Comment by coachTomato** [comment]
I have a similiar issue in my project since I added Ember CLI Mirage 0.1.11. I use Ember CLI 2.4.0 and Ember Data 2.4.0. I have a model "eventprofiles" with inflector irregular definition and I get the WARNING: Encountered "eventprofiles" in payload, but no model was found for model name "eventprofile" . My irregular definition is ignored.
```
// models/eventprofiles.js
import Ember from 'ember';
import DS from "ember-data";

Ember.Inflector.inflector.irregular( 'eventprofiles', 'eventprofiles' );

export default DS.Model.extend( {

    displayName: DS.attr( "string" ),
    version: DS.attr( "number" ),
    previewProfiles: MF.fragmentArray( "profile", { defaultValue: [] } ),
    nodeTemplates: DS.attr()
} );
```
I tried to apply https://guides.emberjs.com/v2.3.0/models/customizing-adapters/#toc_pluralization-customization that was mentioned above. But it didn't help in my case.

However I could add a serializer eventprofiles.js, which works for me 
```
// serializers/eventprofiles.js
import DS from "ember-data";

export default DS.RESTSerializer.extend( {
    isNewSerializerAPI: true,
    modelNameFromPayloadKey: function( root ) {
        if( root === "eventprofiles" ) {
            return "eventprofiles";
        }
        return this._super();
    }
} );
```
However I guess not the most elegant way ... I checked again, but I am sure that the problem occurs after adding ember  cli mirage. Without I do not need to set up the serializer. Any idea how to get the inflector work in the usual way?

**Comment by samselikoff** [comment]
This is working now, with https://github.com/samselikoff/ember-cli-mirage/pull/817 and following the current Ember.js guides for specifying irregular inflection.

**Comment by coachTomato** [comment]
Thank you for solving this! 👍
