### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by tomoguisuru** [samselikoff/ember-cli-mirage#314]
There is a documentation error on the routes docs, http://www.ember-cli-mirage.com/docs/v0.1.x/routes/, seen here https://www.dropbox.com/s/tzcesz8nwz0zavl/Screenshot%202015-10-14%2011.54.55.png?dl=0

`this.urPrefix = 'https://my.api.com';` should be `this.urlPrefix = 'https://my.api.com';`

**Comment by samselikoff** [comment]
Thank you! This looks like an easy fix - would you mind helping me out and mind opening a PR? Just click the "Improve this page" button on the top of that doc, fix the typo, then click the green button. What do you think?

**Comment by tomoguisuru** [comment]
done
