### ISSUE TITLE
Multi-part form data passthrough fails

### ISSUE THREAD

**Issue by justin-hackin** [samselikoff/ember-cli-mirage#316]
The following document tests that the api is working normally:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<input type="file" name="aFile" id="input">
<script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
<script>
    $('#input').on('change',function(evt) {
        var formData = new FormData();
        var input = evt.target;
        formData.append(0,input.files[0]);
        debugger;
        $.ajax({
            type: "POST",
            url: "http://api.debian-vm/layoutbooks/imageupload",
            data: formData,
            cache: false,
            contentType: false,
            processData: false,
            headers: {
                "X_UPLOAD_IMAGE_ASSET_NAME": 'someName',
                "X-upload-image-asset-name": 'someName',
                "X_UPLOAD_IMAGE_ASSET_ID": 'someID',
                "X-upload-image-asset-id": 'someID',
            }
        }, function(data, textStatus, jqXHR) {
            debugger;
        });
    });

</script>
</body>
</html>
```

Given multiple ember apps running mirage (v0.1.11), inserting the input element via Chrome inspector and adding the event handler through the console, the initial OPTIONS request passes but the following POST request fails with "400 (Bad Request)".  Comparing the requests, I can see that the ember app POST request has "Content-Type:text/plain;charset=utf-8" wheras normally it is something like : "Content-Type:multipart/form-data; boundary=----WebKitFormBoundaryIpXCvBDCghXr5iTO" so it would seem the passthrough is muddling the request in some way.  I also tried cut/pasting the code into a non-mirage ember app and it still seems to work.  Sorry I can't provide an example with a working api as that one is running locally but hopefully this will help you make some sense of this.  

P.S.  Though this is not urgent, your attention would be greatly appreciated.  Thanks a lot for making such a useful contribution to ember community :+1:

**Comment by samselikoff** [comment]
Thank you for the kind words :)

What does your current POST mock look like in Mirage? Could you start with something simple, like ignoring the data altogether and just returning a 201?

```js
this.post('http://api.debian-vm/layoutbooks/imageupload', {}, 201);
```

**Comment by justin-hackin** [comment]
There is no post mock for this endpoint.  Why would I need one when my imageupload api works otherwise ?

**Comment by samselikoff** [comment]
I see, so you're saying it's basically not working? The request is not being passed through?

**Comment by justin-hackin** [comment]
The request is passed through but it is not the same as it is ordinarily (see inline comments at >>>>>>)
```
General:
Remote Address:192.168.56.101:80
Request URL:http://api.debian-vm/layoutbooks/imageupload
Request Method:POST
Status Code:400 Bad Request

Response Headers
view source
Access-Control-Allow-Origin:*
Connection:close
Content-Length:67
Content-Type:application/json
Date:Thu, 22 Oct 2015 20:53:52 GMT
Server:Apache/2.2.22 (Debian)
Set-Cookie:PHPSESSID=d9nub0p3h5ert6otd6q7bgtf25; path=/
X-Pad:avoid browser bug

Request Headers
view source
Accept:*/*
Accept-Encoding:gzip, deflate
Accept-Language:en-US,en;q=0.8,it;q=0.6
Connection:keep-alive
Content-Length:5204
Content-Type:text/plain;charset=utf-8  >>>>>>>>>>>> this should be multipart/form-data; boundary=-----WebKitFormBoundaryzRvee2NwIFVAHaxE
Host:api.debian-vm
Origin:http://localhost:4200
Referer:http://localhost:4200/layout-book/FD578D5F-09EF-4B99-9BEB-AA63E4630AD5/1
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36
Request Payload
------WebKitFormBoundaryzRvee2NwIFVAHaxE
Content-Disposition: form-data; name="file"; filename="xmark_red.svg"
Content-Type: image/svg+xml


------WebKitFormBoundaryzRvee2NwIFVAHaxE
Content-Disposition: form-data; name="needsThumbnail"

true
------WebKitFormBoundaryzRvee2NwIFVAHaxE--

```

**Comment by justin-hackin** [comment]
I realized this may be a bug with pretender and not your lib ...

**Comment by foxzool** [comment]
hey,  i got this bug too,   content-type is always text/plain;charset=utf-8

**Comment by samselikoff** [comment]
Strange. I'd love some help tracking this down. Is it Pretender? Mirage?

**Comment by beerlington** [comment]
I just ran into this and it turned out to be an issue with FakeXMLHttpRequest that has been [resolved](https://github.com/pretenderjs/FakeXMLHttpRequest/pull/20). Upgrading Pretender to 0.12.0 fixed it so you can probably close this.

**Comment by samselikoff** [comment]
Nice, thanks for the note!
