### ISSUE TITLE
How do I disable/uninstall mirage, so that I can use something else?

### ISSUE THREAD

**Issue by christopherdumas** [samselikoff/ember-cli-mirage#317]

**Comment by samselikoff** [comment]
Could you elaborate? You can use the [passthrough api](http://www.ember-cli-mirage.com/docs/v0.1.x/server-configuration/#passthrough) to tell Mirage to selectively ignore certain requests. If you want to remove Mirage completely, remove the corresponding entry from your `package.json` and delete the directory from `node_modules`.
