### ISSUE TITLE
Share factories with development environment?

### ISSUE THREAD

**Issue by samselikoff** [samselikoff/ember-cli-mirage#32]

**Comment by rondale-sc** [comment]
I'd imagine this would be quite useful under certain circumstances.  Either allowing creation of entries with factories via the terminal or some init script that would bootstrap some factory info on intial load of the app.  

Could help flesh out things like overflows and the like when using factories to generate lorem (or something).

**Comment by samselikoff** [comment]
Yep I want to use faker JS for fake data and, I want to have a /scenarios
folder for different bootstrap files t make it easy to switch your server
data

**Comment by seawatts** [comment]
Does https://github.com/samselikoff/ember-cli-mirage/commit/6c4ff5dc6985efec254c0012d5d6b2cc9021688e close this?

**Comment by samselikoff** [comment]
yep yep

**Comment by seawatts** [comment]
:smile: :+1:

**Comment by samselikoff** [comment]
looove closin me some issues :stuck_out_tongue_closed_eyes:

**Comment by seawatts** [comment]
lol =P
