### ISSUE TITLE
Mirage is intercepting asset requests

### ISSUE THREAD

**Issue by benoittgt** [samselikoff/ember-cli-mirage#327]
Hello

I had [previously issue to mock the proper request](https://github.com/samselikoff/ember-cli-mirage/issues/326), but it's now nearly fixed.

I'm using ember-cli-rails. 

When I run my test I got `application.js:13 Uncaught ReferenceError: I18n is not defined` : 

```
Acceptance | user list: visiting /users (2, 0, 2) 60152 ms
Uncaught ReferenceError: I18n is not defined@ 165 ms
Source:     
http://localhost:7357/assets/front.js:309
Test timed out
```

So I add to my `config.js` 

``` javascript
this.pretender.get('http://localhost:7357/assets/**', this.pretender.passthrough);
```

But I still have this new error. It's strange because `http://localhost:7357/` is my ember-test running

**Comment by alexmasita** [comment]
Would like to also upvote this issue.

**Comment by benoittgt** [comment]
@alexmasita I've finally move my translation code to ember. i18n is now not anymore with [i18njs](https://github.com/fnando/i18n-js) but with [ember-18n](https://github.com/jamesarosen/ember-i18n). 

If you have error like this one, you should check how to run test if you're using ember-cli-rails but especially add dependencies to `test/index.html`.

**Comment by benoittgt** [comment]
For me it can be close.
