### ISSUE TITLE
Update docs on POST shorthand

### ISSUE THREAD

**Issue by ivanvotti** [samselikoff/ember-cli-mirage#330]
Regarding to [the documentation](http://www.ember-cli-mirage.com/docs/v0.1.x/shorthands/#post-shorthands), this `this.post('/invoices');` should generate a route handler like this:

```js
  this.post('/invoices', function(db, request) {
    var attrs = JSON.parse(request.requestBody);
    var record = db.invoices.insert(attrs);
    return { invoice: record };
  });
```

When I have `this.post('/invoices');` in the `config.js`, I expect to get an invoice object like this after a post request:

```js
{
  id: 1
  amount: "100.00",
  currency: "USD"
}
```

Instead, I get:

```js
{
  id: 1
}
```

But if I define the post route manually in `config.js` like this:

```js
  this.post('/invoices', function(db, request) {
    var attrs = JSON.parse(request.requestBody);
    var record = db.invoices.insert(attrs);
    return { invoice: record };
  });
```

After that, everything works as it should. Why there's a difference?

**Comment by samselikoff** [comment]
Definitely seems ilke a bug. Are you on master, or a particular version?

**Comment by ivanvotti** [comment]
I'm on `0.1.11`

**Comment by samselikoff** [comment]
I just tried to recreate this and couldn't. Are you sure your app is sending the payload? It looks like it from your example. Any chance you could recreate a small test case I can look at?

**Comment by ivanvotti** [comment]
I'm sure my app sends correct payload. I turned on logging by `server.logging = true;` and can see that when the route defined with the shorthand I Mirage sends back payload that contents `id` only. When I use the full route definition like in my example above, Mirage sends a payload that has all attributes I expect. I'll try to make a test case.

**Comment by samselikoff** [comment]
Also you could put a debugger here https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/route-handlers/shorthands/post.js#L19 and see what the `attrs` is

**Comment by ivanvotti** [comment]
Exactly in that point locals are:
```js
{
  attrs: undefined,
  collection: "invoices",
  db: undefined,
  dbOrSchema: Db,
  model: undefined,
  payload: {amount: "100.00", currency: "PHP"},
  amount: "100.00",
  currency: "PHP",
  string: "invoice",
  type: "invoice",
  // ...
}
```

So `attrs = payload[type]` returns `undefined`, because the `payload` is `{amount: "100.00", currency: "PHP"}`. But [the docs example](http://www.ember-cli-mirage.com/docs/v0.1.x/shorthands/#post-shorthands) doesn't do anything like this `attrs = payload[type]`.

**Comment by ivanvotti** [comment]
Looks like the current post shorthand implementatioin expects the payload to look like:
`{ type: { attr1: 'value', attr2: 'value'} }`

But the documentation example expects something like this: `{ attr1: 'value', attr2: 'value'}`

**Comment by samselikoff** [comment]
Yes yore correct, the docs are incorrect. So sorry, will fix this. Also,
the upcoming serializers will let you write a simple normalize method so
you can still use the short hands.
