### ISSUE TITLE
Investigate serializer lookup issue

### ISSUE THREAD

**Issue by samselikoff** [samselikoff/ember-cli-mirage#334]
this didn't work `this.get('/auction_results');`

whereas this did:

```
this.get('/auction_results', (schema/*, request*/) => {
  return schema.auctionResult.all();
});
```

**Comment by xcambar** [comment]
It may be specific to multiple-word routes/models.

I has no trouble with a `/team` route and a `Team` model on 0913545.

**Comment by samselikoff** [comment]
f95aa53262164953f70c970812d8462aa13feab2 closes
