### ISSUE TITLE
Reminder to 'create Object' in json api documentation?

### ISSUE THREAD

**Issue by benoittgt** [samselikoff/ember-cli-mirage#347]
Hello

I'm wondering if telling the user to don't forget to generate content of factories ( like `server.createList('user', 2);`) in the test when speaking about [working with json api](http://www.ember-cli-mirage.com/docs/v0.1.x/working-with-json-api/) is a good idea ? Or completely useless.

Thanks in advance.

**Comment by samselikoff** [comment]
Good suggestion! But I think I'll punt since I'm focused on 0.2.x docs, and when that lands this section won't really be relevant anymore.

Thank you :)

**Comment by benoittgt** [comment]
Ok Sam, thanks.
