### ISSUE TITLE
Consider dropping unnecessary "cli"

### ISSUE THREAD

**Issue by ef4** [samselikoff/ember-cli-mirage#353]
As you're considering breaking changes for 2.0, think about whether `ember-cli` is really a useful prefix. `ember-mirage` is just as specific as `ember-cli-mirage`, and whatever perceived difference there is between `ember` and `ember-cli` is only going to get smaller over time.

**Comment by samselikoff** [comment]
I remember asking @rwjblue about this when I started. He said `ember-cli-` was the convention for addons that utilized the build tools side of things, whereas `ember-` addons would be things directly related to Ember itself (e.g. an Ember component).

@rwjblue, has your stance on this changed? I don't have a strong personal preference here, I just want to align with the community.

**Comment by rwjblue** [comment]
No, I still follow the same rules you have described above, but to me the current state of mirage seems to be 99% browser side.  I could be totally wrong about that though...

**Comment by samselikoff** [comment]
It is completely browser side, but it also has nothing to do with Ember. None of the code under `/addon` uses anything from Ember at all (besides string utils), so my reasoning was that since the addon exists primarily for the build-time wiring, it should be `ember-cli-`.

Happy to move to `ember-mirage` if that feels better to peeps!

**Comment by ef4** [comment]
I didn't mean to reopen a discussion if it had already been thought out. Happy either way. I just have a default reaction in favor of shorter names.

**Comment by lukesargeant** [comment]
Perhaps the rule of thumb could be things that you want to add to the app's code in production, like modals, functional libs and custom components are ember-... and addons that you only use during development are ember-cli-... Seeing as this is intended for development I'd put it under the ember-cli umbrella. Perhaps...

**Comment by samselikoff** [comment]
Closing for now.
