### ISSUE TITLE
Correctly serialize empty array reponses

### ISSUE THREAD

**Issue by ef4** [samselikoff/ember-cli-mirage#368]
This is a followup to https://github.com/samselikoff/ember-cli-mirage/pull/361

We carry type information along as a property on Collection, so we can properly serialize an empty Collection. But the same is not true for an empty Array, and I think that's a useful case to support.

As a workaround in my app, I'm doing:

```js
  this.get('/api/v1/articles', function(schema, request) {
    let pattern = searchPattern(request);
    return new Collection('article', schema.article.all().filter(a => pattern.test(a.title)));
  });
```

While we can try to enrich the Collection API so that people never escape it, it's likely to remain a potential pitfall. I think we can do similar wrapping automatically.

**Comment by samselikoff** [comment]
How would this work, in your example? i.e. how would we ensure `type` was carried along to the return value of your `filter` function? Could we just have `typeForCollection` delegate to the type of the 0th-indexed model, if a `type` property is not found?

How does Rails deal with this?

As you stated I already plan to add support for a filtering function to `where`, which would solve the use case you have here.

**Comment by ef4** [comment]
Instead of trying to carry along `type` inside the user's function route-handler, I would solve the problem higher up the stack. We already have code for detecting the type based on the request, as used in the shorthand route handlers. So if the user returns an ambiguously-typed array, we could re-upgrade it to a Collection automatically using the type derived from the URL.

**Comment by samselikoff** [comment]
Interesting approach...is that a bit presumptuous? We detect type based on request but only for shorthands. So far the assumption has been if you write a custom route handler, anything is fair game. You can return anything you want from there, and it will just pass through the serialization layer. This is how rails controllers work, no inference based on the request alone.

**Comment by ef4** [comment]
It is definitely more opinionated. It seems ok to me because users would still retain the same ability they have now to signal type information: they can return a Model, a Collection, or an array containing a Model, and in any of those cases we won't override their decision. We would only apply a default type when they give us something completely ambiguous, like `[]`.

**Comment by samselikoff** [comment]
Ah I see, only apply if the return value is not explicitly Model or Collection. Only thing here was, I kind of wanted to retain the ability for users to just be able to return POJOs/POJAs from their route handler, and have those only pass through the single Application serializer so things don't get confusing. I'll think more about this.

**Comment by ef4** [comment]
The application serializer would have been sufficient in my situation.

So arguably the bug is just that we don't default to applying the
application serializer in these ambiguous cases. (I was getting no
serializer at all.)

**Comment by bekzod** [comment]
I don't know if it right solution or not, what if function handler will accept option for example `collection` or something like that and turns it into Collection 

```javascript
 this.get('/api/v1/articles', function(schema, request) {
    let pattern = searchPattern(request);
    return schema.article.all().filter(a => pattern.test(a.title);
  }, { collection: true });
```

**Comment by samselikoff** [comment]
That's a possibility, but won't be necessary once #450 is implemented. `article.all` would return a collection and so would `filter`, so the correct serializer would be used. I think I prefer that solution.

**Comment by samselikoff** [comment]
#477 closes
