### ISSUE TITLE
server.create should create blank model if no factory exists

### ISSUE THREAD

**Issue by samselikoff** [samselikoff/ember-cli-mirage#371]

**Comment by jherdman** [comment]
Is the thought here to just return a blank copy of the base model and issue a warning, or to "just work" even if the user opts to not implement a factory forever?

**Comment by samselikoff** [comment]
I think it should create a blank copy of the base model. Basically, `server.create('blog-post')` should first check for a factory, and if none exists just delegate to `schema.blogPost.create()`.
