### ISSUE TITLE
Ember server fails on ember-cli-mirage#master with "TypeError: Cannot read property 'path' of undefined"

### ISSUE THREAD

**Issue by alecho** [samselikoff/ember-cli-mirage#374]
I was going to test out the new changes in master when, after installing the `master` branch, I got this message from `$ ember server`
```
Future versions of Ember CLI will not support v4.2.1. Please u
pdate to Node 0.12 or io.js.
version: 1.13.8
Cannot read property 'path' of undefined
TypeError: Cannot read property 'path' of undefined
    at Class.module.exports.treeForAddon (/projects/openworks-
status-page/node_modules/ember-cli-mirage/node_modules/ember-l
odash/index.js:11:74)
    at Class._treeFor (/projects/openworks-status-page/node_mo
dules/ember-cli/lib/models/addon.js:330:31)
    at Class.treeFor (/projects/openworks-status-page/node_mod
ules/ember-cli/lib/models/addon.js:300:19)
    at /projects/openworks-status-page/node_modules/ember-cli/
lib/models/addon.js:253:32
    at Array.map (native)
    at Class.eachAddonInvoke (/projects/openworks-status-page/
node_modules/ember-cli/lib/models/addon.js:251:22)
    at Class.treeFor (/projects/openworks-status-page/node_mod
ules/ember-cli/lib/models/addon.js:298:20)
    at Class.module.exports.treeFor (/projects/openworks-statu
s-page/node_modules/ember-cli-mirage/index.js:39:32)
    at EmberApp.<anonymous> (/projects/openworks-status-page/n
ode_modules/ember-cli/lib/broccoli/ember-app.js:358:20)
    at Array.map (native)
```

**Comment by samselikoff** [comment]
looks like you're on an old version of node, can you update?

**Comment by alecho** [comment]
Upgraded to node 4.2.2 and 5.0.0 with no luck (same error message). I blew away `node_modules/` and cleared npm's cache before rerunning `npm install`.

**Comment by alecho** [comment]
Just tried with Node 0.12.7 as well with the same results.

**Comment by samselikoff** [comment]
Try 'ember g ember-cli-mirage' to make sure you have all the deps

**Comment by alecho** [comment]
That did it. Wow that's weird. I wonder if I was having network issues or something last night. Do you have any idea what would have caused it?

**Comment by samselikoff** [comment]
I think when you upgrade you need to run the generator, just in case something else needs to be installed. Perhaps a bower dependency didn't get added to your bower.json, so that's why something was missing.

It would be nice if there were an `ember upgrade` command that did this for addons.
