### ISSUE TITLE
Capitalize registered models that hang off of schema

### ISSUE THREAD

**Issue by samselikoff** [samselikoff/ember-cli-mirage#375]
Currently, you access models that are registered to `schema` like so:

```js
this.get('/blog_posts', (schema, request) => {
  return schema.blogPost.all();
});
```

`blogPost` here is really a class, not an instance, so perhaps it should be capitalized:

```js
this.get('/blog_posts', (schema, request) => {
  return schema.BlogPost.all();
});
```

That looks a little strange, but with some destructuring it becomes pretty nice:

```js
this.get('/blog_posts', ({BlogPost}, request) => {
  return BlogPost.all();
  // BlogPost.find(1) etc.
});
```

which of course works with multiple classes too:

```js
this.get('/some-things', ({BlogPost, Author, Comment}, request) => {
  ...
});
```

Thoughts?

**Comment by lukemelia** [comment]
I lean toward capitalizing it.

**Comment by ryanto** [comment]
I like capitalizing as well. Deconstruction looks great.

**Comment by mitchlloyd** [comment]
> blogPost here is really a class, not an instance

I think I know what you mean: conceptually the user created a `BlogPost` class that extended from `Model`. However, I feel this proposed naming cultivates an incorrect mental model. `schema.blogPost` is not the model class that the user created. That model class has no static methods and if the user tried to add one to their class, it would not be available here. As of today, [technically `blogPost` is a POJO](https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/orm/schema.js#L67-L75), and not something you would create an instance of.

The proposal might be driven by a desire to make Mirage look more Rails-like. However I feel that the Rails convention of model classes that represent collections of their instances is problematic. Better to have a collection object (which is exactly have Mirage has!). It's interesting to look at the progression of Ember Data which [used to cargo cult this Rails precedent](https://github.com/emberjs/data/blob/v0.13/packages/ember-data/lib/system/model/model.js#L484) but somehow managed to break free :confetti_ball:. 

My vote is for the API that we already have for `db`: `db.blogPosts`, `db.authors` and `db.comments`. This has helped me understand how to use Mirage and I have a nice time explaining it to people that are new to the library: "The database has a collection for each of our models".

**Comment by samselikoff** [comment]
How providential - I am literally working on this issue right now as the next item in my backlog, and am about halfway wrapped up. Thanks so much for posting your thoughts.

Earlier today I spent some time thinking through this again, to see if the breaking change was worth it. Ultimately I came to the same decision, that capitalizing felt more natural:

```js
let post = schema.Post.first();
```

versus

```js
let post = schema.post.first();
```

The latter feels a bit wrong and like it would be hard to explain to newbies - "that `post` is different than the other `post`" - whereas the capitalized ModelClass is a clear visual differentiator - "any method off of `Post` returns `post` instances". But maybe I'm wrong, and the former is straightforward enough to explain to newbies.

But, I find your points compelling. I'd really like to get this as right as possible, as I want to lock down the API after 0.2.0 and release a 1.0 soon after. I want to think about this a bit more, and maybe we can get some more input from the community.

Of course, we could also emulate ED and do `schema.createRecord('post')`. But I thought this would be even more confusing, as already there's been confusion about what purpose Mirage's ORM serves vs. ED.

**Comment by mitchlloyd** [comment]
> How providential - I am literally working on this issue right now as the next item in my backlog, and am about halfway wrapped up. 

Haha! I must have felt a disturbance in the OO force that compelled me to comment on this issue :smile: 

Just wanted to be clear that I was preferring the plural of the model name: `schema.posts` over both `schema.post` and `schema.Post`. So your example would become.

```javascript
let post = schema.posts.first();
```

If I can use that API, then I might just go back to calling `schema` `db`. Using this pluralized API may even lead to less breakage from 0.1.x to 0.2.0.

I agree that using `Post` will feel "natural" for Rails developers, they will immediately understand how the API should work and it will put them in the mindset of building a backend server. Despite this benefit, I don't feel that continuing this Rails convention is worth it, but I also would like to hear from others.

**Comment by samselikoff** [comment]
Ah, I didn't understand that. So you're saying `schema.posts` to mirror `schema.db.posts` would be a better API, easier conceptually for newbies (each model produces a db collection, and there's a schema collection that wraps it and provides the additional ORM methods etc.) and so on. Not bad.

And then you're saying, just drop the `schema.db.users` vs `schema.users` distinction? So, we'd require everyone to define models for each collection, and then they would never access the raw db? I'm not sure I'm confident enough yet to hide the underlying db api from route handlers.

I also think it's still worth it to have the Collection API, so people can do things like `author.blogPosts` instead of `db.blogPosts.filter(p => p.authorId == author.id)`.

**Comment by mitchlloyd** [comment]
Yep, I think we understand each other. 

With regard to getting rid of the `db` API, I was just noticing that by mirroring the `db` API, some simple routes might not need modification going from 0.1.x to 0.2.x.

```
this.get('/contacts', function(dbOrSchema) {
  return dbOrSchema.contacts;
});

this.get('/contacts/:id', function(dbOrSchema, request) {
  return dbOrSchema.contacts.find(request.params.id);
});
```

Agreed that the new `schema` apis that return models instead of POJOs have a lot of value.

**Comment by samselikoff** [comment]
#607 closes, ended up going with `schema.contacts`.
