### ISSUE TITLE
Anyway to do x===y and/or x===k?

### ISSUE THREAD

**Issue by wayne-o** [samselikoff/ember-cli-mirage#377]
I need to be able to filter results based on something like 

```where {name: 'something || name: 'someotherthing' ```

Appending two arrays doesn't seem to kick it - is there anyway to achieve this currently?

**Comment by samselikoff** [comment]
this is off a schema model class, right? `schema.blogPost.where(...`?

**Comment by wayne-o** [comment]
Not sure if I am using an older v (0.1.11) but yeah db.blogPosts.where(...

**Comment by wayne-o** [comment]
just checked - i'm on the current v :)

**Comment by wayne-o** [comment]
For now I am doing this:
```
let allLineups = [];
let locationNameArray = req.queryParams.locations.split(',');

for (var i = 0; i < locationNameArray.length; i++) {
	let name = locationNameArray[i];
	allLineups = allLineups.concat(db.lineups.where({ location_name: name }));
}
return {lineups: allLineups.map(r => stringify(r))};
```

**Comment by samselikoff** [comment]
yepyep. I have an issue to enhance `where` to take a filtering function, which would let you

```js
.where(lineup => lineup.name == 'something' || lineup.name == 'someotherthing')
```

**Comment by wayne-o** [comment]
:+1:

**Comment by samselikoff** [comment]
a72fd487776a048791db52ed114137842bf074c2 closes. @wayne-o , you should now be able to use a filtering function on `db.where`.
