### ISSUE TITLE
Master branch with `ember cli` creates multiple mirage directories

### ISSUE THREAD

**Issue by alecho** [samselikoff/ember-cli-mirage#380]
Installing master by adding the master branch to package.json and running `ember install ember-cli-mirage` creates multiple `mirage` directories.
<img width="183" alt="screen shot 2015-11-06 at 9 31 35 pm" src="https://cloud.githubusercontent.com/assets/1035853/11013105/5af7d58e-84ce-11e5-96b9-ff850f67f0b8.png">

**Comment by samselikoff** [comment]
The step to upgrade is to add

```
"ember-cli-mirage": "samselikoff/ember-cli-mirage"
```

to your package.json, then run

```
npm install
ember g ember-cli-mirage
```

You can just move anything you need from `/app/mirage` to `/mirage`, and get rid of `/app/mirage`.

**Comment by alecho** [comment]
Something happened which cause my dependency to point to 0.1.11 again. Not sure what cause that exactly but I've got master working in my project for the most part.
