### ISSUE TITLE
Unknown blueprint error when generating a model

### ISSUE THREAD

**Issue by Dhaulagiri** [samselikoff/ember-cli-mirage#381]
The 0.2.x docs [suggest](http://www.ember-cli-mirage.com/docs/v0.2.x/quickstart/#dynamic-mocks) generating models via this shortcut:

`ember g mirage:model foo`

However that results in this error:
```
version: 1.13.8
Unknown blueprint: mirage:model
```

**Comment by samselikoff** [comment]
Thanks!

Don't believe there are namespaced generators so we're stuck with `mirage-model` for now. Master is updated, and I'll update the guides.

**Comment by samselikoff** [comment]
Ok, figured out how to use `:`. Back to `mirage:model`!

**Comment by Oladele** [comment]
Also followed 0.2x install doc for a brand new app, and I'm getting the same "Unknown blueprint: mirage:model" error. I also tried "ember g mirage-model" but got same "Unknown blueprint" error. Per commit history of [sample app](https://github.com/Oladele/mirage-v2-new/commits/master), the exact repro steps are:
`ember new`
`ember install ember-cli-mirage@v0.2.0-beta.1`
`ember g model author`
...So far so good until:
`ember g mirage:model author`
results in error :fire: 
`Unknown blueprint: mirage-model`
Any tips please, anyone ?

**Comment by samselikoff** [comment]
This should be fixed in master

**Comment by irnc** [comment]
@samselikoff https://github.com/samselikoff/ember-cli-mirage/commit/a2b5e321f8840702894a0e1cfeca3616f1b3ee0e, the commit that fixed this issue, actually breaks installation on Windows environment, because directory names could not contain colons there.

**Comment by samselikoff** [comment]
@irnc right- someone else raised this issue too. Looks like we'll need to move back to `ember g mirage-factory`

**Comment by actorius** [comment]
Have the same problem

**Comment by samselikoff** [comment]
@actorius should be fixed in 0.2.0-beta.2, with `ember g mirage-factory`
