### ISSUE TITLE
Tests fail with model definitions

### ISSUE THREAD

**Issue by alecho** [samselikoff/ember-cli-mirage#383]
I added three models to the mirage directory in the dummy app. Some interesting tests fail, although I'm not sure if they are related to my problem I discusses with @samselikoff on slack yesterday.

See https://github.com/alecho/ember-cli-mirage/tree/tests-fail-with-model-defintions

**Comment by samselikoff** [comment]
Thanks for opening this (and sorry for the delay!). I'll check it out before cutting 0.2.0!

**Comment by samselikoff** [comment]
Just cloned that repo and only got one jshint error..you still seeing anything here?

**Comment by alecho** [comment]
Did you check out the `tests-fail-with-model-defintions` branch? It's been awhile and I don't know if I have the same tests failing as before. Here's the two the fail for me:

```
not ok 37 PhantomJS 2.0 - Acceptance: Custom handlers: You can customize the response by passing a handler function that returns the desired body
    ---
        actual: >

        expected: >
            Max depth.,Max depth.
        Log: |
    ...
not ok 40 PhantomJS 2.0 - Acceptance: Custom handlers: returning a non-blank response from a custom handler whose default status is 204 changes the status to 200
    ---
        actual: >
            [object Object]
        expected: >
            [object Object]
        message: >
            The response is correct
        Log: |
    ...
```

This was a result of trying to use mirage for a JSON API mock a couple month ago and I know a lot of work has been done since then so I'll have to give the beta a go and see if I have any issues.

**Comment by samselikoff** [comment]
There are some models in the current test suite and it's passing so I'm going to close this for now. If you are still seeing this in beta.3 or later, we can reopen.

Thank you for opening this issue!

**Comment by alecho** [comment]
Thanks for taking the time to review this. I'll check out Beta 2 or 3 today, if I can get the chance.

**Comment by alecho** [comment]
Beta 3 is working great! Thanks to Sam and everyone for their hard work.
