### ISSUE TITLE
Expose server.build to build new model instances from Factories

### ISSUE THREAD

**Issue by iezer** [samselikoff/ember-cli-mirage#386]
We'd find it useful to add a build function similar to what exists in Factory Girl in Ruby, so for example you could call `var post = server.build('post');` and you get an object with all the properties in the factory without saving it to the DB. Seems like that function already exists [here](https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/server.js#L139), so we just need to expose it.

@samselikoff  Happy to pick this up and submit a PR if you think it's a good idea.

CC @tundal45

**Comment by jherdman** [comment]
That's interesting. Out of curiosity, what's your use case?

**Comment by samselikoff** [comment]
I do think this is a good idea, though you should know with the ORM factories will be building `Mirage.Model` instances instead of just json. (Those models will have an `.attrs` property which will expose the json, too.)

**Comment by iezer** [comment]
@jherdman Our most common use is case is when testing a creation form. We could do `var post = server.build('post');`, fill in the form fields on the page with attributes from `post`, and then assert that the object that got saved to the DB is the same.

@samselikoff cool, is that something that is available now or is it progress?

**Comment by samselikoff** [comment]
The ORM is in the beta release but the Factory doesn't leverage it yet. That will be the highest priority once 0.2.0 ships. New factories will land in 0.2.1.

**Comment by samselikoff** [comment]
Btw I'm not sure factories are the best solution for your use case. Factories are really purposed to seed your database with certain data. Your test sounds more like a user filling in data, which you wouldn't want the factory to be responsible for (I think). I could comment more if I saw the code.

**Comment by tundal45** [comment]
@samselikoff The kind of use we are envisioning is what [factory_girl](https://github.com/thoughtbot/factory_girl/blob/master/GETTING_STARTED.md#using-factories) provides. The idea is that `var post = server.build('post')` would not affect the contents of `server.db` but give us an in-memory object that we can use.

**Comment by tundal45** [comment]
@samselikoff At least for our use case thus far, we are ok with it being `Mirage.Model`.

**Comment by samselikoff** [comment]
Filing this under the "Ability to make Ember Data models from Mirage factories" card in the Roadmap project.
