### ISSUE TITLE
Why does my seed data in development keep getting refreshed?

### ISSUE THREAD

**Issue by Jordan4jc** [samselikoff/ember-cli-mirage#390]
Is this a feature? It seems like it would not be. I have the default scenario generating 10 users, these users have a property called `short_url` that I am using to look the users up by, no their id.

But every time I try to look up the user the `short_url` and all the other data has been refreshed. I suppose I could just use fixtures here but it kind of seems like scenarios would be the better option, unless I'm using them wrong?

**Comment by samselikoff** [comment]
Are you asking why data changes you've made while using your app are not being persisted after you reload your app?

**Comment by Jordan4jc** [comment]
No, when I launch the app, the database gets seeded, and I see the data in the console. So I drill down to one of the users that was created, copy his `short_url` and then try to go the route that uses that short_url as a param. But as soon as I hit enter the users get re-seeded. Is it because I've pasted into the address bar and not used embers `link-to` to transition to the single record route?

**Comment by lukesargeant** [comment]
Yep. You've reloaded the page (app). Use a link-to if you want the app and its data to persist.

**Comment by samselikoff** [comment]
@Jordan4jc Closing this for now, but please let me know if you'd still like some more help here. Whenever you refresh the page, the Mirage server will restart and the db will be wiped, since currently it's just a JS in-memory map.
