### ISSUE TITLE
O(N^2) performance when using createList due to get for this.db[collection].

### ISSUE THREAD

**Issue by DanChadwick** [samselikoff/ember-cli-mirage#391]
In server.js, `createList` calls `create` for each list item. In `create`, `this.db[collection]` is referenced twice. Because `defineProperty` is used to create the ` get` method, it is used for this access. This copies the entire database to JSON and then parses it back.

So if mirage creates a list of 1000 records, 2,000 calls JSON encode/decodes are made, that last one with an array of 1000 elements.

With 100 records, the delay is imperceptible. With 1000 records, the delay is about 15 seconds.

Neither of the two calls to `get` actually uses the copied database. One just checks the length and the other calls it's bound `insert` method, which access the real database through an instance variable.

Or at least I think that's what's happening by stepping through the code. :)

**Comment by samselikoff** [comment]
Thank you for opening this! I will look into it most likely after the 0.2.0 release.

**Comment by joostdevries** [comment]
This one is a pretty big blocker for us (it basically renders mirage unusable at the moment). To overcome this I guess it would be best to pass the collection along as an optional argument to `create()` from `createList()` right? So there would only be one `get()` call.

**Comment by joostdevries** [comment]
Ideally, a call to `create` would not duplicate the entire collection at all. Is there a reason for this?

**Comment by alvinvogelzang** [comment]
@DanChadwick can you check if #441 solves your solves your problem?

**Comment by DanChadwick** [comment]
@alvinvogelzang -- I wish I could, but I'm no longer using mirage. I was only using it early on to provide test data and the project now has real data. Sorry. :(

**Comment by alvinvogelzang** [comment]
@DanChadwick allrighty no probs

**Comment by samselikoff** [comment]
After reviewing the method, the call to `db.collection` is unnecessary - a simple hash map using the factory type will do for storing the current sequence number. I'm focused on 0.2.0 right now, I will get to this soon after that release, or someone else can feel free to pick it up!
