### ISSUE TITLE
There is no route to handle this request Error

### ISSUE THREAD

**Issue by MohamadAtieh** [samselikoff/ember-cli-mirage#394]
I'm new to Mirage so bare with me. I'm trying to return a simple object with a token. I use `POST` in an Ajax call, so my call is being used directly and not through Ember Data methods. The console says I'm calling `authentication/login` but there is no route defined for it.

And that's the point. Does mirage work with any network request detected or just through ember data?

Another few concerns:

- Will it still use the defined Adapters for each model?
- Will it go through the defined serializers after returning the mocked data? 

The error also asks whether I have defined a namespace for my API. Isn't the idea of mirage is to replace my server? I have no host or namespace defined in my adapters, since I proxy my calls to the actual API with the `-pr` flag. So my understanding is that by not defining `urlPrefix` and `namespace` in my config file it would mock my POST function.

    this.post = ('/authentication/login', function(db, request){
        return { 
          token: 12345678
        };
     });

**Comment by samselikoff** [comment]
@MohamadAtieh closing this for now, please let me know if you still have questions!

**Comment by MohamadAtieh** [comment]
@samselikoff The format you provided was the correct one. Forgot to reply back! Thanks a lot!
