### ISSUE TITLE
Contents in app/mirage exists in the minified bundle

### ISSUE THREAD

**Issue by nekman** [samselikoff/ember-cli-mirage#395]
When we build for production, `ember build environment=production` all `/mirage` files: 

* factories
* scenarios
* fixtures
* config.js 

ends up in our minified js-file. How can we remove these files from our production build?

**Comment by blimmer** [comment]
This doesn't help now, but in 0.2.x the mirage folder [is at the root](https://github.com/samselikoff/ember-cli-mirage/blob/master/blueprints/ember-cli-mirage/index.js#L21), not in `app/` so I think that would resolve this problem.

Still a good question for 0.1.x users, though.

**Comment by samselikoff** [comment]
If true this is a bug, mirage should not be included in prod builds. Do you
have enabled = true flag under the prod environment in your config.js?

**Comment by nekman** [comment]
My mistake. I missed the -- before the argument. If I use `ember build --environment=production` then Mirage is not included in the minified file.

**Comment by vfritzon** [comment]
@samselikoff as far as I understand mirage is disabled, but still included, in any environment other than production even if you set `enabled: false`: https://github.com/samselikoff/ember-cli-mirage/blob/e4a0abcda51aef56f03e51cd844a7ca9130f8e09/index.js#L50?

**Comment by samselikoff** [comment]
@vfritzon why? And the reason we include it is because it could be disabled for dev but enabled at test, and some people use `localhost:4200/tests` (which is an ember app built in `development` but with a `test` runtime environment)

**Comment by vfritzon** [comment]
Ok I see, figured there might be a reason. The reason for me wanting some other way of excluding it other than the environment flag was that we used 'qa' as environment value and would like that to produce a build as close to the production one as possible (i.e. exclude mirage in this case) and was hoping that setting `enabled: false` would do that.

However, we ended up using production as environment for QA as well and used other flags to set the  stuff that differed. I think it could be argued that this is generally a better way to go anyway.

**Comment by samselikoff** [comment]
Yep, I think I agree with your conclusion

**Comment by remkoboschker** [comment]
I would like to exclude the mirage, pretender, faker sources from an acceptance environment build, because it doubles the vendor javascript file and impacts loading times significantly. It gives a customer trying the app in acceptance the wrong impression.

Could I change the `_shouldIncludeFiles` condition in the `index.js` file from 
````
    var enabledInProd = this.app.env === 'production' && this.addonConfig.enabled;

    return enabledInProd || (this.app.env !== 'production');
````
to
````
    return this.addonConfig.enabled || this.app.env === 'development' || this.app.env === 'test'
````
I think this would cover the requirements mentioned above i.e. load code in development build when in a test environment for use in the `localhost:4200/tests` scenario. And at the same time it would allow for any other environments to exclude it. So the source would always be included for dev and test and when mirage is enabled and excluded otherwise.

Happy to write the tests and make a pull request.

**Comment by samselikoff** [comment]
We actually have another request/PR for this [here](https://github.com/samselikoff/ember-cli-mirage/pull/555), and in that case that user wants to exclude the files from the build in development. So I think the best path forward is to just add a new option.

We could also just use `enabled`, which would punish people for visiting `/tests` via `ember s` :P (they should be using `ember test --server` anyway). But I think that's too much. Removing `/tests` from `ember s` would make Mirage's init code much simpler...

**Comment by remkoboschker** [comment]
@samselikoff Alright, sorry I missed the other pr. Extra option is fine by me.
