### ISSUE TITLE
option to configure pretenderify data path

### ISSUE THREAD

**Issue by devinrhode2** [samselikoff/ember-cli-mirage#4]
One could place all the pretenderify data in a separate repo for a backend team to use for testing, or otherwise put it in a folder at the same level as the frontend and backend (/frontend, /json-data, /backend)

**Comment by samselikoff** [comment]
I like it. The ultimate dream is to have this intermediate layer be testable, or have some automated tool produce a "contract" that both the frontend and backend could test against.

I like the idea of having it separate, though I'm not sure how easy it'd be to get it into both the /app and /testing trees of the Broc build? At one point rwjblue told me if I wanted to share anything between app and tests to put it under /app. But maybe now that it's an addon it can be completely separate.
