### ISSUE TITLE
Be able to use factory inside config

### ISSUE THREAD

**Issue by Gaurav0** [samselikoff/ember-cli-mirage#405]
So in my application, when I insert a new record, I would like the ability to use a factory to do so, so that I could get all my defaults without needing to recreate them. I am able to do using undocumented (private?) apis like this:

     import AuditHistoryFactory from "./factories/audit-history";

     // ...

     this.put('/:client/pending_cashflows/:id', function(db, request) {
       const attrs = JSON.parse(request.requestBody).pendingCashFlow;
       db.pendingCashFlows.update({
         cashFlowId: request.params.id
       }, attrs);

       const Factory = AuditHistoryFactory.extend({
         cashFlowId: request.params.id,
         text: "Some random text"
       });
       const factory = new Factory();
       const history = factory.build(db.auditHistories.length);
       db.auditHistories.insert(history);

       return new Mirage.Response(204, {}, attrs);
     });

This is based on code copied from server.create. I tried to use window.server, but it was undefined.

I would like to be able to do this without using undocumented (and possibly private, subject to change) apis.

**Comment by samselikoff** [comment]
Yes, others have brought this up. I'll have to think more about this, but my first instinct says factories should not be used directly like this in route handlers. Default values are different than fake data used for seeding, so just like you wouldn't use factory_girl factories in your Rails controllers, I don't think you should use Mirage factories in your route handlers.

Again, you're not the first person who asked for this, so I think there's a way we can come up with something - perhaps default values in the Model file. But for now, if you must, you can do what you're doing here.

**Comment by danny-andrews** [comment]
But Mirage route handlers aren't used in production like Rails controllers are. The purpose of Mirage is to allow you to stub out your backend, so I think it makes perfect sense to be able to use factories inside your route handlers.

**Comment by Gaurav0** [comment]
@danny-andrews Actually I figured out the solution to this quite a while ago. The key is to realize that `this` inside `config.js` and `window.server` in your tests are in fact one and the same object! Once that connection is made, the solution is obvious:

    this.put('/:client/pending_cashflows/:id', (db, request) => {
      const attrs = JSON.parse(request.requestBody).pendingCashFlow;
      db.pendingCashFlows.update({
        cashFlowId: request.params.id
      }, attrs);
      
      this.create('history', {
        cashFlowId: request.params.id,
        text: "Some random text"
      });

      return new Mirage.Response(204, {}, attrs);
    });

**Comment by danny-andrews** [comment]
Woh, thanks @Gaurav0!
