### ISSUE TITLE
Return one object when specific their is a query param

### ISSUE THREAD

**Issue by benoittgt** [samselikoff/ember-cli-mirage#406]
Hello

My json api endpoint looks like this `api/front/devices?users=:user_id`. For the moment in my config I have something like : 

```javascript
  this.get('/api/front/devices', function(db, request) {
      let userId = request.queryParams.user; // but what for?

      return {
        data: {
          type: 'devices',
          id: ??, //which id because is determine by the endpoint ?
          attributes: db.devices.find(??)
        }
      };
  });
```

If I set the `id: 1` and `.find(1)`. I get `TypeError: Ember.A(...).mapBy is not a function`

**Comment by benoittgt** [comment]
`TypeError: Ember.A(...).mapBy is not a function` seems unrelated to the mirage configuration. Close it for now.

**Comment by sirvine** [comment]
It looks like you're returning a single object, but your query to the `api/front/devices` endpoint is expected to return a collection.  Try returning in a format similar to this one:

```javascript
return {
    data: db.devises.map(attrs => (
      {type: 'devises', id: attrs.id, attributes: attrs }
    ))
  };
```

**Comment by benoittgt** [comment]
Thanks @sirvine. It appears the errors was related to [this issue](https://github.com/emberjs/data/issues/3466). I've updated my ember data and change my `query` to `queryRecord` and it's work like I want.

BTW in your exemple you're still few elements?

**Comment by benoittgt** [comment]
Thanks 

I've edited a little bit you answer `s/devise/device` and it's work perfectly in my test. Cheers

**Comment by sirvine** [comment]
Sorry, I had the devise library on my mind!

**Comment by aelkz** [comment]
//return this.store.findRecord('product', params.id); // NOT WORKING
return this.store.queryRecord('product', params.id); // WORKING

@sirvine sollution don't works with me. The error still showing on console.
