### ISSUE TITLE
Delete should return 204 response

### ISSUE THREAD

**Issue by BryanHunt** [samselikoff/ember-cli-mirage#408]
I'm trying out 0.2.0-beta.1 and the delete shorthand is not working with EmberData JSON API.  It seems to return a 200 response which causes EmberData to attempt to parse the empty body and throw an error.  If you create your own implementation of delete and return 204 for the response, EmberData is happy again.  For example:

```javascript
  this.delete('/registrations/:id', (schema, request) => {
    schema.registration.find(request.params.id).destroy();
    return {};
  }, 204);
```

**Comment by samselikoff** [comment]
Ok, will look into this. Thanks for opening an issue!
