### ISSUE TITLE
[0.2.0-beta.1] no route defined when enabled in production

### ISSUE THREAD

**Issue by GreenDude** [samselikoff/ember-cli-mirage#409]
So I've upgraded to 0.2 in development and everything is working fine.

I've also pushed mirage into production as well to showcase a working version of the app. Mirage is loaded but it says the routes are not defined

```
Error: Mirage: Your Ember app tried to GET '/api/v1/assessments/1', but there was no route defined to handle this request. Define a route that matches this path in your mirage/config.js file. Did you forget to add your namespace?
```

The route should be defined tho since it works in development:

```js
  //config.js

  this.namespace = 'api/v1';

  this.get('/assessments/:id', (schema, request) => {
    var id = request.params.id;

    return schema.assessment.find(id);
  });
```

I'm using a factory to generate the assessment and I run `server.createList('assessment', 1);` in the default scenario. I've also got a model defined but it has no relations and an app serializer which just exports the `JsonApiSerializer`.

The differences in production are the following:

```js
  if (environment === 'production') {
      ENV.baseURL = '/candidate-ui';

      ENV['ember-cli-mirage'] = {
        enabled: true
      }
  }
```

The requests are looking fine on the Ember end. Any idea what might cause this? Or perhaps any suggestions on how to debug further?

Cheers!

**Comment by samselikoff** [comment]
Hmm, if it works in dev I would expect it to work in prod. To debug let's first try adding `/` in front of namespace?

```js
this.namespace = '/api/v1';
```

Next step would be to drop the namespace and use the full path on the mock, just to see if it registers:

```js
this.get('/api/v1/assessments/:id`, ...
```

**Comment by GreenDude** [comment]
Adding the `/` in front of the namespace made it work :) Thanks!
