### ISSUE TITLE
Collection update fails when id is a string of digits

### ISSUE THREAD

**Issue by deepan83** [samselikoff/ember-cli-mirage#410]
I am mocking some APIs that have ids as a string of digits and found that the update method on the collection fails since the _findRecord method coerces it into a number and then tries to compare against the id on the original record which in this case is still a string.

```
  server.create('services-account', {
    id: '911000155091',
    status: 'open'
  });

  db['services-accounts'].update(request.params.id, {status: 'closed'}); //Fails to _findRecord to update

   // _findRecord
    if (typeof id === 'string' && allDigitsRegex.test(id)) {
      id = parseInt(id, 10);
    }
```

Is the coercing really required?

Happy to do a PR on this if direction is agreed

**Comment by samselikoff** [comment]
There has been some discussion on this (https://github.com/samselikoff/ember-cli-mirage/issues/67 and others), it's a bit tricky. In general Mirage needs to know how to find things in the db, so I think the path forward is to let it use ids as it wants to and use your serializer layer if you want your mocked API to return strings.

How are you seeding your db here?

**Comment by samselikoff** [comment]
Also https://github.com/samselikoff/ember-cli-mirage/pull/293

**Comment by deepan83** [comment]
We use factories but at the moment pass ids in during server.create as they sometimes have to meet specific formats

**Comment by samselikoff** [comment]
Gotcha. I've prioritized the other issues related to this, and will be tackling them as part of the 0.2.0 milestone.

**Comment by samselikoff** [comment]
Believe #462 closes this.
