### ISSUE TITLE
Cannot install v0.2.0-beta.1 on the windows

### ISSUE THREAD

**Issue by amatsal** [samselikoff/ember-cli-mirage#411]
When I try to install v0.2.0-beta.1 on windows system shows next error:
```
fatal: cannot create directory at 'blueprints/mirage:factory': Invalid argument.
```

Names with colon are restricted on Windows

**Comment by samselikoff** [comment]
Thank you, we will be changing this shortly

**Comment by samselikoff** [comment]
563074a4e8d23f93b0ec7ae0737854fac0c10983 fixes
