### ISSUE TITLE
JSONAPI hasMany relationships not loading

### ISSUE THREAD

**Issue by kevintraver** [samselikoff/ember-cli-mirage#414]
I have the following setup using the latest JSONAPI serializer:

In my model
```
notes: DS.hasMany('note')
```
In my serializer
```
relationships: ['note']
```
and then in my scenario
```
var note = server.create('note');
var contact = server.create('contact', { note_ids: [note.id] } );
```

When I look at the data, it shows the relationship object (relationships / notes / data), but is an empty array.

Am I using the scenario wrong?

**Comment by samselikoff** [comment]
I think `relationships` should be `notes` (it refers to the property name, not the model name). Also, you should be able to do something like

```js
let contact = server.create('contact');
contact.createNote();
```

**Comment by kevintraver** [comment]
is `createNote` something I have to implement myself?

this is what Im trying to accomplish:

`/contacts/1`

```
{
   "data":[
      {
         "id":"1",
         "type":"contacts",
         "links":{
            "self":"http://localhost:3000/contacts/1"
         },
         "relationships":{
            "notes":{
               "links":{
                  "self":"http://localhost:3000/contacts/1/relationships/notes",
                  "related":"http://localhost:3000//contacts/1/notes"
               }
            }
         }
      }
   ]
}
```

`/contacts/1/relationships/notes`

```
{
   "links":{
      "self":"http://localhost:3000/contacts/1/relationships/notes",
      "related":"http://localhost:3000/contacts/1/notes"
   },
   "data":[
      {
         "type":"notes",
         "id":"1"
      },
      {
         "type":"notes",
         "id":"1"
      }
   ]
}
```

I know that might not be possible yet.

Thanks again for your help and the great work!

**Comment by samselikoff** [comment]
No `create[model]` is part of the [associations api](http://www.ember-cli-mirage.com/docs/v0.2.x/models/#associations).

Ah, the `contacts/1/relationships/notes` endpoint is not automated yet so you'd have to mock it out yourself. But if you're using links you don't need `relationships: ['notes']`. That's what you use if you want includes (i.e. if you wanted your first endpoint to respond with the notes as well).

Links is not handled right now so you'd need to mock it out yourself.

**Comment by kevintraver** [comment]
Ok, I was able to get create working... and I see the notes when I do `console.log(contact.notes)`, but I still dont see the notes in the response object:

```
{
  "data": [
    {
      "type": "contacts",
      "id": 1,
      },
      "relationships": {
        "notes": {
          "data": []
        }
      }
    }
  ]
}
```

**Comment by samselikoff** [comment]
sounds like a bug. any chance you could push a test repo that I can look at?

**Comment by samselikoff** [comment]
you're on beta-1 correct?

**Comment by kevintraver** [comment]
Yes, beta-1.

https://github.com/kevintraver/ember-sample-app

**Comment by samselikoff** [comment]
ah, you didn't save `contact`. `contact.notes = [note1, note2]` sets the association in-memory but doesn't persist to the db. You'd need to do `contact.save()` after that to persist.

An easier way:

```js
let contact = server.create('contact');
contact.createNote();
contact.createNote();
```

or

```js
let contact = server.create('contact');
server.createList('note', 2, {contact: contact});
```

The `create*` methods automatically update the db.

**Comment by kevintraver** [comment]
Ah ok. Thanks!!

**Comment by ryrych** [comment]
@kevintraver Were you be able to `createNote`? Updated repo with `save()` would be also helpful.
@samselikoff I have the same problem with `create[model]` method. `save` doesn't work either.

**Comment by samselikoff** [comment]
`createNote` would exist on a `contact` model instance, but currently the factory `server.create` method won't return the model instance, it will just return a hash.

You could get the model instance using `schema`:

```js
let attrs = server.create('contact');
let contact = server.schema.contact.find(attrs.id);

contact.createNote(); // should work
contact.save(); // should work
```

but like I said above the easiest is probably to do it like in my example.

**Comment by ryrych** [comment]
Thanks. I have another question. If you feel that this should land as a separate issue, let me know.

User `hasMany` accounts. Account also `hasMany` users:

```javascript
// models/user
export default Model.extend({
  attrs: ['name', 'email'],

  accounts: hasMany(),
});
```

```javascript
// models/account
export default Model.extend({
  projects: hasMany(),
  users:    hasMany(),
});
```

```javascript
// serializers/user
export default Serializer.extend({
  relationships: ['accounts'],
});

```javascript
// serializers/account
export default Serializer.extend({
  relationships: ['projects', 'users'],
});
```

This is way I wonder why I have to use: `{ accountId: 1 }`, not `{ accountIds [1] }`. The former works, the latter does't.

**Comment by samselikoff** [comment]
Hey @ryrych , sorry you're still seeing problems! Could you open a new issue for this?

**Comment by ryrych** [comment]
Hi, I think I could resolved that creating object via association `account.createUser()` but I'll try it out in your demo app.
