### ISSUE TITLE
Improve DB's autoincrement

### ISSUE THREAD

**Issue by samselikoff** [samselikoff/ember-cli-mirage#415]
Currently the db assigns an `id` based on the `length` of the array. This can cause problems if you delete some models then create a new one. The `id` can clobber an existing model.

**Comment by jherdman** [comment]
I don't mind looking into this if you haven't already begun work on it.

**Comment by samselikoff** [comment]
I haven't, that would be huge!

**Comment by jherdman** [comment]
I've run into an edge case that I'm not quite sure how to handle. What should happen when a record is inserted with an ID that's already been used? Example:

```javascript
db.contacts.insert([ { name: 'Zelda' }, { name: 'Ganon' }); // so far IDs 1 and 2 have been claimed
db.contacts.insert({ id: 2, name: 'Princess' }) // Stomp!
```

**Comment by samselikoff** [comment]
I think that's right. Let them insert with `id`, but if `id` already exists throw error. But for now, console.log as you say.

Thanks for this, this is awesome!
