### ISSUE TITLE
Trailing slashes in model URL's

### ISSUE THREAD

**Issue by orf** [samselikoff/ember-cli-mirage#418]
I'm running into a weird issue with trailing slashes. When my app requests `/somecollection/1/`, the `getTypeFromUrl` function doesn't seem to handle this correctly. It returns `1` as the type, which means mirage tries to look for the `1s` collection.

Has anyone else experienced this?

**Comment by samselikoff** [comment]
I'll take a look at this before we cut 0.2.0. Thank you for reporting!
