### ISSUE TITLE
Serializing one-to-one relationships

### ISSUE THREAD

**Issue by mitchlloyd** [samselikoff/ember-cli-mirage#421]
I'm trying to serialize a one-to-one relationship and I can't figure out to to setup my models and serializers to make this work.

``` javascript
// models/user.js
import { Model } from 'ember-cli-mirage';

export default Model.extend({
  // Should some relationship go here?
})
```

``` javascript
// models/address.js
import { Model, belongsTo } from 'ember-cli-mirage';

export default Model.extend({
  user: belongsTo()
});
```

``` javascript
// serializers/user.js
import ApplicationSerializer from './application';

export default ApplicationSerializer.extend({
  relationships: ['address']
});
```

With this setup, we have `address.user` and `address.userId`, but there is no `user.address`. When serializing user, the address isn't included in the payload.  I was expecting a `hasOne()` model relationship since we're dealing with foreign keys in a database, but I see this doesn't exist. 

This may be a conceptual misunderstanding so maybe something could be added to the `models` documentation to clarify how this should work.

**Comment by samselikoff** [comment]
Yes, we need to add `hasOne` support. I was thinking being able to specify which model owns the foreign key on a `belongsTo` would be sufficient, similar to Ember Data. What do you think?

**Comment by mitchlloyd** [comment]
I thought that Ember Data would accept foreign keys from either side of a relationship. I just did a little searching through the history of `hasOne` and Ember Data and I think this thread is helpful: https://github.com/emberjs/data/issues/3696#issuecomment-139354105. 

It is a shame to deviate from Ember Data when so many other concepts are similar, but since we have to choose which side has the foreign key in a one-to-one relationship, it seems natural to use `hasOne` in the example I had:

```javascript
// models/user.js
import { Model } from 'ember-cli-mirage';

export default Model.extend({
  hasOne('address')
})
```

**Comment by samselikoff** [comment]
Ah. I think I didn't understand how `hasOne` was used in ED, or perhaps elsewhere. Could you help me understand - in your case, if a `user` `hasOne` `address`, where does the fk live?

Btw, for your example above, I think adding a `address: hasMany()` might be a hacky solution that works for now.

**Comment by mitchlloyd** [comment]
In my example, address would have `address.userId`.

In this case I'm thinking of the Rails [`hasOne` method](http://guides.rubyonrails.org/association_basics.html#the-has-one-association). The convention there is that the model with `belongs_to` always has the foreign key. `has_many` and `has_one` define the methods to access the relationship from a model that does not have the foreign key.

**Comment by samselikoff** [comment]
Gotcha. So there's no difference at the database level between `has_many` and `has_one`, just that the `has_many` property would return an array of records and `has_one` would return a single model? If so, this shouldn't be too difficult to add into Mirage's ORM layer.

**Comment by mitchlloyd** [comment]
That's right. My expectation would be that `hasOne` would add methods much like `hasMany` except that they only deal with one record:

```javascript
user.addressId;             // 1 -- even though address actually has the FK.
user.addressId = 2;         // updates the relationship
user.address;               // the related address
user.address = address1;    // updates the relationship
user.newAddress(attrs);     // new unsaved address
user.createAddress(attrs);  // new saved address (address.userId is set)
```

To the serializer this would look the same as the `belongsTo` so hopefully no changes would be needed there.

**Comment by samselikoff** [comment]
Awesome, thanks for taking the time to explain! Not sure if this will make it into 0.2.0 (my priority atm) but if not, will come soon after.

**Comment by saheljalal** [comment]
Is there a suggested workaround for this in the meantime?

**Comment by samselikoff** [comment]
I would say to probably use hasMany on this side of the relationship, and clean up the data in `Serializer#serialize`.

I am actually working through the ORM updates right now, and I'm about halfway through. I have one-to-one and reflexive relationships working at the moment. I'd estimate a few more weeks before this all makes it into master.

**Comment by samselikoff** [comment]
This is now supported in the 0-3 series! Read [this post](www.ember-cli-mirage.com/blog/2017/01/09/0-3-0-beta-series/) for more information.

**Comment by clekstro** [comment]
For posterity, here's a working link to the post mentioned above: www.ember-cli-mirage.com/blog/2017/01/09/0-3-0-beta-series/
