### ISSUE TITLE
[DOCS] Show example of acceptance test of an error

### ISSUE THREAD

**Issue by Gaurav0** [samselikoff/ember-cli-mirage#423]
Something like:

    test('throws error', function(assert) {
         server.get('posts', {errors: ['There was an error']}, 404);

         visit('/');
         andThen(function() {
             assert.equals(find('p:contains(There was an error)').length, 1);
         });
    });

**Comment by samselikoff** [comment]
7b5f137dcf395916afa9a9e8ff1311c7d390ef04 closes
