### ISSUE TITLE
an error

### ISSUE THREAD

**Issue by samselikoff** [samselikoff/ember-cli-mirage#43]
@thatikuntap 

if run ember server, get below error, but it works once I remove http://localhost:8000/tools application adapter.

Error: Pretender will not respond to requests for URLs. It is not possible to accurately simluate the browser's CSP. Remove the http://localhost from http://localhost:8000/tools and try again

**Comment by samselikoff** [comment]
do you have something like `$.getJSON('localhost:8000/tools')` in your app? did you use `--proxy http://localhost:800`?

**Comment by thatikuntap** [comment]
below is code in application adapter

import DS from 'ember-data';
 export default DS.RESTAdapter.extend({
 // host: 'http://localhost:8000',
  corsWithCredentials: true,
   //namespace: 'api/'
});

**Comment by samselikoff** [comment]
yah so you don't want to hardcode localhost in your adapter like that, instead during development do

`ember serve --proxy http://localhost:8000`

**Comment by thatikuntap** [comment]
Thanks Sam!

**Comment by samselikoff** [comment]
:D
