### ISSUE TITLE
[master] Related models appear as `null` when parent is retrieved from the database

### ISSUE THREAD

**Issue by lolmaus** [samselikoff/ember-cli-mirage#436]
Here's what I'm seeing on master given this definition:

```js
      foo: Model.extend({
        bar: Mirage.belongsTo()
      }),
      bar: Model.extend({
        baz: Mirage.belongsTo()
      }),
      baz: Model
```

```js
const foo = schema.foo.create();
const bar = foo.createBar();
foo.bar // => Model
bar.baz // => Model
foo.bar.baz // => null

const fooAgain = schema.foo.find(foo.id);
fooAgain.bar // => null
fooAgain.reload();
fooAgain.bar // => null
```

**Comment by samselikoff** [comment]
I believe this behavior was done intentionally. When building the ORM, I consulted Rails/ActiveRecord for the reference behavior, assuming they've made their decisions for good reason. I just booted up a test rails app to see what they do in this situation.

My app has a `post` that `belongs_to` a `user`. Here's some console output:

```sh
irb(main):001:0> post = Post.create
   (0.1ms)  begin transaction
  SQL (0.9ms)  INSERT INTO "posts" ("created_at", "updated_at") VALUES (?, ?)  [["created_at", "2015-12-15 06:55:07.481959"], ["updated_at", "2015-12-15 06:55:07.481959"]]
   (0.8ms)  commit transaction
=> #<Post id: 5, user_id: nil, created_at: "2015-12-15 06:55:07", updated_at: "2015-12-15 06:55:07">
irb(main):002:0> post.create_user
   (0.1ms)  begin transaction
  SQL (0.6ms)  INSERT INTO "users" ("created_at", "updated_at") VALUES (?, ?)  [["created_at", "2015-12-15 06:55:15.285738"], ["updated_at", "2015-12-15 06:55:15.285738"]]
   (0.6ms)  commit transaction
=> #<User id: 5, created_at: "2015-12-15 06:55:15", updated_at: "2015-12-15 06:55:15">
irb(main):003:0> post
=> #<Post id: 5, user_id: 5, created_at: "2015-12-15 06:55:07", updated_at: "2015-12-15 06:55:07">
irb(main):006:0> Post.find(5)
  Post Load (0.2ms)  SELECT  "posts".* FROM "posts" WHERE "posts"."id" = ? LIMIT 1  [["id", 5]]
=> #<Post id: 5, user_id: nil, created_at: "2015-12-15 06:55:07", updated_at: "2015-12-15 06:55:07">
irb(main):007:0> post.save
   (0.1ms)  begin transaction
  SQL (0.4ms)  UPDATE "posts" SET "user_id" = ?, "updated_at" = ? WHERE "posts"."id" = ?  [["user_id", 5], ["updated_at", "2015-12-15 06:55:52.395389"], ["id", 5]]
   (1.2ms)  commit transaction
=> true
```

So you can see, the in-memory `post` instance is updated with a reference to the `user`, but that updated reference isn't persisted until the `post` is `.save()`d.

You can see I do the same behavior [here](https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/orm/associations/belongs-to.js#L109). I could simply add a `this.save()` right after updating the reference, but I'd first like to find out why this behavior is in rails. I'm going to ask some folks tomorrow, and I'll get back to you.

For now, in your example above, you should just be able to call `foo.save()` and `bar.save()` after creating the parent models, to get the relationships persisted.

**Comment by samselikoff** [comment]
da1b13f953c2d4131b6420eb94318dec989bd2b0 closes
