### ISSUE TITLE
Remove docs note about pass through requiring jQuery 2

### ISSUE THREAD

**Issue by acorncom** [samselikoff/ember-cli-mirage#437]
As of https://github.com/pretenderjs/pretender/pull/130 jQuery 2 is no longer required for passthrough

**Comment by acorncom** [comment]
Though it apparently hasn't been released in a separate version just yet

**Comment by samselikoff** [comment]
Awesome! We'll leave this here until a release + we can bump up the version.

**Comment by samselikoff** [comment]
All set
