### ISSUE TITLE
Modify/extend/overwrite _attrsForRelationships function in the serializer-registry class

### ISSUE THREAD

**Issue by brayancastrop** [samselikoff/ember-cli-mirage#440]
Hi, i'm actually using the master branch in order to take advantage of relationships, so far now i've figured out how to serialize a user hasOne organization relationship with a hack to obtain a json like this

``` javascript
{
  id: '1',
  name: 'user name',
  organization: {
    id: '2',
    name: 'organization name'
  }
}
```

but in my case organization is optional so sometimes my user json is simply

``` javascript
{
  id: '1',
  name: 'user name'
}
```

and there my need to modify this line https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/serializer-registry.js#L194 arise; I need to check if model[key] (the relationship) is present before try to serialize it and throw a Cannot read property 'map' of null, but not sure how to do it?

**Comment by samselikoff** [comment]
If we added a `hasOne()` then I think `embedded: true` would work here, on the base serializer. Do you agree? We need to add that API anyway.

You can also always override `serialize()` in your own, you should be able to call super via

```
let json = BaseSerialize.prototype.serialize.apply(this, arguments);
```

and then munge from there.

**Comment by brayancastrop** [comment]
Thanks!!!

I ended up extending from JsonApiSerializer (i was previously using active-model-serializer but this line https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/serializer-registry.js#L37 makes json-api-serializer required) and customizing it just like the serializer registry with a little change in _attrsForModel and _attrsForRelationships

```javascript
_attrsForModel: function(model, removeForeignKeys, embedRelatedIds) {
  var _this5 = this;

  var serializer = this;

  let attrs = {};

  if (this.attrs) {
    attrs = this.attrs.reduce((memo, attr) => {
      memo[attr] = model[attr];
      return memo;
    }, {});
  } else {
    attrs = _assign(attrs, model.attrs);
  }

  if (removeForeignKeys) {
    model.fks.forEach(function (key) {
      delete attrs[key];
    });
  }

  if (embedRelatedIds) {
    serializer.relationships.map(function (key) {
      return model[key];
    }).filter(function (relatedCollection) {
      return _this5._isCollection(relatedCollection);
    }).forEach(function (relatedCollection) {
      attrs[serializer.keyForRelationshipIds(relatedCollection.type)] = relatedCollection.map(function (obj) {
        return obj.id;
      });
    });
  }

  return this._formatAttributeKeys(attrs);
},
_attrsForRelationships: function(model) {
    var _this6 = this;

    var serializer = this._serializerFor(model);

    return serializer.relationships.reduce(function (attrs, key) {
      var relatedAttrs = isPresent(model[key]) ? _this6._serializeModelOrCollection(model[key]) : null;

      if (relatedAttrs) {
        attrs[key] = relatedAttrs;
      }

      return attrs;
    }, {});
  }
```

And i agree with the hasOne helper makes sense to have the helper as it's needed to properly serialize relationships

**Comment by samselikoff** [comment]
Nice hacking! Although this is kind of crappy for you to have maintain this code in your app :/ For now, fine I think. I believe the real solution here is to add `hasOne` support. I have a ticket for this, it's one of the first things I'm going to work on after cutting 0.2.0.

**Comment by samselikoff** [comment]
Closing as has-one is now supported in 0-3.
