### ISSUE TITLE
Add Pagination metadata to JSONAPISerializer

### ISSUE THREAD

**Issue by joedivita** [samselikoff/ember-cli-mirage#442]
Is it possible to support returning metadata with a route's response?  (Would be good for something like pagination). 

Ie a JSON API response like: 

```
{
  data: [
    { type: 'item', id: 1 },
    { type: 'item', id: 2 },
    { type: 'item', id: 3 },
    { type: 'item', id: 4 },
    { type: 'item', id: 5 }
  ],
  meta: {
    total: 200
  }
}
```

Where this is eventually available in the controller like so: 

```
this.get('model.meta');
```

**Comment by samselikoff** [comment]
Yes I believe it would, especially since there is a spec for this in json:api. This is prioritized behind several other things for me at the moment, but definitely a feature we should/could add!

**Comment by Dhaulagiri** [comment]
@samselikoff I'm finding a need for this so I am interested in taking a stab at implementing this here.  I'm curious if you have any general pointers on how to implement this considering `meta` can be arbitrary?  The use case I am specifically interested in is matching up with jsonapi-resources `record-count` that can be used for pagination:

```
meta: {
  record-count: 3
}
```

**Comment by samselikoff** [comment]
If you want you can manually call `serialize` then add the data yourself in the route handler:

```js
this.get('posts', ({post}, request) => {
  let json = this.serializerOrRegistry.serialize(post.all());

  json.meta = {};
  return json;
});
```

Would that work for now?

**Comment by Dhaulagiri** [comment]
That works great, thanks @samselikoff

**Comment by samselikoff** [comment]
@joedivita and @Dhaulagiri, I added a note about [overriding #serialize and calling super](http://www.ember-cli-mirage.com/docs/v0.2.0-beta.3/serializers/#serializeresponse-request) in the docs, which would be my recommended way of manipulating the json data after its been serialized. This should be used instead of `this.serializeOrRegistry.serialize` in the route handler.

**Comment by Dhaulagiri** [comment]
Much cleaner (and reusable), thanks for pointing that out @samselikoff

**Comment by joedivita** [comment]
This works great and is exactly what I needed.  Thanks @samselikoff.

**Comment by Ramblurr** [comment]
@samselikoff If overriding the serializer and adding meta in #serialize is the way to go, how are we supposed to put request context specific data that is only available in the handler?

Going back to the total_pages example, in the serializer I don't know how many pages there are, that information is only known in the handler.

**Comment by samselikoff** [comment]
No way to yet. Splitting up this work between route handlers and serializers definitely smells funny... maybe we'll need to add a new way to get metadata from handlers to the serializer layer. I think what you're doing - adding it to the request object - is fine for now, though.

**Comment by denzo** [comment]
Is any updates/examples on this (pagination)?

**Comment by AnthonyNitram** [comment]
I up this topic for one precision : 

I use the response of @samselikoff but in my route, i have parameter include and other.
When I wrote : 

`this.serializerOrRegistry.serialize(result);`

This didn't take my include.
This is the good thing to do : 

`this.serializerOrRegistry.serialize(result, request);`

I hope this can help someone

**Comment by Spidlace** [comment]
I up this topic for one precision :

I use the response of @samselikoff but in my route, i have parameter include and other.
When I wrote :

this.serializerOrRegistry.serialize(result);

This didn't take my include.
This is the good thing to do :

this.serializerOrRegistry.serialize(result, request);

I hope this can help someone
