### ISSUE TITLE
Using db and id in factories

### ISSUE THREAD

**Issue by phikes** [samselikoff/ember-cli-mirage#445]
Hi, I am fairly new to Ember, so bear with me :). I try to use `db` and a records `id` in my factory like this:
```
`import Mirage, {faker} from 'ember-cli-mirage'`

Recipe = Mirage.Factory.extend
  commentCount: -> db.comments.where(recipe_id: @id).count

`export default Recipe`

```
In my case a recipe has many comments and comments belong to a recipe. I am setting this up like proposed in the docs. The thing is when** indexing all recipes** I don't want to include all the comment ids, but rather return the comment count.

The code above is not working, but is this possible somehow? I tried to read the code and searched for similar issues, but couldn't find any hints.

Thanks for your help!

**Comment by samselikoff** [comment]
Glad to help! So, Factories in Mirage should really be thought of as ways to generate `db` data - think, the plain fields in your actual server's database tables. So the Recipe factory here should just be concerned with fields on the Recipe model itself.

`commentCount` sounds like something you could do at the response/serializer layer. Are you using 0.1.x? If so, you could write something like this in your `config.js` file:

```js
this.get('/recipes', (db, request) => {
  return db.recipes
    .map(recipe => {
      recipe.commentCount = db.comments.where(recipe_id: recipe.id).length
    });
});
```

Does that make sense?

**Comment by phikes** [comment]
Thank you so much for your help. It is greatly appreciated :) Happy holidays!

**Comment by samselikoff** [comment]
:+1: you're welcome, please post back if you run into more trouble!
