### ISSUE TITLE
Custom faker methods returns functions instead of values

### ISSUE THREAD

**Issue by andrewfan** [samselikoff/ember-cli-mirage#447]
After reading the documentation http://www.ember-cli-mirage.com/docs/v0.2.x/factories/#using-fakerjs i thought that `faker.random.list('a', 'b')` will return me a value 'a' or 'b', but it returns a function that should be execured https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/faker.js
So probably if the idea was to return function we should update the documentation:

```
import Mirage, {faker} from 'ember-cli-mirage';

export default Mirage.Factory.extend({
  name: faker.list.cycle('Economics', 'Philosophy', 'English', 'History', 'Mathematics'),
  students: faker.list.random(100, 200, 300, 400, 500)
});
```
and if somebody wants to modify results he probably can 

``` 
name() {
   const fakerResult = faker.list.random(100, 200, 300, 400, 500)();
   return fakerResult * 10;
}
```

**Comment by samselikoff** [comment]
You're absolutely right - thanks for opening!

1093cd48ceca4dee9484fafc42e0d3e06f9b7ffa fixes
