### ISSUE TITLE
[Feature Request] expose "build" method on server, that returns attrs from a factory but does not persist them

### ISSUE THREAD

**Issue by ballPointPenguin** [samselikoff/ember-cli-mirage#456]
FactoryGirl has the "build" method which is distinct from "create" in that it does not persist the record to the db. (see http://www.rubydoc.info/gems/factory_girl/file/GETTING_STARTED.md#Using_factories)

This is useful for things like generating example attrs for a new user on a signup form.
I am not sure if there is a good way to do this already, such as importing and using a factory within an acceptance test.

**Comment by samselikoff** [comment]
459 closes
