### ISSUE TITLE
[Testing] ember test or npm test failures

### ISSUE THREAD

**Issue by ballPointPenguin** [samselikoff/ember-cli-mirage#457]
I'm probably just missing something, or on the wrong version of something.

I'm using a fresh pull from master (https://github.com/samselikoff/ember-cli-mirage/commit/c3eacd72f25eb312d0f2bd5b4af0f7b7607fceed), clearing tmp and package cache and dist, doing npm install & bower install, and running the tests, either by `npm test` or `ember test`.

I am seeing about 50% of the tests failing.

**Comment by ballPointPenguin** [comment]
I think all the failures are this:

```
at http://localhost:7357/assets/test-support.js:6182: 'undefined' is not a function (evaluating 'this._insertRecord.bind(this)')
```

**Comment by ballPointPenguin** [comment]
`npm test` is all green when I check out #563074a

But I am running phantom 1.9. Let me try with phantom 2.0...

**Comment by ballPointPenguin** [comment]
Aha!
With Phantom 2.0, everything is passing. Perhaps a contributing / requirements section in the readme could include this version requirement. It seems like https://github.com/samselikoff/ember-cli-mirage/commit/0b6cd4e8bb8f199bbc02b9115aa01c8723e4e36f is the turning point after which Phantom 1.9 will not longer fly.

**Comment by ballPointPenguin** [comment]
See https://github.com/samselikoff/ember-cli-mirage/issues/458

**Comment by samselikoff** [comment]
Woops, sorry! I know that must have been frustrating...great idea on a CONTRIBUTING.md. 

Thanks for taking the time to work through this!

**Comment by ballPointPenguin** [comment]
My pleasure. Thanks for creating this indispensable tool.
