### ISSUE TITLE
Probably require everyone to define models

### ISSUE THREAD

**Issue by samselikoff** [samselikoff/ember-cli-mirage#460]
- wouldn't need empty factory/fixture files anymore
- factories would be a specialization on top of an empty model
- easier messaging: "Mirage uses your models to set up the db". That's it.
- would probably simplify future `ember-cli-mirage-ember-data` addon, which can read models & relationships from ED map and configure mirage at runtime, so users don't have to have model definitions in their `/mirage` directory

**Comment by ballPointPenguin** [comment]
+1
This would be really awesome.

**Comment by mellatone** [comment]
Closed my other issues in favor of this one. @samselikof, does `0.2.0` need to be shipped before `mirage-ember-data` kicks off? I feel the path to `0.2.0` is defined enough to start work on this.

**Comment by samselikoff** [comment]
@mellatone if you'd like I could kick off `ember-cli-mirage-ember-data` and write down my thoughts on how to tackle, if you wanted to dive in. Personally it's lower in priority for me than (a) 0.2.0 and then (b) factory relationships. But I don't think it should be _too_ difficult. Basically, an Ember initializer that somehow gets hold of Ember Data's mapping, and augments Mirage's model mapping at runtime.

If you did want to start working on this in earnest, might be good to try out something locally (in a local initializer in your project) then we could extract it. That was going to be my approach when I got around to it.
