### ISSUE TITLE
Write tests to check for the existence of the named exports in addon/index.js

### ISSUE THREAD

**Issue by samselikoff** [samselikoff/ember-cli-mirage#471]
since this is basically Mirage's API

**Comment by koriroys** [comment]
Any hints on how one might do this?

**Comment by samselikoff** [comment]
I think just a sanity-check test somewhere in `/tests/integration` that has

```js
import {
  Model,
  Factory,
  Serializer,
  ...
};

...

assert.ok(Model):
```

as those would fail if the test wasn't able to import those named exports from Mirage's `index.js`.
