### ISSUE TITLE
Error with pubnub test

### ISSUE THREAD

**Issue by villander** [samselikoff/ember-cli-mirage#480]
Hello, i’m using Mirage, when you give me this error, complaining about the pubnub

`Mirage: Your Ember app tried to GET 'http://ps19.pubnub.com/time/0?uuid=87bd6e7e-0e73-4e99-9777-7b1f4196f810&pnsdk=PubNub-JS-Web%2F3.7.18', but there was no route defined to handle this request. Define a route that matches this path in your mirage/config.js file. Did you forget to add your namespace?`

pubnub is third-party APIs

**Comment by villander** [comment]
what do in the case? I do not want the mirage test my pubnub

**Comment by samselikoff** [comment]
You can use the [passthrough](http://www.ember-cli-mirage.com/docs/v0.1.x/server-configuration/#passthrough) API to tell Mirage to ignore requests to these endpoints.

**Comment by villander** [comment]
Thanks @samselikoff

**Comment by shujathkhan** [comment]
Hey @villander , May I know how you handled this ?
I tried, 
this.passthrough('https://ps**')

**Comment by cah-briangantzler** [comment]
Given the docs, I would assume that he may have done
```
this.passthrough();
```

If you want to whitelist paths, the examples with ** would be like this for your case
```
this.passthrough('https://ps19.pubnub.com/**');
```

The docs only show examples of all routes under a host. They dont show a partial host. Just a guess.
