### ISSUE TITLE
ActiveModelSerializer ignores relationships

### ISSUE THREAD

**Issue by ballPointPenguin** [samselikoff/ember-cli-mirage#481]
Unless I'm missing something, ActiveModelSerializer does not serialize relationships or include them at all in the response that it generates.
It is up to the user to implement relationship handling in a custom serializer. Is that correct?

**Comment by ballPointPenguin** [comment]
I spoke too soon. I am looking at the implementation in the integration test now as an example.
https://github.com/samselikoff/ember-cli-mirage/blob/master/tests/integration/serializers/active-model-serializer-test.js

**Comment by ballPointPenguin** [comment]
FYI it was the 'include' keyword that I missed. I was using 'relationships' in my serializer, per http://www.ember-cli-mirage.com/docs/v0.2.x/serializers/#relationships

**Comment by samselikoff** [comment]
Yes, thank you for opening this + sorry about the confusion. I'm waiting to release `beta-2` and then upgrade the docs with the breaking change, but perhaps I should go ahead and rename those to `beta-1` to make it clearer.
