### ISSUE TITLE
Cannot define multiple relationships to the same model

### ISSUE THREAD

**Issue by richmolj** [samselikoff/ember-cli-mirage#488]
This issue is for the 0.2.x version, using master.

Say you have a model `Webapp` that `belongsTo` a `pendingRelease` and a `currentRelease`. Both relationships point to a `Release` model.

```es6
export default Model.extend({
  pendingRelease: belongsTo('release')
  currentRelease: belongsTo('release')
});
```

This will currently throw the error `Cannot redefine property: releaseId`. Is this something mirage can support.

**Comment by samselikoff** [comment]
Yes, absolutely, I believe this is what https://github.com/samselikoff/ember-cli-mirage/issues/350 is about. But this will be addressed soon.

**Comment by samselikoff** [comment]
15e5f38cf8964e55c57e33e163eb1d1c92ef5e44 closes
