### ISSUE TITLE
Move `/app/mirage` to `/mirage`

### ISSUE THREAD

**Issue by samselikoff** [samselikoff/ember-cli-mirage#49]
Is this possible?

**Comment by trabus** [comment]
As part of the config, there could be something like 'mirageRoot' or something like that where we would define the path to the mirage folder. For that matter, the fixtures and factories folder locations could be configurable (optionally of course) for different types of setups.

**Comment by g-cassie** [comment]
I think this would make it difficult to share mirage files across multiple ember addons.  A lot of ember devs are making a "common" ember addon that holds their models and is a perfect place to define a mirage config.  Then they have multiple apps which all use this addon allowing them to share common code.

**Comment by samselikoff** [comment]
Interesting point - but in that case, wouldn't it still be namespaced under your addon? i.e.

    `/your-addon/config.js`

instead of

    `/your-addon/mirage/config.js`

?

**Comment by g-cassie** [comment]
You can do either.  Addons have two directories "addon" and "app".  Files in "app" end up in the same namespace as the consuming application.  Files in "addon" end up in the addon's namespace.  Personally, I am defining all my factories in my common addon's "app/mirage/factories/" folder (would like to put routing config here as well but doesn't seem to work out of the box).  Then in my consuming applications I can call factories without any changes.

**Comment by trabus** [comment]
I wonder if it's possible to treat the `mirage` directory the same as `app` where any code in any addon's `mirage` directory would get picked up and bundled together in my build. 

I personally don't like having mirage code in my app folder, because it isn't part of my distributed app. I would prefer mirage code be organized separately.

**Comment by g-cassie** [comment]
Yeah could be a way forward - but can't quite wrap my head around how the dependency imports would work.

@samselikoff I just reread your comment and I think maybe I misunderstood your point...

**Comment by seawatts** [comment]
I also like the way my app will auto reload because the app dir is being watched. More of a nice to have than anything =P
