### ISSUE TITLE
passthrough all routes

### ISSUE THREAD

**Issue by khirakawa** [samselikoff/ember-cli-mirage#491]
Is it possible to passthrough all requests (including external)?

Right now, it seems the only way we can do this is to do:

```
this.passthrough();
this.passthrough('https://some.other.domain1.com/**');
this.passthrough('https://some.other.domain2.com/**');
this.passthrough('https://some.other.domain3.com/**');
```

and to use jQuery 2.x.

However, this requires prior knowledge of all the domains the application would hit.  This isn't too bad, but it would be nice if we didn't have to add another `passthrough` for each new domain.  

I tried something like the following, but it did not work.

```
this.passthrough('https://**');
this.passthrough('https://*catchall/**');
```

**Comment by samselikoff** [comment]
I don't believe so, this would be an API we'd need to add to [Pretender](https://github.com/pretenderjs/pretender) itself, I think.

Also FYI, if you upgrade your bower.json to the latest version of Pretender you should be able to use `passthrough` on jQuery 1.x.

**Comment by acorncom** [comment]
@samselikoff Is this something we want to keep open?  I'd prefer to close it and re-visit it if we find there's a pressing need in the future ...

**Comment by samselikoff** [comment]
Yep, this is something that'd need to be handled within Pretender.
