### ISSUE TITLE
Use Semantic Versioning for release numbers

### ISSUE THREAD

**Issue by jeradg** [samselikoff/ember-cli-mirage#494]
Love the work you're doing on the new ORM! I've been following the work on 0.2 closely. It's extremely helpful.

I was just reading the project update blog post where you mention that the new 0.2 release will include breaking changes. (http://www.ember-cli-mirage.com/blog/2016/01/03/0-2-update-only-inject-schema/)

package.json files rely on dependency version numbers that follow Semantic Versioning. That means that someone who declares a dependency on ember-cli-mirage ^0.1.0 won't be expecting 0.2.0 to break anything.

According to semver, a release with breaking changes should increment the major version number. That would make the upcoming ember-cli-mirage release v1.0.0.

So I suggest that the next release on ember-cli-mirage be marked as 1.0.0, and that following releases also follow semver. 

Thoughts?

**Comment by csantero** [comment]
According to https://github.com/mojombo/semver/blob/master/semver.md, any release in 0.y.z may introduce breaking changes, and the public API should not be considered stable. That being said, my personal preference is to allow breaking changes in 0.y.z to 0.y+1.z (0.1.0 to 0.2.0), but not from 0.y.z to 0.y.z+1. (0.1.1 to 0.1.2)

**Comment by jeradg** [comment]
@csantero Doi -- yes, of course you're right. Forgot about the exception of pre-1.0 releases. (I agree with the point re: 0.y+1.z vs. 0.y.z+1 and breaking changes, though that doesn't seem to be an issue with this project.)

**Comment by samselikoff** [comment]
Yes, I agree with what you're both saying here. Btw I know this is frustrating, but it felt like the project was going through too many changes for me to release a 1.0.

0.2 introducing breaking changes from 0.1, but I'm happy with where the API is now. After we close all the issues in the 0.2 milestone and release 0.2 proper, I'll want everyone to use it for a bit, and if things seem stable I will release a 1.0 soon after, so we can get proper semver into the release process.

**Comment by jeradg** [comment]
:+1:
