### ISSUE TITLE
Serializer isn't called on 0.2.0-beta.1

### ISSUE THREAD

**Issue by dopin** [samselikoff/ember-cli-mirage#498]
Hi,

I tried to use 0.2.0-beta.1 since [the document](http://www.ember-cli-mirage.com/docs/v0.2.x/serializers/) pointed out to the version.
But it didn't work.
Then, I tried to use the latest version from github. It just worked.

**Comment by dopin** [comment]
It occurs on master(4874f21bf6f476578f73d765148b7aacf3e2f861) too.

```javascript
// mirage/config.js
this.get('/post');
```

This works. But, 

```javascript
// mirage/config.js
this.get('/post', ({db}) => {
  return db.posts;
});
```

This doesn't evaluate serializers.

**Comment by samselikoff** [comment]
Yah, `db.posts` returns a "dumb" array of objects. The serializer layer works by serializing Models and Collections. So try this:

```js
this.get('/posts', ({post}) => {
  return post.all();
});
```

**Comment by dopin** [comment]
It works! Thank you.

Can I ask you one more question?
How can I return serialized json with additional fields like meta data?

**Comment by dopin** [comment]
I've posted an article to introduce ember-cli-mirage in Japanaese.
Article: http://qiita.com/dopin/items/9c8efac9536cb8cbd807
code: https://github.com/dopin/sacloud-ember/

Thank you for creating very useful and helpful tool! @samselikoff

**Comment by samselikoff** [comment]
Very cool, and you're welcome!

There's no "official" way to return meta currently. Perhaps try calling super in your serializer's `serialize` method and mutating it there, something like this:

```
serialize() {
  let json = Serializer.prototype.serialize.apply(this, arguments);
  // add meta to `json` and return
}
```

(we use Backbone's `extend` to do subclassing, so the `super` call is according to [the Backbone docs on calling super](http://backbonejs.org/#Model-extend).

**Comment by dopin** [comment]
Thank you! I'll try it.

**Comment by dopin** [comment]
It seems that works for each serialization of models but not for collections.
I could do by this workaround for collection.

```javascript
// mirage/config.js
  this.get('/server', ({server}) => {
    let json = this.serializerOrRegistry.serialize(server.all());
    json['Total'] = json.Servers.length;
    json['From'] = 1;
    json['Count'] = json.Servers.length;
    return json;
  });
```

**Comment by samselikoff** [comment]
Yep, `this.serializerOrRegistry.serialize` is the workaround for now. I should add this to the docs. Thank you!
