### ISSUE TITLE
Add `ModelClass.first()`

### ISSUE THREAD

**Issue by samselikoff** [samselikoff/ember-cli-mirage#501]
Add an API to models registered with `schema` to return the first model.

Given

```js
// mirage/models/user.js
import { Model } from 'ember-cli-mirage';

export default Model;
```

then I should be able to do

```js
this.get('/users/current', ({user}) => {
  return user.first();
});
```

**Comment by samselikoff** [comment]
Look at https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/orm/schema.js#L91-L102 to see `modelClass.find`'s implementation. `#first` should go right after, and look similar, but just using the first record.

**Comment by lependu** [comment]
Created #511 pull request.

**Comment by samselikoff** [comment]
#511 closes
