### ISSUE TITLE
Delete Request returns wrong status code

### ISSUE THREAD

**Issue by brownie3003** [samselikoff/ember-cli-mirage#502]
Hi Sam,

Probably you've fixed this on master, but using beta-1 the shorthand for delete returns the wrong response. i.e.

    this.del('projects/:id');

I think returns 200. Which causes jsonapi adapter in ember to throw an error. http://jsonapi.org/format/#crud
Deletes should return 204 if the are returning no data.
Deletes can return 200 if they are returning top level meta data. 

I've not investigated it that much, but I know that changing my route handler to this worked:

    this.del('projects/:id', (schema, request) => {
        schema.projects.remove(request.params.id);
        return new Response(204);
    });

Thanks for all the work on Mirage. It's great!

**Comment by samselikoff** [comment]
Yes sir, you are correct. Thank you for pointing this out!

**Comment by samselikoff** [comment]
What version of Ember Data? I'm actually not seeing the error (I think you're still correct, though).

**Comment by brownie3003** [comment]
ED 2.3.1
Mirage 0.2.0-beta.1

If you want to see an example it happens on this project when you use the shorthand for delete: https://github.com/brownie3003/moo-account

Thanks

**Comment by samselikoff** [comment]
Interesting, I just tried to reproduce with json:api on beta.3 and it
seemed to work without an error. Could you try upgrading to beta.3?

**Comment by brownie3003** [comment]
I've upgraded to beta.3 and it works. Both the get('/resource') and the del('resource/:id') shorthands work perfectly for me now. Thanks.
