### ISSUE TITLE
Unable to read the Adapter host configuration to set the urlPrefix

### ISSUE THREAD

**Issue by alexmasita** [samselikoff/ember-cli-mirage#503]
Hi Ember Community.

Is there an easy way of configuring Ember Cli Mirage to read the Adapter host to set the urlPrefix in the config.js file.  My use case is while still under development and regularly uploading to a remote server (as a production build), I want it to automatically read the host so as to continue serving mocks from Ember-Cli-Mirage without me having to manually change the config.js urlPrefix.

My Adapter host setting is as follows:

export default DS.RESTAdapter.extend({
  host: function () {
    if (ENV.environment === 'production') {
      return 'https://sarit-server.herokuapp.com';
    } else {
      return 'http://localhost:1337';
    }
		}.property().volatile(),
  namespace: 'api'
});

############################# Update #########################
I tried using the store service to retrieve the adapter host configuration like seen below:

********************************************
import {faker} from 'ember-cli-mirage';
import Ember from 'ember';

var store = Ember.inject.service('store');

export default function () {
  var host = store.adapterFor('application').get('host')
  this.urlPrefix = host;
}
********************************************
I found that the store object does appear to be returned because it is NOT null but for some reason, an error to the effect 'adapterFor' was not defined is generated.  Perhaps there is something I am missing.

###########################################################
Here below are my environment details
(a). ember cli version: "2.2.0-beta.2"
(b). ember-data: "^2.2.1"
(c). ember: "2.2.0"
(d). node: "0.12.7"
(e). npm: "2.14.10"
(f). os: "darwin x64 El Capitan"

**Comment by samselikoff** [comment]
Hm, you may need to ensure Mirage is initialized after Ember Data is all set up. This may involve tinkering with [Mirage's initializer](https://github.com/samselikoff/ember-cli-mirage/blob/master/app/initializers/ember-cli-mirage.js) (you should just be able to copy and past that file into your project and fiddle with it).

**Comment by alexmasita** [comment]
thanks. @samselikoff.  Will definitely try this.  But isn't it an important enough use case to have it load after ember data on initial installation rather than tinkering with it afterwards after installation?  Many thanks.
