### ISSUE TITLE
Can't define inverse relationships

### ISSUE THREAD

**Issue by thomasdashney** [samselikoff/ember-cli-mirage#504]
First of all, awesome project :)

I'm hoping to have an inverse relationship (as supported in Ember Data). For example:

```javascript
// in /mirage/models/User.js
export default Model.extend({
  projects: hasMany()
});
```

```javascript
// in /mirage/models/Project.js
export default Model.extend({
  user: belongsTo()
});
```

When I try to find a record through the schema, I get a maximum call stack exceeded. Is this something this add-on plans to support? Happy to contribute a PR if so! (created a failing test for this case)

**Comment by samselikoff** [comment]
Thank you! :smile:

This absolutely should work today, a PR with a failing test would be ideal. We could also start with a snippet of the code that's giving the error.

**Comment by samselikoff** [comment]
Ahhh... I believe it's the one-to-one that's causing the problem. (The code in your comment above, with one hasMany and one belongsTo should work).

I need to add an option to let the user specify which model owns the foreign key.

Thank you so much for bringing this up!

**Comment by samselikoff** [comment]
Do you have a 1-1 model in your server you're mocking out?

**Comment by thomasdashney** [comment]
It fails with a one-to-many relationship as well–I just pushed another failing test case for that into my branch.

I'm not developing this against a server.. I just started prototyping an app a few days ago and am probably not going to actually develop a server for a bit. Mostly using ember-cli-mirage for some text fixtures to get up and running quickly! Working like a charm so far

**Comment by samselikoff** [comment]
In your db setup, you only need one foreign key. Mirage assumes the `belongsTo` owns the foreign key.

In your second test, could you remove the `projectIds` from the user and see if that fixes it? `user.projects` should still work, since it looks for all projects with a matching `userId`.

Also, in your first test, remove the `addressId` from the user.

**Comment by thomasdashney** [comment]
Ok, just made the test changes and one-to-many works now. Still having a problem with the one-to-one (`address.user` should exist right?)

**Comment by samselikoff** [comment]
Yah I believe one-to-one won't work right now, I need to allow user to say "this model owns the fk of this one-to-one relationship". For now I'd say stick to a one-to-many, if you can.

**Comment by thomasdashney** [comment]
Cool, will do. Thanks for your help :smile:

**Comment by samselikoff** [comment]
Let me know if you have any more questions

**Comment by ivanbanov** [comment]
Any other workaround for a while for one-to-one relationship? I'm having the same problem here

**Comment by samselikoff** [comment]
I would say, just munge the data in your `serialize` method for now by [overriding super](http://www.ember-cli-mirage.com/docs/v0.2.0-beta.7/serializers/#serializeresponse-request). I actually wrote `hasOne`, I just need to integrate it with the serializer layer. I think this takes lower precedence than the upcoming breaking serializer changes, though.

**Comment by mariogintili** [comment]
#943 possible related to
