### ISSUE TITLE
AMS#normalize is not handled correctly

### ISSUE THREAD

**Issue by martndemus** [samselikoff/ember-cli-mirage#506]
The `PUT`/`POST` shorthand methods don't handle normalizing the request payload very well.
The payload is first normalized by the `SerializerRegistry` :
https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/serializer-registry.js#L26-L29
```js
normalize(payload) {
  let model = payload[Object.keys(payload)[0]];
  return this._serializerFor(model.modelName).normalize(payload);
}
```

This correctly picks of the first key from the payload, but then trys to get `modelName` from the AMS payload, which if it is correct AMS, will never be there, so the AMS#normalize method will never be called.

**Comment by samselikoff** [comment]
You're absolutely correct. I think the reason I missed this is, `model.modelName` will always return `undefined`, so `serializerFor` will default to returning the `ApplicationSerializer`. If that's defined (under `/serializers/application`), the normalization will generally work. But this is definitely broken.

**Comment by samselikoff** [comment]
I'm curious, how did you come across this bug? Did you have an application serializer defined?

**Comment by martndemus** [comment]
The `ApplicationSerializer` is a `JSONApiSerializer`, I need the AMS serializer for a few models on older endpoints.

**Comment by samselikoff** [comment]
Perfect, makes total sense. Should be fixed in master!
