### ISSUE TITLE
Duplicated ForeignKeys in schema

### ISSUE THREAD

**Issue by ajcobo** [samselikoff/ember-cli-mirage#507]
When multiple relationships are defined:

````javascript
 var User = Model.extend({
    projects: Mirage.hasMany(),
    tasks: Mirage.hasMany()
  });

  var Project = Model.extend({
    user: Mirage.belongsTo(),
    tasks: Mirage.hasMany()
  });

  var Task = Model.extend({
    user: Mirage.belongsTo(),
    project: Mirage.belongsTo()
  });
````

In this case in `schema._registry`:

* User will not have foreignKeys 
* Task will have 2 foreignKeys: userId and projectId
* **Project will have 2 foreignKeys userId**

I've noticed that this gets worse with complex models.

I'm more than willing to create a PR for this.

Where should I add the tests?

**Comment by samselikoff** [comment]
Should be all set, and now we have a test where we can add any future regressions related to fks if they show up. Thank you!

**Comment by ajcobo** [comment]
Awesome Sam, thank you!
