### ISSUE TITLE
Memory leaks because of Pretender request tracking

### ISSUE THREAD

**Issue by simonihmig** [samselikoff/ember-cli-mirage#509]
I am having some issues with the fact that pretender is keeping a record of all requests it intercepted, which is never cleared (https://github.com/pretenderjs/pretender/blob/master/pretender.js#L299). So all data coming through pretender is effectively locked from garbage collection.

From the view of pretender it is certainly "a feature, not a bug" (TM), as this is intended this way. And this is probably acceptable for short lived application runs for testing. But an important use case for mirage - at least from my point of view - is to be able to develop and play with your app without having to run a real API backend. So not freeing up those resources can pile up memory consumption considerably if the payload is big enough.

In my case it is about many passthrough requests loading a number of quite large assets (>1MB WebGL textures and 3D data). Obviously I don't need mirage/pretender for those, but as I need to mock my JSON API requests, I configured those asset requests as passthrough requests. As said those request payloads will never be garbage collected. No problem for production, not a big problem for desktops, but mobile clients will crash regularly because they run out of memory.

Probably a rather special case here, but still annoying, at least for me! :) Any ideas how to solve this?

**Comment by bekzod** [comment]
is this a solution #510 ?

**Comment by simonihmig** [comment]
Works for me. Just wondering if this may cause problems in the future, as it modifies private data of  the pretender object. Might be better to have a pretender option to opt out of request tracking?

**Comment by bekzod** [comment]
there is no such api in pretender to `opt out tracking` at the time of writing, will try to submit PR with such functionality

**Comment by simonihmig** [comment]
Yeah, I know. That was actually my question, if it would be better to get this functionally implemented in pretender itself instead of patch ing it...

**Comment by bekzod** [comment]
it depends how fast `pretender` maintainers will respond and react to change, for now we can monkey patch it I think and remove it once `pretender` has it covered

**Comment by bekzod** [comment]
added PR not sure if I did it right way as there was no way passing options variable to pretender before

**Comment by samselikoff** [comment]
It looks like those methods just store the fake request object, and not the response. If I'm not mistaken the actual responses from your backend should not be stored anywhere within Pretender or Mirage.

Could you check and see if you have the same memory issues when running your app without Mirage (and thus Pretender) enabled? There have been some known memory leaks within Mirage, but they've typically cropped up when running tests, rather than during development.

**Comment by simonihmig** [comment]
Yes, but the xhr request object contains the response in its `response` property. See the attached screenshot of a heap snapshot in Chrome. It shows that the requests stored in Pretender contain a reference to the response (ArrayBuffer in this case). The other screenshot show the retainers of the ArrayBuffer object, which all seem to have their root in the `passthroughRequests` array of Pretender.

When disabling mirage, the memory leak does not occur, I already tested that! (Well, at least after fixing some other own memory issues ;))

![image](https://cloud.githubusercontent.com/assets/1325249/12547661/de816930-c351-11e5-8223-f61831d1b316.png)

![image](https://cloud.githubusercontent.com/assets/1325249/12547774/785e92ee-c352-11e5-9ed0-ded29496fa32.png)

**Comment by samselikoff** [comment]
Ah I see. Yes we should get this upstream into Pretender, I've commented on @bekzod's PR there
