### ISSUE TITLE
request is undefined in serialize(response, request)

### ISSUE THREAD

**Issue by ballPointPenguin** [samselikoff/ember-cli-mirage#519]
I am probably just missing something, but it seems to me that in my serializers, in the serialize() hook, the 'request' parameter is always undefined.
I was expecting it to contain the queryParms and whatnot from the 'request' object in my route handlers.

**Comment by 2468ben** [comment]
I found that too yesterday, here's a PR to try out if you want: https://github.com/samselikoff/ember-cli-mirage/pull/515

**Comment by ballPointPenguin** [comment]
Closed in favor of https://github.com/samselikoff/ember-cli-mirage/pull/515
