### ISSUE TITLE
Add option to run Mirage in test environment only

### ISSUE THREAD

**Issue by samselikoff** [samselikoff/ember-cli-mirage#52]
Even if someone isn't using `--proxy` they may want to disable Mirage in development. Let's add an option that lets them do this.

```
// config/environment.js
ENV['ember-pretenderify'] = {
  enableInTestingOnly: true
}
```

We'll need to modify `index.js` [here](https://github.com/samselikoff/ember-cli-mirage/blob/master/index.js#L36) as well as the initializer [here](https://github.com/samselikoff/ember-cli-mirage/blob/master/app/initializers/ember-cli-mirage.js#L12).

As a side note, is there a way to ignore that initializer based on something in the index.js? Seems like we're duplicating some logic.

**Comment by trabus** [comment]
How would you feel about a pattern where we define a list of enabled environments like so:
```js
// config/environment.js
ENV['ember-cli-mirage'] = {
  enabledEnvironments: ['test','development'] // add 'production' if you want to run in production
};
```
Then match against the current environment to determine if 
```js
// ember-cli-mirage/config/environment.js
function enabledEnvironment(environment, appConfig) {
  var environments = appConfig['ember-cli-mirage'] && appConfig['ember-cli-mirage].enabledEnvironments || ['test','development'];
  return environments.indexOf(environment) > -1;
}
appConfig['ember-cli-mirage']['enabledEnvironment'] = enabledEnvironment(environment, appConfig);
```
Then we can just use the enabledEnvironment property of the config object. I've tried it out and it seems to work pretty well so far.

**Comment by samselikoff** [comment]
I like this, but, I still like the default behavior i.e. I think someone should be able to have Mirage run, but if they add `--proxy` it should not run. 

What if we add `enabledEnvironments` and `disabledEnvironments`? Then, 

 - if neither are present, default behavior
 - if env is in enabledEnvironments, always enable
