### ISSUE TITLE
Deprecate Object Handler

### ISSUE THREAD

**Issue by samselikoff** [samselikoff/ember-cli-mirage#525]
There's an edge case where an API in Mirage's route handler definition can be ambiguous.

Mirage has an Object route handler, which lets you write this:

``` js
this.del('/posts/:id', {errors: ['something happened']});
```

The idea being, I just want to return some `{}` object when this request hits this path. Often you'll see it paired with the status code:

``` js
this.del('/posts/:id', {errors: ['something happened']}, 404);
```

but not necessarily

``` js
this.get('/sessions/current_user', {user: {id: 'current'});
```

All route handlers (function, object and shorthand) also have the notion of an options hash that can be passed in at the end. Currently, there are two options available to route handlers, `coalesce` and `timing`.

Here's what it looks like when passed into a shorthand:

``` js
this.post('/comments', {timing: 1500});
```

You can see the problem: when the last param is an object, how does Mirage know if it's an Object route handler or an options hash?

Currently, we know [by checking if the last object has either of the two available options properties](https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/server.js#L55-L66), `coalesce` or `timing`. Of course, this means you couldn't use the Object handler to do something like this:

``` js
this.get('/a_thing', {timing: 'blah'});
```

because Mirage would read that in as an options hash rather than a response value.
## Possible solutions
1. Deprecate & remove object handler. Tell people if they want to return an object, to just use a function:
   
   ``` js
   this.del('/posts/:id', () => {
     return {errors: ['something happened']};
   }, 404);
   ```
   
   This is kinda crappy because
   
   ``` js
   this.del('/posts/:id', {errors: ['something happened']}, 404);
   ```
   
   is really nice, especially in tests. But tbh, not that bad.
2. Require users to pass in the status code when using the object handler. This would allow us to unambiguously determine if an options hash is present, as it would always come after the status code (an integer).
3. Other options?

---

What are y'alls thoughts?

**Comment by bekzod** [comment]
option is last argument if they want to opt-out from shorthand being counted as option they can do `this.get('/a_thing', {timing: 'blah'}, null);` maybe we can warn user in edge cases like this

**Comment by 2468ben** [comment]
I'd vote for solution #1 mainly because the function could get one-lined like:
```this.del('/posts/:id', () => ({errors: ['something happened']}), 404);```
and then it isn't *too* bad compared to the current way, as long as folks are fine with ES6.
But I'm also not using it for quick dev prototyping, where quick return objects would be the most useful.

**Comment by mangatinanda** [comment]
@samselikoff currently the below code doesn't set the delay for the route
```
this.get('/comments', () => { return commentsData }, {timing: 2000});
```
How can specify timing parameter for specific route? 
pardon me, I couldn't find it in the documentation.

**Comment by samselikoff** [comment]
@mangatinanda that feature was added in 0.2.0-beta.3 (or beta.2), you can find the docs here:

http://www.ember-cli-mirage.com/docs/v0.2.0-beta.3/route-handlers/#timing

What version of Mirage are you on?

**Comment by hbrysiewicz** [comment]
This turned out to not be a big problem for anyone yet, and the object shorthand is used frequently enough that it’s nice to keep around. If someone wants to return an object with `timing` in the root, they can use the function handler easily enough.
