### ISSUE TITLE
Ember Data to Mirage Factory Mapping

### ISSUE THREAD

**Issue by mellatone** [samselikoff/ember-cli-mirage#527]
I am about to start writing an ORM of sorts that acts as an interface between a project's models directory and mirage factories. One of the primary use cases will be to handle mapping _required_ relationships between models. We have a relational data model that needs atomic groups of models. Some of these relationships are optional, and some are always required for testing.

Is there a feature that implements something like this?

**Comment by mellatone** [comment]
I found #460 and feel that feature is closely aligned to what I need.

**Comment by samselikoff** [comment]
Yep, though you should know it's a bit of a ways off.

If by required relationships you mean something like a `lesson` is only ever valid if it has a `video`, such that you're doing things like

```js
let lesson = server.create('lesson');
server.create('video', {lesson_id: lesson.id})`;
```

a lot in your tests, you should know factory relationships are designed to solve this exact problem, and will be my highest priority after we ship 0.2.0.
