### ISSUE TITLE
Use key instead of modelName for foreign keys

### ISSUE THREAD

**Issue by samselikoff** [samselikoff/ember-cli-mirage#528]
From https://github.com/samselikoff/ember-cli-mirage/issues/443#issuecomment-172881023

/cc @cs3b

**Comment by 2468ben** [comment]
I was generalizing the hasmany/belongsto tests so I can try different schemas, and found the issues related to this. I'll throw up a PR for the generalized tests and maybe you can use it to test the weird scenarios.

**Comment by 2468ben** [comment]
Specifically, I think I can solve all of them by allowing an inverse option like Ember Data's:
```responseIds: Mirage.hasMany('comment', {inverse: 'parent'})``
that could also help with the 2 associations / 1 model issue (#350)
At least if I get it working that way, you can refactor it and there will be lots of tests to help.

**Comment by samselikoff** [comment]
I actually started working on this this morning, it's pretty complicated but I should have it done soon

**Comment by samselikoff** [comment]
I think #350 is done actually

**Comment by samselikoff** [comment]
https://github.com/samselikoff/ember-cli-mirage/pull/546

**Comment by 2468ben** [comment]
awesome, thanks!

**Comment by samselikoff** [comment]
@2468ben just merged this in, master if you want to give it a go!

**Comment by 2468ben** [comment]
@samselikoff works great everywhere I've tried it, thanks again!
