### ISSUE TITLE
`keyForRelationship` hook does not work as expected

### ISSUE THREAD

**Issue by camhux** [samselikoff/ember-cli-mirage#529]
Using 0.2.0-beta.3, I'm working on mocking a JSON:API back-end whose specs call for snake case in the data objects' keys. Here's how I tried to set it up:
```
import JsonApiSerializer from 'ember-cli-mirage/serializers/json-api-serializer';
import Ember from 'ember';

let { underscore } = Ember.String;

export default JsonApiSerializer.extend({
  keyForModel: underscore,
  keyForCollection: underscore,
  keyForAttribute: underscore,
  keyForRelationship: underscore
});
```
This snakeifies attribute names as expected, but relationships (both within the primary records and in sideloaded/included records) do not have their names transformed from kebab case. I tried setting the `keyForRelationship` value to a function with a debugger statement and never reached it.

It looked like the invocation of `keyForRelationship` lives in a different section of the source than the invocations of `keyForAttribute`, and I saw the comments about the serializer architecture possibly changing soon, so I understand that these hooks might not be wired up in final form yet.

**Comment by samselikoff** [comment]
Thank you for reporting, I'll look into this.

**Comment by samselikoff** [comment]
This should be fixed in master, give it a shot + let me know if you still run into problems!
