### ISSUE TITLE
Cannot sort relationships

### ISSUE THREAD

**Issue by richmolj** [samselikoff/ember-cli-mirage#533]
Let's say you have a `Post` with many `Comment`s. The user can sort comments by `author_name`. If you do something like:

``` es6
comments = db.where({post_id: postId}).toArray().sort(function(a,b) {
  return a.author_name < b.author_name ? -1 : 1;
});
post.comments = comments;
```

The response, or any further calls to `post.comments`, will not be sorted. I believe this is because [the getter fires .where again](https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/orm/associations/has-many.js#L95-L97), blowing away the sort. Is this something mirage can support?

**Comment by samselikoff** [comment]
Are you saying you want to sort the comments in the actual db collection? If so, why? Can you sort them in the route handler?

**Comment by richmolj** [comment]
I am attempting to sort them in the route handler. I am on master using a JSONAPI serializer, so my route would look something like:

```es6
this.get('/posts/:id', function(schema, request) {
  let postId = params.id;
  let post = schema.post.find(postId);

  sortedComments = db.where({post_id: postId}).toArray().sort(function(a,b) {
    if (request.queryParams.sort === '-author_name') {
      return a.author_name < b.author_name ? -1 : 1;
    } else {
      return a.author_name > b.author_name ? -1 : 1;
    }
  });
  post.comments = sortedComments;

  return post;
});
```

The serializer will end up calling `post.comments` again, which will blow away the sort.

Is there a better way to handle this scenario?

Thanks!

**Comment by samselikoff** [comment]
I assume this is because you're using `include` in your serializer?

Yes, the problem is `db.comments.where...` actually returns a copy of the data in the database (to prevent that data from being inadvertently manipulated).

I think the easiest way to handle this for now would be to sort the data after it's been serialized:

```js
import Serializer from './application';

export default Serializer.extend({

  include: ['comments'],

  serialize(object, request) {
    // call super
    let json = Serializer.prototype.serialize.apply(this, arguments);

    // sort comments here using request.queryParams.sort

    return json;
  }

});
```

**Comment by richmolj** [comment]
This looks like it would work, thanks. It **is** kind of confusing though. If this was, for instance, a Rails app, you would be applying the sort when fetching from the database, not when serializing. Maybe just a note in the readme or something, since sorting seems like a pretty common use case.

**Comment by samselikoff** [comment]
yes... you could sort the primary collection in the route handler, but if I'm understanding this is an included resource? How would you sort that in rails?

**Comment by richmolj** [comment]
I think the usual way would be

```ruby
class Post < ActiveRecord::Base
  has_many :comments
  has_many :sorted_comments, order: :created_at
end

class PostsController < ApplicationController
  def index
    posts = Post.includes(:sorted_comments)
    render json: posts
  end
end
```

It's probably more helpful to give my real-world example though. I have a `Search` object that has `results` as a relationship:

```ruby
class Search < ActiveRecord::Base
  # search has conditions and such as well, removed for brevity
  attr_accessor :results
end

class SearchesController < ApplicationController
  def update
    search = Search.find(params[:id])
    search.results = query_elastic_search
    render json: search, include: [:results]
  end
end
```

So I'm actually assigning `search.results` directly. I'm using [active_model_serializers](https://github.com/rails-api/active_model_serializers), so my serializer object looks like:

```ruby
class SearchSerializer < ActiveModel::Serializer
  has_many :results
end
```

I think the big difference between AMS and Mirage here is `results` isn't an ActiveRecord association, it's just an accessor that I want serialized in `include`. Mirage treats these as the same concept, which is where I end up getting in trouble with sorting (since I can't use the DSL to order the association, and I can't directly assign the association without losing the sort later on).

Maybe ordering of relationships is too edge-casey to focus on, so maybe a different way to look at this issue is to support serializing POJOs. In this case I would have been able to do something like:

```es6
this.put('/search/:id', function(schema, request) {
  let search = {
    results: db.posts.all().sortBy('name')
  }

  // Something that supports passing a serializer so I can 'include'
  renderJSON(search, serializer: SearchSerializer);
});
```

I think your serializer suggestion works for now, but just sending feedback on different scenarios that might start being problematic. Thanks!

**Comment by samselikoff** [comment]
Yes, thank you for reporting, it's really good to hear the pain points people are running into.

I have an issue open for supporting an inline/each serializer directly in the route handler, similar to what you've posted.

One issue with the serializer/include example you've posted is, once you're returning just plain POJOs/POJAs, we don't have type information, so we can't look up includes anymore. Do you see a way around this? In your last search example, what would `SearchSerializer` include?

**Comment by richmolj** [comment]
> we don't have type information, so we can't look up includes anymore

I think this is a small misspeak based on my above example - we'd need `type` for the POJO but not the `include` (since the included objects are DB objects). Let's say I have a `peopleSearch` POJO with a `results` array on it, and each result is a DB object

```es6
this.put('/searches/:id', function(schema, request) {
  let search = { id: request.id };
  search.results = schema.person.all(); // I would filter like a search here, removed for brevity

  // specifying the serializer somehow
  return new peopleSearchSerializer(search, { include: ['results'] });
});
```

And I had a serializer:

```es6
import { Model, hasMany } from 'ember-cli-mirage';

export default Model.extend({
  results: hasMany('person');
});
```
I know now `data.relationships.results` is an array of `person` DB objects, so I know the relevant `id` and `type` to fill out here.

What I **don't** know is the `type` for the `search` POJO, or the `type` if `results` were not DB objects. AMS handles this in the serializer, and each association can specify its serializer:

```ruby
class SearchSerializer < ActiveModel::Base
  # If the search results come back as DB objects their serializer can be inferred
  has_many :results

  # If the search results are hashes/POROs I need to specify a serializer
  # The serializer specifies the type
  class ResultSerializer < ActiveModel::Serializer
    # I believe there is active work to make 'type' part of the public API before AMS 1.0
    def _type
      'search/result'
    end

    def attributes
      object.as_json # tell AMS how to render a hash/PORO
    end
  end
  has_many :results, serializer: ResultSerializer

  # If I want this to be an attribute instead of an 'include', with POROs
  attributes :results
  def results
    object.results.map do |r|
      ActiveModel::SerializableResource.new(r, serializer: ResultSerializer).as_json
  end
end
```

So really it comes down to A) a public `type` method as part of the serializer API B) when a serializer specifies relationships, optionally specify a serializer for that relationship (in addition to the current work to specify a serializer in the route).

Of course, this is all to avoid the refetching logic :smile: . I wonder if that logic could maybe work more like the current `_cachedChildren` code - where the setter sets `_internalChildren`, and the getter returns a copy/new collection of `_internalChildren` versus refetching from the DB. I am thinking this type of pattern would preserve the sort order. Does that make sense to you?

**Comment by samselikoff** [comment]
I think so.. I need to think about this a bit more, because it seems like filtering, sorting and meta are all coming up and we should decide whether to solve them in route handlers or serializers.

I definitely plan on adding filtering/sorting support to JSON:API Serializer.

We need the ability to explicitly specify a serializer in the route handler anyway, so that might solve some of this. Also, we could update the `include` piece on Serializers to first check for local accessors, and then fall back to the default relationship. That's another vector that might solve some of this.

**Comment by samselikoff** [comment]
Filing under "Standard way to handle filtering/sorting/pagination" card in the Roadmap project.
