### ISSUE TITLE
Shorthand base incorrectly asserts an error with no data.attributes requested

### ISSUE THREAD

**Issue by nbibler** [samselikoff/ember-cli-mirage#534]
I know this is a bit of a strange case, but if you create an Ember Data Model which contains no local attributes (a join model is an example where there are no local attributes, but there may optionally be relationships defined), then the [`shorthands/base.js#_getAttrsForRequest`](https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/route-handlers/shorthands/base.js#L86-L89) incorrectly fails by asserting a false error.

``` javascript
import DS from 'ember-data';

export default DS.Model.extend({
  option: DS.belongsTo('option'),
  poll: DS.belongsTo('poll'),
});
```

With a join model as described, Ember Data generates a JSON:API request that looks similar to:

``` json
{
  "data":{
    "relationships":{
      "option":{
        "data":{
          "type":"options",
          "id":"1"
        }
      },
      "poll":{
        "data":{
          "type":"polls",
          "id":"1"
        }
      }
    },
    "type":"votes"
  }
}
```

Notice there is no `data.attributes` key in the request.

The `shorthands/base.js` falsly asserts that a JSON:API request **must** contain `data.attributes` when the spec states that [it is optional](http://jsonapi.org/format/#document-resource-objects)  by describing that a request MAY include it:

> In addition, a resource object MAY contain any of these top-level members:
> attributes: an attributes object representing some of the resource's data.

Modifying the `base.js` to read something like the following seems to fix the issue. I attempted to throw together a PR but had a difficult time trying to find where a failing test should fit into the existing suite.

``` javascript
    assert(
      jsonApiDoc.data,
      `You're using a shorthand but your serializer's normalize function did not return a valid JSON:API document. http://www.ember-cli-mirage.com/docs/v0.2.x/serializers/#normalizejson`
    );

    jsonApiDoc.data.attributes = jsonApiDoc.data.attributes || {};
```

**Comment by samselikoff** [comment]
You're absolutely correct - thanks for taking the time to open this!

Some of those "private" methods are complex enough to get unit tests [here](https://github.com/samselikoff/ember-cli-mirage/blob/master/tests/unit/route-handlers/shorthands/base-test.js). Why don't we add a single regression test there? You can just use POJOs to stub out `schema` and `serializerOrRegistry`. Make the `serializerOrRegistry.normalize` function on the stub a noop.
