### ISSUE TITLE
[0.2.0-beta.3] Relationships get created in the schema, but not the application (serializer / JSONAPI problem?)

### ISSUE THREAD

**Issue by promisedlandt** [samselikoff/ember-cli-mirage#537]
used versions:
ember 2.3.0
ember-data: 2.3.3
ember-cli: 1.13.15
ember-cli-mirage: 0.2.0-beta.3

This is a bit of a strange issue, and I'm not sure how I can give you a test case to reproduce, but here goes:

I'm using Mirage to create Eras, which have many Nations.  
That appears to work fine, if I put a debugger breakpoint in my route handler I can see the eras, and each era has their created nations, exactly as expected.  
I can also see in the Ember Inspector that  the models are indeed created in the ember application.

However, the relationship between the models appears to have been lost, and the list of the nations on the era page is empty.  
I can't 100% confirm this since I haven't found how to resolve the belongsTo or hasMany promises in the Ember Inspector.

My best guess is that there's a problem with the JSONAPI serializer, so the models do get created correctly, but the relationship doesn't. That would kind of make sense since the JSON format in the documentation does not match the JSON my application generates, regardless of `embed` setting.

If I turn off Mirage in development and hit my application, everything works as expected.

This happens both in the acceptance test as well as in manual development with the default scenario.

Do you have any ideas? If not, I'll try to upload the Ember application and see if it runs without the backend.

**Comment by samselikoff** [comment]
Can I see the response for your Ember app's request, perhaps a screenshot of the console?

Also, here's how you can use the inspector to see if relationships are properly wired up:

![inspector](https://cloud.githubusercontent.com/assets/2922250/12740925/f8bd8302-c945-11e5-8189-bd4315f55b1f.gif)

Hope that helps!

**Comment by promisedlandt** [comment]
Thank you very much for the quick reply. Using the console with the Inspector is amazing, I didn't know about that.

This is a screenshot of my console:

![2016-02-02--1454392883_1719x888_scrot](https://cloud.githubusercontent.com/assets/557201/12741239/e86abe54-c97a-11e5-9f7b-826b5b3b7d32.png)

Unfortunately, my hasMany relation is not a DS.ManyArray, but <computed> (possibly because the name of the relation is not the same as the name of model: `nations: DS.hasMany "dominions4-nations"`):

![2016-02-02--1454393010_1721x404_scrot](https://cloud.githubusercontent.com/assets/557201/12741286/36eeec62-c97b-11e5-9072-75f46412085d.png)

There are 45 nations created which is what I wanted (3 eras, 15 nations each), but they are not assigned to the eras:

![2016-02-02--1454393470_1718x432_scrot](https://cloud.githubusercontent.com/assets/557201/12741423/658fdc92-c97c-11e5-889f-86afd2373998.png)

Apparently they do not belong to any era:

![2016-02-02--1454393533_1718x433_scrot](https://cloud.githubusercontent.com/assets/557201/12741421/5796b76e-c97c-11e5-9f7b-2dc386cb11fe.png)

I'll upload the ember application to Github. Reproducing would then be as simple as checking out the project, running `ember serve` and clicking one link, thanks to Mirage.

**Comment by promisedlandt** [comment]
I have uploaded the ember project [here](https://github.com/promisedlandt/ember-dominionsserver).
Running it and opening the root is enough to reproduce.

**Comment by samselikoff** [comment]
Thanks for uploading. As I suspected the problem is the mismatch between the property name (e.g. `nations`) and the name of the model (`dominions4-nations`). You should match your Mirage model definitions with your models on the frontend:

```diff
  // mirage/models/dominions4-era.js
  import { Model, hasMany } from 'ember-cli-mirage';

  export default Model.extend({
-   dominions4Nations: hasMany()
+   nations: hasMany('dominions4-nation')
  });

  // mirage/models/dominions4-nation.js
  import { Model, belongsTo } from 'ember-cli-mirage';

  export default Model.extend({
-   dominions4Era: belongsTo()
+   era: belongsTo('dominions4-era')
  });

  // mirage/serializers/dominions4-era.js
  import BaseSerializer from "./application";

  export default BaseSerializer.extend({
-   include: ["dominions4Nations"]
+   include: ["nations"]
  });
```

That got it working for me.

**Comment by promisedlandt** [comment]
Yes, that fixes it.
Thanks again, I appreciate your time, especially since it was my mistake and not a Mirage problem.

I've created a pull request to update the documentation so others will not fall in the same trap (I didn't see an option to specify a model name, which is why my mirage models differed from my ember models).

**Comment by samselikoff** [comment]
You're welcome, and thanks for your time + PR!
