### ISSUE TITLE
Conflicting documentation for creating related data in scenarios

### ISSUE THREAD

**Issue by Keeo** [samselikoff/ember-cli-mirage#538]
In [Associations and serializers](http://www.ember-cli-mirage.com/docs/v0.2.0-beta.3/quickstart/#associations-and-serializers) there is section about creating related data:
```
let author = server.create('author');
author.createBlogPost({title: 'My first post'});
```
Which is in conflict with [Using-factories-in-development](http://www.ember-cli-mirage.com/docs/v0.2.0-beta.3/seeding-your-database/#using-factories-in-development)
```
let author = server.create('author', {name: 'Zelda'});
server.createList('blog-post', 20, {authorId: author.id});
```

Is the server instance passed to `scenarios/default.js` different from the one in first documentation? I am not able to use approach from first documentation because `create` returns plain object and `createBlogPost` is then undefined.

**Comment by samselikoff** [comment]
Ah yes, you're absolutely right. I'm not sure how I missed this.

We do have an open issue for factories to return models, but using the model methods (e.g. `author.createBlogPost`) would _not_ populate the new models with the factory attributes. So, the recommended way will be via `server.create`.

It should be a bit simpler once we rework the factory layer, but this is the recommended way for now. I'll update the docs.

**Comment by samselikoff** [comment]
And, thank you for bringing this up!

**Comment by samselikoff** [comment]
6a03a9adc0084b7e89a7cef9d6caa588d7a35b52 closes
