### ISSUE TITLE
Subdirectories are not supported

### ISSUE THREAD

**Issue by kevintraver** [samselikoff/ember-cli-mirage#540]
When running:

 `ember g mirage-model foo/bar`

The following error occurs when trying to access the route:

`Assertion Failed: Subdirectories under foo are not supported`

A related question:

How would you see Pods structure working with ember-cli-mirage?

Thanks!

**Comment by samselikoff** [comment]
It looks like they aren't supported by default - have you seen any other addons use this? Also, have you tried creating the file manually? It may just be the generator that doesn't work.

I haven't thought about pods and Mirage. I use pods in my Ember apps and Mirage's default structure suits me. Any particular problem you're facing?

**Comment by mattmarcum** [comment]
@samselikoff  the generator works fine and doesn't throw any errors.  That assertion gets thrown by the ember-cli-mirage initializer when its reading in the modules on application boot up in the browser.

**Comment by kevintraver** [comment]
@samselikoff I was just thinking Pods because if you have nested resources in your app, then it would be awesome if Mirage reflected that structure as well.

I guess a potential issue would be if you have two models with the same name under different namespaces.

**Comment by samselikoff** [comment]
I see. We should definitely support nested resources. I'm focused on other 0.2.0 issues at the moment, so if anyone else wants to spearhead this, I would start by taking a look at [options.models](https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/server.js#L107) in the Server constructor, and what ends up in `schema._registry` after all the models are [registered](https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/orm/schema.js#L16).

**Comment by samselikoff** [comment]
Filing under the "Subdirectory support" card on the Roadmap project.
