### ISSUE TITLE
Mirage creating new id rather than using client-generated id

### ISSUE THREAD

**Issue by lkhaas** [samselikoff/ember-cli-mirage#548]
I'm using generateIdForRecord in a DS.Adapter to pass a client-side generated id when creating.  Mirage is generating it's own id value when it stores the record causing Ember to return the error "An adapter cannot assign a new id to a record that already has an id." when the payload returned uses a different id than the id already specified on the DS model.  I've verified that the "id" is passed within the payload as expected.

**Comment by jherdman** [comment]
Is this using the new Mirage 0.2 betas?

**Comment by lkhaas** [comment]
I just updated to the latest beta (0.2.0-beta.3) and tested again with the same result.  Previously I was on a fork of one of the 0.2 betas.

**Comment by jherdman** [comment]
Would you be able to produce a failing test that shows this edge case? There are provisions in the DB's [IdentityManager](https://github.com/samselikoff/ember-cli-mirage/blob/64856ee6cc6085e0d727bcb08daf693083230d16/addon/db-collection.js#L223) to allow for setting, and a few test cases ([example](https://github.com/samselikoff/ember-cli-mirage/blob/64856ee6cc6085e0d727bcb08daf693083230d16/tests/unit/db-test.js#L154-L160)). That indicate this functionality should be working as expected.

I'm not terribly familiar with DS Adapter's `generateIdForRecord`, so I could use a hand :)

**Comment by lkhaas** [comment]
I'm trying to figure out a test case (I'm new to ember mirage), but I think I see the problem in the code.  The check for an id is only looking at the request parameters.  https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/route-handlers/shorthands/base.js#L49

But the id is actually set within the request body.  It is sent in the JSONapi document that is parsed out here: https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/route-handlers/shorthands/base.js#L49

For example, by data (jsonApiDoc variable) looks like:
`{
  data {
    attributes: {
      label: 'test'
    },
    id: 'my-client-side-id',
    type: 'my-model-type'
  }
}`

**Comment by jherdman** [comment]
Whoa! Very interesting. Are you good to go from here at this point, or do you need a hand putting together a pull request? I'm more than happy to help if need be.

**Comment by lkhaas** [comment]
I just started to put one together but I noticed that the id gets forced to an integer.  This wouldn't be the case with client-side generated ids, necessarily.  Do you know if there is a requirement that ids be integers for mirage tables?

**Comment by jherdman** [comment]
I think you just found a second bug by accident. Theoretically all IDs in Mirage should be treated as strings (see #462). This parsing shouldn't be happening.

**Comment by lkhaas** [comment]
Yay - my first pull request for an Ember project :)

**Comment by jherdman** [comment]
Congrats! :cake: 

The only thing I'd recommend is noting in your commit message why you're removing the ID integer parsing, or at least noting that it should have been removed in #462 .

**Comment by lkhaas** [comment]
Thanks - valid point :+1:
