### ISSUE TITLE
allow individual routes to change timing

### ISSUE THREAD

**Issue by samselikoff** [samselikoff/ember-cli-mirage#55]
should be able to pass in a timing parameter to individual routes

**Comment by bianjp** [comment]
Really look forward to it.

**Comment by bekzod** [comment]
@samselikoff I think this was not mentioned in changelog :)

**Comment by samselikoff** [comment]
@bekzod good catch! I just tested this out, this is so cool. Going to add to the docs.

**Comment by samselikoff** [comment]
Added to [changelog](de3438eb7ea2a87054160ca90b6ad43433a6b100) and [docs](aa5969f09aabc227fa711ffe435e31909ec1863f).
