### ISSUE TITLE
Mocking metadata information

### ISSUE THREAD

**Issue by bttf** [samselikoff/ember-cli-mirage#553]
Currently having trouble finding a way to pass data from the setup stage of our acceptance tests that could dictate what values are in the meta object in mirage's response objects.

In this case, we are trying to test our app against different boolean values that are set in the meta object. We're following JSON API specs.

Including query params in our requests was the first thought but it seems a little hacky; any ideas or possible solutions?

**Comment by samselikoff** [comment]
Hm, interesting. In your actual server, what determines what values end up in the meta object? Could you give an example?

**Comment by bttf** [comment]
We are using it to determine access permissions. So in this case, if the current user matches the 'owner user' of a certain model record, the meta obj would reflect this relationship with a boolean or some other flag.

The 'current user' is determined by the auth session serverside. One solution was to somehow pass the current user to mirage and have it check against the 'owner' of the records and set metadata accordingly.

But it seems easier if we could just set our meta objects explicitly in our tests instead of executing 'pseudo-backend' code.

**Comment by samselikoff** [comment]
I see. In your tests you can always overwrite handlers

```js
server.get('/path', () => {
  return {};
});
```

but sometimes people find it easier to just mimic the server code. In your case, this would mean adding some logic to the route handler, and then in your test, `server.create('user')` with various different attributes.

**Comment by bttf** [comment]
Ahh okay; either solution should work for us. Thanks!
