### ISSUE TITLE
shorthand/base#_getAttrsForRequest  should normalize relationships too

### ISSUE THREAD

**Issue by abuiles** [samselikoff/ember-cli-mirage#561]
The method only normalized the attributes and leaves out the relationships.

If I have a payload like the following 

```
{
  "data": {
    "attributes": {
      "does-mirage": true,
      "name": "sam"
    },
    "relationships": {
      "company": {
        "data": {
          "id": "1",
          "type": "companies"
        }
      },
      "github-account": {
        "data": {
          "id": "1",
          "type": "github-accounts"
        }
      }
    },
    "type": "github-account"
  }
}
```

The output should be something like

```
{name: "Sam", doesMirage: true, companyId: 1, githubAccountId: 1}
```

I'm working on a PR, will submit shortly :)

**Comment by samselikoff** [comment]
Nice... good catch. Would the document ever contain has-many relationships? I.e. relationships that primary document model does not own the foreign keys to? Is there any way to check for this? Possibly by introspecting the model?

**Comment by abuiles** [comment]
@samselikoff I believe is totally possible, it can be checked on the type of `.data` https://github.com/samselikoff/ember-cli-mirage/pull/562/files#diff-26f9dc309eb3c49fa6ea23f36ffa4d6fR85  --- if it is an object then it is a belongsTo if is an array then a `hasMany`.


I'd say let's handle this scenario for now, and I'll explore how has many can come in..  I'm migrating our tests suite to mirage so probably this will pop :)

**Comment by abuiles** [comment]
btw, is there a way to mix collections?  say I have a vehicles end-points... I would like to return something like `schema.car.all() + schema.motorcycle.all()`

**Comment by abuiles** [comment]
To answer https://github.com/samselikoff/ember-cli-mirage/issues/561#issuecomment-182849101 

The following seems to do the trick

```
this.get('/api/vehicles', function(schema, request) {
  let collection = schema.car.all();

  collection.push(...schema.motorcycle.all());

  // added a JSONAPI serializer for vehicles, since it is JSONAPI
  // it will look at object.type to create the response (not the collection modelName)
  //
  collection.modelName = 'vehicle';

  return collection;
});
```

**Comment by samselikoff** [comment]
Interesting... so would this be a polymorphic relationship?

**Comment by abuiles** [comment]
> Interesting... so would this be a polymorphic relationship?

Correct, that's what we are trying to get, I'll let you know if we run into any issues with it.
