### ISSUE TITLE
pretender munging file params on multipart uploads despite this.passthrough()

### ISSUE THREAD

**Issue by kluzny** [samselikoff/ember-cli-mirage#564]
Low priority issues, because I have already abandoned this approach. 

I was using mirage to mock out remote requests in ember, but integration testing in rails. 

It worked beautifully to stub out a remote api while letting my local api passthrough,  until I noticed it broke several unrelated tests.

When mirage is enabled, the post params to the file uploads break: 

```
<ActionDispatch::Http::UploadedFile:0x007f838b7c1ee0
 @content_type="text/plain;charset=UTF-8",
 @headers=nil,
 @original_filename=nil,
 @tempfile=#<File:/var/folders/1f/gh75zmnx7n78txd8hk77wl580000gn/T/raw-upload.20160210-92273-j6o19l>>
```
versus
```
<ActionDispatch::Http::UploadedFile:0x007fca3da23a78
   @content_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
   @headers=
    "Content-Disposition: form-data; name=\"import_upload_record[data_file]\"; filename=\"upload_template.xlsx\"\r\nContent-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet\r\n",
   @original_filename="upload_template.xlsx",
   @tempfile=#<File:/var/folders/1f/gh75zmnx7n78txd8hk77wl580000gn/T/RackMultipart20160210-92771-5y4h7d.xlsx>>}
```

of special note, is the headers and filename on the request have changed, and the params are `file` not a nested `data_file`

This is a pretty challenging case to simulate in isolation, but it appears that `this.passthrough()` is not properly ignoring requests.

**Comment by samselikoff** [comment]
Hm, this sounds a lot like https://github.com/samselikoff/ember-cli-mirage/issues/316

**Comment by kluzny** [comment]
Agreed, closing this issue, thanks for looking.
