### ISSUE TITLE
Add ?filter query param support to JSONAPISerializer

### ISSUE THREAD

**Issue by samselikoff** [samselikoff/ember-cli-mirage#565]

**Comment by samselikoff** [comment]
Moved to the Roadmap project

**Comment by bartocc** [comment]
@samselikoff how can we vote for https://ember-cli-mirage.canny.io/feature-requests/p/add-filter-query-param-support-to-jsonapiserializer ?

I don't know Canny well but there does not seem to be a free account possibility.

**Comment by samselikoff** [comment]
@bartocc hm really? When I click upvote in an incognito window I see a modal with the option to signup. There's definitely a way to get free accounts.

I've thought about moving back to GH for votes, using emoji reactions here as an indicator, to avoid Canny (since it's another tool). I hadn't thought about number of emoji reactions (and didn't know you could query issues and sort by that number) when I first started using Canny.

**Comment by bravo-kernel** [comment]
Moving back to GH would be nice as Canny seems a bit outdated and has no linkage back here.

May I also suggest integrating the repo with e.g. [BountySource](https://www.bountysource.com/) to put some power behind certain requests? It's easy to just press the thumb but putting in the $$$ to reach the threshold makes a whole lot more sense to me. Not to limit (free) voting in any way but as a practical addition. Everybody's free time is priceless and mirage is worth the investments if you ask me. 

FWIW I would be more than happy to back the first BountySource linked PR/Issue. 

https://github.com/bountysource/core/wiki/Frequently-Asked-Questions

**Comment by bravo-kernel** [comment]
No rush, the bounty approach is quite cool if you ask me as it allows for two-way funding ($$ set by the owner or $$ set by the requester so anybody can pick it up). Love mirage, thanks for all the work ❤️
