### ISSUE TITLE
Recursive relation does not seem to work

### ISSUE THREAD

**Issue by topaxi** [samselikoff/ember-cli-mirage#566]
I have a model called `section`:

`mirage/models/section.js`:
```js
import { Model, belongsTo } from 'ember-cli-mirage'

export default Model.extend({
  parentSection: belongsTo('section')
})
```

`mirage/fixtures/sections.js`:
```js
export default [
  { 'id': '3',  'name': 'Bern', 'code': 'BE' },
  { 'id': '15', 'name': 'Ittigen', 'parentSectionId': '3' },
  { 'id': '16', 'name': 'Thun-Allmendingen', 'parentSectionId': '3' }
]
```

I'm not sure if I'm doing something wrong but in this case, each section with a `parentSectionId` doesn't get a relation but a normal attribute called `parent-section-id`. I'd expect a relation here.

**Comment by topaxi** [comment]
I just saw https://github.com/samselikoff/ember-cli-mirage/pull/546 and assume this issue is related to this instead of the recursion. Using `sectionId` in my fixtures solves this problem, I guess in the next release `parentSectionId` should work too?

**Comment by topaxi** [comment]
Just tested on `master` works as expected.

**Comment by samselikoff** [comment]
Awesome!
