### ISSUE TITLE
API Passthrough not resolving promise

### ISSUE THREAD

**Issue by elwayman02** [samselikoff/ember-cli-mirage#571]
In my mirage config: `this.passthrough('http://foo.bar/**');`

Request: GET `http://foo.bar/me`

The request goes out to the live API, but when it returns, the promises don't actually resolve properly. It's like the request just gets swallowed and nothing happens. The code works as-is, it was only when I installed mirage that it stopped resolving. Any thoughts @samselikoff?

**Comment by elwayman02** [comment]
Mirage: 0.1.11
Ember: 1.13.13
Ember-Data: 1.13.14

**Comment by anulman** [comment]
Think this could be related to https://github.com/pretenderjs/pretender/pull/130 .

I've dealt with similar behaviour prior, and was able to fix this by upgrading to `pretender >= 0.11.0` || `jquery >= 2.1.0`

**Comment by anulman** [comment]
@samselikoff I see Mirage is adding [pretender ~0.10.1](https://github.com/samselikoff/ember-cli-mirage/blob/db01ab0a4daffd80a357ab875a9e2897e6abdb45/blueprints/ember-cli-mirage/index.js#L56) to projects in the `afterInstall` hook. Any reason the upgrade's not landed yet / if not, want me to change it?

**Comment by elwayman02** [comment]
@anulman thanks for the heads up! I was able to get it working on the latest pretender without upgrading jQuery.

**Comment by anulman** [comment]
:hand:

**Comment by samselikoff** [comment]
Merged the upgrade - thanks for taking care of this yall!
