### ISSUE TITLE
Bug in `bar: belongsTo('foo')`

### ISSUE THREAD

**Issue by Florisvanvoorst** [samselikoff/ember-cli-mirage#573]
Expected is that when you have the model:
```js
export default Model.extend({
  groupType: belongsTo('keyword')
});
```

That if you do `model.createGroupType()` it will create a `Keyword` model and set the foreign key `groupTypeId: keyword.id`.

What happens is the reverse: it will try to create a `GroupType` model (which does not exist) and it will try to set the foreign key `keywordId: groupType.id`.

**Comment by 2468ben** [comment]
FWIW I had this same problem and it's fixed for me on master (https://github.com/samselikoff/ember-cli-mirage/commit/15e5f38cf8964e55c57e33e163eb1d1c92ef5e44):

https://github.com/samselikoff/ember-cli-mirage/issues/528

If you can't use master yet, then the way I was getting it to "work" on the last beta release was manually setting all the values like this:

```
var newGroupType = schema.keyword.create({model: model, modelId: model.id})
model.update({groupType: keyword, groupTypeId: keyword.id})
```

I know that's crazy verbose (and you might not need to set all that stuff) but I had to do all that to be safe on the beta tag.

**Comment by samselikoff** [comment]
Yep, try latest master. We'll cut a new release soon!

**Comment by Florisvanvoorst** [comment]
thanks !
