### ISSUE TITLE
Ember.get doesn't see Mirage Model attrs

### ISSUE THREAD

**Issue by ef4** [samselikoff/ember-cli-mirage#583]
I hit a weird and surprising behavior:

``` js
let post = server.find('post', 1);
assert.equal(post.title, "The Title"); // Works
assert.equal(Ember.get(post, 'title'), "The Title"); // Doesn't work
```

Note that `Ember.get` is supposed to work on POJOs, and it works on `defineProperty` getters. But something about Mirage Model is confusing it.

This came up because I was stashing the Model on `this` in a component integration test, like:

``` js
this.set('model', model);
this.render(hbs`{{call-to-action-card teaser=model}}`);
assert.equal(this.$('h1').text(), this.get('model.title'));
```

And the chained `get('model.title')` fails.

**Comment by ef4** [comment]
I realized that it's weird and incorrect to be using a Mirage model directly against a template like this, so the use case is bogus, but the behavior is real. Possibly it doesn't matter though.

**Comment by samselikoff** [comment]
Yes, that was my first thought. We should investigate when we have some spare cycles.

**Comment by mitchlloyd** [comment]
I saw this bug and was intrigued because I've been using ES5 getters and setters with Ember and I was curious about incompatibilities with `Ember.get`.

I created a [test for this case in a fork](https://github.com/mitchlloyd/ember-cli-mirage/commit/3b835ee15b221c414b3cb86d3cfc8c25b2c30b63) and wasn't able to reproduce this. I tried creating and finding the model a couple of different ways but `Ember.get` continued to work. 

@ef4, maybe there is something else strange going on in that integration test? Also I was testing with current master for mirage and Ember `2.3.1`, so perhaps this issue exists with a different version of Ember / Mirage.

**Comment by tompiarulli** [comment]
I think I've been experiencing this issue while trying to create integration tests for my components:

```
test('it renders the user information', function(assert) {
  const user = server.create('user', {
    firstName: 'John',
    lastName: 'Smith'
  });

  this.set('user', user);
  this.render(hbs`{{users/user-cell user=user}}`);
  assert.equal(this.$().text().trim(), 'John Smith');
});
```

This text fails as the resulting text in the component is empty even though the creation of the object succeeds.

Is this not a proper use of Mirage? It seems silly to manually create stubs for these tests when Mirage does a good job of generating them.

**Comment by samselikoff** [comment]
`server.create` is designed to seed Mirage's db with models, and the only way those would make it to your Ember app would be through an XHR request. From that perspective, it wouldn't really make sense to set the return value from `server.create` on an Ember component.

I think enough people have asked about this though, so I'm open to introducing some helpers that would let you create client-side model instances from Mirage server data. But, no work has started on this yet.

**Comment by tompiarulli** [comment]
Gotcha thanks!

**Comment by samselikoff** [comment]
Filing under "Ability to make Ember Data models from Mirage factories" card in the Roadmap project

**Comment by marclundgren** [comment]
@samselikoff I'm not seeing this issue tracked in roadmap:

https://github.com/samselikoff/ember-cli-mirage/projects/3?card_filter_query=ability+to+make+ember+data+models+from+mirage+factories

Is it tracked somewhere else?

**Comment by acorncom** [comment]
@marclundgren Believe you're looking for https://github.com/samselikoff/ember-cli-mirage/pull/1056

**Comment by marclundgren** [comment]
thank you @acorncom
