### ISSUE TITLE
model.create() re-uses existing id

### ISSUE THREAD

**Issue by BryanHunt** [samselikoff/ember-cli-mirage#585]
I have a case with 0.2.0-beta.4 where calling model.create() re-uses an existing id in the database.

I have an endpoint that looks like:

```javascript
  this.post('/registrations/:id/verify', (schema, request) => {
    let registration = schema.registration.find(request.params.id);
    schema.user.create({userId: registration.userId, password: registration.password, email: registration.email});
    registration.destroy();
  });
```

When schema.user.create() is called, the new user is inserted into the database with the same id as the existing user.  I'm using fixtures to seed the users like so:

```javascript
export default [
  {id: 1, 'userId': 'admin', password: 'admin', email: 'admin@domain.net'},
];
```

**Comment by samselikoff** [comment]
So a user has a `userId`? Is it a self-referential relationship? Also, is there an error that's being thrown, or, what is the behavior you're running into that's different from what you're expecting?

**Comment by BryanHunt** [comment]
`userId` is not a self-referential relationship.  There is no error.  The fixture seeds the database with a single user with `id : 1`.  I execute a `post` which in turn calls `schema.user.create()` and a new user is inserted into the database also with an `id : 1`.  The new user should have `id : 2` instead.

**Comment by samselikoff** [comment]
Did you verify the fixtures are being loaded in the first place? Are you calling `server.loadFixtures()` in `config.js`? You could also put a debugger in the route handler and inspect `schema.db.users`.

**Comment by BryanHunt** [comment]
Yes, the fixtures are being loaded.  I am calling `server.loadFixtures()` in `scenarios/default.js` not `config.js`.  The debugger is showing one entry in `schema.db.users` before the call to `schema.user.create()`:
```javascript
[Object email: "admin@domain.net"id: "1"password: "admin" userId: "admin" __proto__: Object]
```
After the call to `schema.user.create()`, `schema.db.users` is:
```javascript
[Object email: "admin@domain.net"id: "1"password: "admin" userId: "admin" __proto__: Object, 
Object email: "user@domain.net"id: "1"password: undefined userId: "user" __proto__: Object]
```
Note that both objects have the same id.

**Comment by samselikoff** [comment]
f67d9018f21948e6d8fafda687d8b7e76ab5ab1a fixes, you should be all set! Thank you for reporting.
