### ISSUE TITLE
"server is not defined" in development environment with ember-cli 2.3.0

### ISSUE THREAD

**Issue by SaladFork** [samselikoff/ember-cli-mirage#587]
Recently updated a bunch of dependencies but primarily ember-cli to `2.3.0` and now `server` is no longer defined on `window` when running in the `development` environment. Running in the `test` environment it is defined as expected.

Using:
 * `ember-cli@2.3.0`
 * `ember-cli-mirage@0.1.11`
 * `ember-cli-mocha@0.10.0`
 * `ember#2.3.1`
 * `ember-cli-test-loader#0.2.2`
 * `ember-mocha-adapter#0.3.1`
 * `mocha#2.4.5`

**Comment by samselikoff** [comment]
In which file? It was never explicitly defined on `window` in development I believe.

**Comment by SaladFork** [comment]
Sorry, to clarify: when running in development (with `ember s`), all my acceptance tests that use `server.create` and `server.createList` fail with "server is not defined".

**Comment by samselikoff** [comment]
Oh I see. Hm, it might be time for us to figure out a proper way to inject server into tests.

**Comment by SaladFork** [comment]
Hmm, would supporting it via an import like the following work?
```
import { server } from 'ember-cli-mirage';
```

**Comment by samselikoff** [comment]
No because it's not a static import. We need to inject the actual server instance into the tests.

**Comment by bmrsny** [comment]
+1

**Comment by samselikoff** [comment]
So, to clarify, this happens when you `ember s` and then visit `/tests`?

**Comment by samselikoff** [comment]
Just made a fresh 2.3 app and I cannot reproduce this. Could you try the latest beta and see if you are still experiencing it?

**Comment by SaladFork** [comment]
Terribly embarrassed, after some investigation my issue was caused by `ember-cli-mirage.enabled` being set to `false` (in which case `server` not being defined is expected). Sorry for the noise and thanks for your time.

Not sure what issue @bmrsny is seeing.

**Comment by bmrsny** [comment]
I am getting `ReferenceError: server is not defined` in testing. I am using the most recent beta `"ember-cli-mirage": "0.2.0-beta.5"`

i am only getting this error in my instance initializer tests. Other tests seem fine.

**Comment by edmundito** [comment]
I ran into a similar issue and have ember 2.3.0 with mirage 0.1.11. I verified that mirage is enabled during testing. What I had to do is add this workaround to my module:

http://www.ember-cli-mirage.com/docs/v0.1.x/manually-starting-mirage/

```javascript
import { module, test } from 'qunit';
import startMirage from '../../../helpers/setup-mirage-for-integration';

module('Unit | for a plain JS object', {
  beforeEach() {
      startMirage(this.container);
  }
});
```

Then `server` is no longer undefined. However, I am not sure how to shut it down for future tests. Seems that If I run this in one test, I don't have to necessarily run it in other tests because then `server` becomes a global throughout. Is it something that needs to be added to `test/helpers/start-app`?

**Comment by samselikoff** [comment]
Mirage boots up in an initializer, so if you're not running an Acceptance test you'll need to start the Mirage server manually according to the docs @edmundito referenced.

If you start it manually you should shut it down in `afterEach` using `server.shutdown()`. (We should add that to the docs).

**Comment by edmundito** [comment]
@samselikoff Thanks! Good to know...
