### ISSUE TITLE
Sorting and Paging Support

### ISSUE THREAD

**Issue by ajgordo** [samselikoff/ember-cli-mirage#588]
In the latest beta release it seems pretty hard to handle sorting of the data based on criteria, and also the getting a page of data.
In 1.11 I was able to handle the data as an array and use a sort comparer and splice to cater for this, but with the data now being in a lodash collection that seems to be a lot more complex.

**Comment by samselikoff** [comment]
Some others have mentioned this, so we should definitely address it. Could you give me an example so I can see the pain points?

You can also add extra logic to the `serialize` method of your serializer:

```js
serialize(response, request) {
  let json = Serializer.prototype.serialize.apply(this, arguments);

  // sort, filter etc

  return json;
}
```

**Comment by ajgordo** [comment]
Not so much a pain point. I have been able to include sorting and paging as per your example, but it's a little weird because if I wanted to sort on the id vs. any other attribute the approach is slightly different.
Ideally it would be nice if sorting and paging could be handled by the database in the same way as where is handled.

**Comment by Aaronfischer** [comment]
So at the moment, just getting a pulse on this since this is still pretty recent, its probably best to handle filtering/sorting within the serializer directly on the serialized json obj?

I've actually pushed json api specific filtering (`?filter[first-name]=john`) up to the route but kept the pagination/sorting in the mirage serializer.
I also felt handling both of these "functions" in the route difficult as well.

**Comment by samselikoff** [comment]
JSON:API filtering will eventually make its way into the Serializer, but for now I don't think one way is necessarily better than the other. 

If you wanted you should be able to handle it in the Serializer too. Hopefully we'll get some better patterns established around filtering/sorting/paginating once #607 lands

**Comment by samselikoff** [comment]
#607 is closed, so you can get the base serialized json in your route handler now and then add paging/filtering metadata. Eventually we will add support for json:api filters/sorts directly into the serializer.

**Comment by samselikoff** [comment]
Created #710 and #711 to track
