### ISSUE TITLE
Is it possible to mix serializer types?

### ISSUE THREAD

**Issue by lkhaas** [samselikoff/ember-cli-mirage#591]
I have a situation where I use the serializers to specify included resources.  One of the included resources uses a different type of serializer then that parent.  What I'm seeing is that when the included resource is loaded on its own then it's correct serializer is used.  When it's loaded as an included resource, then the parent serializer is used.  I know this is kind of edge-casey so not sure if you want to support it or document the edge case restriction.  If you want to support it I can take an initial stab at an approach via a pull request, but might need a little direction.

This is using the 0.2.0-beta3.  Oh - just realized there are later betas... will try again with an update.

**Comment by lkhaas** [comment]
This doesn't seem to be a duplicate of #506 and the behavior is still the same on 0.2.0-beta5.  Although the more I think about it the more it makes sense that this wouldn't work.  You are mocking a request as a whole and you would expect that the entire response would be a single format... that different formats would come from different requests rather than have included resources in a separate format from the rest of the request.  It's only a fleeting requirement for us as we migrate from one API to another so perhaps it's best that we accelerate our transition or provide a custom work-around.

**Comment by abuiles** [comment]
@lkhaas we are currently doing something similar moving from AMS to JSON API ... mixing both "worked" fine only with async data but then when we tried to do includes things kind of went south.

So, mixing serializers in mirage (ED maybe?) works fine until you start sending compound data, I'd recommend to move the "includes" to be on te same format or do it async while you move all the end-points.

The following payload for example will work fine `authors` is in JSON API and posts in AMD
```
{
 data: {
   type: 'author'
   relationships: {
     posts: {
       data: [{type: 'post', id: '1'}, {type: 'post', id: '2'}]
     }
   }
 }
}
```

**Comment by ef4** [comment]
I think per-model serializers are the way to go. It's consistent with the mirage 2.0 model-centric way of doing things.

Right now mirage picks a serializers based on the top-level thing you pass out of a request handler, but I would rather see recursive serialization. For example, if you return arbitrary responses that _contain_ models, those models serializers could get called:

```js
  this.post('/login', (schema, request) => {
    return {
        user: schema.user.create(),
        access_token: '123123'
    };
  });
```

As a hack that works today, you can call `this.serializerOrRegistry.serialize(someModel)` manually within your response method to get the JSON yourself, and then customize & assemble it further.

**Comment by samselikoff** [comment]
#607 allows you to call `this.serialize` within your function handler, so you should now be able to accomplish this.
