### ISSUE TITLE
Incorrect JSON API response for GET requests that 404

### ISSUE THREAD

**Issue by zachfedor** [samselikoff/ember-cli-mirage#592]
I can't find any info on this in the docs or other github issues, so my apologies if this has already been handled or if I'm missing something that should be obvious.

Using 0.2.0-beta.3, a GET request from Ember to Mirage for a non-existent record of a handled route fails in an unexpected way. Take for example the route `this.get('/users/:id')` with the default serializer and a scenario that creates a single user. When Ember tries to find `/users/1`, mirage responds with the appropriate JSON API response of `{ data: { type: "users", id: "1", attributes: { ... }}}`. But when Ember makes a request to a user that doesn't exist (e.g. `/users/2`), the response is simply `{ error: "not found" }` with a successful status of 200 instead of 404.

Is this the expected/default behavior? If so, should it be? If not, where did I go wrong?

I know I can go through `config.js` and create custom error responses if the schema doesn't return a record, but that seems like a lot of work for all my routes. Can I modify the application serializer instead? Or something like that...

Thanks in advance for the help!

**Comment by samselikoff** [comment]
(Woops, I must not have hit 'send' in my email client)

This is just a holdout from the original Mirage code, and should be fixed soon. Thanks for reporting!

**Comment by samselikoff** [comment]
Fixed up in master, let me know if you have any more issues!
