### ISSUE TITLE
Updating from beta.4 to beta.5 causes errors

### ISSUE THREAD

**Issue by martndemus** [samselikoff/ember-cli-mirage#594]
When I update mirage from beta.4 to beta.5 I get the following errors on integration tests.
I think this is because the upgrade to full mirage models in #582:

- `TypeError: Cannot redefine property: description`
- `Error: Assertion Failed: You cannot use the same root element (#ember-testing) multiple times in an Ember.Application`
- `TypeError: this.set is not a function`

This is an example test:
```js
test('It renders item details', function(assert) {
  let item = server.create('item');
  this.set('item', item);
  this.render(hbs`{{item-details item=item}}`);

  let textContent = this.$().text().trim();
  assert.containsText(textContent, item.title);
  assert.containsText(textContent, item.description);
  assert.containsText(textContent, item.price);
});
```

Downgrading back to beta.4 fixes all of this.

**Comment by samselikoff** [comment]
Hm, we have tests that show you can still use factories without model definitions. Could you show me some of your setup, or try to create a reduced test case?

**Comment by Dhaulagiri** [comment]
I see this problem in our app as well.  If I get some time I will try to throw together a reproduction (if @martndemus doesn't do it first).

**Comment by martndemus** [comment]
@Dhaulagiri please do.

**Comment by Dhaulagiri** [comment]
Initial efforts to reproduce in a separate repo were not successful.  Can confirm the problem, `TypeError: Cannot redefine property:  ...` still does exist in beta 7 though.  @samselikoff is there particular aspect of our setup that I could share that might be helpful?

**Comment by samselikoff** [comment]
Anyway you could publish the mirage directory?

The `redefine property` error sounds like it could be related to the models, since they use Object.defineProperty. Perhaps there's a clash somewhere with property names? Maybe share your model attrs so I can try it out?

**Comment by martndemus** [comment]
https://github.com/martndemus/rommieschilstra.nl-frontend, upgrading to beta 5 should break the suite

**Comment by samselikoff** [comment]
@martndemus I just tried and the upgrade worked (it's on beta 7 now). Run

```
ember install ember-cli-mirage@beta
```

and re-run the test suite, everything passes.

Btw I think the browser is caching the lorempixel image, so if you make your factory attribute something like

```
imgThumbnail: i => `${faker.image.imageUrl(600, 600)}?${i}`
```

you'll get different images.

**Comment by martndemus** [comment]
@samselikoff Awesome!

**Comment by Dhaulagiri** [comment]
Confirmed that beta 7 works correctly for us now :+1: The only thing I did different this time is install using `ember install ...` vs. just updating the version number in package.son.

**Comment by samselikoff** [comment]
Ok great! `ember install` is usually the way to go, as it reruns the default blueprint and updates/brings in any bower packages that go along with the project.
