### ISSUE TITLE
'slice()' method for collections.

### ISSUE THREAD

**Issue by Ramblurr** [samselikoff/ember-cli-mirage#595]
When implementing pagination, I naively assumed a `Collection` was an actual array. After scratching my head and looking at the source when `collection.slice(offset, offset+per_page)` didn't work, I discovered its not really an Array.

Could we get a 'slice()' method for Collections to go along with map, reduce, filter, and friends?

**Comment by samselikoff** [comment]
Definitely. I'm going to wait just a bit because we've been deliberating over whether we could do without `Collection` completely, precisely because of these problems.

**Comment by samselikoff** [comment]
You can now access the JS array of models off a `Collection` via the `models` property:

```js
let users = schema.users.all();
users.models // a JS array
```
