### ISSUE TITLE
Collection.map is confusingly incompatible with Array.map

### ISSUE THREAD

**Issue by ef4** [samselikoff/ember-cli-mirage#596]
Collection.map only works if you're mapping to Models. But sometimes you need to do other things, like correlation and aggregation, in which case you need to map from models to arbitrary values.

For example:

```js
import _ from 'lodash/lodash';
import Collection from 'ember-cli-mirage/orm/collection';
...
  this.get('/api/v1/home', (schema /*, request */) => {
    // Round robin through all the content types we find
    let content = Array.from(schema.contentTeaser.all());
    let types = _.uniq(content.map(entry => entry.type)); // This would break horribly if I didn't know to use Array.from in the line above
    let contentByType = types.map(t => content.filter(entry => entry.type === t));
    return new Collection('content-teaser', _.compact(_.flatten(_.zip(...contentByType))));
  });
```

In general, I think it's a bad idea to try to fake being sufficiently Array-like. Trying to find and eliminate all the pitfalls is a Sisyphean task. I don't think it's even necessary, if all serialization typing could be done per-model, instead of trying to infer types of collections.

**Comment by samselikoff** [comment]
Right, you mentioned this earlier, passing along the type information at a higher level. Mitch and I were talking about this in [another issue](https://github.com/samselikoff/ember-cli-mirage/issues/375#issuecomment-186973213).

I think this might make sense, maybe we don't need Collection at all, and the serializer layer can just inspect the array. If it's a homogenous array of models, we'll use the model-specific serializer. That way, everyone can just work with arrays of models as pure arrays. If someone wants to use a different serializer, we can introduce a new api, something like

```js
return this.serialize(array, 'serializer-type');
```

or

```js
return this.serialize(array, {serializer: 'serializer-type', meta: { ]);
```

or maybe add an option to `Mirage.Response` where you can specify the serializer type (and meta, etc).

**Comment by samselikoff** [comment]
I started working on replacing `orm/Collection` with arrays, and ran into the empty array issue. I feel confident we could come up with a good API to deal with the serialization case, but I worry that there may be other use-cases for empty Collections. Do you have any ideas on how to deal with this? How do Rails' collection proxies handle this?

Alternatively, why doesn't `map` work in your example? Is it a one-off edge case or just an issue with Collection's current implementation? The other array methods in [Collection](https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/orm/collection.js) just call `method.apply(this, arguments)`, so maybe we just need to do a little more work to get these to work consistently?

**Comment by samselikoff** [comment]
#607 resolves. Collections now have a `models` property that gives you access to the underlying JS array, and return JS arrays of models (or explicitly calling `this.serialize`) should take care of this issue.
