### ISSUE TITLE
mirage in addon's unit test

### ISSUE THREAD

**Issue by epyx25** [samselikoff/ember-cli-mirage#597]
I try to use mirage in an addon's unit test: https://github.com/epyx25/mirage

Here is the important part: https://github.com/epyx25/mirage/blob/master/tests/unit/mixins/complete-save-test.js 

I setup a store and a model. If I try to save it, it sends a POST to http://localhost:4200/currencies as it should. If I try to turn on mirage manually: http://www.ember-cli-mirage.com/docs/v0.2.0-beta.5/manually-starting-mirage/ store becomes undefined.

(uncomment https://github.com/epyx25/mirage/blob/master/tests/unit/mixins/complete-save-test.js#L15-L19)

**EDIT**

It looks like, the beforeEach is has never run after https://github.com/epyx25/mirage/blob/master/tests/unit/mixins/complete-save-test.js#L16

I moved the setup code https://github.com/epyx25/mirage/blob/master/tests/unit/mixins/complete-save-test.js#L22-L33 to the test, but now: 

![image](https://cloud.githubusercontent.com/assets/17404207/13250186/c1eeb582-da28-11e5-80c2-1ea50c4e782f.png)

I think the route is correctly defined:
https://github.com/epyx25/mirage/blob/master/tests/dummy/mirage/config.js#L4

maybe some port problem?

**Comment by samselikoff** [comment]
What version of Mirage are you using? There were some fixes regarding addon integration in the beta-4 release

**Comment by BenjaminHorn** [comment]
@samselikoff  0.2.0-beta.5
https://github.com/epyx25/mirage/blob/master/package.json#L30

**Comment by samselikoff** [comment]
Filing under "Addon support" card in Roadmap project.

**Comment by bbansalWolfPack** [comment]
@samselikoff  can we use mirage to seed data for unit tests?

**Comment by samselikoff** [comment]
@bbansalWolfPack Yep! Check out the docs on [manually starting Mirage](http://www.ember-cli-mirage.com/docs/cookbook/manually-starting-mirage)

**Comment by bbansalWolfPack** [comment]
@samselikoff  Thanks a lot for replying back, the actual issue I am facing is on this link, will really appreciate if you can provide some help: https://stackoverflow.com/questions/54409443/ember-unit-testing-models

Also hoping to see you at Ember Con this time :)
