### ISSUE TITLE
RestAdapter getting links object working in factories.

### ISSUE THREAD

**Issue by jackmatt2** [samselikoff/ember-cli-mirage#598]
We are using links in our json responses

For example

Account - Model
```
export default DS.Model.extend({
  name: DS.attr('string'),
  users: DS.hasMany('user', { async: true })
});
```

Account - JSON Response
```
{
  "account": {
     "id": 1,
     "name": "My Account",
     "links": {
       "users" : "users"
     }
  }
}
```

The above says that to get the users you would go to `/accounts/1/users` 

I tried adding the `links` to the factory but it is still not working - Is is never hitting the endpoint and instead returning an empty array.  Is this supported?
```
export default Mirage.Factory.extend({
  accountName(i) {
    return `accountName ${i}`;
  },
  links: {
    users: 'users'
  }
});

```

**Comment by samselikoff** [comment]
Check your console, does your Ember app ever make a request to `/users`? Do you see an error?

**Comment by jackmatt2** [comment]
@samselikoff Yes, we screwed it up.  Cheers working now.
