### ISSUE TITLE
Support for an error response

### ISSUE THREAD

**Issue by kiwiupover** [samselikoff/ember-cli-mirage#6]
Is there a way to handle testing and error response from the server. 

Adding an api that could be used in a test that returns an error for an api resource would be helpful.

I see that you are have this as a todo.

```js
it('should have heading', function(done) {
  pretenderify.stub('get', '/contact/:id', 'error');
  visit('/contact/jack');
  andThen(function() {
    assert.equal(find('.container h2').text(), Ember.I18n.t('title'));
    done();
  });
});
```

**Comment by samselikoff** [comment]
yep exactly. Maybe first steps would be to at least expose the server instance so you could use `stub` as it exists right now - the 4th param is the response code. But I'd also like to think of a nice api, perhaps a global:

```
it('should have heading', function(done) {
  forceRouteError('get', '/contact/:id', {errors: data}, [optional error code]);
  visit('/contact/jack');
  andThen(function() {
    assert.equal(find('.container h2').text(), Ember.I18n.t('title'));
    done();
  });
});
```

**Comment by samselikoff** [comment]
28877212a3a2d83b801395f9e2dfa58337afc030 closes

**Comment by samselikoff** [comment]
Check out https://github.com/samselikoff/ember-cli-mirage/wiki/Acceptance-testing#verb for an example

**Comment by kiwiupover** [comment]
Thanks heaps @samselikoff
