### ISSUE TITLE
Existing ids are reused for new model instances

### ISSUE THREAD

**Issue by balinterdi** [samselikoff/ember-cli-mirage#602]
I have loaded some fixtures into the app but when I create a new model instance, id=1 is assigned to it, which already exists and thus causes confusion:

![PJ and Caspian have both id=1](https://cloud.githubusercontent.com/assets/5022/13300587/30203ad0-db41-11e5-872f-48f6d18e1cf3.png)

My routes use the shorthand method:

```js
// mirage/config.js
(...)
  this.get('/bands');
  this.post('/bands');
  this.get('/bands/:id');
```

This is for version 0.2.0-beta.5.

**Comment by samselikoff** [comment]
I actually just fixed this last night.

Just published beta.6, try that and you should be all set!

**Comment by balinterdi** [comment]
It seems like now the new band gets the latest id and not the latest id + 1:

![Radiohead and Caspian, sitting in a tree](https://monosnap.com/file/Ch8wSWFDmYDb4EUkeS11ecVKDdd0Wl.png)

**Comment by samselikoff** [comment]
Can I see your fixtures?

**Comment by balinterdi** [comment]
Sure, they are [here](https://github.com/balinterdi/rock-and-roll/tree/1672ea4f97220306a42194fd2c12216eb3f9eabe/mirage/fixtures), but let me paste it in here, too:

```js
// bands.js
export default [
  { id: 1, name: 'Pearl Jam', links: { songs: '/api/bands/1/songs' } },
  { id: 2, name: 'Led Zeppelin', links: { songs: '/api/bands/2/songs' } },
  { id: 3, name: 'Foo Fighters', links: { songs: '/api/bands/3/songs' } },
  { id: 4, name: 'Radiohead', links: { songs: '/api/bands/4/songs' } }
];
```

```js
// songs.js
export default [
  { id: 1, title: 'Daughter', rating: 5, bandId: 1 },
  { id: 2, title: 'Yellow Ledbetter', rating: 5, bandId: 1 },
  { id: 3, title: 'Animal', rating: 4, bandId: 1 },
  { id: 4, title: 'Inside Job', rating: 4, bandId: 1 },
  { id: 5, title: 'Who We Are', rating: 2, bandId: 1 },
  { id: 6, title: 'Black Dog', rating: 4, bandId: 2 },
  { id: 7, title: 'Achilles Last Stand', rating: 5, bandId: 2 },
  { id: 8, title: 'Immigrant Song', rating: 4, bandId: 2 },
  { id: 9, title: 'Pretender', rating: 3, bandId: 3 }
];
```

**Comment by samselikoff** [comment]
You were right! There was another regression.

Fixed and published beta-7, that should work now (I tried it with your app locally). Let me know if you run into any other problems!

**Comment by balinterdi** [comment]
Thank you, that has fixed it!
