### ISSUE TITLE
`server.create()` returns wrong record if collection has record

### ISSUE THREAD

**Issue by batjaa** [samselikoff/ember-cli-mirage#605]
I've a fixture that creates some `offers`.
In acceptance test, when creating a new offer (for example `let offer = server.create('offer')` ) it's returning the first offer from the collection (`offer` with the `id=1`). Seem to be related with `this.identityManager.fetch();` in `db-collection.js`.

**Comment by samselikoff** [comment]
I think I just fixed this, could you try beta7?

**Comment by batjaa** [comment]
Thanks it did.
