### ISSUE TITLE
Document how to model a many-to-many relationship

### ISSUE THREAD

**Issue by samselikoff** [samselikoff/ember-cli-mirage#606]
Currently, you must explicitly model the join model.

Eventually, we will add a `has_and_belongs_to_many`, similar to Rails.

**Comment by JoshSmith** [comment]
Any way we can help on this? You can see @begedin and I have had a bit of struggle with this given that referenced PR there. We've been doing lots of relationships work for our acceptance testing.

**Comment by samselikoff** [comment]
Yah, I think right now the answer is, "you have to explicitly create a join model." Eventually we will add something like a `hasAndBelongsToMany` which will keep the join record transparent.

**Comment by scottfisk** [comment]
So I understand the "explicitly create a join model" but do not understand how I make this join model correctly translate to a 2 sided `hasMany` in ember data. Perhaps that is the sort of thing you are talking about documenting? Maybe something in the serializer?
Below is the recommended setup I have gathered from the issues.
Mirage models:
```js
// mirage/models/post.js
export default Model.extend({
  postTags: hasMany()
});
```
```js
// mirage/models/tag.js
export default Model.extend({
  postTags: hasMany()
});
```
```js
// mirage/models/post-tag.js
export default Model.extend({
  post: belongsTo(),
  tag: belongsTo()
});
```
And some fixtures:
```js
// mirage/fixtures/posts.js
export default [
  {
    id: 1
    title: "Post 1"
  }
];
```
```js
// mirage/fixtures/tags.js
export default [
  {
    id: 1,
    text: "Tag 1"
  },
  {
    id: 2,
    text: "Tag 2"
  }
];
```
```js
// mirage/fixtures/post-tags.js
export default [
  {
    postId: 1,
    tagId: 1
  },
  {
    postId: 1,
    tagId: 2
  }
];
```

With the ember data models being:
```js
//app/models/post.js
export default Model.extend({
  tags: hasMany('tag', { async: true })
});
```

```js
//app/models/tags.js
export default Model.extend({
  posts: hasMany('post', { async: true })
});
```

After reading through the issues the one thing I am missing is the best practice using mirage to wire up the `tags` and `posts` async `hasMany` relations so it works with the ember data setup. From the declarations above I wouldn't expect `posts` or `tags` to work in ember data so how do I go about that?

**Comment by samselikoff** [comment]
So, depending on your backend, you could add the ids at the serializer level, something like this:

```
// mirage/serializers/post.js
export ApplicationSerializer.extend({

  serialize(post, request) {
    let json = Serializer.prototype.serialize.apply(this, arguments);
    
    json.post.tag_ids = post.postTags.map(pt => pt.tagId);

    return json;
  }

});
```

Does that make sense? It's a bit hacky but you should be able to set this up, until we have a more expressive API & support for many-to-many with no join model.

**Comment by remkoboschker** [comment]
The serializers below worked for me. I adapted to the example above without testing so beware of a typo

````
// mirage/serializers/post.js
import { JSONAPISerializer } from 'ember-cli-mirage';
export default JSONAPISerializer.extend({

  serialize(response, request){
    let json = JSONAPISerializer.prototype.serialize.apply(this, [response, request]);

    json.data.relationships.tags.data = json.data.relationships.tags.data
      .map(postTag => ({
        id: this.registry.schema.postTags.find(postTag.id).tagId,
        type: 'tag'
      }));

    return json;
  }
});

// mirage/serializers/tag.js
import { JSONAPISerializer } from 'ember-cli-mirage';
export default JSONAPISerializer.extend({

  serialize(response, request){
    let json = JSONAPISerializer.prototype.serialize.apply(this, [response, request]);

    json.data.relationships.posts.data = json.data.relationships.posts.data
      .map(postTag => ({
        id: this.registry.schema.postTags.find(postTag.id).postId,
        type: 'post'
      }));

    return json;
  }
});
````

**Comment by remkoboschker** [comment]
To update a many to many relationship I used the normalize hook. I'm not sure if this should be handled elsewhere. I remove the relationship in question from the request and handle the mapping to the join model adding and removing records as required.

````
// mirage/serializers/post.js
normalize(json) {
    const db = this.registry.schema.db.postTags;
    const tags = json.data.relationships.tags.data;
    const absent = db.where(postTag => {
      // if the join model is about this record
      const isAboutThis = postTag.postId === json.data.id;
      // and if the other side of the join is not in any of the relationship objects
      const isNotInRelationship = !tags.any(tag => tag.id === postTag.tagId);
      return isAboutThis && isNotInRelationship;
    });

    //remove absent
    absent.forEach(item => db.remove(item.id));

    // insert new
    tags.forEach(tag => {
      db.firstOrCreate({
        postId: json.data.id,
        tagId: tag.id
      });
    });

    // unclear what happens if you translate the relationship to another type
    // mirage appears to keep adding join records.
    delete json.data.relationships.tags;

    return json;
  }
````

**Comment by morhook** [comment]
Linking the article https://www.loadsys.com/many-many-relationships-ember-cli-mirage/ as it seems part of this ticket.

**Comment by samselikoff** [comment]
@morhook thank you. With the 3.x beta series underway this should much simpler very soon. You can follow along at https://github.com/samselikoff/ember-cli-mirage/pull/965

**Comment by samselikoff** [comment]
Happy to be able to close this! 

www.ember-cli-mirage.com/blog/2017/01/09/0-3-0-beta-series/
