### ISSUE TITLE
Mirage or Pretender blocking promises?

### ISSUE THREAD

**Issue by davidenglishmusic** [samselikoff/ember-cli-mirage#608]
Thanks for this terrific mocking software. That said, I am running into a bit of a problem with promises not resolving having swapped in mirage, phasing out my use of the older fixtureadapter.

I am using the code from from the [API](http://emberjs.com/api/classes/RSVP.Promise.html):

```
function getJSON(url) {
  return new Promise(function(resolve, reject){
    var xhr = new XMLHttpRequest();

    xhr.open('GET', url);
    xhr.onreadystatechange = handler;
    xhr.responseType = 'json';
    xhr.setRequestHeader('Accept', 'application/json');
    xhr.send();

    function handler() {
      if (this.readyState === this.DONE) {
        if (this.status === 200) {
          resolve(this.response);
        } else {
          reject(new Error('getJSON: `' + url + '` failed with status: [' + this.status + ']'));
        }
      }
    };
  });
}
```

Following the ```xhr.send()```, the readyState stays at 1 and never reaches 4.

I am running Ember 1.13.12, have bumped jquery up to 2.1.4 and have added ```this.passthrough();``` to the app/mirage/config.js.

**Comment by davidenglishmusic** [comment]
Closing for now. This is probably related to something in the promise itself and not to mirage.

**Comment by nkgm** [comment]
@davidenglishmusic any luck resolving this? Facing same problem.

**Comment by davidenglishmusic** [comment]
@nkgm - Ultimately I dropped that promise code here in favour of a jquery **get** request:
```
Ember.$.get( "url", function( data ) {
  // use data
});
```
A quick note though - I was not actually looking to get JSON but rather a file containing markdown

**Comment by nkgm** [comment]
Good to know. In my case it was [pretenderjs/pretender#85](https://github.com/pretenderjs/pretender/issues/85) - missed that in the docs.
