### ISSUE TITLE
Many-to-many relationships being overwritten

### ISSUE THREAD

**Issue by dpdawson** [samselikoff/ember-cli-mirage#609]
I haven't tracked down exactly where the problem is yet, but I can't seem to get many-to-many relationships working.

An example scenario:

```
const category1 = server.create('category', { name: 'One' });
const category2 = server.create('category', { name: 'Two' });
const products = server.createList('product', 4);
category1.products = products;
category2.products = products;
```

All the products end up associated with category2, with none with category1.

If you do something like this instead:
```
category1.products = [products[0], products[1]];
category2.products = [products[1], products[2]];
```

category1 will only be associated with products[0] and category2 will be associated with products[1] and [2].

It appears the second assignment is overwriting the categories association on the products. Maybe this is intended, but if so, how do you create a many-to-many relationship?

**Comment by dpdawson** [comment]
Never mind. I read through some more issues and realized Mirage requires you to explicitly setup the join table.

**Comment by samselikoff** [comment]
Currently yes, sorry about that. It needs to be added to the Models documentation.
