### ISSUE TITLE
Circular Foreign Key Dependencies

### ISSUE THREAD

**Issue by alexlafroscia** [samselikoff/ember-cli-mirage#613]
I'm working on converting the old Pretender-based fixtures over to use Mirage `0.2.0-beta.7`, using the new Model system with my old fixture data (cleaned up to be the right format for Mirage).  It seems like the foreign key resolver is getting stuck in a bit of a loop; I have some models that reference each other through foreign keys, and whenever I try to look up one of them, Mirage exhausts the call stack trying to resolve the relationships over and over again.

I know that fixture data is not the recommended way to approach using Mirage, but since we already have all of the data as JSON fixtures, it's a stop-gap solution for us that allows us to at least take the step toward using Mirage.  Is this kind if circular dependency issue something that our fixture data should just avoid? Or do you think it's a bug in Mirage?

**Comment by alexlafroscia** [comment]
I'm also a little confused by what `fks` represents [here](https://github.com/samselikoff/ember-cli-mirage/blob/2400b33a1e6bd9371436875b684bc6ae943f6b28/addon/orm/schema.js#L149); I thought that it would just be the foreign keys that that model has that point to other models, but from what I'm seeing it includes not all of the keys that that model has that point to other models, and also includes the names of other models that point _at_ the given one.

For example, I have a `project` model that looks like this:

```js
// mirage/models/project.js
import { Model, belongsTo, hasMany } from 'ember-cli-mirage';

export default Model.extend({
  auditForms: hasMany('audit-form'),

  defaultView: belongsTo('view'),

  entities: belongsTo('entity'),

  executiveSponsors: hasMany('user'),

  groups: hasMany('group'),

  owner: belongsTo('user'),

  projectMangers: hasMany('user'),

  reportOptions: hasMany('report-option'),

  views: hasMany('view')
});
```

However, when being instantiated in the method I linked to above, `fks` contains the following:

```js
["institutionId", "defaultViewId", "entitiesId", "ownerId"]
```

which has a few of the relationships, but not all of them, as well as the names for a few of the models that point _at_ this particular project (in this case, `institutionId`).  I have no idea if this is a bug at all, it just struck me as unexpected so I figured I would ask.

**Comment by alexlafroscia** [comment]
It seems like, by default, Mirage tries to eager-load relationships, which might be the root of the issue we're having.  For example, when hitting `/api/projects` I'm trying to load _just_ the projects models and return them, but Mirage is trying to look up every model that every dependency of the ones I want, too.  Is there a way to turn that off?

**Comment by samselikoff** [comment]
I may have to look at this in detail later but can I see your fixtures?

**Comment by samselikoff** [comment]
Fks live on the `belongsTo` side of the relationship. So if you `author` hasMany `posts`, `post` will get an `authorId` added to its fks.

**Comment by samselikoff** [comment]
Also, is `entities` how your API works currently? If so you may have to configure the inflector since it would expect `entity` in the event of a belongsTo

**Comment by alexlafroscia** [comment]
Yeah, I can upload the fixtures somewhere but there are a lot of them and it's a bit of a mess :neutral_face: 

Does Mirage currently expect all relationships to have an inverse (whether explicit or implicit)?  That may be the issue, since many of our relationships don't.

**Comment by alexlafroscia** [comment]
> Also, is entities how your API works currently? If so you may have to configure the inflector since it would expect entity in the event of a belongsTo

What do you mean by that?

**Comment by samselikoff** [comment]
It might be if you have a `ids: []` array in the fixture file on the many side of the relationship.

I.e. in your fixtures if you have an `author` that `hasMany` `posts`, don't have a `postIds: [1, 2, 3]` in your author fixture.

I can look at this more later but that'd be something to check out first. Data in fixtures should only be the fks.

**Comment by alexlafroscia** [comment]
What if the fixtures' array is empty, but present?  I think I have some cases where that is true, but I don't have cases where the key (`postIds` in your example) is missing entirely.

**Comment by samselikoff** [comment]
The fixtures data should mirror your db, so you should never have an array of ids (even just the key) if you're using Mirage's orm.

Could you publish your mirage directory somewhere so I can have a look?

**Comment by alexlafroscia** [comment]
Yeah, I linked to it before; you can find it here:

https://keybase.pub/alexlafroscia/mirage/

**Comment by alexlafroscia** [comment]
> The fixtures data should mirror your db, so you should never have an array of ids (even just the key) if you're using Mirage's orm.

Maybe this is the issue; I have the fixtures set up where they have arrays of IDs in the fixtures.  How are the fixtures supposed to be set up for fixtures with relationships? Embedding the related models in the fixtures?

**Comment by balinterdi** [comment]
@alexlafroscia I had the same issue, although with an AMS Adapter and in a much simpler app, but the same concepts might help: #584 .

If your hasMany-belongsTo relationships are async, just put the foreign key ids on the belongsTo end of the relationship and include a `links` hash on the `hasMany` end to let Mirage know where to fetch the `hasMany` data from, as Sam explains in detail in the linked issue. I hope that helps.

**Comment by alexlafroscia** [comment]
@balinterdi ahh, that looks like the fix! I'll try that out today and see if that fixes things.  Thanks!

**Comment by alexlafroscia** [comment]
After reading over the information in #584, that definitely seems to be the same problem I was having.  The issue I'm running into is that not all of our models have the relationship defined both ways.  For example, a `project` has many `groups`, but the `group` model does not point to any projects.  How would I structure that with the fixtures, since there is no real `belongsTo` side?

**Comment by samselikoff** [comment]
How is that relationship data saved in your actual backend? Is there a `project_groups` join model?

**Comment by alexlafroscia** [comment]
On the server, there is an implicit join model that our backend ORM (Django) abstracts away.  It feels pretty weird to have to model the relationship in Mirage when even the backend doesn't have an explicit representation for it.  I know that it's something that will be worked on in the future, but for now we're doing to start translating all of the fixtures to use join models and once the Mirage API improves, convert to `hasManyAndBelongsTo`.  Hopefully that fixes the issue that we're seeing.

**Comment by alexlafroscia** [comment]
So just to make sure: the only way to achieve something like this:

```json
{
  data: {
    type: 'project',
    id: 1,
    attribute: { ... },
    relationships: {
      groups: {
        data: [{
          type: 'group',
          id: 1
        }]
      }
    }
}
````

is using the join table?  I guess the part that is alluding me is how you get from the join table to a `groups` array inside the JSON:API `relationships` hash for the `project`.

**Comment by alexlafroscia** [comment]
Alright, so I've got all the fixtures moved over to only support the keys on the `belongsTo` side and, while things are slightly better, I'm still running into the core issue.  Not all of the relationships have an inverse at all, and that seems to be causing problems.

For example, a `project`, has an array of `views` and a `defaultView`, and the `view` model belongs to a `project`.  I have the `view.project` and `project.views` explicitly defined as inverses, but there is no inverse relationship for `project.defaultView`; it's just a one-way reference to a view.

What I'm seeing is that this is causing the `_setupRelationships` to continue to exhaust the call stack.  A project loads the `defaultView`, which loads the `project`, which loads the `defaultView`, which loads the `project`... etc.

Is there currently no support for situations that do not have an inverse?  Or is there a different way to set things up to support situations where a relationship only should be defined in one direction?

**Comment by samselikoff** [comment]
I'm not in front of my computer at the moment but perhaps you could upload
your mirage directory, so when I am I can look at exactly how you have
things set up?

**Comment by alexlafroscia** [comment]
I updated the Mirage directory that I linked to yesterday with the latest changes from today, where the foreign keys are all on the `belongsTo` side of the relationships. You can find it here:

https://keybase.pub/alexlafroscia/mirage/

**Comment by samselikoff** [comment]
Sorry, just getting to this now and it seems the keybase directory no longer exists. Maybe you could just post the `project` and `defaultView` definitions + fixtures? (basically the four links in [this comment](https://github.com/samselikoff/ember-cli-mirage/issues/613#issuecomment-191415198))?

**Comment by alexlafroscia** [comment]
Ahh damn, sorry about that.  [Here's the link.](https://gist.github.com/alexlafroscia/7db7aec4a4ec87f63b26)

**Comment by samselikoff** [comment]
The problem is with the two `belongsTo` declarations. Mirage needs to add support for either a `hasOne` or passing an option to `belongsTo` that says "I don't own the foreign key". Let me work/think about this.

**Comment by samselikoff** [comment]
The ORM improvements in the 0-3 series should address this issue.

www.ember-cli-mirage.com/blog/2017/01/09/0-3-0-beta-series/
