### ISSUE TITLE
How do I return error responses in v0.1.11?

### ISSUE THREAD

**Issue by skaterdav85** [samselikoff/ember-cli-mirage#618]
I am doing the following in my Mirage route:

```js
return new Mirage.Response(422, {}, {
  errors: [ /* stuff here*/ ]
});
```

However, the Chrome console says: "Successful request: POST /api/v1/XXX". Am I missing something? Thanks!

**Comment by samselikoff** [comment]
Successful should probably say handled, this is just saying that Mirage
handled the request. Can you check if it's treated as an error in your
code, for example if a catch block is being called?

**Comment by skaterdav85** [comment]
Both the catch and the success are being called.

**Comment by samselikoff** [comment]
Hm, both `.catch` and `.then`? I've never heard of that before. Could you upload a reduced test case somewhere so I can look?

Also maybe try using `{ 'Content-Type': 'application/json' }` for your headers argument (second param to `Mirage.Response`).

**Comment by skaterdav85** [comment]
It was a problem on my end. I didn't realize that if you don't throw in a catch block, success handlers for promises downstream will get invoked. I had something like this:

```js
asyncCall['catch']((err) => {
  return err; // should have thrown here
}).then(() => {
  // executed because i didn't throw in the catch block above
});
```
