### ISSUE TITLE
Singular fixture names cause confusion – they fail silently when loading the whole collection

### ISSUE THREAD

**Issue by balinterdi** [samselikoff/ember-cli-mirage#620]
I've created a fixture using the singular form:

    $ ember g mirage-fixture band

, and then spent some time debugging why the loaded fixtures are not returned for a `schema.band.all()` operation. It turned out the fixtures created a `band` collection as opposed to the `bands` collection and `schema.band.all` reads from the latter.

I think pluralizing the passed fixture name would prevent others from running into the same issue I have. 

@samselikoff If you think this is reasonable, I can take a crack at this.

**Comment by fknoll** [comment]
With all respect - I am still pretty much a newbie to this environment - I find it confusing and error prone that e.g. the **plural** named fixture **mirage/fixtures/bands.js** corresponds to the **singular** named **mirage/models/band.js**.

I regard to having `ember g mirage-fixture <fixture name>` pluralizing the passed `<fixture name>`; how to know, that the passed `<fixture name>` is not already plural?

But maybe, on both issues, I am missing the big picture?

**Comment by balinterdi** [comment]
The pluralization is not an issue, observe:

    > Ember.String.pluralize('bands')
    "bands"
    > Ember.String.pluralize('band')
    "bands"

**Comment by samselikoff** [comment]
Yes, this would be very helpful. Fixture files should be pluralized.

We could probably even pluralize the keys of [the fixtures hash here](https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/server.js#L181), just in case the filename is singular. But we should pluralize the filename too, just to prevent confusion.

**Comment by samselikoff** [comment]
Went ahead and changed it at the `read-modules` level.

**Comment by balinterdi** [comment]
Cool, thank you!
