### ISSUE TITLE
Passing a Collection as part of a return object

### ISSUE THREAD

**Issue by blimmer** [samselikoff/ember-cli-mirage#623]
I've been using the 0.2.x beta and it's really awesome!

One thing I've run into problems with is passing back relationships with additional values. For example, consider this route definition in `mirage/config.js`:

```javascript
this.get('foos', function(schema) {
  return {
    foos: schema.foo.all(),
    meta: {
      myMeta1: 'bar',
      myMeta2: 'baz'
    }
  }
});
```

This doesn't work as I originally expected because `foos` in the object is a `Collection` object. To work around this, I've done something like this:

```javascript
this.get('foos', function(schema) {
  const foos = schema.foo.all().map(function(f) {
     return f.attrs;
  });

  bar = someLogic();

  return {
    foos,
    meta: {
      myMeta1: bar,
      myMeta2: 'baz'
    }
  }
});
```

Is this something we should consider doing for the user (e.g. if a return object is a Collection type, we handle translating to attrs)? Or is the proper thing to do to handle this in the serializer?

**Comment by mitchlloyd** [comment]
Issue #607 is related to this issue. Sam is leaning toward removing `Collection` which would make the original example work.

**Comment by blimmer** [comment]
That sounds good - what should be the destiny of this issue? should we close it and track with #607 ?

**Comment by mitchlloyd** [comment]
Still no resolution on #607 yet so it seems good to keep this open.

**Comment by blimmer** [comment]
Sounds good - thanks!

**Comment by samselikoff** [comment]
#705 is merged, so now you can do something like this:

```
this.get('foos', function(schema) {
  let foosJson = this.serialize(schema.foos.all());

  return Object.assign(foosJson,  {
    meta: {
      myMeta1: 'bar',
      myMeta2: 'baz'
    }
  });
});
```

Note there are some breaking changes in this commit so check the changelog. Let me know if you have any more issues once you get to this!

**Comment by blimmer** [comment]
Thank you - sorry for the delayed response. We tried out `master` and this worked swimmingly for us! Related: what're the release plans for a beta.9 ?

**Comment by samselikoff** [comment]
I'm traveling now, planning on next week. Need to make a small change to
the serializer implementation.
