### ISSUE TITLE
Model returned by server.create doesn't invoke factory with magic methods.

### ISSUE THREAD

**Issue by alecho** [samselikoff/ember-cli-mirage#624]
Apologies if this is a duplicate or wrong, I did due diligence but I wouldn't be surprised if I missed something.

In a test such as
```
test('viewing a thing', function(assert) {
  let firstLocation = server.create('location');
  firstLocation.createThing();
  // More test code
```
Where the location model is defined with: `things: hasMany()`, `firstLocation.createThing();` doesn't invoke the thing factory. A new thing is created but doesn't have the expected name property of "Thing 1" even though `server.create('thing');` would create a new thing with the expected name.

**Comment by samselikoff** [comment]
Yep this is correct actually. I had originally thought the snippet you posted above would be a good example of how to use related methods, but in fact the model's `create` method does not by default fall back to factory methods.

We really need support for model defaults, in addition to factories. Also, factories need relationship support.

The related methods are primarily useful in route handlers, and also if we ever add an `afterCreate` hook to factories.
