### ISSUE TITLE
DbCollection: lastOrCreate(), first() and last()

### ISSUE THREAD

**Issue by RSSchermer** [samselikoff/ember-cli-mirage#625]
`DbCollection` currently provides the [`firstOrCreate` method](https://github.com/samselikoff/ember-cli-mirage/blob/28ec06c9cddaa971f81eb2fe5ba1aeccb94821a8/addon/db-collection.js#L68-L80). Was wondering if perhaps it made sense to add some counterparts:

- `lastOrCreate(query, attributesForNew)`: equivalent to `firstOrCreate` but for the last record rather than the first record.
- `first(query)`: where `query` is optional. Essentially equivalent to `firstOrCreate` but returns `undefined` (or `null`) when no record is found, rather than creating a new query.
- `last(query)`: equivalent to `first` but for the last record rather than the first record.

For my current use case I'm particularly interested in `last`. I'm mocking an authentication API with access tokens (oAuth). When requesting the current token (`/oauth/token/info`) I'd like it to return the most recently added token or null if no tokens were created.

Would be happy to make a PR if you think adding these methods (or a subset) is a decent idea.

**Comment by samselikoff** [comment]
In general I'm leaning towards keeping these APIs slim, and encouraging people to use something like lodash (which has [_.last](https://lodash.com/docs#last). `db.users` is a full-fledged JS array so Array methods from lodash, ramda, etc. should all work on them.

**Comment by RSSchermer** [comment]
Fair enough, thanks for the quick response!
