### ISSUE TITLE
Acceptance Testing data not being run through the serializer

### ISSUE THREAD

**Issue by Aaronfischer** [samselikoff/ember-cli-mirage#627]
Currently using mirage 0.2.0 beta 7.

I've setup /mirage/factories/user.js using a flat structure to generate data for the front-end dummy app, this works great and is serialized via the /mirage/serializers/application.js just fine (which is using the default setup):

``` js
import Mirage, {faker}  from 'ember-cli-mirage';
import moment from 'moment';

export default Mirage.Factory.extend({
  'username'() { return faker.internet.userName(); },
  'emailAddress'() { return faker.internet.email(); },
  'firstName'() { return faker.name.firstName(); },
  'lastName'() { return faker.name.lastName(); },
  'isAdmin'() { return faker.random.arrayElement([true, false]); },
  'createdAt'() { return moment(faker.date.past()).format('YYYY-MM-DD'); },
  'updatedAt'() { return moment(faker.date.past()).format('YYYY-MM-DD'); },
});
```

I've generated /mirage/models/user.js model (default):

``` js
import { Model } from 'ember-cli-mirage';

export default Model.extend({
});
```

I've created /mirage/fixtures/users.js fixture data which is exporting an array of flat data (same attributes as the fixtures + `id` and `type`):

``` js
export default [
    {
        'id': 1,
        'type': 'users',
        'username': 'YippieKiYay',
        'emailAddress': 'john.mcclane@domain.com',
        'firstName': 'John',
        'lastName': 'McClane',
        'isAdmin': true,
        'createdAt': '2017-01-01',
        'updatedAt': '2017-01-02'
    },
    {
        'id': 2,
        'type': 'users',
        'username': 'YippieKiYay',
        'emailAddress': 'john.mcclane@domain.com',
        'firstName': 'John',
        'lastName': 'McClane',
        'isAdmin': true,
        'createdAt': '2017-01-01',
        'updatedAt': '2017-01-02'
    }
];
```

In /mirage/config.js:

``` js
...
this.get('/users');
this.get('/users/:id');
...
```

/tests/acceptance/basic-test.js

``` js
import moduleForAcceptance from '../helpers/module-for-acceptance';
import { test } from 'qunit';

var application;

moduleForAcceptance('Acceptance: Simple Table');

test('Check for expected content /', function(assert) {
    server.loadFixtures('users');
    console.log('server.db.users', server.db.users);
    visit('/');

    andThen(function() {
        assert.equal(currentPath(), 'index');

        var cells = find('table tbody tr').eq(0).find('td');

        assert.equal(cells.eq(0).html(), 'YippieKiYay', 'Check for username');
        assert.equal(cells.eq(1).html(), 'john.mcclane@domain.com', 'Check for email');
        assert.equal(cells.eq(2).html(), 'John', 'Check for first name');
        assert.equal(cells.eq(3).html(), 'McClane', 'Check for last name');
        assert.equal(cells.eq(4).text().trim(), '01/02/2017', 'Check for date');
        assert.equal(cells.eq(5).find('a').text().trim(), 'Edit', 'Check for actions');
    });
});
```

The issue: 
When setting up an acceptance test using the fixture data if the server.db.users is inspected the array is a flat structure without any "attributes" or any kind of structure the serializer should be generating.
Should, when testing, the mirage/serializer/\* be used?
If so, perhaps I have found a bug? Or, I'm missing something when setting up my tests.

(The addon I am building and using mirage to populate the dummy/testing data is currently a private repo, eventually this will be public though)

**Comment by samselikoff** [comment]
Nope, that is correct. Fixtures seed the database (`server.db.users`). Data only passes through the serializer from route handlers. Your shorthand `this.get('/users')` is essentially doing (pseudocode)

```js
this.get('/users', (schema) => {
  let users = schema.user.all();
  
  return this.serialize(users);
});
```

So, your db should never be seeded with serialized data. But, when your Ember app makes an HTTP request to Mirage, it will get back the data in serialized form.
