### ISSUE TITLE
Support for namespaced fixtures and models

### ISSUE THREAD

**Issue by donovan-graham** [samselikoff/ember-cli-mirage#629]
I have a number of models which require nested name spacing. Is there a way to support this in mirage?

`GET /blog/authors?include=blog/posts`

``` js
{
  'blog/authors': [
   {  id: 1, name: 'adam', posts: [1,2] },
   {  id: 2, name: 'bob', posts: [3,4] },
  ]
  'blog/posts': [
   {  id: 1, title: 'Monday thoughts', author: 1 },
   {  id: 2, title: 'Tuesday reminiscence', author: 1 },
   {  id: 3, title: 'Top 10 songs', author: 2 },
   {  id: 4, title: 'Leo says so', author: 2 },
  ]
}
```

`models/blog/author.js`

``` js
import DS from 'ember-data';
export default DS.Model.extend({
  name: DS.attr('string'),
  posts: DS.hasMany('blog/post'),
});
```

`models/blog/post.js`

``` js
import DS from 'ember-data';
export default DS.Model.extend({
  title: DS.attr('string'),
  author: DS.belongsTo('blog/author'),
});
```

**Comment by samselikoff** [comment]
We need to add proper nested support, but for now I would say the best place to do this is in the `serialize` method of your serializer, assuming you're on 0.2 betas.

See [the guides](http://www.ember-cli-mirage.com/docs/v0.2.0-beta.5/serializers/#serializeresponse-request) for how to override serialize, then rewrite your keys.

**Comment by samselikoff** [comment]
Filing under "Subdirectory support" card in the Roadmap project.
