### ISSUE TITLE
Reverse attrs/target on db.update

### ISSUE THREAD

**Issue by samselikoff** [samselikoff/ember-cli-mirage#63]

**Comment by samselikoff** [comment]
Is this still relevant? I think I originally created this issue because I found the original API confusing. I remember changing it, then changing it back. I need to go back and see if it still applies. 

If it does, it'd be good to make the change in current master since 0.2.0 has breaking changes.

**Comment by jherdman** [comment]
IMHO the current API makes sense. For what it's worth, ActiveRecord's class-level [`update` method](http://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-update) uses the same signature.

**Comment by samselikoff** [comment]
Ah, good find. Looks like they have an `update_all` instead of our overloaded `update(attrs)` call. I think it's okay to leave for now, maybe we'll deprecate the update all functionality into a separate method some day, if need be?
