### ISSUE TITLE
Mirage seem to be ignoring --proxy passed on the command line

### ISSUE THREAD

**Issue by pbosse** [samselikoff/ember-cli-mirage#631]
We have hit an issue while trying to disable mirage when using the --proxy in conjunction to setting enabled: false.  It is a random issue, so it might work for awhile then suddenly it stops working.

As far as we know, mirage is not detecting or not passing it up to the App:
```
ENV['ember-cli-mirage'] = {
      enabled: false
    }
```

We are using 0.1.11 of mirage.

**Comment by samselikoff** [comment]
What is the behavior - the Mirage server gets instantiated and starts handling requests?

**Comment by pbosse** [comment]
We troubleshooted a bit more and found out that for some reason, the config/environment.js wasn't passed correctly to the client.  No idea why or how, furthermore it seems to be random. so this is not mirage related at all, so I'll close it.
