### ISSUE TITLE
Embed + Sideload Relationships for a model

### ISSUE THREAD

**Issue by blimmer** [samselikoff/ember-cli-mirage#633]
Is it possible to embed one relationship and sideload another?

For instance, imagine a situation like this:

```
"projects": [{
  "id": "1",
  "supervisor_id": "1",
  "latest_metric": {
    "id": "3",
    "completed": "0.2"
  }
}, {
  "id": "2",
  "supervisor_id": "1",
  "latest_metric": {
    "id": "5",
    "completed": "0.5"
  }  
}],
"supervisors": [{
  "id": "1",
  "first_name": "Bob",
  "last_name": "Jones"
}]
```

In this case, I sideload the supervisor because Bob is the supervisor of multiple project, so I don't want to embed his info in each `project` payload. However, `latest_metric` is a distinct model, but unique to a project and embedded.

Currently, it looks like `embed: true` can only be specified at the serializer level. Is that assumption correct? Should we allow a user to specify this?

**Comment by acorncom** [comment]
@blimmer This issue might be helpful re: the above: https://github.com/samselikoff/ember-cli-mirage/issues/607  TLDR: not now, once the revised version of 0.2 is released

**Comment by samselikoff** [comment]
What if you specified `embed: true` on the `serializers/latest-metric.js`?

For now, until a better API exists for this, you could also sideload everything, and then overwrite `serializers/project.js` and manually add the json yourself, something like

```js
// serializers/project.js

export default ApplicationSerializer.extend({
  serialize(project, request) {
    let json = Serializer.prototype.serialize.apply(this, arguments);

    project.latest_metric = project.latestMetric.attrs;

    return json;
  }
});
```

**Comment by juanazam** [comment]
@samselikoff that approach does work, but there there is a minor tweak to be done, at least in my case calling `Serializer.prototype.serialize.apply(this, arguments)` was not doing the actual serialization on my child object (in this case latestMetric, so its attributes were not converted to snake case). This resulted in the association working, but some attributes were invalid (I took a while to figure that out, it was definitely not my best programming moment).

The tweak: 

```js
export default ApplicationSerializer.extend({
  serialize(project, request) {
    let json = Serializer.prototype.serialize.apply(this, arguments);
    let latestMetricsAttr = Serializer.prototype.serialize.apply(this, [project.latestMetric, request]);

    project.latest_metric = latestMetricsAttr;

    return json;
  }
});
```
Thanks for the help and for `ember-cli-mirage`. If you think it might be worth to enhance the `embed` option per association I can find some time to work on that, it would be a pleasure.

**Comment by samselikoff** [comment]
Closing for now due to inactivity, we can revisit if more folks need this.

**Comment by sethphillips** [comment]
I might add a +1 for a pick and choose which relationships are embedded/vs sideloaded vs just serialized Ids but this thread helped me write a serializer to fit my needs for now
