### ISSUE TITLE
Problem when using both fixtures and factories together

### ISSUE THREAD

**Issue by visualjeff** [samselikoff/ember-cli-mirage#634]
I have factory called **location** and it works fine.  Yeah!   Everything works perfect all the way out to the client.

I added a fixture directory.  With the following file named **buildingconf.js**.  It contains:
```
	export default [
  		{id: 1, value: 'Warehouse'},
                {id: 2, value: 'depot'}
	];
```
My scenarios/default.js contains:
```
	export default function(server) {
   		server.logging = true;
   		server.loadFixtures();
   		server.createList('location', 5);
	}
```

My config file contains (NOTE: I'm returning JSONAPI):
```
   this.get('/buildingconfs', function(db /*, request */) {
        return {
            data: db.buildingconfs.map(attrs => ({
                type: 'buildingconfs',
		        id: attrs.id,
		        attributes: attrs
            }))
        };        
    });
```

When my app runs.  I receive the follow error when trying to load all from the client.

Mirage: Your handler for the url http://localhost:4200/api/v1/buildingconfs threw an error: Cannot read property 'map' of undefined TypeError: Cannot read property 'map' of undefined

Why would buildingconf be undefined?  Is the fixture not getting into the in-memory database?

The version of mirage I'm running is:  0.1.11

Any ideas?

**Comment by visualjeff** [comment]
Anyway, I'm just going to roll with only factories.  They work just fine.  Mixing factories and fixtures might just mean trouble for me.

**Comment by samselikoff** [comment]
Try making the fixture file name should be plural, `/mirage/fixtures/buildingconfs.js`.

We just pushed a change that will prevent this in the future.

**Comment by visualjeff** [comment]
Thanks.  I'll take it for a spin.
