### ISSUE TITLE
passthrough doesn't work when all tests are run, but does when a single test is run.

### ISSUE THREAD

**Issue by NullVoxPopuli** [samselikoff/ember-cli-mirage#637]
in my test environment, I have this:

```
    ENV['ember-cli-mirage'] = {
      enabled: false
    };
```

when that is uncommented, I see in the network panel of the chrome inspector a call to `write-blanket-coverage`

which is great! however, when re-enable ember-cli-mirage (by commenting out the above snippet), the call to that path isn't let through, even though, I have this defined:

```
  // app/mirage/config.js
  this.passthrough('/write-blanket-coverage', ['post']);
```

however, if I click re-run on any test, it appears to work, the call to `write-blanket-coverage` is allowed through.

ref:
 - my repo: https://github.com/NullVoxPopuli/aeonvera-ui
 - https://github.com/sglanzer/ember-cli-blanket/issues/124

**Comment by NullVoxPopuli** [comment]
are there any workarounds for this?

**Comment by NullVoxPopuli** [comment]
@samselikoff any ideas?

**Comment by samselikoff** [comment]
No ideas off the top of my head. My steps to debug would be (1) comment out all tests, start uncommenting them one at a time until you get the smallest set of tests that consistently fail, and debug from there. Then (2) set up a minimum reproducible example in a repo so I can look at it locally and try to figure it out (if you haven't already).

**Comment by NullVoxPopuli** [comment]
Well, I ran every test individually, and each one individually allows the call to write-blanket-coverage through.. hm

**Comment by NullVoxPopuli** [comment]
I figured it out! If I have acceptance tests, the call to `/write-blanket-coverage` never happens when I run all tests

**Comment by NullVoxPopuli** [comment]
@samselikoff do you have a super simple app I could fork to add an acceptance test to see if passthrough no longer works?

My theory is:

 - When all tests are run
   - When there exists Acceptance Tests 
      - The passthrough to be triggered at the end of the test run will not go through (ember-cli-blanket, for example)

**Comment by samselikoff** [comment]
I don't, not on github. Could you try adding `server.shutdown()` to your `afterEach` hook in your acceptance test? Also, what version of Mirage are you on?

**Comment by NullVoxPopuli** [comment]
It looks like, I may have mistakenly had this on the top of my acceptance tests:

```
import Mirage from 'ember-cli-mirage';
```

More info to follow shortly

**Comment by NullVoxPopuli** [comment]
ok, I'm going to mark this resolved. Looks like importing Mirage in an acceptance test breaks the acceptance tests.

**Comment by phikes** [comment]
The `server.shutdown()` worked for me. My coverage was not generated with the same error but I did not have the import-statement in my acceptance tests.
