### ISSUE TITLE
Using mirage in a pre-ember-cli app

### ISSUE THREAD

**Issue by snovity** [samselikoff/ember-cli-mirage#641]
Hi. My goal is to port non-CLI Ember 1.1 app to Ember 2.x. Currently there is no working back-end for the apps, so I though I would use mirage to mock a back-end for both of them to speed up transitioning. Is there any way of using mirage in that old non-CLI Ember 1.1 app?

**Comment by samselikoff** [comment]
There is no dist build of Mirage currently. If you wanted, you could look
at compiling down index.js (or some other way of including the core files
under /addon) and then looking at the Initializer to see how to instantiate
a Mirage server (basically new Server(options)).

**Comment by snovity** [comment]
@samselikoff thanks for the prompt answer, will try to do that

**Comment by n8n8baby** [comment]
@snovity Did you have any success with this? I am in the same boat...

**Comment by snovity** [comment]
@n8n8baby It was not easy, but I was able to do it, I used https://github.com/ef4/ember-giftwrap plus backported three Ember functions `isNone`, `isEmpty`, `isBlank`. Also had to drop the nice Ember CLI imports and revert to old school global naming of factories and scenarios. And certainly there was some luck involved when matching Ember & Mirage versions that would be successfully produce a gitfwrapped Mirage...

**Comment by snovity** [comment]
@n8n8baby If you need this stuff, I can create a repo with giftwrapped Mirage version and instructions of how to integrate it into the old Ember app

**Comment by n8n8baby** [comment]
@snovity That would be great if you could do that. Thanks a million!

**Comment by snovity** [comment]
@n8n8baby sorry for the delay, here is the repo https://github.com/snovity/mirage-giftwrapped

**Comment by n8n8baby** [comment]
Finally getting around to checking it out. Thanks again!

**Comment by n8n8baby** [comment]
Works like a charm. You are, indeed, the MAN! :)

**Comment by n8n8baby** [comment]
Are you looking for a job?

**Comment by snovity** [comment]
hey @n8n8baby, nope, not looking, sorry :)

**Comment by n8n8baby** [comment]
Can't blame a man for trying :) Thanks again!
