### ISSUE TITLE
Inverse relationship not setup properly

### ISSUE THREAD

**Issue by ghedamat** [samselikoff/ember-cli-mirage#643]
When creating the parent model first and then 
creating instances of the "belongsTo" model separately the "hasMany" side doesn't seem to be setup properly

``` js

// models/post.js
import { Model, hasMany } from 'ember-cli-mirage';

export default Model.extend({
  comments: hasMany()
});

// models/comments.js
import { Model, belongsTo } from 'ember-cli-mirage';

export default Model.extend({
  post: belongsTo()
});

// tests/acceptancefoo-test.js
test('Fooing', function(assert) {

  let post = server.create('post');
  c1 = server.create('comment', {
    post: post,

  });
  c2 = server.create('comment', {
    post: post,

  });
  // XXX post.comments should NOT be []
  post.comments = [c1, c2];
  post.save();
  // XXX post.comments is now [c1,c2]

  ...
});
```

Please close if I missed a duplicate of this issue

**Comment by ghedamat** [comment]
(using `post.createComment` works instead)

**Comment by samselikoff** [comment]
This might be because `post` doesn't know about the new comments, since it's just a free variable. (We don't dynamically update instances bc users may set properties and want to then persist them with a call to `.save`).

I would be interested to see if, after creating the comments, you called `post.reload()` if that instance got the new `commentIds` and/or `comments`?

**Comment by ghedamat** [comment]
update: after talking to @samselikoff on slack it looks like
passing `postId: post.id` works and this is actually what's suggested in the docs (very end of page)
http://www.ember-cli-mirage.com/docs/v0.2.0-beta.8/factories/

I found it unexpected behavior but if that's intended feel free to close this issue!

**Comment by ghedamat** [comment]
calling `post.reload()` doesn't fix the issue :/

**Comment by Leooo** [comment]
yes seems like we have to use `server.create('comment', {postId: post.id})` and nothing else to make it work for a hasMany relationship (the following is not working: 
`````
let comment = server.create('comment');
post.comments=[comment]
`````

So would the docs of http://www.ember-cli-mirage.com/docs/v0.2.0-beta.8/factories be better than the last ones of http://www.ember-cli-mirage.com/docs/v0.2.x/models/ then??

**Comment by samselikoff** [comment]
Did you call `post.save()` after this? `post.comments = [ comment1 ]` only sets the comments for this post instance. To persist to the db, you need to call `.save()`.

**Comment by samselikoff** [comment]
The ORM improvements in the 0-3 series should address this.

www.ember-cli-mirage.com/blog/2017/01/09/0-3-0-beta-series/
