### ISSUE TITLE
Do named hasMany (and hasOne) associations require explicit inverses?

### ISSUE THREAD

**Issue by samselikoff** [samselikoff/ember-cli-mirage#644]
I'm working on `hasOne`, which is similar to `hasMany`, and I ran into an issue.

Say we have the following models:

``` js
wordSmith: Model.extend({
  posts: hasMany('blog-post')
}),

blogPost: Model.extend()
```

In this case, `hasMany` adds a foreign key to the `blogPost` model. The name of the key is `wordSmithId`, since `blogPost` has no named association. With this setup, everything works. `blogPost.fks = ["wordSmithId"]`, and given a `wordSmith` instance `wordSmith.posts` would work.

Further, if we add an unnamed `belongsTo` declaration to the `blogPost`, things still work:

``` js
wordSmith: Model.extend({
  posts: hasMany('blog-post')
}),

blogPost: Model.extend({
  wordSmith: belongsTo()
})
```

`blogPost`'s foreign keys are still correct, and an instance of `blogPost` will have a `wordSmith` relation that works.

The wrinkle comes in if we name the `belongsTo` association:

``` js
wordSmith: Model.extend({
  posts: hasMany('blog-post')
}),

blogPost: Model.extend({
  author: belongsTo('word-smith')
})
```

Now, when `schema` reads in this `blogPost` definition, it will give `blogPost` a foreign key of `authorId` - that's the rule for a named association. However, `hasMany` on init checks the target association and makes sure it has a fk of `wordSmithId`; in this case it doesn't, so `blogPost` ends up with two fks:

``` js
blogPost.fks;  // [ 'authorId', 'wordSmithId' ]
```

Defining an explicit inverse on the `wordSmith` solves the problem:

``` js
wordSmith: Model.extend({
  posts: hasMany('blog-post', { inverseOf: 'author' })
}),

blogPost: Model.extend({
  author: belongsTo('word-smith')
})

blogPost.fks;  // [ 'authorId' ]
```

I ran into the same thing while working on `hasOne`, and I just wanted to verify that this is indeed correct and expected behavior. The one thing that concerns me is someone could end up with the configuration above and have two foreign keys without realizing it. Of course, this is tricky because they could actually intend to have two different associations, so we can't rule that out. This may not be a problem at all.

The only potential change here I can think of would be to always require `inverseOf` to be defined on `hasMany` associations, which would tell Mirage explicitly what foreign key to create in lieu of an explicit `belongsTo` declaration on the other side. The same would be true of `hasOne`. But, I think this adds unnecessary work to the case where things match up with the defaults:

``` js
wordSmith: Model.extend({
  favoritePost: hasOne()
}),

blogPost: Model.extend()
```

This would yield `blogPost.fks = ['wordSmithId']`, and if it ever needed to change the user would need to specify an explicit inverse on the `favoritePost`. I think this is okay, again just wanted a second pair of eyes on this. What do you think?

/cc @ef4

**Comment by Serabe** [comment]
My two cents on this issue: I have an app with a really complicated collection of models. Most of our relationships need to include the `inverse: null` option so things do not get weird with automatic associations.

I guess in the case:

```js
wordSmith: Model.extend({
  posts: hasMany('blog-post', { inverseOf: null })
}),

blogPost: Model.extend({
  wordSmith: belongsTo()
})
```

`blogPost` would need to have two different `fks`: `wordSmith` and another for the `posts`relationship in the `wordSmith` model.
