### ISSUE TITLE
Acceptance tests work locally but fail in Travis (PhantomJS)

### ISSUE THREAD

**Issue by cdeeter** [samselikoff/ember-cli-mirage#656]
Hi there,

I'm having an issue running my acceptance tests (which use ember-cli-mirage) with PhantomJS in Travis. They work fine locally and I'm able to see the data I get back from the factory stubs, but when it's pushed to Github and Travis gets a hold of it, it hangs with a "timeout of 2000ms exceeded. Ensure the done() callback is being called in this test." error. It shows this for the very first test (the default one created with ember-cli) and then all subsequent tests as well.

I don't know if this is necessarily an issue with ember-cli-mirage, but I've been at a loss to this issue for a couple days now and was wondering if maybe anyone has an idea? Unfortunately I'm not sure how I can make this reproducible for others to test since it all works fine locally... but here are some details:

Node version: 5.7.1
npm version: 3.6.0
PhantomJS version: 1.9 (have also tried 2.0)
Ember version: 2.4.1
Testing framework/library: Mocha/Chai

Have tried things such as: adding a done() call to my tests, extending the timeout time, upgrading Node and Phantom versions to make sure they match both local and remote, etc...

If anyone has encountered anything like this (or alternatively if there's a better place to ask about this), advice would be much appreciated!

Thank you!

**Comment by cdeeter** [comment]
Turns out I was missing some env variables (API server URL and API server namespace) in my Travis file. This was not immediately obvious to me as someone new to Ember/testing. :3 Closing issue!

**Comment by samselikoff** [comment]
Ok, sorry you ran into this and sorry I was busy this past week! Let me know if you run into anything else
