### ISSUE TITLE
Document `?include` query param support in JSONAPISerializer

### ISSUE THREAD

**Issue by samselikoff** [samselikoff/ember-cli-mirage#659]
It works. we just need to write about it!

**Comment by maschwenk** [comment]
@samselikoff Maybe there you could address the difference between the includes in the serializers and the includes in the query params? Is it simply that one is driven by client, the other defined by the backend?

**Comment by samselikoff** [comment]
Yep, the backend one is the "default" includes, so if you have it specific and the client doesn't, it will be used. If the client specifies `?include`, that will always take precedence.

**Comment by alecho** [comment]
@samselikoff I'll grab this one.

I'm struggling to figure out where in the docs this should go. I think awhile ago @samselikoff mentioned something about having separate docs for each serializer. I don't know if that still makes sense. For now I can put something under "Shorthands" as a JSONAPISerializer specific note unless someone has a better idea as to where this should go.

**Comment by samselikoff** [comment]
@alecho I think if a user were looking for info on the `?include` query param support for json:api serializer, it's reasonable to think they'd click "Serializers".

How about we make another link right next to http://www.ember-cli-mirage.com/docs/v0.2.x/serializers/#include, call it `#include-query-param`, and explain it there, making sure to communicate that it's only for the JSONAPISerializer?

**Comment by samselikoff** [comment]
https://github.com/samselikoff/ember-cli-mirage/pull/763 closes
