### ISSUE TITLE
QueryParams not recognized (e.g. on store.filter)

### ISSUE THREAD

**Issue by jens-a-e** [samselikoff/ember-cli-mirage#66]
Hi,
i am having issues when using query params (such as using `this.store.filter('someModel', {some: "param"});` for example.

The error reported is:
```
Mirage: The route handler for /api/v1/languages?isDefault=true is requesting data from the languages?isDefault=trues collection, but that collection doesn't exist. To create it, create an empty fixture file or factory.
```

Defining this route in `config.js` or overriding the `server.get(...)` in a test does not solve it.

Is there a way to handle these request / defining these routes?

**Comment by samselikoff** [comment]
I see, can you show me the route you defined in `config.js`?

**Comment by jens-a-e** [comment]
Sure (don't mind the non-get verbs):

```
  this.get('languages');
  this.get('languages/:id');
  this.post('languages');
  this.put('languages/:id');
  this.delete('languages/:id');
```
Prerably, if query params are detected, it would be great to handle them in a callback; or with a filter on the collection by default!?

**Comment by samselikoff** [comment]
Yep this is a bug, it should get the languages collection and let you work
with the query params via request.params. I'll check it out.

**Comment by samselikoff** [comment]
@jens-a-e fixed in master, you can use now with this in your package.json:

"ember-cli-mirage": "samselikoff/ember-cli-mirage"

**Comment by jens-a-e** [comment]
:+1: nice! thx for the quick fix!!

**Comment by jherdman** [comment]
I think this might be broken in 0.0.27. I'm seeing the following in my application:

```
Mirage: The route handler for /api/v1/activity_responses?focused=true&membership_id=1 is requesting data from the activity_responses collection, but that collection doesn't exist. To create it, create an empty fixture file or factory.
```

**Comment by jherdman** [comment]
Never mind! I made a mistake.
