### ISSUE TITLE
Docs are installed alongside add on

### ISSUE THREAD

**Issue by beerlington** [samselikoff/ember-cli-mirage#662]
The docs _site directory is being installed within the node_modules/ember-cli-mirage directory when installing the add-on, bring close to 200MB of files with it. 

![screen shot 2016-03-24 at 10 03 31 am](https://cloud.githubusercontent.com/assets/77580/14020181/69cb084c-f1ac-11e5-8d97-0e80e830e811.png)

**Comment by samselikoff** [comment]
Thanks!

I missed that [this](https://github.com/samselikoff/ember-cli-mirage/blob/master/.npmignore) was added.

**Comment by samselikoff** [comment]
You can install `samselikoff/ember-cli-mirage#1a37006` if you'd like to get this now

**Comment by samselikoff** [comment]
v.0.2.0-beta.8 published: https://github.com/samselikoff/ember-cli-mirage/releases/tag/v0.2.0-beta.8
