### ISSUE TITLE
Mirage fails when models are in sub-folders

### ISSUE THREAD

**Issue by BryanHunt** [samselikoff/ember-cli-mirage#663]
Using 0.2.0-beta.8
`ember g mirage-model admin/log`

ember.debug.js:32127Error: Assertion Failed: Subdirectories under admin are not supported
    at new Error (native)
    at Error.EmberError (http://localhost:4200/assets/vendor.js:26056:21)
    at assert (http://localhost:4200/assets/vendor.js:15815:13)
    at Object.assert (http://localhost:4200/assets/vendor.js:25820:34)
    at http://localhost:4200/assets/vendor.js:117769:25
    at Array.forEach (native)
    at exports.default (http://localhost:4200/assets/vendor.js:117761:8)
    at startMirage (http://localhost:4200/assets/client.js:415:66)
    at Object.initialize (http://localhost:4200/assets/client.js:406:9)
    at http://localhost:4200/assets/vendor.js:14823:23

**Comment by samselikoff** [comment]
Thanks for the opening this - this is not super high priority right now, I know it's a pain but for now if you use something else to namespace (underscore, hyphen, etc.) you should still be able to mock your server's endpoints.

**Comment by sky-coding** [comment]
Hey Sam, I am working on an enterprise application that uses pods and has dozens of models neatly organized into their feature folders. It is frustrating to have to flatten our structure and dump all of the factories for our previously organized models into a single folder. We love mirage and understand there are higher priorities, but I want to let you know that it would noticeably improve maintainability if folders were supported.

**Comment by samselikoff** [comment]
@sky-coding this is definitely on the roadmap, but it's not currently the highest priority for the community at large. If your company is interested in sponsoring me, I would be open to working on this issue immediately. Feel free to reach out + we can kick off a discussion.

**Comment by mrosenberg** [comment]
I'm experiencing a similar issue. I don't mind recreating models and factories into a single level but it does present an issue serializing relationships. Given the following structure in Ember:

models -
 client.js
 client -
  goal.js

Ember expects the model type for the client - goal relationship to 'client/goal'. Flattening out my directory structure I've named that model client-goal.js and Mirage sets the model type to 'client-goal'. Emberjs throws an error saying it cannot find that model.

**Comment by samselikoff** [comment]
Busy atm, but have you tried some of the serializer hooks? `keyForRelationship` perhaps? I'm not sure if there's one that will accommodate this, atm. You can always call super and do last-minute data munging in `serialize`

**Comment by mrosenberg** [comment]
I've been digging through the source messing with the hooks. I haven't found a good place yet to transform the data. 

It looks like Mirage does a lot of normalization on init. For instance I have a model that in Ember is 'client/campaign-group' as it is nested. The Mirage model is named 'client_campaign-group' replacing the slash with an underscore to denote the nesting. Mirage then renames that to 'client-campaign-group' at some point which makes a simple str.replace in `serialize` impossible.

**Comment by samselikoff** [comment]
That's frustrating.

Until we have proper support for nested models, you may just need to whitelist some find-and-replaces.

**Comment by mrosenberg** [comment]
I'm writing some manual fixes now. 

Mirage is awesome and the new ORM will be killer. Thanks for all your hard work on this.

**Comment by abrthel** [comment]
To work around this issue for now I've implemented the `typeKeyForModel` hook in my mirage application serializer. 

```javascript
import { JSONAPISerializer } from 'ember-cli-mirage'
import Ember from 'ember'
const { dasherize, pluralize } = Ember.String

export default JSONAPISerializer.extend({
  typeKeyForModel(model) {
    let typeKey = model.typeKey || model.modelName
    return dasherize(pluralize(typeKey))
  }
})
```

Then on each model I just place a `typeKey` attribute where I need to adjust the output type. For instance I have a model that lives in the folder `models/references/faction` and ember can find it if I create a mirage model like so

``` javascript
import { Model } from 'ember-cli-mirage'

export default Model.extend({
  typeKey: 'references/faction'
})
```

**Comment by mrosenberg** [comment]
@abrthel That worked beautifully.

**Comment by samselikoff** [comment]
Filing this under the "Subdirectory support" card in the Roadmap project

**Comment by kitsuneyo** [comment]
Hi @abrthel, sorry for dragging up this old post, I'd like to try your solution but as an Ember newbie I don't fully understand it. What would you name the fixture and factory files in your `references/faction` example? What did you name the mirage model? (I'm guessing 'references-faction.js'?)

**Comment by abrthel** [comment]
@kitsuneyo hey, not a problem. Unfortunately I probably won't be much help atm as I can't even remember exactly what issue this was trying to solve and I don't have access to the code where it was used.

**Comment by kitsuneyo** [comment]
@abrthel No worries, figured it out with a little perseverance, many thanks for this!
