### ISSUE TITLE
ManyToMany relationships "maximum stack size exceeded"

### ISSUE THREAD

**Issue by jackmatt2** [samselikoff/ember-cli-mirage#665]
// authentication-protocol
export default Model.extend({
  integrationLevels: hasMany(),
  ssoApplications: hasMany()   <-------- need to remove for this to work
});

// integration-level
export default Model.extend({
  authenticationProtocols: hasMany(),
  ssoApplications: hasMany()  <--------  need to remove for this to work
});

// sso-application
export default Model.extend({
  authenticationProtocol: belongsTo(),
  integrationLevel: belongsTo()
});

The above gets caught in an infinite loop when and ember-data model is saved to mirage via a POST request.  If comment out the marked lines above it is able to save successfullly. Is this a bug or is there a better way of doing this.  I  don't want to introduce join tables if possible because there are none in my ember-data model.

**Comment by jackmatt2** [comment]
Just to clarify.

1. An `sso-application` has a single `authentication-level` and `integration-level` selected from a dropdown.
2. When an `authentication-protocol` is selected, the `integration-level` dropdown is filtered according to the `authentication-protocol` selected.
3. The same `integration-level` may belong to zero or more `authentication-protocols` hence the ManyToMany.

**Comment by samselikoff** [comment]
Right now you need a join model on the Mirage side. It's a known issue and is prioritized, but atm that's the reason why :(

**Comment by samselikoff** [comment]
Btw the fact that you need a join model doesn't need to leak into your route handler:

```js
// serializers/post.js
export default Serializer.extend({
  
  serialize(model) {
    let json = Serializer.prototype.serialize.apply(this, arguments);

    let tagIds = post.postTags.map(pt => pt.tagId);
    json.post.tag_ids = tagIds;

    return json;
  }

})
```

**Comment by runspired** [comment]
@samselikoff overriding serializer doesn't work for sideloaded or included records.  The moment you need to serialize the other end of the join, you hit impossible to work around infinite loops.

**Comment by garrettlancaster** [comment]
👍 bump

**Comment by samselikoff** [comment]
Just wanted to drop a note - been working on ORM layer this week, and is #1 priority to get this stuff fixed.

**Comment by samselikoff** [comment]
The new ORM improvements in the 0-3 series should address this ✨ 

www.ember-cli-mirage.com/blog/2017/01/09/0-3-0-beta-series/
