### ISSUE TITLE
'attrs' incorrectly applying to included records

### ISSUE THREAD

**Issue by richmolj** [samselikoff/ember-cli-mirage#666]
This is for 0.2x, happening at least on JSONAPISerializer.

Let's say you have `Post` and `Comment` models. We only want to serialize `id` and `title` for `Post`, but `Comment` should serialize all attributes:

```es6
// mirage/serializers/post.js
import BaseSerializer from './application';

export default BaseSerializer.extend({
  attrs: ['id', 'title'],
  include: ['comments']
});
```

The `attrs` here will incorrectly apply to `comments` as well - you'd have to add attributes of `Comment` to `attrs` if you want them to render.

This is because `_attrsForModel` [references 'this'](https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/serializers/json-api-serializer.js#L179), [even for the included records](https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/serializers/json-api-serializer.js#L89).

I've only scanned it but I believe https://github.com/samselikoff/ember-cli-mirage/issues/607 will likely fix this issue as a side effect.

**Comment by samselikoff** [comment]
Nope, was a bug. Thanks for opening the issue!
