### ISSUE TITLE
Latest Travis build did not run all tests

### ISSUE THREAD

**Issue by lependu** [samselikoff/ember-cli-mirage#671]
I have no experience with Travis, so maybe the problem is in my side, but I am figthing with this issue for a while as mentioned [here](https://github.com/samselikoff/ember-cli-mirage/issues/657#issuecomment-200601524), and now it seems to me Travis does not run all tests.

Update: Maybe this issue is the reason: DockYard/ember-suave#94, kellyselden/broccoli-jscs#53.

Reproducing:
`git clone git@github.com:samselikoff/ember-cli-mirage.git`
`cd ember-cli-mirage`
`npm cache clean`
`bower cache clean`
`npm i`
`bower i`
`npm test`
>ember-cli-mirage@0.2.0-beta.8 test /home/ror/ember/ember-cli-mirage
>ember try:testall && mocha tests/**/*-test-node.js

>Cannot find module 'lodash/lang/isFunction'
>Error: Cannot find module 'lodash/lang/isFunction'
>    at Function.Module._resolveFilename (module.js:339:15)
>    at Function.Module._load (module.js:290:25)
>    at Module.require (module.js:367:17)
>    at require (internal/module.js:16:19)
>    at Object.<anonymous> (/home/ror/ember/ember-cli-mirage/node_modules/babel-core/lib/api/node.js:21:29)
>    at Module._compile (module.js:413:34)
>    at Object.Module._extensions..js (module.js:422:10)
>    at Module.load (module.js:357:32)
>    at Function.Module._load (module.js:314:12)
>    at Module.require (module.js:367:17)
>npm ERR! Test failed.  See above for more details.

`rm -rf node_modules/babel-core`
`npm i`
`npm test`

test runs with the result:
>1..1073
>tests 1073
>pass  1070
>skip  0
>fail  3

Meanwhile the latest travis job [1052.1](https://travis-ci.org/samselikoff/ember-cli-mirage/jobs/119717233):
>1..1009
>tests 1009
>pass  1009
>skip  0
>fail  0

**Comment by samselikoff** [comment]
Try rebasing off master

**Comment by lependu** [comment]
Done.
