### ISSUE TITLE
creating a hasMany relation is not persisting

### ISSUE THREAD

**Issue by GCorbel** [samselikoff/ember-cli-mirage#672]
On ember-cli-mirage `0.2.0.beta8`, I'm doing this : 

```
    let activity = server.create('activity', { name: 'Tenis' });

    activity.createCourse({name: 'test'});
    activity.save(); # Just to be sure

    var store = application.__container__.lookup('service:store');
    store.findAll('activity').then(function(activities) {
      expect(activities.objectAt(0).get('courses.length')).to.eq(1);
    });
```

It fails because `courses.length` gives 0. 

Here is my model :

```
import { Model, hasMany } from 'ember-cli-mirage';

export default Model.extend({
  courses: hasMany()
});
```

Is there something wrong?

**Comment by GCorbel** [comment]
I may help. This : 

```
    console.log('1', activity._schema.activity.all()[0].course_ids);
    console.log('2', activity._schema.activity.all()[0].courseIds);

    activity.course_ids = [course.id];
    activity.courseIds = [course.id];
    activity.save();

    console.log('3', activity._schema.activity.all()[0].course_ids);
    console.log('4', activity._schema.activity.all()[0].courseIds);

```

gives

```
1 []
2 []
3 ["1"]
4 []
```

I'm using JSON API

**Comment by samselikoff** [comment]
After `activity.save()` on your first line, can you check

```
server.db.activities;
server.db.courses;
```

and show me that data?

**Comment by GCorbel** [comment]
I have this : 

```
    let activity = server.create('activity', { name: 'Tenis' });
    activity.createCourse({name: 'test'});
    activity.save();

    console.log(JSON.stringify(server.db.activities));
    console.log(JSON.stringify(server.db.courses));
```
[{"courses":[],"course_ids":[],"name":"Tenis","id":"1"}]
[{"name":"test","activityId":"1","id":"1"}]

**Comment by samselikoff** [comment]
Are you loading fixture data? `course_ids` looks wrong, the ORM uses `courseIds` but those shouldn't even be in the db anywhere.

Does your `activity` factory create ids somewhere?

**Comment by GCorbel** [comment]
Here is the factory for activity

```
import Mirage from 'ember-cli-mirage';

export default Mirage.Factory.extend({
  name: 'IT',
  course_ids: [],
  courses: []
});
```

I have no fixtures. I don't have any data elsewhere.

**Comment by samselikoff** [comment]
Remove `courses` and `course_ids` from the factory

**Comment by GCorbel** [comment]
I did it and I have this result : 

```
[{"name":"Tenis","id":"1"}]
[{"name":"test","activityId":"1","id":"1"}]
```

**Comment by GCorbel** [comment]
It works. I retried with the `findAll` method and it works now.

Thanks a lot!

**Comment by samselikoff** [comment]
You're welcome! We should probably have relationships override attrs in the event this sort of thing happens again.

**Comment by GCorbel** [comment]
Yes, I agree. `ember-cli-mirage` is really awesome. Please don't stop your work!

**Comment by GCorbel** [comment]
I have a similar issue in another case.

I have this code : 

```
    let activity = server.create('activity', { name: 'Tenis' });
    let course = activity.createCourse({name: 'Adult'});
    course.createGroup({name: '12h-13h', nbPlaces: 12, schedule: '12h'});

    var store = application.__container__.lookup('service:store');
    store.findAll('course').then(function(courses) {
      let group = courses.objectAt(0).get('groups').objectAt(0);
      console.log(group.get('name'));
    });
```

`group.get('name')` gives `undefined`. When I add `store.findAll('group')` after the creation of the group, `group.get('name')` gives the real name.

I can submit a new issue if you prefer.

**Comment by samselikoff** [comment]
Is your Mirage server sideloading the `groups` with the `courses`? Are the relationships async or sync?

Btw you can do `courses.get('firstObject.groups.firstObject')`.

**Comment by GCorbel** [comment]
I did this 

```
    let activity = server.create('activity', { name: 'Tenis' });
    let course = activity.createCourse({name: 'Adult'});
    course.createGroup({name: '12h-13h', nbPlaces: 12, schedule: '12h'});

    var store = application.__container__.lookup('service:store');
    Ember.run(function() {
      store.findRecord('course', course.id).then(function(course) {
        console.log(JSON.stringify(course.get('firstObject.groups.firstObject')));
      });
    });
```

The result is `undefined`. All relations are synchronous. My server is not triggered.

I tried to put the code in `Ember.run` and it's the same result.

**Comment by samselikoff** [comment]
`server.create` puts records in Mirage's db, not Ember Data's. You need to go through the network to get them into Ember Data's store.
