### ISSUE TITLE
JSON-API serializer include dot-paths leave out intermediary models (but works with queryParams)

### ISSUE THREAD

**Issue by nruth** [samselikoff/ember-cli-mirage#675]
I think Mirage (master) is leaving out intermediary models included with a dot path, but only if they're specified by the serializer instead of query params. The tests only cover the query-params case (which looks like it works) so I've added some below.

If someone could check if the test cases I've linked to below look OK that'd be great.

### JSON-API include multi-part paths and compound documents
According to http://jsonapi.org/format/#fetching-includes

>Note: Because compound documents require full linkage (except when relationship linkage is excluded by sparse fieldsets), intermediate resources in a multi-part path must be returned along with the leaf nodes. For example, a response to a request for comments.author should include comments as well as the author of each of those comments.

### Mirage behaviour (and integration test cases)

In the mirage tests, this seems to work with query-params but not serializer specified includes.

i.e. for query params see https://github.com/samselikoff/ember-cli-mirage/blob/master/tests/integration/serializers/json-api-serializer/associations/included-test.js#L298

However for serializer set it doesn't seem to work. This was missing in the original test so I've forked and added 3 cases to the integration test.

These two show the current behaviour:
https://github.com/nruth/ember-cli-mirage/blob/4a123614fd2966151ba3acb762538431f206b2e1/tests/integration/serializers/json-api-serializer/associations/included-test.js#L436
and
https://github.com/nruth/ember-cli-mirage/blob/4a123614fd2966151ba3acb762538431f206b2e1/tests/integration/serializers/json-api-serializer/associations/included-test.js#L485

And this shows what I think should happen:
https://github.com/nruth/ember-cli-mirage/blob/4a123614fd2966151ba3acb762538431f206b2e1/tests/integration/serializers/json-api-serializer/associations/included-test.js#L622

I'm running the tests with 
`ember test --module 'Integration | Serializers | JSON API Serializer | Associations | Included'` after npm install && bower install (and having run npm test a couple of times previously).

**Comment by samselikoff** [comment]
Thanks for this! Easiest way for me to review is just to just PR your branch against the project. The tests will run & we'll be able to see them fail. Would you mind doing that?

**Comment by nruth** [comment]
Yep ok. Closing this so it doesn't duplicate the PR. I've written less in the PR but it links back here anyway.
