### ISSUE TITLE
Support for Polymorphic relationships

### ISSUE THREAD

**Issue by JakeDluhy** [samselikoff/ember-cli-mirage#677]
Unless it's just undocumented, I don't think there's support for polymorphic relationships with the ORM. I think the best solution would be an implementation similar to the way it's represented in rails (e.g. have polymorphicId and polymorphicType attributes on the factory, that the serializer is smart about finding).

I'd definitely be willing to take a crack at it, once I get a bit of time, as one of the projects I'm working on has those data requirements.

p.s. LOVE 0.2.x right now! I'm finding it very easy to mock my data

**Comment by samselikoff** [comment]
:+1: so glad to hear!

Yes we need to add this, and also hasOne (almost done), and hasAndBelongsToMany.

These are blocked by finalizing the serializer API, which should be done soon.

**Comment by samselikoff** [comment]
Oh and if you want to take a crack at it, please do! Once you dive in I'm happy to dive in.

**Comment by dukejeffrie** [comment]
Hi, folks, is this still going to be implemented? Is there a workaround for a polymorphic hasMany()? I've been trying to hack my own, without success.

**Comment by samselikoff** [comment]
Quick update, been busy but got some sponsorship to work on polymorphic. So will be starting on this soon.

**Comment by bauerjon** [comment]
@samselikoff is there any update on the progress of this feature? thanks!

**Comment by samselikoff** [comment]
There has been progress, you can follow along here: https://github.com/samselikoff/ember-cli-mirage/projects/1

I expect another month or two before the ORM will be ready. For now, I'd suggest hand-mocking polymorphic routes, or hacking it into the current serializer layer.

**Comment by hbrysiewicz** [comment]
Closing as this has been added to Mirage. You can view more information about this feature [here](http://www.ember-cli-mirage.com/blog/2017/06/05/polymorphic-associations-and-auto-discovery-of-ember-data-models/)
