### ISSUE TITLE
db's collection.find should handle an array of ids... 

### ISSUE THREAD

**Issue by lukemelia** [samselikoff/ember-cli-mirage#68]
and return an array of items with those ids (a la ActiveRecord::Base#find)

**Comment by samselikoff** [comment]
`.find([1, 2, 3])` and/or `.find(1, 2, 3)`?

**Comment by lukemelia** [comment]
I think the change you made is sufficient. Supporting `.find(1, 2, 3)` is going to limit future API flexibility
