### ISSUE TITLE
setup-mirage-for-integration missing

### ISSUE THREAD

**Issue by ajgordo** [samselikoff/ember-cli-mirage#684]
Reading through the documentation I see mention of setup-mirage-for-integration to perform testing during integration, but in 0.2.0-beta8 there is no sign of this file. 
Am I missing something?

**Comment by MrNickBreen** [comment]
I'm seeing the file here: https://github.com/samselikoff/ember-cli-mirage/blob/master/app/initializers/ember-cli-mirage.js not sure how to access this from my own ember app that's importing mirage.

**Comment by MrNickBreen** [comment]
Oh! Right, this file is added to your project thanks to the ember-mirage addon. Even though you may not see it explicitly in your IDE's file structure. I added the file (as instructed: http://www.ember-cli-mirage.com/docs/v0.1.x/manually-starting-mirage/) and it works well.
