### ISSUE TITLE
2nd parameter of store.loadData?

### ISSUE THREAD

**Issue by dlo83** [samselikoff/ember-cli-mirage#685]
Hey there, we're upgrading ember-pretenderify v 0.0.17 to the latest version of ember-cli-mirage. After migrating to 0.0.18, I'm trying to convert this test data to factories, but need to figure out what the second parameter means in the context of this data, to make sure I get my factory right.

Example: what does 'completions' mean in this context?

```
store.loadData([{
    id: '1',
    response: {
      'compstatus': {
        '1': {
          'completeness': '100.00',
          'visited': 'true',
          'answered': 'true',
          'mode': 'test'
        }
      }
    }
  }], 'completions');
```

**Comment by samselikoff** [comment]
Looks like it was [the key of the database](https://github.com/samselikoff/ember-cli-mirage/blob/38587f5830b22b552cf01f9dfc6257e70fad7993/addon/store.js#L9-L17), basically the collection name

**Comment by dlo83** [comment]
Gotcha... I think a more appropriate question would be, how would I replicate the same behavior of the loadData function inside my integration test--that is, assigning a collection name to the data--using factories?  (Excuse the noob question; testing is not currently my forté, but I'm working on it.)

Example: I've extracted the data above out into a factory defined in pretender/factories/full-completion.js:

```
import EP from 'ember-pretenderify';

export default EP.Factory.extend({
  id: '1',
  response: {
    'compstatus': {
      '1': {
        'completeness': '100.00',
        'visited': 'true',
        'answered': 'true',
        'mode': 'test'      
      }
    }
  }
});
```

Now in my integration test, I modified the following test:

```
test('does not display a warning if user tries submit an activity with all questions answered', function() {
  expect(1);

  // now, instead of store.loadData([...]), I have the following:
  var completions = server.createList('full-completion', 1); <-- does not seem to work


  return startActivity(url)...
    .then(clickSubmitButton)
    ...
    });
});
```

Am I way off base, or thinking about this the wrong way?  Thanks for your help!

**Comment by samselikoff** [comment]
Are you on Mirage? Pretenderify is really old and I would recommend giving [Mirage's docs a read](http://www.ember-cli-mirage.com/docs/v0.1.x/). The idea with factories is that they seed an in-memory database. The factory you wrote above looks more like an API response. You want to keep the factories just about the data.

**Comment by dlo83** [comment]
Yeah, unfortunately I'm on Pretenderify and looking to get on the latest version of Mirage ASAP.  I just thought that the Ember Way™ of upgrading was to go release by release, fixing deprecations along the way before moving on to the next, but perhaps that doesn't apply to addons?  If you think it would be easier migrating straight away to the latest version of Mirage and going back to fix all deprecations wholesale, then I'll take that approach.  Trying to find the old docs for each release and comparing them to each next release is a PITA anyway :)

**Comment by samselikoff** [comment]
yah Pretenderify was really a spike. How much testing code is there?

**Comment by dlo83** [comment]
3000+ tests :)  Fun times.

**Comment by samselikoff** [comment]
acceptance?

**Comment by samselikoff** [comment]
yah. Well those shouldn't have to change too much, depending on how you set up Mirage. You should probably switch over, the Pretenderify code is debt.

**Comment by dlo83** [comment]
In the process of doing so right now :)  Thanks for the feedback!  I'll close this one out.
