### ISSUE TITLE
Seeding many-to-many is behaving strangely?

### ISSUE THREAD

**Issue by coladarci** [samselikoff/ember-cli-mirage#688]
```
bar = server.create('bar');
foo = server.createList('foo', 5, { barIds: [bar.id] });
```

Results in 5 `foo`'s with only the last one pointng to `bar`.

If I switch the data model to be this:

```
bar = server.create('bar');
foo = server.createList('foo', 5, { barId: bar.id });
```

Everything goes back to working. (except that makes `foo` `belongTo` `bar` instead of `hasMany` `bars`. Am I missing something obvious? 

Thanks!

**Comment by samselikoff** [comment]
Right now with many-to-many, you need to model an explicit join model - in this case, `foo_bars`, that belongs to both `foo` and `bar`. If you want to include a `foo`'s `bar_ids`, you'd need to do this in the serializer layer.

We'll eventually have support for something like Rails' `has_many_and_belongs_to`, which would make this step unnecessary, but for now it's the workaround.

**Comment by coladarci** [comment]
Thanks, Sam! In my case I might be able to do away with the actual relationship modeling for my factories; I just need an array of barIds, so maybe if I kill the relationship I can just set them as a vanilla array..

**Comment by samselikoff** [comment]
You can, but you may run into a situation where you want the test to setup which `bar`s the `foo` has. In these cases it's nice to be able to set up the data within your test.

**Comment by davidlormor** [comment]
Running into the same issues here...just curious - is there any particular advantage to setting up the hasMany relationship via foreign keys in the associated model vs. storing an array of IDs in the primary model?  I know this is typical for relational-type db modeling, but is that a constraint on Mirage? I'm not exactly sure how Ember Data handles their many-to-many relationships (I do know it's been a longtime pain point, although it seems to be in a good place these days), but I'm not aware of foreign key usage...

It seems like this could possibly simplify the construction of many-to-many relationships - simply add the foreign ID to the primary model hasMany array and check for an inverse on the foreign model and add the ID if necessary? I know it's a bit of a contrived example, just my 2 cents...

Either way, thanks for all your hard work @samselikoff - this really is a fantastic tool, and I know plenty of folks in the Ember community are raving about it. I'm sure you weren't setting out to build a full-scale ORM - much respect for all the effort!

**Comment by samselikoff** [comment]
You're welcome, and thanks for the kind words :)

When we get to `hasAndBelongsToMany` it may be that it's easiest to just store the array. You're correct that my reasoning was to just build off of well-tested patterns; but we obviously don't have all the constraints of a traditional database (e.g. field types). When I get to this it might be easiest to go the route of the ids array. I'll need to think through it a bit - but this is high up on my priority list!

**Comment by samselikoff** [comment]
The ORM improvements in the 0-3 series should address this

www.ember-cli-mirage.com/blog/2017/01/09/0-3-0-beta-series/
