### ISSUE TITLE
Configure scenario from environment.js

### ISSUE THREAD

**Issue by angelosarto** [samselikoff/ember-cli-mirage#690]
Is there a planned feature for adding additional scenarios beyond default.js?

The use case is:
My models, fixtures, serializers, factories are the same but I do want to configure them differently e.g. depending on which feature I am working on in development.  The two files that I think would need to change would be scenarios/default.js and config.js.    Basically I might want to load different test data (and vary which routes are proxied depending on the current feature being developed).

I have created local mirage environment configurations in environment.js so that each can be run with `ember serve -e demo-local` 

I would love to be able to choose a different config.js and scenario/default.js from the environment.js file.

I did see the "directory" configuration but this would require duplicating all of the models (or I guess I could sym-link the ones I wanted to be the same...)

**Comment by samselikoff** [comment]
This was the original idea when making `scenarios/default.js`, but this is not a short-term item that's being worked on right. Feel free to propose an API or even a PR!

**Comment by samselikoff** [comment]
Filed under "Support additional scenarios" note in the Roadmap project
