### ISSUE TITLE
Factories are instantiated with attributes undefined

### ISSUE THREAD

**Issue by Gaurav0** [samselikoff/ember-cli-mirage#691]
This used to work in mirage 0.2.0beta7 but fails in 0.2.0beta8

in test:

```
server.create('factory', { name: 'foo' });
```

in factory:

```
  bar() {
    return this.name.substr(1);
  }
```

error:
`Cannot read substr of undefined`

workaround (this totally works!):

```
  bar() {
    return this.name && this.name.substr(1)
  }
```

**Comment by samselikoff** [comment]
ah. the `this.name` must be lazily calculated based on the new dynamic reference implementation.

**Comment by leepfrog** [comment]
Also seeing this on beta8..  Here's an example that doesn't work:

```
export default Factory.extend({
  firstName(){
    return faker.name.firstName();
  },
  lastName() {
    return faker.name.lastName();
  },
  initials() {
      return `${this.firstName[0]}${this.lastName[0]}`;
    }
  }
});
```
On this, it throws an exception (because this.firstName is undefined).

**Comment by ef4** [comment]
@Gaurav0 Thanks for the workaround.  This is still an issue in 0.2.2.

I will circle back and try to fix it if I can pop enough other things off my stack.

**Comment by samselikoff** [comment]
_**Help wanted - anyone can pick this up**_: I think this works if `name` were defined on the factory, so the factory code needs to handle the case where it's undefined.

[Here's a relevant factory unit test](https://github.com/samselikoff/ember-cli-mirage/blob/master/tests/unit/factory-test.js#L75-L89), I would say start here with a new test that has the dynamic property defined but not the original. Then fix the code in [factory.js](https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/factory.js) to handle that.
