### ISSUE TITLE
Could not find module in setup-mirage-for-integraiton.js

### ISSUE THREAD

**Issue by sammilechman** [samselikoff/ember-cli-mirage#692]
Hi,

I'm trying to set up mirage for the first time in my ember app for the purpose of integration testing and followed the steps [here](http://www.ember-cli-mirage.com/docs/v0.1.x/manually-starting-mirage/) to manually start the mirage server.

testem.js:720 Error loading: myproject/tests/acceptance/index-test Error: Could not find module `myproject/initializers/ember-cli-mirage` imported from `myproject/tests/helpers/setup-mirage-for-integration`

The contents of `tests/helpers/setup-mirage-for-integration.js`: 
```
import mirageInitializer from '../../initializers/ember-cli-mirage';

export default function startMirage(container) {
  mirageInitializer.initialize(container);
}
```

It appears that `import` is failing for some reason. I haven't been able to find information about this online - have you seen similar issues? My setup has ember-cli version:0.2.3, node:0.12.7, npm:2.7.6

**Comment by samselikoff** [comment]
Sorry you're having trouble! What version of Mirage? The initializer code was [recently changes](https://github.com/samselikoff/ember-cli-mirage/blob/master/app/initializers/ember-cli-mirage.js) but that would only affect the beta 0.2 branch.

**Comment by sammilechman** [comment]
@samselikoff `0.1.13`

**Comment by sammilechman** [comment]
Update: I'm in the process of upgrading Ember to 2.x and it looks like Mirage is working fine on that. It may be a compatibility issue with the older Ember version.
