### ISSUE TITLE
Include second degree objects from the serializer

### ISSUE THREAD

**Issue by cibernox** [samselikoff/ember-cli-mirage#708]
The JSON-API spec, in the section about including related resources (http://jsonapi.org/format/#fetching-includes) allows to specify related resources of Nth degree using a dot-separated name.

Per example, when requesting a `Quiz` model, you can now include the related questions doing `/quizzes/1?include=questions`. If you also want to get the answers associated to those questions your can perform this query: `/quizzes/1?include=questions,questions.answer`. 

**This already works in mirage** when passing a `include` query param in the request, but no when using the `include` property in the serializer.

For consistency, ember-cli-mirage should make a serializer like this behave the same as if the `include` property was passed in the request.

```js
import BaseSerializer from './application';
export default BaseSerializer.extend({
  include: ["questions.answer"]
});
```

I could work on this if nobody is tacking it or any related work.

**Comment by samselikoff** [comment]
I agree

**Comment by nruth** [comment]
related to #676 which doesn't have any implementation changes but showed it sort-of does it already, if you list them all
