### ISSUE TITLE
Lint not running on `mirage` directory in v0.2.0-beta8

### ISSUE THREAD

**Issue by jimmay5469** [samselikoff/ember-cli-mirage#714]
## The problem
I am running v0.2.0-beta8 and noticed that JSHint and ember-cli-eslint do not run on the `mirage/` directory now that the `mirage/` directory is in the project root and not in the `app/` directory.

## To reproduce
You should be able to easily reproduce this by removing a necessary semicolon on a JS file within the `mirage/` directory. You will notice that this does not cause a JSHint error or ember-cli-eslint error (whichever you are using).

## My attempts to fix
Digging in a little further I noticed that there is a `lintTree` hook for addons. This hook is actually used to generate tests given an already determined lint tree that is passed into the hook. I believe this is the hook that JSHint and ember-cli-eshint use to generate the linting tests you see in your test output. According to [the documentation](http://ember-cli.com/api/classes/Addon.html#method_lintTree) hook only gets invoked for the `app`, `test`, and `addon` trees. So I believe this is where the problem lies, it is never called for the `mirage` tree and the `mirage` tree is not included in any of the other linted trees.

I notice the index.js in ember-cli-mirage merges the `mirage/` directory into the app tree here: [index.js#L54-L61](https://github.com/samselikoff/ember-cli-mirage/blob/master/index.js#L54-L61). Unfortunately this does not seem to be the same the same `app` tree used for linting. I also tried to add similar code to the `treeForTestingSupport` but that didn't work either.

Looking through the ember-cli addon hooks and trying to fix this I think I have run into a wall. I cannot find a hook which will allow me to merge the `mirage/` directory with one of the existing trees and I can also not find any hooks for me to invoke `lintTree` for an additional tree.

## Conclusion
Personally, I really like that the `mirage/` directory has been moved to the root and I have talked to others who feel the same. I believe this is probably actually an issue in ember-cli using a different app tree for linting but wanted to raise awareness and gather feedback here before opening an issue on ember-cli.

**Comment by samselikoff** [comment]
Thanks for opening this. I don't have much insight on how it works, it seems you're probably more knowledgeable about it at this point than I am.

Let me know if there's any help I can be, but it seems like this should be elevated to some folks more knowledgeable with Ember CLI's internals.

Thank you for helping out!

**Comment by jimmay5469** [comment]
I'll test it this afternoon @rwjblue, thanks for this!

**Comment by jimmay5469** [comment]
@rwjblue you're branch is working great for me, thanks for the work, excited to see it in the next beta!

**Comment by samselikoff** [comment]
https://github.com/samselikoff/ember-cli-mirage/commit/fb24028e4ba8e0ec125bcb21e2de5e10fff6d9db closes

**Comment by rwjblue** [comment]
Thanks @samselikoff, sorry for not getting to that for you first. :smiley_cat:

**Comment by samselikoff** [comment]
No need to apologize as long you keep working your ember cli/broccoli witchcraft 😝
