### ISSUE TITLE
Add shorthand for HEAD request

### ISSUE THREAD

**Issue by timjcook** [samselikoff/ember-cli-mirage#723]
In the same way that we have shorthands for `get`, `post` etc. it would be nice to add another shorthand for a `HEAD` request. I can't seem to define a route that will handle this request and thus it breaks my acceptance tests when that request is sent.

Tested on `ember-cli-mirage 0.1.13`.

**Comment by raido** [comment]
Same with Beta.

**Comment by samselikoff** [comment]
https://github.com/samselikoff/ember-cli-mirage/commit/222a4b0815161de038942954f78922388193d234 closes
