### ISSUE TITLE
Production tests fail due to config file missing

### ISSUE THREAD

**Issue by dlo83** [samselikoff/ember-cli-mirage#725]
Hi there,

I finally was able to upgrade from ember-pretenderify to ember-cli-mirage and everything works in development and test.  The only problem I'm running into right now is, I believe, due to the non-standard way we're running mirage.  We're manually starting the mirage server and loading the config because of the way our fixtures are currently set up.

I've put the following in an initializer:

```
import config       from '../config/environment';
import mirageConfig from '../mirage/config';
import Server       from 'ember-cli-mirage/server';

export function initialize() {
  var server;
  var serverStarted = false;

  if(config.environment === 'development') {
    // load mirage for question-navigation
    if (!serverStarted) {
      server = new Server({
        environment: 'test'
      });
      server.loadConfig(mirageConfig);
      serverStarted = true;
    }
  }
}

export default {
  name: 'mirage-loader',
  initialize: initialize
};
/* jshint ignore:end */

```

From there we have our own loadFixtures functionality that traverses the list of fixtures we run for each "activity" and populates the db with the appropriate data to bootstrap the app in dev.

The problem is, when running tests on a production build, I'm getting lots of the following errors:

```
not ok 871 PhantomJS 2.0 - TestLoader Failures: my-app/tests/integration/activity-intro-page-test: could not be loaded
    ---
        actual: >
            null
        message: >
            Died on test #1 	at moduleLoadFailure (http://localhost:7357/assets/test-support-2dee03c44b766c63e1755d667a15020c.js:2:52999)
            	at require (http://localhost:7357/assets/test-loader-aed547223102bd118e24c166a2b8572d.js:1:402)
            	at loadModules (http://localhost:7357/assets/test-loader-aed547223102bd118e24c166a2b8572d.js:1:318)
            	at load (http://localhost:7357/assets/test-loader-aed547223102bd118e24c166a2b8572d.js:1:535)
            	at http://localhost:7357/assets/test-support-2dee03c44b766c63e1755d667a15020c.js:2:53076: **Could not find module `my-app/mirage/config` imported from `my-app/initializers/mirage-loader`**
        Log: >
    ...
```
I'm guessing this is because config.js is excluded from production builds as it's only useful in dev and test scenarios.  Do you have any recommendations as to how I can circumvent this issue without duplicating the data in config.js?

**Comment by samselikoff** [comment]
How are you running the tests? You typically should not be running a test suite against a production build of Ember.

**Comment by dlo83** [comment]
Hey Sam,

When we create a PR, our CI tool (Jenkins, soon to be Travis) automatically runs a test against the production build, and upon passing, a merge is allowed in GitHub.  From there, a tag is cut for the master branch which then gets promoted from the dev environment -> QA -> Production.  Unfortunately I don't think we have much control in the CI and DevOps departments working in an enterprise environment, so I'm trying my best to work within the existing contraints/deployment process, which I realize may not be the ideal workflow.

**Comment by samselikoff** [comment]
Strange. Yah, I'm not sure about this. Note that there is both a build-time environment and a run-time environment. If you have a build-time environment of prod and a run-time of test, I think you will run into problems

**Comment by dlo83** [comment]
I'm going to close this one out-- we changed our deployment strategy to stop running tests against the production build.  Thanks for your input.
