### ISSUE TITLE
Setting up a route handler that returns no data

### ISSUE THREAD

**Issue by agrobbin** [samselikoff/ember-cli-mirage#727]
@samselikoff while working off of the latest beta version of `ember-cli-mirage` I've run into a scenario where I want to test what happens in my application when a request returns a JSON API document that has no data in it.

My route handler looks like this:

``` js
this.get('/segments/:id/assessment', (schema, request) => {
  var segment = schema.segment.find(request.params.id);

  return segment.assessment;
});
```

Sometimes a `segment` will have an `assessment`, other times it won't. When it doesn't, I get this error in my tests:

> Assertion Failed: normalizeResponse must return a valid JSON API document:
> - One or more of the following keys must be present: "data", "errors", "meta".

Is there something I need to do to get the serializer to return the right "no-data" JSON?

**Comment by agrobbin** [comment]
For reference, here is what a JSON API payload looks like when there is no data returned (for a single resource):

```json
{
  "data": null
}
```

**Comment by samselikoff** [comment]
No first-class way to do this at the moment. For now you could add a conditional:

```js
if (segment.assessment) {
  return segment.assessment;
} else {
  return { data: null };
}
```
