### ISSUE TITLE
Expose some base shorthand route handler methods

### ISSUE THREAD

**Issue by musaffa** [samselikoff/ember-cli-mirage#729]
Custom handlers don't have access to some useful methods like `_getAttrsForRequest` which are used in post and put's default handlers. Now, for example, I have a complex model with attributes and relationships and I want to write a custom post / patch handler. Default handlers have access to those methods which can take care of getting attributes from model's attributes and relationships. But In a custom handler we don't have those methods, so we have to roll our own and thus reinventing the wheel.

It would be nice if we have access to those methods. What if the `FunctionRouteHandler` extends the `BaseShorthandRouteHandler` or something better?

**Comment by samselikoff** [comment]
Not a bad idea, I'm definitely open to this. They would go on the [function route handler](https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/route-handlers/function.js). I added the `serialize` method, we could add some more.

**Comment by samselikoff** [comment]
#740 closes
