### ISSUE TITLE
use ember-try

### ISSUE THREAD

**Issue by samselikoff** [samselikoff/ember-cli-mirage#73]

**Comment by willrax** [comment]
Was the aim of this issue to test the library against more version of ember or integrate ember try in to the process of using mirage to test? Either way, I can take a crack at this if you like.

**Comment by samselikoff** [comment]
No just to test this addon against different versions of ember/ember-cli. I think it's possible to hook it up to CI?

**Comment by samselikoff** [comment]
959462cedf2b5892de984c6599de55313ef46914 closes
