### ISSUE TITLE
Hashtree is not defined

### ISSUE THREAD

**Issue by pankaj20dec** [samselikoff/ember-cli-mirage#730]
While running **ember install ember-cli-mirage**. It shows
Reference error: Hashtree is not defined
at C:\Windows\System32\node_modules\ember-cli-htmlbars\node_modules\broccoli-filter\node_modules\broccoli-kitchen-sink-helpers.

Pls help me.

**Comment by samselikoff** [comment]
What version of node, npm, ember?

**Comment by pankaj20dec** [comment]
It is fixed now. I was installing mirage in the wrong directory.
