### ISSUE TITLE
Is Mirage exposed to Localhost / Is it possible to use Mirage outside of Ember?

### ISSUE THREAD

**Issue by hhff** [samselikoff/ember-cli-mirage#732]
I don't fully understand how the Mirage <--> Ember communications work - however I'm just wondering if the Mirage API is actually exposed to the localhost?

TLDR: I need to prototype an API (not for an ember app though), and I'd love to use Mirage for it.  Is that possible?

**Comment by samselikoff** [comment]
It was designed to be, but it hasn't been a high enough priority for me yet. If you want to experiment with it, `npm install ember-cli-mirage` and use your build tool and basically copy [the initializer](https://github.com/samselikoff/ember-cli-mirage/blob/master/app/initializers/ember-cli-mirage.js#L4).

If you look at [this test](https://github.com/samselikoff/ember-cli-mirage/blob/master/tests/integration/server/model-creation-test.js#L9-L19), starting a Mirage server *should* be as simple as this. Note that some Ember APIs may have slipped in to the code under `/addon`, but fundamentally nothing relies on it. If you try this out just know that there will be rough edges :)

**Comment by hhff** [comment]
Thanks Sam!

My Q wasn't detailed enough I'm sorry!  What I want to do is just run `ember serve`, and be able to curl `localhost:4200/api/users`, and have mirage respond.

Is that possible or no?

**Comment by samselikoff** [comment]
Oh - atm, no, since Pretender just fakes out `window.XMLHttpRequest`. Some folks are working on getting Mirage to run in node though. Ping ebryn about this.

**Comment by hhff** [comment]
ok - cool!  thanks sam!
