### ISSUE TITLE
app/config/environment.js `directory` setting not utilized

### ISSUE THREAD

**Issue by gthmb** [samselikoff/ember-cli-mirage#738]
Using 0.2.0.beta-8, the app's [ember-cli-mirage directory setting](http://www.ember-cli-mirage.com/docs/v0.2.0-beta.8/configuration/#directory) is not being used when the containing app builds. Moving your app's mirage directory (even when reflecting the new location in the `config/environment.js`) will result in a Broccoli Funnel error during the build, as Mirage continues to look for it's default folder location. Example below.

Moved `myapp/mirage` folder to `myapp/app/mirage` and updated the config:

```
// myapp/config/environment.js
...
ENV['ember-cli-mirage'] = {
  directory: 'app/mirage'
};
...
```

Building results in:

```
Build failed.
The Broccoli Plugin: [Funnel] failed with:
Error: ENOENT: no such file or directory, lstat '/Users/XXX/Development/myapp/mirage'
    at Error (native)
…
```

I tested with a few other 0.2.0-beta.X releases with the same results.

Getting this setting working will help folks who want to write their own addons that contain models and their respective mirage counterparts. Currently, when authoring an addon, Mirage inserts itself into the dummy application, which is not available to any consuming apps or addons.

**Comment by gthmb** [comment]
I put together a PR here: https://github.com/samselikoff/ember-cli-mirage/pull/739/

**Comment by samselikoff** [comment]
https://github.com/samselikoff/ember-cli-mirage/pull/739 closes
