### ISSUE TITLE
server not defined when used in a helper used in an acceptance test (maybe ember-mocha related)

### ISSUE THREAD

**Issue by NullVoxPopuli** [samselikoff/ember-cli-mirage#741]
I'm using v2 beta 9 and ember 2.5

 

```
TypeError: Cannot read property 'create' of undefined
```

from this line:
```js
server.create('user');
```

which is in a test helper:
```js
import Ember from 'ember';
import 'aeonvera/tests/helpers/service-named';
import { server } from 'ember-cli-mirage';

export default Ember.Test.registerAsyncHelper('login', function(app, assert) {
  server.create('user');
```

which is called from this acceptance test:

```js
import Ember from 'ember';
import { it } from 'ember-mocha';
import startApp from 'aeonvera/tests/helpers/start-app';
import 'aeonvera/tests/helpers/login';
import startMirage from 'aeonvera/tests/helpers/setup-mirage-for-integration';

describe('Acceptance | login', function() {
  let application;

  beforeEach(() => {
    application = startApp();
    startMirage(this.container);
  });

  afterEach(() => {
    Ember.run(application, 'destroy');
    server.shutdown();
  });

  it('can login', function(done) {
    login();
    done();
  });
});
```

any ideas why `server` is undefined?

**Comment by samselikoff** [comment]
You don't import `server`, it's actually a global at the moment.

**Comment by NullVoxPopuli** [comment]
server is still undefined, actually, I've been trying to convert my qunit suite to mocha. Acceptance functions didn't carry over at all. So, I think I need to somehow tell ember that my test is an acceptance test

**Comment by samselikoff** [comment]
Yes, by default Mirage is instantiated in an Ember app initializer. You need to [manually start Mirage](http://www.ember-cli-mirage.com/docs/v0.2.0-beta.9/manually-starting-mirage/) if you're not in an acceptance test.

**Comment by NullVoxPopuli** [comment]
I believe I have in my beforeEach hook. So I think something else may be
the culprit.

**Comment by NullVoxPopuli** [comment]
for the record:

![image](https://cloud.githubusercontent.com/assets/199018/15357777/c81c3626-1cce-11e6-98ca-26298804771e.png)


my imports for this test:

```js
import Ember from 'ember';
import { describe, it, beforeEach, afterEach } from 'mocha';
import { expect } from 'chai';

import startApp from 'aeonvera/tests/helpers/start-app';
import startMirage from 'aeonvera/tests/helpers/setup-mirage-for-integration';

import 'aeonvera/tests/helpers/login';
```

**Comment by NullVoxPopuli** [comment]
and the setup-mirage file:

```js
import mirageInitializer from '../../initializers/ember-cli-mirage';

export default function startMirage(container) {
  mirageInitializer.initialize(container);
}
```

**Comment by NullVoxPopuli** [comment]
I'm also trying to talk with the mocha people on how to properly set up for an acceptance test.

**Comment by marcemira** [comment]
Same here, `server` is definitely not present on acceptance tests. Normal setup here, nothing out of the ordinary :confused:
