### ISSUE TITLE
JSON API setup doesn't return JSON API documents?

### ISSUE THREAD

**Issue by NullVoxPopuli** [samselikoff/ember-cli-mirage#746]
I have this query in my route:
```js
    let promise = this.get('store').findRecord('host', subdomain, {
      adapterOptions: {
        query: {
          subdomain: subdomain
        },
      },
    });
```

and this in my tests:

```js
    let org = server.create('organization', {
      name: 'Test Org',
      domain: 'testorg'
    });

    server.get('api/hosts/testorg', org);
```

I (hopefully) specified to use the JSON API serializer?
```js
// mirage/serializers/application.js
import { JSONAPISerializer  } from 'ember-cli-mirage';
export default JSONAPISerializer;
```

so, when I run my test, I get this error:

```
"Assertion Failed: normalizeResponse must return a valid JSON API document: * One or more of the following keys must be present: "data", "errors", "meta"."
```

implying that data, errors, or meta are not present.

This is when I'm inspecting the `reason` parameter of the `error` action in my route. I don't know how to actually see the payload. (the transition object doesn't appear to have anything useful either)

**Comment by samselikoff** [comment]
typically the response is `console.log`'d, can you see anything in the console after the request?

If you're in a test you'll need to enable logging, as it's disabled by default (for the sake of verbosity in CI logs, etc). Enable it like this:

```js
server.logging = true;
```

**Comment by gar** [comment]
@NullVoxPopuli I don't know if this is helpful at all, but we were seeing the same error while upgrading from mirage 0.1.x to 0.2.0-beta9. It seemed to be caused by having the old directory (`app/mirage`) at the same time as having the new directory (`mirage/`). 

Following the [upgrade guide](http://www.ember-cli-mirage.com/docs/v0.2.0-beta.9/upgrading/), including the step for moving files from the old directory to the new one, resolved the problem for us.

**Comment by NullVoxPopuli** [comment]
I don't have `app/mirage` anymore.

I didn't see any logs when I had `server.logging = true;`
![image](https://cloud.githubusercontent.com/assets/199018/15673078/5b880f88-2702-11e6-90cc-0012cfaa124a.png)

the test:

```js
    it('can view the name of the org', assert => {
      server.logging = true;
      visit('/testorg');
      andThen(() => {
        let h2s = find('h2');
        assert.ok(h2s.text().includes('Register for Test Org'));
      });
    });
```

**Comment by samselikoff** [comment]
That's strange... could you do me a favor, comment out the `server.create` line, and just do

```
server.get('api/hosts/testorg', { test: 'test' });
```

? If you're not seeing the response being logged Mirage isn't picking things up. If that doesn't work, try commenting out that line, and seeing if Mirage throws an unhandled route error handler.

Do you have the route defined in your `mirage/config.js` file?

**Comment by NullVoxPopuli** [comment]
without the server.create line, I see:

```
Successful request: GET /api/hosts/testorg?subdomain=testorg
```

I think I may have been just misreading the log.

I uncommented what I had originally, so:

![image](https://cloud.githubusercontent.com/assets/199018/15696577/bc604d52-277f-11e6-8bfc-2cbcaef09fd1.png)


I did not have the route defined in mirage/config.js.

I defined:
```js
  this.get('api/hosts/:eventalias', function(db, request) {
    return {};
  });
```

![image](https://cloud.githubusercontent.com/assets/199018/15696621/1a833750-2780-11e6-811f-b8f88a25f5dc.png)


it appears to have the same issue.

upgrading to 0.2.0 (from beta 9)

and I get the same error.

Right under the 'Successful Request' it shows an `Object`

is that supposed to be JSON API formatted? or...?

**Comment by samselikoff** [comment]
If you `return {}`, then that `{}` is your response. Since `{}` is not a json:api document, the Ember Data layer will be confused and throw errors.

You can always manually return a json:api document, i.e. `return { data: { type: 'posts', attributes: ...` but Mirage's serializer layer can help you. To use it, return a Mirage model from your route handler, and make sure your `serializers/application.js` is defined and exporting the JSONAPISerializer.

Make sure to read through the guides (especially [serializers](http://www.ember-cli-mirage.com/docs/v0.2.x/serializers/)) and let me know if you still have questions.

**Comment by NullVoxPopuli** [comment]
I have removed the `{}`, and I still get the same problem. I believe I have follow all the instructions. I would like to use the ember-cli-mirage way of doing JSON API documents in testing, as the document format is cumbersome to do by hand.

Again, for reference, here is my repo: https://github.com/NullVoxPopuli/aeonvera-ui

And here are all relevant files:

```
// /mirage/serializers/application.js
import { JSONAPISerializer  } from 'ember-cli-mirage';
export default JSONAPISerializer;

// /mirage/config.js
  this.get('api/hosts/:eventalias');

// /mirage/factories/organization.js
import Mirage, { faker } from 'ember-cli-mirage';
export default Mirage.Factory.extend({});

// my test
import Ember from 'ember';
import { module, test } from 'qunit';
import startApp from 'aeonvera/tests/helpers/start-app';
import 'aeonvera/tests/helpers/login';

let application;

// fake mocha
let it = test;
let describe = function(name, tests) {
  tests();
};

module('Acceptance | Registration | Organization | User is Logged In', {
  beforeEach() {
    application = startApp();

    let org = server.create('organization', {
      name: 'Test Org',
      domain: 'testorg'
    });

    server.get('api/hosts/testorg', org);
  },

  afterEach() {
    Ember.run(application, 'destroy');
    server.shutdown();
  },
});

describe('User is Logged in', function() {
  describe('beginning at the registration index page', function() {
    it('can view the registration page', (assert) => {
      visit('/testorg');
      andThen(() => assert.equal(currentURL(), '/testorg'));
    });

    it('can view the name of the org', assert => {
      server.logging = true;
      visit('/testorg');
      andThen(() => {
        let h2s = find('h2');
        assert.ok(h2s.text().includes('Register for Test Org'));
      });
    });
  });
});

```

and the error:

"Assertion Failed: normalizeResponse must return a valid JSON API document: * One or more of the following keys must be present: "data", "errors", "meta"."

If this does work as you say it does, then I have to be missing something stupid. I. Just. Can't. Seem. To. Find. it. :-(

**Comment by NullVoxPopuli** [comment]
If I comment out the `server.get` in my test, then I get this error: 
```
testem.js:775 Mirage: The route handler for /api/hosts/testorg?subdomain=testorg is trying to access the :eventalias model, but that model doesn't exist. Create it using 'ember g mirage-model :eventalias'.
```

this URL doesn't always return the same model. It can return any of two subclasses of :host

**Comment by samselikoff** [comment]
`server.get('api/hosts/testorg', org);` is wrong and won't pass through the serializer layer. Try reading though the [Defining routes](http://www.ember-cli-mirage.com/docs/v0.2.x/defining-routes/) section of the guide, make your route handler dynamically respond with a model, and then please let me know if you're still stuck.

**Comment by NullVoxPopuli** [comment]
@samselikoffg  I'm now doing this:

```js
// mirage/config.js
  this.get('api/hosts/:host', (schema, request) => {
    let hostId = request.params.host;

    if (hostId.includes('org')){
      return schema.db.organizations.find(hostId);
    }

    return schema.db.events.find(hostId);
  });

// in test's before each
    let org = server.create('organization', {
      id: 'testorg',
      name: 'Test Org',
      domain: 'testorg'
    });
```

(contrary to the docs, the schema doesn't have access to my factory data)

and I am _still_ getting the same output as before

```
"Assertion Failed: normalizeResponse must return a valid JSON API document:↵	* One or more of the following keys must be present: "data", "errors", "meta"."


Successful request: GET /api/hosts/testorg?subdomain=testorg
testem.js:775 Object {domain: "testorg", name: "Test Org", id: "testorg"}



```

**Comment by NullVoxPopuli** [comment]
that console output is outputting a non JSON API object. :-\

**Comment by samselikoff** [comment]
Looks like it's not going through the serializer layer, have you set up JSONAPISerializer in `mirage/serializers/application.js`?

**Comment by NullVoxPopuli** [comment]
Yeah, I think I pasted it in an earlier comment. Also, here is the actual
file:
https://github.com/NullVoxPopuli/aeonvera-ui/blob/master/mirage/serializers/application.js

**Comment by samselikoff** [comment]
Oh, I see the problem. You're writing

```
return schema.db.organizations.find(hostId);
```

so you're just returning the raw `db` record, which doesn't get serialized. To use the serialize you need to return a Model or Collection. This should be

```
return schema.organizations.find(hostId);
```

You'll probably get an error, then, because it looks like you don't have your models defined. Try `ember g mirage-model organization`.

**Comment by NullVoxPopuli** [comment]
hey after I ran `ember g mirage-model organization` my test passed!!!! thank you!!!!! :-)
