### ISSUE TITLE
Update index.js to align with 0.2.2 addon changes

### ISSUE THREAD

**Issue by trabus** [samselikoff/ember-cli-mirage#75]
As per [the v0.2.2 release notes](https://github.com/ember-cli/ember-cli/releases/tag/v0.2.2), the use of `this.Funnel` and `this.mergeTrees` are deprecated and we should move to requiring them directly instead of using `this`.

**Comment by acorncom** [comment]
This seems to be closed by #97

**Comment by samselikoff** [comment]
yep I just need to release. Shoudl be able to soon.

**Comment by samselikoff** [comment]
thx!
