### ISSUE TITLE
JSONAPISerializer Doc Needs to be updated

### ISSUE THREAD

**Issue by cottrellio** [samselikoff/ember-cli-mirage#750]
On page `http://www.ember-cli-mirage.com/docs/v0.2.0-beta.9/serializers/` there is an example of using the `JSONAPISerializer` for the application serializer that reads:
```
import JSONAPISerializer from 'ember-cli-mirage';

export default JSONAPISerializer;
```
and should be:
```
import { JSONAPISerializer } from 'ember-cli-mirage';

export default JSONAPISerializer;
```

This was causing me to get the following error (in case others are experiencing it):
```
Pretender intercepted GET http://localhost:4000/api/v1/features but encountered an error: Cannot read property 'embed' of undefined
```

**Comment by samselikoff** [comment]
Good catch, thanks for opening the issue!

If you have time, could you click the "Improve this page" link at the top of that doc, editing the file + proposing a change?

**Comment by cottrellio** [comment]
Oh cool, I hadn't seen that link. I just sumbitted a PR. Thanks again for your work on Mirage. It's fantastic.

**Comment by samselikoff** [comment]
https://github.com/samselikoff/ember-cli-mirage/pull/751 closes
