### ISSUE TITLE
Form Data

### ISSUE THREAD

**Issue by jbailey4** [samselikoff/ember-cli-mirage#753]
How should form data within the FakeRequest be handled? Does mirage currently parse form data in any way? If not, I feel like parsing form data and allowing easy access to it would be a good addition.

Currently form data in the FakeRequest looks like the following:

`requestBody: "foo=bar&baz=someValue"`

**Comment by samselikoff** [comment]
No convention here yet, you'd need to deserialize that string yourself using some JS (or maybe a helper function from jQuery). Would be a great addition - maybe we could update the [#normalizedRequestAttrs](https://github.com/samselikoff/ember-cli-mirage/blob/a595279657be150dff1e7a9cb50ee2041660865f/tests/integration/server/custom-function-handler-test.js#L46) helper method to return a JS object?

**Comment by jbailey4** [comment]
I'm currently doing the deserialization myself. I did post a similar issue on the pretender repo, thinking maybe Form Data should be supported there. I could look into supporting this in mirage though.

I agree this addition should just parse the form data key/values and provide POJO.

I see [this method](https://github.com/samselikoff/ember-cli-mirage/blob/a595279657be150dff1e7a9cb50ee2041660865f/addon/route-handlers/base.js#L41-L73), maybe that would be a good place to look for the use of Form Data and start the parsing.

**Comment by samselikoff** [comment]
Yep, that's exactly the spot. If you want to take a crack at it I'm happy to advise! I think a simple deserialization should suffice (POJO of key/value pairs).

**Comment by jbailey4** [comment]
Looks like [the method](https://github.com/samselikoff/ember-cli-mirage/blob/a595279657be150dff1e7a9cb50ee2041660865f/addon/route-handlers/base.js#L41) I linked to above is very specific to jsonapi documents, do you think a separate helper method should added to function handlers for normalizing form data?

**Comment by samselikoff** [comment]
Oh, you're right.

Add a new method [here]. Note that `this.request` will be set by the time the function is available in the handler. Let's name it `normalizedFormData`.

**Comment by jbailey4** [comment]
> Add a new method [here].

I didn't get the link, did you mean [here](https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/route-handlers/function.js#L37) in route-handlers/function.js? 😄

**Comment by samselikoff** [comment]
Hehe, yes exactly 😛

**Comment by samselikoff** [comment]
#796 closes
