### ISSUE TITLE
Routes are not loaded in integration test.

### ISSUE THREAD

**Issue by GCorbel** [samselikoff/ember-cli-mirage#760]
I have the same issue as this [question](http://stackoverflow.com/questions/36954576/issue-loading-records-via-ember-cli-mirage-in-unit-test#).

I have this error : 

> Mirage: Your Ember app tried to GET '/activities',
>          but there was no route defined to handle this request.
>          Define a route that matches this path in your
>          mirage/config.js file. Did you forget to add your namespace?

I have this integration test : 

```
/* jshint expr:true */
import {expect} from 'chai';
import {
  describeComponent,
  it
} from 'ember-mocha';
import hbs from 'htmlbars-inline-precompile';
import startMirage from '../../helpers/setup-mirage-for-integration';

describeComponent(
  'user-form-choose-course',
  'Integration: UserFormChooseCourseComponent',
  {
    integration: true,
    setup: function() {
      this.inject.service('store');
      startMirage(this.container);
    }
  },
  function () {
    it('WIP', function () {
      Tiny = {};
      server.create('activity', {name: 'Tenis'});

      const item = this.get('store').createRecord('subscription');

      this.set('item', item);

      this.render(hbs`{{user-form-choose-course item=item}}`);
      expect(this.$('#subscription0-course')).to.have.length(0);
    });
  }
);
```

And this config file : 

```
export default function() {
  this.urlPrefix = 'http://localhost:3000';

  this.get('/activities', 'activities');
  this.post('/activities');
  this.del('/activities/:id');
  this.patch('/activities/:id');
}
```

Is there a problem?

**Comment by samselikoff** [comment]
[This is the line](https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/server.js#L126) that loads the config, could you do me a favor, and 

1. Run the test in your browser
2. Open Chrome inspector
3. +O, start typing `mirage/server.js`, and the fuzzy finder should find this file
4. Click in the gutter on line 125, and inspect the `options` object to see if `baseConfig` is defined

**Comment by samselikoff** [comment]
Also, are you in an app or addon?

**Comment by GCorbel** [comment]
Hi,

`options.baseConfig` is defined. I'm working on an app. Any idea?

**Comment by GCorbel** [comment]
I can see, on [this line](https://github.com/tildeio/route-recognizer/blob/v0.1.11/lib/route-recognizer.js#L219), `this.nextline` is an empty array.

**Comment by samselikoff** [comment]
Any chance you can upload the app the github so I can take a look?

**Comment by GCorbel** [comment]
I can give you an temporary access to the repo but only in private. I send you an email.

**Comment by GCorbel** [comment]
The code I'm talking about is on the dev branch. Please, let me know if you need help. Thanks for you help.

**Comment by SeanGrind** [comment]
Have either of you been able to track this down?  I've run into a similar problem with my Integration test.

**Comment by GCorbel** [comment]
I still have the problem. @samselikoff did you had a chance to see what's wrong?

**Comment by GCorbel** [comment]
Just to know, I have this test : 

```
import {expect} from 'chai';
import {
  describeModel,
  it
} from 'ember-mocha';
import startMirage from '../../helpers/setup-mirage-for-integration';

window.Tiny = {};

describeModel(
  'subscription',
  'Subscription',
  {
    integration: true
  },
  function () {
    beforeEach(function () {
      startMirage();
    });

    it('gives the list of available courses', function () {
      this.store().findAll('course');
    });
  }
);
```

`server.schema` seems to be correct and all routes seems to be loaded.

**Comment by GCorbel** [comment]
I continued to search. In the route recognizer, I can see on [this line](https://github.com/tildeio/route-recognizer/blob/master/dist/route-recognizer.js#L530) it populates the `currentState` with all routes included in the mirage configuration file. [On this other line](https://github.com/tildeio/route-recognizer/blob/master/dist/route-recognizer.js#L678) it search for a route. When it works, `this.rootState` is equal to `currentState` where root are loaded and, when it doesn't work, it's different.

I don't know why and I don't understand all but I will continue later today.

**Comment by GCorbel** [comment]
I finally found. Not sure to understand all but I resolved my problem. In my config file, I had `this.urlPrefix = 'http://localhost:3000'` and in my config file I had `ENV.APP.API_HOST = 'http://localhost:3000';` so everything seems to be correct but pretender, [in this function](https://github.com/pretenderjs/pretender/blob/7e2d2dcef8fe6fe0dc00807a8da2ca337663a06d/pretender.js#L28-L34), build an anchor to find the host.The first time, when mirage is configuring itself, the url is equal to `http://locahost:3000/users` and is correct but, when it do the request, the url is `/users` so the host found is the current host (http://test.local.com:4200/ in my case). Because it does not found the same host, it does find the same route registry.

If I go a step further, the request is not performed on the same host between acceptance and unit test. [This line](https://github.com/emberjs/data/blob/v2.6.1/addon/-private/adapters/build-url-mixin.js#L90) does not provide the same value. It's undefined for unit test and I don't know why.

For the moment, I just removed the `urlPrefix` and `API_HOST` for test and it works. This is probably not the best solution. @samselikoff , you have an idea to fix it? I hope to be clear. It was very hard to debug.

**Comment by samselikoff** [comment]
@GCorbel thank you very much for digging! Sounds like this was really frustrating, sorry I haven't had more time lately to help out.

If your app is making a request to an origin other than the current host, you need to specify it explicitly in your `/mirage/config.js` namespace. When it wasn't working, did you see an error?

I think the solution here is to import your config and use `urlPrefix` and `API_HOST` to dynamically set Mirage's namespace.

**Comment by chrisortman** [comment]
Struggling with this too. Seems to be something like mirage gets run in the context of the test runner but not the ember app when run via testem and specifying the host gets them to the right spot.

Sorry I don't think that's a very good description, but I don't really understand it any better than that right now :/

Here's a repo with a couple of commits that I was figuring this out https://github.com/chrisortman/ember-cms-frontend/commit/745e28c3feafeee8b5f7f0faa7a554b0a364fd52

**Comment by Senthe** [comment]
I have the same issue. : ( Any idea how to resolve it? As for now I have to remove my integration tests if they use anything from the API.

**Comment by john-griffin** [comment]
I got my tests working via testem much like @chrisortman by ensuring urlPrefix/host is always set to something. Blank doesn't seem to work with testem.

**Comment by samselikoff** [comment]
A twiddle that reproduces the bug would be very helpful

**Comment by woosungchu** [comment]
I had the same issue and fixed it by adding this into configuration
```
    ENV.APP.API_HOST = 'http://localhost:7357';
    ENV.APP.API_NAMESPACE = 'api';
```

and the result is ...
```
  if (environment === 'test') {
    // Testem prefers this...
    ENV.locationType = 'none';
    ENV.APP.API_HOST = 'http://localhost:7357';
    ENV.APP.API_NAMESPACE = 'api';
    
    // keep test console output quieter
    ENV.APP.LOG_ACTIVE_GENERATION = false;
    ENV.APP.LOG_VIEW_LOOKUPS = false;

    //mirage
    ENV['ember-cli-mirage'] = {
      enabled: true
    };

    ENV.APP.rootElement = '#ember-testing';
  }
```

**Comment by hbrysiewicz** [comment]
This no longer appears to be an issue.
