### ISSUE TITLE
Disabled logging in production builds

### ISSUE THREAD

**Issue by offirgolan** [samselikoff/ember-cli-mirage#765]
Hi there,

I've been using this addon for quite some time now, but in the last couple of months I've been using it more and more in addon demo pages. When I build my app in production mode and publish it on gh-pages, I still get logging (see screenshot) which I believe should be disabled. 

![screen shot 2016-06-06 at 11 20 06 am](https://cloud.githubusercontent.com/assets/575938/15832793/aa47285e-2bd8-11e6-9827-b3ee28e75eef.png)

**Comment by samselikoff** [comment]
We should update [shouldLog](https://github.com/samselikoff/ember-cli-mirage/blob/333716fc66f1f983d643cf38c7b433a43fb68be9/addon/server.js#L155-L157) to check for ENV vars, but for now you should be able to import ENV in your `mirage/config.js`, and if env is production, run `this.logging = false`.

**Comment by offirgolan** [comment]
👍  great! Thanks for the workaround
