### ISSUE TITLE
Document factory afterCreate

### ISSUE THREAD

**Issue by samselikoff** [samselikoff/ember-cli-mirage#766]
Check out the tests: https://github.com/samselikoff/ember-cli-mirage/blob/master/tests/integration/factories/after-create-test.js

**Comment by koriroys** [comment]
@samselikoff does the ready label mean you've already done it, just haven't committed yet?

**Comment by samselikoff** [comment]
Ready label means this issue is ready for someone to pick up. As soon as someone does (by commenting here) or I do (by assigning to myself), I move it to the "In progress" label.

Trying a new workflow using https://waffle.io/samselikoff/ember-cli-mirage

**Comment by davewasmer** [comment]
Submitted a PR with a basic pass at this: #787
