### ISSUE TITLE
Docs highlight some JS objects as errors

### ISSUE THREAD

**Issue by alecho** [samselikoff/ember-cli-mirage#768]
setting the code fence type to text doesn't syntax highlight but it also doesn't mark it with error highlights. I'm wondering if this is something that should be fixed.

**Comment by alecho** [comment]
Forgot to add a screen grab of the problem: 
<img width="254" alt="screen shot 2016-06-08 at 6 50 35 pm" src="https://cloud.githubusercontent.com/assets/1035853/15913811/50f08ed4-2daa-11e6-8156-fe0278a3b269.png">

**Comment by alecho** [comment]
@samselikoff happy to take this one if your interested in fixing these.

**Comment by samselikoff** [comment]
@alecho that would be great. Yes these are super annoying

**Comment by acorncom** [comment]
@alecho Any additional info on where you are seeing these problems?  We could tag this with a "good for new contributors" flag if there's a bit more info ...

**Comment by alecho** [comment]
I believe when the docs are showing the expected body of the response. I think the highlighter was trying to determine the syntax type and was picking either Javascript or JSON and then highlighting errors based on that type. I just did a quick look though the docs and it looks like this is fixed now.

**Comment by acorncom** [comment]
Sounds good 👍
