### ISSUE TITLE
Quickstart guide

### ISSUE THREAD

**Issue by 0000marcell** [samselikoff/ember-cli-mirage#770]
I think there's an minor error in the quickstart guide instead of 'api/authors' in the mirage/config.js  it should be '/authors', since I'm here let me ask something, is there an project demonstrating all ember mirage functionality?

**Comment by samselikoff** [comment]
Thanks for opening this issue! Would you mind clicking the "Improve this page" link at the top of the docs page where you see the typo, and submitting a PR with the fix? I'd really appreciate it.

There's not a sample project at the moment, but that's a really good idea & I should make one.

**Comment by acorncom** [comment]
The quick start guide issue seems to be fixed at this point, I'll open a new issue re: a sample project
