### ISSUE TITLE
Add YUI docs to belongsTo

### ISSUE THREAD

**Issue by samselikoff** [samselikoff/ember-cli-mirage#774]
https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/orm/associations/belongs-to.js needs YUI docs

Check out [this PR from Liz](https://github.com/samselikoff/ember-cli-mirage/pull/682) as an example

**Comment by 0000marcell** [comment]
the PR mentioned don't have a definition for the model class so the methods changed don't show up when you generate the docs, is that right ? can i add the class definition so i can test it out ?

**Comment by lizzerdrix** [comment]
Trying to find an example of this in the Ember CLI docs, but I'm pretty sure they show up, just without a description/definition. I found at least one instance of this while looking through the Ember CLI API docs. If I can find it again, I'll post a link!

**Comment by 0000marcell** [comment]
k, im gonna test it out with the ember-cli-yuidoc, im using the standard yuidoc and i couldn't find methods without class definition on the generated docs when i tested it.
