### ISSUE TITLE
How to configure route definitions in mirage/config.js to handle query parameters?

### ISSUE THREAD

**Issue by fknoll** [samselikoff/ember-cli-mirage#778]
I find nothing in documentation **about how to configure route definitions in ```mirage/config.js``` to handle query parameters**?

It seems like Mirage supports the two ED methods ```findRecord(modelName, id, options)``` and ```store.findAll(modelName, options)```, though I am not sure about the ```options``` parameter?

It is however unclear for me, whether Mirage supports the two ED methods ```store.queryRecord(modelName, query)``` and ```store.query(modelName, query)```.

In my application ```store.queryRecord(modelName, query)``` seems to ignore the ```query``` parameter and effectively acts, as if I had used the method ```store.findAll()```. Additionally, using the ```store.queryRecord()``` method results in an error message - see #771.

Also ```store.query(modelName, query```) seems to ignore the ```query``` parameter, and effectively acts, as if I had used the method ```store.findAll()```.

**Comment by fknoll** [comment]
Well, well ... I discovered the solution myself!

In **```mirage/config.js```** i replaced relevant **shorthand** definitions like this one:
```js
this.get('/reg-summaries');
```
with **expanded** definitions like this one:
```js
this.get('/reg-summaries', (schema, request) => {
    return schema.regSummaries.where(request.queryParams);
});
```

I humbly propose the documentation to be improved in respect to route definitions supporting query parameters.

**Comment by indieNik** [comment]
I was able to customise my definitions in the same way as well. But is this the best way to do so?

**Comment by samselikoff** [comment]
Yep, this is how to drop down and use Pretender's `request` object to return data based on any info contained in the request, such as query params
