### ISSUE TITLE
Unable to update record per docs

### ISSUE THREAD

**Issue by sirvine** [samselikoff/ember-cli-mirage#782]
The 0.2.x docs provide the following example:

``` javascript
let post = blogPosts.find(1);
post.update('title', 'Hipster ipsum'); // the db was updated
post.update({
  title: 'Lorem ipsum',
  created_at: 'before it was cool'
});
```

I've got a route handler that attempts the following:

``` javascript
this.patch('http://localhost:3000/api/v1/contracts/:id', function({ contracts }, request) {
    let newAttributes = this.normalizedRequestAttrs();
    let { id } = request.params;
    let contract = contracts.find(id);
    // contract.attrs.title = newAttributes.title;
    contract.update(newAttributes);
    return contract;
  });
```

This fails and the title is not updated. However, if I uncomment the third-to-last line, it works. Presumably, update isn't applying the `newAttributes` hash to the `attrs` property of the model.

Probably related: calling the attribute directly, e.g., `contract.title` is null.

I upgraded this app from 0.1.x recently. Did I perhaps miss a change?

UPDATE: 

It looks like I missed something in the change from db to schema. This updates the attributes correctly, but seems like a strange way to handle this case:

``` javascript
  this.patch('http://localhost:3000/api/v1/contracts/:id', function(schema, request) {
    let attrs = this.normalizedRequestAttrs();
    let { id } = request.params;
    schema.db.contracts.update(id, attrs);
    return schema.contracts.find(id);
  });

```

I assume since the shorthand didn't work that something is incorrect upstream.

**Comment by remkoboschker** [comment]
I can confirm that the updated code works whereas the short hand does not.

**Comment by samselikoff** [comment]
It looks like you're just updating the attrs - can you tell me what the shorthand does in your case? Perhaps after the update, check `server.db.contracts`?

Also you don't ever set `contact.attrs`, you just do `contact.title = 'foo'` (attrs is a computed property of sorts).

**Comment by wecc** [comment]
I'm also unable to do `schema.collection.update()` and found that some of the methods available on an "ORM collection" are missing [here](https://github.com/samselikoff/ember-cli-mirage/blob/e7e041f/addon/orm/schema.js#L92-L102)

**Comment by hbrysiewicz** [comment]
This problem appears to be inactive
