### ISSUE TITLE
Fixture JSONAPI

### ISSUE THREAD

**Issue by danilovaz** [samselikoff/ember-cli-mirage#784]
Recently I searched the documentation, any response example of a fixture in JSONAPI but not found. 

Currently I spend my fixtures normal JSON without formatting JSONAPI. But my serializer and adapter are in JSONAPI. For example, I want to know how I can send a meta tag for page counter, for example:

``` "meta ": {
"count-pages": 13
}```

How I can do this with fixtures?

**Comment by samselikoff** [comment]
Fixtures are really for seeding DB data, so putting meta in there probably isn't a good idea.

You can use the `this.serialize` helper and add meta to your response from a route handler:

```js
this.get('/posts', function(schema, request) {
  let json = this.serialize(schema.posts.all());

  json.meta = {
    some: 'key
  };

  return json;
});
```

**Comment by acorncom** [comment]
@danilovaz Are you set here?  If so, let's close this issue ...

**Comment by danilovaz** [comment]
Hi guys! 

Sorry for the delay... busy days :disappointed: 

Issue resolved, I will close it.

Thank's so much :heart:
