### ISSUE TITLE
Clarify difference between db and schema in docs

### ISSUE THREAD

**Issue by maschwenk** [samselikoff/ember-cli-mirage#785]
I'm not clear on the main difference between

`server.db.submissions.update(1, { userId: 1 })`

and 

`server.schema.submissions.find(1).userId = 1`

when user/submission have a hasmany/belongs relationship. I see server.db only has raw POJOs, is it discouraged to create associations via setting the POJO attributes?

**Comment by samselikoff** [comment]
You can always manipulate the db data directly, but the ORM (`schema`) is meant to help with this.

For example, if you had a `submission` instance and a `user` instance, you could do

```js
let submission = schema.submissions.find(1);

submission.user = user;
```
