### ISSUE TITLE
Inconsistent overrides behavior

### ISSUE THREAD

**Issue by davewasmer** [samselikoff/ember-cli-mirage#788]
Currently, if I have a Post factory and I call:

```js
let post = server.create('post', {
  title(i) { return `Blog Post Number ${i}`; }
});
```

The function override works as expected (which is awesome!). The newly created `post` object will invoke the supplied `title()` attribute function to build it's title property.

However, if I forgot to define my Post factory, and do the above, I get a cryptic error:

```
TypeError: newModel.isNew is not a function at set
```

Coming from here: https://github.com/samselikoff/ember-cli-mirage/blob/9ada99e86f343eba6f7f4fdde28177da60db64e7/addon/orm/associations/belongs-to.js#L78

It appears that building objects via `server.create()` is possible for types which don't have a factory - it simply uses the supplied overrides object as the attributes directly:

```js
    let OriginalFactory = this.factoryFor(type);
    if (OriginalFactory) {
      let Factory = OriginalFactory.extend(overrides);
      let factory = new Factory();

      let sequence = this.factorySequences[camelizedType];
      return factory.build(sequence);
    } else {
      return overrides;    // <-- the overrides are returned directly, rather than passed through factory.build()
    }
```
https://github.com/samselikoff/ember-cli-mirage/blob/9ada99e/addon/server.js#L222-231

The problem here (I'm guessing) is that the `factory.build(sequence)` call is responsible for invoking the attribute functions and merging in their return values, but that doesn't happen when the factory isn't found (the else branch above).

Seems like one of three things should happen:

1. You shouldn't be able to call `server.create('type-with-no-factory')`. _(This is my preference since this seems to be an obvious mistake, but perhaps I'm missing some use case where this is handy)._
2. Supplying attribute functions in the overrides object should be disallowed. _(Please don't, this is an awesome feature!)_
3. The code needs to be refactored so that overrides for non-existent factory types get built the same way (perhaps "auto-generating" a factory for that type?).

**Comment by samselikoff** [comment]
So I don't think function overrides are actually part of the API. I'm curious, what's the benefit of putting them in the overrides, vs making an actual factory?

You are correct that the reason the overrides are used is because, no factory exists. I wanted `server.create('user')` to work even if you didn't define a factory, because sometimes you just want to pass in ids (think join models). In this case, `server.create` is not actually invoking a factory; it's just falling back to model creation (e.g. `schema.users.create(attrs)`).

Why not make a factory and put the `title` function there?

**Comment by davewasmer** [comment]
> because sometimes you just want to pass in ids (think join models)

Ah, and there's that use case I didn't think of :wink:

> Why not make a factory and put the title function there?

```js
// mirage/scenarios/default.js
let authors = server.createList('user', 5);
let posts = server.createList('post', 10, { author: faker.list.cycle(...authors) });
```

By allowing functions as overrides, I can customize the `post` factory to generate objects using the surrounding scope. I can now easily generate a `post` that is linked with the current state of the database. Of course, the above could be re-written as:

```js
// mirage/scenarios/default.js
let authors = server.createList('user', 5);
let posts = server.createList('post', 10);
posts.forEach((post) => {
  post.author = faker.random.arrayElement(authors);
  post.save();
});
```

But the first example (using function overrides) is clearer and more concise, and I don't think it introduces any confusion or additional cognitive load.

`afterCreate()` alleviates some of this, but limits the relationships you establish to only those that can be known _a priori_ (because we have to query the database, rather than being able to pull a direct reference in from the surrounding scope).

**Comment by davewasmer** [comment]
Jumping ahead a bit:

It sounds like my option (1) isn't viable (there's a valid use case for factory-less types). I personally think option (2) isn't viable (see my last comment for what I think is a valid use case). If you agree, it seems like option (3) - refactoring factory-less types to go through the same object build process that invokes functions - might be the only recourse.

I realize there's a good chance that (3) a non-trivial refactor for what is an edge use case, so as an interim solution, I'd propose a half step: 

Add some error messages around factory-less object construction that warn the user that (for now) function overrides for factory-less types aren't supported. Clearly this isn't a super common use case, and the workaround is trivial (make an empty factory for that type). That should be good enough for now, and the bigger refactor could sit on the backburner, perhaps to be rolled into some future change when it makes sense.

**Comment by samselikoff** [comment]
Sure, I'll think about this a bit more. (3) is really more, add support for functions at the overrides level. The fact that this works right now is kind of a coincidence.

I want to think if there's a better way to solve the problem. In your example above,

```js
let posts = server.createList('post', 10, { author: faker.list.cycle(...authors) });
```

Are all 10 posts getting the same author, or each a random one?

**Comment by davewasmer** [comment]
Random in this particular case. If it were the same author, I'd probably: `server.createList('post', 10, { author: someAuthor })`.

The general statement of the problem I think is: allowing factories to create objects using the current scope. Function closures seemed like a good option for that, given the current API.

**Comment by samselikoff** [comment]
For now I'm going to say that since hash overrides give us the ability to access the current scope, I'd rather not introduce a new API. I think the way I'd do this today is with something like

```js
let authors = server.createList('user', 5);
Array(10).forEach(() => {
  server.create('post', { author: faker.random.arrayElement(authors) });
});
```

or

```js
let authors = server.createList('user', 5);
authors.forEach(author => {
  server.createList('post', 2, { author });
});
```


Going to close this for now, but happy to continue the discussion. Thanks for opening this!
