### ISSUE TITLE
Collection name not respecting ember-inflector rules

### ISSUE THREAD

**Issue by escobera** [samselikoff/ember-cli-mirage#793]
Hello there,

I've configured the following inflector rule on my ember app (doing so by following the ember guides):

```javascript
import Inflector from 'ember-inflector';

const inflector = Inflector.inflector;

inflector.irregular('tipo-documento', 'tipos-documento');

// Meet Ember Inspector's expectation of an export
export default {};
```

on my `config.js` I have:
```javascript
this.get('/sigoc/api/v1/tipos-documento', (schema, request) => {
  return schema.tiposDocumento.all();
});
```

which is erroring out with the following message:
`vendor.js:127893 Mirage: Your handler for the url http://localhost:8888/sigoc/api/v1/tipos-documento threw an error: Cannot read property 'all' of undefined` .

This is happening because inside `schema` there is a `tipoDocumentos` collection, which is the wrong inflection, as if mirage was completely ignoring my ember configuration.

Is this the intended behaviour? If so, how do I pass my inflection rules to mirage?

**Comment by samselikoff** [comment]
I'm too busy atm to dive into this, but I know this has caused others issues. Could you try searching the issues for inflector and see if one of the solutions there helps?

**Comment by escobera** [comment]
I've tried both solutions. 

One was to move the inflection rules to `app.js`. Wich I did, to no avail.
The other mentioned an initializer, which I can't seem to find (maybe is from the 0.1.x era).

If you, or anyone else that knows, could point me, or help me find, the place where the inflector is used to get the pluralized names and create the collections I could try and find the problem.

**Comment by samselikoff** [comment]
what version of Ember Data are you on?

**Comment by samselikoff** [comment]
ping @raytiley

**Comment by raytiley** [comment]
I wasn't having an issue w/ mirage itself, honestly I haven't gotten that far yet. I will that switching to ember data >= 2.3 fixed the issues I was seeing. As far as I can tell this is because previous to 2.3 Ember data was not an addon and was instead imported as a bower package with it's own version of `ember-inflector` included. Importing the addon version of ember-inflector which mirage does screwed things up.

So I would make sure your on ember data >= 2.3

**Comment by escobera** [comment]
```
//package.json:
"ember-data": "^2.6.0",
```

```
$ npm ls ember-data
sigoc-client@0.0.0 /home/t318791/projects/sigoc-client
└── ember-data@2.6.1 
```

No mention of ember-data on anythig bower related

**Comment by samselikoff** [comment]
I'm still not sure of the problem, this is weird npm stuff. The inflector is [here](https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/utils/inflector.js), maybe you can dig in and figure out what's being imported there?

**Comment by escobera** [comment]
@samselikoff I found the problem.

Everytime `pluralize` is used its first parameter is `camelized` first, like this: https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/orm/schema.js#L76

So my model `tipo-documento` has a rule to be pluralized as `tipos-documento` but no rule is definded for `tipoDocumento`. That way it does the default s-sufix to `tipoDocumentos`

I guess this is the way ember-data does it, but I cannot find any indication in the docs that this is the standard for multi-word models.

**Comment by escobera** [comment]
@samselikoff

This bug is related to this, ember-inflector is not pluralizing camelCased words properly, so we probably shouldn't camelize before pluralize: https://github.com/stefanpenner/ember-inflector/issues/95

**Comment by samselikoff** [comment]
@escobera sounds good to me. Any chance you'd have time to PR this? Shouldn't be too much of a change, and maybe you can add a failing regression test with your failing example?

**Comment by escobera** [comment]
@samselikoff I"m working on it. Although the it very hard to test those cases (70+ uses of ```pluralize(camelize('string'))```), because most of them are used to find only find hash keys. 

Maybe I should refactor all occurences into a utility method somewhere. Don't really know where tough, any tips?

**Comment by samselikoff** [comment]
Probably in `/utils`, maybe some helper functions like

- `toDbCollectionName(str)`
- `toSchemaCollectionName(str)`
- `toModeName(str)`

If you have time feel free to take a shot!

**Comment by escobera** [comment]
Ok, I'm pretty much done. I'll just test it on my project tomorrow to see if I covered all bases. PR incoming.
