### ISSUE TITLE
POST/PUT with embedded records

### ISSUE THREAD

**Issue by Baukereg** [samselikoff/ember-cli-mirage#797]
Say I have a **relation** and **person** model, with relation having an one-way belongsTo connection to person:

```
// models/relation.js
export default DS.Model.extend({
  person: DS.belongsTo('person')
});

// models/person.js
export default DS.Model.extend({ ... });
```

This connection is defined in the mirage model as well:

```
// mirage/models/relation.js
export default Model.extend({
  person: belongsTo('person')
});
```

I used EmbeddedRecordsMixin on the relation serializer. So person is always expected to be embedded in any payload of a GET request, and it will be send with any POST or PUT request as well. Since EmbeddedRecordsMixin doesn't work with JSON API, I use good old REST instead.

GET works fine, but whenever I do a POST or PUT, I get this error:

```
Mirage: Your handler for the url /api/relations threw an error: newModel.isNew is not a function
```

I figured out this has to do with mirage not being able to work with embedded data. So I wrote these custom POST and PUT hooks in config.js:

```
this.post('/relations', (schema, request) => {
    let relation = JSON.parse(request.requestBody).relation;
    relation.id = 'relation_' + new Date().getTime();
    relation.person.id = 'person_' + new Date().getTime();
    schema.persons.create(relation.person);
    relation.personId = relation.person.id;
    delete relation.person;
    schema.relations.create(relation);
    return schema.relations.find(relation.id);
});

this.put('/relations/:id', (schema, request) => {
    let relation = JSON.parse(request.requestBody).relation;
    console.log(relation);
    schema.persons.find(relation.person.id).update(relation.person);
    delete relation.person;
    schema.relations.find(request.params.id).update(relation);
    return schema.relations.find(request.params.id);
});
```

I use ```delete relation.person``` before any attempt to save the relation record  to fix the error.  Still, mirage not being able to handle embedded records seems like a missing feature.

**Comment by samselikoff** [comment]
Yeah - this is tough, because some people's APIs handle persisting even larger graphs of data. I'm not sure there's a standard way to handle this :/

Closing for now, but happy to continue discussing if you have further thoughts.
