### ISSUE TITLE
Allow per-route and fallback passthrough routing

### ISSUE THREAD

**Issue by justin-hackin** [samselikoff/ember-cli-mirage#80]
Currently I need to fetch certain SVG files hosted in public/ based upon some of my model data.  This system seems to make that impossible because it hijacks all my http requests even if they do not start with my chosen namespace.  So, I tried to move that ajax call into a mirage route but the same problem happens there.  It would be nice if all http requests that were not in the mirage namespace would behave normally.  After triple-checking your docs, I noticed the part about this.pretender.  According to the docs there, there is a this.passthrough function on pretender so it would seem I should be able to define something like 

```
this.get('/floorPlans/:id', this.pretender.passthrough)
```

I tried this with and without a dummy floorPlans fixture and neither way worked.  Is there a way to set up passthrough through mirage ?  If not, this becomes pretty useless to me :( because it is much better than other solutions I've tried for fixtures.  If so, I think it ought to be put in the config.js examples to save anyone else the trouble I went through .

**Comment by samselikoff** [comment]
Thanks so much for digging, and I really appreciate you taking the time to post the issue. This is definitely something we should support.

For now, see if this works:

```js
this.pretender.get('/photos/:id', this.pretender.passthrough);
```

**Comment by justin-hackin** [comment]
Sweet, that works, although it didn't work with the namespace so I had to add it into the route. Thanks so much for responding quickly, this was a real bottleneck for me :+1:

**Comment by rtablada** [comment]
@samselikoff along these lines is there a way to setup passthrough for non-configured routes rather than the console error message that it currently sends?

The use case is that we use mirage for test mocks and designing APIs but as the development API is solidified we use the dev environment where possible.

**Comment by samselikoff** [comment]
@rtablada this is a great idea and is a good feature. I believe Pretender's API is per-route - I'll check with trek.

**Comment by rtablada** [comment]
@samselikoff Yeah, I was wondering if that was more of a Pretender issue/proposal, but saw this may be related. I'd love to jump in a hangout or skype some time to talk about how we're using mocks in our product flow. Looking for more places to document and help out where I can.

**Comment by samselikoff** [comment]
that'd be great, I'm always looking to see how people are using mirage. It really started out as a small side project but it seems people are finding it valuable!

sam.selikoff@gmail.com for a hangout

**Comment by samselikoff** [comment]
I wonder if 

```js
this.pretender.get('/:catchall', this.pretender.passthrough);
```

would work?

**Comment by rtablada** [comment]
Have to do:

```
this.get(':catchall', this.pretender.passthrough);
this.post(':catchall', this.pretender.passthrough);
this.put(':catchall', this.pretender.passthrough);
this.delete(':catchall', this.pretender.passthrough);
```

**Comment by samselikoff** [comment]
gotcha. I can definitely add a simpler API to enable this, but it's good to know it's possible with Pretender

**Comment by rtablada** [comment]
I'm trying to figure out if nested resources will still get caught with that as well...

I'm actually creating a proposal for an `all` route registerer for Pretender right now.

**Comment by blimmer** [comment]
Since you can now have a catch-all passthrough (jQuery 2+), I think we can close this. Please reopen if not.
