### ISSUE TITLE
What if i work with underscore notation?

### ISSUE THREAD

**Issue by Sweet-Bob** [samselikoff/ember-cli-mirage#800]
PATCH requests working incorrectly

For example:

1. Change model & save
{first_name: 'Bob'}
changed to:
{first_name: 'Sam'}

2. Shorthands will process our model
    this.patch('/user/:id', ({ users }, request) => {
        let attrs = this.normalizedRequestAttrs(); 
        return users.find(id).update(attrs);
    });

3. Attrs will contain wrong properties
{ firstName: 'Sam', fist_name: 'Bob' }

4. Response will be same as request
{ first_name: 'Bob' }

Please look at: https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/route-handlers/base.js#L53

In normalizedRequestAttrs method, always uses camelize form, how working with underscore properties?

**Comment by samselikoff** [comment]
Mirage's storage format is `camelCase`, so even if your API uses snake_case, when you're working with Mirage you'll be using camelCase.

If you're using a Serialize with an appropriate `normalize` function, this shouldn't be a problem. You should be able to use the shorthand

```js
this.patch('/user/:id');
```

and the attrs will be converted to camelCase. Then, when the response is ready to be sent back to your Ember app, the Serializer will convert attrs back to snake case.

What Serializer are you using?

**Comment by Sweet-Bob** [comment]
I'm sorry, i incorrectly set up the user model

**Comment by samselikoff** [comment]
Glad you figured it out - let me know if you have any more questions!

**Comment by dgaus** [comment]
Hi, I just spent a good while trying to figure out why some of my attributes in factories were dissapearing. We're using the RestSerializer and it turns out it was turning attribute names with underscores into camelCase. Is this necessary or part of the rest spec? it was unexpected for me and I think it should be documented at least. 

In the end this makes it work with our apps.
```
import { RestSerializer } from 'ember-cli-mirage';

export default RestSerializer.extend({
  keyForAttribute(attr) {
    return attr;
  }
});
```

Cheers

**Comment by samselikoff** [comment]
Good question. We went with camelCase as a default, because we wanted Mirage's data to be in camelCase, since it's the JS convention. That is, your factory methods, and all the other pieces of your Mirage server should be in camelCase, because even though it might be emulating an API with underscore, when you're working in JS we want you to follow JS conventions.

Were your factory attrs in underscore? Ultimately the underscore vs camelCase should only matter at the serializer -> HTTP response level. The rest of the system should be in camelCase, because it's all JS.

**Comment by dgaus** [comment]
We have attributes with underscore in our models (i.e. `node_data: DS.attr()`) so naturally I was using the same for that model's factory. However those get camelCased, so when I did `store.find(model, id)` the result had attributes like `title` correctly set, but others like `node_data` were `undefined`. 
I don't see why `keyForAttribute` couldn't just leave the attribute name as it is. If you write your models using camelCase then you write your factories the same way, and if you use underscores that would also be supported.

**Comment by Sweet-Bob** [comment]
@davewasmer perhaps you will be confused when you learn that the Ember JS Model requires use camelCase notation. That link describes the requirements for  [https://guides.emberjs.com/v2.8.0/models/customizing-serializers/#toc_attribute-names](Model Attribute Names), i was surprised :) such a significant requirement in end of model guide ¯\_(ツ)_/¯

**Comment by davewasmer** [comment]
@Sweet-Bob I assume you meant to tag @dgaus? :wink:

**Comment by Sweet-Bob** [comment]
@davewasmer yes, I have no idea how it happened, sorry :)

**Comment by dgaus** [comment]
Thanks for the link, I see it's recommended to use camelCase, we didn't know that when we started the project. However the Ember Rest Serializer does not enforce this (https://github.com/emberjs/data/blob/v2.7.0/addon/serializers/json.js#L1433) and our project works just fine with underscores, so I wonder what is the need for coercing to camelCase in the mirage serializer. It seems the behaviour should match Ember's

**Comment by allthesignals** [comment]
Hmm if I'm following this thread correctly, it seems that it's not possible to change how Mirage handles serialization in terms of notation. It would be useful to have this option, as Active Model Serializers does. When switching between a Mirage development environment to a live or staging Rails AMS environment, you have to build in conditional logic that switches between this kind of serialization. This can get a little hairy when you have many serializers. 

For example, AMS has a keytransform property in its configuration that lets you change how this is done:
https://github.com/rails-api/active_model_serializers/blob/master/docs/integrations/ember-and-json-api.md#server-side-changes

My expectation is that the same should be possible in Mirage as well - or no? Thank you!

**Comment by samselikoff** [comment]
@allthesignals have you looked at the various `keyFor*` hooks in the [serializer docs](http://www.ember-cli-mirage.com/docs/v0.3.x/serializers/)?
