### ISSUE TITLE
OPTIONS requests mocking

### ISSUE THREAD

**Issue by riklaunim** [samselikoff/ember-cli-mirage#804]
Is there a way to mock OPTIONS requests? I use those to get model metadata used for form generation (field choices).

**Comment by samselikoff** [comment]
Hi, I'm actually not sure off the top of my head. Assuming Pretender supports it, it should be relatively straightforward to add.

- Add `'options'` to [this line](https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/server.js#L297)
- Add a very simple test to [this module](https://github.com/samselikoff/ember-cli-mirage/blob/master/tests/integration/http-verbs-test.js)

Think you'd be up for giving this a shot? I'd be happy to answer any questions!

**Comment by riklaunim** [comment]
Yes, I can check that out ;)

**Comment by riklaunim** [comment]
I've added options:
* https://github.com/riklaunim/ember-cli-mirage/commit/14523a7d52163e9f6dd44acb4fd989f766e40bd6
* https://github.com/riklaunim/ember-cli-mirage/commit/e745afca41d07586c9c4b77462b4f303d9bdfd1d

And I get:
    TypeError: this.pretender[verb] is not a function

When trying to use it. Pretender has it: https://github.com/pretenderjs/pretender/blob/7e2d2dcef8fe6fe0dc00807a8da2ca337663a06d
/pretender.js#L53

So it's bit unexpected.

**Comment by samselikoff** [comment]
If you open a PR with your changes we can discuss the code more easily there

**Comment by riklaunim** [comment]
ok :)

**Comment by acorncom** [comment]
@riklaunim Any additional info here?

**Comment by riklaunim** [comment]
New pretender needed.

**Comment by acorncom** [comment]
@riklaunim Newer than the 1.2 merged in in this PR? https://github.com/samselikoff/ember-cli-mirage/pull/881

**Comment by riklaunim** [comment]
Hm.. it needs 1.3 that was released today :) Will update this PR today too.

**Comment by acorncom** [comment]
We're tidying up issues, so am going to close this issue for now.  If it's still an issue, happy to reopen

**Comment by atremblay-seniorlink** [comment]
Any updates on this issue? I'm getting ERR_CONNECTION_REFUSED responses during my Ember Data CORS preflight check. It would be great to have Mirage support the options method (unless it already does and I'm missing something).

**Comment by samselikoff** [comment]
This would be nice to have, if someone has some time to spare I'd love to merge it into Mirage.

For now, if you're using a version of Pretender that supports OPTIONS you should be able to drop down to `this.pretender` in `mirage/config` and write a route handler there.

Closing for now because I'm trying to keep issues actionable. I'll add this to the Roadmap project.

**Comment by williamweckl** [comment]
I'm with the same issue, how can we do it using `this.pretender`?
