### ISSUE TITLE
Update to broccoli-funnel 1.0.2 to avoid minimatch vulnerability

### ISSUE THREAD

**Issue by jtrees** [samselikoff/ember-cli-mirage#805]
See here:

https://nodesecurity.io/advisories/118

**Comment by samselikoff** [comment]
Thank you for opening this! Any chance you'd have time to throw this in a PR?

**Comment by jtrees** [comment]
[et voilà](https://github.com/samselikoff/ember-cli-mirage/pull/810)

**Comment by samselikoff** [comment]
0ef17266ef490d69bbdac2a80252d1a05917d1cb closes

Thanks ! :heart:
