### ISSUE TITLE
Polymorphism

### ISSUE THREAD

**Issue by kagemusha** [samselikoff/ember-cli-mirage#808]
We are trying to model our polymorphic object structure in Mirage and wondering how best to do this.  Our object structure looks like:

```
Variation
    content: DS.belongsTo('content',{polymorphic:true,async:true}),

Content (a superclass)
    (all relations in the subclasses)

StaticImage extends Content
    variation: DS.belongsTo('variation'),

CountdownTime extends Content
    variation: DS.belongsTo('variation'),

(and some other subclasses of Content)

Asset
    content: DS.belongsTo('content',{polymorphic:true,async:true}),
```

We looked at the previously opened issues on polymorphism whic seem unresolved, but apparently there are workarounds?

**Comment by samselikoff** [comment]
Sure, hopefully I can help! Could you write down an example of a simple HTTP response that involves these?

**Comment by kagemusha** [comment]
This is greatly simplified but something as below.  And we are using the ActiveModelSerializer.

The assets call returns:

assets: [
               {id: 10, pic: {type: "static_image", id: 1}, ....}
               ...
             ]

Followed by: 

    {static_images: [
        { id: 1, asset_id: 10, ...}
        ....
      ]}

In the store, we end up with static_image models no content models.  Is that enough detail on the HTTP responses?

**Comment by samselikoff** [comment]
I have limited time to help right now, but I think for this I would try to just keep the modeling simple:

```js
// mirage/models/asset.js
export default Model.extend({
});

// mirage/models/static-image.js
export default Model.extend({
  asset: belongsTo()
});
```

Now `static-image` has a foreign key pointing to an asset. Create the data like this:

```js
// mirage/scenarios/default.js
server.create('asset');
server.create('static-image', { asset });
```

Now the static image should serialize with the asset foreign key. To get the asset payload correct, let's futz with the asset serializer:

```js
// mirage/serializers/asset.js
export default ApplicationSerializer.extend({
 
  serialize(asset, request) {
    let json = Serializer.prototype.serialize.apply(this, arguments);

    json.assets.forEach(asset => {
      let relatedContent = this.registry.schema.staticImages.where({ assetId: asset.id })[0];

      asset.pic = {
        type: relatedContent.modelName,
        id: relatedContent.id
      };
    });
  }
  
});
```

Now of course we're only searching `staticImages` here, so as you add more types you'll need to add some more code here to "find" the first model that has the matching `assetId`.

I think this is the cleanest way to model this currently. You can also have a `Content` base class that has the `asset: belongsTo()` piece, so you don't have to repeat that for all the other models.

Let me know if this gets you moving a bit!

**Comment by kagemusha** [comment]
sorry for the belated response, but first @samselikoff thanks for the suggestions.  it didn't quite work for us, but we've been able to do some ad-hoc stuff for our case.  will try to share some insights when get the chance to distill what we're doing
