### ISSUE TITLE
Server is undefined while in test environment

### ISSUE THREAD

**Issue by alvincrespo** [samselikoff/ember-cli-mirage#81]
**First and foremost, thanks for writing up this addon! It is such a great addition to the community.**

**Problem**
When running tests at [http://localhost:4200/tests](http://localhost:4200/tests) I'm getting `ReferenceError: server is not defined`. Not sure exactly how this might be happening since I've enabled ember-cli-mirage for testing mode only.

_Note_: This error does not occur when running `ember test`

![](https://s3.amazonaws.com/f.cl.ly/items/0F3c35031N1J2Y3s2x36/Screen%20Shot%202015-04-06%20at%202.53.57%20PM.png)

**config/environment.js**

```
module.exports = function(environment) {
  var ENV = {
    modulePrefix: 'cio',
    environment: environment,
    baseURL: '/',
    locationType: 'auto',
    EmberENV: {
      FEATURES: {}
    },

    APP: {}
  };

  ENV.APP.FORCE_REST_ADAPTER = false
  ENV.APP.PROFILE_RENDERS = false
  // Disable ember-cli-mirage by default, we want to use our local api for development
  ENV['ember-cli-mirage'] = {
    enabled: false
  };

  if (environment === 'development') {}

  if (environment === 'production') {}

  if (environment === 'test') {
    ENV['ember-cli-mirage'] = {
      enabled: true
    };

    // Root Element
    ENV.APP.rootElement = '#ember-testing';

    // Testem prefers this...
    ENV.baseURL = '/';
    ENV.locationType = 'none';

    // keep test console output quieter
    ENV.APP.LOG_ACTIVE_GENERATION = false;
    ENV.APP.LOG_VIEW_LOOKUPS = false;

    ENV.APP.rootElement = '#ember-testing';
  }

  return ENV;
};
```

**Comment by samselikoff** [comment]
Thanks for the kind words!

I suspect it's because when you run `ember serve`, you're building your app in `development` environment, but then when you visit `/tests` you're instantiating your app in `test` environment. For this reason, @rwjblue suggests never using `/tests` via `ember server`, but instead running `ember test --server` and +clicking the URL to pull it up in the browser.

Though, I'd still like to support `/tests` (at least for now), since so many people still use it. Question, how are you proxying to your server during development (i.e. during `ember serve`)? If you're using `--proxy` option or have proxies present in `/server/proxies`, Mirage should disable itself (so you could remove the `enabled: false` line from your config).

**Comment by samselikoff** [comment]
I do see the logic in `index.js` is wrong, I need to include Mirage during `development` build even if `enabled: false` is specified, precisely for this reason.

To get around this for now, remove the `enabled: false` option from your default config, and either use `ember test --server`, or add a blank file under `/server/proxies` or pass the `--proxy` option. (You can remove the `enabled: true` line as well, it's enabled by default).

**Comment by samselikoff** [comment]
You can use master now (`"ember-cli-mirage": "samselikoff/ember-cli-mirage"`) to get the fix.

Thanks for bringing this up Alvin!

**Comment by ballPointPenguin** [comment]
Does this imply that running tests in development mode at /tests should work?
I have proxies enabled and ember-cli-mirage explicitly enabled in development, but server remains undefined.

**Comment by samselikoff** [comment]
yes it should work, you have `ENV['ember-cli-mirage'].enabled = true`?

**Comment by ballPointPenguin** [comment]
```
if (environment === 'development') {
  ...
  ENV['ember-cli-mirage''] = {
    enabled: true
  }
}
```

**Comment by ballPointPenguin** [comment]
I wonder if there is conflict with the http-proxy I have configured in server/index.js and server/proxies already.

**Comment by samselikoff** [comment]
no that should work. let me check

**Comment by samselikoff** [comment]
ill have to investigate a bit later. but it should work

**Comment by samselikoff** [comment]
@ballPointPenguin I can't reproduce...with proxies in `/proxies`, I can still use `server.create` in my acceptance tests.

Can you post your `/mirage/config.js` and `/config/environment.js` files?

**Comment by ballPointPenguin** [comment]
```
// app/mirage/config.js

export default function() {

  this.namespace = '/api/v1';

  this.get('/companies/current', function(db) {
    var currentCompany = db.current_companies[0];

    return {
      company: currentCompany
    };
  });

  this.get('/emails', function(db, request) {
    var emails = db.emails || [];
    var emailsPage = collection_page(emails, request);
    var meta = pagination_meta(emails, request);

    return {
      emails: emailsPage,
      meta: meta
    };
  });

  this.get('/feeds', function(db, request) {
    var feeds = db.feeds || [];
    var feedsPage = collection_page(feeds, request);
    var meta = pagination_meta(feeds, request);

    return {
      feeds: feedsPage,
      meta: meta
    };
  });

  this.get('/users', function(db, request) {
    var users = db.users || [];
    var usersPage = collection_page(users, request);
    var meta = pagination_meta(users, request);

    return {
      users: usersPage,
      meta: meta
    };
  });

  this.get('/users/current', function(db) {
    var currentUser = db.current_users[0];

    return {
      feeds: [],
      team_members: [],
      users: currentUser
    };
  });

  this.get('/users/quick_search', function(db, request) {
    var users, name;
    var query = (request.queryParams.q || '').toLowerCase();

    if (query) {
      users = db.quick_search_users.filter(function(user) {
        name = (user.first_name + ' ' + user.last_name).toLowerCase();
        return name.match(query) ? true : false;
      });
    } else {
      users = [];
    }

    return {
      users: users,
      meta: {
        total_entries: users.length
      }
    };
  });

  // these GET requests simply return an array of fixtures:
  this.get('/announcements', 'announcements');
  this.get('/base_txt_messages', 'base_txt_messages');
  this.get('/behavior_types', 'behavior_types');
  this.get('/companies', 'companies');
  this.get('/notifications', 'notifications');
  this.get('/successes', 'successes');
  this.get('/teams', 'teams');
  this.get('/user_path_types', 'user_path_types');

  function pagination_meta(collection, request) {
    var perPage = parseInt(request.queryParams.per_page);
    var total = collection.length;
    var pages = Math.floor(total / perPage + 1);

    return {
      total_pages: pages,
      total_entries: total
    };
  }

  function collection_page(collection, request) {
    var perPage = parseInt(request.queryParams.per_page) || 15;
    var page = parseInt(request.queryParams.page) || 1;
    var startIndex = perPage * (page - 1);
    var endIndex = perPage * page;

    return collection.slice(startIndex, endIndex);
  }
}
```

**Comment by ballPointPenguin** [comment]
```
// config/environment.js

/* jshint node: true */

module.exports = function(environment) {
  var ENV = {
    modulePrefix: 'frontend',
    environment: environment,
    baseURL: '/',
    locationType: 'hash',
    EmberENV: {
      FEATURES: {
        // Here you can enable experimental features on an ember canary build
        // e.g. 'with-controller': true
      }
    },

    APP: {
      // Here you can pass flags/options to your application instance
      // when it is created
      rootElement: '#perk-ember-container'
    }
  };

  if (environment === 'development') {
    // ENV.APP.LOG_RESOLVER = true;
    // ENV.APP.LOG_ACTIVE_GENERATION = true;
    ENV.APP.LOG_TRANSITIONS = true;
    // ENV.APP.LOG_TRANSITIONS_INTERNAL = true;
    // ENV.APP.LOG_VIEW_LOOKUPS = true;

    ENV.contentSecurityPolicy = {
      'img-src': "*",
      'style-src': "'self' 'unsafe-inline'",
      'font-src': "*"
    };

    // disable this to use http-proxy instead of mirage/pretender
    ENV['ember-cli-mirage'] = {
      enabled: true
    };
  }

  if (environment === 'test') {
    // Testem prefers this...
    ENV.baseURL = '/';
    ENV.locationType = 'none';

    // keep test console output quieter
    ENV.APP.LOG_ACTIVE_GENERATION = false;
    ENV.APP.LOG_VIEW_LOOKUPS = false;

    ENV.APP.rootElement = '#ember-testing';
  }

  if (environment === 'production') {

  }

  return ENV;
};
```

**Comment by ballPointPenguin** [comment]
Sorry about the extra noise. I guess I could try to make a minimal app that replicates the issue. Maybe I'd discover something along the way.

**Comment by samselikoff** [comment]
Np, I'm traveling so may not be able to look at it for a bit, but a minimal repo that I can clone would definitely help

**Comment by ballPointPenguin** [comment]
This hasn't really bothered me enough to isolate yet. Overall, I am very happy how awesome everything is. :hamster:

**Comment by samselikoff** [comment]
haha so glad to hear :) what version of mirage are you on?

**Comment by g-cassie** [comment]
@ballPointPenguin @samselikoff I was getting undefined server in both dev and test environments.  It turned out it was because I was trying to do something like this:

```
module('Acceptance: UsersIndex', {
  beforeEach: function() {
    server.create('user');
    application = startApp();
  },

  afterEach: function() {
    Ember.run(application, 'destroy');
  }
});

```

**Comment by samselikoff** [comment]
Ah, yep right now Mirage's server is instantiated during an Ember initializer. Might make sense to change that, esp. in tests.

**Comment by g-cassie** [comment]
Yeah, I was trying to do this because I need to get the currently logged in user and set it on my session service prior to every single acceptance test.  

I'm just on day 2 with mirage but other than this I am really happy with it - thanks a lot for your work on this great project!

**Comment by ballPointPenguin** [comment]
I finally verified that this is in fact working `localhost:4200/tests` in a pristine ember-cli app with ember-cli-mirage 0.0.29 (likely with 0.0.27 as well, I'd bet).
I'm not sure what was going on in that other app.

**Comment by albertpak** [comment]
I'm getting same error in a recently built app - generated an acceptance test, i try add `server.create('user')` and getting an error while running tests that `server` is not defined

**Comment by alecho** [comment]
@albertpak Same here are you on Ember 2.10? @samselikoff Might be a change there as that's what my app is on? Looking at a 2.4.3 app I'm not doing anything remarkably different there as the 2.10 app.

**Comment by alecho** [comment]
@albertpak @samselikoff In my case this was caused by ESLint thinking that `server` was undefined when the initializer took care of making sure that wasn't the case. My fix is to add `/* global server */` to the top of my acceptance tests so that ESLint doesn't cause a test failure.

**Comment by albertpak** [comment]
My app is on ember 2.5.3 - i did add `server` to .jshintrc in main folder and then in  tests folder also, in `predef` section
