### ISSUE TITLE
JSONAPISerializer cannot use include as a function

### ISSUE THREAD

**Issue by alexpyc** [samselikoff/ember-cli-mirage#815]
Hi all, recently I have an issue on customizing serializer in sideloading related data.

I have the model relationship like this:
Community --hasMany--> Channel --hasMany--> Post
(Channel is included in community's serializer and post is included in channel's serializer)

Previously when I retrieve a community from mirage, it returns me a community along with its child channels and their (channel's) child posts. But then I thought that it is a bit redundant to get also the child posts (which there are a lot of it) each time I get community. So I want to change it that when I get community, mirage returns me only community as well as its channels, but not the posts.

However, when I followed the doc on serializer ([link](http://www.ember-cli-mirage.com/docs/v0.2.x/serializers/)) and tried to include things dynamically, it fails.

The following is the error message I get when I tried to implement include in serializer dynamically (I haven't started adding any conditional statements, but it did not work already):
> vendor.js:42215TypeError: Pretender intercepted GET /communities?identifier=hkusu but encountered an error: (0 , _lodashObjectGet.default)(...).join is not a function
    at child._getRelationshipNames (http://localhost:4200/assets/vendor.js:147266:81)
    at child._serializeRelationshipsFor (http://localhost:4200/assets/vendor.js:147090:38)
    at child._serializeIncludedModel (http://localhost:4200/assets/vendor.js:147115:14)
    at http://localhost:4200/assets/vendor.js:147101:50
    at Array.forEach (native)
    at http://localhost:4200/assets/vendor.js:147099:25
    at Array.forEach (native)
    at child._serializeRelationshipsFor (http://localhost:4200/assets/vendor.js:147092:27)
    at child._serializePrimaryModel (http://localhost:4200/assets/vendor.js:147064:14)
    at child.serialize (http://localhost:4200/assets/vendor.js:147019:27)

Here is the code I wrote in the serializer:
```
import { JSONAPISerializer } from 'ember-cli-mirage';

export default JSONAPISerializer.extend({
  include: function() {
    return ['posts'];
  }
});
```

I am not sure if this coming merge request is related to my issue: 
[the pull request](https://github.com/samselikoff/ember-cli-mirage/pull/781)

Thank you very much!
Pui Yiu

**Comment by samselikoff** [comment]
`include` can be a string too, and only needs to be a function if you want it to be dynamic. What happens if you do

```
include: ['posts']
```

?

**Comment by alexpyc** [comment]
Hi, thank you very much for the reply. It works completely normal when I implement `include` as literal string. But it generates my above error message whenever I tried to implement it in function.

**Comment by samselikoff** [comment]
Ah you're right - this is because the implementation of `include` as function is in the base serializer, but right now JSONAPI doesn't extend from it. This should be fixed when I finish #781

**Comment by alexpyc** [comment]
Thanks! I am looking forward to the fix.

**Comment by acorncom** [comment]
@alexpyc #781 has been merged, does that fix your problem here?

**Comment by acorncom** [comment]
@alexpyc #781 has been merged, does that fix your problem here?

**Comment by alexpyc** [comment]
Hi @acorncom, 

sorry for my late reply. It does fix my problem as stated above. Now I can write include as a function in order to include one or multiple related models. Thank all of you very much for the fix!
