### ISSUE TITLE
setting "type" for JSON:API

### ISSUE THREAD

**Issue by skaterdav85** [samselikoff/ember-cli-mirage#818]
Is there a way to set the `type` with the JSONAPISerializer? If not, I'd be happy to implement that if you agree this is a useful feature. Currently a backend I am working with follows JSON:API but the `type` is often neglected and has no convention, and I want to set a custom `type` in my Mirage responses to simulate the backend.

**Comment by skaterdav85** [comment]
I was looking through the source and noticed that there already is a method that I think controls the `type`: `typeKeyForModel`. Is this public?

**Comment by samselikoff** [comment]
Yes it is - we need better documentation on the individual serializers. `typeKeyForModel` is what you want.

**Comment by skaterdav85** [comment]
I'd be happy to help out with the docs if you can show me where they are located.

**Comment by samselikoff** [comment]
Thank you, that would be extremely helpful!

Here's the serializer docs: http://www.ember-cli-mirage.com/docs/v0.2.x/serializers/. Just click "Improve this page" at the top to open a PR.

At the bottom are the docs for each of the `keyFor` hooks. I would add a section right down there for `typeKeyForModel`, and just add an italicized note that it only applies to the JSONAPISerializer.
