### ISSUE TITLE
Whitelist routes for actual API

### ISSUE THREAD

**Issue by 0x8890** [samselikoff/ember-cli-mirage#822]
It would be nice to be able to define routes which do not use pretender so that an actual HTTP request is made for specific requests.

The use case is that there may be functionality that should rely on a server.

**Comment by samselikoff** [comment]
I think you might be looking for [passthrough](http://www.ember-cli-mirage.com/docs/v0.2.x/configuration/#passthrough)?

**Comment by 0x8890** [comment]
That looks like it, my fault for not reading the docs thoroughly.
