### ISSUE TITLE
TypeError: Cannot call a class as a function

### ISSUE THREAD

**Issue by nerdyworm** [samselikoff/ember-cli-mirage#824]
I'm getting the following error thrown when the ember app is initialized via the startApp function for acceptance tests.

    TypeError: Cannot call a class as a function

I only get this error running acceptance tests in phantomjs. It seems to work just fine in the browser.

If I remove mirage completely, the error goes away.

I've narrowed it down to using function calls in the mirage config file.
``` mirrage/config.js
export default function() {
  // using any function causes TypeError: Cannot call a class as a function
  this.get('/testing', function() { });
}
```
The error can be toggled on and off by adding or removing the this.get() function call.

I can not reproduce this in a new ember app.

If anyone has any idea of what to look at that would be amazing.  I'm hoping at least someone else has run into this :grin:

**Comment by nerdyworm** [comment]
Update:  This error seems to be caused by a missing or bad es5 shim.

We had had a shim for `.bind` in our codebase from https://github.com/kdimatteo/bind-polyfill 

Adding the ember-cli-es5-shim seem to solve the problem.

Closing the issue.  Hopefully, no one else runs into this!  Thanks so much for the library and all the hard work!

**Comment by kkumler** [comment]
FYI, alternative solution: install PhantomJS > 2.0. Testem will also load phantomjs if installed via npm package `phantomjs-prebuilt`
