### ISSUE TITLE
Upgrading from to 0.2.x and getting "ID already in use" errors

### ISSUE THREAD

**Issue by denchen** [samselikoff/ember-cli-mirage#828]
I'm following the [Upgrade Guide](http://www.ember-cli-mirage.com/docs/v0.2.x/upgrading/) to migrate my app from 0.1.13 to 0.2.1, and I'm receiving this error:

    	Error: Attempting to use the ID <my_custom_id>, but it's already been used

My app currently uses all fixture data instead of factory, and several of my fixture files use the same ID. Is this not allowed in 0.2.x?

**Comment by samselikoff** [comment]
It should be one unique `id` per model. If your old files inserted two of the same model with the same ID, I think they'd be getting overwritten.

Is that the case or is it complaining about the same `id` for different models?

**Comment by denchen** [comment]
Actually, I haven't defined any models (yet), as the upgrade guide does say "Currently, Mirage will still work if a factory/fixture file is defined for a particular db collection without a corresponding model."

What I have is 5-6 different fixture files, and most of them do share common ids, but within each fixture file, ids are unique (obviously).

Is the problem that I'm trying to load them all at once via `server.loadFixtures()` in my acceptance test? I also suppose I might be better off fully upgrading by using models?

**Comment by samselikoff** [comment]
You shouldn't have to, for some it will be a lot of work to transition to models so I want to make sure things still work without them.

Do you receive the error in testing or development? Does any of your tests attempt to create a record with a specific ID? Can you print the whole stack trace of the error?

**Comment by denchen** [comment]
I decided to try to upgrade again, this time adding models for each of my fixtures and adding loading of fixtures in my `/mirage/scenarios/default.js`, and everything is working this time without any hitches. I'm just going to chalk this up as I probably didn't do something right the first time around (like maybe I didn't change every instance of `db` to `schema.db`, or something like that).

I believe this issue can be closed.

**Comment by samselikoff** [comment]
Glad you got it working!
