### ISSUE TITLE
Nested routes supported?

### ISSUE THREAD

**Issue by mykehsd** [samselikoff/ember-cli-mirage#831]
I'm loving mirage however I noticed when I nest a route mirage stops working.  

```
this.route('main', {path: '/', function() {
    this.route('create', {path: '/create', resetNamespace: true});
});
```
When run through my acceptance test the create route executes model.save(), which never returns. When inspecting the model you can see it is isSaving: true.  When I un-nest that route it works just fine.

Is this a known limitation?

**Comment by crhayes** [comment]
Is there any way you can put this code in a public repository that could be viewed?

**Comment by mykehsd** [comment]
Sorry I can't but we did figure out that it was related to the authentication requirement inside main.  We stubbed the authentication and it resolved it.  Thanks!
