### ISSUE TITLE
Disable console.log messages

### ISSUE THREAD

**Issue by kgish** [samselikoff/ember-cli-mirage#834]
By default, mirage will output messages. It should be possible to disable these. Or maybe it's better to turn them off by default.

For example, in server.js:
```
console.log(loggedResponse)
console.log('Passthrough request: ' + verb.toUpperCase() + ' ' + request.url);
console.log('Successful request: ' + verb.toUpperCase() + ' ' + request.url);
```

**Comment by samselikoff** [comment]
You can [explicitly disable logging](http://www.ember-cli-mirage.com/docs/v0.2.x/configuration/#logging) within your config.js:

```
this.logging = false;
```
