### ISSUE TITLE
External / passthrough relationships

### ISSUE THREAD

**Issue by buschtoens** [samselikoff/ember-cli-mirage#840]
We use mirage to mock out new features in our project, while passing everything already implemented through to our actual API. Consider this config which works fine so far:

```js
import config from '../config/environment';

export default function() {
  this.urlPrefix = config.endpoints.api;

  this.get('/cars/:id');

  this.passthrough();
}
``` 

```js
import { Model, belongsTo } from 'ember-cli-mirage';

export default Model.extend({
  owner: belongsTo('owner')
});
```

Now assume that `car` has a `belongsTo` relationship with `owner`, which is not handled by mirage, but our actual API. If I then define some `car` fixtures like so:

```js
export default [
  {
    id: '1',
    ownerId: '175600524'
  },
  {
    id: '2',
    ownerId: '175600524'
  }
];
```

... and then request a car like so:

```js
this.store.findRecord('car', 1);
```

I get this error:

```
Mirage: Your handler for the url http://api.localdev/car/1 threw an error: Cannot read property 'find' of undefined
```

I guess this is, because mirage tries to resolve the relationship (even though I did not specify it to be `include`d)...

**Comment by buschtoens** [comment]
After `ember g mirage-model car` (whithout configuring any route handlers), I get this error:

```
Mirage: Couldn't find owner with id = 175600524
```

**Comment by samselikoff** [comment]
Yah, I believe this is because Mirage is trying to serialize your `car` and in doing so needs to reference the `owner`.

You could try writing a custom route handler instead, or just `ember g mirage-model owner` and that should take care of it.

**Comment by samselikoff** [comment]
Let me know if you need any more help 😄
