### ISSUE TITLE
Add `.config` to Server API (shared mirage config addon)

### ISSUE THREAD

**Issue by samselikoff** [samselikoff/ember-cli-mirage#842]
Mirage configures itself in its [constructor](https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/server.js#L108-L150). Let's extract this logic to a `config` method. The constructor will call it with the `config` that's passed in (let's rename `options` to `config`), but exposing this method will allow developers to augment their server's config after construction time. This will enable developers to piece together a Mirage server's config from multiple places, e.g. in-addon config.

Once extracted the `.config` method should be made idempotent, so it can be called again and again safely.

 - There's some code that sets initial values (timing, namespace etc). This code should only run if the given variables are `undefined`.
 - The db and schema are set up. `schema` has a public `registerModels` method that takes a hash of models - this should already be idempotent and can be called again with new models. It also creates the `db` collection if it doesn't exist. So this shouldn't be too difficult.
 - The `pretender` server instance should only be instantiated once
 - We should probably throw an error if the environment is explicitly changed (i.e. if it was explicitly set to `dev` in one run but then `test` the next)
 - for `loadFactories`, the factoryMap should augmented (not replaced). Creating a db collection for each factory is a backwards-compatibility thing. `db.createCollection` should already be idempotent

The rest looks pretty straightforward (e.g. `loadConfig` should be run each time, etc).

**Comment by samselikoff** [comment]
I would love for someone to take this one!

**Comment by Leooo** [comment]
@samselikoff looking

**Comment by acorncom** [comment]
@samselikoff Is this resolved at this point?

**Comment by samselikoff** [comment]
Yep thanks. Tracking next step in #899
