### ISSUE TITLE
Documentation unclear for how to customise POST/PUT/PATCH endpoints

### ISSUE THREAD

**Issue by jackmatt2** [samselikoff/ember-cli-mirage#843]
I am using the JSONAPI serializer. I need to customise a JSONAPI payload before it is saved.

From the [documentation](http://www.ember-cli-mirage.com/docs/v0.2.x/shorthands/#post-shorthands) it says that the equivalent shorthand for a POST request is:

```
this.post('/contacts', ({ contacts }, request) => {
  let attrs = this.normalizedRequestAttrs();

  return contacts.create(attrs);
});
```

But `this.normalizedRequestAttrs();` is not a valid function.

**Comment by samselikoff** [comment]
Whoops, can't use a fat arrow function here, since the helper methods are attached to the `this` object (the route handler).

**Comment by samselikoff** [comment]
https://github.com/samselikoff/ember-cli-mirage/commit/e44040194ccc9f4b2adfb1e31519f1f9aac1a67b closes
