### ISSUE TITLE
'"this.normalizedRequestAttrs" is not a function' when extending shorthands

### ISSUE THREAD

**Issue by nikz** [samselikoff/ember-cli-mirage#847]
Hi Sam,

(First off thanks for `ember-cli-mirage` 🐹 ❤️ )

I'm working through upgrading to `0.2.0`, and I have some custom Route handlers so that I can add validation messages. I am using the ActiveModelSerializer.

Using [the exact shorthand expansion from the docs](http://www.ember-cli-mirage.com/docs/v0.2.x/shorthands/#put-shorthands) seems to result in an error (`"this.normalizedRequestAttrs" is not a function`) and checking the debugger, it looks like that function is indeed not about.

I've worked around it by not using the ` => ` function and accessing the handler directly, replacing the `normalizedRequestAttrs` call with:

```js
this._getAttrsForRequest(request, "contact");
```

Now, given there's an underscore there, I'm fairly sure that I shouldn't be doing that 😄 

There are a couple possibilities:

  1. I'm doing something silly (always a chance...)
  2. The docs need updating
  3. The code needs updating

If you could point me to which case it is, I'm more than happy to send a PR for (2) or (3). Unfortunately I don't think PRs are possible for (1) at this stage.

Thanks again!

Nik

**Comment by samselikoff** [comment]
Have we updated the docs at this point? I think it's because you were using `=>`, but `this.normalizedRequestAttrs` requires the `this` context from the actual function handler (it binds the request). Let me know if that fixes it?

Probably not the best API as others have run into this...

**Comment by nikz** [comment]
Hi Sam,

You're quite right, the docs don't use the `=>`... doh 😄 

I wonder if there's an adjustment we could make to the API so that it would forward from the current context (or we could pass the normalised params into the function handler?) as I think you're right, it's a teensy bit confusing.

Happy to help out with that change.

**Comment by samselikoff** [comment]
Could you point out in the docs where it's using `=>` instead of `function()`?

Unfortunately to be able to use `=>` we'd need to import the function and pass in all arguments, something like

```
import { normalizedRequestAttrs } from 'ember-cli-mirage';

this.get('/users', (schema, request) => {
  let attrs = normalizedRequestAttrs(request);
});
```

which imo reduces its usefuless. I think we could support both, though I'd rather there be "one way".

**Comment by nikz** [comment]
@samselikoff the docs are all using `function()` correctly - but because the other handlers use `=>` it's a bit of a gotcha.

We could just pop an "NB: note that we're using `function` not `=>` here..." into the docs?

**Comment by samselikoff** [comment]
I like it

**Comment by acorncom** [comment]
@nikz Would you be able to send in a PR for that note above?

**Comment by nikz** [comment]
@acorncom done!
