### ISSUE TITLE
faker.random.uuid in a factory doesn't work with Faker 3.1

### ISSUE THREAD

**Issue by Dhaulagiri** [samselikoff/ember-cli-mirage#850]
[A bug/change](https://github.com/Marak/faker.js/issues/368) in Faker 3.1 causes exceptions if you have a mirage factory that uses `faker.random.uuid`.  The reason for this is that the context of `self` inside faker's uuid function [here](https://github.com/Marak/faker.js/blob/e8231413cc38a3ce49d712823dadbffbd1849acc/lib/random.js#L93) is the factory object itself when called from mirage [here](https://github.com/samselikoff/ember-cli-mirage/blob/216250b8d6c8530474edb7440697c8de2efdd359/addon/factory.js#L88).

Prior to https://github.com/samselikoff/ember-cli-mirage/pull/813 it was easy enough for consumers of ember-cli-mirage to peg their preferred version of Faker in their bower.json, but subsequent to #813 that doesn't seem possible.

I'm not sure if there is anything specific we could do with ember-cli-mirage to avoid this, but I thought it was worth opening an issue in case others have encountered this problem and had some insight on how to proceed.

_It's also worth noting that Faker 3.1 also includes at least [one other breaking change](https://github.com/Marak/faker.js/issues/356) and that in general Faker doesn't seem to follow semver._

**Comment by samselikoff** [comment]
We should allow users to specify their own versions, let's see if @locks has some insight on whether it's possible to override NPM package versions.

**Comment by Leooo** [comment]
(changed Faker version to one working in https://github.com/samselikoff/ember-cli-mirage/pull/849)

**Comment by samselikoff** [comment]
Seems like we should lock Faker to a previous version, @Leooo (or anyone else) it'd be great if we could get a single PR for this. (Alternatively, @Leooo once you address my comments in #846 it will land there too).

**Comment by ktrhn** [comment]
This issue is again present in current version of ember-cli-mirage.
