### ISSUE TITLE
Multiple hasMany() in model

### ISSUE THREAD

**Issue by marxsk** [samselikoff/ember-cli-mirage#854]
Hi,

Let's have model:
```
node.js
export default Model.extend({
  nodeAttributes: hasMany('attribute'),
  personAttributes: hasMany('attribute'),
});
```
We can now create a new record using:
```
...
node.createNodeAttribute({key: 'attr #1', value: 'foo'});
node.createPersonAttribute({key: 'attr #2', value: 'bar'});
```

JSON returned to Ember application serializes them in a way that nodeAttributes contains both these attributes and personAttributes too. I was able to locate that orm/associations/has-many.js in last function for create* does not save 'association.key' anywhere so this information is lost.

**Comment by marxsk** [comment]
@samselikoff if you can give me pointers how you wish to solve such issues, I can create a PR but I'm not aware of other issues

**Comment by samselikoff** [comment]
Because Mirage makes assumptions about foreign keys, you'll need to specify inverses to differentiate the collections. A `hasMany` by itself here is creating a `nodeId` property on the `attribute` model, which is why they're all getting lumped together.

Have a look at the docs on inverse under [Associations](http://www.ember-cli-mirage.com/docs/v0.2.x/models/#associations), then check out [this twiddle](https://ember-twiddle.com/b88aefbb1342f31cbdc68e6092959898?openFiles=templates.application.hbs%2C) I've made demonstrating how it works.

**Comment by marxsk** [comment]
Thanks a lot for twiddle. 

So, if I want to have multiple relations hasMany to same type, I need to define inverse/belongsTo even if I need it [that's fair enough]. But if I don't want to have blueUser: belongsTo() and redUser: belongsTo in fish.js but only one attribute "user:", the inverse part will not help because in some cases it will points redFish and in other it will be blueFish.

Because I plan to re-use my model quite a lot (10+ times), the only solution that should work for now is to have blueUser, redUser, yellowUser, ... and then to have computed property 'user' which will contain the real value. Is that right?

**Comment by samselikoff** [comment]
How is the domain modeling done in your actual server? Is this a polymorphic relationship?

(Btw, you shouldn't _have_ to be doing this at all, ideally you would just be able to stick the `hasManys` on there and get your `Ids: []` array. This will be the case after some upcoming changes, but alas this is the current workaround).

**Comment by marxsk** [comment]
We have attributes (key : string / value : string) that are used all around the application and from the front-end perspective they share same logic, the only difference is where to put it in. The input JSON contains nodeAttributes : [{key/value}, {key/value}, ... ], nodeUtilizationAttributes [{key/value}, ...]. But as there is no chance there will be several pointers to the same attribute, it is possible to change my ember models to (key/value/type) and it will solve this issue. Thanks a lot for idea.

**Comment by samselikoff** [comment]
Ok, great. Let me know if I can be of any more help.
