### ISSUE TITLE
Unpersisted model creates duplicate children for hasMany

### ISSUE THREAD

**Issue by richmolj** [samselikoff/ember-cli-mirage#855]
So, there's an easy workaround for this, it might just be a documentation issue. But something very unexpected occurs with this code:

``` js
let post = db.posts.new({ title: 'test title' });
let tag = db.tags.new({ name: 'test' });
post.tags = [tag];
post.tags.models.length // 1
post.save();
post.tags.models.length // 2
```

The save creates a duplicate `tag` record, with the same id/attributes. This does **not** occur if you persist the post first.

This doesn't usually come up, but I'm building helpers to work with compound (nested) documents. I had been building up a big `post` record then saving it, like I would do with Rails. But it looks like mirage requires you to persist the parent before adding children or you get unexpected results.

**Comment by siva-mahadevan** [comment]
I can confirm this issue. Will this workaround require me to persist the parent twice? For instance (in your snippet), once before adding the tags and once after?

**Comment by richmolj** [comment]
@siva-mahadevan yeah AFAIK you need to save twice - once for the initial model, once after setting associations.

**Comment by samselikoff** [comment]
Interesting, definitely looks like a bug.

Just to mention, `schema.create` will immediately persist the initial record (as opposed to `schema.new`). But this is still an issue.

**Comment by samselikoff** [comment]
Can somebody help with this?

- the `post.tags = []` method is [here](https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/orm/associations/has-many.js#L133), you can see the `if isNew` branch of code, that would be one place to look
- the `save` method is [here](https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/orm/model.js#L41) which calls `_saveAssociations` [here](https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/orm/model.js#L257). That'd be another place to look

**Comment by samselikoff** [comment]
...I know this is very late! But the problem seems to have been resolved.

https://ember-twiddle.com/258d1ced969e6938c3b7d338e38e64ff?openFiles=mirage.scenarios.default.js%2C
