### ISSUE TITLE
Share mirage folder between apps in an add-on?

### ISSUE THREAD

**Issue by Leooo** [samselikoff/ember-cli-mirage#856]
Hello,
Is it possible to share the mirage folder (factories, scenarios, models etc.) between different Ember apps, probably using an addon?

Thanks,

L

**Comment by samselikoff** [comment]
No, but other folks have asked about this too. I wrote out some thoughts in #842, and would love to have your help in implementing it!

**Comment by Leooo** [comment]
one solution is in https://github.com/samselikoff/ember-cli-mirage/issues/899
