### ISSUE TITLE
Logging seems to be faulty

### ISSUE THREAD

**Issue by mariogintili** [samselikoff/ember-cli-mirage#857]
```
DEBUG: -------------------------------
ember.debug.js:6734 DEBUG: Ember           : 2.7.0
ember.debug.js:6734DEBUG: Ember Data      : 2.7.0
ember.debug.js:6734DEBUG: jQuery          : 2.2.4
ember.debug.js:6734DEBUG: Model Fragments : 2.3.2
ember.debug.js:6734
DEBUG: -------------------------------
```

My version of `ember-cli-mirage` also is `0.2.1`

It seems like if you return a 500 from ember-cli-mirage the logging still shows it as a "success" - is this the expected behaviour?

<img width="1250" alt="screen shot 2016-09-01 at 10 23 09 am" src="https://cloud.githubusercontent.com/assets/3522106/18162430/60091aaa-702e-11e6-941a-18e068b95daa.png">

**Comment by samselikoff** [comment]
This is a poorly worded message - it really means Mirage handled this request.

Would you be up for submitting a quick PR? Let's change [this line](https://github.com/samselikoff/ember-cli-mirage/blob/10cdfe9a84de1cc96c8580b67b40cd7721f6a4ce/addon/server.js#L27) to show:

    Mirage: [200] GET /my/url

and  leave the response being logged.

**Comment by mariogintili** [comment]
@samselikoff will do soon 😄

**Comment by mariogintili** [comment]
@samselikoff https://github.com/samselikoff/ember-cli-mirage/pull/869 😄

**Comment by samselikoff** [comment]
https://github.com/samselikoff/ember-cli-mirage/pull/869 closes

**Comment by samselikoff** [comment]
🎊
