### ISSUE TITLE
docs syntax wrong on faker.list.cycle

### ISSUE THREAD

**Issue by Leooo** [samselikoff/ember-cli-mirage#868]
Should be:

`````
  // factories/meterRead.js
  classification() {
    return faker.random.arrayElement([
      'Actual',
      'Estimated'
    ])
  }
`````

**or**

`````
  // factories/meterRead.js
  classification: faker.list.cycle(
    'Actual',
    'Estimated'
  )
`````

**but not**

`````
  // factories/meterRead.js
  classification() {
    return faker.list.cycle(
      'Actual',
      'Estimated'
    )
  }
`````

the last one is the one in the docs, not working

**Comment by samselikoff** [comment]
Ah yes, this is super confusing & bad that we introduced a basically inconsistent API. There are reasons for it but yah, for now let's just update. 

Would you mind clicking the "Improve this page" link on the relevant doc page & submitting a PR with the fix?

**Comment by Leooo** [comment]
done thanks

**Comment by samselikoff** [comment]
Super helpful, thank you sir
