### ISSUE TITLE
Notify/warn when more than one server is started. 

### ISSUE THREAD

**Issue by GCheung55** [samselikoff/ember-cli-mirage#875]
Multiple servers can start due to improper shutdown. There should be a warning/notification when this happens.

**Comment by samselikoff** [comment]
A warning is a great idea for now, we could deprecate & change to an error for 1.0 release.

You should be able to check if there's already a Mirage/Pretender server running by looking if window.XMLHttpRequest is a fake one, and then `console.warn` a message.

Think you could open a PR and add this check, perhaps [here](https://github.com/samselikoff/ember-cli-mirage/blob/master/app/initializers/ember-cli-mirage.js#L26)?

**Comment by GCheung55** [comment]
Okay. I'll see what I can do.

**Comment by samselikoff** [comment]
Pretender took care of this upstream.
