### ISSUE TITLE
Doesn't work if baseURL removed from environment.js

### ISSUE THREAD

**Issue by GendelfLugansk** [samselikoff/ember-cli-mirage#876]
Today I upgraded ember-cli to 2.8. During build there was a notice that baseURL was deprecated and I should use rootURL. So I removed baseURL from config. 

After this, if current url is "/invoices/20", mirage tells me "Your Ember app tried to GET 'auth/2', but there was no route defined to handle this request." (in fact, auth/:id route is defined in my config). if url is "/invoices", everything works fine.

If I put baseURL back, mirage works in all cases.

**Comment by GendelfLugansk** [comment]
Nevermind. That is a problem with ember data and my config.

**Comment by blimmer** [comment]
@GendelfLugansk what ended up being the problem? I'm seeing the same thing.

**Comment by blimmer** [comment]
For some reason, I had to change my namespace from:

```javascript
namespace: 'web_v1',
```

to
```javascript
namespace: '/web_v1',
```

and things started working again.

**Comment by GendelfLugansk** [comment]
@blimmer in adapter host has been set to '/'. And I don't understand why, but in this case ember data sends ajax request to 'user/2' instead of '/user/2'. And removing ``baseURL`` removes ``base`` tag from html. Setting host to '' (empty string) fixed things.

**Comment by rwwagner90** [comment]
Can you guys elaborate on what changes to make and where please?

**Comment by GendelfLugansk** [comment]
@rwwagner90 in your adapter (of your app), set namespace to '/' and host to ''

**Comment by rwwagner90** [comment]
@GendelfLugansk I was able to fix it using another method, thanks!

**Comment by seawatts** [comment]
I was getting the same thing and I added back the `baseURL` to my `config/environment.js` and then it worked. I don't have time to figure out the root cause right now. But that is my workaround for the time being

**Comment by trevorrjohn** [comment]
I am also getting this bug, it is strange because it works in Chrome without setting the `baseURL` however when I run my tests with PhantomJS it is failing.

**Comment by knownasilya** [comment]
Solved the issue for myself by adding back in `baseURL` in `config/environment.js`. Adapter namespace works both with a `/` and without one, made no difference.

**Comment by knownasilya** [comment]
This should be reopened as a bug I think, because all latest versions of ember-cli don't have `baseURL` any more. cc @samselikoff

**Comment by allthesignals** [comment]
Spent an hour tracking down this issue - if you're using any of the beta functionality in http://www.ember-cli-mirage.com/blog/2017/01/09/0-3-0-beta-series/, this will become a problem in production environments like Pagefront and Github Pages

**Comment by samselikoff** [comment]
@knownasilya I don't think Mirage relies on baseURL, could you open a new issue with either a twiddle or sample repo/code/test showing the problem?
