### ISSUE TITLE
Chrome: `Uncaught Error: Mirage: Your Ember app tried to GET 'native messages.js',`

### ISSUE THREAD

**Issue by jesseditson** [samselikoff/ember-cli-mirage#878]
When running tests via `ember test --serve`, I get this message every so often, only in the chrome runner:

```
Global error: Uncaught Error: Mirage: Your Ember app tried to GET 'native messages.js',
         but there was no route defined to handle this request.
         Define a route that matches this path in your
         mirage/config.js file. Did you forget to add your namespace? at http://localhost:7357/assets/vendor.js, line 29830
```

The last line of my config.js function is `this.passthrough();`, which I assume would let this through. Perhaps there's some bad detection causing ember-cli-mirage to believe we should be handling this? I don't see the requests fire in my network panel, and I can't find any information about what this js file is on google/SO - any clues what's going on here?

**Comment by jesseditson** [comment]
Looks like I can workaround (very temporarily locally, not in CI) by removing my namespace. Is there an option somewhere to passthrough non-namespaced requests? Seems like this should be the default IMO.

**Comment by samselikoff** [comment]
Hm I think I agree. Could you try moving the `this.passthrough()` line above your `this.namespace` declaration as another test?

**Comment by stephanebruckert** [comment]
That worked for me @samselikoff! Thanks

**Comment by hbrysiewicz** [comment]
Closing as it appears this has been fixed

**Comment by dennismende** [comment]
Hi,
only in case some has a similar problem in the future.

For me it worked to just simply disable once the chrome extensions and activate them again after an app page refresh.

Don't know why but afterwards the problem was gone.
