### ISSUE TITLE
Importable config

### ISSUE THREAD

**Issue by carlbennettnz** [samselikoff/ember-cli-mirage#879]
I manage a few Ember apps that all share the same backend. Right now I'm duplicating all of my Mirage config into each app. Is there any way I could keep my config in one repo and import it manually into each app?

**Comment by acorncom** [comment]
@carlbennettnz Looks like you'd need to update this line in a custom fork of Mirage (https://github.com/samselikoff/ember-cli-mirage/blob/master/index.js#L43).  @samselikoff is this something you'd be interested in supporting in the long run if a PR was sent in?

**Comment by acorncom** [comment]
@carlbennettnz Just saw an issue / PR that I hadn't seen earlier.  Looks like this idea is in the works here (https://github.com/samselikoff/ember-cli-mirage/issues/842).  Not sure it's finished yet, but it's coming.  Would love to have your help on it if you've got the time!

I'll close this issue for now so we can track in the linked issue

**Comment by samselikoff** [comment]
Tracking in #899
