### ISSUE TITLE
Data persistence across sessions

### ISSUE THREAD

**Issue by idijan** [samselikoff/ember-cli-mirage#88]
If I'm running an Ember CLI app with Mirage as the data source, and accessing it from multiple different sessions, is the data set supposed to be shared?

I assumed it would be after reading this paragraph:

__As long as all your Mirage routes read from and write to the db, your user interactions during development will persist. This lets users interact with your app as if it were wired up to a real server.__

But it doesn't seem to be the case out of the box.
Was it a misunderstanding on my part? :)
The scenario is that 2 users connect to the app that's running on a devbox, one makes some updates and the other will see updated data next time he fetches it. Is it a complete no-go (each session creates their own mirage server) or I might be missing some setting?

**Comment by samselikoff** [comment]
Yes, for now the db is in memory. At this point it looks like you need to start writing your actual server :)

The "interactions during development will persist" line means, as the user uses (a single instance of) the app, the db will stay updated. So if he moves around, creates things + comes back, the data will be updated. But its only for that instance.

Possibly one day we could point Mirage to use a shared db? But the point is really just to be a lightweight mock of your server for development + testing.

**Comment by idijan** [comment]
Thought so, thanks!
