### ISSUE TITLE
Allow customHandlers to determine the http status code.

### ISSUE THREAD

**Issue by cibernox** [samselikoff/ember-cli-mirage#89]
I dove into the docs and the code and I haven't found any way of customizing the response code in custom handlers. I think it's not possible right now.

What I'd like to do:

```js
  this.post('/posts', function (db, request) {
    let data = JSON.parse(request.requestBody);
    if (!data.post.title) {
      return [ 422, {
        errors: { title: ["can't be blank"] }
      }];
    }
  });
```

Seems reasonable to asume that if a custom handler returns a tuple (an array with 2 elements in which the first one is a number in the status-code range 100..599) you're customising the status code. 
I suggested a tuple because it similar to the rack behaviour many people already knows.

**Comment by samselikoff** [comment]
Yes, there's a discussion over in #70. Others have mentioned the tuple (I thought it was a triplet: status code, headers, body). The problem is, I also want it to be easy for someone to just return a 3-element array from their route.

I need to think about this, but I should have something soon. Seems more and more people want it.

**Comment by cibernox** [comment]
I missed that issue. Closing this :)

**Comment by samselikoff** [comment]
np, good to know others want it though. For now you can override your route in tests to test the error response. But we'll definitely have an answer to this soon.

**Comment by skaterdav85** [comment]
any update on this? =)

**Comment by samselikoff** [comment]
Yes this has been possible for a while, see the [second example in the Routing API guide](http://www.ember-cli-mirage.com/docs/v0.1.x/routes/#function-handler).

**Comment by skaterdav85** [comment]
ah I missed that. thanks!
