### ISSUE TITLE
Make auto generated ids as string configurable

### ISSUE THREAD

**Issue by jasalguero** [samselikoff/ember-cli-mirage#891]
I updated from 0.1 to 0.2.x and many things stopped working because the application was expecting integer ids, since that's what the real api outputs.

I think the change comes from here: https://github.com/samselikoff/ember-cli-mirage/issues/67 and I understand the logic behind, but without an alternative to for generating integer ids this will break a lot of stuff :(

Ideally an option in the configuration would make the trick

**Comment by samselikoff** [comment]
This sucks - definitely frustrating :(. At the least we should mention it in the upgrade guide.

**Comment by samselikoff** [comment]
I don't think we need to make this configurable, we just made that change so internally to Mirage (the db, etc) ids are strings. If your actual API returns ints, I think the serializer layer is the most appropriate place for this.

We need to add an API to do this per-attribute. For now if I had to do this, I think I would do it in the `#serialize` hook:

```js
// serializers/application.js

export default Serializer.extend({

  serialize(response, request) {
    let json = Serializer.prototype.serialize.apply(this, arguments);

    // crawl json looking for `id` field, converting from string to int

    return json;
  }
});
```

Does that seam possible/reasonable?

**Comment by jasalguero** [comment]
I agree, but the problem is the Serializer only works when using models. As it is now, with the combination of both issues, there's no way to change that behaviour... only solutions I can see are:

A) Make Serializer process all outgoing responses
B) Make Id type configurable

I prefer option A, since I can foresee many cases where someone needs to add/remove/modify data in a general way, so it seems more powerful.

**Comment by samselikoff** [comment]
Follow #892 for progress
