### ISSUE TITLE
Shift the docs from gh-pages branch to master branch?

### ISSUE THREAD

**Issue by acorncom** [samselikoff/ember-cli-mirage#895]
Per Github, they now allow docs to be stored in `/docs` on `master`: https://github.com/blog/2228-simpler-github-pages-publishing

Would shifting things there make it easier to keep things in sync?  Not sure we'd want to do that, but thought I'd ask ...

**Comment by samselikoff** [comment]
Yep, potentially.

1. If we moved the Jekyll source to `/docs`, GH will still build and publish?
2. I've been wanting to move away from Jekyll and make the docs site an Ember app in `/dummy`, and use the `ember-cli-gh-pages` addon to publish. This way they'd be in the same repo as the code, and maybe we could even get API docs for free from the YUI comments. Big question here is how to deal with older versions of the docs. Maybe we can just grab the static output from the current site and stick them in the dummy app's public folder.

Once we decide on a course of action I'll make a Project and break down the steps.

**Comment by samselikoff** [comment]
At this point it seems clear to me that moving the docs to the dummy app is the best next step. I'll open a new issue to discuss what needs to happen.

**Comment by samselikoff** [comment]
https://github.com/samselikoff/ember-cli-mirage/issues/909
