### ISSUE TITLE
Shift the UseCanvas roadmap into a Project?

### ISSUE THREAD

**Issue by acorncom** [samselikoff/ember-cli-mirage#896]
Makes it easier to see progress on things over time ...

**Comment by acorncom** [comment]
@samselikoff I'm happy to help with this once we've figured out the Github organization question

**Comment by samselikoff** [comment]
Yes, it was already outdated so we'll track in a new spot. Going through issues now and hoping to make some projects to accommodate our progress. Or, eventually possibly the org.

**Comment by samselikoff** [comment]
The ORM has a project and the traits/associations were done. Once I get through issue backlog we'll make a "General development" project with prioritized issues
