### ISSUE TITLE
Setup a sample project demoing various Mirage functionality

### ISSUE THREAD

**Issue by acorncom** [samselikoff/ember-cli-mirage#897]
More details on this here: https://github.com/samselikoff/ember-cli-mirage/issues/770

**Comment by kashiif** [comment]
I would love to take this. Can we have a list of items that should be demonstrated?

**Comment by samselikoff** [comment]
This should be part of the dummy app once move the documentation site over. This is blocked by those steps but I've added a note to the docs project [here](https://github.com/samselikoff/ember-cli-mirage/projects/2). 

Once we take care of the early stuff we'll come back to this.

**Comment by samselikoff** [comment]
https://github.com/samselikoff/ember-cli-mirage/issues/909 is the first issue
