### ISSUE TITLE
Question - Add custom logic to shorthand handlers

### ISSUE THREAD

**Issue by kashiif** [samselikoff/ember-cli-mirage#898]
I have a big project having couple dozens of endpoint handlers. Most of our list endpoints have paging capability so for example a `/users` is always called as `/users?page_number=X&page_size=Y` where `X` and `Y` are integers. The response contains `Y` numbers of records for the given page number `X`. Sometimes the query string can also contain sorting information.

Most of our handlers look like this:

```js
this.get('users', function (db, request) {

  let pageSize = request.queryParams["page_size"] || 10,
    pageNumber = request.queryParams["page_number"] || 1,
    sortColumns = ((request || {}).queryParams || {}).sort || '';

  let lastPage = 1;
  let results = [];

  results = db.users.all();

  // the code that sort results according to `sortColumns`

  // the code to extract `pageSize` number of records for page `pageNumber`

  let json = this.serialize(results);

  json.meta = {
    page: {
      total: lastPage,
      number: pageNumber,
      size: pageSize,
      sort: [{
        field: "id",
        direction: "asc"
      }]
    },
    total_count: totalRecords
  };

  return json;

});
```
Is there a way to override the default shorthands and make mirage use the overridden functions? This means that when we add a new handler `this.get('purchases')`, it already have the paging and sorting functionality?

**Comment by samselikoff** [comment]
Unfortunately no. Typically here folks will extract this into a new function that makes it easier to reuse:

```js
// mirage/utils/paginate-and-sort.js
export default function(collection) {
  let pageSize = request.queryParams["page_size"] || 10,
    pageNumber = request.queryParams["page_number"] || 1,
    sortColumns = ((request || {}).queryParams || {}).sort || '';

  let lastPage = 1;
  let results = [];

  results = db[collection].all();

  // the code that sort results according to `sortColumns`

  // the code to extract `pageSize` number of records for page `pageNumber`

  let json = this.serialize(results);

  json.meta = {
    page: {
      total: lastPage,
      number: pageNumber,
      size: pageSize,
      sort: [{
        field: "id",
        direction: "asc"
      }]
    },
    total_count: totalRecords
  };

  return json;
}

// mirage/config.js
import paginateAndSort from './utils/paginate-and-sort'

export default function() {
  this.get('users', paginateAndSort('users'));
  this.get('posts', paginateAndSort('posts'));
  // etc
}
```

I think I'd prefer to keep this logic here in userland, the shorthands are really just to get people going for the basic routes. We've also talked about adding pagination/sorting/filtering support somewhere in the serializer layer.

 Let me know if you have any more questions!
