### ISSUE TITLE
Make namespace/host support more robust

### ISSUE THREAD

**Issue by samselikoff** [samselikoff/ember-cli-mirage#901]
Folks keep running into issues if their namespace/host is
- undefined
- empty string
- starts with a leading slash

or if their routes have or omit a leading slash. We should make the logic robust to all these cases.

**Comment by samselikoff** [comment]
Seems there's also issues now that baseUrl is deprecated. I want to get all this stuff sorted out, would love someone's help.

**Comment by backspace** [comment]
Ah, this is happening to me [here](https://github.com/travis-ci/travis-web/pull/723)! Removing `baseURL` has caused test failures that I don’t know how to fix apart from adding a leading `/` in the adapter’s namespace, which results in unsightly `//`s in production API calls. 🤔

**Comment by 0000marcell** [comment]
I having this issue too, if i remove baseURL the tests won't pass, if i add baseURL i get a deprecation warning, for now i'm leaving the deprecation warning, is there any better solution ?

**Comment by samselikoff** [comment]
https://github.com/samselikoff/ember-cli-mirage/pull/1006 closes
