### ISSUE TITLE
Version 0.2.2 Not Published

### ISSUE THREAD

**Issue by paulyoder** [samselikoff/ember-cli-mirage#902]
I just tried to install this package with `ember install ember-cli-mirage` and noticed NPM only has version 0.1.14

Can the 0.2.2 version be published to NPM? 

Thanks!

**Comment by samselikoff** [comment]
Looking into it

**Comment by samselikoff** [comment]
It is published, you can `ember install ember-cli-mirage@0.2.2` but I don't know why 0.14 clobbered it as the default

**Comment by samselikoff** [comment]
Should be all set. 

Future reference: publishing an older version rewrote `latest`. To fix I did

```
npm tag ember-cli-mirage@0.2.2 latest
```

I think there's a way to just publish in the future without overriding latest but I'm not sure how, something with `--tags`.
