### ISSUE TITLE
Relation is serialized to the model name instead of the attribute name

### ISSUE THREAD

**Issue by jessedijkstra** [samselikoff/ember-cli-mirage#905]
When I upgraded from 0.2.1 I noticed that all of the sudden certain relationships with on the wrong key. It uses the model key instead of the attribute key.

I defined the relationship with `include` on a model that is serialised with the `ActiveModelSerializer` serialiser as followed:

``` js
import ApplicationSerializer from './application';

export default ApplicationSerializer.extend({
  include: ['author']
});
```

The model includes the relationship as followed:

``` js
export default Model.extend({
  author: belongsTo('user'),
  user_answers: hasMany('user_answer'),
});
```

The factory sets the author with afterCreate as followed:

``` js
  const { user_answers, author } = user_question;

  if (!author) {
    user_question.author = server.create('user');
  }
```

The returned JSON with 0.2.1 stores the relation in the author key:
<img width="560" alt="screen shot 2016-09-27 at 10 44 11" src="https://cloud.githubusercontent.com/assets/226130/18866293/a5fa1048-849f-11e6-90bc-c2c7eac0fe9e.png">

In 0.2.2 the relation is stored in the user key:
<img width="559" alt="screen shot 2016-09-27 at 10 45 42" src="https://cloud.githubusercontent.com/assets/226130/18866300/aaaf649e-849f-11e6-88e1-da6160c095b2.png">

**Comment by jessedijkstra** [comment]
@samselikoff any information on this? It's a breaking bug.

**Comment by aquamme** [comment]
I've encountered this problem too. I ended up just renaming my model as a workaround.

**Comment by saheljalal** [comment]
In the `_hashForModel` method in `serializer.js` it seems the attribute key isn't used when embedding resources.

```javascript
if (this.embed) {
  let newDidSerialize = _assign({}, didSerialize);
  newDidSerialize[model.modelName] = newDidSerialize[model.modelName] || {};
  newDidSerialize[model.modelName][model.id] = true;

  this.getKeysForIncluded().forEach(key => {
    let associatedResource = model[key];
    if (!_get(newDidSerialize, `${associatedResource.modelName}.${associatedResource.id}`)) {
      let [ associatedResourceHash ] = this.getHashForResource(associatedResource, true, newDidSerialize, true);
      let formattedKey = this.keyForResource(associatedResource);
      attrs[formattedKey] = associatedResourceHash;

      if (this.isModel(associatedResource)) {
        let fk = `${camelize(associatedResource.modelName)}Id`;
        delete attrs[fk];
      }
    }
  });

  return attrs;
}
```

**Comment by jessedijkstra** [comment]
@saheljalal Yeah, noticed that myself. Am working on a pull request, only need to get the JSONAPI and RESTSerializers working with the new code in the default serializer:
https://github.com/samselikoff/ember-cli-mirage/pull/930
