### ISSUE TITLE
createList only push the last record into store in scenario

### ISSUE THREAD

**Issue by Padchi** [samselikoff/ember-cli-mirage#906]
Hi!

Like the title says, only the last record is pushed into store and i'm not doing anything fancy in the default scenario:
```
export default function(server) {
  server.createList('recipe', 10);
}
```

In my recipe factory title is set like the docs explain that's how I know it's only the latest record that is stored (the one recipe that is generated have 'Recipe 9' as title):
```
title(i) { return `Recipe ${i}`; }
```

And this is logged to the console: 
```
Mirage: [200] GET http://api.vjr.dev/v1/recipes
server.js:77 Object {recipes: Array[1]}
```

**Comment by acorncom** [comment]
Hi @padchi, sorry to hear about the headaches. I regularly use a setup that looks almost identical to what you are describing (here'a an example in this app: https://github.com/ember-learn/ember-help-wanted/blob/master/mirage/scenarios/default.js) and this feature works great. 

What version of Mirage are you using? Have you created a mirage-model named `recipe`? If you have and it's still not working, a sample repo would be helpful for debugging what is going on ...

**Comment by Padchi** [comment]
Hi @acorncom!

I'm using the v0.2.2. Yes I have a mirage model named `recipe` (it's empty tho). The weird thing is that `server.createList('recipe', 10);` works in my acceptance test's.

**Comment by Padchi** [comment]
Yeah it's the fake uuid that make this. Skipping that, not so important anyway.

**Comment by ryanrishi** [comment]
Interesting...any idea as to why `faker.random.uuid()` causes the store to only keep one record?

**Comment by Padchi** [comment]
@ryanrishi actually i've no idea, I have just skipped that UUID part in my apps for now. I don't need it in my tests anyway.
