### ISSUE TITLE
Included not functioning properly for JSON API Serializer

### ISSUE THREAD

**Issue by seanmhoffman** [samselikoff/ember-cli-mirage#907]
I was in the process of mocking out an API when I realized that my includes weren't working for any model in which the relationship attribute was defined with anything except camelCase.

For example the following works:
```javascript
import { Model, hasMany } from 'ember-cli-mirage';

export default Model.extend({
   blogPosts: hasMany(),
});
```
However this doesn't:

```javascript
import { Model, hasMany } from 'ember-cli-mirage';

export default Model.extend({
   blog_posts: hasMany(),
});
```
The problem occurs because of line 90 in the json-api-serializer.js:

```javascript
let nameForCurrentResource = camelize(names.shift());
```
which causes the included name on my model's serializer, in this case `blog_posts`
to become `blogPosts`

On line 95 and 105 the `nameForCurrentResource` variable is used to grab the relationship off the model:

```javascript
let relationship = model[nameForCurrentResource];
```

This returns `undefined` because the relationship is actually stored under `blog_posts` not `blogPosts`

Unfortunately, I can't change that attribute to be camelCased because my UI and Backend rely on it being underscored.

**Comment by acorncom** [comment]
@seanmhoffman I believe the solution here is to set that at the serializer level, not within your actual model.  More details here: http://www.ember-cli-mirage.com/docs/v0.2.x/upgrading/#x--02-upgrade-guide

**Comment by seanmhoffman** [comment]
@acorncom Thanks for the suggestion. I failed to mention but I did have that include defined within my serializer for that model

```javascript
import { JSONAPISerializer } from 'ember-cli-mirage';

export default JSONAPISerializer.extend({
   includes: ['blog_posts']
});
```
I ended up fixing my issue by just overwriting the `getIncludesForResourceAndPath` method in my serializer to not camelize the names.

**Comment by samselikoff** [comment]
As @acorncom mentioned the idea behind camelizing the properties within Mirage is that, you're writing JS so we should follow standard JS convention of camelizing properties. That way in tests, route handlers, etc you can use `schema.blogPosts` and so on.

If your actual API returns snake-cased names, the idea would be to use some of the [serializer hooks](http://www.ember-cli-mirage.com/docs/v0.2.x/serializers/) to customize the outputted data.

Let me know if you have any more questions!
