### ISSUE TITLE
auto generated relationship methods do not use factories

### ISSUE THREAD

**Issue by H1D** [samselikoff/ember-cli-mirage#913]
I have two models: `pet` and `user`. Factory for `user` has some logic inside `afterCreate()` to created related `pet` objects via `user.createPet()`. It turned out that objects created that way have no attrs  =( looks like `pet` factory wasn`t invlolved.

Twiddle: https://ember-twiddle.com/259b0c0ee941777449274344834416ff?openFiles=mirage.factories.user.js%2C

**Comment by samselikoff** [comment]
Yes - `model.createChild()` is the ORM method, think of it as `store.createRecord` from Ember Data.

To use the factory, use `server.create('pet', { user })` and that will use the factory. Does that make sense?

**Comment by H1D** [comment]
Oh, OK! Actually I ended up using `server.create('pet', { user })`

But it seems to me that `createChild()` should use factory as well

**Comment by samselikoff** [comment]
If it did then how would you just create a new blank child? Again the analog is `store.createRecord`, the ORM needs a base "create related object" method.

**Comment by H1D** [comment]
That's right.
Thanks for clarification
