### ISSUE TITLE
Odd behaviour with ** wildcard

### ISSUE THREAD

**Issue by mjparrott** [samselikoff/ember-cli-mirage#918]
I've been using ember-cli-mirage for request mocking, and came across some odd behaviour. Suppose I have setup 3 endpoints like so:

`
this.get('/api/resource/:id',  function() {
  return 'resource';
});
this.get('/api/resource/:id/subresource', function() {
  return 'subresource'
});
this.get('/api/resource/**', function() {
  return 'wildcard';
});`

If I try calling /api/resource/1 in a test, I"ll get the `wildcard` endpoint. If I call /api/resource/1/subresource, I'll get the `subresource` endpoint. However, if we remove the double wildcard endpoint from our mirage configuration, I'll get the `resource` endpoint and the `subresource` endpoint for the same calls. This is not how I would expect this to work, and would expect to get `resource` and `subresource` in both cases.

**Comment by samselikoff** [comment]
I apologize for not responding to this!

I’m trying to get back on top of issues, so for now I’ll go ahead and close this issue since it's quite old.

If you’re still having trouble, please ping me here or on slack @samselikoff and I’ll be happy to reopen + discuss.
