### ISSUE TITLE
[Feature Request] Customize Nesting and Key Names in Response

### ISSUE THREAD

**Issue by ballPointPenguin** [samselikoff/ember-cli-mirage#92]
As a user of some irregular endpoints, I would like to be able to fully customize how an object is nested and named in the response body of a mirage request that uses factories.

instead of:
```
this.get('/users/current', 'users');
```

something like:
```
this.get('/users/current', function() {
  var user = factory.create('contact', {id: 1});
  var friends = factory.createList('user', 3);

  return {
    "current_user": user,
    "friends": friends,
    "meta": { "other": "stuff" }
  }
});
```

**Comment by samselikoff** [comment]
Hm, so you want the request itself to be able to add data to your db via factories? Today it'd be something like

```js
this.get('/users/current', function(db) {
  var user = db.users.insert({id: 1});
  var friends;
  for (var i=0; i < 2; i++) {
    friends.push(db.friends.insert({user_id: 1}));
  }

  return {
    "current_user": user,
    "friends": friends,
    "meta": { "other": "stuff" }
  }
});
```

Models with relationship support is coming soon, so then this would become something like

```js
this.get('/users/current', function(schema) {
  var user = schema.user.create();
  var friends = user.friends.create([{some: 'attr'}, {some: 'attr'}, {some; 'attr'}]);

  return {
    "current_user": user,
    "friends": friends,
    "meta": { "other": "stuff" }
  }
});
```

Would that solve your problem? Factories are generally used for testing. I'd need to think about exposing them in route handlers. Perhaps some hooks in the model layer may also suffice:

```js
// mirage/models/user.js
export default Mirage.model({
  init: function() {
    // code that gets called on .create
  }
});
```

**Comment by ballPointPenguin** [comment]
Thanks for the response. That is helpful.
I can see now that factories may not belong in the route handlers, especially for non-testing usage.

**Comment by ballPointPenguin** [comment]
I was confounding two separate needs: populating the database and serializing the responses.
When I started with fixtures, these two things were kind of happening together, in config.js.
Now, using factories, I am realizing that populating the data should happen from the test (or a test helper), and serializing the response can happen in config. It is starting to make sense. :smiley:

**Comment by samselikoff** [comment]
exactly :) since, the response (mostly) stays the same. The way to think of it is, your building an Ember app with the expectation that, e.g., `/contacts` returns your backends contacts. Then, in each of your acceptance tests, you change what contacts are in your backend's database. But the fact that `/contacts` returns all the backend's contacts, stays the same. Which is why `config.js` is shared across dev + all tests.

**Comment by samselikoff** [comment]
let me know if this is still an issue :)
