### ISSUE TITLE
Mirage in add-on

### ISSUE THREAD

**Issue by Baukereg** [samselikoff/ember-cli-mirage#920]
Is there a way to make Mirage part of an add-on?

Right now, I have a single add-on containing models and adapters/serializers (anything data related) to be shared among multiple projects using the same server API. But instead of having to install Mirage and add fixtures and factories for each project, I'd like to include it in this add-on.

If not possible, I think it would be an amazing feature.

**Comment by samselikoff** [comment]
There is some work started on this, I am hoping to give some more direction
this weekend when I have a bit more time.

**Comment by Baukereg** [comment]
Cool!

What I've done for now: I've moved the ```mirage/``` folder from the root of the project to the ```app/``` folder of the addon. Than I added a new ```mirage/config.js``` file that looks like this:

```
import MirageConfig from 'my-awesome-addon/mirage/config';
export default MirageConfig;
```

**Comment by Leooo** [comment]
@Baukereg if you do that you will share your Mirage folder of your addon in production, leading to a not needed bigger build unfortunately.
L

**Comment by Baukereg** [comment]
You're right, I'll have to use the treeForAddon hook to funnel it out for production.

**Comment by Leooo** [comment]
@Baukereg any example or lead of how you would do that I'm very interested!

**Comment by Baukereg** [comment]
Just finished it and the ```index.js``` file of the addon now looks like this:

```
const stew = require('broccoli-stew');

module.exports = {
  name: 'my-awesome-addon',
  envConfig: null,
  
  included(app) {
    this.envConfig = this.app.project.config(app.env) || {};
  },
  
  postprocessTree: function(type, tree) {
    if (type === 'js' && !this.envConfig['ember-cli-mirage'].enabled)   {
      return stew.rm(tree, '*/mirage/**/*');
    }
    return tree;
  }
  
};
```

This requires broccoli stew to be installed (```npm install --save broccoli-stew```). I use the mirage settings in the environment config because sometimes we need to deploy a production build with mirage included for testing or a demo.

**Comment by Leooo** [comment]
very cool @Baukereg thanks!

**Comment by knownasilya** [comment]
Does this work, I'm trying to setup in an in-repo engine?

**Comment by Leooo** [comment]
@knownasilya it does, though you can't extend the addon's Mirage routes / models with the ones of your app that way. i.e., you have you use the config of the addon, you cannot add some tweaks for your app.

**Comment by danielleadams** [comment]
+1

**Comment by samselikoff** [comment]
Closing this as we've moved the feature to the Roadmap. Trying to clean up some issues.

Feel free to discuss ad-hoc solutions here until someone has cycles to work on it.

**Comment by Leooo** [comment]
one solution is in https://github.com/samselikoff/ember-cli-mirage/issues/899
