### ISSUE TITLE
Cannot find module 'broccoli-merge-trees'

### ISSUE THREAD

**Issue by ballPointPenguin** [samselikoff/ember-cli-mirage#93]
After 1246cdc46161ca01f54b476c58f8e95ac36b13a6,
ember serve fails with:
Cannot find module 'broccoli-merge-trees'.
(using ember-cli 0.2.3)

Workaround:
```
npm install --save-dev broccoli-merge-trees
npm install --save-dev broccoli-funnel
```

**Comment by samselikoff** [comment]
I believe 68eca7a7ec6034421eb01205df6fcc464e34207a fixed, could you try master?

**Comment by willrax** [comment]
How did you update the addon? `npm install` or` ember install`

**Comment by ballPointPenguin** [comment]
I updated the addon with npm install. Not sure if you can specify github master when doing 'ember install'.

I will try again with latest.

**Comment by Soliah** [comment]
Same problem here. Both in CI and locally.

**Comment by willrax** [comment]
What version of ember-cli are you running?

**Comment by cibernox** [comment]
Same problem here installing from master. I'd say that `broccoli-funnel` & `broccoli-merge-trees` have to be runtime dependencies, not devDependencies.

**Comment by cibernox** [comment]
I've just created a PR for moving those broccoli-plugins to the dependencies section.

**Comment by samselikoff** [comment]
Should be all set now. To install master,

```
npm install --save-dev samselikoff/ember-cli-mirage
ember g ember-cli-mirage
bower install
```
