### ISSUE TITLE
Bump "faker" to 3.1.0

### ISSUE THREAD

**Issue by denzo** [samselikoff/ember-cli-mirage#935]
Currently in `ember-cli-mirage v0.2.3` it is `faker: 3.0.1` and it is missing `faker.random.alphaNumberic` :(

**Comment by samselikoff** [comment]
Yeah, we actually just changed it to `^3.0.0` so you can override it in your host app. Faker seems to be breaking semver so we decided to float it.

So you should be able to look up the version that has `alphaNumeric` and just specify it in your host app's package.json.

Let me know if that doesn't work!

**Comment by xomaczar** [comment]
@samselikoff are you planning on releasing/publishing this

**Comment by samselikoff** [comment]
@xomaczar no we float faker at 3.0 right now since it doesn't seem to comply with Semver, so if you'd like a specific version you can just pin it down in your app's `package.json`. Let me know if that doesn't work.

**Comment by xomaczar** [comment]
@samselikoff the latest published version (@0.2.3) does not float faker - the faker is pinned to 3.0.1

**Comment by samselikoff** [comment]
oh woops, thank you

**Comment by samselikoff** [comment]
@xomaczar do you think you'd have time to help? The process is to update the changelog with line items for the commits, and update package.json. You can see [this commit](https://github.com/samselikoff/ember-cli-mirage/commit/1004fdfe9e8b520aa22658b52a5495f1d4d30f73) for a recent example

**Comment by denzo** [comment]
Should this be reopen then?

**Comment by samselikoff** [comment]
Should be all set https://github.com/samselikoff/ember-cli-mirage/releases/tag/v0.2.4

**Comment by xomaczar** [comment]
@samselikoff - I was about to help but you beat me to it. Thanks again!
