### ISSUE TITLE
Override response for included models

### ISSUE THREAD

**Issue by Leooo** [samselikoff/ember-cli-mirage#937]
Probably not a priority, but still worth mentioning:

I have a case where I want to include the `child` model in the `parent` response, and also override the `child` (included) response to add `links` in its payload.

I found that, instead of just overriding the `serialize` method of the child, I had to:

1) override the `getHashForIncludedResource` method of the parent serializer to use `lookupSerializer=true` in the `serializer.getHashForResource` function call

2) override the `getHashForResource` of the child serializer to add my links.

Pretty indirect, I think at least this line should be changed in the `getHashForIncludedResource` method:
from:
`let [ hash, addToIncludes ] = serializer.getHashForResource(resource);`
to:
`let [ hash, addToIncludes ] = serializer.getHashForResource(resource, false, {}, true);`

**Comment by samselikoff** [comment]
I apologize for not responding to this!

I’m trying to get back on top of issues, so for now I’ll go ahead and close this issue since it's quite old.

If you’re still having trouble, please ping me here or on slack @samselikoff and I’ll be happy to reopen + discuss.
