### ISSUE TITLE
pasthrough() dropping ember-ajax data payload 

### ISSUE THREAD

**Issue by mdbr000** [samselikoff/ember-cli-mirage#939]
ember-cli-mirage v0.2.3
ember-ajax v2.0.1

I've set ember-ajax up as an injected service in one of my routes, and have it returning an ajax request that has a data object with query params supplied to the backend API.  I do not want mirage to handle this request since it is going to an external endpoint on AWS.  So I am using the passthrough() option in mirage/config.js to ignore all requests to this external host, [per the docs](http://www.ember-cli-mirage.com/docs/v0.2.x/configuration/#passthrough).

When mirage is disabled in environment.js, the call works fine and I get data back from AWS.  When mirage is enabled, the request goes out, but the JSON payload containing the query parameters is completely empty (I verified this with tcpdump).

Any idea why this is happening?

Thanks.

**Comment by samselikoff** [comment]
I apologize for not responding to this!

I’m trying to get back on top of issues, so for now I’ll go ahead and close this issue since it's quite old.

If you’re still having trouble, please ping me here or on slack @samselikoff and I’ll be happy to reopen + discuss.
