### ISSUE TITLE
Pretender registry doesn't have handlers on non-base url refresh

### ISSUE THREAD

**Issue by knownasilya** [samselikoff/ember-cli-mirage#942]
Starting at `localhost:4200` mirage works fine. As soon as a you visit a url, then refresh the page, it cannot find the handlers.

Can be tested with https://github.com/loaves-and-fishes/community-groups. Visit `http://localhost:4200/church/sojourn` directly and it wont work.

**Comment by samselikoff** [comment]
@knownasilya sorry for never getting back to you on this... I'll close for now because it's so old but let me know if it's still an issue... I've never heard of this bug before and would expect many others would have experienced it too.
