### ISSUE TITLE
Maximum call stack exceeded

### ISSUE THREAD

**Issue by simonihmig** [samselikoff/ember-cli-mirage#943]
I have the following model relationship defined, including their inverse counterpart:

**product** -- hasMany --> **product-association** -- hasMany --> **product**

This is how the database is seeded in one of my tests:

      let associatedProducts = server.createList('product', 4);
      let association = server.create('product-association', {
        associatedObjects: associatedProducts
      });
      let product = server.create('product', {
        associations: [association]
      });

On the last `create` statement for `product` I get an "Maximum call stack exceeded" exception. Judging from the call stack the `_setupRelationships` method is called with infinite recursion. At some point it is called again for the `product` itself that is just to be created and which started this chain.

Interestingly this happened after upgrading from 0.2.0-beta.8 to 0.2.4, so it was working very well with the prerelease version!

**Comment by designblooz** [comment]
Can you paste your `product` and `product-association` mirage models?

**Comment by simonihmig** [comment]
Sure...

product:
```js
export default Model.extend({
  associations: hasMany('product-association', { inverse: 'owner' }),
  associatedTo: belongsTo('product-association', { inverse: 'associatedObjects' })
});
```

product-association:
```js
export default Model.extend({
  owner: belongsTo('product', { inverse: 'associations' }),
  associatedObjects: hasMany('product', { inverse: 'associatedTo' })
});
```

**Comment by designblooz** [comment]
try

```javascript
let product = server.create('product');
let association = server.create('product-association', {
  ownerId: product.id
});
let associatedProducts = server.createList('product', 4, {
  associatedToId: association.id
});
```

**Comment by simonihmig** [comment]
@designblooz Indeed that "fixed" the problem! 

This is still a workaround for a bug, which should be fixed some time, right? Or at least be documented in some way. Will keep the issue open then...

**Comment by designblooz** [comment]
I'm not sure if it's a bug or intended. Since, from the server side has many associations are linked through foreign key of the model that has hasMany association.

**Comment by mariogintili** [comment]
I'm getting the same error in a setup where

```js
// models/user.js
groupUsers: hasMany('groupUser')
```

```js
// models/group-user.js
  user:   belongsTo('user'),
  group:  belongsTo('group'),
  wallet: belongsTo('groupUserWallet')
```

```js
// models/group.js
groupUsers: hasMany('groupUser')
```

```js
// models/group-user-wallet.js
groupUser:   belongsTo('groupUser'),
```

**Comment by samselikoff** [comment]
One to one relationships are not supported in the current ORM. I have them working in the new one, but still have some work to do before I can push it.

I will move it to a public branch soon so folks can start testing it out.

**Comment by simonihmig** [comment]
@samselikoff Yeah, I know about this limitation. You are probably refering to @mariogintili's case. But in my case there is no one-to-one (see first comment). It is kind of reflexive, but just indirectly (a product has associated products via the product-association model).

It seems `_setupRelationships` is following the associations recursively, and does not stop recursion when visiting an already visited model. Here starting from the origin `product` via the `association` to the `associatedProducts` and back again via the inverse relationship until it reaches the first `product` again where the cycle starts from the beginning. Shouldn't it check for such cycles to stop recursion? 

At least it seem strange that the order of instantiation makes a difference (see https://github.com/samselikoff/ember-cli-mirage/issues/943#issue-189470295 vs. https://github.com/samselikoff/ember-cli-mirage/issues/943#issuecomment-260801581)

Obviously these are just wild guesses, as I have not been digging to much into the code, hope you can assess better what is going on...

**Comment by mariogintili** [comment]
@samselikoff where can we add an assertion to set my case to fail a bit more explictly? and could you push that branch 😄

**Comment by samselikoff** [comment]
@simonihmig I know it's a bummer it's not working right now- I've tried to stay away from individual cases because I want to focus on the new code, and then comb through all the issues to make sure we have everything supported.

@mariogintili I'll try to get it into a state that can be used/tested

**Comment by simonihmig** [comment]
Ok, got it. You probably did not anticipate having to create a kind of full fledged ORM when you started this. Your effort on this is highly appreciated though! :)

**Comment by mariogintili** [comment]
@samselikoff I'm happy to develop on it, my team needs it asap 😄 could you open an issue with a spec/guidelines? I'm new-ish to the project

**Comment by mariogintili** [comment]
@samselikoff hello :) issue still affecting us, any updates on this?

**Comment by mariogintili** [comment]
Just going to assume this is not going to be solved in the foreseeable future

**Comment by samselikoff** [comment]
@mariogintili I would avoid recursive and many-to-many relationships for now. I have them working in a new branch but there's still more work to be done before we can start testing it out.

**Comment by mariogintili** [comment]
@samselikoff we can't avoid them. We've decided to drop ember-cli-mirage altogether from my project and looking at using it in ~3 months time 😄

**Comment by samselikoff** [comment]
Sure thing. Just so you know you can usually hard-code your way around missing features in Mirage by accessing the underlying database. You don't have to use the ORM. For example I did this recently in a project to add an endpoint to support polymorphic data, something like this

```js
import Ember from 'ember';
import ApplicationSerialiser from './application';
import { Collection } from 'ember-cli-mirage';

const { pluralize, dasherize } = Ember.String;
const { isArray } = Ember;

export default ApplicationSerialiser.extend({

  serialize(response) {
    let json = ApplicationSerialiser.prototype.serialize.apply(this, arguments);
    json.included = [];

    let posts = response instanceof Collection ? response.models : [ response ];
    posts.forEach(post => {
      this.addPostableToJson(json, post);
    });

    return json;
  },

  addPostableToJson(json, post) {
    let postable = this.getPostableForPost(post);
    json.included.push(this.resourceObjectForPostable(postable));

    if (isArray(json.data)) {
      json.data.findBy('id', post.id).relationships = this.relationshipForPostable(postable);
    } else {
      json.data.relationships = this.relationshipForPostable(postable);
    }
  },

  getPostableForPost(post) {
    return post._schema[pluralize(post.postType)].find(post.postableId);
  },

  resourceObjectForPostable(postable) {
    return {
      id: postable.id,
      type: dasherize(postable.modelName),
      attributes: Object.keys(postable.attrs).reduce((obj, key) => {
        obj[dasherize(key)] = postable.attrs[key];
        return obj;
      }, {})
    };
  },

  relationshipForPostable(postable) {
    return {
      postable: {
        data: {
          id: postable.id,
          type: dasherize(postable.modelName)
        }
      }
    };
  }

});
```

then

```js
let note = server.create('note');
server.create('post', {
  postType: 'note',
  publishedAt: '2016-10-28',
  postableId: note.id
});
```

Just wanted to point out Mirage's escape hatches in case the orm or a serialize doesn't support a particular feautre.

**Comment by mariogintili** [comment]
@samselikoff that's a valid approach, however I found as a user that maintaining a hybrid setup across endpoints(some manual payloads/ORM) proved harder to maintain than my actual application code

**Comment by samselikoff** [comment]
With 0.3 recursive relationships now work. The only feature missing from Mirage's ORM is polymorphic relationship support, which I'll be working on soon.

@mariogintili let me know if you run into any issues.
