### ISSUE TITLE
Serializer: specifying `attrs` filters out attributes of included records

### ISSUE THREAD

**Issue by deepflame** [samselikoff/ember-cli-mirage#944]
I have a `person` model which includes a `company`. When we serialize the person, the attrs of the company are all `undefined`.

The reason is that the attrs of the person are used for the company as well. So when I remove the `attrs` property everything is fine.

**Comment by acorncom** [comment]
@deepflame any chance you can setup your problem in a Twiddle using this template? https://ember-twiddle.com/eedfd390d8394d54d5bfd0ed988a5d0f  These types of issues are far easier to look at if there's a good reproduction available ...

**Comment by deepflame** [comment]
Hi @acorncom , thanks for your reply.

Here is the Twiddle you were asking for:
https://ember-twiddle.com/6c72188c65dee983d107d6752e3510b6?openFiles=mirage.serializers.user.js%2C

Just remove the comment from the `attrs` in the user-serializer and you will see that the posts loose their title...

Hope this helps.

**Comment by acorncom** [comment]
Hi @deepflame yep, that does help. Any chance you'd want to send in a PR? Folks are pretty swamped on this end (as you can tell by the issue count :grinning:) so this may not get much attention for a while without it ...

**Comment by deepflame** [comment]
Sure, here you go @acorncom :) #950

**Comment by samselikoff** [comment]
https://github.com/samselikoff/ember-cli-mirage/pull/950 closes
