### ISSUE TITLE
server.create extend array doesn't have expected functionality

### ISSUE THREAD

**Issue by seawatts** [samselikoff/ember-cli-mirage#95]
Repo steps:
Using versions: 
ember-cli-mirage: 0.0.24
ember-cli: 0.2.3
ember: 1.11.1
ndoe: 0.12.2

Config config.js
```js
export default function() {
  this.get('/contents');
};
```

Factory - contents.js 
```js
import Mirage from 'ember-cli-mirage';

export default Mirage.Factory.extend({
  myArray: [1, 2, 3]
});
```

Acceptance test - contents-test.js
```js
test('visiting /contents shows content', function(assert) {
  assert.expect(1);
  var contents = server.create('contents', {
    myArray : [4]
  });

  visit('/contents');

  andThen(function() {
    assert.equal(currentURL(), '/contents');
    var arrayElement = find('.content .my-array');
    assert.equal(arrayElement.length, 1);
```

Result:
`assert.equal(arrayElement.length, 1);` failed `arrayElement.length === 3`

It looks like you are using jquery `.extend` method here:
https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/server.js#L108

However, I just found this bug that it does not replace an array object if it is extended. https://forum.jquery.com/topic/jquery-extend-modifies-but-not-replaces-array-properties-on-deep-copy

I'm not sure if deep extend would help `.extend(true, a, b) ` would help. I haven't tested it out.
http://api.jquery.com/jquery.extend/#jQuery-extend-deep-target-object1-objectN

May want to use lodash to get the intended functionality.
https://lodash.com/docs#assign

**Comment by seawatts** [comment]
I'm trying to create a PR for this and run the tests however it takes forever to run `npm test` is the intended because you are using `ember try`?

**Comment by samselikoff** [comment]
Thanks so much for writing this up! The jquery extend call is actually [here](https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/factory.js#L25). I'm not sure why the array isn't being overwritten, I'll have to look into it. `npm test` shouldn't take that long, either.

**Comment by samselikoff** [comment]
#96 closes
