### ISSUE TITLE
'server' is not defined

### ISSUE THREAD

**Issue by imhuytq** [samselikoff/ember-cli-mirage#953]
I writing an acceptance test and got an error:

> acceptance/redirect-test.js: line 7, col 3, 'server' is not defined.

`acceptance/redirect-test.js file`

```javascript
import { test } from 'qunit';
import moduleForAcceptance from 'websizy-dashboard/tests/helpers/module-for-acceptance';

moduleForAcceptance('Acceptance | redirect');

test('should redirect to website index', function(assert) {
  server.createList('website', 1);

  visit('/websites');

  andThen(function() {
    assert.equal(currentRouteName(), 'website.index');
  });
});

```

Ember: **2.9.1**
ember-cli: **2.9.1**
ember-cli-mirage: **0.2.4**
node: **6.8.0**
phantomjs: **2.1.1**

**Comment by dustinfarris** [comment]
is the error coming from the acceptance test or from JSHint?

**Comment by imhuytq** [comment]
That is JSHint Error

**Comment by dustinfarris** [comment]
possible you did not install with `ember install ember-cli-mirage` which would mean the default blueprint didn't run which adds "server" to tests/.jshintrc

You can do this yourself, or you can run:

```
ember generate ember-cli-mirage
```

**Comment by jonblack** [comment]
Just came across this error as well. Adding `server` to `"predef"` in `tests/.jshintrc` resolves it. Running `ember generate ember-cli-mirage` did not add this, so perhaps something is broken?

**Comment by imhuytq** [comment]
@dustinfarris I was use `ember install ember-cli-mirage`, but it did not add `server` to "predef" in `tests/.jshintrc`.

**Comment by dustinfarris** [comment]
@imhuytq weird, this might be broken then.  can you reopen the issue?

**Comment by albertpak** [comment]
Ran into this issue this week - generated an acceptance test, tried to use `server.create('user')` and got an error that `server is not defined`, checked .jshintrc and `"server"` is in it

**Comment by albertpak** [comment]
I've even compared it to another app (2.3.4) and I don't see anything different in it, as to why the `server` wouldn't be available during tests.

**Comment by albertpak** [comment]
anyone else run into this issue?

**Comment by taheilo** [comment]
I'm also having this issue, on Ember 2.10.0. I'm using `eslint` however. 

tests/.eslintrc.js
```
module.exports = {
  root: true,
  extends: '../.eslintrc.js',
  globals: {
    'server': true
  },
  env: {
    'embertest': true,
    'es6': true
  }
};
```

**Comment by imhuytq** [comment]
@albertpak I'm also having this issue.

**Comment by taheilo** [comment]
Incase it could help debugging, here is my full package file

```
    "broccoli-asset-rev": "^2.4.5",
    "ember-ajax": "^2.4.1",
    "ember-cli": "2.10.0",
    "ember-cli-app-version": "^2.0.0",
    "ember-cli-babel": "^5.1.10",
    "ember-cli-dependency-checker": "^1.3.0",
    "ember-cli-eslint": "3.0.0",
    "ember-cli-htmlbars": "^1.0.10",
    "ember-cli-htmlbars-inline-precompile": "^0.3.3",
    "ember-cli-inject-live-reload": "^1.4.1",
    "ember-cli-mirage": "0.2.4",
    "ember-cli-page-object": "1.7.0",
    "ember-cli-qunit": "^3.0.1",
    "ember-cli-release": "^0.2.9",
    "ember-cli-sass": "^5.5.2",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-test-loader": "^1.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-cp-validations": "3.1.3",
    "ember-data": "^2.10.0",
    "ember-export-application-global": "^1.0.5",
    "ember-intl": "2.13.1",
    "ember-intl-cp-validations": "2.3.1",
    "ember-keyboard": "2.1.3",
    "ember-load-initializers": "^0.5.1",
    "ember-local-storage": "1.3.1",
    "ember-radio-button": "1.0.7",
    "ember-resolver": "^2.0.3",
    "ember-simple-auth": "1.1.0",
    "ember-svg-jar": "0.9.3",
    "ember-wormhole": "0.4.1",
    "eslint-plugin-ember-suave": "^1.0.0",
    "liquid-fire": "0.27.0",
    "loader.js": "^4.0.10",
    "phantomjs-prebuilt": "^2.1.14"
```

**Comment by albertpak** [comment]
mine looks pretty much the same as mine...I don't understand what could be happening with a package that started disabling `server`...my only thought that it was related to 2.10 release...but i'm running 2.5.x  and still running into that issue

**Comment by taheilo** [comment]
@albertpak I'm not quite sure what I did since I was on a dirty branch, but I suspect that somewhere the config setting for mirage changed from defaulting to true for testing env to false. After setting Mirage to true for the test env, the server error went away.

Again, I'm not sure this is the actual solution since I had tried alot of stuff to fix this, but give it a try.

**Comment by albertpak** [comment]
@taheilo in your app, are you using a `--proxy` option in your app?

**Comment by albertpak** [comment]
@taheilo and if you don't mind sharing - what snippet did you add to activate the mirage server on test environment? I tried adding code snippet below to `if (environment === 'test') {` section in `config/environment.js` file:

```ENV['ember-cli-mirage'] = {
      enabled: true,
    };```

**Comment by taheilo** [comment]
@albertpak thats it. And no, im not using `--proxy`.

**Comment by albertpak** [comment]
Figured it out - i had a system wide setting for the environment to be set to development mode, so the app never went into `test` environment 👊

**Comment by taheilo** [comment]
Oh lol :) Good that you got it solved.

**Comment by imhuytq** [comment]
Ember-CLI use [fs-extra.outputFile](https://github.com/jprichardson/node-fs-extra/blob/1.x/lib/output/index.js#L5) function for insertIntoFile function.
I think it is the source of this problem.

**Comment by albertpak** [comment]
That's weird...not to familiar with that function, but loading of mirage should be separate from that. Check in your `config/environment.js` that you're enabling `mirage` server in `test` environment. Also, if you run your Ember app with `proxy` option, Mirage might not be enabled

**Comment by acorncom** [comment]
Sounds like this isn't a Mirage issue, so I'll close it for now

**Comment by backspace** [comment]
This happened to me with a fresh application recently. To test it out, I tried making a new application and running `ember install ember-cli-mirage` with these Ember CLI versions:
* 2.10
* 2.9
* 2.8
* 2.7
* 2.3

In none of them did the correct lines get added to the `.jshintrc` files. It’s confusing because surely this did work at some point, so maybe it’s some other dependency at fault?

It was easy enough for me to fix but I find it concerning because Mirage is used in the guides and it might be confusing for newcomers.

**Comment by imhuytq** [comment]
@backspace Ember-CLI use [fs-extra.outputFile](https://github.com/jprichardson/node-fs-extra/blob/1.x/lib/output/index.js#L5) function for insertIntoFile function.
I think it is the original of this problem.

**Comment by backspace** [comment]
hmm, do you have any idea of how we could use that understanding to fix it, @imhuytq?

**Comment by imhuytq** [comment]
I was test [fs-extra.outputFile](https://github.com/jprichardson/node-fs-extra/blob/1.x/lib/output/index.js#L5) function on new project (not Ember) and work correctly.
But on Ember, [fs.exists (line 12) callback in fs-extra.outputFile](https://github.com/jprichardson/node-fs-extra/blob/1.x/lib/output/index.js#L12) function was not fire.
That's strange.
