### ISSUE TITLE
ember-cli-mirage-nested

### ISSUE THREAD

**Issue by Leooo** [samselikoff/ember-cli-mirage#962]
@samselikoff, are you ok with an addon completing Mirage such as this one:

https://github.com/britishgas-engineering/ember-cli-mirage-nested

?

Thanks,

L

**Comment by samselikoff** [comment]
I think it's great to experiment. I am hoping the association helper in #880 plus traits/afterCreate will give us a good story for creating object graphs.

**Comment by hbrysiewicz** [comment]
Issue and related addon are inactive.
