### ISSUE TITLE
no route defined to handle this request

### ISSUE THREAD

**Issue by FrancoB411** [samselikoff/ember-cli-mirage#970]
To Manually Recreate the behavior

In the browser:
Visit /sales-quotes. You should see a list of items.
Click the first item. You should transition to /sales-quote/1
Open dev tools
Refresh the page. In console you should see the following error: "Mirage: Your Ember app tried to GET '/sales-quotes/1', but there was no route defined to handle this request."
Remove namespace from adapters/application.js and mirage/config.js
Do the above steps again, and there should be no error.

In the test environment, the error persists in both namespace and non namespace conditions.

Here is a repo with an app, and tests that recreate the behavior
https://github.com/FrancoB411/mirage-server-issue

Thanks!

**Comment by alenm** [comment]
I am able to recreate the situation with the files provided. The error gets generated when I
• Click on the browser refresh button 
• Copy the URL '/sales-quote/1' and paste it into a new tab

I tried an older version of mirage `"ember-cli-mirage": "0.1.13` and I created a similar project layout to to yours. I was not able to recreate the error in 0.1.13. 

Too much has changed from 0.1.13 to 0.2.4 to suggest a downgrade.

**Comment by FrancoB411** [comment]
Update:

In `mirage/config` I added the forward slash before `this.namespace = 'api/v2/';` changing it to
`this.namespace = '/api/v2/';` and now the browser tests.

However `ember test` still return a 404 for the `sales-quote/1` route with the following stack trace:

```
not ok 30 PhantomJS 2.1 - Acceptance | happy path: visiting sales-quote/1 directly? Problem
    ---
        actual: >
            false
        expected: >
            true
        stack: >
            exception@http://localhost:7357/assets/test-support.js:7334:49
            adapterDispatch@http://localhost:7357/assets/vendor.js:49018:22
            dispatchError@http://localhost:7357/assets/vendor.js:27439:23
            onerrorDefault@http://localhost:7357/assets/vendor.js:40942:32
            trigger@http://localhost:7357/assets/vendor.js:68386:17
            http://localhost:7357/assets/vendor.js:69270:26
            invoke@http://localhost:7357/assets/vendor.js:10892:18
            flush@http://localhost:7357/assets/vendor.js:10960:15
            flush@http://localhost:7357/assets/vendor.js:11084:20
            end@http://localhost:7357/assets/vendor.js:11154:28
            run@http://localhost:7357/assets/vendor.js:11277:19
            join@http://localhost:7357/assets/vendor.js:11299:28
            join@http://localhost:7357/assets/vendor.js:32109:33
            error@http://localhost:7357/assets/vendor.js:148009:37
            fire@http://localhost:7357/assets/vendor.js:3637:36
            fireWith@http://localhost:7357/assets/vendor.js:3767:11
            done@http://localhost:7357/assets/vendor.js:9576:24
            http://localhost:7357/assets/vendor.js:9816:17
            http://localhost:7357/assets/vendor.js:71711:17
            dispatchEvent@http://localhost:7357/assets/vendor.js:71755:28
            _readyStateChange@http://localhost:7357/assets/vendor.js:71955:27
            _setResponseBody@http://localhost:7357/assets/vendor.js:72019:31
            respond@http://localhost:7357/assets/vendor.js:72040:28
            http://localhost:7357/assets/vendor.js:72452:26
            resolve@http://localhost:7357/assets/vendor.js:72501:21
            http://localhost:7357/assets/vendor.js:72492:28
        message: >
            Error: Ember Data Request GET /api/v2/sales-quotes/1 returned a 404
            Payload (application/json)
            [object Object]
        Log: |
            { type: 'warn',
              text: '\'You created a second Pretender instance while there was already one running. Running two Pretender servers at once will lead
 to unexpected results and will be removed entirely in a future major version.Please call .shutdown() on your instances when you no longer need them to respond.\'\n' }
            { type: 'error',
              text: '\'Error while processing route: sales-quote\' \'Ember Data Request GET /api/v2/sales-quotes/1 returned a 404\\nPayload (applic
ation/json)\\n[object Object]\'\n' }
            { type: 'error', text: 'null\n' }
            { type: 'error', text: 'null\n' }
```

**Comment by alenm** [comment]
**Before**
I had the namespace to be just `this.namespace = 'api';`

**After**
But after these suggestions I changed it to `this.namespace = '/api';`

```
// mirage/config.js
export default function() {
  this.namespace = '/api';
  
  this.get('/users');
  this.get('/users/:id', 'user');
}

// adapters/application.js
import DS from 'ember-data';

export default DS.JSONAPIAdapter.extend({
  namespace: 'api';
});
```

Now everything is working but I don't know why.

**Comment by FrancoB411** [comment]
@lancedikson

Yeah, I had tried the leading slash in the config, and it got the browser working. 

But `localhost:4200/tests` still reports a 404 in the browser, and `ember test` offers the double pretender error I included above.

Have you tried running it with an acceptance test?

**Comment by lancedikson** [comment]
@FrancoB411, it was a similar situation for me, but:
- `localhost:4200/tests` said that everything is ok;
- `ember test` said that there is no that route `/api/v1/products`.

So, I don't know why, but additional slashes made it works :)

**Comment by oskarrough** [comment]
Just to confirm, I'm seeing the same behavior in 0.3 beta.

If the slash IS required, let's add it to the guides? But I assume it shouldn't be.

**Comment by lancedikson** [comment]
@samselikoff, take a look, please :)

**Comment by samselikoff** [comment]
Latest 0.3 release should have more "robust" support (so trailing slashes/no slashes should all work).

Also if `ember test` is warning that there's a double pretender server instance, make sure to add `server.shutdown()` to your afterEach. (This is done automatically in Acceptance tests). See https://github.com/samselikoff/ember-cli-mirage/issues/915 for more info.
