### ISSUE TITLE
Fundraise for a logo

### ISSUE THREAD

**Issue by samselikoff** [samselikoff/ember-cli-mirage#978]
Designer [Lindsey Wilson](https://twitter.com/lindsey_io) of [Tomster fame](https://lindsey.io/portfolio/) tweeted that she had some availability, so I reached out to her about creating a logo and color scheme for Mirage.

The quote is $1,000, and I thought we could put together a fundraising campaign and reach out to Mirage's users for help. I think with its reach this shouldn't be terribly hard to hit, and it gives folks a way to give back to the library, as most of Mirage's development has been pro bono.

Does anyone have experience running crowdfunding or fundraising campaigns like this? Looking for someone to take the lead on this! I'd really appreciate it.

**Comment by abuiles** [comment]
@samselikoff maybe link to your paypal or square cash?

**Comment by samselikoff** [comment]
@abuiles is there a way to track total amount with that? I could do it but would prefer it be visible.

**Comment by samselikoff** [comment]
https://www.indiegogo.com/projects/ember-cli-mirage-logo-design/x/9849671#/
