### ISSUE TITLE
Acceptance test fails in PhantomJS

### ISSUE THREAD

**Issue by oskarrough** [samselikoff/ember-cli-mirage#979]
Hi, using mirage 0.3.0 beta 4 with ember-cli 2.10.0.

My test pass in Chrome but not in PhantomJS.  This is my acceptance test:

```js
import { test } from 'qunit';
import moduleForAcceptance from 'my-app/tests/helpers/module-for-acceptance';

moduleForAcceptance('Acceptance | shows');

test('I can view the shows', function(assert) {
	assert.expect(2);
	let shows = server.createList('show', 10, 'timestamps');
	visit('/shows');
	andThen(function() {
		assert.equal(currentURL(), '/shows');
		assert.equal(find('.ListGroup-item:first h3').text().trim(), shows[0].attrs.title, 'the data matches mirage');
	});
});
```

It seems to be the `createList` method that causes the error, which looks like this:

```
Acceptance | shows: I can view the shows
    ✘ Died on test #1 http://localhost:7357/assets/tests.js:7:18
    exports@http://localhost:7357/assets/vendor.js:140:37
    requireModule@http://localhost:7357/assets/vendor.js:32:25
    require@http://localhost:7357/assets/test-support.js:7107:14
    loadModules@http://localhost:7357/assets/test-support.js:7099:21
    load@http://localhost:7357/assets/test-support.js:7129:33
    http://localhost:7357/assets/test-support.js:7013:22: undefined is not a constructor (evaluating 'Object.assign({}, modelClass.be
longsToAssociations, modelClass.hasManyAssociations)')
        associationsFor@http://localhost:7357/assets/vendor.js:131413:29
        http://localhost:7357/assets/vendor.js:129579:63
        inverse@http://localhost:7357/assets/vendor.js:129591:13
        _disassociateFromHasManyInverses@http://localhost:7357/assets/vendor.js:130926:42
        _disassociateFromOldInverses@http://localhost:7357/assets/vendor.js:130913:48
        http://localhost:7357/assets/vendor.js:130904:46
        forEach@[native code]
        _saveHasManyAssociations@http://localhost:7357/assets/vendor.js:130903:78
        _saveAssociations@http://localhost:7357/assets/vendor.js:130885:38
        save@http://localhost:7357/assets/vendor.js:130532:31
        create@http://localhost:7357/assets/vendor.js:131311:45
        create@http://localhost:7357/assets/vendor.js:131248:33
        create@http://localhost:7357/assets/vendor.js:133965:44
        createList@http://localhost:7357/assets/vendor.js:134002:38
        http://localhost:7357/assets/tests.js:10:32
        runTest@http://localhost:7357/assets/test-support.js:3494:34
        run@http://localhost:7357/assets/test-support.js:3480:13
        http://localhost:7357/assets/test-support.js:3654:15
        process@http://localhost:7357/assets/test-support.js:4716:26
        begin@http://localhost:7357/assets/test-support.js:4699:11
        http://localhost:7357/assets/test-support.js:4660:11
```

My `mirage/models/show.js` has a belongsTo defined with a hasMany on the other model. If I can provide any more information let me know.

**Comment by samselikoff** [comment]
I think this is a Phantom issue, try using Phantom version 2.x

**Comment by samselikoff** [comment]
And thank you for trying out the beta! I really appreciate the help

**Comment by oskarrough** [comment]
First time using Mirage and the benefits are now obvious, so thank you!

I'm using Phantomjs 2.1.1. I tried to debug a bit more and now the culprit seems to be one of my two models.

```js
import { Model, hasMany } from 'ember-cli-mirage';
export default Model.extend({
	videos: hasMany()
});
```

If I remove the hasMany relationship the test passes again.

**Comment by samselikoff** [comment]
Is there an error? What is the response to the web request, and what do you expect it to be?

**Comment by oskarrough** [comment]
The error appears only through my acceptance test in Phantomjs. Pasted the error in the issue above. There are some hasMany methods hidden in there...

In the front-end (and chrome ci tests) the relationships and mirage all work.

**Comment by samselikoff** [comment]
Ok so if it's still that error it's `Object.assign` is not a function, it's because of the version of JS that Phantom is using.

I really don't like PHantom because it uses an outdated version of V8, all hte major browsers support Object.Assign right now (I actually thought this was transpiled by Babel). In the meantime can you switch your test runner to Chrome only? Though I do think we should change this to just use `_assign` from Lodash, since so many people do use Phantom.

Anyway, that's what's going on and I can update it when I get back to my computer.

**Comment by oskarrough** [comment]
Aha, that makes sense in a JavaScript kind-of way. As long as Phantom is enabled by default in ember-cli I assume more people will run into it.

Also https://github.com/ember-cli/rfcs/pull/86

**Comment by dustinfarris** [comment]
If you really want to use Phantom you can also enable babel polyfill in your ember-cli-build.

**Comment by andrewmtoy** [comment]
Thanks, this was helpful.  I'm going to try switching to Firefox from phantom.

**Comment by samselikoff** [comment]
d6373945220bac85a23e570fc9ce23af0661fcf0 closes
