### ISSUE TITLE
Extending a Factory does not wire extended factory to Parents Endpoints

### ISSUE THREAD

**Issue by ezpuzz** [samselikoff/ember-cli-mirage#98]
I have a factory for a model `session` and I extend the factory to `google-session` as in the human/man example in the wiki.

In a test I `server.create('session')` and `server.create('google-session')`  then I expect a `GET` to  `/sessions` would return two sessions.  In my experience only the `session` is  returned and not the `google-session`.  Is this intended?

I want to be able to use the `google-session` to override just certain attributes of a regular `session` but still return it as a `session` and have `server.create` recognize it is just a variety of `session`.

**Comment by samselikoff** [comment]
This is really a task for traits, which haven't landed yet :( 

Unfortunately right now the model created is tied to the filename of the factory. This will obviously change, and maybe I can prioritize it over the serializer stuff, but for now I think you'll just have to put up with some repetition and use a single factory.

**Comment by ezpuzz** [comment]
alright, thanks for the response.  that's what i figured and wound up doing for my use case, just overriding it in the tests as needed.  so the extendable factories are really only for polymorphic models with independent endpoints.  thanks.
