### ISSUE TITLE
support ember-network fetch mocking

### ISSUE THREAD

**Issue by izelnakri** [samselikoff/ember-cli-mirage#983]
This might not be common but I still believe an essential feature. Mirage/pretender should support fetch() requests. 

I have one component that doest fetch request to a model endpoint however the endpoint is dynamic sometimes it is the same as the ```person``` model endpoint

I have this:
```js
// in mirage/config.js
this.get('/people', ({people}, request) => {
    const params = request.queryParams;
    if (params.query) {
      return peopleSearch(people.all());
    } 
     
    return people.all();
});
```

I have this call in a components:
```js
// in components/foo.js

export default Component.extend({
    searchPath: computed('attribute', function() {
        const entityType = this.get('entityType');

        if (entityType === 'person') {
            return '/people';
        } else {
            return '/application';
        }
    },
    keyUp() {
        let query = $(event.target).val();

        if (query.length > 0) {
            // IMPORTANT PART:
            fetch(config.apiHost + `${this.get('searchPath')}?query=${query}`)
            // I do more with it 
        }
    }
});
```

this fetch makes a request to the same endpoint as Ember 'person' model adapter. It would be great if we can make mirage support fetch calls. Currently I have to mock this with something like: https://github.com/wheresrhys/fetch-mock and duplicate the ember mirage code/logic.

P.S I will always use fetch instead of $.get() because that is what fastboot supports.

**Comment by morhook** [comment]
I think this ticket is related with how pretender could do it https://github.com/pretenderjs/pretender/issues/60

**Comment by samselikoff** [comment]
After some quick reading it looks like @stefanpenner recommends `ember-fetch`, could somebody verify this?

If so I think that should be the solution, `ember-fetch` polyfills `fetch` but never falls back to default (as of today), so Pretender should always work.

**Comment by izelnakri** [comment]
Yes, this is indeed the case, I think ```ember-network``` will get replaced by ```ember-fetch```. ```ember-network``` also has caveats regarding its then/catch promise handling.

**Comment by lypborges** [comment]
I have a similar use case here, it's a dashboard component that uses `ember-fetch` to load data. Is there any way to help with this or should we wait for pretender to be updated?

**Comment by 0xadada** [comment]
so i'm working on an app where we've
1) removed jQuery as a dependency
2) migrated to `ember-fetch` as a replacement for `$.ajax` / `XMLHTTPRequest`
  2a) Configured `fastboot` to use `node-fetch`
3) configured Ember Data to use `adapter-fetch` to retrieve data using `fetch`

the last piece of the puzzle is getting mirage to work, and it seems like pretender would need to support `fetch` for this to work?

**Comment by rwjblue** [comment]
`ember-fetch` is currently _always_ a polyfill and actually using XHR under the hood. Eventually we would like to fix that, but for that to work we need a "FakeFetch" implementation for `pretender`.

**Comment by 0xadada** [comment]
@rwjblue to rephrase: so `ember-fetch` _currently never_ uses native fetch, and always uses XHR. To get mirage to work, we need `pretender` to use the the same "FakeFetch"™ that `ember-fetch` uses?

**Comment by rwjblue** [comment]
Partially correct, ember-fetch never uses native fetch and instead uses `XmlHttpRequest` which mirage mocks (via pretender). 

Mirage should already work with this setup...

**Comment by hbrysiewicz** [comment]
Feature requests are being moved to Canny.
[View this feature request on Canny](https://ember-cli-mirage.canny.io/feature-requests/p/support-ember-network-fetch-mocking)

**Comment by williamweckl** [comment]
@0xadada I've done pretty much what you did, but still not able to make it work with mirage.

Im using [ember-cli-fastboot-testing](https://github.com/embermap/ember-cli-fastboot-testing) and looks like is always trying yo fetch using node-fetch, so pretender is intercepting my requests.

Any clues of what I'm doing wrong?

**Comment by samselikoff** [comment]
@williamweckl I think it'd be easier to help if you opened a new issue with some more info/a reproduction

**Comment by williamweckl** [comment]
@samselikoff Actually I'm a little lost. Just want to test my ember app with fastboot but I'm not able to mock any requests to my API. Maybe it's not a mirage issue, I just hope that someone already did that and can show me the path to do it.

As you already saw, there is an issue at [ember-cli-fastboot-testing](https://github.com/embermap/ember-cli-fastboot-testing/issues/2).
