### ISSUE TITLE
Request: Ability to pick response code inside route handler callback.

### ISSUE THREAD

**Issue by ltegman** [samselikoff/ember-cli-mirage#985]
Right now I use mirage not only in test but frequently in dev. The issue I'm running into is that if I have a route handler that looks like this for logging in:
```js
this.get('/login', (schema, request) => {
  const {username, password} = request;

  if (username === 'username' && password === 'password') {
    return {
      token: 'this is not a real token'
    };
  }

  return {
    error: 'not a valid login'
  };
});
```
It will only ever send a 200 response. In test I'd just override this handler for the test that needs an error, but in dev that involves changing the config and restarting the app to test error code responses. Would you ever be open to adding a mechanism for changing the error code from within the handler? That way I could check for a certain input and conditionally provide different response codes from the same handler.

**Comment by samselikoff** [comment]
Yes, this is possible with Mirage.Response. Check out the [docs here](http://www.ember-cli-mirage.com/docs/v0.2.x/route-handlers/#function-handler) and search for "Mirage.Response" for an example.

This tells me that maybe we should add this class to the sidebar! Let me know if you have any more questions.

**Comment by ltegman** [comment]
Thanks for pointing me in the right direction!
