### ISSUE TITLE
Release 0.2.5

### ISSUE THREAD

**Issue by samselikoff** [samselikoff/ember-cli-mirage#988]
Depends on #987.

- [x] Update Changelog. Go through commits from 0.2.4 and write short summaries of what's changed
- [x] Update package.json version

**Comment by renpinto** [comment]
@samselikoff Is it okay if I release 0.2.5 tonight by updating the change log with #987 issue and then go through the rest of the commits & write logs in couple of days?

**Comment by samselikoff** [comment]
eb476d5d9d00d65e3194d2dfa18dd848db4571eb closes

**Comment by samselikoff** [comment]
Went ahead and took care of it :)

**Comment by renpinto** [comment]
awesome.. Thank you very much... :)
