### ISSUE TITLE
Documented association() helper is unreleased

### ISSUE THREAD

**Issue by courajs** [samselikoff/ember-cli-mirage#989]
The `association` factory helper is documented [on ember-cli-mirage.com](http://www.ember-cli-mirage.com/docs/v0.2.x/factories/#factories-and-relationships) under the 0.2.x docs, but doesn't exist in the latest release, 0.2.4.

I think the website should only be updated when a release is made.

Will `association()` be available in 0.2.5? Or 0.3.0?

**Comment by samselikoff** [comment]
Whoops - good catch. 0.2.5

**Comment by samselikoff** [comment]
Could you add a note? We did this in 1.x to let folks know if a feature was added in a later version.

It looks like this

```
<aside class='Docs-page__aside'>
  <p>Faker was added in version 0.1.3.</p>
</aside>
```

If you add that right to the top of the `Factories and relationships` section that would be very helpful. "The association helper was added in version 0.2.5."

**Comment by courajs** [comment]
I've been having trouble getting jekyll working to preview this change, but I'll add it when I get a chance.

I've been looking into `git subtree` a little bit. Would you be open to maintaining a `docs` folder on master, and when cutting a new release have it automatically pushed into the gh-pages `docs` folder with the new version number? That way ember-cli-mirage.com would only be updated when new releases are made, and we would avoid this kind of issue in the future.

**Comment by samselikoff** [comment]
Yes... I don't even think we need subtree, I believe gh pages now supports a docs folder on master. Could you look into it? It would be extremely helpful!

**Comment by samselikoff** [comment]
Also I'd like to move docs to the dummy Ember app in master, but that's a bigger project.

**Comment by samselikoff** [comment]
Will be working on this in future version of the docs. Sorry again for the annoyance here!
