### ISSUE TITLE
Inconsistent APIs for`.create()` and `.update()` in regards to `hasMany` relationships

### ISSUE THREAD

**Issue by Herriau** [samselikoff/ember-cli-mirage#990]
It seems that `.create()` expects hasMany relationships to be defined as an array of related model instances, e.g:

```javascript
let post1 = server.create('post', {...}),
    post2 = server.create('post', {...});

server.create('user', {
    posts: [post1, post2]
})
```

Whereas `.update()` expects hasMany relationships to be passed in as `Collection` objects, e.g:

```javascript
let post1 = server.create('post', {...}),
    post2 = server.create('post', {...}),
    user = server.create('user', {...});

user.update({
    posts: new Collection('post', [post1, post2])
})
``` 

This is by the way not documented anywhere. The documentation conveniently only discusses of the more straightforward `belongsTo` relationship.

**Comment by Herriau** [comment]
Actually it seems like `.update()` doesn't work at all with hasMany relationships...

**Comment by Herriau** [comment]
Actually it seems like `.create()` doesn't work properly either with hasMany relationships: If I have:

```
let post1 = server.create('post', {...}),
    post2 = server.create('post', {...});

let user1 = server.create('user', {
    posts: [post1, post2]
}),

let user2 = server.create('user', {}),
```

`user1` and `user2` are now both serialized with:

```
"relationships": {
    "posts": {
        "data": [{"type": "posts", id: "1"}, {"type": "posts", id: "2"}]
    },
}
```

instead of just `user1`.

Alright this is probably enough reasons for me to abandon ember-mirage at this point 😣

**Comment by samselikoff** [comment]
I can see why this is frustrating. Which version of Mirage are you on? There were some improvements made in the 0-3 beta series. You can read more and see some examples [in this blog post](http://www.ember-cli-mirage.com/blog/2017/01/09/0-3-0-beta-series/).

The ORM in 0-2 was incomplete - turned out to be hard to get all of these cases working correctly. I think we're closer.

You can look at the [one-to-many](https://ember-twiddle.com/5031fb20898b277fa6aea8fe89571148?openFiles=mirage.scenarios.default.js%2C) example from the post to see how I normally create relationships.

The reason for the inconsistency in the array versus `Collection` is that, `server.create` actually goes through the Factory layer, whereas `model.update` is the "lower-level" ORM layer.

**Comment by Herriau** [comment]
@samselikoff I was indeed on 0.2 but I just gave a shot to the beta version you mentioned. It is much much more stable, which brought back my faith in ember-mirage, so thank you for pointing this out. 

I initially ran into additional issues, as I had several one-way reflexive hasMany associations, where I'd essentially either get duplicate entries or a plain and simple crash after several `.update()`, but all these problems went away after I declared `{inverse: null}` on these associations. It would have been nice to get a warning about this.

**Comment by samselikoff** [comment]
Interesting. Glad you're finding 0-3 useful.

I believe the behavior matches Ember Data - if you `user: belongsTo('user')` on a `user` model, by default that sets up an implicit inverse.

**Comment by Herriau** [comment]
@samselikoff There are no `belongsTo` associations involved here. Essentially just:

```
// mirage/models/post.js
export default Model.extend({
    parents: hasMany('post'),
    siblings: hasMany('post'),
    related: hasMany('post')
})
```

If I do this with Ember Data, at least it will warn me that the inverse could not be determined as this is an ambiguous definition, whereas Mirage just silently ignores the problem.

**Comment by samselikoff** [comment]
Ah yes - thank you. You're right that I need to add warnings for ambiguous schema definitions.

In Ember Data you need to specify null inverse in this case though, right?

**Comment by Herriau** [comment]
Yes correct, either null inverse for one way, or explicit inverse for two way.

**Comment by samselikoff** [comment]
Great, added a new issue to track this: https://github.com/samselikoff/ember-cli-mirage/issues/1065
