### ISSUE TITLE
Mirage add-on in master app?

### ISSUE THREAD

**Issue by mark-a-roberts** [samselikoff/ember-cli-mirage#991]
I have an API and want to have a mirage mock server for the api in an addon.

Using the various install and generate functions I end up with models, fixtures and factories in tests/dummy/mirage, and some export statements in **app/mirage-models**, **app/mirage-fixtures**, **app/mirage-factories** etc.

I also want to have the same mock server functionality when my addon is built into my master app. So I include mirage into my master app.

My question is what do I have to do in order to get the mirage addon files working in the master app?

I have tried copying the mirage config.js file from the addon into the master, but when the application runs, I get...

_The route handler for /xxx/1234?include=yyy is trying to access xxx model, but that model doesn't exist._

Should the mirage-models/fixtures etc directories it creates in the app folder for the addon really be **app/mirage/models**, **app/mirage/fixtures** etc?

**Comment by samselikoff** [comment]
Check out https://github.com/samselikoff/ember-cli-mirage/issues/920 for how some folks have solved this. We need more robust addon support, unfortunately the story right now is not complete.

**Comment by mark-a-roberts** [comment]
Thanks for the reply - I'm grateful you got back quick. 

What is confusing is that ember g mirage-factory creates export files in the app directory, which is misleading as mirage support for add-ons is incomplete.

So what I did as a temporary fix is the following

Create mirage model, factory, fixture and serialiser directories and the in the addon directory instead of in tests/dummy.

Create matching files in the app tree which export the files in the addon directory.

e.g **myAddon/app/mirage/models/postcode:**

`export { default } from 'myAddon/mirage/models/postcode';

In the main application, install mirage as normal, and add the mirage/scenarios and mirage/serialisers directories.


`

**Comment by mupkoo** [comment]
I got misled by this as well. :)

My solution includes creating a `mirage-support` folder in the root of my addon and then modify the `index.js` file so it merges that folder with the one found in the consuming app.

```javascript
/* eslint-env node */
'use strict';

var path = require('path');
var MergeTrees = require('broccoli-merge-trees');
var Funnel = require('broccoli-funnel');

module.exports = {
  name: 'shuttle',

  included(app) {
    this.app = app;
    this.addonConfig = this.app.project.config(app.env)['ember-cli-mirage'] || {};
    this.mirageSupportDirectory = path.join(this.root, 'mirage-support');

    this._super.included.apply(this, arguments);
  },

  treeForApp(appTree) {
    var trees = [appTree];

    if (this._shouldIncludeMirageFiles()) {
      trees.push(new Funnel(this.mirageSupportDirectory, {
        destDir: 'mirage'
      }));
    }

    return new MergeTrees(trees, { overwrite: true });
  },

  _shouldIncludeMirageFiles() {
    if (process.env.EMBER_CLI_FASTBOOT) { return false; }

    var enabledInProd = this.app.env === 'production' && this.addonConfig.enabled;
    var explicitExcludeFiles = this.addonConfig.excludeFilesFromBuild;

    return enabledInProd || (this.app.env !== 'production' && explicitExcludeFiles !== true);
  }
};
```

**Comment by samselikoff** [comment]
Closing this as we've moved the feature to the Roadmap. Trying to clean up some issues.

Feel free to discuss ad-hoc solutions here until someone has cycles to work on it.

**Comment by bartocc** [comment]
@samselikoff could you point me to the above mentioned Roadmap please ?

**Comment by samselikoff** [comment]
Going to try using Canny for feature requests: https://ember-cli-mirage.canny.io/feature-requests
